### ISSUE TITLE
Pay for failed order didn't check the product stock status

### ISSUE THREAD

**Issue by imknight** [woocommerce/woocommerce#10189]
if I try to pay for a Failed Order but the product is already out of stock, the stock will become -1 and allow me to pay through the payment gateway.

**Comment by mikejolley** [comment]
Looks like the "pay" page has no validation of items since the order is already created, and this doesn't go through the cart page.

There are 2 possible solutions to this;

1. We do stock reduction on items regardless of payment status, and only restore stock when the order is cancelled by an admin. We would need a timeout of failed orders to automatically cancel them after a certain amount of time.

2. We add validation rules to order items, however, these to me sounds like a difficult approach and could cause other issues.

I'd be happy for 1, but as this is a larger item I'm moving milestone to 2.7 and asking for dev feedback.

@claudiosmweb

**Comment by mikejolley** [comment]
Related to #10764. Both should use regular checkout if we can.
