### ISSUE TITLE
Frontend Common JS module for WooCommerce scripts and refactoring

### ISSUE THREAD

**Issue by EmilEriksen** [woocommerce/woocommerce#10679]
The frontend JS code could be kept a lot more DRY and more easily maintainable if a global object was introduced. Take for instance getting the endpoint URL for AJAX. Right now a simple [search](https://github.com/woothemes/woocommerce/search?utf8=%E2%9C%93&q=%25%25endpoint%25%25) returns 7 different files where variations of this function is used. It would make a lot more sense to have a function like this in one place (e.g. window.WooCommerce).

Additionally each JS file could be converted to an object and exported to the WooCommerce object (e.g. for cart.js window.WooCommerce.cart). This would allow for much easier extensibility. I recently found myself copying around 40% of cart-fragments.js when AJAXifying mini cart item removal.

If each object also had an init function that was then called in a separate file when everything is loaded it would also be possible to redefine any functions used by i.e. cart.js before they were executed allowing for even greater customization. This might cause some issues though and I'm not sure how it would impact load time since all WC files would have to be loaded before executing any of them.

**Comment by mikejolley** [comment]
@coderkevin any thoughts on this? Globals worse idea?

**Comment by coderkevin** [comment]
I wonder if we could better satisfy these dependencies by writing a CommonJS module for the parts that get repeated. Then any code that needs it can simply require() it. Since we already have a compilation step in grunt, it wouldn't add any additional steps to integrate. Doing this in a module would be cleaner than adding to the many global variables under window.

**Comment by mikejolley** [comment]
@coderkevin yeah thats what I thought you'd suggest :) I'll move to 2.7 and assign you if you don't mind B)

**Comment by coderkevin** [comment]
Sounds good. @EmilEriksen would you like to mention the parts that you feel could be in such a module?

**Comment by EmilEriksen** [comment]
From my experience this is some common functionality, I've run into:

* Block and unblock UI elements
* Animations
  * There are slide animations for coupons, payment methods, shipping methods and probably elsewhere. Ideally these animations would be replaced with CSS but if not maybe they should be functions with common properties for UI consistency
* Getting an endpoint URL as mentioned in my original post
* Function for getting the AJAX URL (no need to have an ajax_url param for each file)
* Function for replacing fragments
* HTML5 storage test
* Functions for adding and removing notices

As I also mentioned in the original post, I've often found myself needing functions from files such as cart.js (since it's been AJAXified), cart-fragments.js and checkout.js. when modifying templates. Idk if this is beyond the scope of a CommonJS module but these pages have a lot of stuff relying on javascript and this means you can't really move stuff around very easily or change the markup without some JS failing.

**Comment by coderkevin** [comment]
@EmilEriksen Thanks for the quick feedback! I think we can put whatever we want in modules to make it easier to use. It does take an extra build step to use, but we'll just add that to grunt. Putting this stuff into modules also eliminates issues with including the scripts twice, because the require functionality will make sure each script isn't included twice.

**Comment by mikejolley** [comment]
This issue should simply be treated as a refactor and tidyup of frontend scripts. 

I don't think requiring modules during build will work for us because of the way scripts get enqueued in WordPress. Scripts could however be split up so the common things (such as blocking and unblocking elements) can be enqueued as script dependencies and used in global scope. This could be a single common script, or several for each feature?

Parts I can see which could be split:

- [ ] blocking/unblocking (blockUI)
- [ ] getting endpoints and other URLs e.g. ajax URL
- [ ] Testing for supported features e.g. html5, localstorage
- [ ] Getting settings, such as currency format, from one place

Some of these replaced passed in params.

Other items:

- [ ] The woocommerce.js file could also be replaced with scripts per feature which get enqueued only when needed, e.g. the orderby dropdown code could be enqueued as part of the orderby dropdown template file. 
- [ ] add-to-cart-variation.js uses a prototype pattern which is more organised than the more procedural scripts such as geolocation.js and add-to-cart.js. We should consider using this in other places.

**Comment by mikejolley** [comment]
This hasn't had much traction and doesn't seem a priority, nor of much benefit if you ignore personal preferences. Script splitting is occurring naturally, as is implementing the prototype pattern across frontend scripts. We should continue with that process.
