### ISSUE TITLE
Add consistently named classes to all WooCommerce markup

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#10674]
Our CSS classes are messy as there's no consistent naming convention. Whilst removing the old classes would cause havoc, adding new ones would be an enhancement and would provide consistency and familiarity. 

New classes should follow our [current guidelines](https://github.com/woocommerce/woocommerce/wiki/CSS-SASS-coding-guidelines-and-naming-conventions).

Removing all the old classes has massive implications and is still tbd in a separate issue/discussion.

When adding new classes, let's add them _before_ the old ones. IE `<div class="woocommerce-info">` becomes `<div class="woocommerce-message woocommerce-message--info woocommerce-info">`. Hopefully that will encourage folks new to WooCommerce to use our new class names.

**Comment by revxx14** [comment]
You could add an option in the back-end "Include legacy classes." This would be turned on by default, and turning it off would remove all the cruft left behind by the old class names. Minor thing, but it'd be nice to trim down the HTML a bit.

**Comment by jameskoster** [comment]
That would involve having a filter on every single class attribute we specify, or removing the old classes via js on page load. Neither are worth it imo.

**Comment by jameskoster** [comment]
Discussed this again recently and decided it makes sense to use the naming conventions in Calypso as a foundation https://wpcalypso.wordpress.com/devdocs/docs/coding-guidelines/css.md

Why?

1. Consistency
2. Familiarity 
3. Proven

We'll need to tweak this slightly as we're not using React components - this will be added to the wiki.

It also means revisiting some elements that have already been updated to use Suit, but the trade-off is worth it.

**Comment by EmilEriksen** [comment]
Has any progress been made here? I'd love to see it. I've been reading a lot about CSS best practices lately and would really like to start incorporating some kind of standard into my workflow. 

I've read the wiki page and I noticed the example might cause some confusion. The way "loop-product" is referred to as a nested block makes it sound like the class names should reflect the DOM-structure. I understand that "loop-product" has its name because there are multiple different presentations of products (e.g. "singular-product"). The way the example is presented makes it sound like "loop" is added since it's a child of "loop" though. So say I have .some-block I wanted to add as a child element to .loop-product it makes me think its class name should be .loop-product-some-block.

**Comment by jameskoster** [comment]
Progress has been made but nothing groundbreaking yet as this isn't due til 2.8.

The product loops is tricky and isn't set in stone yet.

> The way the example is presented makes it sound like "loop" is added since it's a child of "loop" though.

Is _is_ a child of the `.woocommerce-loop` block.

> So say I have .some-block I wanted to add as a child element to .loop-product it makes me think its class name should be .loop-product-some-block.

This all depends on the block you're adding. If it only applies to product loops then that is the class name you'd use. But in that case an element would probably make more sense. Otherwise you can just use `.woocommerce-some-block`.

**Comment by EmilEriksen** [comment]
I get what you're saying but I'm not sure it's a good idea to name a block after any parent block even though it's only used in that context. I think you'd run into a lot of the same [issues](https://en.bem.info/methodology/faq/#why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2) you would if you named nested elements like ´.block__elem__child-of-elem´. Isn't that also exactly what defines an element as well - it being dependent on its parent block? So it might as well be an element in that case. Therefore `.woocommerce-loop-product` should not include "loop" because it's its' parent but because it's a product block of the type "loop".

Anyway the example makes me think that if I wanted to add a block element as a child to another block, I should prefix its' class name with the parents' one. E.g. if I wanted to add a generic `.button` to `.woocommerce-loop-product` I should call it `.woocommerce-loop-product-button` but maybe that's just me.

**Comment by jameskoster** [comment]
Ah, I understand your original point now. To re-affirm what I said, product loops are tricky. Actually, whilst `.woocommerce-loop-product` is technically a child of `.woocommerce-loop` that's not the reason for choosing that class name. Like you said in your original post, `.woocommerce-product` isn't accurate enough. Is it a product on the cart? In a widget? The single product page? It needs to be more specific and having things like `.woocommerce-loop-product`, `.woocommerce-single-product`, `.woocommerce-cart-product` makes sense to me.

A possible alternative would be `.woocommerce-product-loop`, .woocommerce-product-single`, `.woocommerce-product-cart`... but they're by no means perfect either.

Definitely open to suggestions for this specific case.

**Comment by EmilEriksen** [comment]
Yes exactly. I don't disagree with that naming pattern at all - I don't have a better suggestion. I was just trying to say that the specific example on the wiki might cause some confusion because it seems like `.woocommerce-loop-product` is named the way it is because it's a child of `.woocommerce-loop` in the DOM structure and not because it's a product of the type "loop" :)

**Comment by jameskoster** [comment]
I'll add a note to the wiki xD

**Comment by rellect** [comment]
If it's not too late, is it have to be '.woocommerce-'?
It's quite long.. I'd prefer '.wc-' or '.woo-'

**Comment by jameskoster** [comment]
It's too late :p 

We decided `.wc-` or `.woo-` presented too much risk for conflict.

**Comment by mikejolley** [comment]
This is ongoing rather than a fix-once issue due to bw compat.

> New classes should follow our current guidelines.

Found here https://github.com/woocommerce/woocommerce/wiki/CSS-SASS-coding-guidelines-and-naming-conventions
