### ISSUE TITLE
"order-pay" not updated, when different payment method selected

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#10764]
## EXPLANATION OF THE ISSUE

Using the standard checkout it is possible (through plugins) to update the checkout (trigger: "update_checkout") on the selected payment method. For instance adding an additional fee.

Unfortunately this doesn't work on the "order-pay". There doesn't seem to be a way to trigger something, when the payment method is change.

Background: Sometimes it is necessary to create orders manually for customers and just send them the link for final payment.
## STEPS TO REPRODUCE THE ISSUE
1. Use some plugin to add additional fees for the selected payment method. I tried ["WooCommerce Germanized"](https://wordpress.org/plugins/woocommerce-germanized/). 
2. It is working at checkout but not on order-pay.

**Comment by mikejolley** [comment]
That sounds correct as of now. The order pay page is 'fixed' in that it cannot update the order values from what was previously created. There are no ajax events on this page.

Also important to note, the order pay page pays for an order, not the cart, which is why the values and order totals etc are fixed and not updatable.

Adding ajax update events would require a full rewrite of this page, even though core doesn't actually use this feature at present. So rather than rewrite this now, i'm going to suggest we leave this as #wontfix short term, but look at reworking the entire pay flow when we tackle #10672, if that is possible without disrupting plugins like subscriptions which I believe use it.

One possible solution would be to populate the cart and use regular checkout, rather than using the order pay page. i.e. populate the cart contents, set the order ID in the session, and redirect user to checkout.

If they pay, the order is updated.
If they leave, unset the cart.

Then we can keep the one flow and not have to manage a separate pay flow outside of regular checkout.

**Comment by scrobbleme** [comment]
Hello Mike, thanks for your reply.

The problem with loading the cart is, that customers will then be able to alter the cart. (or is there a way to not let them edit it?). Which we don't want (customers just should pay their proposal).

Maybe it would be easier to have another page "cart-pay", which is somewhere between checkout and order pay.

At least it would be great to be able to collect transaction fees at this point of payment.

**Comment by scrobbleme** [comment]
Found another plugin, which might be affected by this. Just had a quick look into their code, and I think they might have the same problem, when addressing this.

Generally the specific endpoints shouldn't behave different in different views :|

https://github.com/angelleye/paypal-woocommerce/issues/473

**Comment by mikejolley** [comment]
This should be done with https://github.com/woocommerce/woocommerce/issues/10672
