### ISSUE TITLE
Improve adding fees

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#11142]
1. In [class-wc-cart.php](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-cart.php#L1961) the fees id is directly derived from the name. 
   This doesn't make it possible to dynamically changes the fees name to something more descriptive without changing/breaking the id as well.
2. ~~There is no method for removing fees~~
3. ~~There is no method for updating fees~~
4. Add ability to add additional meta data to fees
5. Also actions and/or filters might be missing here

**Comment by mikejolley** [comment]
Fees are not persistent, and you have access to fees during woocommerce_cart_calculate_fees hook if you need to remove or adjust after the fact. Since core doesn't use fees, your code adding the fees would be the only thing working with them.

**Comment by scrobbleme** [comment]
Thanks Mike, so we can skip the remove/updating methods.

But this still doesn't allow to set a different title for instance, which for instance is shown to the customer ;)

Our case: We use a plugin, where we have defined 200+ fee rules (yes, it has to be so many as the plugin doesn't allow any grouping). Now I tried to unify the name (through the_title filter), so that the customer always sees the same name, independly, which rule was applied. But unfortunately this is not possible (I wasn't able to figure out why). Just had the chance to introspect fee handling a little more.

A possible workaround would be to iterate over every rule and fee and change only the name directly within the array. Eventually I have to iterate as I can't store any type of unique reference (id) for the fee to make it much easier to check if this is really the fee I want to change the name for.

Another problem might be multilingual environments, where a fee was added to the cart and then the customer changed its language and the fees title with this. I don't know what will happen then. Might be a plugin author problem as well.

This also might be problem with the generated order. There are already less information about fees. So for plugin authors there is no chance to recalculate fees when clicking "Calculate totals" within the administration, as simple name changes would break everything.

**Comment by mikejolley** [comment]
I've re-reviewed the code behind this and don't think we need to adjust or allow manually defined IDs.

The reason is that each load, `woocommerce_cart_calculate_fees` is what defines the fees for the cart.

This means that on each load, a plugin utilising fees will need to send them to the cart for display and calculation.

If the language were to change, or the name, it would affect the current page load only.

Therefore, if an ID list was needed to track different fees, it could be maintained 100% in the custom plugin which then sends the final list of fees to WooCommerce. Then on next page load, those fees are gone until send again by the plugin.

Hope this makes sense :)
