### ISSUE TITLE
Add address settings for local pickup for tax calculations

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#11595]
## EXPLANATION OF THE ISSUE

Currently if Local Pickup is used as a shipping method, the shop Base address is what is used for tax calculations. The Base address is only as accurate as a country and state/territory, and not as defined as a city or postal code. If tax settings are include postal codes and/or cities, then taxes may not be calculated correctly.

I believe the Local Pickup shipping option should have address fields within it where the user can define the address of their physical location. This address would then be used for accurate tax calculations.

This was loosely mentioned here:
http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/3044456--local-pickup-option-need-to-be-able-to-add-in-sa

**Comment by kristinaplauche** [comment]
This ticket [#455267](https://woothemes.zendesk.com/agent/tickets/455267)had problems related to having no zipcode set for the base location. Tax is set to the zipcode level, so no tax was calculated when Local Pickup was selected.

**Comment by DanielSantoro** [comment]
Another follow-up/related issue - Ticket 488611.

When the local ZIP code is using the local rates and shipping is selected, it all works well, but when switching to Local Pickup it goes to state tax which is incorrect.

I set up a demo of the bug on a test site. Here is the process to see it for yourself:

Add an item to the cart - this is a good example: https://wpsantoro.mystagingwebsite.com/product/ninja-silhouette-2/

Set your address to **United States > Ohio > 45210**. This is outside of the zip codes I've set up to allow local pickup, so you'll see the State Tax appear, with USPS options. So far, so good.

Now, set your address to **United States > Ohio > 45219**. This should enable the Local Pickup. When you have Shipping selected you'll see "Cincinnati Tax" with an increased amount, but if you choose Local Pickup it reduces to a the State Tax value. This means incorrect tax is being chosen, because tax has to be based off of the ZIP code of the store location.

-----

It seems like either in the Local Pickup or the General settings, adding a ZIP code to the shop base address would give us something to fix this issue. Any ideas?

**Comment by mikejolley** [comment]
I wonder if we should inherit anything from the zone here?

**Comment by DanielSantoro** [comment]
I'd say it would be a quicker solution for the user to establish their ZIP code during setup as one of the General Settings (like how they choose their country). Then we'd have a record to use across any plugins that might need it like UPS/USPS, etc. We'd need them to look up what their local tax rate is in the wizard though (which just has states at the moment) - for me, sales tax is 5.75% in Ohio and then an additional 1% for the county for 6.75% total: http://www.salestaxstates.com/sales-tax-calculator-ohio-cincinnati-45245

That said, if we add a ZIP code per zone and somehow get shipping methods to use that instead of global settings defined in the plugin, then we could open a door to allowing people to use multiple shipping locations which is asked pretty commonly (i.e. a user wanting to ship from their Canada warehouse to Canadian Addresses and from their store location to US addresses).

Thinking out loud.

**Comment by mikejolley** [comment]
This issue needs:

1. Base zip code exposed in the UI, like state and country
2. This zip should be used for base tax calculations (should work once get base location returns zip code too)
3. Allow local pickup to define country/state/zip for pickup also, which should be used for taxes if local pickup method is selected (this will be the most tricky aspect of the issue).

**Comment by mikejolley** [comment]
We're adding more specific base tax location separate to this issue which will actually resolve. Should be ~3.2. @allendav was going to send a PR.
