### ISSUE TITLE
Shipping Zones - UX Improvements

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#11639]
Shipping zones have been in the wild for a while now, and there are two common problems that I often see come up in support for them. Finding a way to make things a bit more clear in these two areas could help a lot towards first time user experiences.

1) How can I remove a shipping method from a zone? Or, how can I disable the worldwide zone?

Can't say for sure, but I'm guessing most users stay on the zone overview screen and never need to click into an actual zone. So when the need comes to remove a method, they get stumped. Currently, you need to click on one of these two links to do so, the second of which only appears on hover: http://cld.wthms.co/9fhp/JayoVXKs. Once you do that, you then need to hover over the method name to see the delete link.

Possible solutions:

- Change the terminology of the "view" link to something more clear, signifying you can delete and re-arrange shipping methods on the next page. This is particularly confusing I believe, as the "edit" link beside it is only used for editing the zone's name/regions.

- The "view link" could be permanently displayed (not just on hover), and the link on the shipping zone name could be removed. This should draw more attention to the secondary link.

- Force users to go to the shipping zone instance screen to do any sort of zone editing (even adding shipping methods). Then they know where to go when it comes time to delete and re-arrange. A big bonus to this is that the "pop-up" settings for methods will be used a lot more.

If we did the last item above, the last column could also be better used to re-direct users to the second shipping zone screen: http://cld.wthms.co/Ku0D/5cKdaEJp. The "add method" icon can redirect to the edit zone screen, and when clicking to edit a method from here - the pop-up version of the method settings could appear within the zone page. So when it's closed/saved, users find themselves where they need to be to also delete/arrange that zone's methods.

_________

2) My shipping zones aren't working. Only one method is appearing at checkout.

This question comes in a lot of different forms, but the underlining problem is the mis-understanding of how zones work. Specifically how only one zone will be matched and used at checkout, starting from the top. I see variations of this quite a bit: http://cld.wthms.co/8HJ8/2zn1SGC2.

Possible solution:

- If two shipping zones have exactly the same matching regions, display a notice of some sort.

- Explain or better signify that only one zone will be used at checkout, and that matching starts from the top down. Is it possible to programmatically check against something like this: http://cld.wthms.co/B3R7/3dnG49Th - where a zone further down has a more specific query to a certain region than one above it?

- Add some more prominent inline documentation regarding how zones work.

**Comment by mikejolley** [comment]
@jameskoster can you review the above?

**Comment by jameskoster** [comment]
@mikejolley @WPprodigy are these two items the priority? Or do we need to do a full review?

For the first issue, forcing users into the edit zone screen is probably going to be our best bet purely because it is more in keeping with the rest of our current interface. We'd obviously need to include the region selection input on that screen as well if we do.

The action links are a mess, I agree. Let's get rid of that inline edit feature. 'View' then becomes 'Edit' or perhaps 'Manage' (and takes you to the edit zone screen). 'Remove' stays. No more adding methods on this screen.

Removing inline editing probably means we should change how zones are added as well, but before I touch on that...

For the second issue, yeah... this is also a bit of a mess. We should alert folks who try to create zones that cover exactly the same regions as an existing zone. There's no case for having two, right?

> Explain or better signify that only one zone will be used at checkout, and that matching starts from the top down.

I'm probably being dumb but why does the ordering have any impact on which zone's methods are offered? Shouldn't methods just be offered from the closest matching zone? So in [this](http://cld.wthms.co/B3R7/3dnG49Th) example if my address is in Illinois I get free shipping, if it's any other US state I get the US flat rate, if it's outside the US I get the rest of the world rates?

As for adding new zones, I feel like we should probably ditch the inline adding. So clicking 'Add shipping zone' would take you to the edit zone screen mentioned before. On that screen you add the zone title, define the regions and add the methods. Editing the methods works the same as it does currently.

Thoughts?

**Comment by WPprodigy** [comment]
> So [in this](http://cld.wthms.co/B3R7/3dnG49Th) example if my address is in Illinois I get free shipping, if it's any other US state I get the US flat rate

In that set-up, the first zone would be matched for Illinois (it wouldn't look any further) and only flat rate would be returned. It has to work from top to bottom - that way you can provide fallbacks such as the worldwide zone.

> As for adding new zones, I feel like we should probably ditch the inline adding.

I'm definitely in favor of moving most functionality over to the edit zone screen, but I feel like adding/removing zones should stay possible on the overview page. It would add some consistency.

Shipping zones overview page: Add, remove, and re-arrange shipping zones.
Individual shipping zone: Add, remove, edit, and re-arrange shipping methods.

**Comment by jameskoster** [comment]
> In that set-up, the first zone would be matched for Illinois (it wouldn't look any further) and only flat rate would be returned. It has to work from top to bottom - that way you can provide fallbacks such as the worldwide zone.

Ah yeah, makes sense. I can definitely see why this is confusing. It's not really a simple thing to explain succinctly via text alone though. Especially when there's already so much else going on on that screen. 

What if, on the empty zones state we include the Zones video? Hopefully the majority of people would watch that and it'd at least make them aware of the feature.

Other than that all I can really think of would be using pointers to guide you through the whole interface.

> but I feel like adding/removing zones should stay possible on the overview page. It would add some consistency.

What are we using for our consistency comparison? I'm looking at other areas of wp-admin (coupons, orders, products, posts, pages). Removing would be consistent with those, but not adding. The flow of adding zones currently certainly feels clunky. 

Another benefit of going to the 'edit' screen to add the zone highlights that the screen actually exists (you mentioned that folks struggle to find this). 

To me that is more consistent with the experience of 'adding' stuff in wp. I think that's what we should aim for. Clearly the significant differences in the Zones UX is throwing people off.

**Comment by WPprodigy** [comment]
> What if, on the empty zones state we include the Zones video?

That could help, but definitely won't be a catch-all. Those who won't watch a video will probably dislike pointers as well. I'm thinking some inline error reporting would be best for the "self help" type. Having a zone turn red somewhere if it has exactly the same region for example, or alerting them if a more specific zone is found under a matching zone (Illinois zone underneath a US zone).

> To me that is more consistent with the experience of 'adding' stuff in wp. I think that's what we should aim for. Clearly the significant differences in the Zones UX is throwing people off.

True. I was thinking just within zones, but to follow suit for the rest of WC admin - your proposition does make more sense.

**Comment by jameskoster** [comment]
> Having a zone turn red somewhere if it has exactly the same region for example, or alerting them if a more specific zone is found under a matching zone (Illinois zone underneath a US zone)

If it's possible to detect this, shouldn't we just move it automatically?

**Comment by bekarice** [comment]
A quick thought: why not always match the most specific zone rather than trying to use menu order as priority? So if a region contains any postcode(s), then this zone is always matched first, regardless of menu order. This way, if I have these zones in this order:

 - USA
 - Rest of the World
 - Pennsylvania (no postcodes)
 - Pennsylvania (has postcodes, let's say Philadelphia in this case)

PA with postcodes would always be the zone I check first, so any customer in Philadelphia will automatically match that zone rather than the USA zone or the generic "Pennsylvania" zone (no postcodes). As a merchant, I think that automatically selecting the "best" / most specific zone is easy to understand.

Menu order can then be a fallback if two zones have the same postcode coverage. While unlikely, you could potentially have one zone with `191*` as the postcode, and another with `19131` as the postcode, so WC would just grab the first zone with a matching postcode. Or perhaps this can be a place where a notification is thrown, as checking an intersection between the postcodes of different zones may be a simpler check.

**Comment by jameskoster** [comment]
@bekarice that's exactly what I _expected_ would happen.

**Comment by mikejolley** [comment]
Could base it on https://github.com/woothemes/woocommerce/pull/11540

**Comment by mikejolley** [comment]
Actually thats not going to work @bekarice @jameskoster. Zones can have multiple countries/states. It's easy with taxes because they are limited to one country.

**Comment by bekarice** [comment]
> Zones can have multiple countries/states. It's easy with taxes because they are limited to one country.

True, I guess I wasn't considering automatic sorting on the merchant side though, moreso the logic around getting available methods for the cart. Here's a more expanded scenario I was thinking.

A store has pickup locations in Toronto, CA and Boston, USA, so they'll offer pickup for these zones, and Shipping throughout the USA and Canada.

- zone 1: USA - flat rate $5, free shipping
- zone 2: CA - flat rate $6, free shipping
- zone 3: Canada & USA - local pickup for postcodes `M4B*` and `021*`, free shipping
- zone 4: Rest of the world - flat rate $10

When any customer checks out, since zone 3 contains postcodes, we'd run through that array to see if they match before checking any other zones, regardless of menu order. As the customer can only match one of the postcodes, it doesn't matter if there are multiple ones / multiple countries listed. If matched, these rates are offered.

If not matched, then we check rates in the following order:

1. Go through the zones that have a state / province set to see if they match (this can be done in menu order since they're of equal specificity)
1. Go through zones that have a country specified (again, in menu order)
1. If no zones match based on postcode, province / state, or country, then we'd fall back to the rest of the world zone.

So for the following customers:

 - A CA customer in Toronto will be offered free shipping + local pickup
 - A CA customer in Vancouver will be offered CA flat rates
 - A US customer in Boston is offered free shipping and local pickup
 - A US customer in Texas is offered US flat rate
 - A customer in the UK is offered the "rest of the world" rates

Which would be the same behavior as the manual priority now, just trying to automate it a bit / save people from themselves. That would leave the the "non-stacking" behavior (only one zone applies at a time) as the only thing required to explain.

Now I'm not sure how efficient this set of checks would be, but defaulting to specificity and falling back to menu order might be something that could be considered. 

I know it's not quite the same, but that's what we do with Memberships content restriction rules (the most specific rules, ie post rules, are applied before more generic rules are checked, like a category or post type rule -- the menu order for the rules list is only used if there are two, equally-specific rules that could apply like both a cat and tag rule).

**Comment by leewillis77** [comment]
Hi all; 

I'm just working on porting my shipping plugin over to Shipping Zones and some of the issues I'm having touch on some of the issues raised in this thread. My main issue is around the fact that only one zone is matched and presented at checkout. I think this limits things quite heavily.

> We should alert folks who try to create zones that cover exactly the same regions as an existing zone. There's no case for having two, right?

I actually think there is a strong case for having overlapping zones, consider the following requirement for three different prices
- Standard delivery £5 - available everywhere
- Faster delivery - £10 in UK, £15 to France

As things stand, this involves setting up five flat rates across three zones:

**Zone 1 - UK**
Standard - Flat rate - £5
Faster - Flat rate - £10

**Zone 2 - France**
Standard - Flat rate - £5
Faster - Flat rate - £15

**Zone 3 - RoW**
Standard - Flat rate - £5

Notice how "standard" has to be duplicated in every zone? It'd be great to find some way of avoiding that. Possible suggestions:
- allowing multiple zones to be matched at checkout, special casing RoW to only apply if no other zones match, and introducing an "everywhere" zone that _always_ exists (like RoW) and _always_ matches. In which case the standard rate would only need to be added once, into the "everywhere" zone.
- allowing method instances to be assigned to multiple zones (UI hell?)

I'm sure that's not a simple change, but may address some of the issues people are finding with the usability, and make the system more flexible. I'm not expecting it to be a quick fix - but worth flagging the usability issues with the current system.

**Comment by mikejolley** [comment]
^ that would prevent exclusion based rules or more specific rules.

e.g. I want to offer local pickup locally and nothing else, but UPS across the rest of the country.

**Comment by leewillis77** [comment]
Hi Mike; 

I assume your comments are relating to my suggestion to allow multiple zones to match? If so - I'm not sure it _prevents_ that model - but perhaps makes it more difficult than the current approach.    To achieve your example you'd need to put the UPS method into a zone that doesn't include whatever your definition of "local" is, rather than into "everywhere". That's certainly not easy to setup with the current UI though I guess ...

Do you see issues (UI-aside) for the approach of allowing method instances to be assigned to multiple zones?

**Comment by mikejolley** [comment]
> Do you see issues (UI-aside) for the approach of allowing method instances to be assigned to multiple zones?

Yes, the case I mentioned.

>  I want to offer local pickup locally and nothing else, but UPS across the rest of the country.

You cannot do this with overlapping zones. My postcode is in the UK. I cannot exclude my postcode from the main UK rule, unless I define all other postcodes which is not feasible.

**Comment by leewillis77** [comment]
I'm confused. I made two separate suggestions. The first was to allow multiple zones to be matched at checkout. I get the difficulties with your example under that scheme. 

The second though was to **keep** the current "_only match one zone_" behaviour - but allow a method instance to be assigned to multiple zones to avoid having to duplicate methods. So - to achieve your requirement you'd have the following - which is exactly what you have under the current scheme. 

**Zone 1 - "Mike's postcode"**
Local Pickup

**RoW**
UPS

If you did want to allow UPS to your postcode as well, currently you have to add a separate UPS method instance, and configure it again.

Under my proposal - you could assign the existing UPS method instance that you have for RoW to "Mike's postcode" as well. So, it would be the same instance - just attached to more than one zone.  

To achieve the example I gave earlier - you'd have the following:

**Zone 1 - UK**
Standard - Flat rate - £5
Faster - Flat rate - £10

**Zone 2 - France**
Standard - Flat rate - £5
Faster - Flat rate - £15

**Zone 3 - RoW**
Standard - Flat rate - £5

Rather than having to add three different method instances for Standard shipping (and edit three when prices change etc.) you'd add it once, but then assign it to each of the three zones.

Does that make more sense?

**Comment by mikejolley** [comment]
> The second though was to keep the current "only match one zone" behaviour - but allow a method instance to be assigned to multiple zones to avoid having to duplicate methods. So - to achieve your requirement you'd have the following - which is exactly what you have under the current scheme.

I feel this would make the system more confusing? I mean, editing one and affecting others could lead to undesirable results. I think a duplicate feature might make things more manageable?

**Comment by mikejolley** [comment]
@jay lets chat about this on team day.

**Comment by mikejolley** [comment]
Started on this here https://github.com/woothemes/woocommerce/tree/shipping-zone-ui

**Comment by mindsize** [comment]
What if we were able to duplicate a method from one zone to any number of other zones? That way, you can set up your USPS method once and then assign the same settings to multiple zones, but in the background, have it actually duplicate the method. Something like "Clone to Additional Zones" or "Copy This Method To...?" Fits DRY, doesn't further confuse the already complex feature, just adds more options to make it faster to set up. My general workflow is to define my zones, then define my methods. This would probably cut 15 minutes off of my setup time for an average sized site.

**Comment by mikejolley** [comment]
@mindsize Something I want to add in the future, but want to get this refactored and working first with the adjusted flow beforehand.

Todo.

- [ ] Zones screen - Remove links to methods
- [ ] Zones screen - Remove save button
- [ ] Zones screen - Live update on sort/delete
- [ ] Methods screen - Use 'changes' for name/locations.
