### ISSUE TITLE
Add a system status tool for clearing orphaned variations

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#11979]
We commonly see orphaned variations (variations without parents) created by importers, other plugins, or custom code which can other issues. A system status tool for clearing them out would make handling support and these cases easier.

**Comment by WillBrubaker** [comment]
FWIW this tool exists in Product CSV Import suite - if it's going to be added to WC, does it want to be removed from the CSV import to avoid clashes?

**Comment by coccoinomane** [comment]
Hello,

We use the System Status Tool to remove orphaned variations with success, but we have noticed that while it correctly removes the orphaned variations, **it does not remove post-meta attached to the variation** (ex. `_sku`). 

To reproduce the issue, try importing this CSV file ([test-import.csv.zip](https://github.com/woocommerce/woocommerce/files/1495838/test-import.csv.zip)) with one variable product and four variations. The import of the variable product fails because the corresponding image does not exists, while the four variations are imported correctly.

If you then use the System Status Tool to remove the four orphaned variations, it works, but you will still find the SKUs of the four variations in the post meta table, togther with the other post metas.

If this is the intended behaviour, it seems unconvenient because deleting orphaned variations leaves the DB "dirty", while one would hope it would do a complete job.

Thank you for your attention,
Guido
