### ISSUE TITLE
On the checkout screen where it shows the shipping options, UPS flat rates and local delivery with options, show on screen regardless of their button being ticked or not.

### ISSUE THREAD

**Issue by Daledde** [woocommerce/woocommerce#12000]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by justinshreve** [comment]
Hi @Daledde - I'm not sure what you are asking for here (and you are using the title instead of description box). However, shipping options depend on how your WooCommerce store is configured. GitHub is meant for bugs/enhancement requests so if you need help setting things up, please check out the following URLs:

* https://docs.woocommerce.com/ (for customers)
* https://wordpress.org/support/plugin/woocommerce (for all WooCommerce users).
