### ISSUE TITLE
About Variant filter for specific styles

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#12040]
Hello,

I wonder why Woo doesn't have variant filter for specific products. 
For example, I have 2 t-shirts with different size and colors.

When customers choose the first style t-shirt, it will filter available sizes and colors for that t-shirt and show them. The unavailable variants will be hidden. And vice versa.

**Comment by claudiosmweb** [comment]
This happens when have less than 30 variations in the product. When have more than 30 it's displayed all variations and then uses ajax to check if is available. This is necessary if not cause performance issues.

If you want to load more than 30 variations at the same time you can use the filter `woocommerce_ajax_variation_threshold`, here an example of how use: https://gist.github.com/claudiosmweb/6f91ad228c2176b986b2#file-functions-php
But as I said, load several variations will cause performance issues.

**Comment by harkalygergo** [comment]
Claudio’s nickname changed to claudiosanches, so the required link: https://gist.github.com/claudiosanches/6f91ad228c2176b986b2
