### ISSUE TITLE
PHP Warning:  array_unique() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/woocommerce#12052]
## EXPLANATION OF THE ISSUE

Getting PHP warnings on a client's site (providing just one, difference is in timestamp only):

```
[10-Oct-2016 16:23:04 UTC] PHP Warning:  array_unique() expects parameter 1 to be array, null given in /home/somedomain.com/app/plugins/woocommerce/includes/class-wc-query.php on line 395
```

## STEPS TO REPRODUCE THE ISSUE

I can't reproduce, as it's a client site and I don't know the steps.
But according to code: you just need to cast `(array)` for filter results on that line.

---

Using the latest WooCommerce.

**Comment by claudiosmweb** [comment]
Not an issue on WooCommerce, since we expect an array from the filter: https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/class-wc-query.php#L395
So some other plugin is using this filter wrong, since we don't use this filter in core.

**Comment by slaFFik** [comment]
So why not preventing that? 
If you allow to pass `null` where you expect `array` - that's definitely a WooCommerce issue.

**Comment by claudiosmweb** [comment]
>  If you allow to pass null where you expect array - that's definitely a WooCommerce issue.

We don't allow pass `null`, as I said, this expect an `array`. if you are not sending an array is because your are doing it wrong.

And prevent people of doing things wrong?
A little hard, since this will cause errors too.
Like returning `false`.

```
wp> (array) false
=> array(1) {
  [0]=>
  bool(false)
}
```

Better throw an error/warning so people can fix, as opposed to "hide" it and cause unexpected behaviors.
