### ISSUE TITLE
Slow Query on "my-account/orders/" page

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce#12051]
Ticket: 476940

User reports that SQL "my-account/orders/" is taking around 100s to load.

To provide context, user reports hundreds of thousands of orders in DB with orders growing by thousands per day. Hundreds of thousands of rows in ```wp_posts``` and millions of rows in ```wp_postmeta```.

@mikkamp tracked down the SQL query to be:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
INNER JOIN wp_postmeta
ON ( wp_posts.ID = wp_postmeta.post_id )
WHERE 1=1 
AND ( ( ( wp_postmeta.meta_key = '_customer_user'
AND wp_postmeta.meta_value IN ('1') ) ) )
AND wp_posts.post_type IN ('shop_order', 'shop_order_refund')
AND ((wp_posts.post_status = 'wc-pending'
OR wp_posts.post_status = 'wc-processing'
OR wp_posts.post_status = 'wc-on-hold'
OR wp_posts.post_status = 'wc-completed'
OR wp_posts.post_status = 'wc-cancelled'
OR wp_posts.post_status = 'wc-refunded'
OR wp_posts.post_status = 'wc-failed'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 10
```

Following discussion with @mattyza, I'm opening a GitHub issue questioning why we're checking for ```wp_posts.post_status```? Surely we want all orders by default?

Ping me or @mattyza for direct ticket access.

**Comment by mikejolley** [comment]
Seeing as 'post_status' is inside the posts table we're querying, I doubt that part makes much of an impact on this. We need to to avoid querying things like drafts and trashed orders. The list of statuses are the public statuses we need to display.

The actual query is for pagination, but the slowness is caused by the join to postmeta. We *could* hack something like post_author to store data like this, but I don't feel thats a good short term solution and could bite us later. 

As you may know, we're working on CRUD classes in 2.7 to abstract how data is sent to WC by third parties etc. When this is ready/launched we're going to work on a feature plugin to use a custom table for all order data to avoid this issue entirely.

See: https://github.com/woocommerce/woocommerce/issues/10071

It may be rough around the edges to begin since we'll need a new order UI (when we stop using posts) but it will certainly scale better than postmeta.

For now, you can optimise tables (in phpmyadmin), or if needed disable that screen. Not idea I know. 

cc @mattyza @claudiosmweb

**Comment by pucitos** [comment]
You can address the query slowness by creating a composite index. In my system, this approach reduced the response time from about 10 seconds to 0.7 seconds. Here's the SQL command I used:

```CREATE INDEX idx_meta_key_value_post_id ON wp_postmeta (meta_key, meta_value(191), post_id);```

This specifically targets the performance issue by optimizing the database's ability to quickly access the necessary data.
