### ISSUE TITLE
Tax Wrong, possibly the coupon tax

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#12087]
Using Wocommerce 2.6  on Wordpress 4.6.1
Only plugin active is woocommerce and the theme has been set to twenty twelve 

Tax is turned on with a standard tax setup @ 20% 
![tax-setup](https://cloud.githubusercontent.com/assets/11464425/19360753/c1aacd02-9177-11e6-9704-c35827f4685f.png)

Prices Entered With Tax = yes

Coupon has been set up for £5 off as cart discount

Added to the cart is:

- 3x products @ 6.50 (inc vat - variation) 
- 1x product @ 0.20 (inc vat - simple)
- 2x products @ 4.95 (inc vat - variation)

Delivery is non taxable

This is the cart total before coupon is added
![pre-coupon](https://cloud.githubusercontent.com/assets/11464425/19360580/08c1eb36-9177-11e6-8264-c1dfc9c56b53.png)

And this is the cart total after the coupon is added
![coupon-added](https://cloud.githubusercontent.com/assets/11464425/19360581/08c3a16a-9177-11e6-808e-3aaf255d1704.png)

This is the cart total with discount applied, with tax showing
![coupon-added-ex-vat](https://cloud.githubusercontent.com/assets/11464425/19360829/07c0d7f0-9178-11e6-856b-318ff800daf2.png)

As you can see, it's out by 1p.

**Comment by mikejolley** [comment]
Confirmed in 2.6, but fixed in 2.7. https://dl.dropboxusercontent.com/s/alugh2d7lvxs1du/2016-10-14%20at%2013.06.png The changes to resolve rounding issues are too large to apply in a fix release so this needs to wait for the 2.7 release. It's to do with the way discounts are divided between each item to make taxation fair. You can avoid this issue by using % based coupons or product discount coupons.
