### ISSUE TITLE
Can't change woocommerce language

### ISSUE THREAD

**Issue by vytautas-g** [woocommerce/woocommerce#12100]
Hi guys,
I am trying to change language for woocommerce from english to lithuanian. I have tried putting _woocommerce-lt_LT.mo_ file into `wp-content/languages/woocommerce/` and _woocommerce-lt_LT.po_ file to `woocommerce/i18n/languages/` and still no success,
Also, I have tried loco translate, and filling additional line of code `define('WPLANG', 'lt_LT');` but no success.
Please help @mikejolley or someone else I have lost any hope translating my website to lithuanian. 
I'm using newest wordpress with DIVI (elegant themes) theme.

**Comment by claudiosmweb** [comment]
You can find instructions for it in: https://docs.woocommerce.com/document/woocommerce-localization/
But the correct directory is `wp-content/languages/woocommerce/`, you can include the `.po` and `.mo` files inside this directory. But you need to make sure that you are selecting the correct language in the WordPress settings, since `define('WPLANG', 'lt_LT')` is deprecated and should be avoided.
And you can help translate WooCommerce in: https://translate.wordpress.org/locale/lt/default/wp-plugins/woocommerce

**Comment by MurKit** [comment]
I have got it working only after adding also lt_LT.mo and lt_LT.po, as well as admin-lt_LT.mo & admin-lt_LT.po into languages folder. 
I wanted to translate woocommerce first, and then the rest, but should have done vise versa.
