### ISSUE TITLE
Showing the "order received" thank you page even an order was cancelled automatically.

### ISSUE THREAD

**Issue by 70599** [woocommerce/woocommerce#12154]
## EXPLANATION OF THE ISSUE

Showing the "order received" thank you page even an order was cancelled automatically.

## STEPS TO REPRODUCE THE ISSUE

0. Create an order,
0. Forward to the checkout page, but do not pay,
0. Wait for the payment past due(the order was cancelled automatically in the backend),
0. The checkout page redirect to the thank you page automatically.

The thank you page produced by stpes above, looks exactly the same as a normal paid order.

## SYSTEM STATUS REPORT

WC 2.6.6
WP 4.6.1

**Comment by mikejolley** [comment]
Not able to replicate this one. There is no automatic redirect - it just sits there. When you next place order, it creates a new order (since the status is not pending - only pending orders are resumed).

If you have more details on making it happen please respond again, but I cannot seem to make it occur.

**Comment by 70599** [comment]
Automatic redirect maybe caused by my payment gateway plugin.

You can try to refresh the checkout page after the payment past due.
See what happens.

Or open a link like http://yoursite.com/checkout/order-received/[order id that already cancelled].
Also shows "order received" thank you page, but without order details.
