### ISSUE TITLE
Customer can register at checkout with a single character password

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#12213]
When registering for an account at checkout in WooCommerce if the Password is not auto generated and that setting has been disabled a customer can enter a password consisting of a single character.

The indicator displays that the password is weak and should consist of 7 characters but if you continue and pay for the order it accepts less than 7 characters all the way down to a single character and creates the account.

![meur](https://cloud.githubusercontent.com/assets/1190565/19815145/6d527610-9d39-11e6-94e8-723efe3a9f25.png)

Is there anyway would could verify if less than seven and ask the customer to use a stronger password if the strength meter possibly only a suggestion of length but not validated.

**Comment by mikejolley** [comment]
@stuartduff We received a lot of push back when enforcing the validation as shown because of it's impact on conversions. Therefore on checkout it's non-blocking and will allow it. Otherwise payment would be prevented and so on. The warning is still there though so you're at least aware you're a dummy.
