### ISSUE TITLE
wc-ajax=get_variation takes too long 

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#12260]
I noticed that the ?wc-ajax=get_variation with POST method took too long to load when i visited a product page. It took almost 14.09s. How can fix it?

**Comment by mikejolley** [comment]
get_variation query can be reviewed, but I'm not sure if it can be optimised further.

**Comment by mikejolley** [comment]
With post meta this cannot be improved much more - but we can look at this when we redesign variations.

**Comment by kevin25** [comment]
This should be optimize. Woo is fast with single product but it's really slow with variants.

**Comment by berzley** [comment]
Has anyone identified a solution or a work around?

**Comment by leomiranda92** [comment]
I'm having a big problem with this.
I have an product with  thousands variations and ?wc-ajax=get_variation take 12 seconds to allow me to add to cart.

**Comment by berzley** [comment]
@leomiranda92 A few months of research and troubleshooting on my end has only shown that switching away from WordPress/WooCommerce (to something such as Shopify) or breaking the product up into many (many many) smaller products is the only solution.

**Comment by leomiranda92** [comment]
:/

**Comment by mikejolley** [comment]
@leomiranda92 Having 1000's of variations in a single product is not going to be performant regardless of platform. The product itself should be looked at; often there are other ways to tackle problems e.g. product addons, 'any' attributes to avoid a variation per attribute combinations, bundles, composite products and so on.

**Comment by rochow** [comment]
Sorry @mikejolley I don't agree it is what it is and nothing can be done.

Default WC: https://d.pr/i/obCuol/IRBAmlGfm2

/includes/data-stores/class-wc-product-data-store-cpt.php
Change function find_matching_product_variation to https://pastebin.com/jpLPUDRW

Result: https://d.pr/i/TjsrRc/F7Ulb9jeun

46 seconds down to 700ms

This was slapped together quickly given the client's site is unusable atm so it's not a finished product.

I think breaking it down into smaller chunks and then doing the matching query is far more efficient than an all in one SQL query.

This particular product is only 48 variations so it's not something insane.

**Comment by kevin25** [comment]
@rochow Have you tested it carefully without issue? I'm really interested in this.

**Comment by rochow** [comment]
@kevin25 On my testing on latest WC with PHP7. The code is pretty simple overall: here are the attributes and parent ID, find the 1 variation that matches them. It returns the ID or 0 as per the original function. So I think it shouldn't matter about any other WC plugins installed compatibility wise, and php wise this should be fine on 5.4+.

The main "not production ready" part is unhooking and hooking this in somehow rather than editing the core plugin as I've done. At the moment I've made the site workable so it's mission accomplished for now, I was waiting for feedback about the approach before making it a self contained solution.

I tested the frontend archive, single, cart, checkout, order emails, order in admin - all works still. Not many other places I can imagine to test.

I'd be curious if you can update the file with the code, and do a before/after looking at the Ajax request to see what speed difference you get. It's one copy and paste so very easy to revert if it doesn't work.

**Comment by peterfabian** [comment]
Especially when having a lot of attributes, the version proposed by @rochow seems to perform a lot better (as otherwise there is a db JOIN for each attribute which kills the performance). When I tested with 13 attributes, it took ages to run the large SQL query that is currently in place.

@rochow -- would be great if you could create a pull request for your contribution.

**Comment by kevin25** [comment]
@rochow  That is really interesting. Can you create a pull request? @mikejolley Can you please take a look at this?

**Comment by rochow** [comment]
@peterfabian @kevin25 Glad that it works well for you too. I've made a pull request.

It's fugly compared to the old code but the results are worth it 🐎

**Comment by palmps** [comment]
This function is still a major speed bottleneck issue.  Not sure if it's related to updates to Wordpress, but I am having wait times of 4 to 12 seconds on this function.  It halts the rendering of the rest of the page as the script tries to load the options (it's a product with only 5 color variations). Pages that do not require or load variations are rendering in much faster.  I would be curious to know if the above solution was included in the final?

**Comment by amostajo** [comment]
I am having an issue with a client in this regards... He wans a complex item that has multiple variation grid and this ajax call is simply not optimized.

WooCommerce should save a variations grid table (in form of cache) for quick access rather than having to look up into wordpress taxonomy table for the right combination.

**Comment by JudithK87** [comment]
i'm having a 13 seconds page load on a self-created landing page that pulls 3 variable products... from my "Inspect Element" tabs I can see that this ajax file is the main source of delay. I'm a noob at programming and the links posted by @rochow in 2018 seem to no longer work. Anybody has a (simple to implement) code I can put somewhere to have a workaround for this?

**Comment by rochow** [comment]
The code ended up making its way into WC core.

3 variable products you have within one page that people can add to cart?
How have you embedded these?

This _may_ be something more specific to how it's built or hosting, rather than a generic issue.

**Comment by JudithK87** [comment]
It could be... I'm using Elementor to build my pages. I have used shortcodes for this page: 
[product_page id="123"] for the main variable product on my page, 
and added a couple of extra ones with additional shortcodes: [add_to_cart id="456"]. 
Then I did some hardcoded CSS to add text ":before" and ":after" the woocommerce buttons etc. I thought it was a great idea but I guess this isn't a good practice 😭

**Comment by rochow** [comment]
It sounds unusual to take that long for what is seemingly a pretty basic setup.

Does the same issue happen if you visit the product page directly, rather than this Elementor page? To isolate whether it's an issue with the product, or related to the custom page.
If slow in general, if you make a new test variable product, give it 3 random attributes, is that one slow too? To isolate whether it maybe something specific with the product.

You can also disable all plugins minus WooCommerce + Elementor, some add-ons are dreadfully coded and could be causing issues too.

You may need to engage a developer to help debug or build the page another way, depending on where the issue looks to be.

**Comment by JudithK87** [comment]
Oh my! I cannot thank you enough!!! My site's single product pages were ALL super-slow. I did a troubleshoot and found the plugin that caused it!! out-dated and no longer supported by my current version of woocommerce. Now I'm running my site without this plugin and my original problem is solved! and the rest of the single pages are also fast again! (now I need to find a solution to replace this plugin that is no longer working but at least my site is saved! Thank you!!!!

**Comment by rochow** [comment]
No problem, glad it was that simple :)

**Comment by peterfabian** [comment]
Thanks for the help, @rochow !

**Comment by NatOdUa** [comment]
> Sorry @mikejolley I don't agree it is what it is and nothing can be done.
> 
> Default WC: https://d.pr/i/obCuol/IRBAmlGfm2
> 
> /includes/data-stores/class-wc-product-data-store-cpt.php Change function find_matching_product_variation to https://pastebin.com/jpLPUDRW
> 
> Result: https://d.pr/i/TjsrRc/F7Ulb9jeun
> 
> 46 seconds down to 700ms. And this isn't a bad host it mirrors my results on local.
> 
> This was slapped together quickly given the client's site is unusable atm so it's not a finished product.
> 
> I think breaking it down into smaller chunks and then doing the matching query is far more efficient than an all in one SQL query. Despite the fact it's obviously not as pretty the speed difference is insane.
> 
> This particular product is only 48 variations so it's not something crazy.
> 
> Is there a reason why something similar can't be implemented into WC core?

The links are out of date, could you re-share the code, please?

**Comment by rochow** [comment]
The code is in https://github.com/woocommerce/woocommerce/pull/20900

WC has modified it since including changing the SQL queries, as the pull request simply turned 1 mega query into a few smaller queries with PHP loops.

**Comment by sunjava11** [comment]
@rochow 
Hi, not the thread, but it's kind of relevant. wc-ajax=get_variation() is not being called on live server (it was before). On my local machine, it is being called. I don't know where to look and find the issue.
