### ISSUE TITLE
User have permission or not to download any file in Woocommerce

### ISSUE THREAD

**Issue by genexweb** [woocommerce/woocommerce#12275]
I want to check whether any user have permission or not to download any file. I have product id and user id so How I can check?
I have explored a lot on google and in woocommerce documentation but didn't find any solution.
Any help?
Thanks in advance.

**Comment by mikejolley** [comment]
There is no dedicated function for this since it's done on a per-download/order basis: https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/includes/class-wc-download-handler.php#L86

We do have functions to see if the user has purchased anything but this might differ from what you're attempting.
