### ISSUE TITLE
validate_attribute_slug only allows 28 characters

### ISSUE THREAD

**Issue by peterigz** [woocommerce/woocommerce#12294]
## EXPLANATION OF THE ISSUE

When trying to import product attribute data using the REST API, I'm getting the error "woocommerce_rest_invalid_product_attribute_slug_too_long". 

The data structure allows a field length for the slug of 200 characters, but the function validate_attribute_slug (https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-product-attributes-controller.php#L635) disallows anything over 28 characters. 28 doesn't seem very long, is it an over site or is there a specific reason for that?

Thanks!

**Comment by claudiosanches** [comment]
Good question.
But this is not a problem of the REST API, since the REST API only replicate it:

![screenshot from 2016-11-09 23-09-26](https://cloud.githubusercontent.com/assets/1264099/20160888/a0ed1682-a6d1-11e6-9bb2-f5629e540d54.png)

https://github.com/woocommerce/woocommerce/blob/2de494e105ba88b135ebf6ba9767c9f6a9299fce/includes/admin/class-wc-admin-attributes.php#L91-L106

@mikejolley any reason for it?
In the table is a `VARCHAR` for 200 characters:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L467-L476

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Function_Reference/register_taxonomy

> $taxonomy
> (string) (required) The name of the taxonomy. Name should only contain lowercase letters and the > underscore character, and not be more than 32 characters long (database structure restriction).

See https://github.com/WordPress/WordPress/blob/2d07c3196e473bc2fb5f83e036e09aeb53968776/wp-admin/includes/schema.php#L76

**Comment by peterigz** [comment]
Ok that's fine, however, it says 28 max, yet the condition is >=, shouldn't it be just > ?
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-product-attributes-controller.php#L636

**Comment by mikejolley** [comment]
Shorter than 28 means 27 max. We need to allow a few chars for our prefix.

**Comment by peterigz** [comment]
I mean the error message - https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-product-attributes-controller.php#L637 - says 28 max, it should say 27 max. Not a big deal but just saying :)
