### ISSUE TITLE
Zoom does not work in new gallery on laptop with touch capability

### ISSUE THREAD

**Issue by arashohadi** [woocommerce/woocommerce#12315]
## EXPLANATION OF THE ISSUE

**What happens:** Zoom does not work in new gallery on laptop with touch capability.
**When:** Hovering over single product image
**What I expect:** Zoom to work on a laptop with touch capability
**Version:** master branch / commit 6eba8342d8a8dc6f520f4f630d0e149914947439

## STEPS TO REPRODUCE THE ISSUE

I am using a laptop with touch capability. 
```
/**
		 * Init zoom.
		 */
		init_zoom: function() {
			// But only zoom if the img is larger than its container and the visitor is not on a touch device.
			if ( ( $( '.woocommerce-product-gallery__image img' ).attr( 'width' ) > $( '.woocommerce-product-gallery' ).width() ) && ( ! wc_product_gallery.is_touch_device() ) ) {
				$( '.woocommerce-product-gallery__image' ).trigger('zoom.destroy');
				$( '.woocommerce-product-gallery__image' ).zoom();
			}
		},
```

Removing the check for ```! wc_product_gallery.is_touch_device()``` in the if statement makes the zoom work.

**Comment by jameskoster** [comment]
Well, this is a tricky one. 

First of all; Magnification is disabled on touch devices because it interferes with the swiping behaviour of the gallery. It's poor user experience to have both behaviours occur at the same time and swiping is more important for handheld browsers.

Of course, magnification should work on a laptop when you hover, but not when you touch. 

We might need to rethink that `init_zoom` method so that it looks for the tap vs hover events. What do you think @claudiosanches ?

**Comment by jameskoster** [comment]
OK I just double checked and there's an option to disable touch interactions in the Zoom script we're using. 

I don't have a touch-enabled laptop to test this though. Would you be able to check [that branch](https://github.com/woocommerce/woocommerce/compare/fix/magnification-on-touch) please @arashohadi ?

**Comment by arashohadi** [comment]
@jameskoster Yes, the commit seems to fix it, thanks!

**Comment by jameskoster** [comment]
Sweet!
