### ISSUE TITLE
Add wrapper for all deprecation notices

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#12328]
<del>Use wc_soft_deprecated_function and _argument so notices don't display until 2.8. This will make it easier on devs. This task should be done last so notices don't appear in core later.</del>

Add wrapper for deprecation notices and hide during ajax calls.

**Comment by claudiosanches** [comment]
To be honest I do not like it, it seems to me bad for devs, mainly because with the warnings it's possible to know where is the problem and how fix it as soon as possible. This make easy when comes the date to remove the legacy code and starting now everyone will have more time to fix stuffs.

Not to mention that `wc_soft_deprecated_function()` function is only to starting display a message some version in the future... I can't see any advantage in comparing versions over and over again only to not display a deprecated warning right now. If we need to do something like it, so it's better to only use the `@deprecated` notation.

Looking for `_deprecated_function()` and `_deprecated_argument()` code it's possible to see what only throw warnings when `WP_DEBUG` is enabled.

https://developer.wordpress.org/reference/functions/_deprecated_function/
https://developer.wordpress.org/reference/functions/_deprecated_argument/

And if you are fine with hide deprecated messages, it's still possible to use `add_filter( 'deprecated_function_trigger_error', '__return_false' );` and `add_filter( 'deprecated_argument_trigger_error', '__return_false' )`.

So for regular users this is not really an issue.

**Comment by claudiosanches** [comment]
@allendav Mike asked to CC you here.

**Comment by claudiosanches** [comment]
And speaking for myself... I don't change code if something is working without any error or warning just because there is a new cool way to get some data from an order or coupon.
If I'm using in one of my plugins `$order->billing_first_name` I'll not change to `$order->get_billing_first_name()`, since don't throw any warning so I can assume that `$order->billing_first_name` is stable enough and that works since WooCommerce 2.0.0, so I don't need to do anything  :wink:

**Comment by mikejolley** [comment]
Hmm. @allendav any thoughts on this one?

**Comment by coderkevin** [comment]
Do we have a clear path forward for developers that's ready to go with examples and documentation? If so, I don't see any reason why not to print deprecation notices in the debug log. It wouldn't harm performance in production, and it informs our developers as early as possible that changes are coming.

**Comment by mikejolley** [comment]
@coderkevin It's mainly because if you want to support 2.6 and 2.7, you need conditionals, otherwise you get notices.  I don't think it's a problem with the education side.

**Comment by mikejolley** [comment]
Lets move this out of sprint and talk about it tomorrow in team meeting. Once decided, it's a quick one to apply anyway.

**Comment by gedex** [comment]
Yeah, I think conditional is fine. Would be great if we could provide the conditional wrapper for common functions that developers can use.

**Comment by mikejolley** [comment]
@gedex That kinda only makes sense if we plan on refactoring the refactors :p

**Comment by gedex** [comment]
@mikejolley I was thinking to put snippet in the post. Just like we provide tokenization or my account endpoint snippets.

**Comment by gedex** [comment]
For example a wrapper for `prefix_wc_get_order_id( WC_Order $order )`.

**Comment by mikejolley** [comment]
@gedex Thats not really useful IMO - until you change your code, you get notices and still need conditonal. No different to using new methods.
