### ISSUE TITLE
Fatal error: Cannot use object of type WC_Product_Variable as array

### ISSUE THREAD

**Issue by monecchi** [woocommerce/woocommerce#12376]
## EXPLANATION OF THE ISSUE

After updating to WordPress Versão 4.6.1 and WooCommerce 2.6.8, I keep getting the following error:

**Fatal error: Cannot use object of type WC_Product_Variable as array in woocommerce/includes/class-wc-product-variation.php on line 178**

Any chances of this being a bug?

In order to narrow down the chances it being a plugin or theme issue, I've disabled all WooCommerce extensions and other plugins. My theme hasn't any functions involving the class `WC_Product_Variable` also.

**Comment by claudiosanches** [comment]
I don't believe it is linked to the update, since the first time I see this error.

> My theme hasn't any functions involving the class WC_Product_Variable also.

Even then you should test with a default theme to be sure.

The line reported by the fatal error is: https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/class-wc-product-variation.php#L178

And in WooCommerce core we use this method passing some value only two times:

https://github.com/woocommerce/woocommerce/blob/release/2.6/templates/cart/cart.php#L51
https://github.com/woocommerce/woocommerce/blob/release/2.6/templates/order/order-details-item.php#L31

And both don't send a `WC_Product_Variable` object as an `array`.

Note that both of are on templates, so this can be an issue on your theme.
