### ISSUE TITLE
Concurrent checkouts can cause negative inventory for items with backorder disabled

### ISSUE THREAD

**Issue by TWarszawski** [woocommerce/woocommerce#12467]
## EXPLANATION OF THE ISSUE

When two customers check out concurrently for the same product (with backorder disabled), both checkouts may complete successfully when this would cause the inventory to become negative.  This negative inventory is reflected in the admin console.

It seems likely that a solution to #5966 would resolve this issue, but it also seems that this could be fixed without implementing the functionality proposed in #5966.

## STEPS TO REPRODUCE THE ISSUE

1.  Start site, create two customers, create/pick test product and allocate some stock.
2.  Both customers add the product to their carts such that each cart individually is under the available stock, but combined they exceed the available stock.
3.  Perform a checkout concurrently, making sure both customers finish checkout (click the 'Place Order' button) as close to the same time as possible.

We have reproduced this behavior on a single machine, by performing the above steps by simulating one customer in one browser window and another customer in a second browser window.

Expected Result:
One of the two checkouts fails to complete.

Actual Result:
Both checkouts succeed and the final inventory is negative.

### WordPress Environment ###

Home URL:
Site URL:
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.2g PHP/5.6.19 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 5.6.19
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.8

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
@coderkevin suggested using a queue. How do you see that working Kevin?

**Comment by coderkevin** [comment]
The queue could be implemented a few ways, maybe even in a custom orders table by adding a new order status to indicate the order quantities were successfully secured for the order.

In any case, there would also need to be a new UI flow to show the user upon checkout if the quantities couldn't be secured for their order.

**Comment by mikejolley** [comment]
> The queue could be implemented a few ways, maybe even in a custom orders table by adding a new order status to indicate the order quantities were successfully secured for the order.

I wonder if the sessions table would suffice? But still, how can we ensure 2 orders coming in at the same time are not checking and updating this table at the same time? Locks?

**Comment by coderkevin** [comment]
The best way to do it is to have a single background job do the fulfillment (e.g. inventory decrementing) of the orders. Then it's a serial operation. Just because an order is placed doesn't mean it will be fulfilled, so we'll need a status to show that, too.

**Comment by coderkevin** [comment]
By the way, this is where back-orders should be handled as well.

**Comment by mikejolley** [comment]
@coderkevin Back-order stock works in the same way as regular stock so that shouldn't be an issue here.

I guess I'm just unsure how this 'job' runs, technically. The only way I can think of to only do this one-at-a-time would be table locks on the database https://dev.mysql.com/doc/refman/5.7/en/lock-tables.html

**Comment by franticpsyx** [comment]
Not sure if you've been able to replicate but I can confirm this is an issue I have seen in the past.

It mostly affects high-traffic stores and stores which sell highly-demanded items which run out of stock quickly. Used to run a store where stock replenishment was announced in advance and done at a predetermined time -- customers would wait for that time and then pull the trigger and we'd watch stock disappear in minutes. Stock go down to -2 or -3.

I thought it happened due to the delay involved in processing a payment. By the time payment for the last available item had been processed (and order stock was permanently reduced to 0), another customer (or more) could be checking out.

One solution would be to keep track of orders/SKUs that are currently "being paid for" and deduct them from the available stock when another customer attempts to check out. The message displayed to the customer should not be a "product X is out of stock" message, but a message that encourages them to retry in a few seconds.

**Comment by mikejolley** [comment]
We determined that even with table locking, this data would need to be in a separate table to avoid locking up the entire site. Therefore, 3.0 seems to be the right milestone.

**Comment by franticpsyx** [comment]
@mikejolley How would table locking would be helpful? Customers may spend a long time paying for a pending order off-site. In older WC versions, it was even possible to pay for a pending order without WC double-checking line item availability.

"Hold stock" would resolve the problem here, but many shop owners choose not to enable it knowing that some customers may wish to pay for their "pending" orders with a delay (sometimes hours/days).

In UX terms, a "softer", always-on alternative would be to:

1. Deduct stock in "pending" orders that go back as far as X minutes when checking availability **at checkout** -- and show a stock-related message that encourages customers to "try again in a few minutes" if the "stock on hold" 
2. Always check availability when attempting to pay for a pending order (might already be fixed in core).

**Comment by mikejolley** [comment]
@franticpsyx we're talking about 2 requests at the same time. 

> "Hold stock" would resolve the problem here

This won't fix anything because there is still a risk of 2 concurrent checkouts, both seeing something in stock, and both creating the order/reducing stock at the same time. Thats why you need table locking or a queue.

**Comment by franticpsyx** [comment]
Thanks for the explanation @mikejolley -- looks like I misunderstood the original issue.

**Comment by SukcesStrony** [comment]
Same here - negative stock amounts with backorders turned off. More people are experiencing this: https://wordpress.org/support/topic/woo-commerce-inventory-issue-negative-stock/
The WooCommerce version 4.0 milestone looks like too long of a wait for such a critical bug imho. I'd be great if this can be pushed forward earlier.

**Comment by claudiosanches** [comment]
@SukcesStrony not sure what "WooCommerce version 4.0 milestone looks like too long", 4.0 could come still this year, maybe next week, like after 3.1.0 could come 4.0.
Still the changes required here are for a Major release, please check it: https://woocommerce.wordpress.com/2017/03/13/important-update-regarding-the-upcoming-woocommerce-release-2-7-will-be-3-0-0/ and please stop making assumptions with version number and time, because they are not related. Thank you.

**Comment by SukcesStrony** [comment]
@claudiosanches My assumption is based on the previous _major_ version's date, which was released 10 months before this major release. Don't assume I'm assuming based on version numbering, thanks :)
As this is an important bug, it would be great if the release cycle could work faster for it, no matter the version numbering.

**Comment by claudiosanches** [comment]
@SukcesStrony "no matter the version numbering." !== "The WooCommerce version 4.0 milestone looks like too long of a wait for".
You are contradicting yourself. But ok, as I said, this is something that we are working on and will require a big change and then need to go into a Major version.

**Comment by SWS-Denzle** [comment]
Hi all,

Do you have any update on this please?

I have a meeting with my client this afternoon and he's going to ask me if I've made any progress, I would appreciate it if I had something to say :)

Cheers.

**Comment by mikejolley** [comment]
@SWS-Denzle No. This issue will not be tackled until the next major release. You're free to contribute if you want it sooner though :)

**Comment by SWS-Denzle** [comment]
@mikejolley okay, as least that is something I can still pass on to my client. I would love to help but I think its beyond the scope of my skills :)

Cheers

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent problems with heavy load/concurrent checkouts](https://trello.com/c/GuGBXoQz/110-prevent-problems-with-heavy-load-concurrent-checkouts)

**Comment by Exellent1988** [comment]
The trello link istn't working. IS there now a fix or eaven temporary workaround availible?

**Comment by mikejolley** [comment]
Until you see a link to a commit or pull request here, no.

**Comment by lab21gr** [comment]
Hello, i am having the same problem with stock turning to -1.
This happened for 2 orders placed at the same time, but also in 1 more case:

I was testing the site as my client told me of the issue with stock being -1 for 2 products.
So at the checkout the page kinda "froze" so i did the "stupid user" action: refreshed the page and clicked to submit the order again. The stock went to -1, but i have 2 same orders in the backend so i guess in these cases i can just cancel the second order.

I am running latest Woo (3.1.2)

not sure if this info helps out in solving this issue.

thanks

**Comment by mikejolley** [comment]
Right; locking wasn't really working well for this. We've logged an issue for the queue idea here to be done (hopefully) this year.

https://github.com/woocommerce/woocommerce/issues/16971

**Comment by salar90** [comment]
there would be a temporary solution:
add a hook to woocommerce_order_status_completed that checks all pending orders. cancel any of the orders which have items that are now out of stock.

**Comment by SukcesStrony** [comment]
@salar90 that would be an awful solution. Canceling orders that were already made and/or paid and emailed to the customer? Come on, man :)

**Comment by salar90** [comment]
@SukcesStrony as far as I know this issue would only happen when an a "pending order" is paid after another pending order is paid which have items in common. this is very very rare and I think it usually happens when customer leave the payment step to another time. happens maybe once in 3 month with a 7k customer shop. and as I said it's a temporary solution and you are cancelling the pending order. not the paid one. good luck :)

**Comment by camilosw** [comment]
Why this issue was closed? I tested with 3.5.1 and the problem persist. The referenced issue #16971 was also closed but the merged pull referenced on that issue didn't solve the problem.

**Comment by SWS-Denzle** [comment]
Hi, we are still getting this problem and each time we get negative stock the website will send duplicate order emails confusing our customer. Any news on a fix for this please?

**Comment by ethan-tqa** [comment]
are there any temporary solutions for this, like clearing all stock values?

**Comment by ethan-tqa** [comment]
After a quick check through the source code, I found that wc_get_held_stock_quantity() function does not take woocommerce_hold_stock_minutes into account. Deleting pending orders seems to help, but of course that isn't really the right solution.

**Comment by smartstak** [comment]
function sleep_order_before_process(){
 sleep(4);   //  minutes for you want to sleep new order query so stock table will be updated
 This is the best till now
}
add_action('woocommerce_before_checkout_process',' sleep_order_before_process');

**Comment by mdqmatias** [comment]
> function` sleep_order_before_process(){
> sleep(4); // minutes for you want to sleep new order query so stock table will be updated
> This is the best till now
> }
> add_action('woocommerce_before_checkout_process',' sleep_order_before_process');

Can you explain better this? I have other problem, that is related. I need to the inventory be reduced in the "pending payment" order instance, cause some payment methods are in cash on 24hs still credited. or some clients want to pay tomorrow for example. I need to secure stock for THAT clients, at least for 48hs (with the hold stock option in minutes before cancel).

**Comment by plxrisa** [comment]
I have the same problem and I have already opened an issue about it:
https://github.com/woocommerce/woocommerce/issues/22544

As you can see it needs votes so we can have an option about that to use it as we want.
If you want you can give your vote and help to resolve this big issue with already sold items and the stock levels.

**Comment by Marajade208** [comment]
Hey guys! I'm yelling this from the rooftops because hopefully it makes your lives easier and is the solution for you. I know it was for me. So here was the problem:

We has a product setup as a virtual, simple product, with backorders not allowed. The stock got down to 1 and a customer bought the last item in stock. However, we got a notification for a -1 back order, even though the client only bought 1 item and was charged for only the 1 item. So we started freaking out thinking all of the thoughts listed above. "Does this mean two people were trying to check out at the same time", "does this mean the customer tried to buy two", etc.

No, it was much dumber than that. We have a Woocommerce site. So I went to the order, and in the "order notes" area to the right, I noticed this:
![Screen Shot 2020-02-08 at 8 02 42 PM](https://user-images.githubusercontent.com/15135238/74094767-812cff80-4ab4-11ea-9b71-a1a401214a7f.png)

Because the customer checked out using Paypal, the payment was verified twice because in our Paypal we had both IPN and PDT enabled, thus causing the double verification, the double notification, and the -1 back order even when back orders are disabled. So if you go to your Paypal, and disable PDT in Account Settings>Website Payments>Website Payment Preferences>PDT this will stop the double verification, thus the double notification, and the accidental -1 back order alert. 

Check this out, and dear lord, I hope this is saving some of you a headache like it is me. And this is thanks to something that a guy named Mike W said on another random forum which I found...
[](https://wordpress.org/support/topic/ipn-payment-completed/)

**Comment by amirulasyraf88** [comment]
https://stackoverflow.com/questions/63655365/why-my-stock-from-woocommerce-variation-deduct-to-negative-value I have a same question also, but still not solve. Anyone can help answer my question?

**Comment by attritionorg** [comment]
Old ticket I know, but this was opened in reference to the following vulnerability disclosure: http://www.bailis.org/papers/acidrain-sigmod2017.pdf   

It isn't clear if this has been resolved. #12467 references #16971 which in turn references PR #20030. The 11 commits associated with it seem to have landed before the 3.4.5 release, and a commit at the end was merged in 3.5.0-beta.1. 

That said, other users have reported the same issue but it appears that this can manifest a number of ways, including in 3.5.1. So the question is, has the original vector / vulnerability posted here, born out of the ACIDRain paper, been fixed?

Thanks!

cc @mikejolley
