### ISSUE TITLE
Discount just non sale items when a cart discount coupon is used.

### ISSUE THREAD

**Issue by mgason** [woocommerce/woocommerce#12473]
Right now when a cart discount coupon is set to not apply to sale items and a sale item is in the cart the coupon is completely rejected. "Sorry, this coupon is not valid for sale items."
This is lame and really annoys customers. We have to instruct them make separate orders, thats if they bother to contact us and don't just get pissed and leave. Some have told us afterwards that they did exactly that.
Woocommerce should be smart enough to deduct the coupon from the total of all non sale items and keep the sale item in the cart without discount. I have seen this request here, punted down the road since 2013, and also on your feature request page for several years.

**Comment by mikejolley** [comment]
Maybe it gets punted because you can use product coupons instead. If it's % based it will work out identical.

Cart level coupons are designed to take all cart items into consideration for each validation rule. We shouldn't make some rules apply and some not. It's not consistent?

Also no one forces you to exclude sale items from discounts. I've never really liked that setting nor seen why stores would want it. Seems unfair as it is.

**Comment by mgason** [comment]
Fair enough. It is very standard retail practice to exclude sale items from further discounts though. Not my job as a developer to say if that is right or wrong.
Are you saying there is a way to setup a product (as opposed to cart) coupon so that it applies to all products except sale items? That would be great, can you explain that?

**Comment by mikejolley** [comment]
I will leave this open so we can have a chat about fixes cart vs fixed product rules anyway.

**Comment by mikejolley** [comment]
Proposal in #12598
