### ISSUE TITLE
Tax settings are affecting coupon amount

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/woocommerce#12508]
## EXPLANATION OF THE ISSUE

With certain settings, tax affects the amount discounted by a coupon. 

## STEPS TO REPRODUCE THE ISSUE

1. Clean installation, [Twenty Sixteen Theme](https://wordpress.org/themes/twentysixteen/), no plugins
2. Tax settings: Prices entered exclusive of tax; Display prices Including tax 

![](http://cld.wthms.co/kXVK/29Fbe1WK+)
Image Link: http://cld.wthms.co/kXVK/29Fbe1WK  

3. Tax rate 15% across the board
4. Create simple product, tax status: Taxable
5. Create a flat rate $10 off cart coupon

![](http://cld.wthms.co/WV8D/xZrNA6a6+)
Image Link: http://cld.wthms.co/WV8D/xZrNA6a6  

6. Test purchase with coupon shows coupon discount at $11.50, not the expected $10

![](http://cld.wthms.co/6lmB/59fMfaLE+)
Image Link: http://cld.wthms.co/6lmB/59fMfaLE  

7. Changed settings to Display excluding tax, coupon shows as $10

![](http://cld.wthms.co/lscQ/1fO1trNn+)
Image Link: http://cld.wthms.co/lscQ/1fO1trNn  

![](http://cld.wthms.co/7T6a/7uFGpc6F+)
Image Link: http://cld.wthms.co/7T6a/7uFGpc6F  

User reported 501887-zd-woothemes 

@mikejolley

**Comment by mikejolley** [comment]
This one is intentional due to tax inclusive prices. If we didn't 'adjust' the discount display amount, the subtotals/totals would not "add up". The actual discount amount (10) does not change, just the displayed value.

```
Ex tax:
2000
-10
+298.50
= 2288.50
```

```
Inc tax:
2300
-11.50
= 2288.50
```

Note the totals match in both examples. The same discount has been applied. Please note; tax is calculated after discounts (it's illegal to discount tax!) which is also why the discount appears more, but isn't. The amount of tax payable is reduced because the amount you're paying is discounted. Does that make sense?

If we did as your ticket suggests and left it as 10,

```
Inc tax:
2300
-10
= 2288.50
```

That looks like wrong math :)

**Comment by LaurenaRehbein** [comment]
Thank you for the very clear explanation, much appreciated!
