### ISSUE TITLE
_usort_terms_by_ID is deprecated in WP 4.7

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#12525]
Should use wp_list_sort: https://make.wordpress.org/core/2016/11/02/wp_list_sort-and-wp_list_util-in-4-7/

Found in https://github.com/woocommerce/woocommerce/blob/f67ffe4d89e0ab5e967f63cf5bdc1ba5d9308579/includes/wc-product-functions.php#L250

**Comment by johnrom** [comment]
I view this as a high priority? This can make a product-heavy dev site needing WP_DEBUG unusable.

**Comment by alexweblab** [comment]
Query Monitor plugin reports a warning and a notice:
Warning - usort(): Array was modified by the user comparison function - Location: wp-content/plugins/woocommerce/includes/wc-product-functions.php:231
Notice - _usort_terms_by_ID is deprecated since version 4.7.0! Use wp_list_sort instead. - Location: wp-includes/functions.php:3783

**Comment by birgire** [comment]
This part:

    ` usort( $terms, '_usort_terms_by_ID' ); // order by ID
`
 needs to be replaced with: 

    if( function_exists( 'wp_list_sort' ) ) {
        $`terms = wp_list_sort( $terms, 'term_id', 'ASC' );  // order by term_id ASC
    } else {
        usort( $terms, '_usort_terms_by_ID' ); // order by term_id ASC
    }
`

to handle both 4.7+ and old versions.

**Comment by birgire** [comment]
Glad to see it's fixed, was just writing the patch ;-)

**Comment by DiveMachine** [comment]
Thank you birgire it worked. Easy to fix.
Will be interested if this returns in future updates.
Thought I had a big problem and your fix worked beautifully.
