### ISSUE TITLE
Free Shipping Coupon UX - Allows User to Apply Coupon they are Ineligible For, Should Produce Error Message

### ISSUE THREAD

**Issue by sghartman** [woocommerce/woocommerce#12605]
I already submitted this to WooThemes support and was informed that, "his is actually an issue with WooCommerce and not Smart Coupons." They suggested I post it here.

This is a UX issue whereby users in a Shipping Zone which does NOT have the Free Shipping method enabled are still able to apply free shipping coupon codes. The codes don't actually grant them free shipping, but they do submit and appear in their Cart details as applied. In summary, the functionality works to not grant free shipping, but the UX isn't what you'd expect. Customers are confused as to why the coupon applied but they didn't get free shipping.

We would expect the code to show an error upon a user submitting it and for there to be warning that says something like, "Free shipping is not available for your shipping destination" or whatnot.

This is happening with WooCommerce version 2.6.8 and Smart Coupons plug-in version 3.1.7.

(My non-developer suggest is that there be a new coupon code category created for a code that grants free shipping and free shipping only. I think the above is happening because the only way to create a free shipping coupon code is for the code to be classified as Discount Type "Cart Discount" and then to check the box for "Allow free shipping: Check this box if the coupon grants free shipping. A free shipping method must be enabled in your shipping zone and be set to require "a valid free shipping coupon" (see the "Free Shipping Requires" setting)."

If their were a Discount Type for "Free Shipping Only" it seems to me it could be limited more easily.

## STEPS TO REPRODUCE THE ISSUE

1. Create a new coupon code (Discount type "Cart Discount" and "0").
2. Check the Free Shipping box indicated above "Allow free shipping"
3. Load cart
4. At checkout, enter a destination address which is in a Shipping Zone which does NOT have a Free Shipping method enabled
5. Apply coupon. (See screenshot here for what you'll see http://imgur.com/a/yEurY).

**Comment by mikejolley** [comment]
There are a few reasons why this one cannot really be fixed in core.

1. Free shipping coupons can also give fixed or % discount which would still be valid
2. Coupons can be applied before you have the customer's address/zone, so it would be wrong to reject them on that basis
3. A dedicated free shipping coupon would still have problem 2.

To improve UX you could consider:

- Offering free shipping elsewhere if you have this promotion
- Making it clear up front this won't apply to X counties
- Don't include 'free shipping' in the coupon code

Hope this makes sense.
