### ISSUE TITLE
Endless loading/spinner on the checkout page

### ISSUE THREAD

**Issue by doviis** [woocommerce/woocommerce#12640]
![Uploading 15555363_1463506063676913_880234438_o.png…]()
I have woocommerce website VVVVVV.gamedeal.lt 
At checkout SOME customers get endless loading/spinner and cannot place order.
SOME of customers get SYNTAX Error.
Some customers can place orders and everything works fine. It works fine for me also with all browsers. 

I have no idea where to start and how to look for problem.
Checkout page is: www.gamedeal.lt/checkout

Using Opay payment gateway (installed plugin) and paypal (no plugin)

Please help

**Comment by mikejolley** [comment]
This is not a support area, and the issue is likely an error thrown by a plugin you're running.

Debug syntax error with this:

https://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

And enable in config:

`
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
`

And check your error logs after it occurs to find a useful error message.
