### ISSUE TITLE
Feature Request:  Coupon page (shortcode)

### ISSUE THREAD

**Issue by brewone** [woocommerce/woocommerce#12698]
EXPLANATION OF THE ISSUE

It would be helpful if Woo had a shortcode for a coupon form [woocommerce_coupon] so customers   could apply codes or redeem a product `(via usage restrictions /100% discount)` from any page.

**Comment by mikejolley** [comment]
To me this is plugin territory. You could use ideas.woocommerce.com if you wanted but this is the first request I've seen so it likely won't get many votes.

We only allow coupons to be added during cart/checkout because thats when the customer has a session. Before the user has a cart, we don't set session cookies or anything (which also allows caches to function).
