### ISSUE TITLE
Who is the customer?

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12708]
Currently woocommerce always display customer name as the person who make the order.
This is true for private customers... This is not the for companies.

If on order the customer entered a company name this should be the main name displayed in the dashboard:
For example:

` #12390 by Company Name`

Why this is important?
Purchasing person who makes the order isn't always the one who will order next time in this case the customer name has no meaning only the company name has meaning... if there are issues with the order it's not always the person who ordered which will call you and ask for explanations. Company Name is the only common ground for this case. The invoice is also for the company and not for the person who made the order for the company.

**Comment by mikejolley** [comment]
This is a pretty large generalisation you're making. I can't see how that would always be the case - the company is not making the purchase, a person is. The company does not have an account, a person does. Since companies don't have dedicated accounts you cannot assume it's a company purchase.

> if there are issues with the order it's not always the person who ordered which will call you and ask for explanations

No the account holder should, and they are named. Company names are included in the address though so it's searchable.

You may be interested to read and contribute to https://github.com/woocommerce/woocommerce/issues/12610. This introduces the concept of B2B.
