### ISSUE TITLE
How can I remove shipping calculator for specific delivery method (on cart page)?

### ISSUE THREAD

**Issue by Feofilov** [woocommerce/woocommerce#12776]
I need to remove the calculator only for a selected specific shipping method. I tried to use the filter like this:
```
function woocommerce_remove_my_shipping($needs_shipping) {
  $chosen_methods = WC()->session->get( 'chosen_shipping_methods' );
  $chosen_shipping = $chosen_methods[0];

  if (is_cart() && $chosen_shipping == 'ems_shipping') {
    return false;
  }
  return $needs_shipping;
}
add_filter( 'woocommerce_cart_needs_shipping', 'woocommerce_remove_my_shipping', 10, 1);
```
But that removes everything including the choice of method of delivery.
woocommerce_shipping_calculator() function without the possibility of a hook?

**Comment by WPprodigy** [comment]
Hi,

Hmm, not sure if that really makes sense. Why remove the calculator after a specific shipping method is chosen? Going to run into a cause/effect issue doing this with PHP. Your snippet is telling WooCommerce that shipping isn't needed all, so that hook definitely isn't what you need.

I'd recommend just using some Javascript/CSS to hide the calculator based on the selected shipping method. That way you can unhide the calculator as well when the selected method is changed.

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.
