### ISSUE TITLE
Cannot create coupons with Discount Type of Fixed Cart Discount

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#12816]
## EXPLANATION OF THE ISSUE

Observed on master from Jan 12, 2017

If you create a Coupon of **Discount Type** "Fixed cart discount" and then edit it, it displays as **Discount Type** of "Percentage Discount" instead.  Also, there is nothing displayed in the **Coupon Type** column on the Coupons page for such coupons:

<img width="1107" alt="screen shot 2017-01-13 at 11 00 23 am" src="https://cloud.githubusercontent.com/assets/1595739/21941953/f4ff117c-d97f-11e6-863c-72acae212736.png">

## STEPS TO REPRODUCE THE ISSUE

Attempt to create a coupon of discount type "Fixed Cart Discount"

## SYSTEM STATUS REPORT

N/A

**Comment by justinshreve** [comment]
I don't have a proper fix for this yet, but I spent quite a bit of time tracking down the problem. Tricky :). cc @mikejolley on the best suggestion for fixing this.

We will only put something in the `changes` array if the value differs from the prop in `$this->data`. In this case, the value is `fixed_cart` in both, because WC_Coupon sets a default value of `fixed_cart`.  

See https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/abstracts/abstract-wc-data.php#L411 and https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/class-wc-coupon.php#L31 and https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/abstracts/abstract-wc-data.php#L477

The second part of this bug is the fact that `WC_Coupon_Data_Store_CPT->create` is never ran. `WC_Coupon_Data_Store_CPT->create` unlike `-WC_Coupon_Data_Store_CPT>update`, ignores the `changes` array and just forces a meta update (see the true at https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/data-stores/class-wc-coupon-data-store-cpt.php#L72). The coupons admin first creates a post, and then sets up a WC_Coupon object and calls `save` on it -- which calls `update`. 
 See https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php#L275 and https://github.com/woocommerce/woocommerce/blob/99527e80131fd9176986c73d7c37c95247d93451/includes/admin/class-wc-admin-meta-boxes.php#L65.

Since `update` looks to see whats in the `changes` array and our value is omitted - no meta is set.

**Comment by mikejolley** [comment]
@justinshreve good find there. Sounds like this may also affect new products, we've just not noticed a bug there yet :)

Perhaps, since this is a WP admin problem only, we could do some tinkering with when forcing occurs. i.e. force if the real post status is auto-draft or whatever is set when this bug occurs? That way we can always ensure the minimum data set exists, even when update is called instead of create.
