### ISSUE TITLE
REST API: GET Products with consumer key/secret as query string parameters returning duplicates on different pages

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#12909]
WC Version: 2.6.13
WP Version: 4.5.3

I'm doing a GET for all products as follows:

GET /wp-json/wc/v1/products?page=1&consumer_key=ck_123456&consumer_secret=cs_98765
GET /wp-json/wc/v1/products?page=2&consumer_key=ck_123456&consumer_secret=cs_98765
GET /wp-json/wc/v1/products?page=3&consumer_key=ck_123456&consumer_secret=cs_98765

and so on (HTTP Basic Auth wasn't working on this particular server).

Looking at the list of returned IDs I can see duplicates starting to appear on subsequent pages. For example ID 1375 is returned for the page 1 request but also on the page 2 request.

**Comment by claudiosanches** [comment]
This should be something in your installation removing the `page` parameter or changing the `WP_Query`.
I made some tests and don't see anything in WooCommerce core that can generate it.
Better you try debug more in your side, please let me know if you found anything.
But closing, since don't looks related to WooCommerce core as I said.
Thanks.

**Comment by databuzz** [comment]
Adding these parameters:

orderby=id&order=asc

to override the default sort by creation date/time appears to solve this issue (where multiple products have the same creation date/time)
