### ISSUE TITLE
Free shipping & shipping calculator, can they be better together?

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#12913]
## EXPLANATION OF THE ISSUE

Using the latest, 2.6.13, if you only have Free Shipping as a shipping method you can still have the Enable the shipping calculator on the cart page. This isn't a big deal, but does seem like a potential confusing user experience. Shipping is free, why would anyone need to calculate shipping? 

This is solved by disabling that in the Shipping Options settings. But I'm creating the issue to see if we can think further on the

## STEPS TO REPRODUCE THE ISSUE

Setup a shipping zone with Free Shipping only, and make sure you have the Enable the shipping calculator on the cart page setting enabled. This will needlessly then let you calculate free shipping on the cart page when Free Shipping is already shown. :)

**Comment by mikejolley** [comment]
@ryanr14 Since it can be disabled (based on store owner needs) I think that makes sense. Shipping methods are added to zones, and to get the zone we need an address. Some settings remove the users default address so they don't see shipping until they enter their address.

Whilst possible, I don't think it would be particularly reliable or efficient to "detect" if there is only 1 zone and option and change the behavior. Plus you could have a scenario where they only ship to certain countries, even if they do only have the 1 free shipping method.

The fact that the shipping calculator is hidden could be yet another source of confusion for users expecting it to be there (with the setting not disabled).

**Comment by ryanr14** [comment]
Thanks @mikejolley, that makes sense. :)
