### ISSUE TITLE
Hide payment method if shipping zone is not available

### ISSUE THREAD

**Issue by kristinaplauche** [woocommerce/woocommerce#12915]
## EXPLANATION OF THE ISSUE

Customer tries to place an order for an area that cannot be shipped to.
Payment options and fields display. Customer enters their credit card information.

The payment won't go through, but the error that displays says: `No shipping method has been selected. Please double check your address, or contact us if you need any help.` 

This is confusing to the customer. They think something is wrong with their card & they keep looking for a shipping method.

## STEPS TO REPRODUCE THE ISSUE

Setup a Shipping zone for the state of New York with 1 shipping method.
Setup Rest of the World with no shipping methods.
General Settings sell to United States only.

Try to place an order for a US state other than New York.
Try to checkout with a credit card

## Desired outcome

Hide payment methods if customer's address does not match any shipping zones.
& Change error message to "No shipping is available to your address."

**Comment by carasmo** [comment]
You can change the text with a filter. 

http://docs.shopplugins.com/article/33-how-to-change-the-no-shipping-methods-available-message

You may also want to check out:
http://jeroensormani.com/enable-disable-payment-gateways-for-specific-shipping-methods/ and other searches for similar to see if you can find a way to do it.

**Comment by mikejolley** [comment]
@kristinaplauche Isn't there a big notice saying no shipping methods are available where shipping usually appears?

**Comment by kristinaplauche** [comment]
@mikejolley There is a notice that no shipping methods are available but the customers aren't looking at that because they are busy entering their payment information. It's not until after they try to submit payment that the big red notice appears saying they can't submit their order because there are no shipping methods.  So it _works_, but it's confusing to people.

**Comment by kristinaplauche** [comment]
@mikejolley Anything I can say to the customer about this? Is there any reason to have the payment methods display if the customer can't checkout due to no shipping available?

**Comment by mikejolley** [comment]
You're probably not going to like my answer @kristinaplauche but bare with me.

Yes I see it's a problem, but with the current checkout flow hiding payment is going to look odd and feel 'broken'. It wouldn't feel like a solution but more a workaround/stop gap measure.

Because of that, and after speaking with @claudiosanches, we feel it's best to leave it as-is until we do it properly via https://github.com/woocommerce/woocommerce/issues/10672 @jameskoster We can account for this there.

Perhaps the store owner should ensure all places are covered for shipping (fall back methods?) if they are concerned with loss of sales, because either way that 'customer' cannot purchase anything. Or they can make it clearer where they ship and/or change the 'sell to' locations.

**Comment by kristinaplauche** [comment]
@mikejolley I am not unhappy with that response. :D I'm glad to se that it can be taken into account for the future. That is enough for me to tell the customer at this point. Thank you!
