### ISSUE TITLE
get_category_ids for a Product Variation are empty

### ISSUE THREAD

**Issue by lucasstark** [woocommerce/woocommerce#12942]
If you have an instance of a Product Variation you can call get_category_ids(), however this will always return empty since product categories are assigned to the Product itself, not the individual variations.  

Not sure if this is expected behavior, but I can see this causing confusion.   For example, add one of the variations to the cart and then try to get the categories for the $cart_item['data'] object.

**Comment by mikejolley** [comment]
@lucasstark has this not always been the case? Variations have no association with categories, so at least from a data standpoint there should be no link.

**Comment by franticpsyx** [comment]
>For example, add one of the variations to the cart and then try to get the categories for the `$cart_item['data']` object

I agree that variations should inherit the categories of their parent, similar to how they inherit their shipping class by default. (or used to: https://github.com/woocommerce/woocommerce/issues/13015)

**Comment by mikejolley** [comment]
@franticpsyx @lucasstark The difference here is that shipping class is explicitly set to inherit from the parent object. Categories and tags are not - they are not part of the variation UI, nor are they a taxonomy which variations have. 

We need to draw the line somewhere about what should be inherited. If we try to inherit too much, we may introduce new performance problems.

If you have a more specific case where this approach causes problems please let me know, otherwise I think we should not have them inherit.

BTW we have 2 issues open for 2.8/2.9 to completely rethink variations. I have a few ideas for this, and I hope we can all work together to make them better in that release :)

cc @justinshreve @claudiulodro

**Comment by bolderelements** [comment]
I'd be interested in this or whatever you have planned for the future. I understand drawing lines where needbe, but I also hate having to "hack" information retrieval when the function isn't available because then you have to worry about compatibility in future versions. It's not critical, but simply a nuisance when meeting the requests of certain shop owners.

I have a few plugins that people like to categorize their products based on category. For example, your multiple packages feature. I've had users in the past want to calculate their shipping and lay it out based on item category but it's hard to do so without inheriting the category ID on variations. It works for shipping too, prioritizing shipping costs based on category. The idea of assigning a class and a category to every product begins the client complaints of "too much work" and "I don't understand why I have to do that", so to make them happy and me stress-free, my code uses get_terms to find the categories, but first checks whether to use the product ID or parent ID.

It gets the job done for now, but then I hear you say big changes coming for variations and now I have to worry about compatibility. 

Just my two cents on the matter. I'll continue with the work around and keep tabs on 3.1/3.2 :)

**Comment by mensmaximus** [comment]
@mikejolley isn't this the same issue that arises from time to time with the request to exclude attributes from the layered navigation if variations are out of stock? Any taxonomy is bound to the parent product and you need extra (expensive) queries for to get them for the variations. If I recall correct you already had the idea to change that.

**Comment by ctrlaltdylan** [comment]
I just want to add to this issue and make sure that the team is aware that this issue persists.

For our business use case, it's important to know which product categories are within a given order, to see if it qualifies for specific actions. 

For example, as a developer I expect when I iterate over the list items of an order, that I can inspect each product's categories or tags.

There's no warning or error when you call `get_category_ids()` on a `ProductVariant` instance, which is returned by `$order->get_line_items()`.

We have found a workaround by leveraging the `is_type('variant')` and then retrieving the parent product, but this introduces a performance issue because of the long product retrieval query * X number of product variants in an order.

So there are several side effects that this bug introduces.

1. As a developer, you're not aware that `get_category_ids()` doesn't return the parent's product categories.
2. As a merchant, you can't assign categories to product variants anyway
3. The workaround is to call `$product_variant->get_product_id();` then `$product = wc_get_product($product_id);` in order to finally get the product categories. This is a performance issue with multiple product variants in a single order.
