### ISSUE TITLE
Review WC_Product get_name() and get_title() usage.

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#12990]
See https://github.com/woocommerce/woocommerce/pull/12967#issuecomment-275253186 and #12783.

> Issues:
>
> - Repetition. In some locations where `get_name` is used the user sees a list of the variation attribute values in the variation title, followed by a breakdown of attribute names + values. E.g. in the cart & order details. In these cases, the variation title doesn't need to differ from the parent title, since it's followed by detailed attributes config info anyway.
>
> - Sometimes `get_name` is not sufficient because it's missing attribute names. Examples in https://github.com/woocommerce/woocommerce/pull/12783
>
> - Sometimes `get_name` helps keep everything short -- For example, variations in AJAX product search results are probably fine without the attribute names.
>
> I suggested doing a quick scan of the locations where `get_name` is used and make a quick re-evaluation of user experience based on these observations.

**Comment by justinshreve** [comment]
At least in the case of the cart, I think returning the attribute in the title makes sense. The meta values are shown as a fallback, but I think the title looks nicer and gets the information across.

**Comment by franticpsyx** [comment]
@justinshreve have you seen the colors example from #12783 ?

Attribute Names: Ceiling Color, Walls Color, Details Color.

A variation title such as "Room Colors: Blue, Red, White" is not helpful because it lacks attribute names and here context is necessary.

I know some users have complained in the past about the length of attribute details displayed in the cart / order templates, but I would prioritize accuracy / usability over conciseness.

>The meta values are shown as a fallback

Don't see a big issue with either approach, as long as we don't show duplicate info.

**Comment by mikejolley** [comment]
Whist I agree it's hard to make EVERYONE happy, the attributes-in-title works for me and gives a cleaner look overall. Like @justinshreve said, we have a fallback in place.

wc_get_formatted_variation has the ability to return the names - it's true by default but set to false when generating names. We could expose that easily by a filter?

Also, `get_name` itself has a filter in view context so that can be changed. We could document both.

Finally, we could make the name generation in the variation data store more content aware e.g. if multiple attributes are called 'color', call wc_get_formatted_variation with true rather than false.

That would replace the line here https://github.com/woocommerce/woocommerce/blob/abe87d9bfa01fc9bd71730af854213ae4d3ee61b/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L106

cc @franticpsyx @justinshreve

**Comment by claudiulodro** [comment]
I've done a review of how variation products show up and here is what one product will look like at different places around a site (Let me know if I've missed any):

**Frontend**
Cart: "Shoes – 9.5, Black"
Order Received: "Shoes – 9.5, Black × 1" and then "Size: 9.5 | Color: Black" underneath
Order Details: "Shoes – 9.5, Black" and then "Size: 9.5 | Color: Black" underneath

**Backend**
Edit Order: "Shoes – 9.5, Black" and then "Size: 9.5 | Color: Black" underneath
Order Notes metabox in Edit Order: "Shoes – 9.5, Black"
Quick Edit Order: "Shoes – 9.5, Black"
Ajax Product Search: "Shoes – 9.5, Black"

**My recommended changes:**
Cart: Add attribute details underneath the product title, like the Order Received/Details pages have (for consistency and clarity).
All 3 frontend pages: Just go with "Shoes" for the title since the attributes are directly under the title.
Backend: Leave as-is. The shorthand titles are used by the ajax search, so it makes sense to expose them as much as possible so shop managers get familiar with the shorthand titles.

No customer would have to figure out what "Room Colors: Blue, Red, White" is; only the person managing the shop would see that. We also wouldn't need to do logic to figure out which title to use, and title-modifying filters can just go in the in the template files when the titles are rendered for people that want non-standard product titles.

Thoughts?

cc @franticpsyx @justinshreve @mikejolley 


<img width="445" alt="orderdetails" src="https://cloud.githubusercontent.com/assets/7317227/22760215/5cb62e92-ee0a-11e6-91cb-0596b079104f.png">
<img width="664" alt="cart" src="https://cloud.githubusercontent.com/assets/7317227/22760216/5cb9ef3c-ee0a-11e6-8283-b3266762ff88.png">

**Comment by mikejolley** [comment]
> Cart: Add attribute details underneath the product title, like the Order Received/Details pages have (for consistency and clarity).

This is actually how it was in previous versions - look at 2.6.x. We wanted to move away from this because the list can get pretty long, and because with CRUD we can generate more meaningful product titles above.

I'd prefer to go the other way, and remove the list from the order received page for consistency. The pages are much neater IMO

Yes there is still the issue of "Room Colors: Blue, Red, White" etc, but it feels solvable...we could even introduce some logic to revert to the 'list' display if > 1/2 attributes or something like that? 

cc @jameskoster

**Comment by claudiulodro** [comment]
Gotcha. Switching everything over to "Shoes – 9.5, Black" and getting rid of the list is probably a better idea. That way names are consistent throughout the front and back ends.

The Room Colors problem is going to be trickier. In this situation, the attribute taxonomies are likely going to be different and some terms are going to have the same names but not necessarily the selected ones.

E.g.
```
Wall Color (taxonomy=pa_wall-color)
        Red (taxonomy=pa_wall-color&tag_ID=1)
        Blue (taxonomy=pa_wall-color&tag_ID=2) 
        Green (taxonomy=pa_wall-color&tag_ID=3)
Floor color (taxonomy=pa_floor-color)
        Red (taxonomy=pa_floor-color&tag_ID=4)
        Black (taxonomy=pa_floor-color&tag_ID=5)
        Green (taxonomy=pa_floor-color&tag_ID=6)
```

This makes it difficult to predict when to show a different kind of list. One possible solution that I've used in the past for this exact problem is instead of just having the values, have the values followed by the attribute. Then it becomes "Room Colors: Blue Wall Color, Red Ceiling Color, White Floor Color." This generally works for all attributes and could just be the default way of rendering the title.

**Comment by jameskoster** [comment]
> I would prioritize accuracy / usability over conciseness

This is a good point, but it can be countered with;

> Let's provide the best experience to the majority of users with fallbacks for edge cases

I really like the new titles but concede I hadn't considered the 'multiple colors' example.

> Yes there is still the issue of "Room Colors: Blue, Red, White" etc, but it feels solvable...we could even introduce some logic to revert to the 'list' display if > 1/2 attributes or something like that?

Dunno how expensive it'd be, but can't we just check if a products assigned attributes share any terms? If they do, display in list mode.

**Comment by franticpsyx** [comment]
On second thought I agree it would be cleaner to show everything in the front-end using the 2.7 approach. That might also spare us the need to store chosen attribute values as order item meta?

>I really like the new titles but concede I hadn't considered the 'multiple colors' example.

One way to solve this would be to inform shop managers about the change and:

a) Encourage them to change term names to include context, .e.g. change **Red** to **Red Room Color**. The downside of this would be some repetition in the single-product drop-downs.

b) Provide some filter that allows the attribute name to be included in saved variation names, e.g. save Shoes – Size: 9.5, Color: Black . In edge cases where the default list is problematic, shop managers could enable this filter.

**Comment by mikejolley** [comment]
> b) Provide some filter that allows the attribute name to be included in saved variation names, e.g. save Shoes – Size: 9.5, Color: Black . In edge cases where the default "name-less" list is problematic, shop managers could enable this filter.

How about doing that if there are > 1 attribute? If there is 1, there is no opportunity for confusion. It does as you say make the titles longer however.

**Comment by claudiulodro** [comment]
See #13136.
