### ISSUE TITLE
Duplicated `_price` product meta

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#12997]
## EXPLANATION OF THE ISSUE

Products can occasionally have the `_price` meta value duplicated, which seems like an expected / poor behavior considering the duplicate appears to be to save both a min and max price value. See [this example in the 2.6.13 branch](https://github.com/woocommerce/woocommerce/blob/2.6.13/includes/class-wc-product-variable.php#L824-L825) and from what I can see, [example 1](https://github.com/woocommerce/woocommerce/blob/920acbe019b6995a8026789cdb684902cc99ef9f/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L373) and [example 2](https://github.com/woocommerce/woocommerce/blob/2cdf95096326008cb18214fe0586310bf9bea9cc/includes/data-stores/class-wc-product-grouped-data-store-cpt.php#L34) from the 2.7 branch.

Since these are storing min / max values, shouldn't these have unique meta keys? It seems fairly unintuitive that the price meta should be duplicated, especially with such a non-descriptive key.

More practically, we've run into this issue when trying to do inventory valuations, as for the sake of performance, we're getting product prices from the database directly, but having to `JOIN` on postmeta results in 2 rows being returned, therefore causing duplicated information (and thus our sum is incorrect).

While I know it's not the responsibility of WC Core to work around extension issues and we could adjust around this, at the same time, it seems super odd that we'd have a real need to store multiple, disparate values under the same, duplicated meta key.

Shouldn't we be storing min / max values as unique keys, then perhaps always ensuring price is the lowest or "canonical" value for the product instead? This would ensure it can still be used in sorting, but that data is stored in a more sane way.

**Comment by mikejolley** [comment]
There is a good reason for this; filters. Variable products have a range of prices. By storing the min and max our price filters can work without special rules or extra post meta joins.

**Comment by bekarice** [comment]
@mikejolley not 100% sure I follow you here; I think what you're saying is related to [this filtering](https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-price-filter.php#L160)? If so, why not just add / modify the price keys in the `IN` statement since you're already using an array? 

More accurately, if what that query is intending really is to get the min price, returning a min price post meta would seem more desirable.

I'd also contend that the cost of one extra join or modification in filtering should be weighed against the fact that when you use `get_post_meta( $product->get_id(), '_price', true );` you can't really have an accurate idea of what you're getting. The extra join for a single widget seems less egregious to me than a duplicated meta key on an essential piece of product information.

**Comment by mikejolley** [comment]
Yes I'm talking about the price filter widget. To query 2 meta keys we'd have to join the postmeta table twice. Trust me, that is not good for performance. 

It should return the same value (max?) So it's still consistent no? Plus this only affects variable products.

**Comment by bekarice** [comment]
So it sounds like this issue is only present with filtering by price -- is that right? If so, would it make more sense to save a second meta key, perhaps `_price_range` that would have duplication expected and then be used for these situations?

This way a variable product could have multiple `_price_range` values, but without the (imho) unexpected ability to return multiple results when `_price` is being used, along with getting more consistent / expected results when using `get_post_meta( $id, '_price', true );`

Again, something we can absolutely work around so I understand the goal to keep filters performant. The thing that seems unintuitive to me is that `_price` is the primary record for the price that a product is at, so it seems odd to intentionally duplicate that meta key. Not saying it's without reason, just feeling like there has to be a more semantic way to store this information.

**Comment by mikejolley** [comment]
Introducing price_range values introduces that slow down. Plus it's more data to sync. 

When you say it's not consistent what do you mean? It returns one value as it should.

**Comment by bekarice** [comment]
> Introducing price_range values introduces that slow down.

I meant that `_price_range` could be one key, allowing for duplication; ie a product could have `'_price_range' = '30'` and `'_price_range' = '35'` instead of duplicating `_price`, but still only having one meta key to use for these queries. Essential `_price_range` would replace `_price` in the SQL.

> Plus it's more data to sync.

My thinking was instead of syncing `_price` for multiple values, syncing `_price_range` to `_price`, replacing the sync functions with this key instead. So a product would only every have one `_price` meta, but could have multiple `_price_range` metas, which could be used in filtering. 

The downside being then that every product would need this meta, so both would be saved for all products. Definitely agreed on more syncing so I'm not sure if this would feel feasible; I've not really looked at this part of WC until noticing the duplicated meta.

> When you say it's not consistent what do you mean? It returns one value as it should.

I meant moreso you don't know which value you're getting -- when you get `_price` is it the minimum, maximum, or another price in between? You don't know because the value you're asking for is not unnique. I understand you could be using core functions like `$product->get_price()`, but your use-case is better off for using the direct SQL, so likely there are other custom use cases in which the same principle applies.

**Comment by franticpsyx** [comment]
Just to add to the discussion here, I agree that the current way that the price filter widget works is somewhat restricting for product types that have a range and need to store a single `_price` meta.

So, currently, the way it works is that `_price` is used to identify both the minimum AND the maximum price in `price_filter` queries, which only works if:

- There are variations with different `_price` meta.
- There are multiple `_price` meta on the same product.

The advantages of this approach are:

- Arguably less data.
- More performant queries.
- Results accuracy: If a product can be purchased for $10, $14 or $20, then searching for products that cost between $11-$13 will (correctly) yield no results.

The disadvantages:

- Arguably more data. A grouped product needs multiple `_price` meta to work like this accurately. A product type that has 50.000 configuration permutations (and does not create 50.000 variations to allow it) would need to store 50.000 `_price` meta to return reliable results. On the other hand, if we only store the min/max `_price` then the accuracy argument is no longer relevant for grouped/complex type products (Grouped, Bundle, Composite, MnM).
- Semantic issues. In the end, it is unclear what `_price` represents. Try to describe in one sentence what `_price` contains. Is it all the different prices that a product can be purchased at? No, because that's not sustainable. Is it just the minimum and maximum? That's not how it is in WC 2.7 at the moment.

In the end, we need a formal way to represent products with a price range in the DB, even if it's less accurate for specific product types. One that works with any product type and does not force developers to do mumbo-jumbo like this: https://github.com/somewherewarm/woocommerce-product-bundles/blob/master/includes/class-wc-pb-display.php#L593

If multiple extensions have to modify the price filter query like that to return correct price filter widget results, it's easy to guess the outcome.

**Comment by franticpsyx** [comment]
Just had a look at WC 2.7 -- I think this pretty much negates the "less data" argument: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L361

I expect some serious meta table clutter due to this ^ -- also keep in mind that, down the road, horizontal meta storage in dedicates tables will not quite work with this approach, since there will be only 1 price column per table.

While it's not too common that a variable product would contain 50.000 variations, variable products with 1000 variations are quite common.

In extension territory, complex products with 50.000 permutations are quite common. A composite product with 3 components, each having 10 options is ~60.000 permutations.

That's the equivalent of a variable product with 3 attributes, each having 10 options.

**Comment by franticpsyx** [comment]
>My thinking was instead of syncing `_price` for multiple values, syncing `_price_range` to `_price`, replacing the sync functions with this key instead. So a product would only every have one `_price` meta, but could have multiple `_price_range` metas, which could be used in filtering.

So a variable product with 2 variations, priced $10 and $20 would have 2 `_price_range` meta of equal values?

This would make the migration to horizontal tables easier, provided that all these `_price_range/point` meta remain in the post-meta table.

Just wondering if we could find a solution that doesn't need all that meta to work. It's hard to swallow a solution that can potentially create thousands of `_price` or other meta in the postmeta table, which is already a bottleneck.

**Comment by mikejolley** [comment]
@franticpsyx @bekarice 

> I meant moreso you don't know which value you're getting -- when you get _price is it the minimum, maximum, or another price in between? You don't know because the value you're asking for is not unique. 

I don't think this is true. We insert them in the same order, so WP will return the 'same' value each time. The fact we store multiple values for a same named keys won't affect this.

> Just wondering if we could find a solution that doesn't need all that meta to work. It's hard to swallow seeing thousands of _price or other meta created in the postmeta table by 1 product -- the postmeta table is already a bottleneck.

This may be so, but joining the meta table multiple times is also a bottleneck.

Both approaches have draw backs but overall I prefer the multiple _price solution for filtering. It provides the most accurate price filter results (because all variation prices are evaluated) and prevents the need to join post meta multiple times. 

One thing you're forgetting with "Price Range" is that if will miss the prices in the middle. Example:

variation 1: $10
variation 2: $25
variation 3: $100
Filter: $20 - $30 - no match. Price range does not have this value.

I don't think the flat meta idea in the future will be thwarted by this because we'll be able to just query variation price meta directly without (as much of a) performance impact.

@claudiosanches @justinshreve for reference.

**Comment by franticpsyx** [comment]
>Both approaches have draw backs but overall I prefer the multiple `_price` solution for filtering. It provides the most accurate price filter results (because all variation prices are evaluated) and prevents the need to join post meta multiple times.

Agreed, but for reference:

- This does not scale at all when a product has many configuration permutations. 
- This does not work with products that have an unlimited top price.

So we can just accept this is a WC core limitation and mark any related issues that come up in plugins/extensions as "wont' fix".
