### ISSUE TITLE
Review tax exclusion code

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13011]
See https://wordpress.org/support/topic/price-including-tax-doesnt-play-nice-with-eu-vat-number-plugin/#post-8686557

**Comment by DavidAnderson684** [comment]
Here's another concern that might be relevant.... with post-Jan 2015 digital goods regime, it's possible for a shop to want to deduct VAT on some line items, and not on others. That's not currently possible with the existing is_vat_exempt stuff inside WC, because that is applied to the whole order.

Here is my client's description of his use-case. We could only advise him to add a code snippet to forbid mixed digital/non-digital carts, and force the customer to check-out twice.

* * *

We are a Swiss company that sells both Soft- and Hardware to Germany. The Hardware is delivered from a German facility (so it is "inland"), software from our server (so from abroad), and the VAT handling should legally be as follows (a german consulting firm has confirmed this for us):

Hardware has to be sold applying 19% VAT for B2B and B2C,
Software, however, with 19% VAT for B2C and 0% VAT (reverse charge) for B2B.

The problem now: if i set Germany as base country and prevent tax exemption via providing VAT ID for base country, I can't get to 0% vat for the software - and if I allow tax exemption for the base country, I also apply 0% VAT for the hardware, which I'm not allowed to.

**Comment by mikejolley** [comment]
See #13099
