### ISSUE TITLE
Error when changing wordpress from http to https

### ISSUE THREAD

**Issue by shawnvdb** [woocommerce/woocommerce#13030]
## EXPLANATION OF THE ISSUE

I changed my wordpress from http to https in the wordpress settings. I changed my .net code to reflect https and recreated the api keys. Yet I get the following error:

{"code":"woocommerce_rest_cannot_create","message":"Sorry, you are not allowed to create resources.","data":{"status":401}}

If I change the site back to http, it works again.

## STEPS TO REPRODUCE THE ISSUE

As above

**Comment by mikejolley** [comment]
Core has no issues with API calls over https. Confirmed it's working. Therefore it could be related to either your HTTPS config, certificate, or the API calls themselves. "Sorry, you are not allowed to create resources" usually means your auth credentials are missing (not set or not received due to server) or invalid. Thanks.
