### ISSUE TITLE
New Variations System

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13086]
A push to make variations more understandable, usable, and scalable.

**Comment by imbeingfollowed** [comment]
I completely agree that variations system needs some work.

The system becomes cumbersome to manage when you have more than 10 variations. The sliding animation is very disorientating and it is easy to lose your place.

One of the other biggest improvements I think, would be to put a checkbox next to each variation so that you can use the bulk options on a selection of products rather than all.

**Comment by mikejolley** [comment]
Consider how stock can be shown/managed also: https://github.com/woocommerce/woocommerce/issues/14493

**Comment by f3bruary** [comment]
I just wanted to add something I've been struggling with since using WooCommerce for about a year now. Developer either cannot or manage by great effort to create filter plugins that can take variations stock into consideration. The cause is how WooCommerce works with variable products.

It seems like a very basic feature to be able to filter by variation like size for example and only see products that are actually in stock for that specific size.
