### ISSUE TITLE
Tax is incorrectly calculated - it's rounded to 2 decimals but should be 3 

### ISSUE THREAD

**Issue by dligthart** [woocommerce/woocommerce#13174]
## EXPLANATION OF THE ISSUE

Tax is incorrectly calculated - it's rounded to 2 decimals but should be 3.

Version 2.6.14
PHP 7.0.13
WordPress 4.7-0

See screenshot:
https://www.dropbox.com/s/s319pmb1d9bjp4l/Screenshot%202017-02-13%2013.44.18.png?dl=0

21% tax rate

0.21 * 0.8 = 0.168 but is rounded to 0.17 

this is causing issues for us with the validation of accounting.

## STEPS TO REPRODUCE THE ISSUE

Add products to cart with small amounts.
Set to 21 % tax rate
Order overview

**Comment by dligthart** [comment]
TAX => 21%
SHIPPING => [cost] * 0.1

PRODUCT #1
    Regular price => 1
    Tax status => none

PRODUCT #2
    Regular price => 0,8

PRODUCT #3
    Regular price => 0,5

ORDER
    PRODUCT #2 0,8 x 1 - 0,8 - 0,17
    PRODUCT #1 1,0 x 1 - 1,0 - 0,0
    PRODUCT #3 0,5 x 1 - 0,5 - 0,11
    
    SHIPPING 0,13 - 0,03
    
TOTALS
    SHIPPING 0,13
    TAX 0,3
    ORDER TOTAL: 2,73

[2:07]  
order items tax sum 0,17 + 0,11 + 0,03 = 0,31 vs tax total = 0,3

**Comment by mikejolley** [comment]
Edit the line item and you'll see unrounded values. When prices/taxes etc are _displayed_ it will be rounded to 2dp because you cannot have half a cent. You're adding up rounded values to get 0,31

This has nothing to do with the calculation itself, which you can read about in https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

**Comment by dligthart** [comment]
Thanks.
