### ISSUE TITLE
[2.7] Removed purchased column from Orders dashboard?

### ISSUE THREAD

**Issue by dare-devil-arrives** [woocommerce/woocommerce#13185]
## EXPLANATION OF THE ISSUE

After updating to WC 2.7 beta 2, Purchased column is not visible in Orders dashboard.

Before (Till WC 2.6.14) Screenshot : [WC-v2.6.14](https://cl.ly/j93L/WC-v2.6.png)

After (In WC 2.7 beta 2 onwards) Screenshot : [WC-v2.7-beta 2](https://cl.ly/j9RZ/WC-v2.7-beta2.png)

Why it was removed? I don't think it should be removed. It gives a quick overview of what is purchased in that order. Without it, there is no quick way to find out the same.

**Comment by mikejolley** [comment]
Performance; this causes all order items and all order item meta to be loaded for all orders listed on the page. This is a huge bottleneck if you have a full page of orders.

**Comment by mikejolley** [comment]
I think we could add something similar in the future, but it would need to be loaded dynamically. We're working on new UIs so I'm swaying towards leaving it until then :)

**Comment by dare-devil-arrives** [comment]
Looking forward to seeing it in future someday :)

**Comment by tobiasschutter** [comment]
Our solution might interest you. We re-introduced the Purchased column in our plugin "Admin Columns", because we got so many requests for it from our users. The way we solved it is by splitting the column value in two parts. First, we only load the item count of the order. Secondly, after clicking the item count, we dynamically load the detailed order data. This eliminates the performance penalty, but it will still show all the relevant information product information. Also, it allows you to make the column sortable in an efficient way.

I have described our solution in more details on our public github page: https://github.com/codepress/admin-columns-issues/issues/721. 

![woocommerce_purchased_column](https://cloud.githubusercontent.com/assets/2736280/25668816/0d7c0f3a-3028-11e7-8232-712071e1916e.gif)
