### ISSUE TITLE
[2.7]  The product category count is not updated

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#13191]
WordPress : 4.7.2
Plugins activated : Only WooCommerce 2.7 beta2 (master)
Theme : StoreFront 2.1.7

To reproduce :
Go to the products list, select a product, quick edit or edit it > add a product category > update.
Go to the products category list > Count : the count is not updated.

**Comment by datafeedr** [comment]
I am also experiencing the same issue.

WordPress 4.7.2
WooCommerce 2.7.0-beta-2

I attempted to add some terms to a product via the `wp_set_post_terms()` function. However, this ignored the term recount functionality.

Additionally, when I went to WordPress Admin Area > WooCommerce > System Status > Tools and clicked the [Recount terms] button, the count was not updated.

The issue is related to these new lines of code in this file: 

**wp-content/plugins/woocommerce/includes/wc-term-functions.php**

```
	// Don't recount unless CRUD is calling this.
	if ( empty( $wc_allow_term_recount ) ) {
		return;
	}
```

After removing those lines, my call to `wp_set_post_terms()` worked and the [Recount terms] button on the Tools page worked again, too.

Is it necessary to limit recounting strictly to CRUD calls? 

Eric

**Comment by mikejolley** [comment]
@datafeedr It's a performance tweak, but also one which stops WP Admin breaking counts. If we don't have this, WP ADMIN does a recount on save, and then we have to do another recount when saving our object after the other props are set.
