### ISSUE TITLE
[CRUD] Add a way to read extra data stored as taxonomies

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#13262]
In the class `WC_Product_Data_Store_CPT`, some internal properties are stored as taxonomies, other are stored as metadata.

There are actions `'woocommerce_new_product'`, `'woocommerce_update_product'`, `'woocommerce_delete_' . $post_type` and `'woocommerce_trash_' . $post_type` to create, update and delete properties in any way we want. There is the method `WC_Product_Data_Store_CPT::read_extra_data()` to read any property stored as metadata. But there is no way to read extra properties stored as taxonomy.
 
Same issue in `WC_Order_Data_Store_CPT`.

I suggest to add the possibility to read extra properties stored as taxonomies the same way it is done for metadata in `WC_Product_Data_Store_CPT::read_extra_data()`.

**Comment by mikejolley** [comment]
We're considering search (https://github.com/woocommerce/woocommerce/issues/12677) but taxonomy saving is not something I feel should be handled by core CRUD classes. 

- these taxonomies are registered externally.
- If the storage method ever changed, your taxonomies would not due to their nature.
- We store an array of data; not information on how to store data or if it's a taxonomy/taxonomy name

This is better left to the actions and filter hooks, or custom data stores, if you have extra data to handle. 

Meta is an exception because it's self-contained and easy to store consistently in a location of our choosing. 

cc @justinshreve Agree?

**Comment by Chouby** [comment]
> Meta is an exception because it's self-contained and easy to store consistently in a location of our choosing.
I understand your point. And you are right that taxonomies are externally registered.So maybe the best is not to include the function to read taxonomy terms in core.

But in that case, new actions placed at the end of WC_Product_Data_Store_CPT::read() and WC_Order_Data_Store_CPT::read() allowing to set extra props should allow plugins authors to use CRUD to manage properties when they are not stored as meta.

**Comment by justinshreve** [comment]
Agreed @mikejolley. If there is extra data outside the realm of meta, a custom data store should be used.

**Comment by Chouby** [comment]
I went deeper into the code since yesterday and started to understand why there is no action/filter to read the data when I saw this: https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L525

If I well understand, the goal is to keep a product (or any other object) closed (i.e preventing plugins to add properties). Would it not prevent plugins to take profit of the performance improvements associated with CRUD?

I mean for example that currently I cannot associate a property stored as a taxonomy term to a product before it is saved (because of the id). So if some core property must depend on my taxonomy term, I will have to let WooCommerce save the complete product. Then I will save my taxonomy term and only after that I will have to modify the product property and resave it. That would work but goes against the performance.

Or maybe I missed something.

**Comment by mikejolley** [comment]
It's locked down because it's impossible to add getters and setters dynamically. We handle core data, and provide a meta data API layer for you to add extra data outside of the scope of core.

What we don't handle is taxonomies, because as I said earlier, those require extra handling such as registering taxonomies prior to usage. That handling should be done in your own codebase; either by extending data stores, or just handling them the 'traditional' way.
