### ISSUE TITLE
Problem With Jalali date in "Edit Order" page

### ISSUE THREAD

**Issue by javad2625** [woocommerce/woocommerce#13289]
Hello
I have been using Woocommerce for 2 years, and I am running the latest version right now. All versions of WC have problem with Jalali Calendar. I use WP-Jalali plugin, so to convert all Wordpress dates into Jalali date. For example, Today is  3 Esfand 1395 in the Persian (Jalali) Calendar (3/12/1395). I also use Woocommerce Farsi plugin, so to add Persian language and Iranian Toman (currency) to WC. Everything works quite fine, but I cannot edit the orders. If I try to edit an order, when I click on "Update" button, WC alerts me "Incorrect date format". This is because the order date is 03-12-1395. Please solve this issue with the plugin. If is a pity I cannot edit the orders.

Thank you

**Comment by mikejolley** [comment]
Does this happen when editing posts too? Do you have a link to the plugin which adds support?

**Comment by javad2625** [comment]
Hello Mike
Thank you for your reply. This problem never happens when editing posts or pages. It only happens when editing WC products. The problem is definitely with WC, not with WP-Jalali. WP-Jalali changes the default date format of Wordpress; therefore, it changes the date format of all the plugins that use default Wordpress date format, but it has compatibility issues with the plugins that do not accept “Year 1395”. Some plugins do not allow us to enter “1395” as a valid date. WC has no problem with Persian dates, but its Product editing page tries to validate the date, so it alerts that the date is not valid. 
This is the support page of WP-Jalali, but it is in Persian.
http://forum.wp-persian.com/forum/10

WP-Jalali recommends plugin developers to use gregorian date in their databases, but i18n date format in their output and input fields. 
WP-Jalali is developed by the formal Persian translation team  of WP.

**Comment by mikejolley** [comment]
There are 2 issues;

1. Converting user entered data from Persian -> Gregorian
2. The patterns we use for validation on date input fields 

So this one cannot be fixed by WooCommerce alone. I looked into the wp-jalali plugin and it handles conversion of Persian -> Gregorian dates. We cannot apply this logic because it's not possible for us to know if the data being entered is intended to be Persian/Gregorian. A compatibility plugin would be needed.

Since this is needed anyway, we can make it so the patterns can be changed via plugin also. I'm adding a new filter called `woocommerce_date_input_html_pattern` to allow this.

**Comment by medicamin** [comment]
Sorry for reopening this issue after almost one year! But we are still facing this problem. 
I have an Idea, but don't know how to do it. As there is no need to change the order date at most of the times, could it be possible to remove this section from the shop order admin metabox, by a function or filter in a custom plugin? So when we update an order, there would be no change in the order date and the time.
