### ISSUE TITLE
Paypall error

### ISSUE THREAD

**Issue by janeng424** [woocommerce/woocommerce#13332]
Hi,

We keep getting this paypal error “sorry we can’t complete your purchase at this time.” for virtual product checkout.

We have the latest woocommerce version installed.

Please help !

Thanks.

**Comment by WPprodigy** [comment]
I'm sorry but Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

This is an issue occurring on your site because of configurations or other plugins. You can use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page. This document may also help: https://docs.woocommerce.com/document/paypal-standard/
