### ISSUE TITLE
Creation of log of what was changed and when?

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#13362]
In almost every information system there is a log table which saves significant changes in the data.
For example if product name was changed or better yet see when the price of product was change. Currently we can only see the last most updated value
We don't know when it was changed and what was the name before the change.

WooCommerce is an information system from that point of view. It is design to support almost every aspect of Online Store. Logs of information (user meta data) is a huge step forward to make the system better.

There is always the question of what is needed to be logged and how the user will access the information. This can be discussed if you will find this idea worth to implement.

**Comment by mikejolley** [comment]
Would you mind submitting feature requests such as this to http://ideas.woocommerce.com/forums/133476-woocommerce? I don't want to unfairly prioritise work logged as issues vs ideas which are validated on the ideas board with actual user demand. 

What you're asking for is an audit log system - this seems like something that should be separate to WC since you'd want to log events from WordPress too, not just WooCommerce products. There are WP audit log plugins available already. Audit logging is also more enterprise level - I doubt smaller shops would find this information useful, nor would they appreciate the DB being filled up with logs.
