### ISSUE TITLE
Taxes not being calculated at random, affecting many users on Facebook as of yesterday.

### ISSUE THREAD

**Issue by accetturo** [woocommerce/woocommerce#13399]
## EXPLANATION OF THE ISSUE
Multiple Users are complaining(10+) on facebook woocommerce groups about Sales Tax not properly being detected from taxable items.

![image](https://cloud.githubusercontent.com/assets/7546902/23452850/f772fbde-fe33-11e6-9ff7-16e8018e75d0.png)

I am not at liberty to disclose their names as I noticed many posts on facebook, but I have linked them all to this post to follow up with replication methods.

## STEPS TO REPRODUCE THE ISSUE

Unforchantly, I do not know how. Many users are also stating that they cannot replicate this issue and it seems to be at random. It may be related to AWS if the tax rates are called from there, but that's a complete assumption due to current events and timing..

## SYSTEM STATUS REPORT

I have relied this to the users
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by jrosengard** [comment]
I'm not sure how to replicate other than what is posted above. I tested the shopping process both on my phone and computer and was charged tax without issue.

HOWEVER, after going back to look and try again, I noticed that the products ordered (jewelry) included one 'variable' product allowing the customer to choose the color. It's possible that's it b/c when I tried to purchase that myself, BAM, no tax was charged.

I double checked, and that product is definitely set to be taxable (and the client has stated every order ever received has always had tax applied... until that one the other day.

I have gone through to verify that all 300 products are in fact, set to "taxable" so that step is done.

I tried it on the live site, as well as, the local development version = same issue.

Otherwise, every other order she receives (simple & taxable products) are charging tax fine.

Hopefully this helps (the possible variable product glitch?).

**Comment by mikejolley** [comment]
I suspect this is simply a few users with similar but different problems saying "me too"! WooCommerce does not rely on AWS and there are no known issues in core regardless taxes.

The only possibilities I could think of would be a) config issue, and b) Using a plugin for taxes which could in theory pull from a service using AWS but this is not core.

Ideally, this should be debugged to find a bug before logging on Github - otherwise the issue itself is not helpful to us and certainly not actionable - we need to be able to reproduce problems.

> It's possible that's it b/c when I tried to purchase that myself, BAM, no tax was charged.

Since it's variable I'd suspect you may be looking at the wrong variation (maybe due to overlapping attributes - remember only one matches) and that variation either having taxes disabled, or a different tax class. If you look at the order line items you should be able to see the variation ID listed there. Look this up by editing the product and check it's settings.

We know the variations UI is confusing and it's on the roadmap to improve.

Thanks
