### ISSUE TITLE
[2.7] 'date_modified' prop changes not saved

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13419]
WC 2.7 offers a `'date_modified'` prop for many objects, including `WC_Abstract_Order` & `WC_Product`. These classes also provide a `WC_Data:set_date_modified()` method, but any value set for the `'date_modified'` prop is never saved, meaning changes to it are not honoured.

For example, `Abstract_WC_Order_Data_Store_CPT::update()` save the `post_date` & `post_date_gmt` columns via `wp_update_post()`, but it doesn't save the the `post_modified` or `post_modified_gmt` column values.

The `post_modified` column has special role in the posts tables and is automatically set to the time of updates. I suspect that may be why it's not updated manually by the data stores' `update()` methods. However, if that is the desired behaviour, the `set_date_modified()` methods should be removed. If they can't be removed to provide a consistent API, then the `update()` methods _should_ honour changes to the `date_modified` prop and update the `post_modified'` and `post_modified_gmt` column values.

**Comment by mikejolley** [comment]
We need the getters, so we also need a setter so the data can be set by the data stores. Since the data-store is separate to the actual object, this needs to be public.

Saving post_modified is undesirable if it's simply the version which was read earlier. We should set it only if in the array of `changes`.
