### ISSUE TITLE
Wrong billing country and state / county on checkout

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#13468]
Hi,

Installed the RC 1 today and discovered that the billing country is set to the (in my case) shop base country instead of the billing country entered in the user details. Also the field state / county is empty on the checkout page while there is a value entered in the user details for sure.

It worked fine in the Beta 3.

Best wishes.

**Comment by mikejolley** [comment]
Just triple checked this and the fields are populated as normal. Sounds like you may be logged out; thats how it would be if not signed in when checking out.

**Comment by AdriOosterwijk** [comment]
OK I will dive into it further. Still strange a logged in user from Luxembourg is presented with The Netherlands and an empty state / region field on the checkout. On the user profile page everything is correct. When needed I will open a new issue.

**Comment by mikejolley** [comment]
Reply here, don't open a dupe. If the default address is your store address, that makes sense.

**Comment by wprue** [comment]
I think I may have gotten a little further with the behaviour described here and thought I would chime in.

Testing w/ WooCommerce 3.0 RC2

**Steps to Reproduce:**
1. Create a new customer user
2. Set a billing or shipping address for the user, noting the country and province/state
3. Return to the edit address page for the address just saved
4. Update both the country and province/state and save the change
5. Confirm the change is displayed on the shipping/billing address edit screen
5. Return to edit the address one final time

**Expected Result:**
The country and state/province would save and be displayed when returning to the edit screen.

**Actual Result:**
The state/province values are not retained.

**Further Notes:**
Continuing to checkout, the state/province values are also dropped. Checking the impacted user via the WordPress backend, the expected state/province is displayed. If the address is edited again and the originally selected country is restored, the province/state value will again save as expected. No errors are logged.

**Comment by claudiosanches** [comment]
@wprue missing steps, like "Create a new customer user", where? on front-end or back-end?
The same for edit billing and shipping addresses, should be create by back-end ad then changed on front-end?

**Comment by wprue** [comment]
Updated for clarity.

**Comment by mikejolley** [comment]
Tested, cannot replicate. Created new account via checkout. Edit address. Values always were set correctly.

**Comment by barbrick** [comment]
I have been able to consistently replicate this using the steps below:

1. Install WordPress 4.7.3
2. Install WooCommerce 3.0.0
3. Select all default WooCommerce settings, setting Base Location to United States (US) - Alabama
4. In the WooCommerce settings check: Enable customer registration on the "My account" page. and save the settings
5. In an incognito browser window browse to /my-account/
6. Register a new user entering an email address and password.
7. Browse to the Edit Address endpoint (/my-account/edit-address/)
8. Under Billing address select Edit (/my-account/edit-address/billing/)
9. Fill out all required address fields selecting "Canada" as the country and "Nova Scotia" as the province and press "Save address".
10. Note the billing address displays Nova Scotia and Canada on the Edit address screen (/my-account/edit-address/).
11. Under Billing address select Edit (/my-account/edit-address/billing/)
12. Change the Country field to "Cambodia" and set the "State / County" field to "Test" and press "Save address".
13. Note the billing address displays Test and Cambodia on the Edit address screen (/my-account/edit-address/).
14. Under Billing address select Edit (/my-account/edit-address/billing/)
15. Note that the "State / County" field is not populated as expected (Should display "Test").

This happens using the default TwentySeventeen theme with no additional plugins loaded.


A workaround that prevents this behaviour is the following filter:


```
function test_state_fix($value, $customer) {
	if (isset($customer->data['billing']['country'])) {
		$value = $customer->data['billing']['country'];
	}
	return $value;
}
add_filter('woocommerce_customer_get_billing_country', 'test_state_fix', 10, 2); 
```


The issue seems to be when WooCommerce loads the country it is loading it from the session instead of the customer. This causes it to load the store Base Country (United States) instead of the selected country (Cambodia) preventing it from selecting the correct state/county/province.

System Status report: https://pastebin.com/TTueet1e

**Comment by wprue** [comment]
Thanks for the followup @barbrick - hopefully that gets this going in the right direction.

**Comment by claudiulodro** [comment]
@barbrick I can replicate it on 3.0.0, but not on the current WooCommerce master branch (almost 3.0.2). Can you give it a whirl on master and confirm the problem has been resolved?

**Comment by barbrick** [comment]
@claudiulodro I tested this again today against the current master branch (3.1.0-alpha) and the issue does seem to be resolved.
