### ISSUE TITLE
Order number should be separate to post ID

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#13491]
Today, I found an issue with order numbers and post IDs.

Using Algolia for woocommerce, the plugin creates posts when it syncs items to their server. 1000 products changing daily means that there are 1000's of new posts being created/deleted by Algolia daily.

Now obviously this isn't just related to Algolia, creating posts, products and pages also pushes the value of the orders up. When syncing with a system that brings 1000's of new products in weekly also contributes to this

It's only just started to show it's face where Order numbers are concerned. Due to the fact they use post IDs to increment the orders, my order list jumps from 140000 to 148053 within the space of a few hours and only 1 order coming through.

This is starting to confuse the order handling department, in that this number might as well be generated completely randomly.

There should be some sort of setting to allow order numbers to be incremental and not based on post IDs. 

If there was a way to continue from this point forward by allowing the orderID to have it's on meta based on the last order in the form, then increment in a logic manner, this would allow there to be a consistency from the order numbers.

**Comment by DavidAnderson684** [comment]
Have you tried Googling? You'll find multiple solutions in seconds.

**Comment by mikejolley** [comment]
https://wordpress.org/plugins/woocommerce-sequential-order-numbers/

**Comment by yratof** [comment]
Are you kidding me? 

- "This wall is wonky"
-  "no it's ok, we offer a stick to prop it up"

**Comment by yratof** [comment]
Or can I ask, in what scenario would you not want order numbers to be sequential?

**Comment by franticpsyx** [comment]
>Or can I ask, in what scenario would you not want order numbers to be sequential?

Personally I haven't met a single store owner who was willing to disclose how many orders they get per week/month/year or how many orders they have processed up to a point in time.

Sequential order numbers make it easy for third parties to estimate sales volume / revenue based on a rough/estimated average order value in the specific industry.

**Comment by yratof** [comment]
@franticpsyx this isn't about disclosing orders though, it's about managing orders. In terms of secrecy, the dashboard of wordpress shows straight up an order count, so the order numbers themselves don't come into play unless someone orders 10 things back to back to check the numbers, right?

**Comment by mikejolley** [comment]
You'd only have to place 1 order to know what the 'count' was up to.

Order IDs are unique identifiers and are needed either way. Order ID !== Order Number. There are no plans to introduce new IDs or built in order number systems with post meta at this point. Use the perfectly good stick thats available.

**Comment by Jojohomefries** [comment]
Sorry to necro this thread, I realize it is many months old. The problem with using the database ID for an order as the 'Order ID' value becomes apparent during migration procedures. Imports have to avoid database ID collisions, which compensate by changing the insert ID, thus the Order ID.  In a controlled development environment this could be avoided certainly, but it's also unintuitive for merchants, and why the WooCommerce Sequential Order plugin exists.

**Comment by richboos** [comment]
@franticpsyx @mikejolley 
Also sorry to necrothread, but if it helps any in future endeavors, we actually utilize Sequential Orders plugin in a way to obfuscate the order number to the public, while being able to know internally what the order number is, in sequence.

We utilize the prefix and suffix patterns to allow the current time to give the faux appearance of randomness.  The actual order number is placed between the seconds and the minutes.  Since we went with the minute version that doesn't have leading zeros, the order number and minute pattern work against eachother to provide that faux random appearance.  Order number 1 a the time of me typing this would appear in that specific segment as 142.  Another order placed 15 minutes from now, the same segment would be 257.  Put it altogether, and the a third order (also 15 minutes from now) with our full prefix on one store would look like CA-1431258

I think if we put the seconds on both sides of the order number, that would be even better.  Never tried, nor considered it until today.
14 is the hour
3 is the actual order number, in sequence
12 is the minutes past 14:00
58 are the seconds past the minute.
