### ISSUE TITLE
[2.7 RC1] Can not select "Shop" page template

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce#13508]
## EXPLANATION OF THE ISSUE

In WC 2.7 RC1 I can no longer select a page template for "Shop" page (products main archive). This was possible in 2.6 and as my theme pages default to fullwidth layout, I offer a sidebar page template which is no longer selectable in WC 2.7. Could this be fixed? Thanks.

## MY SETUP

* **WordPress**: 4.7.3
* **Theme**: a custom theme
* **WooCommerce**: 2.7.0 RC1

**Comment by claudiulodro** [comment]
[The page template selection for Shop pages has been removed in 2.7.](https://github.com/woocommerce/woocommerce/issues/12034) For the large majority of users, selecting a template for the Shop page will break their Shop page, since most page templates aren't designed to also function as shops. We're removing the Shop template selection going forward.

Since you're on a custom theme, you can just add this snippet to your code to re-enable template selection for the Shop page:
```
add_filter( 'theme_page_templates', function( $page_templates, $class, $post ){
	$shop_page_id = wc_get_page_id( 'shop' );

 	if ( $post && absint( $shop_page_id ) === absint( $post->ID ) ) {
 		$page_templates["path-to-template/full-width.php"] = "Template Name";
 	}

 	return $page_templates;
}, 11, 3 );
```

**Comment by webmandesign** [comment]
Thank you for the code and explanation. I'm not sure whether this was a happy solution, though. 

In my opinion **if a theme claims compatibility with WooCommerce, it should integrate support for Shop page templates as well or remove the templates itself**.  Page templates are mostly a territory of themes anyway. Page template selector should not be removed by WooCommerce I think.

It seems like you guys now are favoring themes that don't have good support for WooCommerce...
