### ISSUE TITLE
It's not possible let the payment method button (radio) unselected by default

### ISSUE THREAD

**Issue by matheusgimenez** [woocommerce/woocommerce#13535]
Hello folks, good night!

In a project using WooCommerce I had to modify the radio button of payment method to let by default none selected. I faced some difficulties, I guess, that it could be more simple.
For example: The javascript file checkout.js selects  the first option if it doesn't  nothing selected. And there’s no filter to avoid it. 
Check this: 
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L75)
The only way that I managed to modify, was removing the script with wp_dequeue_script() and adding it with this removed line from my theme. I don’t think it should be good to the approach. 

I think, the best approach in the case would be a filter and/or a option which be passed to the JS in wp_localize_script().

**Comment by mikejolley** [comment]
We force a selection quite simply because gateway is *always* required. Missing those radios is quite possible which would lead to a slower checkout and more clicks from the user. I don't really see a valid use case for leaving them de-selected. Radio buttons after all should have a selected value.

https://www.nngroup.com/articles/radio-buttons-default-selection/

```
The main guideline for radio button design is to select one of the radio buttons by default (i.e., when the page loads, in the case of a web application.) This is good usability and elegant design. I say this not because I am waving a banner for traditionalism, or even for consistency. Rather the banners I’d parade in this case would be decorated with concepts such as the following:
user control,
expediting tasks, and
the power of suggestion.
```
