### ISSUE TITLE
woocommerce_cart_updated hook not wholly accurate

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#13542]
## EXPLANATION OF THE ISSUE

I have a plugin that uses woocommerce_cart_updated hook to do something when the cart contents change. I've been investigating a few issues where the hook was invoked without any apparent change in cart contents. It appears that the hook isn't really what it claims to be, as it's also called in circumstances where the cart contents haven't been updated. As an example, when the cart shortcode is rendered, or any occassion where the cart totals are calculated.

I tried to see if there were an alternative hook / hooks I could use, and came up with this list which cover most, but not all scenarios:

```php
do_action( 'woocommerce_add_to_cart', $cart_item_key, $product_id, $quantity, $variation_id, $variation, $cart_item_data );
do_action( 'woocommerce_cart_item_removed', $cart_item_key, $this );
do_action( 'woocommerce_cart_item_restored', $cart_item_key, $this );
do_action( 'woocommerce_after_cart_item_quantity_update', $cart_item_key, $quantity, $old_quantity );
```

However, they don't cover all. For example there's no hook fired *after* an items quantity has been reduced to zero - neither woocommerce_after_cart_item_quantity_update, nor woocommerce_cart_item_removed are triggered in this case.

While I can definitely deal with what we have now, I wonder if there's value in creating a single hook that is fired whenever the contents of the cart are changed? `woocommerce_cart_contents_changed` maybe? If so - I'll raise a PR.

Previous similar reports:
https://github.com/woocommerce/woocommerce/issues/5233
https://github.com/woocommerce/woocommerce/issues/9656

**Comment by mikejolley** [comment]
`woocommerce_cart_updated` gets fired whenever the session variables update. Thats what it refers to, not changes.

`woocommerce_before_cart_item_quantity_zero` fires when a qty is set to zero. 

Rather than add a new hook here for all of those possible cases, which would be a stopgap measure, I'd prefer to do this when the cart is refactored. We need to do some refactoring when https://github.com/woocommerce/woocommerce/pull/12006 is worked on. There are also some conversations needed about whether we'd like an API based cart, or a local session based cart so that would be a good time to revisit. All of these would have implications for hooks.

**Comment by leewillis77** [comment]
Thanks Mike, I'd agree it's not urgent. I'll track #12006. 

Just for info though - woocommerce_before_cart_item_quantity_zero isn't sufficient in this case. All of the other hooks I mentioned are fired *after* the cart has been updated. In essence, we can capture the final cart state via these. That's not the case for woocommerce_before_cart_item_quantity_zero - which applies before the cart is updated.

**Comment by mikejolley** [comment]
woocommerce_before_cart_item_quantity_zero and woocommerce_after_cart_item_quantity_update fire in the same method? It's fired before because once the item is removed it's no longer accessible.

**Comment by leewillis77** [comment]
`woocommerce_after_cart_item_quantity_update` is only fired if the quantity is non-zero. As you mentioned that's sensible, because there's no "item" left. However, it does mean that there's no hook that fires in `set_quantity()` *after* the cart is updated *if* the new quantity of the item is 0. 

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L1045

Anyway - I'm fine with it not getting handled now. I'll track #12006 and feed back on there if there's still stuff missing. I can work around the existing issues fine for now - was just raising as a potential improvement.

**Comment by chrisvanpatten** [comment]
I wasn't sure whether it's worth creating a new issue, however we've also encountered this — through a long tree of hooks, `woocommerce_cart_updated` seems to be fired on _every_ pageload.

Jumping around from hook to hook, starting from the `WC_Cart_Session` constructor (which is triggered when in `WC_Cart`'s constructor, which is in turn triggered on every pageload in `class-woocommerce.php` line 456):

```
class-wc-cart-session.php
...
42: 		add_action( 'wp_loaded', array( $this, 'get_cart_from_session' ) );
...
105:		do_action( 'woocommerce_cart_loaded_from_session', $this->cart );
...
48: 		add_action( 'woocommerce_cart_loaded_from_session', array( $this, 'set_session' ) );
...
154:		do_action( 'woocommerce_cart_updated' );
```

We use a 3rd party plugin (Klaviyo for WooCommerce) that hooked into `woocommerce_cart_updated` to create or update a mirror object of the cart in its own post type. But because `woocommerce_cart_updated` was being triggered on every pageload it was also creating new posts on every pageload.

It's partly up to Klaviyo to fix their plugin to use a more appropriate hook, but I also find it very strange that `woocommerce_cart_updated` is being fired so often.

Above, @mikejolley said:

> `woocommerce_cart_updated` gets fired whenever the session variables update. Thats what it refers to, not changes.

But as far as I can tell — and it's entirely possible I'm wrong, caveat emptor, etc. — it's being run even when the session variables _haven't_ updated. It's being fired all the time, no matter what.

**Comment by michaelworthley-klaviyo** [comment]
@chrisvanpatten - Great news! Klaviyo has resolved this issue with our latest plugin release.

The plugin now implements only the Klaviyo javascript tracking API instead of using the redundant woocommerce_cart_updated hook and creating new posts. The latest plugin can found here: https://help.klaviyo.com/hc/en-us/articles/115005255808-Integrate-with-WooCommerce#install-the-klaviyo-woocommerce-plugin

**Comment by chrisvanpatten** [comment]
Ha, thanks so much @michaelworthley-klaviyo.

This still seems to be an issue with WooCommerce core — a hook called `woocommerce_cart_updated` firing on every pageload seems misguided — but the Klaviyo plugin was the primary case where it was impacting us and I'm glad we can switch back from our forked version :)
