### ISSUE TITLE
[2.7 RC3] Single product image - <figure> used as a wrapper elemenet

### ISSUE THREAD

**Issue by sevenstudio** [woocommerce/woocommerce#13546]
Hi folks, I'm quite new to WP and WooCommerce - just playing around ;)

In the latest 2.7.0 RC3 version, in the single product image template `/templates/single-product/product-image.php`
you are using `<figure>` element, as a wrapper for the slider,
in a result, on the frontend you get figures inside figure:

```
<figure class="woocommerce-product-gallery__wrapper">
	<figure class="woocommerce-product-gallery__image">
		...
	</figure>
	<figure class="woocommerce-product-gallery__image">
		...
	</figure>
</figure>
```

This element - `woocommerce-product-gallery__wrapper` serves only as wrapper here, so in my opinion it should use `<div>` instead of `<figure>`.

Having figure as a wrapper can cause styling issues in a third party themes. 
For example, if someone will add a max-width to the figure style:

`figure {max-width: 100%; }`

flex slider will display all product images at once in a stack. It could be worth to change it, or is there any specific reason why the `<figure>` was used for the wrapper?

```

**Comment by jameskoster** [comment]
Using the figure as the wrapper is semantically correct as the gallery is a group of related images that serve the same purpose - a visual description of the product. We should probably add `role="group"` to it though.

I do see how the nested `figure`s could cause issues for themes. If we decided to change the markup I'd propose we replaced the nested `figure`s with `div`s rather than replacing the wrapper.

But I'm pretty happy with this markup tbh. I'm not really sure we should compromise WooCommerce for what is honestly a theme issue. Nesting `figure`s is perfectly fine and themes should account for that in their css. Was a particular theme causing you issues?

I'll leave this open while I stew on it some more over the weekend, I'm keen to hear others thoughts as well.

@tiagonoronha @kellychoffman

**Comment by sevenstudio** [comment]
@jameskoster  thank you for your reply!

I know that this is semantically ok Just as I mentioned this could cause styling issues, as in example mentioned above. Of course even in that case this could be easily fixed by applying different style directly to the wrapper.
Changing nested figure elements wouldn't make sense, they match perfectly fine there.

> Was a particular theme causing you issues?
No no. I was just playing with code to see how to build a WP theme with support for a WooCommerce.

Of course this issue can be closed without any changes, just some food for thought.

**Comment by gunnerman1** [comment]
If I understand the convention properly, its proper use seems highly dependent on the content creator. A figure should be self-contained, as already stated. So the first test for a figure is: Will the section content still make sense if I completely remove the figure content? If no, then figure was misused. 

I think [W3's HTML 5.1 Figure Recommendation](https://www.w3.org/TR/2016/REC-html51-20161101/grouping-content.html#the-figure-element) and their examples 31, 33, and 34 are particularly relevant. 

I think I somewhat fall on the side of don't use the figure tag in a template, it is one of those tags (like dfn) that is easily misunderstood (we are sitting here trying to figure it out) and misused. I would expect a template to use more generic tagging and then the designers use more specific tags as appropriate for their case rather than the other way around. I think for the case of the WC product slider, I would remove the nested figures (See W3 figure example 33 and 34) and either follow example 34 or use a figure for each image and not as a wrapper. If my image slider only has one image it does not really make sense to have a nested figure.

**Comment by jameskoster** [comment]
> (we are sitting here trying to _figure_ it out)

I see what you did there :>

Yeah, example 34 is pretty much what I was getting at with my previous comments. The images would still need wrappers, but we can swap those existing `figure`s to `div`s.

> Will the section content still make sense if I completely remove the figure content?

If by "section content" you mean the product description etc, then yes, it still makes sense.

The example I always liked for using the `figure` tag was an instruction manual (e.g. for legos or flat-pack furniture or something). The instructions will still make sense on their own but the accompanying figures/diagrams greatly enrich them. That relationship feels pretty similar to what we're doing with the product description/gallery. They're not just 'random' images plonked on the page. So I'd defend the use of the wrapping `figure` at least.

**Comment by kellychoffman** [comment]
> I'm not really sure we should compromise WooCommerce for what is honestly a theme issue. Nesting figures is perfectly fine and themes should account for that in their css. Was a particular theme causing you issues?

I hear your point, but can also see how many themes would not having a style for `figure`. Going with a `div` would make WooCommerce more theme-friendly now and down the road.
