### ISSUE TITLE
Price Filter ignores taxes 

### ISSUE THREAD

**Issue by TypeT** [woocommerce/woocommerce#13607]
I'm including **tax value** with product price but the **Price Filter** still displays minimum price without taxes and maximum price without taxes

**On shop page product price is correct** 
**I'm Using Only Simple Produts**
**Woocommerce version 2.6.14**
**Wordpress version 4.7.3**

Tested on two different themes 
1: Total Theme
2: Storefront Theme

I have found some old issues from 2014-15 saying that is impossible to be fixed

**Comment by mikejolley** [comment]
> I have found some old issues from 2014-15 saying that is impossible to be fixed

Were you expecting a different result for some reason now?

We plan on removing the price filter in favour of price banding in a future update because thats more performant and controllable. You didn't give steps or settings to reproduce the above btw so as for your issue vs what should happen I cannot really help.

**Comment by mikejolley** [comment]
![2017-03-16 at 11 21](https://cloud.githubusercontent.com/assets/90977/23993981/bbd9e674-0a3a-11e7-9758-301c4061562c.png)

![2017-03-16 at 11 21](https://cloud.githubusercontent.com/assets/90977/23993989/c66c60a8-0a3a-11e7-91f2-b0a23ed15065.png)

It does attempt to add taxes to the prices but this affects the max only.

https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-price-filter.php#L92-L108 It can only guesstimate based on standard rate taxes because the 'inclusive tax' price is not stored anywhere - it's calculated during checkout.

I mentioned above, we want to remove this at some point in favour or price brackets anyway.
