### ISSUE TITLE
Automatic mapping for common field names

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13622]
Research a variety of common CSV export formats and automatically map them.

Need to research if these have a CSV export, but look into:

- Shopp (http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/2500599-import-data-from-shopp)
- WPEC
- Shopify

**Comment by claudiulodro** [comment]
[Here's the Shopify CSV schema and a sample CSV file.](https://help.shopify.com/manual/products/import-export#product-csv-file-format)

**Comment by mikejolley** [comment]
This is on hold; focussing on the single supported format and getting feedback first before committing to this issue.

**Comment by johndcoy** [comment]
To help with this process I created a branch with mappings for some Shopify fields:

**Comment by johndcoy** [comment]
I created the mapping for default fields:

https://github.com/woocommerce/woocommerce/pull/23255

There is an issue with products being marked as `private` since there is not a *Published* column in the default shop apply CSV.

@mikejolley also, it's nearly impossible to import variations without adding columns and assigning SKUs so would it be best to open a new issue to introduce a wizard of sorts?

@dsmithweb Has a detailed breakdown of what's required. He can share the details that could help intro duce automation.

**Comment by mikejolley** [comment]
@johndcoy I don't think we want a wizard here--seems out of scope. We'd need to map only and handle any odd scenarios automatically if the format is supported.

If the CSV is not in an importable format, it would have to be edited by the user...

**Comment by mikejolley** [comment]
This was my abandoned attempt https://github.com/woocommerce/woocommerce/pull/15976/files

**Comment by mikejolley** [comment]
See Shopify import PR in progress here https://github.com/woocommerce/woocommerce/pull/23255
