### ISSUE TITLE
Downloadable product file fields cannot handle relative paths

### ISSUE THREAD

**Issue by ksdhans** [woocommerce/woocommerce#13750]
NOTE: I'm not sure if WooCommerce is the right module to file this against, but I'm not sure exactly where the download_object->file_exists() code is. A quick search in the core WordPress code didn't find it. Feel free to redirect this issue as appropriate.

## EXPLANATION OF THE ISSUE

Basically, if the URL for a downloadable file doesn't include the full domain, then you get a "The downloadable file <filename> cannot be used as it does not exist on the server" error. This causes serious trouble if you have the "Relative URL" plugin installed. 

The trouble occurs in /includes/abstracts/abstract-wc-product.php, on line 1163 where it calls download_object->file_exists(). The file_exists() function isn't handling relative URLs. 

You may think there's no real issue here, but file_exists really should be able to handle relative URLs. Relative URLs are commonplace on other systems, and fully supported by browsers.

## STEPS TO REPRODUCE THE ISSUE

1. Create a "virtual" and "downloadable" product
2. In the download section, click "Add file"
3. Add a file to the product using the "Choose file" button
4. Now remove the "https://domain" part so you're left with a path relative to the root (i.e., "/<path>"). NOTE: You can also use the "Relative URL" plugin to do this automatically
5. Save/update the product
6. You'll see the "does not exist" error message, 

## SYSTEM STATUS REPORT

NOTE: It really is the Relative URL plugin that triggers the issue by making all URLs relative. I've tested this, so you can ignore the other plugins.

```
`
### WordPress Environment ###

Home URL: https://localhost/ksd/store
Site URL: https://localhost/ksd/store
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ

### Active Plugins (4) ###

Enhanced Media Library: by wpUXsolutions – 2.4.4
Relative URL: by Tunghsiao Liu – 0.1.5
Woo Checkout for Digital Goods: by Multidots – 1.5
WooCommerce: by WooThemes – 2.6.14

```

**Comment by mikejolley** [comment]
This isn't a flaw with WC, it's a flaw with your "relative" paths. A path starting with `/` is relative from the home directory, not the directory containing WordPress on your server.

http://stackoverflow.com/questions/7613274/why-would-a-developer-place-a-forward-slash-at-the-start-of-each-relative-path

`/wp-content/uploads/something.png` works in the browser because it's relative to the site root.

`/wp-content/uploads/something.png` however when detecting if a file exists fails, because the true path is something like `/srv/www/wordpress-develop/public_html/src/wp-content/uploads/something.png`

Solution: use the full path when you define your download paths.

I can try adding a workaround to detect this scenario but it's not really a bug.

**Comment by robrecord** [comment]
The fix applied here is hard coded to use `'/wp-content'` which doesn't work if you're using Bedrock or another framework where the path to the wp-content directory is different. In Bedrock, the URL is `/app/` instead of `/wp-content/` and hence detection of files doesn't work when selecting a file from the media library.

**Comment by atoupet-toki** [comment]
Any fix for this ?!
