### ISSUE TITLE
TypeError: a.cookie is not a function

### ISSUE THREAD

**Issue by dixitadusara** [woocommerce/woocommerce#13787]
Uncaught TypeError: a.cookie is not a function
    at HTMLDocument.<anonymous> (cart-fragments.min.js?ver=2.6.14:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

When i load my page this error display in console.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This usually happens when you have 2 versions of jquery being loaded on your page, commonly caused by trying to use google for jquery or themes. This needs to be removed. You cannot reproduce this one with a clean install.

After checking that and confirming jquery is loaded correctly, once, see https://docs.woocommerce.com/document/jquery-cookie-fails-to-load/

**Comment by dixitadusara** [comment]
This is my product page link 
https://rhrswag.staging.wpengine.com/product/eibach-conventional-front-springs/?attribute_height=5.5%22+x+9.5%22+Tall&attribute_rate=950

Only 1  jQuery included in my page. but still it generate a.cookie error. can you please tell me what is the exact issue.

**Comment by mikejolley** [comment]
Well for one thing, the "cookie fix" plugin you're using is not using the script WooCommerce core uses or needs https://rhrswag.com/wp-content/plugins/woocommerce-jquery-cookie-fix/jquery_cookie.min.js?ver=1.3.1

**Comment by logixtreeCode** [comment]
Seems like a recent change from jQuery Cookie to Vanilla JS cookie https://github.com/js-cookie/js-cookie in woocommerce

but the cart-fragment.min.js is still using it through jquery. What you have to do is reminify the cart-fragment.js

Might be an update issue from wordpress repo. 

Running woocommerce 3.0.1, The issue is fixed by above. 

For more info : https://github.com/js-cookie/js-cookie 

Regards,
Team LogixTree

**Comment by wpsupprt** [comment]
Thx logixtreeCode  - saved the day

**Comment by vikili** [comment]
So How Can I Fix This Issue.

**Comment by eirabie** [comment]
I'm having this issue too, and only one jquery is being loaded

**Comment by mensmaximus** [comment]
I have seen this issue with plugins that display a 'cookie notice' as requested in Europe. If you have one of those just try to disable it and test again.

**Comment by luiseduardoluz** [comment]
The fix for this problem was found on the woocommerce page https://docs.woocommerce.com/document/jquery-cookie-fails-to-load/ :)
