### ISSUE TITLE
Continuation of issue #13790 bug if category = 0  { no results }

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#13839]
Hi, 
Sorry to join you every day this week, but my application get all products, categories, attributes and almost all the fields we can get .. so i must verify the compliance of the new release.
Im working with Woo 3.0.0 and WP 4.7.1
With my application, WP 4.6.4 Woo 2.6.11 
When i try to get my 'global category' including all the products, i use 
$woo ->get("products", array('category' => $id_category )
with $id_category = 0 and the API returns me all products.
But now, the same "get" returns me nothing.
Do I change for categories? Or you will correct?
Thanks

**Comment by mikejolley** [comment]
Yes there is a difference; it looks like it could be the sanitisation of `category`. It seems 2.6 ignores `category` 0, and the newer versions pass it to the query.

@claudiosanches Might need to look at that.

However, the fix is simple your size. **Don't pass an empty category.** There is no such thing as 'global category, or category 0. If you pass no `category`, it returns all products without a category filter.

**Comment by mikejolley** [comment]
From your other issue:

> Ok ... i'm just trying to replace 'category' by 'categories' and it works...but what is the correct term

There is no `categories` prop. It's ignored. Gives the same results as passing NO filters.

**Comment by claudiosanches** [comment]
There is no "zero global category", you are exploring a bug in 2.6 that has been fixed in 3.0.
If you want to get all products you should not include any `category`.

**Comment by WaldenStew** [comment]
Ok thanks yous very much for your help ... i probably post an other ticket in the morning because i have an other problem with the get attributes terms.
