### ISSUE TITLE
How to authenticate for Woo commerce REST API  

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#13838]
I have enabled REST API from wp-admin and generated Consumer Key and Consumer Secret but I don't know why am always getting `401 Unauthorized ` error when testing API from Postmen.

GET  `https://my-domain/ktest/wp-json/wc/v1/customers`

![image](https://cloud.githubusercontent.com/assets/26181331/24493538/c12d32a8-154c-11e7-97d3-d9399416e567.png)

**Comment by ghazalejon** [comment]
[Claudio Sanches](https://github.com/claudiosanches)  thank you for your answers in [post](https://github.com/woocommerce/woocommerce/issues/13834)
But the problem did not exist in previous versions (wc version 2.6.x    -  /wp-json/wc/v1/products)
This problem was created after the update to  wc version 3.0.x
This server has no problem with the previous version
Please send video configuration and testing this version the server
![22](https://cloud.githubusercontent.com/assets/10259185/24497106/909f0b22-154f-11e7-85a9-5ac68daca273.jpg)
![33](https://cloud.githubusercontent.com/assets/10259185/24497107/90a02192-154f-11e7-8299-1f6cb8f8afdf.jpg)
![11](https://cloud.githubusercontent.com/assets/10259185/24497108/90c61762-154f-11e7-98ea-b395fe3d1287.png)

**Comment by mikejolley** [comment]
@ddhara Please see https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API 

@ghazalejon The code uses the server `time()`. Maybe look into that?

```
$valid_window = 15 * 60; // 15 minute window.

		if ( ( $timestamp < time() - $valid_window ) || ( $timestamp > time() + $valid_window ) ) {
			return new WP_Error( 'woocommerce_rest_authentication_error', __( 'Invalid timestamp.', 'woocommerce' ), array( 'status' => 401 ) );
		}
```

Follow up on your issue here if you find anything https://github.com/woocommerce/woocommerce/issues/13834.
