### ISSUE TITLE
Product pages no longer show image meta Title on hover

### ISSUE THREAD

**Issue by cnelsonjeffers** [woocommerce/woocommerce#13914]
Image meta Title tooltip no longer shows up on Product page when hovering cursor over the primary product image and Gallery thumbnail images. Image meta Title set in WP Media Library appears to be no longer passed.

**Comment by claudiosanches** [comment]
This was an intentional change and improve for the new image galleries.
If you want to restore the title in the link, you can do in the templates:

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-image.php#L49

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php#L42

cc @jameskoster
