### ISSUE TITLE
Variation descriptions no longer render shortcodes.

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13949]
Works in 2.6, but not 3.0. Test with a [product] shortcode.

**Comment by DanielSantoro** [comment]
To add to this, it also doesn't render any HTML that may have been added. 

**In 2.6.14:**
![http://cld.wthms.co/MCr6](http://cld.wthms.co/MCr6+) 
Full Size: http://cld.wthms.co/MCr6

**In 3.0:**
![http://cld.wthms.co/Ox76](http://cld.wthms.co/Ox76+) 
Full Size: http://cld.wthms.co/Ox76

The word "red" in the second screenshot should be colored - using the same formatting on both installs.

-----

556674-zd-woothemes

**Comment by claudiosanches** [comment]
@DanielSantoro your issue is a different one, the original here is only on the output. But what you are reporting in the admin due a new sanitization for this field.
I just tryed to salve `<span style="color: red">RED!</span>` and WooCommerce it's removing it.

**Comment by claudiosanches** [comment]
@mikejolley what @DanielSantoro it's because this line: https://github.com/woocommerce/woocommerce/blob/3fff61ea4ea0e4b38cdc1716440ef549ca7ecb56/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L387

Change done in https://github.com/woocommerce/woocommerce/commit/5f4dbdb7336a3842dab951d0e2b15ba609b872c1
