### ISSUE TITLE
Should factories return empty objects on exception?

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14100]
When you use a function such as `wc_get_product` or `wc_get_order`, if the object fails to load (invalid, wrong post type etc) you'll get back null or false.

If you don't handle this by checking if the object is not false, and then try to call a method e.g. `->get_id()` you will get a fatal error.

What is the factory returned an empty object instead? Method calls would not fail, it would essentially be an empty object, and you can use the `->exists()` method to see if it's a valid product (which has been around for ages but does not have much use if you return null).

Thoughts? Bad idea? This could save some headaches in support.

@thenbrent @justinshreve @claudiosanches @maxrice @pmgarman

**Comment by claudiosanches** [comment]
What could save some headaches in support it's too check if the object exists before use, no matter how, if is by a method of what is returning, since a blank product or order will generate support questions too...

Still I don't like functions returning mixed types, it should return `null` when does not exists or an empty object.
A method like `exists()` should be great in any case for all CRUD classes, for example `WC_Customer` that does not have a wrapper and made the check for you.

**Comment by maxrice** [comment]
I don't have a strong opinion on this. We've generally always made use of `is_callable` or `$object instanceof ...` before calling methods on objects returned from WC core. That said, I can see this being a nice quality of life thing for developers, so I think we'd be fine to shift over to use `$object->exists()` instead of the other checks. If possible though, I'd prefer to see this added in a minor version release and not a patch.

**Comment by pmgarman** [comment]
+1 for an `->exists()` method regardless if the factory functions add this functionality. Let an object determine if it exists in the database. Also +1 for minor release like @maxrice mentioned, but I think semver would already see to that.

I could see pros and cons of returning an empty object. Back compatibility could be an issue, unless maybe a bool argument for returning an new object that defaulted to false was added (example: `wc_get_object( $id, $firstOrNew = false )`)

Similar to `firstOrNew` in Laravel (which I do use regularly). https://laravel.com/docs/5.4/eloquent#other-creation-methods

Syncing data is one scenario where it may be useful. Looping through objects, use this function to get an object or create a new one if it doesn't exist, update the meta, save it which either will insert a new object or update an existing one.

Could also create some messy scenarios if not done well.

**Comment by mikejolley** [comment]
@claudiosanches The good thing is `exists()` is already used in core in many places.

@maxrice This is labelled major, could be minor, defo not patch.

@pmgarman "Could also create some messy scenarios if not done well" examples?

**Comment by claudiosanches** [comment]
@mikejolley as I said, I prefer anything than use mixed types, returning `false` there really bothers me.

**Comment by pmgarman** [comment]
Messy may not be the best word, more _unclear_ which could lead to confusion for some devs? Just trying to think through all the areas that may pop up, I've done all I could to attach my name to a far bigger breaking change so I am doing what I can to _not_ break things too much anywhere else, _yet_ :D

scenario: importing orders

$order = wc_get_order( 123 );

Returns an empty object, it's an import script so now we are trying to import order 123 and we got back an empty object we fill with our data and save. Oops the next post ID in WP is actually 321, we imported order 123 as 321 because of an assumption that it was setting the new object's ID as the ID we were looking for.

**Comment by thenbrent** [comment]
If 3rd party developers aren't checking `is_callable()`, I doubt they'll check `->exists()`, so the next question (that @pmgarman is already jumping too above) is what you do with methods on the returned empty object, especially those from custom classes that aren't known in advance.

Do you always return something from those methods in case a return value is expect? If so, is it `''`/`false`/`null`? Or should a standard object be returned in case the return value for that unknown method is being used blindly as an object also (which is the case for things like `WC_Subscription::get_last_order()`)?

It's a bit of a pain but not a major issue to check `is_callable()`, though it's obviously not as clean as reliably having an instance of an object.

The discussion of returning `null` for `get_date_{date_type()` APIs all applies here too obviously.

> if the object fails to load (invalid, wrong post type etc) you'll get back null or false.

Returning `false` from those methods isn't new. IIRC the validation just got stricter in 3.0. So if the goal is to reduce support load from this, not to provide a nicer set of APIs for developers, that validation could be the focus of review instead.

In a similar vein, it's pretty common I have this in my dev environment: https://cl.ly/1G0H1R0I2Q1j

While it would be really nice to have consistent return values added in a major version in future, maybe a minor release could do something to offer logging and/or throwing the exception when `WP_DEBUG` is set to help developers discover this issue prior to release (though they would still need to access a deleted object to trigger those and would already be seeing a fatal error from that if they come across it in testing, it's just harder to trace because the exception is caught).

**Comment by mikejolley** [comment]
Ok, lets leave it :) @claudiulodro was putting in a PR to return null vs false for 3.1.

**Comment by vishal-px** [comment]
Hi @mikejolley 

- I have created a script that calculates the vendor commission and updates meta_key in wp_postmeta table.
- The script is at WP root directory. and executing using CRONJOB.
- In that script, the wp inbuilt functions[ get_posts(), get_post_meta(), etc ] are working, but the Woocommerce functions like wc_get_order($post->ID), wc_get_product($product_id), etc returns null value. I set static value in wc_get_order(507788) but still its return null. And orders of this orders Id(507788) is showing me at admin panel in orders.

I'm using Woocommerce version: 3.3.4
Have you got any solution?
Need a help/solution.

Thanks.
