### ISSUE TITLE
 Price display suffix issue for variations (WooCommerce 3.0.1)

### ISSUE THREAD

**Issue by nash4ever** [woocommerce/woocommerce#14143]
Price display suffix message does not show for variantions in the shop.
I works well for simple products.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L121

> Note: Variable prices do not show suffixes like other product types. This
> is due to some things like tax classes being set at variation level which
> could differ from the parent price. The only way to show accurate prices
> would be to load the variation and get IT's price, which adds extra
> overhead and still has edge cases where the values would be inaccurate.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L159

> This is skipped if the suffix
> has dynamic values such as {price_excluding_tax} for variable products.

This is intentional - these values cannot be shown accurately since they depend on the variations themselves.
