### ISSUE TITLE
Variation Problem no working and conflict with theme zoom feature

### ISSUE THREAD

**Issue by Alexlim91** [woocommerce/woocommerce#14192]
Dear Woocommerce Author,

Currently I am facing conflict problem between woocommerce 3.0.1 variation and theme zoom conflict. Here is the sample of the product http://www.shopbuzz.com.my/product/iphone-66p77p-soft-back-casing/ 
When I select an option of the product then the featured image of that option was no showing. Currently the theme that I using has 4 zoom style, when using default zoom the variation working but when using other 3 zoom style the variation no working. 
Then I got contact to theme author they mentioned not their theme problem is because of woocommerce 3.0.1. Before update it working well. 

Thank You

**Comment by mikejolley** [comment]
> Then I got contact to theme author they mentioned not their theme problem is because of woocommerce 3.0.1. Before update it working well.

This is advertised as a WC theme so it is their problem to test and address https://themeforest.net/item/emallshop-responsive-multipurpose-woocommerce-theme/18513022 I'm sorry you're caught in the middle.

Core changes these elements with the image (which works with our built in gallery):

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L547-L593 

Custom scripts would need to handle this event too if custom scripts need other images updated.

TBH there is no point in using a custom ZOOM script with 3.0.0 since we handle it. Maybe the theme should use ours.

Please let the author know about this issue. If they'd like to comment they are welcome, but this is not our issue to fix.
