### ISSUE TITLE
Hook to filter formatted order item meta array

### ISSUE THREAD

**Issue by bitadvisor** [woocommerce/woocommerce#14200]
Pre-3.0 WC allowed formatted meta to be filtered via the `woocommerce_order_items_meta_get_formatted` hook in `WC_Order_Item_Meta::get_formatted`. This functionality is not available in 3.0.

There should be a filter for `$formatted_meta` in `WC_Order_Item::get_formatted_meta_data`.

**Comment by mikejolley** [comment]
That is deprecated https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/class-wc-order-item-meta.php#L141

There are other hooks to control meta output in other places, such as `woocommerce_display_item_meta`. So whilst there is no direct replacement, it shouldn't be needed in order to customise this.

If I'm wrong, file a PR with details on WHY you need such a hook and we can consider for 3.1

cc @claudiosanches

**Comment by josk79** [comment]
I would also be interested in this. For certain meta data I need to change the `display_key` depending on context.

`woocommerce_order_item_display_meta_key` and `woocommerce_order_item_display_meta_value` could be used for this if the $meta and and item would be passed as 2nd and 3rd argument.

I.e. replacing this: (in `WC_Order_Item::get_formatted_meta_data`)
```
$formatted_meta[ $meta->id ] = (object) array(
    'key'           => $meta->key,
    'value'         => $meta->value,
    'display_key'   => apply_filters( 'woocommerce_order_item_display_meta_key', $display_key ),
    'display_value' => wpautop( make_clickable( apply_filters( 'woocommerce_order_item_display_meta_value', $display_value ) ) ),
);
```
by this:
```
$formatted_meta[ $meta->id ] = (object) array(
    'key'           => $meta->key,
    'value'         => $meta->value,
    'display_key'   => apply_filters( 'woocommerce_order_item_display_meta_key', $display_key, $meta, $this ),
    'display_value' => wpautop( make_clickable( apply_filters( 'woocommerce_order_item_display_meta_value', $display_value, $meta, $this ) ) ),
);
```

Using `woocommerce_display_item_meta` for this would be cumbersome as this is a concatenated string containing html tags.

What do you think?
