### ISSUE TITLE
Suggestion: Carry "layered nav" selections through to single-product pages

### ISSUE THREAD

**Issue by mattkersley** [woocommerce/woocommerce#14201]
Currently, layered navigation selections (filters) aren't carried through to the single-product page.

As a user, I think it's a reasonable expectation not to have to set these all again once on the single-product page.

While it's not a major issue for the project I'm working on, this could be frustrating for end users who rely heavily on filters to narrow their products down?

**Comment by pmgarman** [comment]
+1

short version: take layered nav args, filter product urls, pass args using the appropriate attribute names to the product pages.

**Comment by eddPragmatic** [comment]
+1 show of support. You're right, surprised this doesn't come up more often.

**Comment by WPprodigy** [comment]
Mind giving some use case examples for this? I'm keen on looking into it.

If I'm reading this right, the idea is that the attribute terms selected through layered nav widgets are passed along when clicking into a product, and if variable, the terms are pre-chosen. Is that correct?

What happens in a scenario where the widget was using the "OR" filter, and the user selected multiple terms for a certain attribute? Just pick the first one I'm guessing?

This sort of interferes with the "default selections" options/settings, so could lead to unintended behavior for some I'd imagine.

**Comment by eddhurst** [comment]
Key example - if I want to buy a pair of shoes I filter it down by type of shoe, and size. The site shows me everything available, but when I click through it just shows me the shoe, and I have to click again to see the size and confirm the price. Gold standard would be if it could remember my selection, and prefilter the shoe based on my input.

In terms of an OR filter, that's a good point. Perhaps there could be a way to indicate to the user "This item is available in one or more of your search filters". i.e. multiple colours or filters. That perhaps falls out of the scope of this feature request, as an MVP it could work only on AND and see how it feels.

**Comment by WPprodigy** [comment]
Took a looksy, doesn't seem to be too complex. Though, I'm not 100% sure where something like this would belong.

For background, I added in a new filter called `woocommerce_loop_product_link` to the `woocommerce_template_loop_product_link_open` template function locally, that way when clicking the title/image of the product the attributes can still be passed on, rather than just the button. Not really mission critical, but thought I'd address that before you try the below snippet.

So this snippet will essentially do what is being asked:

```
 add_filter( 'woocommerce_product_add_to_cart_url', 'wc_pass_layered_nav_selections', 10, 2 );
 add_filter( 'woocommerce_loop_product_link',       'wc_pass_layered_nav_selections', 10, 2 );

 function wc_pass_layered_nav_selections( $link, $product ) {
	// Append layered nav filters when possible.
	if ( 'variable' === $product->get_type() && $chosen_attributes = WC_Query::get_layered_nav_chosen_attributes() ) {
		foreach ( $chosen_attributes as $name => $data ) {
			if ( ! empty( $data['terms'] ) && 1 === count( $data['terms'] ) && 'or' !== $data['query_type'] ) {
				$link = add_query_arg( sanitize_title( 'attribute_' . $name ), $data['terms'][0], $link );
			}
		}
	}

	return $link;
 }
```

In it's current form, it is rather opinionated. For example, if more than one term is selected in the widget, then that attribute will not be passed along. And if the "OR" query type is being used for the widget, the attribute will not be passed along. There are ways around these, but a decision would need to be made on how best to handle it.

WooCommerce core already supports passing attributes into a variable product page, you'll see this functionality if you add a variation to the cart, then click on it from the cart. The above snippet pretty much just mocks that functionality.

I haven't submitted a PR yet, because like I said, I'm not 100% sure where something like this would belong. I started out by created an `add_to_cart_url` method for the `WC_Product_Variable` class, but that turned out to not be a great idea per the need for the other filter.

**Comment by mikejolley** [comment]
@WPprodigy Looks promising. Perhaps this should start as a snippet rather than core then? If it's added to the docs, we can put it on the ideas board and see how many votes it gets?

**Comment by mikejolley** [comment]
So above there is a concept for this so with the new filters we know this is possible.

Whats not clear is how much demand there is for this. I can find no such requests on the ideas board, and this was the first request via Github.

As such I'd prefer this was made into an extension @WPprodigy 

I have however logged an idea here http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34000132-carry-layered-nav-filter-by-attribute-selectio so if it does end up getting a high number of votes we can reconsider for core, and possibly tie into the product custom table work which makes attribute/filters more performant.

Thanks
