### ISSUE TITLE
Error 500 after "copy product"

### ISSUE THREAD

**Issue by bennywhite87** [woocommerce/woocommerce#14397]
At WC3 (i use WC 3.0.3) i have following Issue:

- Create Product

- Product is SAVED & LIVE

- Copy Product into a new Product
Here is the Issue. It's loading and then the Server get's an Error 500. The Copy of the product is placed, but i need to go to the products site in my backend to see it.

**Comment by claudiulodro** [comment]
We need a copy+paste of the system status report at WooCommerce > System Status in order to troubleshoot this.

We also need the specific PHP error causing the 500 error. Error 500 is too generic. To get a real error message one has to look at either the server error logs, or enable WP_DEBUG. Nothing we can do with just the info you've provided.

**Comment by AntBentinck** [comment]
I'm also getting this but unable to generate a system report as getting 500 error on that also. the page itself loads but wp-admin shows error 500 in console.

**Comment by mensmaximus** [comment]
Check your hosting providers error.log. It will reveal the source of the problem.

**Comment by mikejolley** [comment]
What @claudiulodro said ^ Without more info, and without being able to replicate, there is no action that can be taken. Comment back if you can find out more from the error logs and I'll reopen if needed.

Again, error 500 is a generic message servers output. The real error message (which we'd need) is in the php error log.
