### ISSUE TITLE
Product gallery not aligned to product image

### ISSUE THREAD

**Issue by ddipaola** [woocommerce/woocommerce#14418]
Using Woocommerce, Divi theme and on my product page, the product image and the product image gallery are misaligned on the left hand side but aligned on the right hand side.   See Example

![image](https://cloud.githubusercontent.com/assets/27590418/25067631/476f020c-2217-11e7-824f-1dbb5bc484b2.png)

I would like the product image gallery to be aligned on both sides and have equal spacing between thumbnails.  This use to occur before the update to Woocommerce 3.0.  I have disabled the zoom function.  

Is there CSS code to do this or do I need to modify one of the php files to accomplish this?

**Comment by mikejolley** [comment]
Without a link to the page I cannot check the CSS.

**Comment by ddipaola** [comment]
https://www.storyinart.com/product/it-happens-to-the-best-of-us/

**Comment by wpexplorer** [comment]
@ddipaola - This is a theme related issue, but you can fix it easily with the following custom CSS added to your site at Appearance > Customize > Additional CSS:

`.woocommerce div.product div.images .flex-control-thumbs { margin-left: 0 !important; }`

You should submit a ticket though with Elegant Themes as they may not be aware of the issue so that they can fix things accordingly.

**Comment by ddipaola** [comment]
Great worked perfect.  Thank you.
