### ISSUE TITLE
Add Helper Function for Star Ratings

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#14426]
### EXPLANATION OF THE ISSUE

Currently there are multiple locations that display star ratings: templates/single-product/rating.php, templates/single-product/review-rating.php, includes/widgets/class-wc-widget-rating-filter.php....etc.

If one wanted to alter the look of the star ratings (requiring html edits) it would require overriding a lot of files. Having a simple helper function (with a filter on the output) such as woocommerce_star_rating_output( $rating = '' ) would allow for easier modifications and also follow the DRY principle.

Thank you for considering ;) If wanted I could push out a pull request for this, unfortunately I messed up recently so my forked repo has edits from another pull request I submitted as I forgot to make a new branch so It would have to wait once that's pulled or rejected.

- AJ

**Comment by mikejolley** [comment]
`wc_star_rating_html` needed.

**Comment by avinapatel** [comment]
@mikejolley 

I have added "wc_star_rating_html" filter. 

Please see the PR #14464 for this.

Thanks,

**Comment by emgk** [comment]
@wpexplorer @mikejolley While fixing the issue I found that there is 'wc_get_rating_html' helper function already available inside https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L2536 file to get the HTML for rating. Also, it has a filter 'woocommerce_product_get_rating_html' to modify the output content on return statement. 

@mikejolley Instead of creating a new helper function, can't we replace 'wc_get_rating_html' function wherever we are showing the rating content? Need your suggestion.

**Comment by mikejolley** [comment]
A function containing the filter would be better IMO

**Comment by emgk** [comment]
@mikejolley 'wc_get_rating_html' function has filter to modify HTML content.

**Comment by wpexplorer** [comment]
@emgk - Nice I totally didn't see the existing 'wc_get_rating_html' function (I'm blind). Would be good to use the existing function in the various template parts currently not using it. Good find!
