### ISSUE TITLE
Shipping Zones are broken

### ISSUE THREAD

**Issue by extrapixel** [woocommerce/woocommerce#14420]
Not buggy - but broken in concept. IMO the zones should not match from top to bottom - but all zones should match which match the address.

If this behaviour is not wanted for some reason - it should not be possible to add a country to multiple zones. In my opinion the possibility to do so implies that multiple zones should match.

**Comment by mikejolley** [comment]
Thanks for sharing your opinion, but there are several use cases your solution does not solve.

The current setup allows for exclusionary rules. This for example:

![2017-04-16 at 10 32](https://cloud.githubusercontent.com/assets/90977/25070201/0df065a6-2290-11e7-869e-1e21fd2067a5.png)

In these cases, to work with your logic you'd need to define every single postcode in the UK aside from the excluded ones in one zone, and the excluded postcode in it's own zone. Thats way more work - there are hundreds of postcodes.

Plus, changing this now would break all current implementations. Hope that makes sense. If you have suggestions to make the current way clearer, let us know.

**Comment by extrapixel** [comment]
thanks @mikejolley I understand - but still think it's "wrong". Has there been a discussion about this I can read upon? Discussing it here doesn't make sense of course as it's implemented already. 

But I'm looking for the best way to implement additional shipping methods. Of course these should be compatible with shipping zones - but I just can't wrap my head around how to solve with the current logic without replicating the zones feature inside my shipping methods. 

I've simplified a setup to demonstrate. For simplicity sake let's assume it's all Flat Rate methods and weight is ignored:

Carrier A:
Country 1, 2, 3 = 5$
Country 4, 5, 6 = 10$

Carrier B
Country 1, 2, 5 = 10$
Country 3, 4 = 20$
Country 6 = 30$

Carrier C
all countries: 50$

You see - if all methods would match, I'd need only a couple of shipping zones, each with the respective rates. However, in the current system (top-to-bottom matching) - I see no solution how to implement the above. The only way would be to handle it in the method itself - re-implementing the shipping zones completely inside the method and on system level everything would go into "Rest of the world".

Your example could also be implemented easily if the limit zip-codes feature would accept multiple ranges. Then you'd have 2 zones, one with all the cheaper zip codes, one with all the expensive zip codes. In addition, if you had a second carrier that has one rate for the whole country (e.g. FedEx), you'd just add a third zone with the whole country.

**Comment by mikejolley** [comment]
> Your example could also be implemented easily if the limit zip-codes feature would accept multiple ranges. Then you'd have 2 zones, one with all the cheaper zip codes, one with all the expensive zip codes

This is supported. But there are a tonne of postcodes you'd have to a) know about and b) list. It's not workable. Postcodes are not US zipcodes - they have letters so ranges are not suitable.

> Carrier A:
> Country 1, 2, 3 = 5$
> Country 4, 5, 6 = 10$
> 
> Carrier B
> Country 1, 2, 5 = 10$
> Country 3, 4 = 20$
> Country 6 = 30$
> 
> Carrier C
> all countries: 50$

The shipping method only needs to have the above logic. The USER has control over which zones they want to offer these rates inside, by adding the shipping method to whatever zones are applicable.

Just because a carrier offers rates somewhere, does not mean the user has to offer those rates everywhere.

**Comment by extrapixel** [comment]
> they have letters so ranges are not suitable.

I see. makes sense. 

> Just because a carrier offers rates somewhere, does not mean the user has to offer those rates everywhere.

Agree. Probably I just have a different perspective as a small shop selling worldwide, using multiple carriers with multiple zones and multiple rates. The shipping zone feature seemed like a relief in all this plguin-mess we're in right now. But it turns out it doesn't help much in its current state.

There are some very simple setups, in my opinion quite real-world examples that can't be done with the current implementation. All flat rate methods:

Fast Carrier:
Country 1, 2, 3 = $10

Slow Carrier:
Country 1, 2 = 5$
does not ship to country 3

Note - I'm using 3 countries in the example - in the real world it's 80+ countries. Your point is, this needs to be handled in the plugins and can't be achieved with simple flat rates?

> Plus, changing this now would break all current implementations. Hope that makes sense. If you have suggestions to make the current way clearer, let us know.

Makes total sense. But, I doubt it can be made much clearer, because it seems kind of an un-intuitive way to do it. I do have a suggestion however. Let the users decide. Above the shipping zones in the backend, there could an option:

Match shipping zones: first | all

This would not break existing implementations and would allow for a more global perspective.

Besides the exclusive example you gave, are there other reasons for this - in my opinion - quite limiting implementation? Performance? Protecting sales of the Woo shipping plugins?

**Comment by mikejolley** [comment]
> Protecting sales of the Woo shipping plugins

Why would this even be mentioned? Zones are a unique thing; the paid shipping methods don't enhance them.

> Besides the exclusive example you gave, are there other reasons for this - in my opinion - quite limiting implementation?

Back at you, what can't you do with current zones vs your proposed change?

**Comment by extrapixel** [comment]
> Back at you, what can't you do with current zones vs your proposed change?

The following is not possible. Try to implement this with Flat Rates:

Fast Shipping (carrier A):
- Country 1, 2, 3 = $10

Slow Shipping (carrier B):
- Country 1, 2 = 5$
- B does not ship to country 3

( i know this is easy with 3 countries with duplicating the methods. But think many countries - 4 carriers instead of 2 etc).

> Zones are a unique thing; the paid shipping methods don't enhance them.

I think it's the other way around. Shipping zones should enhance the shipping plugins (all of them, not just Woo's). So not each of them has to implement their own zones-feature. But I guess here is my fundamental misunderstanding of the new shipping zones features. I maybe wrongly assumed it was added to simplify existing shipping plugins - to give a new standard building block that plugin developers can build upon. But as it is now, I can't think of any real world setup where it would work without any custom plugins - except maybe local niches like your UK example. Back to the plugin mess i guess...

**Comment by mikejolley** [comment]
>  Try to implement this with Flat Rates:

For flat rates, this would take 2 zones (country 1 and 2, and country 3). 1&2 zone would have 1 method (carrier A). 3 zone would have 2 methods (carrier A and carrier B) if this was a user choice.

A custom plugin however implementing carrier logic for both carriers A and B wouldn't need to do this because the "B does not ship to country 3" and price logic would be in the plugin. If say you added this custom method to the 1 'rest of the world zone', the method still gets told which country the package is shipping to, so the price logic is done at that level.

**Comment by extrapixel** [comment]
Thanks @mikejolley . So it must be handled within a custom plugin (again, I know with 3 countries it's simple as we both pointed out - think much more countries).

Not sure if you noticed the update of my proposal in an earlier comment: If there was a switch to match

-first (top-down, like now)
 OR
- all

My simple case would not need any custom plugins but could all be handled within the core methods.  

Would you not see any advantage of such an option (match all / match first)? Compatible with existing implementation (would not brake anything) and adding a complete degree of flexibility.

**Comment by mikejolley** [comment]
TBH I prefer decisions over options, especially with something like zones which is already quite complex.

**Comment by garym210** [comment]
@mikejolley I am new here, I am having an issue with shipping zones randomly default a domestic order to international shipping at checkout. I am using all flat rate shipping. I have searched all over and not found any similar issues. Any suggestions?

**Comment by tjvargas** [comment]
@mikejolley In another words, I think that we need instead of a default Location, a default shipping method. Because:

- If we have 30 shipping zones, 4 equal shipping method each, and 1 shipping different method each. We need manually create (and config) 5 shipping methods for each zone.

- When you need to edit this (the value for example), you will need to edit 30x1 times the same shipping method.

- I do not see a other way to fix this without a lot of work. Mainly because of the database and how it was done.

So, Its my suggestion, a default shipping methods instead of a default zone (we dont need this at all). And when the system is to select the delivery methods available for that zone, it makes available the union of what is inside the shipping zone with what is in the default zone (Now called default shipping zones). And maybe join only shipping methods with different name. With this we would have as an example, with 2 zones:

1. Zone London with:
- Flat Rate Alpha; (18$)
- Local Pickup;

2. Zone UK with:
- Local Pickup

Default Zone (that we now call Methods):
- FEDEX
- Flat Rate Alpha;  (25$)

When a person from London makes the request, she get the following options:

1. Flat Rate 1 (18$)
2. Local Pickup
3. FEDEX;

When a person from UK makes the request, she get the following options:
1. Local Pickup
2. Flat Rate 1 (25$)
3. FEDEX;

Thank you.

**Comment by extrapixel** [comment]
@tjvargas Yes - if you have multiple carriers with non-equal shipping zones (e.g. for pricing) like FedEx - you'll end up copying a lot of shipping methods. Even the simplest setup results in dozens of shipping methods with most data duplicated.

Solution: use the Advanced Shipping plugin. I too would prefer to have this basic functionality in WC itself - but if you don't want to have an non-manageable amount of duplicated shipping methods, there's no way around using dedicated plugins.

**Comment by flexrc** [comment]
So here is the story, I've updated Woocommerce CanadaPost plugin and found out that now it is implemented within shipping zones, ok cool!

Here is the issue:
I have multiple tiny shipping zones because of the different rates for them defined with table rate but they are all within USA.
So now I have to add CanadaPost to each of these zones in order and reproduce settings for each of them, which is a huge pain and kind of against of do not duplicate concept.

So for me in such case I will prefer to have a Shipping zone which will match everything that is related to where I ship from CanadaPost even if other shipping zones are matched at the same time.

If there was some kind of option to achieve, like a checkbox to enable such behavior then it would've be fantastic
