### ISSUE TITLE
Variable product is adding unwanted srcset code to image

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14451]
Theme is using its own resize script but since V 3.0 the variable product is adding unwanted src_set code to the image. Even the original src=”image url” the theme adds as a url with the propper sized image is replaced with product image sized following the woo product display settings for single product. 

Very annoying i must say as now we get blurry images on resize and the theme resizing script is failing because the woo plugin replaces the image url after the theme has resized the image and added the correct url to that resized image.

See image below the variable product is ok ! Variable product image has src_set code added

![variable-product](https://cloud.githubusercontent.com/assets/6078370/25088375/3af5746a-2376-11e7-9f1f-246c9d5e87b5.png)

The theme resizing script the theme uses fails because of this. Pls also add data-thumbnail=”[image id]” to the img tag  where [image id] is the id of the image after swapping the selected variant image! This way we can use that data to do our stuff by js code !

Even in the default wp theme setting a product image to 294 x 294 creates blurry images. Besides that: Why not use the original image above 294px? It is part of the src set code. Why is there a max_width set to 294 px and is this image used for all the viewpoints above 294px? And why is the original image url part of the code and not used? Now  one has to use regenerate thumbnails in order to fix this.

Why is there not like the product-image.php or a filter for the creation of the variable product images? So that we have full control of that image as well. Now woo is just grabbing the default images that are generated by the woo image settings for display single products image. But woo provides a products.image.php for any normal product to overrides that image. Pretty useless when using variable products as then woo is then replacing the image url in the product-image.php by javascript without respecting what we already added in there by our custom product-image.php

To me this feels like a bug !

**Comment by mikejolley** [comment]
src_set  is something WordPress adds and supports to all thumbails, when using WordPress functions to output images. Variations _need_ to set/update this value on image change otherwise the actual `src` of the variation image would never be used.

> Theme is using its own resize script

Why?! If you define image sizes you can let WordPress handle it. 

https://alistapart.com/article/responsive-images-in-practice

Or disable/change how it works: https://wordpress.stackexchange.com/questions/211375/how-do-i-disable-responsive-images-in-wp-4-4

If you have a better idea for supporting srcset and your changes, without breaking existing usage, please submit a PR for review.

Also, you can filter variation images/src before they are used here: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L276

Hope that helps.

**Comment by BackuPs** [comment]
Hi

Thank you for the answer. Of course we already knew how to disable responsive images but  i have one question left though... if wp is adding the srcset then why is that code not there when it is not a variable product?

Thank you !

**Comment by mikejolley** [comment]
All product type images have srcset..at least on my install.
