### ISSUE TITLE
Shop Page slug Name change

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14452]
After changing the slugname of the shop page which already has been set as the shop page in the woo display settings that page will not list or show any products.

Even when changing temporarily the shop page in the woo settings to another page, save the settings and set it back to the shop page with the changed slugname that page will never show any products.
One has to create a new shop page and set that page as the shop page in order to get the products back in the shop.

Looks like a bug to me.

**Comment by mikejolley** [comment]
The 'shop' page is actually a custom post type archive. The page just acts as a placeholder. If you did make such a change you'd have to go to Settings > Permalinks and save so the structures are updated.

It may be unreliable to flush this after page save but I'll give it a go. This is not something new in 3.0 however so punting to 3.1

**Comment by claudiosanches** [comment]
@mikejolley "It may be unreliable to flush this after page save but I'll give it a go."

In fact we already try to do it.

https://github.com/woocommerce/woocommerce/blob/5eab267ec1df635a2669b305e89e7e2b101edf7a/includes/wc-core-functions.php#L793-L802

But `save_post` is too soon and need to save the page twice to make it work.

So is a bug since we have a code for it that don't works :P
