### ISSUE TITLE
woocommerce_rest_cannot_view with status 401 (Python)

### ISSUE THREAD

**Issue by gauravrajput14** [woocommerce/woocommerce#14487]
I've been trying to list products on WooCommerce by 2 different methods:

1. Python WooCommerce API module
2. Postman

Both methods stated above return a 401 error. The Key and Secret were generated using the `/wc-auth/v1/authorize` endpoint with permissions to Read/Write. The exact message that I get is - 

`{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}`

Here is some detailed info on how I'm trying to list the products **using Python** - 

`wcapi = API(
        url=usersearch["url"],
        consumer_key=userkey,
        consumer_secret=usersecret,
        wp_api=True,
        version="wc/v1",
        timeout=50,
        query_string_auth=True
    )`

Removing `query_string_auth` doesn't help.

Here is some detailed info on how I'm trying to list the products **using Postman** -

 
![auth1](https://cloud.githubusercontent.com/assets/26098843/25127561/ea21a2c8-2453-11e7-8f87-c4c479677abe.png)
![auth2](https://cloud.githubusercontent.com/assets/26098843/25127562/ea315600-2453-11e7-9720-24ad8474434a.png)

**Comment by claudiosanches** [comment]
Works just fine, this could be several different things.
Like your server blocking requests, or even removing the query strings for oauth.
Have you checked if there is modsecurity or anything blocking requests?
Can you check if all oauth query strings are send to the server?
Are you sure that you are using the correct consumer key and secret?

But closing because I don't see anything wrong with WooCommerce.
