### ISSUE TITLE
Membership Plugin Admin Page Formatting issues

### ISSUE THREAD

**Issue by robertsmoto** [woocommerce/woocommerce#14492]
![membership admin](https://cloud.githubusercontent.com/assets/27731507/25136903/1b116ab0-240b-11e7-941e-a47254b3fe23.png)
### EXPLANATION OF THE ISSUE

Woocommerce v3.0.3 & Woocomerce  Membership by SkyVerge v1.8.2
Conflict with All In One Schema Rich Snippets v1.5.1 by barinstorm see screenshot.
The formatting in the admin area is unusable.
Woocommerce-->Memberships-->Membership Plans-->Add Membership Plan

### STEPS TO REPRODUCE THE ISSUE
Intsall Woocommerce and Pugin Versions above
Conflict with All In One Schema Rich Snippets v1.5.1 by barinstorm see screenshot.

I've resolved the issue. Conflict with plugin as described.
### SYSTEM STATUS

<details>
```
System status okay.

```
</details>

**Comment by mikejolley** [comment]
This is the WooCommerce core bug tracker, but I'll let Skyverge know.

cc @bekarice @maxrice ^ ;)

**Comment by bekarice** [comment]
> All In One Schema Rich Snippets

This sounds like frontend scripts may be loaded in the backend, as I can't replicate this issue with Memberships. Likely needs an update on the All In One Schema Rich Snippets end, but happy to [help via the help desk](http://woocommerce.com/my-account/tickets/).

**Comment by robertsmoto** [comment]
Thank you. SkyVerge doesn't let you submit a support ticket unless you
purchased the product from them, otherwise I would have posted it there.

Thanks for letting them know about the conflict.

**Comment by bekarice** [comment]
@robertsmoto I'm from SkyVerge :) The reason you can't submit a ticket via SkyVerge.com is because no plugins are sold there -- they're all via woocommerce.com. You can always submit a [WooCommerce.com thread number here](https://www.skyverge.com/contact/?form_type=support&purchased=woothemes), but all support is done in the Woo help desk.

To be clear, this likely isn't something Memberships can fix, but happy to confirm via the help desk.
