### ISSUE TITLE
New Product Image Gallery Flawed - Allow Old Lightbox Option

### ISSUE THREAD

**Issue by mattmikulla** [woocommerce/woocommerce#14513]
It seems that the new WooCommerce 3.0 product image gallery implementation was poorly thought out.

The decision to implement the combination of zoom, lightbox and slide was based on polling developers and I doubt little attention was paid to store owners and how stores actually operate.

https://woocommerce.wordpress.com/2016/09/07/the-new-woocommerce-product-image-gallery/

These changes affect conversion rates and sales. This change introduces a completely new variable into the conversion optimization of a page. Not by the store owner's choice.

This new UX functionality was implemented and forced on users without the ability to fall back on how the previous image gallery worked.

The previous lightbox may or may not have been optimal but it was a control and standard.

There used to be selectable checkbox for lightbox image gallery in WooCommerce settings. That is gone. Theme developers built around that including CSS.

It seems that this new image gallery was built for and tested with images that are all 1:1 aspect ratio and square.

Was it tested with featured product images and gallery images that vary in aspect ratio?

Here's an example of how the current implementation goes wrong.

If I have a landscape image with an aspect ratio of 3:2 set as my featured product image.

And I have images in my gallery that are square 1:1 or portrait 2:3.

Then there is a large white space beneath the featured image and above the product thumbnails.

And that white space looks much bigger on a mobile display.

That white space is there to accommodate the display of the selectable product thumbnail that is larger vertically than my 3:2 featured image. 

That has just destroyed by beautiful layout where the thumbnails were nestled vertically up to my featured image creating a nice grid.

Note. This isn't a CSS issue. The whitespace is there to accommodate how the gallery works and the largest vertical image in the gallery.

The only way for this option to look good is if all the images, featured product image and gallery, are all the same aspect ratio.

This is not realistic from a store owner perspective.

Why is there not an option in WooCommerce to use the previous lightbox implementation where you just click on an image and it pops up in the lightbox?

Not all stores are the same and not all product images uploaded will be the same aspect ratio.

One thing I'm not certain about is how much of this is WooCommerce vs the theme being used.

Is the lightbox support that is now implemented in WooCommerce similar to the one provide previously?

Is it a matter of theme developers providing options to disable zoom and slide and only keeping lightbox enabled?

Everyone I have spoken to seems confused and this new implementation is creating problems.

**Comment by mikejolley** [comment]
> It seems that the new WooCommerce 3.0 product image gallery implementation was poorly thought out.

Given this was a community decision, with a planning blog post, voting blog post, and result post, plus testing, that statement is baseless.

> The decision to implement the combination of zoom, lightbox and slide was based on polling developers

It's the "The official WooCommerce development blog" and not just for developers, but anyone who wants to decide on features such as this. The poll was promoted on the user groups/facebook so there were a mix of voters. This was a community decision. 

This is what your above issue should have looked like: https://github.com/woocommerce/woocommerce/issues/14448

In which case I could have directed you to the fix for the spacing issue when using images of different size - https://github.com/woocommerce/woocommerce/pull/14462

And shown you a way to disable flexslider and zoom if not needed on your store:

https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0#disabling-gallery-features

**Comment by Julix91** [comment]
@mattmikulla venting can feel good, but it's rarely the best way to address the problem that was causing the desire to vent in the first place -- and just in general, don't go accusing those building things of malice or carelessness, that just never works out for anyone...

secondly grouping sentences of the same topic into one paragraph would help text-scan-ability, and thus increase likelihood someone will read the whole thing. I tried.

> It seems that this new image gallery was built for and tested with images that are all 1:1 aspect ratio and square.

As you mention later, it works well as long as the aspect ratio is the same, regardless of ratio. Many stores have consistent aspect ratios (some even fill remaining space with transparent or white if they have odd shaped objects. I agree though that not all stores are the same and that the solution should be flexible enough to handle that somehow, so I was happy to know that 3.1 will be out relatively soon and includes a smoothHeight fix.

However, update 3.0 was clearly marked as one that would break compatibility in some places, and the WC team doesn't do that lightly. [Here](https://woocommerce.wordpress.com/2016/08/18/a-new-product-gallery-coming-to-2-7-maybe/) you can read about the motivations behind the gallery. The poll didn't come out of no where - the question was asked, because many were having issues with the existing lightbox.

For future reference, some people wait for the x.1 of major releases (to give plugin and theme developers more time to adjust, and to find and squish new bugs or incompatibility). Maybe something to consider doing in the future if you want maximum stability in your experience.
