### ISSUE TITLE
Add filter for $custom_attributes in wc-meta-box-functions

### ISSUE THREAD

**Issue by ReneLuecking** [woocommerce/woocommerce#14529]
**`$custom_attributes`** are a possibility to add additional attributes to form fields if using a function stored in _includes/admin/wc-meta-box-functions.php_. If you add a filter on this array, it would be possible to add custom attributes to standard product fields, which are generated by WooCommerce itself. For example adding the `required` attribute to the price field.

Maybe the declaration of `$custom_attributes` can be changed from
`$custom_attributes = array();`
to
`$custom_attributes = apply_filters( 'woocommerce_wp_text_custom_attributes', array(), $field );`
(_text_ should be replaced by the respective meta box type)

**Comment by mikejolley** [comment]
I don't think thats a clean or good way to adjust core fields. `custom_attributes` does not cover all input properties.

Adding this would also cause problems since core won't handle things like "required" on the server side, and it can lead to extension conflicts.

It feels like the direction of these panels/fields will eventually be API based in future releases, so I don't think we should change the current behavior without a really good reason. 

If you need required price fields, you can add them via the actions, do server side validation, or enhance with JS.
