### ISSUE TITLE
'/orders?after=' filters incorrectly.

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#14539]
### EXPLANATION OF THE ISSUE

Been doing some tests in postman, and getting unexpected results with the "after" filter.

So the order I'm trying to filter out is:
```
    "id": 7019,
    "created_via": "rest-api",
    "version": "3.0.3",
    "date_created": "2017-04-19T17:28:00",
    "date_created_gmt": "2017-04-19T15:28:00",
    "date_modified": "2017-04-19T18:17:40",
    "date_modified_gmt": "2017-04-19T16:17:40",
    ...
```

I'm gonna list the `GET` requests made, and the expected result and the actual result.

Assumptions:
A zulu iso8601 date should search the "_gmt" column i.e 2017-04-19T15:27:59Z

```
QUERY                                                        EXPECTED       ACTUAL
GET wp-json/wc/v2/orders?after=2017-04-19T17:27:59Z          No order       Got order
GET wp-json/wc/v2/orders?after=2017-04-19T15:28:01Z          No order       Got order
GET wp-json/wc/v2/orders?after=2017-04-19T17:28:01%2B02:00   No order       Got order
GET wp-json/wc/v2/orders?after=2017-04-19T19:27:59%2B02:00   No order       Got order
```

We tried the same tests, but against the `date_modified` field, but it seems like the query runs against `date_created`.

### STEPS TO REPRODUCE THE ISSUE

Make an order, and try to query against the date fields.
No one here at the office can make sense of this, so we assume its buggy.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.18-1+deb.sury.org~xenial+1
PHP Post Max Size: 130 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ 

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: nuvo_24_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Carbon Fields: af htmlburger – 1.5
WooCommerce: af Automattic – 3.0.3
WordPress MU Domain Mapping: af Donncha O Caoimh – 0.5.5.1
WP Pusher: af WP Pusher – 2.4.2
Yoast SEO: af Team Yoast – 4.6
S3 Uploads: af Human Made Limited – 2.0.0-beta3
Nginx Helper: af rtCamp – 1.9.8
WP REST API - OAuth 2.0 Server: af justingreerbbiap.koponen – 1.0.1

WP Crontrol: af John Blackbourn & contributors – 1.5
Jetpack af WordPress.com: af Automattic – 4.8.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /shop/
Indkøbskurv: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ 

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by claudiosanches** [comment]
This works like WordPress REST API, only by the `date_created` and not in GMT.

**Comment by larssn** [comment]
Yeah but the above tests shows that it doesn't even filter correctly against `date_created`.

`GET wp-json/wc/v2/orders?after=2017-04-19T17:28:01%2B02:00` should NOT find anything.

**Comment by larssn** [comment]
And besides, it should be irrelevant to the user which timezone the order is stored in. The only concern the user should have is sending a correct ISO8601 date, either in zulu time or with a time zone attached.

From there it's your responsibility to convert it to the desired format, so you can make a correct comparison.

**Comment by claudiosanches** [comment]
This pass all information to `WP_Query` in the same way that WordPress REST API does.

**Comment by larssn** [comment]
And that excuses it not working?

**Comment by claudiosanches** [comment]
@larssn ?

**Comment by larssn** [comment]
As I wrote, doing a search for `GET wp-json/wc/v2/orders?after=2017-04-19T17:28:01%2B02:00` **should not** find an order with `"date_created": "2017-04-19T17:28:00"`, irregardless of what column is being looked at.

It seems like the client is required to send his iso8601 date in Zulu time, which is then compared to a non-zulu time date in the database. This is bad; it's backwards it's unintuitive, it's idiosyncratic. Call it what you will.

Most apps would:
1. Convert the user's date to UTC or a timestamp.
2. Since the server knows how dates are stored: Easily convert the client's date to the required date (with timezone or not) or timestamp and make the correct comparison.

**Comment by claudiosanches** [comment]
@larssn before you come here with this tone, can you test WP REST API first?
Check the posts endpoint, doing the same are you saying here.
If have the same behavior, please feel free to open a core ticket in WordPress, then after they merge it I can change here too. Thanks.

**Comment by mikejolley** [comment]
We're limited to what we can do in our API but the WordPress REST API we build upon. If you have a legit bug in WordPress REST API, use the core trac.

**Comment by larssn** [comment]
I'm sorry if my post came off as an attack on anyone, it was not meant to. I only wanna attack the issue at hand, and get it solved. However this thread was dismissed and closed minutes after being posted. I realise you probably get a lot of nonsense in this issue tracker, which is why I strive to make the issues as clear and apparent as possible, to make it understandable. When your users spend time doing the same, at least hear them out before closing - maybe there actually is a problem.

Now I'm a dev myself, and I greatly appreciate what you are doing. I will investigate further, but I don't think it normally something you can expect from your users. They will have varying degrees of technical know-how.

**Comment by claudiosanches** [comment]
@larssn I'm saying for you since from the begin that this is the same behavior that WordPress REST API. That's why I closed, and still you choice to be rude, no need to be a developer to understand that if is working for WordPress core, should work good here too, no reason to start attack me or be rude only because you don't like the way it work... I'm deeply offended with you.

**Comment by larssn** [comment]
Well you didn't even elaborate on that fact. How is a normal non-dev user - coming here with what he assumes is a bug - ever gonna get anywhere when you just close the topic with one line of text. That's pretty rude in itself: A user spent time working on a bug report, which you quickly glance at, and then close with a vague one-liner.

I don't understand why you'd be offended by anything written in this thread tbh.

**Comment by mikejolley** [comment]
I think the issue here is that the WP Rest API supports time in the site timezone only, so passing strings with timestamps won't work. I've ran into issues recently with WordPress using odd date formats and not-quite-to-standard dates in the admin area.

Anyhow, I suggest repeating tests with the posts API http://v2.wp-api.org/reference/posts/

If you can replicate something on there, it's not a bug in WC core. If you can however find an issue only in WC api endpoints and not in http://v2.wp-api.org/reference/posts/, we can look into it.

**Comment by larssn** [comment]
Will see if I can squeeze a test in tomorrow; I'll report back if relevant.

**Comment by claudiosanches** [comment]
@larssn I just said that this is the same behavior that WordPress REST API.
There is nothing to more to say, we are not trying anything fancy here, and if it's the same behavior that WordPress REST API.

Here what WooCommerce and WordPress does: 

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L211-L214

After it will try add a few additional params in:
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L268
https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L858-L903

And finally query with: https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L296-L297

Like that I said?
> This pass all information to `WP_Query` in the same way that WordPress REST API does.

That's it.
Still no reason to be rude, since I just write two lines and you already started to throw me rocks.

And let me know if want to show all endpoints in WooCommerce REST API too, all doing exactly the same as WordPress REST API.

**Comment by DavidRJohns** [comment]
I'm going to stay out of the debate over etiquette, but I will weigh in on the technical issue.

It would be nice to be able to provide the timezone information of the after and before parameters and the API make the necessary conversion to either database local time or GMT before doing the comparison.  I have an issue where I'm helping a client who is in a different timezone than me.  As it is, I have to add a client side correction to his timezone before submitting the request.  More generically, it means that organizations have to set the WordPress timezone to the place from which they will be making API calls.  In some cases, that may not be what they want.  In other cases, like mine, they may have multiple locations from which API and other access calls are being made so it may necessitate a client side conversion to a different timezone.  It would be better if the framework took care of this since it has all the information it needs to be able to do so.

**Comment by larssn** [comment]
@DavidRJohns That is the issue indeed. But it does appear to be a flaw in WP and not in WC. It's a strange design choice, and I wonder if the person who designed it really knew about timezone conversions. I haven't gotten around to creating a bug report in core yet, since my schedule is pretty tight, and it can be exhausting explaining this stuff in detail.

**Comment by albertwan-oms** [comment]
@larssn Have you been able to create a bug report in core? We just hit this issue too.
