### ISSUE TITLE
[3.0] Grouped Products display in Cart change

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#14538]
It looks like the cart display for Grouped Products (and the email display, I believe) have been changed - I'm not sure if it was intentional, but some customers are looking to return to the old style. Both of the images are grouped products on different versions of a localhost, same settings to the site.

## WC 2.6.14 ##

![http://cld.wthms.co/div4](http://cld.wthms.co/div4+) 
Full Size: http://cld.wthms.co/div4

## WC 3.0.3 ##

![http://cld.wthms.co/C5pZ](http://cld.wthms.co/C5pZ+) 
Full Size: http://cld.wthms.co/C5pZ

-----

Any idea on how to switch this back or have a toggle/snippet?

563513-zd-woothemes

**Comment by claudiosanches** [comment]
This is made by design, since a product now can be part of multiple groups, and in the case of a product be part of multiple groups makes hard to display like before.

@mikejolley @claudiulodro maybe for a future minor release we could use the form of grouped products and include meta data, like we does for variations.

**Comment by mikejolley** [comment]
Due to the multi-group feature, prefixes make much less sense going forward. I don't think we should revert this back unless the idea is validated - tbh I've not seen many comments on it.

Changing the actual product title if the prefix is important is still viable.

@DanielSantoro I'd suggest creating something on the ideas board so we can see if this needs debate in the dev chats. I'm not convinced it's that useful given how grouped products work.
