### ISSUE TITLE
System Status will not load

### ISSUE THREAD

**Issue by jamieis** [woocommerce/woocommerce#14546]
### EXPLANATION OF THE ISSUE
System status will not load, I have the latest WooCommerce and the latest Flatsome.
Did have a message that my WooCommerce were out of date but have now updated to 3.3.4. 
Error: Inactivity Timeout
Description: Too much time has passed without sending any data for document.
Once the error happens it taken some time to load the web site up again, I must clear the cookies. Then moving around the site slows down.
If I don’t select system status then moving around is fine.
Any help would be great.

### STEPS TO REPRODUCE THE ISSUE

Select the item in the wooCommerce menu 

### SYSTEM STATUS

unable to get

**Comment by claudiulodro** [comment]
What troubleshooting have you done?

```
Before logging BUGS, ensure you:
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

**Comment by jamieis** [comment]
Yes done all that. disable the plugins.
switched over to 2017 and still no luck.
 have re downloaded current theme flat some 3.3.4.

So that why I thing its to do with WooCommerce

**Comment by claudiosanches** [comment]
@jamieis have you contact your hosting provider? I read that this could be generated because is hitting the `MaxRequestWorkers` of apache.
In system status we do some requests to test `wp_remote_get()` and `wp_remote_post()`, and maybe your store is already doing a lot of requests at the same time and consuming a lot of resources from the server.
