### ISSUE TITLE
Unpaid order cancelled – time limit reached. Yet Paypal IPN payment Complete

### ISSUE THREAD

**Issue by addahandle** [woocommerce/woocommerce#14587]
Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.
I have wordpress 4.7.3, woocommerce 3.0.3 use GoDaddy SSL updated 11/14/16 and Paypal which says it all looks good on their end.
Senerio:
order placed on website and payment made at 10:10am, according to Paypal
website shows IPN complete at 2:10pm
then at 3:34pm Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.
I am receiving a cancellation email and then hours later a order confirmation but the website then states cancelled.  
Anyone?

**Comment by mikejolley** [comment]
Need to see the order notes on the order which was cancelled.

**Comment by addahandle** [comment]
Hope this helps

this order is still pending 5409 but
 paypal paid Invoice ID:	
WC-5409
Custom:	
{"order_id":5409,"order_key":"wc_order_58f789819f3cf"}.
Date:	
Apr 19, 2017
Time:	
09:00:42 PDT
Status:	
Completed  

Payment Type:	
Instant
Order Notes:
IPN payment completed
added on April 19, 2017 at 4:23 pm Delete note
IPN payment completed
added on April 19, 2017 at 4:07 pm Delete note
IPN payment completed
added on April 19, 2017 at 4:01 pm Delete note

this is for order 5408 - this order I received payment from paypal at 10:09:42amEST
Invoice ID:	
WC-5408
Custom:	
{"order_id":5408,"order_key":"wc_order_58f76f8dad070"}.
Date:	
Apr 19, 2017
Time:	
07:09:42 PDT
Status:	
Completed  

Payment Type:	
Instant

Order Notes
Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.
added on April 19, 2017 at 3:34 pmEST Delete note
IPN payment completed
added on April 19, 2017 at 2:10 pmEST Delete note

**Comment by mikejolley** [comment]
Cam you should screenshot the notes in the affected order please? Will be easier to read..

**Comment by addahandle** [comment]
it won't let me copy and paste the photo. If you want I can email it directly to you. 
I copy and pasted the direct info from the website and it is below. This order processes through Paypal and Woocommerce sent me a cancellation email.

Order Notes
Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.
added on April 19, 2017 at 3:34 pmEST Delete note
IPN payment completed
added on April 19, 2017 at 2:10 pmEST Delete note

**Comment by mikejolley** [comment]
Since "IPN payment completed" is added, but the status was not updated, I see 1 of 2 possibilities.

1. Something is filtering the 'paid' status so it's not processing or completed
2. Something is throwing an error before said status can be set.

You didn't provide a status report so I cannot see what plugins are active, but:

- you need to establish if a plugin is blocking the update
- you can check server error logs for 'fatal error' which may reveal the problem

Since this cannot be replicated on my own sites, and this is not a widespread issue, it seems specific to your site.

As a temporary measure whilst you look into why, you can:

- disable the auto-cancellation of orders in WC > Settings > products > inventory
- enable PayPal PDT as a fallback (may also be affected if this is a plugin conflict) https://docs.woocommerce.com/document/paypal-standard/#section-27

Let us know how it goes.
