### ISSUE TITLE
Checkout - select2 and country_to_state_changed Reset current select2 theme.

### ISSUE THREAD

**Issue by widoz** [woocommerce/woocommerce#14647]
### EXPLANATION OF THE ISSUE

**version**: 3.0.4
**File**: wp-content/plugins/woocommerce/assets/js/frontend/country-select.js:63
**Function**: wc_country_select_select2()

**Where and What**
On checkout after selected a country if I used a different select2 theme (or a custom one) the style is reset to the original one because of the select is created again on _country_to_state_changed_ event.

**Expecting**
I expect the select2 is not reinitialized to use the defined theme style.

Is there a reason why the select2 is reinitialzed?

### STEPS TO REPRODUCE THE ISSUE

Try to implement a different theme for the select2, then in checkout change the value for the "Country" field.

**Comment by mikejolley** [comment]
> Is there a reason why the select2 is reinitialzed?

Yes; because some countries don't have a state field and some countries do. When the state input is dynamically inserted, it needs to be re-init otherwise it would have no styling/no enhancement.

If you need to define custom init vars to OUR select2 init methods, raise a PR and we'll consider it for core. e.g. you could add a filterable array of args which are passed into our checkout/country select scripts.

Since the init is on purpose this is not a bug, but as I said we'll consider a filter ;)

**Comment by mikejolley** [comment]
e.g. https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/country-select.js#L58-L61

Anyhow, a PR would be good so you can test it does what you need before we make any changes.

Thanks!
