### ISSUE TITLE
Main product image displaying within product gallery section strange display with variations

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#14677]
### EXPLANATION OF THE ISSUE

With WooCommerce v3.0.4 the main Product Image now displays with the product gallery section as the first image in the row on the left-hand side. 

**Product**
![screenshot](http://cld.wthms.co/U0f3+) 
**Image Link:** http://cld.wthms.co/U0f3

**Single Product**
![screenshot](http://cld.wthms.co/4Hde+) 
**Image Link:** http://cld.wthms.co/4Hde

When a variation is chosen the first image in the row is replaced with the image which is set on the actual product variation replacing the product image in the gallery which seems a little strange as it doubles up gallery images.

![screenshot](http://cld.wthms.co/tnh3+) 
**Image Link:** http://cld.wthms.co/tnh3

I'm not sure if the main product image is now intended to be displayed automatically within the product gallery, if it is then when switching to a different variation I don't think that main image should be replaced/hidden as it's confusing that it no longer displays within the product gallery.

When cross-tested against v2.6.14 the main product images does not display within the product gallery section and no images are replaced when choosing variations.

![screenshot](http://cld.wthms.co/tVeN+) 
**Image Link:** http://cld.wthms.co/tVeN

**Ticket:** 557238-zd-woothemes

**Comment by mikejolley** [comment]
@stuartduff This is because in the example you've given you've set the same images:

1. In the gallery itself
2. Per variation

So you're seeing a double up because of that.

For the slider to work, you need all images currently being output (even when a variation is selected) shown below, which is why replacement happens.

**There is no link** because a gallery image (in the product edit screen sidebar) and a variation image (in the variations panel).

**Comment by stuartduff** [comment]
@mikejolley I'm not too sure I'm understanding your reply and I think you're maybe missing a screenshot ( shown below ) :)

> This is because in the example you've given you've set the same images:

- In the gallery itself
- Per variation

> So you're seeing a double up because of that.

Does this mean the customer now needs to upload a different image for a variation than for in the product gallery as that would be double the work and duplicate images?

I simply uploaded three images to my sites and used them for the main product image, product gallery, and variations which is how most customers add images.

> For the slider to work, you need all images currently being output (even when a variation is selected) shown below, which is why replacement happens.

Is there a screenshot missing from this :)

> There is no link between a gallery image (in the product edit screen sidebar) and a variation image (in the variations panel).

I understand this.

A customer reported this change of behavior to us after upgrading from v2.6.14 to v3.0.4 and I replicated it by adding the images in the exact same way to both versions though.

Cheers

**Comment by mikejolley** [comment]
@stuartduff  I don't know if I'm making sense but I know what I mean :p 

> Does this mean the customer now needs to upload a different image for a variation than for in the product gallery as that would be double the work and duplicate images?

Pretty much because as I said, there is no relationship between the gallery and the variation images which get defined separately. It doesn't swap them or switch to a gallery image, it does a replacement of the main product image.

The only different vs 2.6 is that the thumbnails below the main image include the current main image. The actual replacement of the main image with a variation is identical. 

If you go to 2.6 version and use the lightbox after selecting a variation, and then cycle through images, you'll still see the duplicate.

**Comment by mikejolley** [comment]
What we could do is output the thumbnail ID on each image, and if the variation target thumbnail ID matches an existing item, switch rather than change.

Would require some template modification so whacking in 3.1.

**Comment by stuartduff** [comment]
> What we could do is output the thumbnail ID on each image, and if the variation target thumbnail ID matches an existing item, switch rather than change

@mikejolley That would be awesome and a little more intuitive of what the customer would expect with switching out and an elegant solution I feel, much appreciated.

**Comment by faisal-alvi** [comment]
Hi @mikejolley and @stuartduff 

I hope you both are well..!

Here is the fix - #14777 

Please note that I have fixed it for (maximized version) 'add-to-cart-variation.js'.

@mikejolley  please guide me how to update my fix in minimized 'add-to-cart-variation.min.js' which is currently used by WooCommerce.

Thanks!

**Comment by ayeronnie** [comment]
I have the same issue as the OP. I set my main product image, then I set up to 8 different images in the product gallery section. Yet on the product page, in the gallery below the main product image, it also shows the main product image as well. Previous versions of Woocommerce did not do this.

I set my images up so I only have up to 9, 1 product and 8 thumbs for the gallery. But this new set up makes those all 9 now and kind of sets the gallery off. It's not a huge deal, but kinds messes up my gallery with a now, extra row.

Some one else mentioned on the support section for woocommerce on wordpress.org.

**Comment by faisal-alvi** [comment]
Hi @mikejolley and @stuartduff

Here is the fresh fix - #14874 

Please note that I have fixed it for (maximized version) 'add-to-cart-variation.js'.

Thanks to @emgk to help me to sort out commit history issue in the main branch.

@mikejolley please guide me how to update my fix in minimized 'add-to-cart-variation.min.js' which is currently used by WooCommerce.

Thanks!

**Comment by emgk** [comment]
@faisal-alvi I think, You should never make any changes inside the minified js file as it will be done automatic through grunt, once your patch has merged to master branch. 
see https://github.com/woocommerce/woocommerce/blob/master/Gruntfile.js#L43-L112

**Comment by faisal-alvi** [comment]
Thanks for the info @emgk 👍

**Comment by vicocotea** [comment]
I just had this issue due to, I think, the recent change of image_size especially `woocommerce_gallery_thumbnail`.

Variations return `woocommerce_thumbnail` size and the gallery use `woocommerce_gallery_thumbnail` size, so they don't match here : https://github.com/woocommerce/woocommerce/blob/348154f43b59c59f6414f9f6e56a3452095be186/assets/js/frontend/add-to-cart-variation.js#L567

I used a workaround with this filter : 
```add_filter( 'woocommerce_gallery_thumbnail_size', 'custom_woocommerce_gallery_thumbnail_size' );
function custom_woocommerce_gallery_thumbnail_size() {
  return 'woocommerce_thumbnail';
}```

So it match again.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19335

**Comment by k3nsai** [comment]
So how can we fix this guys? What do we need to do in our theme to prevent the thumbnail from showing as a duplicate?
