### ISSUE TITLE
Woocommerce should not use localeconv()

### ISSUE THREAD

**Issue by preliot** [woocommerce/woocommerce#14673]
Woocommerce uses localeconv() to set decimal / thousand seperators for decimals, sizes, etc. I've seen it used in a few places to replace decimal seperators.

Problem is i can't use setlocale, because the locale information is maintained per proces. So this information could be changed by others on the same host, if i understand it correctly. See the 'warning' at the following url http://php.net/manual/en/function.setlocale.php

### STEPS TO REPRODUCE THE ISSUE

0) Use setlocale, f.e. setlocale(LC_ALL, 'nl_NL');
1) Search for localeconv() in woocommerce code
3) Another script calls setlocale in diffferent thread on same proces
4) localeconv() retrieves different settings, not the expected nl_NL locales.

### What should be done imho

Make new admin fields or repurpose the 'currency decimal/thousand seperator' fields underneath woocommerce > settings > general. Use those fields to ensure correct thousand / decimal seperators.

**Comment by mikejolley** [comment]
We need localeconv() to handle conversions. Surely if a host had people sharing this variable, it would prevent setlocale() from being called?

**Comment by preliot** [comment]
If setlocale is disabled, you have no control over the ouput anymore. 
Say you host your website with a foreign hoster, it could output a decimal seperator / thousand seperator you did not want.

**Comment by mikejolley** [comment]
To be frank, thats hardly a problem WC should have to account for.

The fact is, `setlocale` affects us because it changes how floats are converted to strings, and things like that. Without `localeconv` it's impossible to reverse and standardise these changes. See our `wc_format_decimal` function for example. It needs to strip off all locale formatting to store the data in a standard "10.00" decimal format.

The other usage converts our standardised format to the locale format on display.

_This entire issue seems to be speculation anyway_:

> So this information could be changed by others on the same host, if i understand it correctly.

I wouldn't expect this to be the case. And searching "setlocale shared hosting" gives no useful results - if it were an issue I'm _sure_ it would have been talked about in the past.

If in doubt check with the host?

**Comment by preliot** [comment]
I've tried to generalize the issue, hence the speculation. 

I've came accross this when i handled dimensions. They were imported with a dot as a decimal seperator, which was wrongly assumed to be a thousand seperator by the format function. I saw the settings at woocommerce > settings > general, but they are only used for prices. It would make sense to generalize this over all decimals, not only prices.

Working arround it by changing the import settings to the expected decimal seperator.

**Comment by mikejolley** [comment]
You should set the correct/desired locale in your php ini file for sure if it's not what you're expecting. I'd rather avoid a tonne of new settings for this because it adds an extra layer of complexity around storage/conversion/display.

System status report will give you info on current locale.

And if you insist on new settings, log an idea so it can be validated before development ideas.woocommerce.com

Thanks
