### ISSUE TITLE
Update 3.0 language bug

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce#14691]
### EXPLANATION OF THE ISSUE

I updated to the newest woocommerce version. Since then I experience a strange behaviour with langauges. In wordpress general settings I see me langauge but when I save it, it still reads "English (United States)". However the wordpress part gets translated into German. But woocommerce still thinks the site language is en_US and loads wrong translation.

If you see the screenshot you can see that everything is in German except that WooCommerce still reads en_US as langauge (and in frontend loads the wrong language because of this).

<img width="1919" alt="bildschirmfoto 2017-04-25 um 17 35 30" src="https://cloud.githubusercontent.com/assets/8314202/25394126/ad9ca1e2-29dd-11e7-901b-54d95f471647.png">

EDIT: Tried with all plugins disabled (except woocommerce) but to avail. Checked the database and WPLANG is set to de_DE

### STEPS TO REPRODUCE THE ISSUE

Honestly, don't know. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiosanches** [comment]
What really happens is that you don't have the updated language files for WooCommerce 3.0.
Since WooCommerce 3.0 have a lot of new strings and some changes in the old ones too, you need to get it updated.
I can see that the community already translated to German ([Format too](https://translate.wordpress.org/locale/de/formal/wp-plugins/woocommerce)): https://translate.wordpress.org/locale/de/default/wp-plugins/woocommerce so it's already available the update to be downloaded by WordPress.
Try go to Dashboard > Updates and click in the "Update translations" button (maybe need to make WordPress check for translations first).
Good luck.

**Comment by florianbepunkt** [comment]
@claudiosanches Thank you. There is no update translations button in Dashboard -> Update. Also woocommerce status report says the site langauge is english

**Comment by florianbepunkt** [comment]
Deleted woocommerce translation. Then updated woocommerce translations. Issue still exists.

**Comment by florianbepunkt** [comment]
For other people having the same issue: In my case WooCommerce seems not to be compatible with the popular Divi plugin (or the other way around if you prefer). Having all plugins disabled, the issue occurs when Divi theme and WooCommerce are active. If I switch the theme WooCommerce language is set properly.
