### ISSUE TITLE
Enhancement: validate_posted_data() in class-wc-checkout introduces translation problems

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce#14694]
### EXPLANATION OF THE ISSUE

In class-wc-checkout.php in the method validate_posted_data you change the $field_label as following

```
switch ( $fieldset_key ) {
  case 'shipping' :
    /* translators: %s: field name */
    $field_label = sprintf( __( , 'woocommerce' ), strtolower( $field_label ) );
  break;
  case 'billing' :
    /* translators: %s: field name */
    $field_label = sprintf( __( 'Billing %s', 'woocommerce' ), strtolower( $field_label ) );
  break;
}
```

This introduces two problems:

(1) In German (and I guess in other languages as well) you would write the `$field_label` with a capital, but you hard coded a strtolower method, so `Billing Address` becomes `Billing address`. In German this is a spelling mistake - it would need to be `Billing Address` with a capital A and it would need be one word ('Billing address = Rechnungsadresse).

(2) Prefixing the labels with billing or shipping  introduces a range of langauge problems.... for example Billing address in formal German would be "Rechnungsadresse" (so basically the word adress already includes the word billing, but it's one word). If use this then suddenly in my errors the words are doubled since you already prefix it. So it reads billing billing address.

Greetings from Berlin

**Comment by mensmaximus** [comment]
I agree the strtolower() is an issue with specific languages and countries. But unlike plural and singular rules there is no equivalent for upper or lowercase in gettext(). One would have to create a function (maybe_strtolower()) that gets the site language and compares against an array containing key value pairs for language and case (or boolean for lowercase). Something like $lower_case( 'en_US' => true, 'de_DE' => false). Or one could introduce a new table (woocommerce_i18n) to store countries, iso codes, lower case rules and what ever. This way one could get rid of all the country related arrays in class WC_Countries.

The prefixed Billing and Shipping should stay as it indicates which fields are missing. Otherwise you would get two times 'Vorname ist ein Pflichtfeld' (Name is required) instead of 'Rechnung Vorname ist ein Pflichtfeld' (Billing Name is required) and 'Lieferung Vorname ist ein Pflichtfeld' (Shipping Name is required).

**Comment by florianbepunkt** [comment]
@mensmaximus Don't agree on the second part as "Rechnung Vorname" (billing name) is simply not correct German (and probably there are other languages where this sounds even more forced and unnatural).

Maybe a filter that we can hook in to change the validation notices would be a compromise (?)

**Comment by mensmaximus** [comment]
@florianbepunkt we talk about the verification message showing up if a mandatory field is empty or malformed. Because 'Vorname' (firstname) can be empty two times you need a way to show the customer which field is empty. The one in the billing form or the one in the shipping form. If you don't like the current translation 'Rechnung Vorname' you could either suggest a new wording like 'Rechnungsanschrift %s' or '%s in der Rechnungsadresse' to the translation team or you can create a custom translation. 

The filter you ask for is already there 'woocommerce_checkout_required_field_notice'

**Comment by florianbepunkt** [comment]
@mensmaximus thank you, didn't know about that filter.

**Comment by claudiosanches** [comment]
The `strtolower` can be hard I agree.
But still you can provide a better translation for it.
It's not because in English is `Billing address` that you need to translate like it, you can translate to something like `address in the billing section`.

I translate WooCommerce do pt_BR and sometimes this kind of change is necessary, and it's fine changes like this to make sense in your language, even in the handbook to translate WordPress is saying:

![screenshot from 2017-04-25 17-54-18](https://cloud.githubusercontent.com/assets/1264099/25407306/3cbf41e8-29e0-11e7-8dd6-9ee2f935d7ed.png)

https://make.wordpress.org/polyglots/handbook/translating/expectations/

**Comment by claudiosanches** [comment]
@mensmaximus looks like you suggested the same, but I just checked what `%s in der Rechnungsadresse` means now :P

**Comment by florianbepunkt** [comment]
@claudiosanches It's not that easy and it's simply not a matter of being creative (or organic) with the translation. In German every noun begins with a capital letter. So I have no idea how to translate Billing address to something useful and normal looking (lightyears ahead from providing a better translation than we had before). I'm not sure if it is good practice to force people to use rather twisted wording to get around a forced lower string.

**Comment by claudiosanches** [comment]
@florianbepunkt it's easy, trust me, I'm saying it as a translator, and not as a developer.
I agree there is a problem with the `strtolower()` function there, still there is always a better way to translate something. And this will be something which I personally will fix, and that's why this issue is still opened.

**Comment by mikejolley** [comment]
It's not really worth adjusting case so I've put in a PR. See https://github.com/woocommerce/woocommerce/pull/14713
