### ISSUE TITLE
Emails sent via admin should switch to global locale

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14763]
We should fix the issue in the emails class instead of https://github.com/woocommerce/woocommerce/pull/14599

**Comment by gingerlime** [comment]
I'm using 3.2.6 and still see some weird non-translated strings in emails if I send them out from an admin with a different locale than global. e.g. I had an email sent out that had most strings translated apart from the state (Japanese prefecture), which ended up in English instead of Japanese...

**Comment by mikejolley** [comment]
It cannot/does not translate user input data such as names.

**Comment by gingerlime** [comment]
Of course not. But I'm talking about state/country - which is available in a dropdown from a pre-selected list. It gets translated correctly if the admin uses the same locale as the global one (Japanese, in this case), but doesn't get translated if the admin language is different (English). Instead it shows the English non-translated version on the email to the customer.

**Comment by mikejolley** [comment]
Is the localisation missing? Those strings were changed in 3.2.6

**Comment by gingerlime** [comment]
I noticed some missing/changed, but we updated them. I don't think that's the problem here though, because the same strings (e.g. the country name -- Japan) get translated correctly when the admin locale is Japanese.

**Comment by gingerlime** [comment]
I think I traced where this problem comes from. We use the [`woocommerce-for-japan` plugin](https://github.com/artisanworkshop/woocomerce-for-japan), which seems to inject a list of states / prefectures by hooking to the `woocommerce_states` filter, and those states provided by the plugin aren't translated by it (you can see that it uses `-Ken` with capitals, whereas woocommerce uses `-ken` without...). So I think the problem isn't with Woocommerce, but rather the plugin. Sorry for the false alarm. I'll report the issue to the plugin author.
