### ISSUE TITLE
Send the right new order to the right personne

### ISSUE THREAD

**Issue by solsbury31** [woocommerce/woocommerce#14793]
Hello everybody, i have an ecommerce website with woocommerce and i have diffrent seller in it which means i don't sell anything on the website but i have different stores and brands who sells their products on my website, my role is to add the products, so let's say for exemple in my website there is samsung which sells it products , adidas sells its products, nike .......etc so what i want is when a custumer order something on my website the new order email goes directly to the owner of this product that this custumer ordered not to the admin of the site , so if for exemple someone ordered the samsung galaxy s7 , the new order email goes to samsung's email or someone ordered an adidas jacket the new order email goes to adidas's email ...etc.
please is there any way i can do this ?
thank you all

**Comment by UserName011** [comment]
You need a plug in for that:
"Advanced Notifications

Cost $29
https://woocommerce.com/products/advanced-notifications/
What does it do?

Lets you send email notifications about orders (purchases or backorders) or stock (low stock, out of stock) to people. These can be related to all products, products within a specific category, or specific products. The latter needs to be set up on individual products via the Products section rather than within Notifications."

http://www.mailpoet.com/the-most-useful-email-extensions-for-woocommerce/
