### ISSUE TITLE
Adding HTML to woocommerce_review_order_after_order_total duplicates when cart updates totals

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#14792]
If you add any HTML to any of the following hooks:

```
do_action( 'woocommerce_review_order_before_cart_contents' );
do_action( 'woocommerce_review_order_after_cart_contents' );
do_action( 'woocommerce_review_order_before_shipping' ); 
do_action( 'woocommerce_review_order_after_shipping' ); 
do_action( 'woocommerce_review_order_before_order_total' ); 
do_action( 'woocommerce_review_order_after_order_total' ); 
```

So basically any hook in the `review-order.php` template, then the HTML is duplicated when the cart order totals are reloaded:

![image](https://cloud.githubusercontent.com/assets/507025/25539814/81a263b4-2c0e-11e7-9f0c-0e16627dce79.png)

I thought it was perhaps the form field, but just echoing out text causes the same repeating.

**Comment by mikejolley** [comment]
This table is replaced via JS after updating, but if you've inserted non-table content via these hooks it will be moved out of the table as it's invalid. 

All of the action hooks listed need table rows - https://github.com/woocommerce/woocommerce/blob/76b32c9aa52ebac70fe5a60a8d56351218760471/templates/checkout/review-order.php#L32 - since it's within a HTML table/tbody.

**Comment by anderly** [comment]
Probably worth noting that the appropriate hook for something to be displayed before order review is `woocommerce_checkout_before_order_review`.

**Comment by siteit** [comment]
@anderly thanks for the comment ;) saved my day
