### ISSUE TITLE
Shipping rates can't be filtered using the Shipping Method instance ID

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#14837]
When a shipping rate is added it uses the function add_rate, this in turn adds it using the rate ID and the method ID.
https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L264

Later on when all the rates are added for each package it uses the filter `woocommerce_package_rates`. This allows you to limit the Shipping rates which show up for a specific package.

Plugins which allow you to setup these kind of limitations are:

- [WooCommerce Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/)
- [WooCommerce Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/)

But because the rates do not contain the instance ID, if there are multiple instances of the same method you can't filter the rates of a specific one.

Say for example I have FedEx Rates setup for returning Freight shipping and FedEx Rates setup for regular shipping. The rates which are available in the filter `woocommerce_package_rates` will be:

```
["fedex:FEDEX_GROUND"]=>
  object(WC_Shipping_Rate)#1118 (6) {
    ["id"]=> string(18) "fedex:FEDEX_GROUND"
    ["label"]=> string(12) "FedEx Ground"
    ["cost"]=> string(4) "7.54"
    ["taxes"]=> array(0) { }
    ["method_id"]=> string(5) "fedex"
    ["meta_data":"WC_Shipping_Rate":private]=> array(0) {}
  }
```

In the above example the method_id is `fedex`, but since I have two instances of FedEx I don't know which instance returned that rate. It would be useful if either the Rate could contain both the method_id and the instance_id.
Or alternatively if the method_id would be stored using the function `get_rate_id`. This would mean the method_id would contain `method_id:instance`

**Comment by franticpsyx** [comment]
It would be really nice if WooCommerce would make it easier to know which method AND which instance is "behind" a generated rate. @mikkamp is spot on -- it would make it a lot easier to work with conditional shipping logic.

When 2.6 was in development, we had a quick chat about this with @mikejolley which was about finding a "standard" way to generate rate IDs that would contain this information AND be backwards compatible. Back then, we tweaked `get_rate_id` and expected shipping method authors would just use it.

Right now, many shipping method developers still define custom rate IDs when calling `add_rate`, instead of using `get_rate_id`. So any logic that relies on "parsing" rate IDs to extract the method and instance ID fails in these cases.

@mikkamp 's idea to add the `method_id` and `instance_id` to rates would make it a lot easier to filter shipping rates by method or shipping zone.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16012

**Comment by brianjhanson** [comment]
Any chance there's a workaround for this until 3.2.0 gets released?

**Comment by mikejolley** [comment]
Nope. Wasn't possible before.
