### ISSUE TITLE
How to apply coupon usng API?

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#14847]
When new order is being generated from API, coupon apply is not working. Discount amount is not being calculated. What can i do for that? using `woocommerce 3.0.5` and `API version v2`

**Comment by claudiosanches** [comment]
There is nothing that apply discounts on REST API. Not even in old versions of WooCommerce.
But we have a plan to introduce it soon.

**Comment by ddhara** [comment]
Okay! Thank you for the quick response. Is there any alternate way to do that task? Can you please help me? I have tried some ways but no solution is fully satisfied and when will you introduce it? Eagerly waiting for that as you know coupons are very important part of eCommerce

**Comment by claudiosanches** [comment]
@ddhara you can calculate in your end and send the correct discount. Will be introduced in a future release, we first need to create abstraction layer for discounts, since is all inside the cart object and there is no way to include discount in admin or anywhere else, so I don't have a date for it right now, but should come still this year, this is something that I personally want to do.
