### ISSUE TITLE
Administrator can't pay on behalf of Customer (it used to work)

### ISSUE THREAD

**Issue by hiheaven** [woocommerce/woocommerce#14885]
Login as administrator and can't pay on behalf of Customer (it used to work).

Prior to WC 3.x , this feature worked. But after upgrading to 3.x, it's broken!

STEPS:

1. Login as Administrator

2. Goto WooCommerce | Orders

3. Choose a order that is in Pending status

4. Click at link "Customer Payment Page"  (URL: http://YOURWEBSITEADDRESS.COM/checkout/order-pay/1691?pay_for_order=true&key=wc_order_5907f06ab0c00)

5. Get error: "**Invalid order. If you have an account please log in and try again. My account**"
(prior to WC 3.x, it used to work! here Administrator could click at payment type and finish
the rest)

### SYSTEM STATUS
WC version:		3.0.4
WP version:		4.7.3
WP multisite:		–
WP memory limit:		512 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.30-1+wpengine8
PHP post max size:		100 MB
PHP time limit:		3600
PHP max input vars:		1000
cURL version:		7.35.0, OpenSSL/1.0.1f
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		50 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		2.6.14   
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
```

**Comment by thomas-zg** [comment]
In my case, it only happens for orders created prior V3.0

**Comment by claudiosanches** [comment]
> Prior to WC 3.x , this feature worked. But after upgrading to 3.x, it's broken!

Well this not suppose ever to be a feature, sounds like a bug fixed in 3.0.
Not to mention that the administrator can just change the status from the order in the dashboard.

**Comment by sa561** [comment]
admin may be able to change status but not process a credit card.... this function allowed an admin to process a payment properly and should be fixed....  using a shop as customer as a workaround but it has issues...

**Comment by claudiosanches** [comment]
@sa561 an admin paying with his/her own credit cart an order for a customer?

**Comment by teammartinmiller** [comment]
@claudiosanches - this is a big deal. My client uses this feature to process payments made via phone. Their wholesale customers are super busy and don't have their login information to the site accessible at all times so they really appreciate being able to have one-click access to payments sent to them by email, like these links used to provide. This way of paying process 85% of their $500K / year revenue. They are flipping out because of this and I'm not sure how to fix it.

**Comment by claudiosanches** [comment]
@teammartinmiller "so they really appreciate being able to have one-click access to payments sent to them by email", this is possible, you can create the order on the admin screen and then select to send the invoice e-mail, the customer will get a link by email to just pay on the site.

**Comment by teammartinmiller** [comment]
They have to actually log in to their account though. The "Customer payment
link" before 3.0 allowed a client to pay without having to log in to their
My Account. Is that how the invoice email works?

**Comment by teammartinmiller** [comment]
I just tested it. It doesn't work like that. You have to be logged in to
your account to pay the invoice now. This may seem like it's a big deal,
but it is. Competition is tight -- if my competitor has a Shopify site that
allows them to do this -- which they can -- then over time there is a good
chance that they'll steal my customer. If this cuts conversions in half,
that's a good $200K+ dollars down the drain.

To have had this capability and now not to have it is a big deal.

**Comment by claudiosanches** [comment]
@teammartinmiller so you want to open the link for your customer and use the customer's credit card?

**Comment by teammartinmiller** [comment]
Yes, exactly. This used to be possible up until 3.0 and I thought it was a
feature.

**Comment by teammartinmiller** [comment]
I also want to be able to email that link and have them be able to pay
immediately.

**Comment by claudiosanches** [comment]
@mikejolley thoughts?

**Comment by teammartinmiller** [comment]
Or is there a way in the core file to disable the requirement to be logged in to have to do this? At least as a quick fix until a more permanent solution is figured out?

**Comment by mensmaximus** [comment]
@teammartinmiller why not simply using the "shop as customer" plugin?

**Comment by teammartinmiller** [comment]
Because of this scenarios: we have a client on the West coast -- she's not
tech savvy. All she wants to do is put her credit card in and pay us
$5,000. She can't understand the error message that she gets when she gets
sent to the current "Customer Payment Page" link. It's stupid error text
makes it look like we've deleted her order. So we tell her to click My
Account and log in. She doesn't have her password. We tell her to click the
"forgot password" link. She can't remember her email password. So we tell
her that if she wants to she can just give us her credit card over the
phone. She doesn't want to, especially considering the fact that we can't
"get our site to work properly."

Taking big orders over Woocommerce is a nightmare. Suppliers, vendors, and
wholesale customers are a busy bunch. Being able to provide a high-level of
customer support and doing most of the work for them so they can give us
money is a nightmare with Woocommerce right now. There is no standard core
way of handling these customers - and "shop as customer" is a time-wasting
workaround for busy employees who already are spending most of their time
in the Admin section. It adds minutes to every order processed like this.
Plus hours and hours of development time trying to find a workaround and
then realizing that updates break the workarounds.

Shopify makes this very easy. POS. Ordering on behalf of customers. A link
that goes on invoices that allows customers to pay an order without having
to remember a username & password. These are built into the system.

For any customer who relies on these types of payments for 85% of their
business, this is a BIG DEAL.

The easiest fix for now, would be to make the "Customer Payment Page" link
work like it used to -- a customer clicks it and they can pay right away,
no login, no fuss. My Shop Admins can click it and pay for them.

So is there a way to comment out the requirement that they be logged in to
access that link?

A lot of businesses have grown quite big using features of Woo that most
developers don't think about if you are looking at it from the viewpoint
that everyone is selling homemade candles that they make and package up in
their garage.

Also, this scenario of working on behalf of wholesale customer and
processing their orders, working with a factory to manufacture goods
shipped and stored from a 3PL warehouse -- this scenario needs to be worked
into future core plans. Or at least a recommended setup should be outlined.

Brent

**Comment by teammartinmiller** [comment]
Just to be more specific, this is happening only with customers who order
with a specific "wholesale customer" role.

**Comment by nuclearape** [comment]
We use that link for regular phone orders.

We have 3 members of staff manning the phones for our website. 80% of orders are done online but 20% of our customers like to call up and talk to a member of staff to make their order.

With the customer on the phone, we create an order, click the "customer payment page" link and then enter their card details.

I understand why they have removed this feature from the core WC but I feel that we should have **a bit of code we can implement to bring this feature back to those that need it.**

**You could make it so that 'administrators' and 'shop managers' can access the link as well as the owner of the order.**

**Comment by mikejolley** [comment]
@nuclearape I've pointed out, tokens and user details get associated with the account which checks out. Adding an option to enable this would therefore be enabling broken functionality.

Use user switching.

3.1 will have a login form instead of the meaningless message.

**Comment by nuclearape** [comment]
@mikejolley We will use the payment gateways virtual terminal instead. Thanks for clarifying :)

**Comment by teammartinmiller** [comment]
I can guarantee a login form will flush 20% of our money down the toilet.
Have you seen a checkout funnel report from Analytics? For every page a
user has to navigate through, there is a >20% drop off in conversions.
Login pages are especially bad. Our wholesale customers like [insert the
name of a large U.S. specialty shop] place a large order every few months.
I would imagine the person who does this probably orders millions of
dollars of merchandise from at least 300 vendors. What are the chances that
he/she is going to remember their My Account login info for our site? So
now you've just added two to three minutes of password recovery to her busy
day. One of our competitors sends her some samples and she pays for them
from a link that takes her directly to a payment page. Boom. Now we've lost
a customer.

One of the reasons I moved a client from Shopify to Woocommerce -- it gave
us a better checkout process. It still does because of the custom URL for
checkout, but we didn't realize how poorly Woocommerce manages the
wholesale customer ordering experience.

But with Shopify, they make it very easy to take phone orders/faxed orders
and have the shop admin manually enter them. We're trying to set up the
same thing with Woocommerce POS but it's clunky.

I realize that using a third-party invoicing program like Quickbooks or
Stripe to take an order is one way of doing it, but then there is no way to
get the order information back into Woo so that it shows up in the report.
And user switching frankly feels a little dishonest.

@mikejolley - maybe it would be better to start working on two UX scenarios
- wholesale customer and shop admin serving a wholesale customer - and use
those as a basis for developing some of these features. If this becomes
standard functionality in Woo, I can see a whole buttload of people
migrating off of Shopify.

**Comment by sa561** [comment]
@mikejolley - using user switching or the merchant gateway are both cumbersome and slow processes down, my sales cycle can be 6 months, maybe more sometimes - 85% of my customers are either phone orders that want to give us a CC over the phone or customers that don't want to deal with an account but want to checkout at the click of a link (typically) in a quote we provide them. We also allow select customers to pay by Purchose Order and are simply entering a PO number and agreeing to terms. We are building in esignature workflow as part of the order-pay and checkout processes. Payment links Are a much needed capability for anyone selling B2b goods. 

My current solution involves commenting out the if statement in the core that produces this and I hate that I had to do that - it's the only core mod that I've had to make but a sales rep can take payment for an order or a customer be given a link to pay by either credit card, or in the case of a flagged customer, a purchase order. Regardless of payment the customer can then complete an eSignatire agreement. I don't care that a sales rep account is getting meta written from the order because I can basically erase it all. I figure I can rewrite the order-pay function at some point too instead of modifying core files.

**Comment by mikejolley** [comment]
@teammartinmiller  

```
I can guarantee a login form will flush 20% of our money down the toilet.
Have you seen a checkout funnel report from Analytics? For every page a
user has to navigate through, there is a >20% drop off in conversions.
Login pages are especially bad. Our wholesale customers like [insert the
name of a large U.S. specialty shop] place a large order every few months.
I would imagine the person who does this probably orders millions of
dollars of merchandise from at least 300 vendors. What are the chances that
he/she is going to remember their My Account login info for our site? So
now you've just added two to three minutes of password recovery to her busy
day. One of our competitors sends her some samples and she pays for them
from a link that takes her directly to a payment page. Boom. Now we've lost
a customer.
```

If you're not bothered about accounts and logins, don't assign orders to specific users? They are guest orders then. Otherwise accounts are needed to keep orders together and details of said user private..

Sounds like you need a POS plugin anyhow, even if you do not like the current options?

@sa561 

> I don't care that a sales rep account is getting meta written from the order because I can basically erase it all.

Isn't this dangerous? What if the rep forgets to clear than data on future orders, leaking customer details? Or worse, pays with another users credit card token?

These are all possibilities, and even if you're working around them, other less technical users may not realise. 

Virtual terminals are offered by many payment providers which are usually used for phone orders - then the CC details don't even go through your site.

**Comment by teammartinmiller** [comment]
We are using a POS plugin now.

Here are the two issues:

1) Having a direct pay link that doesn't require an account login and that
can be put in an invoice or email like every other invoicing program
(Freshbooks, Harvest App, Quickbooks) etc seems neither insecure nor
something that needs to be argued about. It just needs to be put on the
schedule to get done. Because if it isn't, people who actually make enough
money to pay Woocommerce for plugin support will start to migrate to
systems that make this possible, @mikejolley. There is too much money at
stake to not do this.

2) Woocommerce is supremely customizable. But this means that any changes
to the core need to be properly communicated ahead of time to the people
who actually use it -- not just developers. Plugin developers may not be
supporting things that everyone uses or changes may have been made once by
a contractor -- then the update breaks everything and users are in this mad
scramble to find out what's going on and how to fix it. Huge waste of time
and money plus lost sales. If there is already a mailing list then I need
to know where to sign people up.

**Comment by teammartinmiller** [comment]
Another problem with paying outside of Woocommerce is that the data is outside of Woocommerce with no way to get it back in except by doubling the work and entering data twice. And manually, increasing the chances of bad input.

It's like with marketing, Woo needs to be centered around the intent of a business owner with a growing e-commerce shop. Even if a client's site starts with one person buying from her and her shipping a product out of her garage, she wants it to eventually be retail customers buying full price as well as wholesalers buying her product at cost, and all products being shipped from a warehouse. When we help customers, it's with the goal of getting them through the beginning stages through to the end stage. 

Woo should design to fit the end-stage scenario, not just the beginning stages. Or at least have a clear roadmap of add-ons and plug-ins that are supported continuously by the core. This would include:
- wholesale pricing, phone orders
- shipping
- communicating with a warehouse
- POS

We've figured out how to do most of this, but no one has formally written up a guide. 

Plus, our site doesn't have a 2.6 version to go back to because we migrated from Shopify in the midst of all this 3.0 drama. Fortunately, we still see this as an advantage because of the customization options. But it's only a very slight advantage right now.

What we're scared about now is that someone is going to pull the rug out from underneath of us with a future update.

**Comment by amrod1** [comment]
Hi teammartinmiller. I have the same problem after i updated to WC 3
"Pay" link in the customer invoices now forces the customers to login.
Example link;
"http://www.domain.com/checkout/order-pay/3406/?pay_for_order=true&key=wc_order_59640e5f70ced "

Our customers want to click the link and put their info for the payment like they do in WC 2 or they want to make the payment over the phone.

Do you have any solution for this? I had to roll back to WC 2.

**Comment by EvolutionSigns** [comment]
If you send the invoice out as a "guest invoice" you don't get the login screen on the payment link - you can then easily change the customer to a registered account after payment so that customers can login and see previous orders (if required)

**Comment by RicoCallirgos** [comment]
This worked for me as a workaround in my functions.php.

`function your_custom_function_name( $allcaps, $caps, $args ) {
  if ( isset( $caps[0] ) ) {
    switch ( $caps[0] ) {
      case 'pay_for_order' :
        $user_id  = $args[1];
        $order_id = isset( $args[2] ) ? $args[2] : null;

        // When no order ID, we assume it's a new order
        // and thus, customer can pay for it
        if ( ! $order_id ) {
          $allcaps['pay_for_order'] = true;
          break;
        }

        $user = get_userdata( $user_id );
        if ( in_array( 'administrator', (array) $user->roles ) ) { 
          $allcaps['pay_for_order'] = true;
        }

        $order = wc_get_order( $order_id );

        if ( $order && ( $user_id == $order->get_user_id() || ! $order->get_user_id() ) ) {
          $allcaps['pay_for_order'] = true;
        }
      break;
    }
  }

  return $allcaps;
}
add_filter( 'user_has_cap', 'custom_function_name', 10, 3 );`

**Comment by TooeleShootingSupply** [comment]
Hello,

I would like to reopen this issue due to the incredible frustration it causes with your WooCommerce Deposits plugin.

Currently, with Layaway plans made by your Deposits plugin, the only way for a customer to make a Scheduled Payment early is by contacting the store (us) and requesting the next payment link be sent early. (This would be bypassed if there was a way for the customer to trigger that e-mail from their My Account -> Scheduled Orders page, but currently all they can do is View the order.)  Usually they will just call us up to request to make the next payment early, and since they've already called us, they like to just make the payment over the phone.

This is where it now becomes a headache. 

There is now currently NO way for us to quickly bring up their next payment link. We used to easily do it through the backend by just going to their Scheduled Order, changing the status to Pending Payment, and clicking on the Customer Payment Page link, but now we have one of two options:

1 - Pull up the Auth.Net backend and manually process the payment that way, making us copy over the customer info, billing address, email, etc and then once that's processed, manually change the Order Status to Complete.

2 - Remove the customer account assigned to the order, then mark it as Pending, process the order, and then re-add the customer account to the order.

We could also switch user accounts, but as that takes even longer to do than the above option, it's not really a viable solution either. 

Also, I have to bring up the obvious problem we've been seeing of customers forgetting their login info or not even realizing they aren't logged in! So when they actually click on the link in the e-mail to make their next payment on their layaway plan, if they aren't already logged in it kicks back an error. When the average age of our customer base is over 50 years of age, they get VERY frustrated VERY easily with errors like this, and then we are stuck dealing with angry customers.

I would never presume to tell you what to do, as I am a complete tech idiot compared to you lot. However, we have several hundred thousand dollars in layaways going at any given time, and this has been nothing but a headache since updating to 3.x. If you could please revisit this, possibly just make an optional admin permission to access these payment accounts that we can set on a per-admin-acct basis, it would be **extremely** helpful.

**Comment by mikejolley** [comment]
@TooeleShootingSupply There are workarounds above. An official solution would mean we need to get around the saving-credit-card-to-profile problem which *will* occur if you use a customer card. Thats not easy to solve.. Virtual terminals exist for this.

**Comment by chrisrae** [comment]
Just adding my voice to the choir - that (now gone) functionality of an admin loading the payment page was incredibly useful and as a result the amount of work required to process a manual order has increased significantly and makes for unhappy owners of WC driven sites.

**Comment by sa561** [comment]
This simplicity described herein is so critical to my model, I modify a
single woocommerce file to override the security check with every release
in order to have this functionality.

**Comment by EvolutionSigns** [comment]
>  There are workarounds above. An official solution would mean we need to get around the saving-credit-card-to-profile problem which will occur if you use a customer card. Thats not easy to solve.. Virtual terminals exist for this.

Hello Mike - would it be possible to have this as an advanced option which also disables the ability to save credit card info to the profile?

**Comment by mikejolley** [comment]
Potentially, but all gateways work differently so this may or may not be possible. Subscriptions is a good example; that *needs* tokens saved to the profile. Who's profile does it save to? This would need a deep dive from a developer. If anyone wants to take this on as either a feature plugin or core patch they are welcome too. Our team currently have other priorities so won't be able to look at this short term.

**Comment by sheilalalala** [comment]
If not possible, then please respect Guest Checkout option when selected, so that we can open in a separate browser.  Subscriptions and recurrent payments should never be allowed for Guest Checkout (makes no sense to have Subscription or Recurrent payments without a user/customer account on wordpress/woocommerce).

**Comment by sheilalalala** [comment]
Also it should be possible for store managers and admin to process a one time customer order (No saving of Credit Card numbers, no Subscriptions, and no Recurrent payments).  This is a big deal for us also.

Any workaround in functions.php is like a hack that can stop working on subsequent updates or create bugs/security problems, it should be part of the core woocommerce.  Thank you for taking this issue seriously and fixing it asap.

**Comment by danielbair** [comment]
I found this...
https://wordpress.org/plugins/woocommerce-pos/

**Comment by bestslopedesigns** [comment]
RicoCallirgos works perfectly fine in WC V3.4.2
