### ISSUE TITLE
Single Product Page - Thumbnail Images

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#14929]
Hi,

Thumbnail image size from WooCommerce options don't work

If you don't want to have flexslider inside single product page, then thumbnail image size will always be as main featured image size because you set that in code template product-thumbnails.php

**$html .= wp_get_attachment_image( $attachment_id, 'shop_single', false, $attributes );**

Only solution is to override whole template but for mine opinion this is bug in code and you can set some condition around this code if flexslider support is enabled to use this in otherwise to set **shop_thumbnail** image size.

Also could you modified filter hook inside this file, because it's same as in product-image.php file

**apply_filters( 'woocommerce_single_product_image_thumbnail_html', $html, $attachment_id );**

only difference is privileges  where you set attachment id so we need to add very big list with filter hooks inside theme to override all thumbnails with new code instead to use only one hook to apply changes for all thumbnails. Thanks

Best regards,
Nenad

**Comment by mikejolley** [comment]
Can can resize shop_single via the settings or with filters.

You can change woocommerce_single_product_image_thumbnail_html markup with a filter.

You can also see if the thumbnail passed through woocommerce_single_product_image_thumbnail_html is the same ID as the featured post image to know if it's the main image or not.

So it all seems possible as-is.

**Comment by braddalton** [comment]
@mikejolley 

`You can also see if the thumbnail passed through woocommerce_single_product_image_thumbnail_html is the same ID as the featured post image to know if it's the main image or not.`

Yes, possible as-is, however it would be more user friendly if you can add a specific filter for the main image rather than use 1 for both main image and thumbnail gallery images which is currently the case in product-image.php and product-thumbnails.php
