### ISSUE TITLE
Webhook with actions triggered twice

### ISSUE THREAD

**Issue by klaasnienhuis** [woocommerce/woocommerce#14957]
### EXPLANATION OF THE ISSUE

When using a webhook with an action, this webhook is triggered twice a few seconds apart. I've tried with the woocommerce_order_status_completed and woocommerce_order_status_processing webhook. both displayed this behavior. I'm using wc 4.7.4.

### STEPS TO REPRODUCE THE ISSUE

Create a new webhook
Set the topic to Action
Set the action event to woocommerce_order_status_completed
Create an order and set it to Processed
In my case the webhook now is triggered twice.

**Comment by mikejolley** [comment]
I did 2 tests based on your report without luck. 

Webhook for woocommerce_order_status_completed

Created processing order. No fires.
Changed order status to completed - fired once.
Created a completed order - fired once.

https://dl.dropboxusercontent.com/s/r0cis1v6727aa44/2017-05-09%20at%2013.14.png

Does not appear to be a duplication issue with core alone. Maybe narrow what you have active to narrow your issue?

**Comment by vforteli** [comment]
I recently ran into this issue as well.
If I manually complete an order that is on hold, woocommerce_order_status_completed is fired twice.
If I first change the status from on hold to processing, and then complete it, woocommerce_order_status_completed fires once.
Maybe related?

**Comment by LacerdaPT** [comment]
Hello 

I'm getting the same issue with the woocommerce_order_status_processing hook. 
This doesn't always happen but it has serious consequences even if it only happens every once in while. As far as I can tell this happens when the order is paid for with credit card (with the stripe plugin).
You'd think this is a problem with the stripe plugin (and it might and I posted an issue on the plugins page) but if I go to Woocommerce->Settings->Logs I can see the “woocommerce-gateway-stripe-” only recording the first time, but the “webhooks-delivery-” has the two fires 2m30s apart.

Any ideas?
Cheers

**Comment by th3happybit** [comment]
Hello
I'm having the same issue when using a credit card payment, any solution please?

**Comment by Aleksandar-Mitic** [comment]
The same issue here! On order_created action. And the second webhook does not contain signature, so it bumps on 403 reponse. Therefore later the same webhook get's disabled after XY failed attempts to reach destination URL.

**Comment by JohnMarsden24** [comment]
Happening to me as well, the last active webhook gets fired twice and same as Aleksandar above my API rejects it. Here's the logs from Google Cloud:

```
Function execution started
[0mPOST /v1/orders/shipping-confirmation [32m200[0m 1159.595 ms - 65[0m
Function execution took 1164 ms, finished with status code: 200

Function execution started
ApiError: Invalid request
StatusCode: 401
[0mPOST /v1/orders/shipping-confirmation [33m401[0m 0.809 ms - 116[0m
Function execution took 5 ms, finished with status code: 401
```
