### ISSUE TITLE
[WC 3.0] Fatal error calling WC_Product->has_attributes() on variation product

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#14959]
### EXPLANATION OF THE ISSUE

Calling `$variation->has_attributes()` triggers the fatal error:

```
 PHP Fatal error:  Call to a member function get_visible() on string in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 1540
```
### STEPS TO REPRODUCE THE ISSUE

Use a code snippet like this:

```php
$variation = wc_get_product( 16685 ); // Where 16685 is a variation ID
$variation->has_attributes();
```

-------------

The issue appears to be caused by an change in the type of data returned from `WC_Product::get_attributes()` on `2.6.x` and `WC_Product_Variation::get_attributes()` on `3.0`. 

Previously `WC_Product::get_attributes()` would return an array of attributes along with the attribute data when called on both variation and variable product objects. However, on `3.0` this has changed to an array of `WC_Product_Attribute` objects for variable products and an array of strings for variations.

**Comment by mikejolley** [comment]
Variations in 2.6 would always return false for this because variations themselves do not have attributes like real products. We can add a variation specific method.

**Comment by Estees** [comment]
Don´t waste your time. It´s absolutely simple. The Theme doesn´t support the new version 3.0 of Wocommerce. I returned to WC version 2.67 and everything works perfect now.

**Comment by james-allan** [comment]
> Variations in 2.6 would always return false for this because variations themselves do not have attribute terms like products

I'm not sure that's right. Please correct me if I'm wrong but in WC 2.6 variations inherited the function `get_attributes()` from the `WC_Product` class. `WC_Product::get_attributes()` would get the list of attributes [here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-product.php#L1409), inside the `WC_Product_Variation::__get()` function there was no special handling for `product_attributes` keys and `_product_attributes` meta was not stored against the variation ID so it would fall back to [`parent::__get( $key )`](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-product-variation.php#L146). Inside `WC_Product::__get( $key )` the `_product_attributes` meta was pulled from post meta using `$this->id` which for variation products was the parent product's ID. 

So back in WC 2.6 `$variation->get_attributes()` would return the same data as `$variable->get_attributes()`, which meant `$variation->has_attributes()` would also return the same as `$variable->has_attributes()`. With #14962 that's no longer the case.

**Comment by mikejolley** [comment]
You may be correct, but variations should not inherit attributes from the parent because a variation is not mapped to multiple attributes like the variable product. No terms are assigned to a variation itself. Variations should have 1:1 mapping to attribute terms, hence it's name/value pairs.

`has_attributes()` itself is used in one place; to see if attributes need outputting on the additional info tab. Variations are not displayed like products so have no use for it.

**Comment by jvoosten** [comment]
I would just like to point out that this change broke one of my plugins :-( I am using an extra attribute in the 'parent' product to control the behaviour of my plugin. This worked fine in WooCommerce < 3.0 because get_attributes() included the parent attributes for a variation, and IMO it actually makes sense to do so. Now I have to make a distinction in my code between WC_Product and WC_Product_Variable and do some magic to get the correct attribute.
