### ISSUE TITLE
Fatal error calling wc_get_payment_gateway_by_order for a refund

### ISSUE THREAD

**Issue by dgwatkins** [woocommerce/woocommerce#14973]
### EXPLANATION OF THE ISSUE

With WooCommerce 3.0.6 only active and twentysixteen theme I get a fatal error calling the wc_get_payment_gateway_by_order() function with a refund id.

With 2.6.14 it doesnt happen.

### STEPS TO REPRODUCE THE ISSUE

- Refund an order and take a note of the refund id.
- Run the following code replacing the 47800 with your refund id:

`$payment = wc_get_payment_gateway_by_order(47800);`

You get:

`Fatal error: Call to undefined method WC_Order_Refund::get_payment_method() in wp-content/plugins/woocommerce/includes/wc-order-functions.php on line 707`

**Comment by mikejolley** [comment]
Refunds are not the same as orders - I'd argue this has been fixed since refunds do not get payment methods stored to them.

We need to add validation that the order being loaded is indeed an order and not a refund maybe by looking at the class with `is_a()`. If it's a refund, return false - there is no gateway.
