### ISSUE TITLE
Add Northern Ireland as Shipping Zone

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#15066]
### EXPLANATION OF THE ISSUE

United Kingdom has several territories added as individual shipping areas: 

* Isle of Man 
* Jersey 
* Guernsey

Can we add Northern Ireland to that list?

It is part of the UK, but not part of mainland UK and thus many Irish shops ship to ONLY Northern Ireland and do not want to show "shop to all of UK". 

Can we add Northern Ireland to the shipping zones (like Isle of Wright) to service WooCommerce users in Ireland (who usually ship to Ireland AND Northern Ireland, but not the rest of the UK). The workaround - using UK and restricting by postcode area is not very end-user friendly, since it gives the impression that all of UK is served. 

Northern Ireland has the following counties: County Antrim, County Armagh, County Down, County Fermanagh, County Londonderry, County Tyrone

**Comment by ValeDeOro** [comment]
567909-zd-woothemes
Recommended as a workaround: https://docs.woocommerce.com/document/add-a-new-country-to-countries-list/

**Comment by mikejolley** [comment]
Refer to https://en.wikipedia.org/wiki/ISO_3166-1

The difference between Isle of Man, Jersey, Guernsey and Northern Ireland is that Northern Ireland does not have an ISO country code - it's part of GB. So a top level country cannot be added - we cannot make up non-standard ISO country codes :)

> who usually ship to Ireland AND Northern Ireland, but not the rest of the UK

This is an assumption?

> Unfortunately some people still believe that Northern Ireland is a Foreign country and as such requires postage costs in the extortionate to get here. WRONG. Believe it or not Royal Mail WILL bring post to us and more shockingly for the same price as you would send something from London to Glasgow for example (Obviously depending upon where you are in the country). 

http://www.ebay.co.uk/gds/Postage-to-and-from-Northern-Ireland-/10000000003791864/g.html

AFAIK shipping costs within the UK, regardless of whether it's NI, are the same. I don't think we need to make special allowances in core for this. 

> Recommended as a workaround: https://docs.woocommerce.com/document/add-a-new-country-to-countries-list/

This is fine if needed - you can also add states for the counties/regions if needed, but we don't want to add this in core because it's not required for shipping (postcode is the most important thing for UK addresses and NI have postcodes if you need to have a NI specific zone).

**Comment by ya-well** [comment]
I appreciate that this issue is marked closed and non-actionable but having worked on a few Irish / UK sites, I would like to weigh in behind this request as I believe it would make sense for many IE/UK sellers. While there are a number of workarounds availble to add countries to WC - one of which I'm working through at the moment - I and I imagine others would take comfort if something as central as countries were available from the core without the need to write them in manually

I'd like to discuss a few points made above also...

>... Northern Ireland does not have an ISO country code

Could [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:GB#Countries_and_province) be utilised here? As far as I can gather, it's basically 3166-1 with some sub-divisions appended


>     who usually ship to Ireland AND Northern Ireland, but not the rest of the UK
>This is an assumption?

&

> AFAIK shipping costs within the UK, regardless of whether it's NI, are the same. I don't think we need to make special allowances in core for this.

Not so much. It is common for UK mainland sellers to charge extra to ship from the UK mainland to NI and some refuse altogether. This is perhaps even more evident in the opposite direction with sellers in NI / RoI shipping (or not shipping...) into the UK mainland. While Royal Mail offer equal pricing from the UK mainland to NI and vice versa, the private couriers most certainly do not. Couriers pass on the cost of traversing the Irish Sea which means parcels from UK --> NI or NI --> UK can be twice or three times the cost of UK mainland internal. Also, if sending "across the water" via the national postal operators - there are restrictions to be considered on items containing batteries, aerosols, etc...

Another scenario would be where businesses in the Republic of Ireland and Northern Ireland would ship to / do business with each other but not the UK mainland. This can be common for smaller companies shipping product or for companies offering services on the island of Ireland or "both sides of the border" as we say but WooCommerce can't easily cater for this scenario as NI isn't broken out from the default "United Kingdom"

From a shipping stand-point, yes we can use post-code triggers so when the customer types "BT1 xxx", the cart returns the pricing for Northern Ireland. However, I have found - with sellers in the Republic of Ireland -  that this leads to a bad customer experience and cart abandonment as the cart will display the much more expensive UK shipping cost until the customer types in their Northern Ireland postcode.

I added this as an idea a few days back where I explain the scenarios a bit better perhaps. I'd love to hear some feedback or see some votes on the topic [Idea: Split "United Kingdom" into England, Scotland, Wales & Northern Ireland](http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/19756804-split-united-kingdom-into-england-scotland-wal)

**Comment by mikejolley** [comment]
@ya-well Those iso codes would have an impact on shipping services which expect GB. 

Also speaking personally, when I shop online I **never** look for "england". No store I've ever used has done that instead of United Kingdom. Look to amazon for examples.

**Comment by ya-well** [comment]
Agreed re. the 3166-2 ISO's and afaik, Paypal also looks for a 3166-1 ISO code so anything but "GB" might play badly with it (Stripe doesn't mind what country code is presented from what I can tell). As an alternative, can you forsee an issue with adding Northern Ireland but giving it the country code "GB" also... duplicate ISO codes in effect

As for _"looking for England"_, I don't expect any customer on the mainland would ever do this, settling for "United Kingdom" in all cases. Northern Ireland is a different kettle of fish from both a seller and customer POV. Firstly, to debate with a customer from Northern Ireland whether they belong to NI or the United Kingdom... don't ever do that is my advice! There are people in Northern Ireland who would wince at the thought of selecting United Kingdom when buying online... sad reality. From a seller's stand-point, the fact is that a number of UK / IE couriers with whom the seller will work with list and price Northern Ireland seperately to the UK (examples: [Yodel](http://www.yodel.co.uk/send/), [Fastway IRL](https://www.parcelconnect.ie/), [DPD UK](http://www.dpd.co.uk/pdf/DPD_Tariff_Guide.pdf), [An Post](http://postage.anpost.ie/transit.asp))

As for Amazon, it would seem Amazon prohibit sellers from excluding Northern Ireland from the UK - yet some still do. 
[Amazon Seller's take on NI](https://sellercentral-europe.amazon.com/forums/thread.jspa?threadID=89058)
[Amazon Customer's take on NI](https://www.amazon.co.uk/forum/deals?_encoding=UTF8&cdForum=Fx1DEIHNWYF5SA9&cdThread=Tx3R4N2YE6QM56N)
