### ISSUE TITLE
Backorder notification – clearer customer advice

### ISSUE THREAD

**Issue by seoidau** [woocommerce/woocommerce#15092]
### EXPLANATION OF THE ISSUE

Testing version 3 on a local copy of a site, I think the only thing stopping me from updating the live site is the way backorder availability is notified on product pages. As [previously raised](https://github.com/woocommerce/woocommerce/issues/14530), having a product in stock with backorder possible, and advising the customer that it is 'In stock (can be backordered)', is conflicting and sounds like it _has_ to be backordered.

I preferred the way it was; when the low stock threshold was met the backorder advice was given (one of the points for having a low stock threshold). However if we must have this advice no matter how much stock there is, may I suggest we advise customers that  '_more_ can be backordered'. By including 'more' we clearly say that the shop has stock and the ability to backorder more is an option if need be.

### STEPS TO REPRODUCE THE ISSUE

1. Edit product.
2. Product data box > Inventory tab > Allow backorders? option.
3. Select drop-down list item 'Allow, but notify customer'.
4. View product page.

### SYSTEM STATUS

<details>

**WordPress environment**
Home URL:		https://localhost/nordicware
Site URL:		https://localhost/nordicware
WC version:		3.0.6
Log directory writable:		✔ C:\xampp\htdocs\nordicware/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		✔
Language:		en_AU

**Server environment**
Server info:		Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.27
PHP version:		5.6.27
PHP post max size:		128 MB
PHP time limit:		120
PHP max input vars:		1000
cURL version:		7.50.3, OpenSSL/1.0.2d
SUHOSIN installed:		–
Max upload size:		128 MB
Default timezone is UTC:		✔
fsockopen/cURL:		✔
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		✔
GZip:		✔
Multibyte string:		✔
Remote post:		✔
Remote get:		✔

**Database**
WC database version:		3.0.6
Database prefix	 	nordicpress_
woocommerce_sessions	 	✔
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔
woocommerce_shipping_zones	 	✔
woocommerce_shipping_zone_locations	 	✔
woocommerce_shipping_zone_methods	 	✔
woocommerce_payment_tokens	 	✔
woocommerce_payment_tokenmeta	 	✔

**Security**
Secure connection (HTTPS):		✔
Hide errors from visitors		✔

**Active plugins (22)**
iThemes Security	 	by iThemes – 6.2.1
Contact Form 7	 	by Takayuki Miyoshi – 4.7
Cooked Recipe Plugin	 	by Boxy Studio – 2.4.1
Duplicator	 	by Snap Creek – 1.2.6
Force Regenerate Thumbnails	 	by Pedro Elsner – 2.0.6
Giftable for WooCommerce	 	by Decom – 0.9.12
Jetpack by WordPress.com	 	by Automattic – 4.9
Lightweight Grid Columns	 	by Tom Usborne – 0.7
MailChimp for WordPress	 	by ibericode – 4.1.2
Search By SKU - for Woocommerce	 	by Matthew Lawson – 0.6.1
Woo Stickers by Webline	 	by Weblineindia – 1.1.0
WooCommerce Colors	 	by WooThemes – 1.0.6
WooCommerce Expand Tabs	 	by Diana Burduja – 1.4
WooCommerce Stripe Gateway	 	by WooCommerce – 3.1.8
WooCommerce Google Analytics Integration	 	by WooCommerce – 1.4.2
WooCommerce MailChimp	 	by Saint Systems – 2.1.0
WooCommerce Prices By User Role	 	by Festi-Team – 3.1
WooCommerce Product Archive Customiser	 	by jameskoster – 1.0.5
WooCommerce Stock Manager	 	by Vladislav Musílek – 1.1.4
WooCommerce	 	by Automattic – 3.0.6
Yoast SEO	 	by Team Yoast – 4.7.1
WP User Avatar	 	by flippercode – 2.0.8

**Settings**
API enabled:		✔
Force SSL:		–
Currency		AUD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		dgfw_gift (dgfw_gift), external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

**WC pages**
Shop base:		 Page not set
Basket:		#6 - /basket/
Checkout:		#7 - /checkout/
My account:		#8 - /account/

**Theme**
Name:		Storefront Child
Version:		1.0.0.1.2.3.4.5.6.7.8.9
Author URL:		
Child theme:		✔
Parent theme name:		Storefront
Parent theme version:		2.1.8
Parent theme author URL:		https://woocommerce.com/
WooCommerce support:		✔
</details>

**Comment by mikejolley** [comment]
This issue was to ensure the message was displayed like in 2.6 https://github.com/woocommerce/woocommerce/issues/14530

I don't know if it's a language thing or a translation issue but "can be backordered" does not sound like "has to be backordered" to me...it says "can". It's a possibility. It still states how many units are actually in stock.

FWIW it's shown because even if you had say 5 units in stock, if the user wants 10 this is more evident.

Backorders are due a refactor anyhow: https://github.com/woocommerce/woocommerce/issues/11259

For now you can tweak the text via translation files, a plugin (loco translate/say what), or the gettext filter in WordPress if you want to try a tweak in wording. I don't think we should change core without more feedback, so this can wait for #11259

**Comment by olarionov** [comment]
Hi, 
Thank you for your reply and all hard work you do to make WC better. 
As per description of the issue in my ticket, I'd like to add this. To show the stock quantity on the product page is optional and configurable (which is excellent). Many stores are configured do not show stock QTY on the product page. So If I have only 1 or 2 items in stock and allow backorder, the stock message in WC 3.0.7 says "In stock (can be backordered)". As a customer, I can read it as this product "in stock as backordered" and need to wait longer for delivery (1 or more months), so I would not buy and move somewhere else. The customer must not see word "backorder" on a product page with items in stock. You will never find any online store that would do that, why you introduce this problem in WC3?. Try to find any online store based on Magento or other platform that will display word "backorder" in any variation of a sentence on a product page where  a product is actualy in stock, this doesn't exist in the World. The only place we want to show that product of such QTY is on backorder during check-out if the customer ordered more that in stock. I have to hire PHP developer at $50/HR to wok on this issue and to revert it back as in WC2.6 in order to upgrade. Please don't introduce new feature like this if you never had a request from business that this is useful , at least make it optional or configurable. Make a simple checkbox for this new feature wording, so users can decide if they need it to use. PLEASE revert it back as it was in WC 2.6 to show only "In stock" phrase. Or make it configurable.

Thanks again!

**Comment by olarionov** [comment]
Could you please give me a hint where do I change it? Where do I update the translation?
Thank you so much!

**Comment by mikejolley** [comment]
You can use a gettext filter or a plugin like "say what"/"loco translate"

**Comment by olarionov** [comment]
Hi Mike,

I have tried this and it did not work because the test string for translation includes text in brackets (can be backordered)

If i remove the text in brackets the translation will work, but I do actualy need to catch that text in brackets and take it away;

Here is the code I use, may be I need to you special formatting for this particular case?


/*** GetText filter **/
add_filter( 'gettext', 'theme_change_comment_field_names', 20, 3 );
/**
 * Change comment form default field names.
 *
 * @link http://codex.wordpress.org/Plugin_API/Filter_Reference/gettext
 */
function theme_change_comment_field_names( $translated_text, $text, $domain ) {

    if ( is_singular() ) {

        switch ( $translated_text ) {

            case 'In stock (can be backordered)' :

                $translated_text = __( 'In stock', 'flatsome' );
                break;

        }

    }

    return $translated_text;
}

Thank you for the help!

Oleg

On May 23, 2017, at 3:41 PM, Mike Jolley <notifications@github.com<mailto:notifications@github.com>> wrote:


You can use a gettext filter or a plugin like "say what"/"loco translate"

**Comment by mikejolley** [comment]
Brackets can be translated too...

**Comment by olarionov** [comment]
How? Can you please tweak the code I sent?

Thanks
On May 23, 2017, at 5:13 PM, Mike Jolley <notifications@github.com<mailto:notifications@github.com>> wrote:


Brackets can be translated too...

**Comment by seoidau** [comment]
As I wrote initially, the new text added to backorder-possible products is conflicting – in-stock _and_ on backorder..? As a customer this is confusing and would put me off.

Yes it may sound like it 'can' be backordered, but it doesn't have to be. Woo doesn't state how many units are actually in stock until the product reaches the low stock threshold, which is when this backorder notification is necessary. You can have a million units in stock and it will still say it 'can' be backordered. 

I installed Loco Translate to edit this text and it worked. However using a plugin to add five characters once feels like overkill. I was hoping that adding a small bit of code in functions.php would have been possible.

**Comment by mikejolley** [comment]
@seoidau https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext

**Comment by olarionov** [comment]
Mike,

I have tried this code in functions.php and it didn’t work because the part of the string is text in round brackets (can be backordered).
If I use only part of text without brackets (or outside of round brackets) – it works.
Basically the text in round brackets does not translate. Not sure what is the work around this.

/*** GetText filter **/
add_filter( 'gettext', 'theme_change_comment_field_names', 20, 3 );
/**
* Change comment form default field names.
*
* @link http://codex.wordpress.org/Plugin_API/Filter_Reference/gettext
*/
function theme_change_comment_field_names( $translated_text, $text, $domain ) {

    if ( is_singular() ) {

        switch ( $translated_text ) {

            case 'In stock (can be backordered)' :

                $translated_text = __( 'In stock', 'flatsome' );
                break;

        }

    }

    return $translated_text;
}


Thanks
On May 24, 2017, at 8:14 AM, Mike Jolley <notifications@github.com<mailto:notifications@github.com>> wrote:


@seoidau<https://github.com/seoidau> https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext

**Comment by mikejolley** [comment]
The brackets really should not mater here; why not var_dump the string and see what is being passed through?

**Comment by olarionov** [comment]
Where do I plug this code for var-dump?

**Comment by mikejolley** [comment]
The string you should be translating is just:

`(can be backordered)`

**Comment by olarionov** [comment]
You mean translating it into empty string ‘“ ( a.k. nothing)? So it will leave only ‘In stock’ part of the string?

On May 24, 2017, at 1:12 PM, Mike Jolley <notifications@github.com<mailto:notifications@github.com>> wrote:


The string you should be translating is just:

(can be backordered)

**Comment by mikejolley** [comment]
Or a different string.

**Comment by catrymer** [comment]
I wanted to weigh in on this as we've seen quite a few reports about this exact issue as well. I believe the problem is that "Allow, but notify customer" can be interpreted two ways and how you want it to work on your own shop depends on what kind of store you are running.

This can mean that you want to always communicate, no matter the current stock levels, when an item is available for back order. This makes a lot of sense in the example you gave, Mike ,where someone is running a shop that makes it common for folks to bulk order products and you want them to know that even though there are only a few left they can still order however many they need of that particular item. This especially makes sense if you have a shop where customers typically bulk order products, and not *everything* is available for backorder so you need to clearly communicate what is and is not. 

However, this setting can also mean, as it does for many of the shop owners weighing in on this thread, that you only want to notify people about the ability to backorder something when it actually is on backorder. For shops that sell items you typically buy only one of at a time, especially large and expensive things, this interpretation makes more sense. If you are trying to buy a new sofa and you have the choice between one that's available now and one that's on backorder, you will factor that into your decision. For shops like this, you can end up losing business if your customers believe an item is on backorder when it isn't. For them, not having the ability to only display this message when an item is actually out of stock can interfere with their ability to run their shop successfully.

Can we revisit the way "Allow, but notify customer" works? Ideally shop owners should be allowed to decide if they want the backorder message to always display versus if they want it to only display when an item is out of stock.

**Comment by seoidau** [comment]
I agree with @catrymer, shop owners should be allowed to decide if they want the backorder message to display. In my instances it is when the product reaches the low stock threshold, like it was.

Oh, and actually advising customers of _how many are backorders_ on the basket page would be better, too. Woo has always just said 'Available on backorder' despite, say, 2 in stock and I want to buy 4. If a customer adds products to their cart without visiting the product page, they're never notified.

**Comment by mikejolley** [comment]
Revisiting the setting will require a refactor, so it should really be done with https://github.com/woocommerce/woocommerce/issues/11259 since it's not a quick change.

**Comment by LeighBelles** [comment]
Hi, Ive only had a website for a short while so I am not very experienced but I have been researching endlessly and cant find any one else experiencing quite the same problem as me so im really hoping one of you may have the answer.  
I sell lots of items that are not in stock so I need to allow back orders but in doing so my customers are not able to use a product filter to easily find items that are in stock. This would be useful as sometimes my customers need items quickly and are only interested in stock that can be delivered within 1-3 days. If all items need to be listed as in stock to enable back orders then Is there any code that would enable product filters only to show stock with a quantity equal to or greater than 1? I would really appreciate any guidance. thank you
