### ISSUE TITLE
Can't upload images using new REST API v2 with a product update

### ISSUE THREAD

**Issue by cnkcp** [woocommerce/woocommerce#15385]
### EXPLANATION OF THE ISSUE

 WooCommerce 3.4 ,REST v2 , I am trying to upload product images with the update product call(PUT) .  
 I get a response StatusCode = OK, but the image is not uploaded. My src is an external URL
I have used this same method in the legacy v3 api and it worked.

### STEPS TO REPRODUCE THE ISSUE

1.The id of the product I am trying to upload an image to is 625
 the host is https://"mydomain"/wordpress/wp-json/wc/products/625
 the payload is {"images[{"src":"http://services.cloud9retail.net/companies/Testgolf/images/VEST.jpg","position":0}]} 

### SYSTEM STATUS

<details>

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

I suspect your request is being accepted as a GET request rather than PUT. Some servers do not support PUT.

You can try updated other props at the same time to be sure. I'm having no issues on my side with the images prop - it sets as it should, and on failure it gives an error code.

Thanks
