### ISSUE TITLE
Icon font blurry in Firefox

### ISSUE THREAD

**Issue by diggy** [woocommerce/woocommerce#15434]
out of the box:

![ff-1](https://cloud.githubusercontent.com/assets/1071337/26751494/0dc1b64a-483b-11e7-94e3-aa1cc6366458.png)

with `-moz-osx-font-smoothing: grayscale;`:

![ff-2](https://cloud.githubusercontent.com/assets/1071337/26751496/14cfef7e-483b-11e7-80b5-08b2051c0a69.png)

- macOS Sierra 10.12.3
- Firefox 53.0.3

**Comment by mjassen** [comment]
Hi, thanks for writing. I am looking on firefox on a dev setup, in the Admin dashboard, under "Products" menu. 

I don't immediately see the symptom. Can you write back a description of where (which screen) is being viewed when the symptom manifests itself?

( I couldn't tell which screen it is from the two screenshots above, as they don't show the rest of the page nor the page url)

A screenshot of my point of view:
<img width="500" alt="screen shot 2017-06-03 at 12 06 45 pm" src="https://cloud.githubusercontent.com/assets/1563241/26755412/bd65b208-485a-11e7-901f-74479ff5310a.png">

my test environment:
macOS Sierra 10.12.5
Firefox 53.0.3 (64-bit)

**Comment by diggy** [comment]
@mjassen checking on my macbook now (MacBookPro10,1, retina) and the icons look fine; at work however I connect to two extra monitors, on which the font is displayed as in the screenshots I posted. Far from an expert on the matter, maybe this is due to my setup and/or config, i.e. false alarm?

**Comment by mjassen** [comment]
@diggy 

Ok- seems like something outside of the WooCommerce environment. 

Curious, though, that it if it is a monitor/graphics issue with that Mac/monitor setup, curious that it affects Firefox and not Chrome, and that the CSS snippet resolves it in that case!

If it can be found how to reliably reproduce the symptom on other environements, then mabye re-open this as WooCommerce issue, otherwise I think a good next-step is try and find out how to update/modify that particular mac/monitor environment.

**Comment by diggy** [comment]
left Chrome, right FF:

![screen shot 2017-06-05 at 13 06 14 3](https://cloud.githubusercontent.com/assets/1071337/26781662/06127f54-49f0-11e7-84f2-e6044f7f9615.png)

**Comment by mjassen** [comment]
@diggy 
I was looking into what generates this font icon. It seems like character "...006" in WooCommerce.svg. 

However I'm getting stuck on troubleshooting it -- figuring out how apparently JavaScript is generating this icon on-the-fly.

I'm thinking a good next step is to isolate the exact font icon (for example in a sample .html file), and then proceed to try and replicate the symptom, and then move forward to figure out why it is happening in firefox and not Chrome (for that computer monitor/setup)

**Comment by mjassen** [comment]
@diggy 

Where was it that you inserted the `-moz-osx-font-smoothing: grayscale;`?
In the browser inspector? Or in a .css file? or in some custom css area? or __(somewhere else, insert here)____?

Can you please look back on that exact computer monitor, in Chrome and then in Firefox, and confirm for sure that on that particular monitor it is symptomatic only in Firefox and not in Chrome? It seems strange to me!

But I'm thinking that if it is, then the css snippet above fixing it will be a good place to start to shed some light on the issue to start to trace back the symptom to its cause -- that's why I'm asking exactly where the custom css was inserted.

Looking forward to read your reply!
