### ISSUE TITLE
Checkout Page JS preventing custom field validation events.

### ISSUE THREAD

**Issue by reescott** [woocommerce/woocommerce#15430]
### EXPLANATION OF THE ISSUE

I'm building a custom payment gateway, and trying to add custom validation on checkout page fields. I'm finding that my custom events are being removed by [assets/js/checkout.js line 35](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L35). When I dequeue this script, I am able to add click/blur handlers as expected. What would be a good way to allow the validate_fields function to be extendable for custom field validation, or at least not remove custom event handlers from fields on the checkout page?

### STEPS TO REPRODUCE THE ISSUE

Add a custom 'blur' or 'click' event handler to a field via a custom enqueued script. Notice that the events do not fire.

**Comment by mikejolley** [comment]
Look at https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L180

There is no `e.preventDefault` call here, so actually custom event handlers will still be ran.

I'd expect you're just being affected by the order functions run and these lines:

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L189
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L217

This may need some experimentation to make it compatible with your code (PR welcome once working) but I'd suggest trying to:

a) add a trigger event in our function after the initial class clear
b) attach error data to the input rather than removing and adding classes throughout the function + your own validation class
c) at the end of the function, look at the error data and THEN update the classes based on this so custom validation functions are also respected.

> Add a custom 'blur' or 'click' event handler to a field via a custom enqueued script. Notice that the events do not fire.

This however does not appear to be true. Using:

`
jQuery('.input-text').blur(function() {
	alert(1);
});
`

shows it no problem.

**Comment by KenStoneBlue** [comment]
I'm having this exact same issue.  Doing the same, adding a payment gateway.  

I add something like
`$("#variant_cell_phone, #variant_msg_phone").keyup(function(e){`
to do some replace as the user is typing but events are not happening...

Among other things....

**Comment by KenStoneBlue** [comment]
I don't understand why the woo fields fire but the fields I add for the custom payment gateway do not
For example this and similar continue to work no problem at all.
`$("#billing_first_name").change(function(){`
