### ISSUE TITLE
Feature Request: REST API – Filter Orders by Modified Date

### ISSUE THREAD

**Issue by bhanuc** [woocommerce/woocommerce#15444]
In the older v3 API, You could have filtered orders by modified_date.
Like:
http://storeurl.com/wc-api/v3/orders?filter%5Bupdated_at_min%5D=2017-03-20&filter%5Bupdated_at_max%5D=2017-04-20

Now the options available are: after and before which are based on the create date of the order. 

Use Case for getting orders by modified is a call for action for orders that were updated recently.

**Comment by mikejolley** [comment]
Feature requests should go to --> http://ideas.woocommerce.com/forums/133476-woocommerce

This will be included in a future release, probably with v3 API, [once the order search helpers have matured](https://github.com/woocommerce/woocommerce/issues/13646) (they are coming in 3.1). 

For now, you can still introduce custom filters for any endpoint in the same way you can introduce filters in the WordPress REST API.

If you're just wanted to know when orders update, consider using a webhook instead of the API so you can listen for updates.
