### ISSUE TITLE
added_to_cart is triggered too early

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#15447]
The javascript trigger `added_to_cart` in [add-to-cart.js ](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart.js#L69) is triggered too early – before the product is added to the cart. The global trigger is called before WC does it own stuff and so it's not possible to do the same thinks like in WooCommerce 2, e.g. manipulating the `.add_to_cart_button.added` or `.added_to_cart` elements.

In WooCommerce 2, after `added_to_cart` has bee triggered, the add button has class `.added` and the new link `added_to_cart` exists.

In WooCommerce 3, after `added_to_cart` has bee triggered, the add button has class `.loading` and the new link `added_to_cart` not exists.

This is a big BC break.

**Comment by mikejolley** [comment]
Change made here by a contributor: https://github.com/woocommerce/woocommerce/commit/cf6c42fb016e6edb6efeb979c3b1c294f43f272d

I disagree it's too early. The product has been "added to cart" because the event is triggered once the AJAX add to cart is complete.

Once this event is fired, WC will append those links and elements rather than in 2.x where WC would do it before firing any such events.

I'm not willing to revert this because the new structure is more flexible, and it was made in 3.x which is a major update anyway. You can either adapt your code to add your event handler later, after us, so that when your event fires our custom handler is finished and the markup is up to date, or you can use a different event (adding some new ones now for 3.1).

**Comment by Babelfisch** [comment]
In order that the `added_to_cart` trigger makes no sense and you break backward compatibility without any reason. It's very easy for you to call `added_to_cart` later but it's your decision, to make some plugins useless.

**Comment by mikejolley** [comment]
added_to_cart does make sense if you need to call custom events (like the contributor who made the change used it for).

> You can either adapt your code to add your event handler later, after us, so that when your event fires our custom handler is finished and the markup is up to date, or you can use a different event (adding some new ones now for 3.1).

Maybe you missed this.

**Comment by Babelfisch** [comment]
I see only the later called `wc_fragments_loaded` trigger but i'm not sure, if it always called.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15448
