### ISSUE TITLE
Bug with decimals in everyplace and for how tries to update to 3.1 beta 1

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#15457]
I'm receiving reports from people testing 3.1 beta 1 that are having issues with decimals when update.

I had a few trouble too creating orders on admin:

![screenshot from 2017-06-05 15-28-41](https://cloud.githubusercontent.com/assets/1264099/26797692/1e4f83a0-4a04-11e7-8dfd-6c1feee98a23.png)

This need to be revised and check where is failing to properly convert since the last changes with `wc_format_decimal()`.

**Comment by claudiosanches** [comment]
cc @mikejolley @Ninos

**Comment by claudiosanches** [comment]
Sounds part of #15458

**Comment by mikejolley** [comment]
Adding tests.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15469 - this change needs to be removed.

**Comment by Ninos** [comment]
As I understood correctly, sometimes prices are saved in database in localization format, not as float (raw format)? Because following check is for validating the format type (raw or localization) `strval( floatval( $number ) ) !== $number`. It's strange, but if the thousand removal makes so much problem, it should be better to remove it from code.
For future it should always be better to save all prices in raw format and only use wc_format_decimal when really needed.

@claudiosanches Can you please tell me the used decimal and thousand seperators. I want to investigate what happend wrong to understand the problem a bit better :-)

**Comment by claudiosanches** [comment]
@Ninos period for thousands and 2 digits decimals with commas, like in the screenshot.

**Comment by Ninos** [comment]
Ok, bug found. This happens because wc_format_decimal is running twice. Let me explain with a small example:
```
$number = "18,50";
$number = wc_format_decimal( $number ); // Returns 18.50
$number = wc_format_decimal( $number ); // Returns 1850
```

Normally this must not happen because of my check `if ( ! is_float( $number ) && strval( floatval( $number ) ) !== $number ) {`. Too bad that `strval( floatval( $number ) ) !== $number` here returns true, because `strval( floatval( "18.50" ) )` returns `18.5`.

To sum up, it's because of the zero, following number will work fine: `18,5`:
```
$number = "18,5";
$number = wc_format_decimal( $number ); // Returns 18.5
$number = wc_format_decimal( $number ); // Returns 18.5
```

### How to solve
You can add the thousands removal, you just need to replace following line:
```
if ( ! is_float( $number ) && strval( floatval( $number ) ) !== $number ) {
```
with
```
if (  'string' === gettype( $number ) && ! is_numeric( $number ) ) {
```

With this change something like that should never happen again. If you want I can start my last try (PR) with some more testings.

It was very bad that I thought `strval( floatval( $number ) )` will solve our problem in an elegant way.

**Comment by mikejolley** [comment]
The code makes sense already if you understand how php converts floats to strings. It uses its locale decimal points.

**Comment by Ninos** [comment]
Yeah, you're right. As answered in the PR, I've replaced `strval()` with `wc_float_to_string()` :-)
