### ISSUE TITLE
Implement a version check for extensions.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15478]
See: [This comment thread](https://woocommerce.wordpress.com/2017/05/31/june-6th-dev-chat-5/#comment-3330).

We need to implement a good solution for managing extension version requirements. A lot of stuff broke on sites when people upgraded WooCommerce to 3.0 without having WooCommerce 3.0-compatible extensions.

One proposed solution is to have a "Tested up to" item in the extension docblock. Plugins that don't have the correct WooCommerce version in their "Tested up to" will get a warning, potentially get deactivated, etc.

More planning is needed to determine the correct behavior for extensions that haven't been tested up to the minimum WooCommerce version.

====================================
**Components**
- [x] Plugins screen inline and modal notice.
- [x] Bulk plugins screen modal notice.
- [x] Prevent auto-updating of WC if major release and plugins untested.
- [x] Good-looking modal notice design (@mikejolley)

**Comment by NickGreen** [comment]
> Plugins that don't have the correct WooCommerce version in their "Tested up to" will get a warning, potentially get deactivated, etc.

To expand on this idea: now that WC is using semantic versioning, what if major releases had capability to disable, but point releases would simply produce a warning?

That would prevent the issue of a quick WC bugfix release disabling swaths of extensions, but still prevent major "backwards compatibility" issues.

**Comment by thenbrent** [comment]
Also for posterity, link to initial Slack discussion: https://woocommercecommunity.slack.com/archives/C4TNYTR28/p1496765681939300

**Comment by bekarice** [comment]
> Plugins that don't have the correct WooCommerce version in their "Tested up to" will get a warning, potentially get deactivated, etc.

Rather than deactivating the plugin, the issue here is updating WC core without having updated the plugin first. I'd recommend showing a notice / requiring confirmation before updating WC itself instead.

While this isn't always a hard requirement (upgrading extensions first), it does ensure the smoothest experience for the merchant, as compatibility code is therefore already in place.

Example:

 - I run WC 3.0.8 and Subscriptions 2.2.7
 - WC 3.1.0 comes out, and Subscriptions doesn't have `WC tested up to: 3.1.0` yet in the header (or any number of other plugins) 
 - When I go to update WC, it warns me of this:   <br />
   > Heads up! The following plugin(s) are not listed compatible with WooCommerce 3.1.0 yet. If you upgrade without upgrading these extensions first, you may experience issues:
   > - WooCommerce Subscriptions
   > - Plugin 2, etc <br />
   > [Abort Upgrade] [Upgrade Now] 

Obviously hosting auto-updates of WC core will still pose an issue, so potentially as Nick mentioned, looking at deactivating plugins then could be an option with major updates:

> Heads up! The following plugins are not listed as compatible with WooCommerce 4.0.0, which is **a major update**. These plugins have been deactivated as a precaution; you can re-enable them at your own risk, but please upgrade as soon as possible:
> - Plugin 1
> - Plugin 2

In this sort of case, though, I'd be pretty hesitant to deactivate essential plugins without emails and every flashing light possible sent to site admins as well. Imagine if you sell subscription products and you have no subscriptions now, if you have a payment gateway that wasn't compatible and now you can't take orders, or if you run a membership site, but haven't upgraded Memberships yet, and all content is public when it's deactivated. The best course is prompting for extension updates first.

It sounds like working with hosts that auto-upgrade would probably be a more sane solution so as not to upgrade to a major version automatically, letting users see the "these plugins need an update" alert instead.

**Comment by franticpsyx** [comment]
Add my vote to what Beka just said.

Deactivating plugins is not something I'd consider ad an option under any circumstances. A notice should be enough to make people think twice.

What I'd look into for the first iteration of this warning system is a way to make it work reliably when bulk-updating.

Another point already brought up is the need to work with hosts to ensure that this "warning system" will prevent auto-updates. Better yet, I would also try to educate them on the need to update WC extensions (WC tested up to) before WC core.

**Comment by douglsmith** [comment]
According to the [Creating a Plugin](https://docs.woocommerce.com/document/create-a-plugin/#section-8) page, extensions are already supposed to have a `WC requires at least` and `WC tested up to` headers  in the readme.txt file along with the standard WordPress headers.

I attempted to reference these in preparation for upgrading to WC 3 but there were too many extensions without them for it to be useful. So part of what is needed here is as much policy and education as code. A good first step would be requiring all extensions sold through WooCommerce.com to have them.

**Comment by ben72** [comment]
Bare in mind many updates are carried out using remote systems like iThemes Sync, ManageWP etc. Warning messages will not work in those cases.

So warning messages can be a good complement but education seems to be the simplest and most reliable way to go.

**Comment by NTShop** [comment]
I agree with @ben72 - education is realiable. Loads of developers won't know to add any particular plugin header tags, so in those cases version checking won't help. What might help is somehow warning site operators that an update might break their site if they proceed. So in other words, add glaringly obvious descriptive info the WC "update available" notice that can be read before they click to update, and maybe hooking into the update process to intercept the update process before proceeding to confirm that they're sure they've check compatibility and really want to proceed. Some JS could help with the latter, there are unique class names in the list of plugins on the plugins page that can be used, same for the Dashboard -> Updates page (except hooking into it with JS would be different since it's a form).

**Comment by claudiulodro** [comment]
[Screenshots of initial beta version functionality.](https://github.com/woocommerce/woocommerce/pull/16086#issuecomment-315224673) Please leave feedback. :)

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Version checking before updates](https://trello.com/c/fRAT3OtP/101-version-checking-before-updates)

**Comment by webdados** [comment]
Just a heads up that the documentation says the headers should be on the readme file, but actually they should be on the plugin main file.
https://docs.woocommerce.com/document/create-a-plugin/#section-8 

I was updating a couple of plugins of mine and couldn't make the "Not tested with the active version of WooCommerce" message go away because I was adding the headers to readme.txt instead on the plugin main file.

**Comment by claudiosanches** [comment]
@claudiulodro I just updated it, but feel free to improve.

**Comment by claudiulodro** [comment]
Looks good. Thanks @claudiosanches!

**Comment by KoolPal** [comment]
@claudiulodro Has something changed in this?

In my custom plugin I have entered:
```
* WC requires at least: 3.0.0
* WC tested up to: 3.5.4
```
Yet I see the dreaded Not tested with the active version of WooCommerce

I was checking the code for [WooSidebars](https://wordpress.org/plugins/woosidebars/) and I do not see any reference to 
```
* WC requires at least: x.x.x
* WC tested up to: 3.x.x
```
Please see below
```
/**
 * Plugin Name: WooSidebars
 * Plugin URI: http://woocommerce.com/woosidebars/
 * Description: Replace widget areas in your theme for specific pages, archives and other sections of WordPress.
 * Author: WooCommerce
 * Author URI: http://woocommerce.com/
 * Version: 1.4.5
 * Stable tag: 1.4.5
 * Requires at least: 4.1
 * Tested up to: 4.9.6
 * License: GPL v3 or later - http://www.gnu.org/licenses/gpl-3.0.html
 * Text Domain: woosidebars
 * Domain Path: /lang
 */
```
