### ISSUE TITLE
Can add unavailable variation to cart using add-to-cart URL

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#15481]
### EXPLANATION OF THE ISSUE

If you have a product using Global Attributes but are using only some of those attributes, you can still add the variation to the cart using the URL (or Order Again? button if it was previously available).

### STEPS TO REPRODUCE THE ISSUE

This is a simple example, here you could avoid the issue by doing size specific variations, but this isn't practical with large numbers of variations and combinations.

1) Create a variable product using a Global Attribute for variations. Here I've just selected S and M even though the Global has L and XL available.

![Screenshot](http://joelwills.com/flpbF3+)

Link to image: http://joelwills.com/flpbF3

2) Added those as variations by selecting `Any Size..` for the variation 

![Screenshot](http://joelwills.com/hminvw+)

Link to image: http://joelwills.com/hminvw

All is correct on product:

![Screenshot](http://joelwills.com/D2Igq+)

Link to image: http://joelwills.com/D2Igq

3) Use the URL to add a different variation to the cart, in my case a L size:

https://XXX/?add-to-cart=4833&variation_id=4837&attribute_pa_size=l

4) Large size is added to the cart even though it's not an available attribute:

![Screenshot](http://joelwills.com/ia0Rks+)

Link to image: http://joelwills.com/ia0Rks

It also shows up differently for some reason.

The `Any size...` option isn't selecting from the available terms in the product attribute, but from the global attribute terms.

Tested on 3.0.7, on two sites. 

As mentioned this can be avoided in this situation by specifying S and M variations individually and not using `Any Size...` (you then getting an error that that size isn't available when trying to use the URL), however that shouldn't be necessary when variations have the same cost etc and also very impractical when multiple attributes are used in complex setups.

586109-zd-woothemes

**Comment by liveaspankaj** [comment]
Hi @mikejolley 

This change caused an issue with my code. Let me know if you have a solution that doesn't require core code change. 

Requirement: 
I am selling license renewals and want user to select their license as part of variation attribute. 
All the licenses cannot be added to the attributes in product. 

Existing Solution:
So I am adding the user specific attributes via code in template single-product/add-to-cart/variable.php

Problem:
If I make the attributes in product as blank. (i.e 'any' variation). It doesn't show the dropdown for selection. Even if I change the options array in variable.php 
If I add one value in attributes in the product. I am able to change the dropdown values in variable.php template. But get Invalid value error due to the change in above commit. 

Solution: 
A way to override/filter the validation. Or, the attribute values should help me fix the issue without core code changes in WooCommerce. I could not find any hooks in these functions. 

Let me know if I am missing anything.

**Comment by mikejolley** [comment]
You can still add the attributes to the parent product so it validates.

**Comment by liveaspankaj** [comment]
@mikejolley There is no parent product, or any option to create a parent product. 

I am using a "Variable Product" and when I copied my site on sandbox to experiment. I found that blank value in attribute removes the attribute completely. So, the 'any' variation mentioned in code comment is gone?

**Comment by mikejolley** [comment]
By parent I mean the variable product.

The variations can still use 'any'. Any means any of the variable product's assigned attributes.

**Comment by liveaspankaj** [comment]
@mikejolley, thanks for your responses. it did not work. I am leaving it to manual code change to remove the check. spent more time on it than expected. 

but, woocommerce is starting to be more sensitive on updates recently. last time I updated, the attributes were deleted, and I had to create them again. 

this time its this invalid values thing. hope to have less issues in future and a hook to fix this issue so that I don't need to modify code.
