### ISSUE TITLE
Consistent customer download display

### ISSUE THREAD

**Issue by accetturo** [woocommerce/woocommerce#15563]
### EXPLANATION OF THE ISSUE

When a user purchases a downloadable file, it shows them the following

PRODUCT NAME x QUANITY
- DOWNLOAD 1 : DOWNLOAD NAME
and so on

Instead of people clicking the DOWNLOAD 1, about 20% of them click the product name. This kicks them back to the product page and most of them don't understand they have a members center for downloads. This causes us about 300 tickets a day, and is non-sense. What is the purpose of having a link back to the product page after purchase. This is just asking for trouble UX/UI wise, please resolve this.

**Comment by mikejolley** [comment]
@jameskoster thoughts?

**Comment by jameskoster** [comment]
> What is the purpose of having a link back to the product page after purchase

They might want to write a review, or double check the description or something. Having a link back to the product page is definitely valid.

I do however agree that the download link should be the clearest CTA.

How about we make the download link a `button alt` and change the column heading from 'File' to 'Download'?

![download](https://cldup.com/RHHSUWNdgZ-2000x2000.png)

**Comment by accetturo** [comment]
I do agree that some people may want to reference, I think the layout @jameskoster included would be much more user-friendly. People also seem to do this in the confirmation email, and it's really a mess for our support team atm. We have people replying to the email confirmations asking where their download links are to the email with the download links because they just don't understand again. To me its clear, but to many it seems to not be. Really this problem affects 3 areas, the  Thank you page, members center downloads page and confirmation email tables.

**Comment by mikejolley** [comment]
@jameskoster There are also the regular emails and order view display which need some adjustment. I'm going to mark this needing design for 3.2

**Comment by jameskoster** [comment]
I thought about this and think it makes most sense to use the same table in all locations for consistency. 

If an order contains downloadable products it's reasonable to assume that the customer will want to download them/it immediately. So having a dedicated 'Order downloads' section on the order confirmation/view screen makes sense.

As for positioning, on order confirmation I'd put it before the order details section. Having just completed checkout folks will be more keen to download their purchase rather than re-reading the order information.

On the order view screen it doesn't need as high priority because we have the dedicated Downloads page. I'd like to think that this is where folks will most likely go to download their stuff. We can probably put it beneath order details here.

Emails can be the same as the order view screen. Just leave out the 'downloads remaining' column.
