### ISSUE TITLE
WC API basic auth not working with HTTPS

### ISSUE THREAD

**Issue by cgeitz** [woocommerce/woocommerce#15581]
### EXPLANATION OF THE ISSUE

I'm using WC rest API V1 and using Basic auth in an ajax filtering tool in my shop. For some reason the get requests are returning a 403 error over HTTPS but over HTTP the correct response is given. 

### STEPS TO REPRODUCE THE ISSUE

If I insert both of these links into postman, Http is giving the correct response while HTTPS is returning a 403 error

https://mysite.com/wp-json/wc/v1/products?consumer_key=my_key&consumer_secret=my_secret

http://mysite.com/wp-json/wc/v1/products?consumer_key=my_key&consumer_secret=my_secret

**Comment by mikejolley** [comment]
Testing this;

- http gave 401 error (since basic auth is not supported)
- https worked

Seems like a mistake or server issue tbh. I suggest checking plugins are not affecting this, check you can access to WordPress REST API, and run though https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API You can also use real auth headers rather than query string.

cc @claudiosanches

**Comment by claudiosanches** [comment]
Basic Auth only works under HTTPS.
