### ISSUE TITLE
[3.1] Manage shipping methods

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15605]
The default zone now has a "Manage shipping methods" option, but the custom zones do not. I'm first inclined to click "Edit" on my custom zones when I actually want to edit shipping methods not the actual zone settings.

Couple of suggestions:

1) Change "Edit" to "Edit Zone" for clarification on what is being edited.
2) Do number 1 as well as add a "Manage shipping methods" option.
3) Utilize this white space to have a "Manage shipping method" button or text: http://cld.wthms.co/eiIu7. (as well as implement number 1)

![](http://cld.wthms.co/f0LDh7+)

**Comment by dixitadusara** [comment]
@WPprodigy 

Let me try and I will get back to you.

Thanks,

**Comment by WPprodigy** [comment]
May be worth waiting to see what the core devs think about the change first. Getting feedback from them before making any changes would be best.

**Comment by dixitadusara** [comment]
@WPprodigy 

Thanks for the reply. I have done PR #15607 for the same.

Thanks,
Dixita Dusara

**Comment by mikejolley** [comment]
Both `edit` and `Manage shipping methods` go to the exact same place. The difference is you cannot edit title/locations of the global zone, so this was changed to clarify that. Adding 2 links is utterly pointless, and since there is only one `edit` link per zone row, having more clarification should be unnecessary. If concerned, or it causes confusion after launch please talk to Jay :)
