### ISSUE TITLE
Webhook only containing webhook_id as payload

### ISSUE THREAD

**Issue by alexislg2** [woocommerce/woocommerce#15642]
### EXPLANATION OF THE ISSUE

Webhook is fired but payload only contains `webhook_id=<XXX>` as body.

And moreover this firing doen't appear in the webhook logs

It seems to be related to https://stackoverflow.com/questions/41878254/woocommerce-order-created-webhook-firing-only-sometimes-and-with-incomplete-payl

### STEPS TO REPRODUCE THE ISSUE

1. Create a requestbin ( requestb.in ) to test
1. create a new webhook concerning orders update and add the requestbin as endpoint
2. create a new order, then update it in order to fire the webhook
3. Have a look at the requestb.in : Only `webhook_id=<XXX>`

I am using cloudfare. Could it be linked? How can I debug this?

### SYSTEM STATUS

<details>
Woocommerce 3.0.8 with WP 3.8
</details>

**Comment by mikejolley** [comment]
This is a test ping WC uses to confirm the endpoint can be reached. It will be triggered everytime you save/update a webhook.

**Comment by alexislg2** [comment]
@mikejolley OK so then my question is: why this ping happens when I update an order?

I am not updating a webhook, I'm updating an order here.

**Comment by mikejolley** [comment]
I wasn't able to replicate that. Only 1 webhook was triggered on update which had the full payload.

**Comment by alexislg2** [comment]
OK I know it works for many people. But we are at least 2 (according to the SO post) having this issue. My clue is that this is because I'm using cloudfare. Could be linked?

Please reopen this issue. I clearly don't have the expected behaviour here

**Comment by mikejolley** [comment]
> My clue is that this is because I'm using cloudfare. Could be linked?

You tell me? If you can replicate the issue surely you can disable it temporarily?

**Comment by mikejolley** [comment]
> And moreover this firing doen't appear in the webhook logs

Pings don't appear in the logs.

They are triggered on webhook save event (confirmed). Checking if anything else can trigger save.

**Comment by mikejolley** [comment]
Try that PR ^ It should protect against multiple pings if triggered more than once for any reason. I wasn't able to replicate the issue itself.

**Comment by Andriy-Kulak** [comment]
@mikejolley does the webhook (for Order Create) get triggered when an order is created via the Woocommerce API?

I want to test the webhook by creating fake order with the Woocommerce API. All I am getting is the webhook_id when I update the webhook but nothing else when the actual test orders are created. I don't see anything in webhook logs either.

The way I am testing the webhook is by pointing it to an endpoint that saves everything that is in the body of a POST request to a mongoDB. If there are better ways to test, please let me know!

Thanks!

**Comment by mikejolley** [comment]
Yes, API uses the same system/hooks.

**Comment by alexislg2** [comment]
Sorry I thought that the order update was triggering the Ping. Only the webhook update triggers a ping on my system.

So Here is the behaviour on my system:

* I receive a payload looking like `webhook_id=<XXX>` (aka ping) when I update the webhook. (Expected behaviour)
* I set a webhook triggered by order.update but I don't receive anything when an order is updated (unexpected behavour)

**Comment by alexislg2** [comment]
@Andriy-Kulak I think you have the same behaviour than me.

you can use requestb.in as an endpoint for testing. It is much easier...

**Comment by mikejolley** [comment]
Thats been patched then.

**Comment by alexislg2** [comment]
@mikejolley Which patch?

BTW After some debugging I discovered that this is linked with a Cron issue. Reaching www.example.com/wp-cron.php?doing_wp_cron delivers all the webhook I was waiting for

**Comment by mikejolley** [comment]
See the merged PR ^

**Comment by kdekok** [comment]
This issue is still not resolved.

After an order is updated, the order.updated webhook is fired with a `application/json` content type(Expected behaviour)

Immediately after that, another call is made to the delivery url with content type `application/x-www-form-urlencoded` and a body containing just `webhook_id=x`. (**Unexpected behaviour!**)

This is unnecessary trafic and throwing 415.
Please fix it.

**Comment by stephangroen** [comment]
Same issue as @kdekok here. Every time a webhook is delivered to an endpoint, a new requests follows with `webhook_id=x`  as the body. I see this behavior over a dozen installs I have checked. Including the latest releases:

WooCommerce 4.7.0
Wordpress 5.5.3 

Also the second call (the ping) doesn't contain the X-WooCommerce-*** headers which is why I discovered this issue. I got a lot of logs reporting the webhook signature could not be validated.

**Comment by GRSM78** [comment]
Please check if you have any caching plugin installed - in my case Breeze was causing the issue. I'm still looking for a way to fix this so will keep you posted

**Comment by Robbertdk** [comment]
I also had same issue as @kdekok and @stephangroen. 

In my case the problem was that the response of the test ping was 401, which resulted that the pending_delivery status of the webhook was always true.

For the connection with the ERP system of my client, I added a custom authorization header.
I set that header via `woocommerce_webhook_http_args` filter. That filter adds the authorization header to all the webhook deliveries, except the ping request.

Therefore the ping request resulted in a 401 response and  `pending_delivery` status of the webhook was set to true.  Each time the webhook is delivered, WooCommerce sends another ping if the `pending_delivery` status of the webhook is true. That  caused the double calls.

By setting `pending_delivery` status to true in the database, the problem was resolved.
You can change that value by going to the database table `wp_wc_webhooks`. There you'll find all the webhooks you've created. Set the value in the column `pending_delivery` to `0` for your webhook to mark your ping signal as delivered and to prevent the double calls.

**Comment by MrLightful** [comment]
I'm a bit late to the party, but can someone tell me how the system expects me to handle these test pings? Right now I just return 401 as the signature isn't valid, but does WooCommerce punishes us for it (e.g. the 5 failed webhooks => disabled)? Can we safely ignore this and keep returning 401? Or I have to force 2xx for such webhooks, even if I don't have any way to validate its origin?

Upd: seems we do get disabled for this. I must force 2xx. Damn, really bad design choice to have these pings this way, imho. No way to validate it.
