### ISSUE TITLE
"Exclude sale items" coupon restriction doesn't work

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce#15669]
According to the "Exclude sale items" option's description:

> Per-cart coupons will only work if there are no sale items in the cart.

However, using a **Fixed cart discount** type coupon with the "Exclude sale items" enabled, the coupon gets applied to the cart successfully.

Coupon: https://cloudup.com/cdaaJbugh4p / https://cloudup.com/igdKIIZRZTQ
Product: https://cloudup.com/cJFpGHW4xO4
Cart: https://cloudup.com/cO3bwJ2Gu5l

Tickets:
* 588958-zd-woothemes

**Comment by mikejolley** [comment]
Updated the text only https://github.com/woocommerce/woocommerce/pull/15680

Logic is fine. The user is wrong that this is 'costing them money'. Their customer's could get the same amount of discount by placing 2 separate orders (1 with the sale item, 1 without the sale item) which is why the old exclusion logic does not make sense.

As long as there is a non-on-sale item, the coupon can apply, and the discount (fixed amount) can be applied.
