### ISSUE TITLE
Feature Request - Pull Refunds by Creation Date

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#15691]
Hi,

Can you add an endpoint to pull refunds by creation date?

GET /wp-json/wc/v2/refunds?after=6/19/2017&after=6/20/2017

My current code must pull a list of orders by modified date, based on a certain status, and find refunds. Orders can have any status, so I must send a request for each status and date modified.

**Comment by claudiosanches** [comment]
This is already possible and is part of our documentation:
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-refunds

only not possible with the current date format you are using, requires a ISO8601 compliant date.

**Comment by jmawebtech** [comment]
Hi,

It is possible, if you have an order ID? What if I don't have an order ID?

**Comment by claudiosanches** [comment]
Just read the docs, no need for order IDs...

**Comment by pjv** [comment]
Hi @claudiosanches, I hope you are right and I am missing something, but I just read the docs [here](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-refunds) carefully and there does not seem to be an endpoint to access refunds without having an order ID. The only endpoint related to refunds in that documentation looks like this:

`/wp-json/wc/v2/orders/<id>/refunds`

... which does require an order ID.

This makes a particular kind of reporting impossible via the REST API because you cannot find some refunds during a reporting period if the order which was refunded was created in an earlier reporting period.

**Comment by jmawebtech** [comment]
Hi,

Can you add code to pull refunds and orders by the modified date field? I work with C# and I cannot add this filter to WooCommerce. Since our tool cannot pull orders by the date modified, our tool cannot filter orders by status or pull refunds automatically. Orders are not created as completed or refunded.
