### ISSUE TITLE
Clear all filters for class-wc-widget-price-filter.php

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#15714]
Hi! 

It looks like `includes/widgets/class-wc-widget-layered-nav-filters.php` has "Remove Filter" in `output()` but `includes/widgets/class-wc-widget-price-filter.php` doesn't .. is that intentional? If not, is this something we can add to price filter? 

Thanks!

**Comment by mikejolley** [comment]
There is no dedicated "Remove Filter" link for the widget as a whole. The options are just toggle-able.

The price slider on the other hand has different UI so it's not ideal.

The 'active filters' widget can remove any of the above - this should be used.

When price filter is changed from a slider to a list (I expect this due to performance in the future), it will match.
