### ISSUE TITLE
Variation attributes are displaying below product title if dash is in value

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce#15763]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create product with a dash in the attribute value (such as "one-time")
2. Add item to cart, view in cart product table
3. Purchasing also shows it in the email template

## Expected behavior and actual behavior

When I follow those steps, I see the attribute title and value displayed below the product title when a dash is used:

![](https://cldup.com/vO58QNtgtM.png)

With WooCommerce v3.0 and above the variations should not display under the product title and instead the first two chosen variations display in the product title, unless they are not found in the title.

If you use a dash in the attribute value, the dash is stripped, making it think it is different, when in fact, it's not.

## Related discussion

https://github.com/Prospress/woocommerce-subscriptions/issues/2205

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
I guess it was to prevent hard to read/confusing stuff like this: http://cld.wthms.co/l9co1e. I wonder if there's a better character we could use for spacing out the attributed, leaving dashes alone since they are pretty common.

Reading up on grammar, maybe em-dash? https://english.stackexchange.com/questions/2116/when-should-i-use-an-em-dash-an-en-dash-and-a-hyphen. Not a perfect fit, but closes than hyphen. Would look like this: http://cld.wthms.co/oXHEFb

Secondly, I don't quite understand this purpose: https://github.com/woocommerce/woocommerce/blob/5ebc4a40104b2f93c7329cda3b4fb0c75aa54444/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L231. And even the condition above it? The attribute name is never listed in the title so, why does that matter at all?

___

For part of the fix, just need to remove this: https://github.com/woocommerce/woocommerce/blob/aab401c8f8eb67d586214129ed00edbcb6842d69/includes/wc-product-functions.php#L379-L381. Unsure about switching out characters though, so not going to submit a PR until a decision is made :)

**Comment by dixitadusara** [comment]
I have to pull request for #15778 Variation attributes are displaying below product title if dash is in value. In this issue, I have removed https://github.com/woocommerce/woocommerce/blob/aab401c8f8eb67d586214129ed00edbcb6842d69/includes/wc-product-functions.php#L379-L381 line as per your suggestion.

**Comment by claudiulodro** [comment]
> Secondly, I don't quite understand this purpose: https://github.com/woocommerce/woocommerce/blob/5ebc4a40104b2f93c7329cda3b4fb0c75aa54444/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L231. And even the condition above it? The attribute name is never listed in the title so, why does that matter at all?

@WPprodigy That check is supposed to prevent things like "Room - Blue, Red", which is confusing to users and was fiercely debated before 3.0. 

The logic for solving the problem that made the most sense was that in all situations where that sort of confusing variation name would be generated, the attribute name would be multiple words long (e.g. "Wall color" and "Ceiling color").

`$name` is the attribute slug, so if the slug has a '-' in it ("wall-color") the attribute name is multiple words and we don't want to potentially generate a confusing variation name. 

It's hard to make good rules for this kind of stuff! :P

**Comment by WPprodigy** [comment]
@claudiulodro I see, thanks for the explanation :)

So for this issue, what do you think about using the em-dash instead? Makes more grammatical sense imo. Of course we'd run into the same problem if a store uses the em-dash in an attribute value, so still requires a change there.
