### ISSUE TITLE
Paypal logos are missing due of hotlinking

### ISSUE THREAD

**Issue by uxschw** [woocommerce/woocommerce#15845]
Hi, I sent a request to Woocommerce and they asked me to post it here, hope this is the right place.

This is happening to me and other people that I know. The paypal logos images in the checkout page are missing 90% of the time ( https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg )
Here is what happens:  https://i.gyazo.com/818a4926cb1a6f3479dd694b643eadfe.png

I would like to suggest a feature to be implemented; give the option to locate this kind of image in our own host/server.. hotlinking images is always a bad idea.

Also I would like to suggest this image instead:  http://i.imgur.com/J2E41cu.png  seems more suitable and better looking.

Thanks.

**Comment by mikejolley** [comment]
From what I remember, PayPal recommend using their images because they change based on country. Hosting the images would mean we need to gather many different images, for different countries, and maintain them. So it's something I'd like to avoid if possible.

That said PayPal should keep these images up - it looks like in your case the links where down.

I will close this issue because right now there is no action that should be taken, but I will email PayPal and see what they recommend going forward and to see if there is an alternative. I'll reopen this if they agree on self-hosting.

For now, you can hardcode the image to one on your server using the `woocommerce_paypal_icon` filter. e.g.

```
add_filter( 'woocommerce_paypal_icon', 'custom_woocommerce_paypal_icon' );

function custom_woocommerce_paypal_icon() {
  return 'https://image-url-here.jpg';
}
```

Thanks for bringing to our attention.

**Comment by mikejolley** [comment]
What was the store URL @uxschw ?

**Comment by uxschw** [comment]
@mikejolley its uxstore.com
