### ISSUE TITLE
[Community][Dev]Adding Croatian States into WooCommerce Core (Plugin Created)

### ISSUE THREAD

**Issue by markoidzan** [woocommerce/woocommerce#15859]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] This is not an issue, it is a suggested enhancement

## Steps to reproduce the issue

None

## Expected behavior and actual behavior

See All 21 Croatian States in all Serchable options. Works even with State option. Currently it is used within few of web shop projects which I build.

## Environment

WooCommerce 3.0+ Compatible

## Details

Plugin Source Code ( https://github.com/markoidzan/woocommerce-hr-states )
If needed can fix code to be more compatible with woocommerce core.

## Isolating the problem

- [x] Enhacement and WooCommerce Core Upgrade Idea

**Comment by mikejolley** [comment]
Please raise a pull request if you'd like to contribute.

Ensure the ISO codes are valid and do not contain special chars. Maybe look at https://en.wikipedia.org/wiki/ISO_3166-2:HR

Also ensure/show examples of Croatian stores using state dropdowns instead of inputs. Not all countries need a dropdown of states.

Thanks!
