### ISSUE TITLE
Merge product shortcodes into one

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15979]
Just logging. Details will be fleshed out in time. cc @WPprodigy @jameskoster 

https://github.com/WordPress/gutenberg/blob/master/blocks/README.md
https://github.com/WPprodigy/woocommerce-external-product-embed/blob/master/classes/class-wcepe-shortcodes.php#L113

**Comment by WPprodigy** [comment]
## Gutenberg integration.

I started playing around with Gutenberg some, and having a working prototype you can see here: http://cld.wthms.co/MGBhxB

Here is what we have to work with:

1) The block itself is fully customizable. We can show/do whatever we want inside the block in the editor, and something completely different can show up on the front-end.

2) You can add custom toolbar options to your block. Example: http://cld.wthms.co/X0PKWX.

3) You can add settings to the sidebar (inspector controls) area: http://cld.wthms.co/hw4mJw

Since we are starting with the product listing shortcode, here are some possible design options for that using the above 3 things.

____

### Design Options

**Option 1**: Show the products themselves inside the block based on the settings configured on the right. While likely the most complicated option, this perhaps fits the “flow” of other components as you see what you get in the block, and configure extra options on the right.

**Option 1.5**: Same a option 1 (configuration on the sidebar), except instead of showing all of the live products, there will just be some placeholder text/design in the block. Alternatively, there could be some example products instead, which would fit a similar design to what option 1 would look like.

**Option 1.9:** A mix of the above two options, but also utilizing the toolbar for some of the settings as well as inspector controls. (column count for example, as it affects display over functionality)

**Option 2**: Create a fancy UI where users configure their settings within the block. This gives the most flexibility for the UX, and puts the options front and center (which is arguably the main part of a products listing shortcode/widget)

______

## What's Next?

After we have the product listings shortcode ready to go, it should be pretty easy to start adding support for the rest of the shortcodes and then move onto widgets.

It's also important to look at what else we will be doing in the future before deciding on a design option for the product listings shortcode.

I think the page shortcodes could be phase 2, having a block that's added to our cart, checkout, and account pages instead of the user needing the shortcode (no more `<pre>` problems!).

After that, we can cover the various remaining shortcodes. `woocommerce_order_tracking`, `related_products` for product page, and the `add_to_cart` buttons.

Then shortcodes will be wrapped up, leaving way for widgets. Widgets being last seems fitting, as we can wait to see how the WP landscape evolves in this area.

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Products shortcode and block for Gutenberg](https://trello.com/c/f2x5VAK0/104-products-shortcode-and-block-for-gutenberg)

**Comment by GlennMartin1** [comment]
@WPprodigy, regarding your "Design Options," check out https://github.com/WordPress/gutenberg/blob/master/docs/design.md#block-design-checklist-dos-and-donts-and-examples. One point listed there states: 

> Your block when unselected should preview its contents.

My reading of these guidelines seems to point to what you described as "Option 1."

**Comment by GlennMartin1** [comment]
@mikejolley Got a valid link on that last comment?

**Comment by claudiosanches** [comment]
Changes are coming for Gutenberg and there is no need to use just one shortcode on it.
Of course is easy and will save us some code using only `products` to display On Sale, Top Rated, Best Selling and Featured products too, but better hold it until we have more news about Gutenberg changes.
I'm removing the 3.2.0 milestone for now.

cc @mikejolley

**Comment by claudiosanches** [comment]
Well, not good to plan anything for Gutenberg for now, but we can still work on the shortcode.

It's possible extend `[products]` to have the same behavior as `[product]`, `[featured_products]`, `[sale_products]`, `[best_selling_products]`, `[recent_products]`, and `[top_rated_products]`.

Things to do:

- [ ] Create unit tests, make sure that no shortcode will change it's default behavior (required some code changes to make the current code testable).
- [ ] Extend `[products]` shortcode allowing to be used instead the shortcodes listed above.
- [ ] Allow `limit` attribute to replace `per_page`.
- [ ] Introduce `visibility` attribute to display hidden products, default to `catalog`.

cc @mikejolley
