### ISSUE TITLE
New Extensions admin menu not limited to users who can install plugins

### ISSUE THREAD

**Issue by JakePT** [woocommerce/woocommerce#15987]
3.1.0 introduced the Extensions page as a replacement for the Helper plugin for connecting to woocommerce.com for licensing extensions.

The issue with this is that the menu item is added for users with just the `manage_woocommerce` capability, which means that granting a user the capability to manage the shop's settings also grants them visibility on all the extensions available to them and download links, even if that user is not the owner of the connected account.

This can be undesirable in situations where a developer/agency manages themes, plugins, and extensions for a client, while giving the client reduced access focused on managing content. In these cases the developer might want to give access to WooCommerce settings so that they can manage emails, shipping etc. but not the ability to install plugins, themes and extensions.

While the Extensions page doesn't seem to allow directly installing extensions, it seems to me that there is a disconnect between allowing a user that lacks the ability to install plugins to browse and download them.

My opinion is that the Extensions page should be limited either to users with the `install_plugins` capability, or a new capability should be introduced for it.

**Comment by JakePT** [comment]
Yeah sorry, you're right. The Extensions item isn't new. The new thing that my issue is mostly about is the WooCommerce.com Subscriptions tab on that screen. The functionality that's in that tab _is_ new though, as far as that menu item is concerned, since the functionality previously existed in the Helper plugin which only added the menu item under Dashboard for users with `manage_options`.

**Comment by DavidAnderson684** [comment]
It seems reasonable to me that manage_woocommerce allows you to browse or even download extensions. Information is just information. The shop isn't protected against anything by keeping extension installation or source code information a secret. In a default setup, you can get all that information by other means anyway. (Browse the front-end HTML source, search for available JS and CSS, readme.txts, etc. - or for source, buy your own, or search Github, etc).

**Comment by mikejolley** [comment]
@JakePT @DavidAnderson684 I tend to agree with David. This is simply exposing public data. If we ever **did** add something which would install a plugin, this would certainly need to check the role. In fact we do that in some places now for things which use our background installer such as https://github.com/woocommerce/woocommerce/blob/66259ebff1d9e8f7c4c73a8f787f0f99abf4f046/includes/admin/class-wc-admin-addons.php#L321

> While the Extensions page doesn't seem to allow directly installing extensions, it seems to me that there is a disconnect between allowing a user that lacks the ability to install plugins to browse and download them.

I guess you could argue that even if you don't have permission to install things, it isn't bad to know these things are available or exist. You'd just have to get permission first :p 

Since this has not changed in 3.0 I vote we leave as-is and revisit if installing/downloading is ever added to the helper.

Thanks 👍
