### ISSUE TITLE
New registered customers now display username on orders instead of full names

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#16015]
## Steps to reproduce the issue

When a customer registered for a site during checkout the orders used to display the First and Last names on orders like this example below from v3.0.8 of WooCommerce.

![screenshot](http://cld.wthms.co/cXghzE+) 
**Image Link:** http://cld.wthms.co/cXghzE

The user setting **Display name publicly as** was set like this after registration.

![screenshot](http://cld.wthms.co/ExKJxZ+) 
**Image Link:** http://cld.wthms.co/ExKJxZ

Within v3.1.0 the orders are now only displaying the username, however.

![screenshot](http://cld.wthms.co/YeShEN+) 
**Image Link:** http://cld.wthms.co/YeShEN

Inspecting the user settings the **Display name publicly as** is set like this after registration.

![screenshot](http://cld.wthms.co/9XPx0v+) 
**Image Link:** http://cld.wthms.co/9XPx0v

I cross tested this on two separate installs one with v3.0.8 and one with v3.1.0 and received the same results. The only change I could see in v3.1.0 within the changelog was this.

* Tweak - Check for an existing display name before updating a user on checkout. Adds display_name prop to the CRUD.

I also tested the latest master branch and got the same results along with also testing WordPress v4.8 and v4.7 on both installs too.

![screenshot](http://cld.wthms.co/BO2pJM+) 
**Image Link:** http://cld.wthms.co/BO2pJM

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by nishitlangaliya** [comment]
Fixes-16015

Some adjustment added to set display name when  new user registered from checkout page  and done pr https://github.com/woocommerce/woocommerce/pull/16024

Thanks

**Comment by nishitlangaliya** [comment]
Hi Team,

Please ignore previous PR which is #16024,

I have re arranged code and done latest PR - https://github.com/woocommerce/woocommerce/pull/16025

Please check for the same and let me know if change required.

Thanks

**Comment by mikejolley** [comment]
@stuartduff You can find that PR here https://github.com/woocommerce/woocommerce/pull/15239

Essentially, we stopped doing this because it updated the display name of anyone who checked out, and since display name is used on the site e.g. comment forms, this could be undesirable. I think the  person who reported this ran an adult site :) 

See https://github.com/woocommerce/woocommerce/issues/15020

**Comment by nishitlangaliya** [comment]
@mikejolley ,

Understood your concern thanks for look into this :)

Thanks

**Comment by crabilld** [comment]
For someone wanting to use the full name for the display name instead of the username, here's some code:

    function change_user_display_name( $name ) {
    	if ( isset( $_POST['display_name'] ) ) { // User has direct control of the display name
    		return $name;
    	}
    	$current_user = wp_get_current_user();
    	$current_name_set = ( $current_user->user_firstname || $current_user->user_lastname ? true : false ); // Determine if a main name is set for current user
    	$name_types = array( 'first', 'last' );
    	foreach ( $name_types as $name_type ) {
    		if ( isset( $_POST['account_' . $name_type . '_name'] ) ) { // Name set on WC Account Details page
    			if ( $current_user->display_name && $current_name_set // Display name and main name are set
    				 && $current_user->display_name != trim( $current_user->user_firstname . ' ' . $current_user->user_lastname ) ) {
    				return $name; // Use the pre-existing display name, because it deviates from "first last" format
    			} else { //  Set the name from fields
    				${$name_type.'_name'} = sanitize_text_field( $_POST['account_' . $name_type . '_name'] );
    			}
    		} elseif ( isset( $_POST['billing_' . $name_type . '_name'] ) ) { // Name set on WC Addresses page or during checkout
    			if ( $current_user->display_name && $current_name_set ) { // Display name and main name are set
    				return $name; // Use the pre-existing display name
    			} elseif ( $current_name_set ) { // Needs display name set
    				${$name_type.'_name'} = sanitize_text_field( $current_user->{'user_'.$name_type.'name'} ); // Set name from the main name field
    			} else {
    				${$name_type.'_name'} = sanitize_text_field( $_POST['billing_' . $name_type . '_name'] ); // Set name from the billing field
    			}
    		}
    	}
    	if ( $first_name || $last_name ) {
    		$name = trim( $first_name . ' ' . $last_name );
    	}
    	return $name;
    }
    add_filter( 'pre_user_display_name', 'change_user_display_name' );
    
    function change_woocommerce_checkout_update_customer( $customer, $data ) {
    	$current_user = wp_get_current_user();
    	if ( $current_user->user_firstname || $current_user->user_lastname ) { // First and/or last name is already set for user
    		$customer->set_first_name( $current_user->user_firstname );
    		$customer->set_last_name( $current_user->user_lastname );
    	}
    	return $customer;
    };
    add_action( 'woocommerce_checkout_update_customer', 'change_woocommerce_checkout_update_customer', 10, 2 );

This is what the code does:

 - By default, WC will set the user's first/last name as the billing first/last name when they checkout. If the user already has a first/last name set, this prevents the billing fields from replacing them. Sometimes a customer wants their display name to be different from their billing name. For instance, if "My Company" places an order with "John Doe" in the billing fields, then their comments and activity on the site would all change to "John Doe". The above code still allows the billing fields to change the user's name (when a new customer hasn't set their name yet), but thereafter, it keeps these fields separated while still allowing the user's billing fields to be updated.
 - By default, WC will set a new user's display name to be their username, after which their display name cannot be changed by them. The above code sets the display name to be "firstname lastname" when the user edits their name on the Account Details page. If they have not added a name to the Account Details page, then it sets the display name when they add a billing address (from the Addresses page or when placing an order).
 - However, there are times when a customer may not want their display name to be their first and last name. In those cases, they may contact the site owner to get it changed. The above code still allows the site owner to change a user's display name and deviate from the "firstname lastname" norm for a specific user. In those cases, changes by the user to their name fields do not change their display name.

Notes:

 - If a site wants the user's display name to ALWAYS be "firstname lastname", then this code could be much simpler.
 - As referenced above, [a filter was recently added][1] to prevent the billing fields from updating the user's name. However, this also prevents the user's name and/or billing address from ever being updated from the checkout page (even for a new user), so it's not an ideal solution.
 - IMHO, this is the way WC should work by default. This code allows the account page to say "Hello John Doe" instead of "Hello doej1960". Or at least it should be a WC setting.


  [1]: https://github.com/woocommerce/woocommerce/issues/15020#issuecomment-303440595

**Comment by digitalmantis** [comment]
@mikejolley Seems odd to penalize all users to accommodate to an adult website. Why not make them change their code vs. ruin the existing functionality for hundreds of thousands/millions of woocmmerce users with a legitimate business?

**Comment by mikejolley** [comment]
It's hardly a business killing change. Privacy first?

**Comment by crabilld** [comment]
@mikejolley I agree that it's not a business killing change and I understand why you made it, but it would be nice for it to be a setting or filter or something. On my site, members are not publicly listed, so it's not a privacy issue for me, and I prefer addressing my customers by name instead of username, as I would in a real store.

**Comment by KoolPal** [comment]
@mikejolley Chiming in with @crabilld Please make changes like these as options rather than forcing it on everyone.

The Adult site Owner could have used custom code to change the display name on **his** particular site rather than getting Woocommerce to change their core!

When Woocommerce make such changes, please guide users on how to revert back in case they do not wish to use your newly introduced **_feature_**

You cannot foresee how & where Store Owners have used display name.

In my store (under development, luckily) I have :
1. The Display Name to be saved as First Name & Last Name and that is used in addressing the customer in the New Account Email (which is otherwise **not possible**!) 
2. Similarly, I use the display name in the the My Account Dashboard to show the customer that he is logged in.

I will now have to tinker with the code so graciously provided by crabilld but in my view this exercise is a waste of time which could have been better utilised in focusing on other pending aspects of my store.

Side note: What happened to the part where Woocommerce was to be friendly for Store Owners as well? How many **normal** store owners would end up on this thread?

**Comment by mikejolley** [comment]
We prefer to have decisions > options - there are already so many options which can be overwhelming. In the case of privacy (and security) issues, we should default to that where possible unless there is a really good reason. In this case, we are changing WP core behavior, and introducing a potential privacy issue.

**Comment by KoolPal** [comment]
@mikejolley I do not wish to get argumentative / confrontational but your response does not give much confidence to Store Owners like me. 

I am not sure that tinkering with code amount to overwhelming options! 😄

The frustration of Store Owners is evident by the increasing interest towards Shopify due to agonizing frustrations in trying to make Woocommerce work without resorting to code changes for basic things leading to Wo**e**-Commerce (pun intended). There are numerous blog posts around this and I do not wish to waste everyone's time retrieving the links.

In case my reply is not appeasing to you & others in this team, I apologize.

On my part, I will hang around till I reach a point of utter frustration and then move to some other platform. 

All the best!

**Comment by mikejolley** [comment]
Other platforms also make decisions on how things should look and function. The difference with WC is you have access to the code (open source) to make changes. But it's your decision :)

I just want to point out, the automatic display-name setting was not a 'feature' until 3.1.0, and no-one complained before that for the 4 odd years WC existed. 

In fact, I found an opposite thread to this one where people were complaining about it's introduction https://github.com/woocommerce/woocommerce/issues/15020

So damned if we do, damned if we don't :) We'll side with privacy this time round. Thanks.

**Comment by nicomollet** [comment]
I am interested in this too. It seems the majority of users want firstname+lastname as dispay name.
If not it could be an option.

**Comment by NEILBATCHELOR** [comment]
Hi guys, I used this from @crabilld : and received the following results which is very odd:

function change_user_display_name( $name ) {
	if ( isset( $_POST['display_name'] ) ) { // User has direct control of the display name
		return $name;
	}
	$current_user = wp_get_current_user();
	$current_name_set = ( $current_user->user_firstname || $current_user->user_lastname ? true : false ); // Determine if a main name is set for current user
	$name_types = array( 'first', 'last' );
	foreach ( $name_types as $name_type ) {
		if ( isset( $_POST['account_' . $name_type . '_name'] ) ) { // Name set on WC Account Details page
			if ( $current_user->display_name && $current_name_set // Display name and main name are set
				 && $current_user->display_name != trim( $current_user->user_firstname . ' ' . $current_user->user_lastname ) ) {
				return $name; // Use the pre-existing display name, because it deviates from "first last" format
			} else { //  Set the name from fields
				${$name_type.'_name'} = sanitize_text_field( $_POST['account_' . $name_type . '_name'] );
			}
		} elseif ( isset( $_POST['billing_' . $name_type . '_name'] ) ) { // Name set on WC Addresses page or during checkout
			if ( $current_user->display_name && $current_name_set ) { // Display name and main name are set
				return $name; // Use the pre-existing display name
			} elseif ( $current_name_set ) { // Needs display name set
				${$name_type.'_name'} = sanitize_text_field( $current_user->{'user_'.$name_type.'name'} ); // Set name from the main name field
			} else {
				${$name_type.'_name'} = sanitize_text_field( $_POST['billing_' . $name_type . '_name'] ); // Set name from the billing field
			}
		}
	}
	if ( $first_name || $last_name ) {
		$name = trim( $first_name . ' ' . $last_name );
	}
	return $name;
}
add_filter( 'pre_user_display_name', 'change_user_display_name' );

function change_woocommerce_checkout_update_customer( $customer, $data ) {
	$current_user = wp_get_current_user();
	if ( $current_user->user_firstname || $current_user->user_lastname ) { // First and/or last name is already set for user
		$customer->set_first_name( $current_user->user_firstname );
		$customer->set_last_name( $current_user->user_lastname );
	}
	return $customer;
};
add_action( 'woocommerce_checkout_update_customer', 'change_woocommerce_checkout_update_customer', 10, 2 );

I have a username of xyz1, a first name of neil1 and a last name of neil2

I was expecting the code to create a display name of neil1 neil2 and then to use this everywhere.

The result I got was username xyz1 still being used on the https://.../myaccount/ page and its used everywhere as the same.

I then updated the first name and last name to neil3 and neil4 and it didn't change the display name, it doesn't force use of the display name - still uses the username everywhere that I can see. All latest versions of everything being used: @crabilld @mikejolley any help/advice would be appreciated thank you.

My goal is to want the user to be able to edit the nickname field in the edit account page
To force wordpress to display the nickname/display name instead of username, everywhere front and back. Make sure that wordpress uses a unique nickname/display name and nicename.
As a first priority use First Name Last Name - Billing Company as the nickname/display where any of those fields exist. All are requested on registration.

Thanks   
Neil

**Comment by RusGamer** [comment]
i need username shortcode to place in placeholder. Please help
its what i have now:
placeholder="<?php esc_attr_e( 'store name', 'dokan-lite' ); ?>"
