### ISSUE TITLE
WooCommerce order created on new user registration is not displayed in wp-admin

### ISSUE THREAD

**Issue by w7089** [woocommerce/woocommerce#16057]
The goal is to create a **new order** when a new customer registers in *Wordpress / WooCommerce* web site. 
To achieve that, the following hook was added to child theme's *functions.php*:

```
    add_action( 'user_register', 'add_order', 10, 1 );
    
        function add_order( $user_id ) {
        
            $order = wc_create_order();
            $order->set_customer_id($user_id);
            $order->save();
        }
```

When a new user registers, it's created in DB , but is not displayed in *wp-admin->woocommerce->orders*. No error is seen in the log.

**Comment by WPprodigy** [comment]
Take a look at this test: https://github.com/woocommerce/woocommerce/blob/bad16b47da1c0be5e3c3f2ca882016d54015746b/tests/framework/helpers/class-wc-helper-order.php#L41 versus this test: https://github.com/woocommerce/woocommerce/blob/bf91127682bd5749da56c2bcc7235865ccb58994/tests/unit-tests/customer/functions.php#L115-L119

If you use `wc_create_order()`, you should pass it args. Otherwise, you should use `new WC_Order`.

**Comment by mikejolley** [comment]
I tested the snippet and it did create a blank order, but I registered on the wp-login.php page. 

For WooCommerce pages such as my account, you may want to target the action `woocommerce_created_customer`.
