### ISSUE TITLE
get_user_metadata filter is not respected

### ISSUE THREAD

**Issue by muhammad-naderi** [woocommerce/woocommerce#16136]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [ X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. add following snippet to functions.php to encrypt and decrypt user_meta_data
```
add_filter('get_user_metadata', 'decrypt_user_meta',10,4);
add_filter('add_user_metadata', 'encrypt_user_meta',10,5);
add_filter('update_user_metadata', 'encrypt_user_meta_in_update',10,5);
```

## Expected behavior and actual behavior

When I follow those steps, I see in the checkout screen my encrypted values are showing in the checkout fields

I was expecting that like previous versions (2.6.4) the values gets decrypted prior to setting to this fields

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://www.dedicated.shygunsys.com
Site URL: http://www.dedicated.shygunsys.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.37.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.38 - ما پیشنهاد می کنیم حداقل نسخه MySQL 5.6 باشد. ببینید: نیازمندی های وردپرس
Max Upload Size: 64 MB
Default Timezone is UTC: ❌ منطقه زمانی پیشفرض Asia/Tehran می باشد - شما می بایست از UTC استفاده کنید
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() با شکست مواجه شد . با ارائه دهنده هاستیگ تماس بگیرید . 403
Remote Get: ❌ wp_remote_get() با شکست مواجه شد . با ارائه دهنده هاستیگ تماس بگیرید . 200

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌فروشگاه شما از HTTPS استفاده نمی کند. اطلاعات بیشتر درباره HTTPS و SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (30) ###

گرویتی فرم: توسط بیست اسکریپت – 1.9.16
Map List Pro (shared on 20Script.ir): توسط 20script – 3.10.1
bbPress Enable TinyMCE Visual Tab: توسط Jared Atchison – 1.0.1
bbPress - Private Replies: توسط Pippin Williamson and Remi Corson – 1.3.3
بی بی پرس: توسط هازمان بی بی پرس – 2.5.12
bbPress Moderation: توسط Ian Stanley – 1.8.3
Bulk Delete: توسط Sudar – 5.5.6
Cloudflare: توسط John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.1

Device Mockups: توسط Sixteenbit – 1.6.1
Knowledge Base for Documents and FAQs: توسط Echo Plugins – 3.0.1
Front-End Only Users: توسط Etoile Web Design – 3.1.6
Gravitate Encryption: توسط Gravitate – 1.0.4
Drop Down List Field for Gravity Forms: توسط Adrian Gordon – 1.7.4
Gravity Forms User Registration Add-On: توسط rocketgenius – 2.3
درگاه شرکت ایران کیش: توسط SOFTIRAN.ORG – 1.0
Official MailerLite Sign Up Forms: توسط MailerGroup – 1.1.25
گرویتی فرم پارسی: توسط حنان ابراهیمی ستوده – 2.1.5
ووکامرس فارسی: توسط ووکامرس فارسی – 3.1.1
Persian World: توسط Danial Hatami – 3.2.3
Social Media Widget: توسط Noah Kagan – 4.0.6
User Activity Log: توسط Solwin Infotech – 1.3
User Role Editor: توسط Vladimir Garagulya – 4.35.1
W3 Total Cache: توسط Frederick Townes – 0.9.5.4
Woo Checkout Field Editor Pro: توسط ThemeHiGH – 1.1.9
ووکامرس: توسط اتوماتیک – 3.1.1
افزونه Yoast SEO: توسط تیم Yoast – 5.0.2
افزونه ارسال تیکت در وردپرس: توسط پرشین اسکریپت – 2.1.4
WP-Filebase: توسط Fabian Schlieper – 3.4.4
وردپرس فارسی: توسط زاکروت، راهکارهای مبتنی بر وب - با همکاری تیم وردپرس فارسی – 5.0.1
ایمیل SMTP وردپرس: توسط کالوم مک دونالد – 0.10.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

پایگاه فروشگاه: #2122 - /shop/
سبد خرید: #2123 - /cart/
تسویه حساب: #2124 - /checkout/
حساب کاربری: #2125 - /my-account/

### Theme ###

Name: Enfold
Version: 4.0.2
Author URL: http://www.kriesi.at
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس یا پوسته والد هستید پیشنهاد می کنیم از پوسته کودک استفاده کنید. چگونه یک پوسته کودک بسازیم را ببینید
WooCommerce Support: ✔

### Templates ###

Overrides: –
````
</details>

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This filter is not respected because the internal meta handling in the CRUD does not use `get_user_metadata`. This approach won't be supported.

https://github.com/woocommerce/woocommerce/blob/a9058fe10bca25e5bd7330f8878a2441ab8d4606/includes/data-stores/class-wc-data-store-wp.php#L68-L80

Without going too deep, we're not able to use these functions because we also need the meta IDs. These functions only return keys and values.

I'll add a filter there so you can adjust data retrieved via the data store. But it will require some coding changes in your class.

BTW it does not look like that filter passes the value? https://core.trac.wordpress.org/browser/tags/3.7.1/src/wp-includes/meta.php#L276

And other meta retrieval functions are not covered in your example either:
https://core.trac.wordpress.org/browser/tags/3.7.1/src/wp-includes/meta.php#L350

There are many ways to access WP data, either directly or through meta functions. There is no abstraction layer. So your solution may be incomplete, even if you added support for the CRUD classes.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16140 adds a filter for meta data.  To be clear, this is only extra meta data, not fields such as the shipping and billing address.

If you're finding other data such as addresses not being handled, it uses `get_user_meta` here https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-customer-data-store.php#L146 Make sure your code handles cases where non-single values are returned, since this does go through the meta data API.
