### ISSUE TITLE
Alternatives to `default_product_type`

### ISSUE THREAD

**Issue by braders** [woocommerce/woocommerce#16144]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Details of issue

In previous versions of WooCommerce the default product type could be set with the `default_product_type` filter. This affected the new product screen (/wp-admin/post-new.php?post_type=product) by setting the initially selected product type. 

In previous WooCommerce version this could be used as follows:
```
function set_default_product_type(){
    return "variable";
}
add_action( 'default_product_type', 'set_default_product_type' );
```

However, it appears this filter was removed in October last year as part of the move to getter/ setter functions - https://github.com/woocommerce/woocommerce/commit/038104c8a83e3d1938829d3701d816b4d55b4fbb.

So my questions are:

 - Was this intentional & was it publically discussed anywhere (I cannot find any record of why this was removed).
 - What are the alternatives in WooCommerce 3.x.x?

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
I don't think there is a discussion but it was removed because of the way CRUD objects work. This filter was incompatible with the way forward, and cannot be applied to the new objects because the default is to have no type, with a fallback to simple. We don't plan on reintroducing this filter.

Since it only affects the selector on the edit product page, JavaScript could be used to change the default value of the box only on the 'new' product screen, using jQuery `.val()`. Once changed, the panels would also change to reflect this change.

Thanks
