### ISSUE TITLE
Facing product image problem, when I'm clicking on product, it;s opening with image path, Please check here : http://www.funscapes.ca/shop/wood-clubhouse-roof/  anyone can help??

### ISSUE THREAD

**Issue by angelasmith22** [woocommerce/woocommerce#16193]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by killrazor** [comment]
I think this fails that  "This is not a usage question (Those should be directed to the community, unless this is a question about a premium plugin in which you should use the helpdesk for official extensions or contact the author of 3rd party extensions)" prereq.

And you gave no steps to reproduce, expected behavior, etc...

I'm not a regular here but I would think you aren't going to get any response from anyone whatsoever. 

Just to attempt to be helpful, it seems like code was edited that would have opened a Modal to display the image. How it is currently isn't the worst but more than likely not a bug that need to be reported here.

**Comment by mikejolley** [comment]
Theme is simply lacking support for the gallery in WC. Contact the author.
