### ISSUE TITLE
Problem when using API V1 order endpoint

### ISSUE THREAD

**Issue by stephennyu** [woocommerce/woocommerce#16196]
## Prerequisites

We have just encountered a problem when using API V1 for order endpoint.

This is the reply we get from the API server

```
[
    null,
    null,
    null,
    null,
    null
]
```

But when we try to switch to using API V2, all seems fine, but the problem here is we can't just migrating our entire codebase to using the V2 since it will break our exisiting code.
Any help on this matter is highly appreciated

## Steps to reproduce the issue

1. Accessing the woocommerce REST API using order endpoint /wp-json/wc/v1/orders?
2.
3.

**Comment by mikejolley** [comment]
Both v1 and v2 endpoints work for me. 

Obviously I cannot check this on your site, nor can I see what versions you're running or what plugins you're running alongside because no status report was provided, but given the 'null' response I'd say something installed on the site is adjusting the responses. I'm not seeing a code path which would show 'null'. 

https://github.com/woocommerce/woocommerce/blob/master/includes/api/v1/class-wc-rest-orders-controller.php#L357

In terms of data, v2 and v1 are fairly similar so it may not be as breaking as your think.

If you can narrow this down and comment back that would help, but right now this is not affecting other sites or reproducible from what I can see.
