### ISSUE TITLE
Jetpack sharing buttons should not be displayed on checkout, cart, order complete, my account, etc

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#16209]
i.e. these:

<img width="805" alt="screen shot 2017-07-20 at 1 44 50 pm" src="https://user-images.githubusercontent.com/1595739/28438087-c1334bfe-6d51-11e7-916e-09f97f520812.png">

The buttons don't make sense / aren't appropriate on cart, checkout, order complete, my account, possibly other places as well.

See `sharing_display` - https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=sharing_display&type=

Looks similar to closed https://github.com/woocommerce/woocommerce/issues/5410 so possibly a regression

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/5410 were completely inappropriate places due to misuse of filter hooks. These however are just pages. Users can control this:

<img width="338" alt="2017-08-07 at 12 43" src="https://user-images.githubusercontent.com/90977/29025337-218dc360-7b6e-11e7-811d-e8f19216ddf6.png">

If they were to be removed by default, the best place I see this logic living is here: https://github.com/Automattic/jetpack/blob/764a699120ca6795dac3d264207713516200ee7b/3rd-party/woocommerce.php There is a dedicated WC compatibility file. This avoids having Jetpack specific function calls in WC core.

@allendav is_cart/is_checkout/is_account_page conditionals could be used if you want to submit that as a PR to Jetpack? Or I can later in the week, just let me know here :)
