### ISSUE TITLE
Page crashes after trying to delete a product from our store

### ISSUE THREAD

**Issue by jessejamesvettv** [woocommerce/woocommerce#16218]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
![screen shot 2017-07-20 at 12 56 35 pm](https://user-images.githubusercontent.com/30347186/28465630-096c2d6c-6def-11e7-8df6-79a32dda1e8a.png)

2. 
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
> [x ] I have included a failing test as a pull request (Optional)

Really? Please don't check all the boxes without really doing the steps.

Your report is missing all the requested details, and there is no system status report. This issue is therefore invalid. Unless we're given proper steps to reproduce an issue we can only assume it's something specific to your install (theme/plugin bug) and cannot assist. Look at the server error logs for clues, or rule out plugin conflicts before coming here.

**Comment by jessejamesvettv** [comment]
Sorry that your form is confusing and isn't very detailed. You make it
difficult enough to even contact your company for any sort of help. This
was by far the unprofessional response from someone at a company I have
ever received.


Jesse James
Veteran Television
Writer, Store Ops Chief, Graphic Designer
303.889.9793
Semper Fidelis

**Comment by mikejolley** [comment]
@jessejamesvettv I'm here to triage bug reports and ensure they are logged correctly. The form is more technical because Github is a bug tracker, **not** a support forum.

>  This is not a usage question (Those should be directed to the community, unless this is a question about a premium plugin in which you should use the helpdesk for official extensions or contact the author of 3rd party extensions)

Use the helpdesk for support queries, as the form implies, or do some troubleshooting steps yourself. 

https://woocommerce.com/contact-us/ 

https://docs.woocommerce.com/document/woocommerce-self-service-guide/
