### ISSUE TITLE
Selecting a variation triggers product image gallery load

### ISSUE THREAD

**Issue by softtama** [woocommerce/woocommerce#16257]
Hi.

I setup my product to have only 2 variations (color, size). As we know, selecting a variation in the front end product page will trigger product image gallery to load. So, for my requirement, I want only Color variation that triggers the gallery load. Currently, the Size variation triggers the load too. Is there any documentation or thread for that?

Thanks.

![wjvte 1](https://user-images.githubusercontent.com/7237624/28605147-f79608b0-71f9-11e7-82fa-24220260b7e8.gif)

Question on StackOverflow by me: https://stackoverflow.com/questions/45076277/woocommerce-separate-variation-relationship

**Comment by mikaelz** [comment]
I tried https://youtu.be/4BHiqxL2JwE with a custom theme and only woocommerce plugin and functions good.
Only the main image reverted from scroll on variation click.

1. You're using custom theme, paid or free? Themes might interfere.
2. Could you provide URL to try?
3. Could you try with disabling all plugins except WooCommerce if the problem persists?

**Comment by claudiosanches** [comment]
By default is not possible to have attributes like you are displaying... This issue is missing a lot of information, you ignored the entire issue template, we don't know what plugins you are using or any details to reproduce this issue, so this is issue is invalid and sounds like a support question... Better you try the support channel of the plugin that you are using to change the attributes to colors and sizes like the screenshot, if is a WooCommerce.com plugin you should try the helpdesk in: https://woocommerce.com/my-account/tickets/
Thanks.
