### ISSUE TITLE
Prices are set to zero when update.

### ISSUE THREAD

**Issue by patrick66053** [woocommerce/woocommerce#16251]
If we update our site to the newest version then al of the prices are setting themselves to €0,00

**Comment by mikejolley** [comment]
> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action

Can you amend the issue?

**Comment by patrick66053** [comment]
If we update the woocommerce all prices of our products changes to €0,00

**Comment by mikejolley** [comment]
I understand this, but you've provided no context. Github is for logging bug reports, which is why you're asked for a bunch of information on submission. This issue lacks any information we can use to reproduce an issue.

If you need technical support use the helpdesk: https://woocommerce.com/contact-us/
