### ISSUE TITLE
shopping cart is broken if user not logged in!

### ISSUE THREAD

**Issue by Faracademy** [woocommerce/woocommerce#16271]
Hello,  we use woocommerce 3.1.1 and we have a problem like https://github.com/woocommerce/woocommerce/issues/10290

visit our website : faracademy.ir/shop and Add any product to the shopping cart, do not log in.
View cart. The cart is empty.

cart page = https://faracademy.ir/cart
checkout page = https://faracademy.ir/checkout

The cart is empty in **persian** = "سبد خرید شما در حال حاضر خالی است."
Checkout in **persian** = "تسویه حساب" or "تصفیه حساب" or "اقدام به پرداخت" 
you need this verbs in visiting our website. thanks

**Comment by mikejolley** [comment]
This is an issue in your environment. Not being able to debug myself, I'd guess it's caching implemented by your host because the cart disappears on refresh. Checked? Cart/checkout needs to be excluded from cache.

https://docs.woocommerce.com/document/configuring-caching-plugins/

Either that or the ajax refresh thing your theme is doing may be breaking it.

**Comment by Faracademy** [comment]
so i must to tell this problem to my hosting support unit?

**Comment by mikejolley** [comment]
You should certainly look into that.
