### ISSUE TITLE
Version 3 Requires customers to LOGIN for order pay links

### ISSUE THREAD

**Issue by amrod1** [woocommerce/woocommerce#16295]
When you send an invoice, in the email there is a link "<strong>pay</strong>" OR 
when you go to the order there is a link "<strong>Customer payment page →</strong>".

Example url;
/checkout/<strong>order-pay</strong>/1237/?pay_for_order=true&amp;key=wc_order_596827e54d351

In <strong>Woocommerce V2.16</strong> when you go to these urls you were seeing payment page that you can enter your payment information and complete the payment.

Unfortunatelly in <strong>Woocommerce  V3</strong> when you go to these links, you are forced to login to your account, 

it says;
<strong>PAY FOR ORDER</strong>
"Please log in to your account below to continue to the payment form."

My question is how we can disable this "force login" in checkout/order-pay page?
This problem is being asked for a long time and there is no solution yet. I searched most of the forums.

**Comment by mikejolley** [comment]
You can filter the user caps to allow it https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/shortcodes/class-wc-shortcode-checkout.php#L98 but really we don't want to support this in core because when you pay as someone else, their details (including payment preferences) get saved to your account. Plus if not logged in, it could leak data.

**Comment by lucanos** [comment]
This should probably not have been Closed off, as it also affects stores where Guest Checkout is permitted (which means that Customers don't have a Login to enter to get to the Payment Page).
