### ISSUE TITLE
Improve Refunded Tax Handling in Order Reports

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#16306]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior

The core sales reports intend to calculate net sales totals by getting sales, less shipping and taxes assessed in an attempt to isolate "product"-based revenue. 

However, if sales tax in a given period has been refunded, these refunded totals are _negative_ numbers, which means that they're added to net sales. 

As the intention is to omit these totals from the calculation, I'm pretty sure this is incorrect. [See this line for an example](https://github.com/woocommerce/woocommerce/blob/cad30e96130e68a7505c880af35e899bd8d43443/includes/admin/reports/class-wc-report-sales-by-date.php#L394) -- if you log each value that goes into that calculation, you'll see that your subtracting a negative number for sales tax / shipping tax, which will then be added to your net sales.

Consider these two scenarios:

 - Assume all positive totals for order totals, shipping totals, and tax totals: $100 in sales, $5 total assessed in shipping, $2 assessed in tax. My net sales in this period are $93 because this is the actual "revenue" from sales collected.
 - Now assume we've had refunded tax in this period. My net sales will be marked as $100 - $5 - ( -$2) = $97. This doesn't make a lot of sense to me, given that the intention is to exclude tax from the sales revenue in the first place. Therefore, if it's refunded, given that it wasn't part of the sales total in the first place, the refunded total shouldn't be considered in future calculations as "revenue"; it should probably be ignored instead. 

A more consistent intention would be to _omit_ tax from net sales rather than _subtract_ tax from net sales.

## Steps to reproduce the issue
Here's the most obvious way to recreate this:

1. Create 2 orders:
   - an order placed today with no sales tax assessed - [See screenshot](https://user-images.githubusercontent.com/4983547/28810174-5ec75902-7656-11e7-8570-8ba83fd998be.png)
   - an order placed yesterday; the items in this order have sales tax assessed on the line items / shipping.
2. Refund the order from yesterday (ensure the refunded date is _today_ though, as we'll only be pulling today's report). Ensure that the tax values are refunded. [See screenshot](https://user-images.githubusercontent.com/4983547/28810195-82a03646-7656-11e7-9c12-5bac9604a124.png)
3. Pull a sales report for today only. Notice that the net sales is incorrect: [See screenshot](https://user-images.githubusercontent.com/4983547/28810212-96f2fc14-7656-11e7-9554-56de20ba42ea.png)

My gross sales are correct, based on the following: 
$122 sales - $14.48 refunded = **$107.52 gross**

Net sales are incorrect. Given that taxes should not be included in my net sales total, I would expect them to be subtracted, and the net sales total to be:
$107.52 gross - $11 net shipping ($1 was refunded) - $0 in tax or shipping tax = **$96.52 net sales**

However, the refunded sales tax poses the obvious problem here -- rather than ignoring these negative tax values, it will include them in the calculation, adding them as sales:
$107.52 gross - $11 net shipping - (-$3.24 sales tax) - (-$0.24 shipping tax) = **$100.00 net sales**

I'm pretty sure this is entirely unexpected for a merchant, producing some pretty unintuitive reporting on what your "real" revenue was. Given that refunded tax isn't a product sale, it likely shouldn't be shown like one.

At first glance, I think that taxes should only be included in the net sales calculation here when > 0 so that the intention is to completely ignore taxes in net sales.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WP 4.8 / WC 3.1.1

**Comment by mikejolley** [comment]
Hmm this is pretty confusing, but I don't fully agree with the logic. I did your steps and put together these two orders.

<img width="146" alt="2017-08-11 at 11 35" src="https://user-images.githubusercontent.com/90977/29209980-4666edb0-7e89-11e7-9ed5-00518d89257b.png">

I sold $100 today (that order had no tax).
I refunded $19.50 today (that also refunded some tax).

I don't think it matters how much tax was or was not refunded, my sales today after refunds equal 100 - 19.50 = 80.50. This matches the report:

<img width="263" alt="2017-08-11 at 11 37" src="https://user-images.githubusercontent.com/90977/29210051-91f735c8-7e89-11e7-9c99-14fb91a7e2ae.png">

Am I missing something there? From initial testing it looks to be correct, at least, it's working how it was intended looking at the code so I don't think it can be classed as a bug.

> I'm pretty sure this is entirely unexpected for a merchant, producing some pretty unintuitive reporting on what your "real" revenue was.

This I do agree with. I'd love at some point to look at the reports from scratch with fresh eyes. I don't think we need something Metorik level, but basic sales and tax reports + insights to compare dates would be useful. 

Since you've logged a few report issues in the past, this is perhaps a project you'd be interested in contributing to? Having a good spec put together in terms of what reports would be useful to merchants, and what data they are made up from would be awesome. It would at least save us going back and forth trying to make the current reports 'work' :)

**Comment by mikejolley** [comment]
@bekarice O and I I missed the point above please let me know where I went wrong and I'll reopen for next week.

**Comment by mikejolley** [comment]
Looks like when I was looking into this I 'patched' it and forgot :D My net is $85.

**Comment by mikejolley** [comment]
There we go, see https://github.com/woocommerce/woocommerce/pull/16411

**Comment by bekarice** [comment]
Sure, happy to help out with those. not something I have bandwidth for within the next ~6 weeks but something I could contribute to for a 3.3+ cycle
