### ISSUE TITLE
How to handle stale CRUD objects

### ISSUE THREAD

**Issue by EmilEriksen** [woocommerce/woocommerce#16362]
I have a function that updates some order meta hooked to `woocommerce_order_status_completed`. Something along the lines of:
```php
add_action( 'woocommerce_order_status_completed', function( $order ) {
    $order->update_meta_data( 'some_meta', 'some_value' );
    $order->save();
} );
```
I believe the order completed email is hooked to this action as well (somewhere up the "hook chain"). In the order completed email this meta is again fetched using $order->get_meta(). Something along the lines of:
```php
add_action( 'woocommerce_email_order_details', function( $order ) {
    $some_meta = $order->get_meta( 'some_meta' );
} );
```
The issue is that $some_meta is empty. Doing a `$order->read_meta_data()` or `$order = wc_get_order( $order )` before fetching the meta solves this. I think this is because the order object passed in `woocommerce_email_order_details` was created before the order object in `woocommerce_order_status_completed` was saved. With an event driven system it's extremely difficult to know when a CRUD object has gone stale like this and when to update it. What's the best way to handle this?

**Comment by mikejolley** [comment]
@EmilEriksen There is not good way to do this because instances of the same order do not know about each other. What we have been trying to encourage however is to use the main instance which gets passed around.

For example, in the case of `woocommerce_order_status_completed` the first passed arg is the ID, and the second is the instance. If you use the passed instance, hooks further up the chain will see any changes you make and include the data.

Hope this makes sense. If this can be clarified in a doc let me know which you'd expect it in. Maybe https://github.com/woocommerce/woocommerce/wiki/CRUD-Objects-in-3.0?

**Comment by EmilEriksen** [comment]
Ah, okay thanks! I hadn't noticed the second arg passed in `woocommerce_order_status_completed` was the order instance.

That seems like the right place to me.

**Comment by EmilEriksen** [comment]
Related to this; it's not actually possible to call `WC_Order->save()` in `woocommerce_order_status_completed` (or any of the hooks in `WC_Order->status_transition()`) since `WC_Order->status_transition()` is called in `WC_Order->save()` causing an infinite loop. 

I think this could be solved by saving `$this->status_transition` to a local variable and then immediately setting `$this->status_transition`  to false before doing any of the actions.

**Comment by mikejolley** [comment]
Hmm can you submit a PR to show what you mean?

**Comment by EmilEriksen** [comment]
I submitted #16379. Since `$this->status_transition` is set to false before firing the hooks the if condition on line 311 should fail on consecutive calls to WC_Order->save() from one of the hooks.
