### ISSUE TITLE
WooCommerce Additional Variation Images Not work

### ISSUE THREAD

**Issue by shiransavion** [woocommerce/woocommerce#16371]
Hi
i buy WooCommerce Additional Variation Images plugin and i use the gem or porto wordpress themes
i upload one image for the  variable and one or more in "Add Additional Image" but i not see the images from "Add Additional Image".
if i change the theme to "Twenty Fifteen" or "Twenty Sixteen" wordpress theme its work and i see all the images but in porto or the gem theme its not work.
thanks for the help.

**Comment by mikejolley** [comment]
> This is not a support portal. If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/

**Comment by PrinceOfAbyss** [comment]
@mikejolley I'm sorry for bringing this topic up after so many years, I know this is a bug report topic while my question is a presales one more or less...

However, as I googled the matter and this topic was returned, can you please let me know before I proceed to purchasing your plugin, that any incompatibility issues with Porto theme were resolved?

At first I asked the same question to the Porto authors, but as their support is awful, they replied that any use of external plugins is generally discouraged, as many times external plugins tend to conflict with their theme... So instead of giving me a clear answer, they once again advertised their paid service under which they tend to deal with such special cases needed custom work... Go figure...

Anyway, the theme is what it is, their support is what it is, but my website is 95% ready to publish, and only this detail is left to deal with... So can you please confirm or deny the compatibility between your plugin and Porto theme? Thank you in advance!

PS: There is another plugin that adds this kind of functionality, a free plugin, which I tried, but it doesn't work with Porto... That's why I wanna make sure before I purchase it that it works fine!
