### ISSUE TITLE
Show/handle manual discounts in cart.

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#16444]
We did this in admin,  but have not added any such display for the cart https://github.com/woocommerce/woocommerce/pull/16392

Once this is ready, we should perform the following tests and checks:

- [ ] Add $10, 10%, and coupon discount to cart. Place order
- [ ] Add Add $10, 10%, and coupon discount to custom/manual order.
- [ ] Compare all meta data saved in DB between both. Ensure they match.
- [ ] Check prices inc tax, display inc tax logic.
- [ ] Check prices ex tax, display ex tax logic.
- [ ] Check prices inc tax, display ex tax logic.
- [ ] Check prices ex tax, display inc tax logic.
- [ ] Final audit of method naming/duplicate code.
- [ ] Ensure cart and order methods have similar naming conventions.
- [ ] Test against store credit extension.
- [ ] Test against smart coupons extension.
- [ ] Test against deposits extension (check payment plans).

**Comment by claudiulodro** [comment]
Logging this issue here so we don't forget. (Happens in cart and order, so it's something in WC_Discounts)

<img width="1357" alt="screen shot 2017-08-17 at 9 22 23 am" src="https://user-images.githubusercontent.com/7317227/29422885-7426129a-832e-11e7-883c-636496991467.png">

The discount is applying negative taxes for unused tax classes. (The product is standard rate and shipping isn't taxed)

**Comment by mikejolley** [comment]
This is not happening now - I'll log an issue for fees.
