### ISSUE TITLE
Call to a member function get_formatted_billing_full_name()

### ISSUE THREAD

**Issue by fhervazquez** [woocommerce/woocommerce#16487]
Error in email notifications after this morning update.

**Comment by fhervazquez** [comment]
Using original templates, not overridden.

![screenshot-www ocp com 2017-08-16 15-02-53](https://user-images.githubusercontent.com/26604917/29387276-20fca6d2-8294-11e7-8599-d0672297fa8a.png)

**Comment by claudiulodro** [comment]
Do you have the full stack trace from your logs or any other information? 

Also, the order exists and it's a valid order, correct?

**Comment by fhervazquez** [comment]
It is all i have. The order does exist!

**Comment by claudiosanches** [comment]
Better fill all the issue template, since is missing a lot of information, like steps to reproduce it.
For what we can read in the error message is that the `$order` is null and trying to get a method... And there is a lot of things that could cause it, like plugins or themes.
Better check everything before and open another issue filling all field in the template, this will helps a lot debug it.
Thanks.
