### ISSUE TITLE
Shipping prices entered Exclusive of VAT is rounded too early

### ISSUE THREAD

**Issue by batesy87** [woocommerce/woocommerce#16498]
WC Version@latest

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L263

When prices are entered excluding VAT the shipping total cost is rounded too early and causes the order the be stored with the pre tax value to 2dp

e.g. a Flat rate shipping of £4.95 set to £4.125 (because prices excl tax)
will actually come out as £4.96 due to the above

On our store we have an export of vat exclusive orders/items/shipping to import into our ERP system and this is causing a mismatch when vat is calculated

**Comment by mikejolley** [comment]
Only on master? 3.1?

**Comment by batesy87** [comment]
Sorry, yes.. 3.1.2

**Comment by mikejolley** [comment]
This isn't something we can fix easier unfortunately. When you introduce the extra precision, some services/gateways etc break due to totals mismatching. Really, the most reliable way to keep things working is to use 2dp prices.

Since we don't support tax inclusive prices for shipping there is not a way to support your use case in core. We did think about adding tax inclusive support but this has not been a high priority because it's a potentially breaking change, and tbh it's much harder to work with tax inclusive prices than it is tax exclusive.

I think you'll need to either decide on 4.94 or 4.96 for shipping costs and avoid the 3dp precision in the meantime.

Sorry about that.

**Comment by AJDinmore** [comment]
Hi,

My colleagues and I are having trouble understanding why the rounding is necessary here and which totals might mismatch because of the extra precision. Would you mind expanding on why it's required, to sake our curiosity? Perhaps an example case where taking it out breaks something?
