### ISSUE TITLE
If no extensions load the update helper, don't load it and make irrelevant http requests

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#16536]
With no extensions from woocommerce.com or anything that is loading the update helper, it is still trying to connect to woocommerce.com to check for updates and subscriptions. Nothing has loaded the helper but WooCommerce core - so why is it trying to connect? This seems extremely inefficient and pointless.

Unless there is a purpose for phoning home without any reason to.

**Comment by mikejolley** [comment]
As mentioned in https://github.com/woocommerce/woocommerce/issues/16537

`
- These requests only happen after connecting to woo.com via the helper.
- "zero WooCommerce.com extensions" is not relevant here because the helper code is pulling a list of extensions from your account. Subscriptions are listed even if not installed.
`

So if you're connected via the helper to woocommerce.com, requests are normal. Requests occur on plugin deactivation and activation, and on helper screens.

All code only runs when the helper is connected and you have auth details - I've checked all methods and when auth is empty, no helper requests are made.

There is one exception I can see; if you have a plugin or theme using the global `woothemes_updater`. If this is found (from the old helper), it will attempt to migrate the connection to the new helper then deactivate the old helper.

In testing, I had no requests attempted whilst not connected via the helper. I was monitoring with query monitor.

**Comment by mikejolley** [comment]
NVM the other issue/fix resolves this too.
