### ISSUE TITLE
Make update helper HTTP requests not fail

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#16537]
I don't know if this is an issue with WooCommerce.com or WooCommerce itself, but, HTTP requests shouldn't be made 

1. to endpoints that are going to return a forbidden error or 
1. if there is no authentication handy to make the http requests and we know it will return a forbidden error - don't make the api call.

At the root of the WordPress dashboard with zero WooCommerce.com extensions there is an extra 2.5s of load time just because of these http requests.

![](http://c.pmgr.mn/apfIa+)

**Comment by mikejolley** [comment]
@pmgarman The endpoints are valid and working it seems:

https://dl.dropboxusercontent.com/s/bzkrefrmhkxuxcb/2017-08-21%20at%2010.34.png

Also note:

- These requests only happen after connecting to woo.com via the helper. 
- "zero WooCommerce.com extensions" is not relevant here because the helper code is pulling a list of extensions from your account. Subscriptions are listed even if not installed.

Temp downtime? Blocking requests somehow? Either way the code can be tweaked to bail without auth.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16544
