### ISSUE TITLE
WooCommerce CSV Import Wrong Behavior of Products Afterwards

### ISSUE THREAD

**Issue by mateomalik** [woocommerce/woocommerce#16533]
I have a large database of products so I decided I will import stuff I need. WooCommerce imports my products correctly, including special <i>meta tags</i>. I am using the built-in CSV Import feature of WooCommerce.

The problem is that at this moment after I import my variable products with <i>zero stock quantities</i> I get a product that has MANAGE STOCK option <i>enabled</i> and STOCK STATUS is <i>in stock</i> and I cannot disable it. All product variations' quantities equal zero but this is always ON and IN STOCK message is visible.

The thing is strange, because when I create a VARIABLE product in WooCommerce (not through import) it works correctly.

This behavior has a bad impact on showing of product with ZERO QUANTITY in the shop. When imported product have ZERo QUANTITY they are shown in the shop (simple and variable products). If I create the same product by hand ONLY THOSE that have QUANTITY greater than 0 are shown.

Attachments: Archive with SYSTEM REPORT + EXAMPLE CSV FILE
[Archiwum.zip](https://github.com/woocommerce/woocommerce/files/1236263/Archiwum.zip)

WC Ver.: 3.1.2
WP Ver.: 4.8.1

**Comment by mikejolley** [comment]
Sending a value (or or otherwise) will toggle stock management on when using the importer.

If you don't want stock management to turn on, send an empty value rather than 0.

When you enable stock management at product level as well as variation level, different rules can apply to how variations display. It sounds like you only need stock management at variation level.

Thanks
