### ISSUE TITLE
Some shipping fields get empty after ajax order update

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce#16542]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Choose product requires shipping
2. Go to checkout
3. Fill billing/shipping fields
4. Change any field to initiate ajax checkout update

## Expected/actual behavior

When I follow those steps, I see some fields (like shipping_first_name, shipping_last_name, shipping_company) gets empty. 

I was expecting to see all field values preserved.

**Comment by smazur** [comment]
Here is a filter I used to temporarily fix issue:

`
add_filter( 'woocommerce_checkout_get_value', function( $value, $input ) {
	if( is_ajax() && empty( $value ) && isset( $_POST['post_data'] ) ) {
		// Get checkout form data from 'post_data' variable
		if( is_string( $_POST['post_data'] ) ) {
			parse_str( $_POST['post_data'], $post_data );
		} else {
			$post_data = $_POST['post_data'];
		}

		if( !is_array( $post_data ) ) {
			return $value;
		}

		if( isset( $post_data[$input] ) ) {
			$value = $post_data[$input];
		}
	}

	return $value;
}, 20, 2);
`

**Comment by mikejolley** [comment]
Since there is no link to the site provided or status report it's hard to say for certain, but it sounds like a theme conflict. 

Why? Because address fields do not change after an ajax update. Only the bottom payment/shipping area is reloaded by default.

Also the current code should catch all post data:

`if ( ! empty( $_POST[ $input ] ) ) {
			return wc_clean( $_POST[ $input ] );
`

So this would only fail if post data was missing for some unknown reason. Look at themes/plugins first.

Thanks

**Comment by smazur** [comment]
@mikejolley Thanks. You are right it's our theme issue.
