### ISSUE TITLE
Woocommerce cannot login using email address (only username)

### ISSUE THREAD

**Issue by KVNHNF** [woocommerce/woocommerce#16614]
Hi, 

A customer asked us, when trying to login through woocommerce dashboard, why does it says "login using your username or email" (above the password field) but only the username works?

Can this be changed in future updates? Either edit the text to "login using your username" or add the ability to also login using email add? 

Many thanks 

Best regards

**Comment by claudiulodro** [comment]
Email login is supported and works. [Here is the code that handles it](https://github.com/woocommerce/woocommerce/blob/56f2dc6005481187abdd4df8d6f582bf9d782fc5/includes/class-wc-form-handler.php#L932-L943).

Make sure the user is trying to log in using the same email they have in their Account Details section. If their email looks good, here is how you can pinpoint the problem better: disable all plugins except WooCommerce and use a standard theme like twentytwelve or Storefront. If the issue still happens the problem is WooCommerce. If it doesn't the problem is one of your other plugins or themes.
