### ISSUE TITLE
Invalid timestamp please help me i

### ISSUE THREAD

**Issue by meysamsh** [woocommerce/woocommerce#16621]
Hello
i install modernshop app category an product not show

{
"code": "woocommerce_rest_authentication_error",
"message": "Invalid timestamp.",
"data": {
"status": 401
}
}

This problem does not exist in store in localhost
please help me

**Comment by claudiulodro** [comment]
This is going to be a problem in the way ModernShop is authenticating. [Timestamps are valid for 15 minutes](https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/api/class-wc-rest-authentication.php#L444). The error you see happens when an invalid timestamp is used when trying to authenticate. This isn't a bug in WooCommerce. I would go to the ModernShop support for solving this issue.

**Comment by ameenbadri7** [comment]
check the time and date of your localhost  or online server, for me

"code": "woocommerce_rest_authentication_error",
"message": "Invalid timestamp.",

was because of the time and date.
