### ISSUE TITLE
WooCommerce Orders section bug

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#16629]
As I have no alternative OR idea of where to place this specific bug to... I thought that I would note it here once again.

After being told by a user/admin of this repository when I initially reported this bug, it is still occurring within my account that still utilizes WOOCOMMERCE.

Everything from the status report states that WooCommerce is optimal & reports no errors... however, attempting to enter my order section results in an infinite loop of wait time that consistently fails to load, etc.

I have attempted to de-activate & re-activate woocommerce but that still doesn't help. Any suggestions and/or comments would be appreciated.

Thanks!

**Comment by mikejolley** [comment]
The new issue form has a list of things you should do before logging bugs, since ruling out conflicts usually finds your problem. There are also some requested details you've missed in the report. 

```
- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above
```

If you can reproduce the issue with only WooCommerce active, and with a default theme active, send the status report and any php error logs you can find. I don't anticipate this being a "bug" because there would be more users reporting it, so I think it will turn out to be a conflict.

Thanks
