### ISSUE TITLE
Importing a Variable product CSV leaves out the variations, Price, Stock

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#16635]
### Summary

When I import a variable product with 4 attributes, 2 of which are used to variations, having 9 variations. After the import we see that the variations are not created, the inventory is set to `out of stock`

### Steps to recreate the behavior:

1. Create a variable product having 4 attributes, 2 of which are used for creating variables ![](http://cld.wthms.co/jsyM8t+)
2. Now set price for each of the 9 variations that get created.
3. Goto **Products >> All Products >> export** and export this variable product as CSV.
4. Delete the existing variable product and now Import the CSV back to WooCommerce from **Products >> All Products >> import**.
5. We will now see that the stock is set to `out of stock`and the variations are not created.
6. Here is the CSV that I tried to import http://cld.wthms.co/HETcwO

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior

When I follow those steps, I would like to import the exact same variable product with all the specifics which was exported.

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: http://woo.dev
Site URL: http://woo.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.1
PHP Version: 7.0.20-2~ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Test Payment Module for Woocommerce: by Sean Barton (Tortoise IT) – 1.5
WooCommerce Pre-Orders: by WooCommerce – 1.5.1 – 1.5.3 is available
WooCommerce: by Automattic – 3.1.1 – 3.1.2 is available

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
@spraveenitpro Please reopen if this isn't what I said on Slack; variations need to be exported as well. Not just variable.

**Comment by comfortablejohn** [comment]
@mikejolley @spraveenitpro I also had this issue, but managed to get the import working. 

Say we have a global attribute `Size`, with three variations `Small, Medium, Large`. 

The attribute name in the exported CSV for both the variable product, and the variation, will reflect the attribute as named above, i.e. `Size`.

I found that in the [set_variation_data](https://github.com/woocommerce/woocommerce/blob/1a8a16c79caa26c750a18bd05efee2bf99f7273b/includes/import/abstract-wc-product-importer.php#L390) function, the parent product (i.e. the variable product) was saving it's attribute as the global slug: `pa_size`. So when importing the variation with attribute name `Size`, it finds no attribute attached to the parent.

Using the attribute name `pa_size` for __variations__ fixed this for me. For example:
```
ID       | Type        | Name                   | Attribute 1 name
--------------------------------------------------------
4985  | variable   |  Test 2                 | Purchase Type
4986  | variation  |   Test 2 - Single  | pa_purchase_type

```
I suspect this isn't intended as a required convention?

**Comment by werm42** [comment]
I too am plagued by this issue, it works fine for about a week (been playing with the same batch of data for a while), then today WHAM the following is missing on import:

1. no variable > variation relationships, 
2. no prices
3. no stock status

Any insights on how to fix this are appreciated.

**Comment by mikejolley** [comment]
Send example CSVs if it's the same issue as above ^ And screenshots of global attributes.

But please note, the variable product (parent) needs the values/terms. If they are conflicting we can probably work around it.

**Comment by jsears** [comment]
I'm currently having this issue as well, and nothing I use has overcome it.  I tried the wp all import plugin as well.  If I import variable products first, then variations I still have an issue because it does not set the use for variations radio button, nor does it properly assign the variation (eg Length 10") for each variation so they exist, but show up as the lowest one when you try to check out.

Even exporting once I've got them all working right doesn't export ALL the correct required data for variations.  (see attached csv file: [wc-product-export-2017-11-24.zip](https://github.com/woocommerce/woocommerce/files/1501963/wc-product-export-2017-11-24.zip)).

My client is missing out on Black Friday due to this issue.  If someone could provide insight to making this work it would be greatly appreciated.

**Comment by ep-dev** [comment]
I'm also experiencing this issue, similar to jsears above, related to custom product attributes with special characters in the values. In reviewing, it appears that the sanitize_title function being used for both the attribute name and values being imported could be causing the issue where these are successfully created when added manually but cannot be imported properly.

## Steps to recreate the behavior:

1. Create a variable product having 1 attribute used for variations and include special characters in 2 attribute values.
2. Set price and unique SKU for each of the 2 variations that get created.
3. Go to Products > All Products > Export and export this variable product as CSV.
4. Permanently delete the existing variable product andi

Import the CSV back to WooCommerce from Products > All Products > Import, skipping import of the ID field for the previously permanently deleted product.
5. The variations are not created - "Used for variations" is not checked and product is listed as Out of Stock.

Attached is the CSV that I exported and tried to import to again.

[wc-product-export-2017-11-27-exportdata.csv.xlsx](https://github.com/woocommerce/woocommerce/files/1506610/wc-product-export-2017-11-27-exportdata.csv.xlsx)

**Comment by angiebabakhani** [comment]
Hi Everyone! Please help me I am having this same problem with my CSV sheet. Everytime I try importing my products the items import with no size variation, or stock or price.  I have included a PDF of the CSV I am using. Here is the format I want to follow for my site. I am selling matching clothing for mother and daughter. I have one product for example Blue Woman's Dress (variation- Small/Medium/Large). Then I have a different product Blue Child's Dress (variation- 7/8, 9/10, 11/12, 13/14). Once I am done inputting these two products I group them together in a different grouped product called Blue Mommy & Me Dress (this would link both products above into one easy page for people to click thru which would take you to the individual womans dress or childs dress). Sorry if I put too much info into this. I am a newbie to woocommerce. So I think my problem is the title for the CSV sheet. I am completely not good at this so if you can help please lay it out step by step because seriously I have been lost for 2 months on this problem. If you can just format one product for me so I can see what I am doing wrong? THANK YOU SOOO MUCH!!!

[Please Help-Import.pdf](https://github.com/woocommerce/woocommerce/files/1558013/Please.Help-Import.pdf)

**Comment by mikejolley** [comment]
3.2.6 had an ID bug fix related to variation import.

If unsure about how to format columns, create a variable product manually and export. It will show the correct columns etc.

**Comment by angiebabakhani** [comment]
Hi mike! I am on version 4.9.1 and I am still having problems. 

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 14, 2017 at 3:08 AM, Mike Jolley<notifications@github.com> wrote:   
3.2.6 had an ID bug fix related to variation import.

If unsure about how to format columns, create a variable product manually and export. It will show the correct columns etc.

**Comment by angiebabakhani** [comment]
Also that is how I originally came about the CSV file by doing an export but for some reason when I try to go back and import the products it comes up as out of stock with zero variation and no price

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 14, 2017 at 7:26 AM, Angie Babakhani<angiebabakhani@yahoo.com> wrote:   Hi mike! I am on version 4.9.1 and I am still having problems. 

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 14, 2017 at 3:08 AM, Mike Jolley<notifications@github.com> wrote:   
3.2.6 had an ID bug fix related to variation import.

If unsure about how to format columns, create a variable product manually and export. It will show the correct columns etc.

**Comment by mikejolley** [comment]
We'd need to see the CSV. Also 4.9.1 is your wordpress version, not woocommerce version.

**Comment by angiebabakhani** [comment]
Hi! Ok so I updated my woocommerce, thank you for the help regarding that. I tried to do what you tell me, I added a test variable product. I then exported and added a few items to the list. I then proceeded to import this CSV sheet into woocommerce and again it comes up as zero variation, zero stock, zero price. I am not sure what is going on. Please help. I have uploaded the CSV file for you to review. I uploaded it as a JPEG and as a PDF. Thank you.
![csv jpeg](https://user-images.githubusercontent.com/34531487/34076566-1d40d614-e2a0-11e7-92c6-5c9895cc5151.jpg)
[CSV PDF.pdf](https://github.com/woocommerce/woocommerce/files/1565319/CSV.PDF.pdf)

**Comment by mikejolley** [comment]
If you send that in CSV format I'll try it myself.

**Comment by angiebabakhani** [comment]
Hi Mike! Here you go. 
[CSV Import 12_18_17.zip](https://github.com/woocommerce/woocommerce/files/1568440/CSV.Import.12_18_17.zip)

**Comment by mikejolley** [comment]
There are duplicate SKUs causing the import to fail. Ensure each SKU for variations are unique, or leave it unset.

**Comment by angiebabakhani** [comment]
How is that possible each SKU is completely different from each other. Can you give me an example of my duplicates skus I made sure I rewrote all new skus multiple times so that they would not conflict with anything I've imported before. How can they be duplicate? Can you give me more insight. Im sorry im such a novice

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 18, 2017 at 7:28 AM, Mike Jolley<notifications@github.com> wrote:   
There are duplicate SKUs causing the import to fail. Ensure each SKU for variations are unique, or leave it unset.

**Comment by mikejolley** [comment]
9-women-2017 is repeated.

**Comment by ep-dev** [comment]
Following up on the same issue, comment posted on 11/27 with sample CSV to test.

**Comment by maricris823** [comment]
I have this same issue. I did an export (one item with variations), added shipping class, re-imported with no other changes, and it unchecked the "use for variations" for two of the three variations. It retained shipping status as a variation, and remove the other two. The attributes are there, just not checked as "use for variations". WP 4.9.1  WC 3.2.6  Apache 2.4.18 Ubuntu 
[test-import-from-tracy.xlsx](https://github.com/woocommerce/woocommerce/files/1570526/test-import-from-tracy.xlsx)

**Comment by maricris823** [comment]
IF anyone can tell me where in the db this, I'll just write an update query to "use for variations" as I now have 4000 products with this box unchecked, and no import variation I try will fix it. If I do it via the admin, it restores the variations.  It looks like it's in json format, is that correct? If this is the correct place, it's over my head on how to access and update via sql.

**Comment by mikejolley** [comment]
Sorry folks, this isn't a support area to dump all import issues you're having. If you need help with imports you should be using either the forums or the helpdesk, unless you have a legitimate reproducible bug to report which can be filed in a new issue so it's not buried.

In this case, variations do import if you have a valid CSV, and the dummy-data.csv file included with WooCommerce (which also has unit tests) imports correctly which shows variations can be imported successfully.

If needed, the docs for the importer are here https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter

The schema for the CSV is here https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

The final step after import has a link to view failures and usually gives a reason e.g. duplicate SKU.

> IF anyone can tell me where in the db this, I'll just write an update query to "use for variations"

@maricris823  It's serialised so I wouldn't recommend it unless you know what you're doing. `_product_attributes` meta.

---

I'm closing comments here now because the original issue has been addressed (the user failed to export variations). Again, if you have a new issue with steps to reproduce and a valid CSV to test with, please open a new issue up with the full details.

Thanks
