### ISSUE TITLE
Cookies items cart override DB items cart

### ISSUE THREAD

**Issue by eladvider-softangible** [woocommerce/woocommerce#16649]
Hi,
If  i have items in my cart as logged user, when i Logout and save items to my cart and then log in again - my previous cart items that saved in the database gone away.

Reporduce : 
1. log in 
2. Add items to Cart
3. logout 
4. Add items to cart
5. log in 

results : 
I have only the items from the seconds time that i was log out (came from the cookie/session)

Thanks

**Comment by mikejolley** [comment]
Persistent cart is only restored if your cart is empty. If you're logged out and add things to cart, it wouldn't make sense to replace those. Think about a situation when you have a cart and checkout, and login during checkout. Would you appreciate having items added last minute without knowing?

This is expected behaviour.

**Comment by eladvider-softangible** [comment]
Ok, 
its make sense but i will think about more sophisticated solution like if you are login during checkout then dont add the previous items but if you login in another page like homepage, shop etc .. then do merge between the Persistent cart and the sessions items

**Comment by eladvider-softangible** [comment]
So i saw that you change it in 3.2.6....

Fix - Merge session and persistent carts when both exists after login.
