### ISSUE TITLE
Separated tables on wp database

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#16692]
Hello,

This was planed almost 1 year ago but is there any process or ETA? All products are mixed with WP post that takes so long to query. That hurts performance so much.
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3232463-separated-tables-on-wp-database

**Comment by pmgarman** [comment]
WC 3.0 implemented CRUD classes - it is technically possible for you to move product data already. However you will find that too many plugins fail to support the CRUD API and you will not easily move your data without creating many conflicts. We use this on projects already.

In the interim you can solve the issue with solutions like Elasticsearch or Algolia. 

Personally I don't find any issues with leaving products where they are, for the few stores that require additional performance due to their data or scale, free open source plugins exist to solve that without moving the data and creating tons of conflicts.

**Comment by mikejolley** [comment]
Roadmap is here https://trello.com/b/YgRbpuze/woocommerce-platform-roadmap

**Comment by kevin25** [comment]
@mikejolley  Thank you. So there is no plan for it anymore?

**Comment by mikejolley** [comment]
https://trello.com/c/2QGrEbBW/113-an-order-database-that-can-scale-feature-plugin

**Comment by kevin25** [comment]
That is just for orders only. I'm concerning about products. 

> separated tables on wp database
> 
> you could better create unique wootables as products and orders, instead of saving them on posts and comments ones, just to organize data :3

**Comment by kevin25** [comment]
Thank you, @mikejolley

**Comment by kevin25** [comment]
@mikejolley  Looks like only orders are going to be moved out of it. How about products?
