### ISSUE TITLE
Cart expiry when changing product configurations

### ISSUE THREAD

**Issue by sambomcd** [woocommerce/woocommerce#16779]
Hello,

I have a situation with Product Bundles which I originally directed to the SomewhereWarm team but they suggested it goes beyond PB and could affect other product types, such as Variable Products or Grouped Products.

My client uses Bundles as their main product, however change the items in each Bundle every week. This can cause a situation where a customer who has added the Bundle to their cart but not completed checkout, then comes back later (after the Bundle contents are changed) receives an error that one of the Bundled Items is not available (presumably because it has been removed from the Bundle). They have to remove the Product Bundle from their Cart and re-add it to continue.

There seems to be 2 ways of dealing with this:
1. Have an option with PB to allow updating of Bundles that may be sitting in carts when the content of such a Bundle is changed.
2. Have the ability to control Cart expiry time.

I approached the PB team about number 1, and have searched for solutions for number 2 myself, and have tried the code outlined in [this SO question](https://stackoverflow.com/questions/41167646/woocommerce-set-cart-expiration-interval) to do with wc_session_expiring and wc_session_expiration but ran into 2 issues:

- The mini-cart used in some themes (Storefront in my case) does not update to reflect the state of the Cart (empty) once it expires.  The mini-cart retains reference to the items that used to be in teh cart, until something new is added.
- In my testing this works for 'guests' (i.e. not-logged in users) but it does not work for logged-in users.

I am not an expert by any stretch of the imagination, and I apologise if I am bulldozing straight across something obvious - I have spent a long time trying to find an answer to this prior to coming here. Any thoughts or ideas will be gratefully accepted.

regards,
Sam

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Maybe we/@franticpsyx should consider a hash of bundle contents. If it changes, invalidate the cart item.

Seems more bundle specific?

**Comment by franticpsyx** [comment]
Hey @sambomcd @mikejolley 

PB validates bundles in the cart on `woocommerce_check_cart_items` and adds a notice if there's a problem with their contents.

It does not remove invalid bundles from the cart automatically, but if you want them to be removed silently, one solution would be to hook into `woocommerce_cart_loaded_from_session`, check the container item with `WC_PB_Cart::validate_bundle_configuration` and silently remove the entire collection.

The reason I suggested that a core ticket be opened is that I saw this as an opportunity to check how core handles invalid configurable (variable) products in the cart _in general_. E.g. what happens when the attributes of a variation are changed? Is cart item variation attribute data validated?

As I mentioned to @sambomcd -- rather than silently removing cart items I feel it's better for the end user to let them know that the bundle the purchased has been modified.

Imagine you are adding a bundle / product to the cart, then proceed to checkout and all of a sudden your cart is emptied silently because the store owner changed something. Is this the best behavior for everyone? I'd say no, which is why PB works like it does now.

**Comment by franticpsyx** [comment]
> should consider a hash of bundle contents
💯 
That's more or less how the current system works. The config is stored in a cart item key and validated on `woocommerce_check_cart_items`.

**Comment by seb86** [comment]
Amazon checks and notifies you in the basket if the price of a product has changed and shows you what the price was before and what the new price is now.

Also, any item that is no longer available is still left in the cart or the "save for later list" while only removing the price of the item and informing the customer that this item is no longer available.

Is this related to what you are talking about?

**Comment by sambomcd** [comment]
Thanks guys.

@franticpsyx I can try hooking in to `woocommerce_cart_loaded_from_session` as you suggest, but it does seem to my (uneducated) mind that a simpler solution would be to have a configurable timeout on the cart session, set by store owner/admin, accompanied by a useful message to the end user that their cart has been emptied as it is 'stale'.

PB's aside, I can imagine other scenarios where this might be worthwhile: stores who change prices frequently, or offer specials that they don't want to drag past a certain cutoff time (both assume product prices do not get updated in cart, which I am actually not sure it's the way it works!). Or Grouped Products where config might change?

Coming back to the PB issue I actually have - I agree what I am looking for may not be the best behaviour for everyone. But this is a real life issue we face - we change the contents of our bundles once a week, whilst retaining the bundle itself with the same name, price, etc.  Is there no way of setting the cart session timeout, for all users (logged in or not)? The snippet I used from the SO article I posted earlier worked for non-looged in users just fine. Is there not some way of achieving something similar for logged-in users? Or a reason why it should not be reduced to, say, 2 hours?

**Comment by franticpsyx** [comment]
> a simpler solution would be to have a configurable timeout on the cart session, set by store owner/admin, accompanied by a useful message to the end user that their cart has been emptied as it is 'stale'.

I'm not sure how long WC maintains cart session data but reducing the "invalidation" time would not solve this.

> both assume product prices do not get updated in cart, which I am actually not sure it's the way it works

Prices are updated because products are re-instantiated on session load.

The only type potentially affected is the Variable one (stale attributes). @mikejolley might know how this case is handled in core.

> The snippet I used from the SO article I posted earlier worked for non-looged in users just fine.

I wouldn't recommend solving this by looping over (and modifying) all stored carts for performance reasons. Also, to display a message when these carts are re-loaded you'd need to store this "requirement" somewhere anyway -- which is why I suggested doing this on `woocommerce_cart_loaded_from_session`. When the "stale" bundle gets removed, you can add the useful notice you have in mind -- e.g. `"Product X" has been removed from your cart because its contents have changed. Please add it to your cart again by clicking here.`

WC does something similar when it finds a cart item (product) with an empty/undefined price.

**Comment by mikejolley** [comment]
Agree with @franticpsyx 

A simple invalidation/remove mechanism is all thats needed here.

**Comment by sambomcd** [comment]
OK guys. I do think there is a valid use case here that can lead to this error, however I appreciate that there are many other considerations, and maybe what we have happening is not a common use of the PB plugin. Will look at adding in a validation check. 

Thanks for your help!

**Comment by mikejolley** [comment]
Written up and moved this to https://github.com/woocommerce/woocommerce/issues/16970
