### ISSUE TITLE
Error while add category - rest_missing_callback_param

### ISSUE THREAD

**Issue by danielgamajpa** [woocommerce/woocommerce#16830]
When I try to send a POST to add category by API **"/wp-json/wc/v2/products/categories"**
and the body is a JSON, the following error is being returned:

`{"code":"rest_missing_callback_param","message":"Par\u00e2metro(s) ausente(s): name","data":{"status":400,"params":["name"]}}`

**Follow Wireshark log:**
**REQUEST:**

POST http://34.211.183.40/wp-json/wc/v2/products/categories?oauth_signature_method=HMAC-SHA1&oauth_timestamp=1505494579&oauth_nonce=2f9d9046ca8449c292d027e4dbbb0972&oauth_version=1.0&oauth_consumer_key=ck_5405d5ca29543c6d3522555bc8e66467b67f86b3&oauth_signature=5lq%2f518B01pLgnHDGrgZ3%2bdiN1M%3d HTTP/1.1
User-Agent: Nemiro.OAuth v1.12.4.2615
Accept: application/json
Content-Type: application/json; charset=UTF-8
Host: 34.211.183.40
Transfer-Encoding: chunked
Expect: 100-continue
Proxy-Connection: Keep-Alive

{"name":"MACAQUINHOS"}

**RESPONSE:**
HTTP/1.1 400 Bad Request
Via: 1.1 SEDNA
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Transfer-Encoding: chunked
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Date: Fri, 15 Sep 2017 16:51:34 GMT
Content-Type: application/json; charset=UTF-8
Server: Apache
X-Powered-By: PHP/5.6.30
X-Robots-Tag: noindex
Link: <http://34.211.183.40/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Cache-Control: no-cache, must-revalidate, max-age=0
Allow: GET, POST
X-Frame-Options: SAMEORIGIN
Vary: Cookie

{"code":"rest_missing_callback_param","message":"Par\u00e2metro(s) ausente(s): name","data":{"status":400,"params":["name"]}}

**Comment by mikejolley** [comment]
Tested this endpoint locally and it's functional. The only way I can trigger this error is by changing the request type from 'JSON' to 'Other'. Looks like the endpoint is not receiving valid JSON.

I'd suggest testing this over https in a client (https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API) before looking into whether the server is affecting the data before it's received. 

I'd also suggest testing the WP REST API to see if the same thing occurs.

Sorry I cannot be much more help, since I cannot replicate I don't think it's a bug our side. Let us know what you find anyway!
