### ISSUE TITLE
Mozilla Back issue after checkout

### ISSUE THREAD

**Issue by alisaleem252** [woocommerce/woocommerce#16904]
I am doing checkout as following url
site.com/checkout/?add-to-cart=PRODUCTID
After completing checkout i hit back on thank you page and get a message "Sorry, your session has expired", So i hit forward and hit back again, then this message disappears and new item is added in cart with checkout form.
As on second back Mozilla Consider it a new request and adds new item in cart.
Can this be fixed in WooCommerce or only mozilla can fix it?

**Comment by mikejolley** [comment]
Thats how the back button works across all browsers? You're going back to the checkout and seeing the result of the checkout 'post'. Because the cart is empty at that point, you will get the session expired message. I can only assume the second forward/back loses track of the POST data and essentially checks out again.

If you want to customise the checkout when the cart is empty, you can use the action hook `woocommerce_before_checkout_process`. In your function you can do a redirect or something fancy if the cart is empty:

```
if ( WC()->cart->is_empty() ) {
 // Do something
}
```
