### ISSUE TITLE
There's no way to save custom data for Attributes.

### ISSUE THREAD

**Issue by reigelgallarde** [woocommerce/woocommerce#16934]
https://github.com/woocommerce/woocommerce/blob/18873ac9a7372c75eea6eee2d49e65c64a0e027d/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L217-L269

Above function is what I'm referring to.. This function is called inside function save_attributes. Which is triggered or called via ajax.

https://github.com/woocommerce/woocommerce/blob/a871d36380bb4cfd4f94bf952af754301433d67b/includes/class-wc-ajax.php#L556-L574

**What I have tried:**
I tried hooking to `wp_ajax_woocommerce_save_attributes`.
But with priority 10 or greater, my function won't execute because of `wp_die()` inside function save_attributes.
I tried priority less than 10 but the attributes has not been saved yet.

My final work around now is to remove_action `wp_ajax_woocommerce_save_attributes`.
Copy its content and do some of mine.. It's just not neat..

Is there a way I might have missed? Ideally, I just need to set a custom data specific to an attribute. That can be saved when pressing "Save Attributes" button.

**Comment by mikejolley** [comment]
I guess a filter could be inserted around `$attributes[] = $attribute;` possibly, but you'd need to test to see if it meets your use case. Custom data for attributes has never been supported - core has no need or use for it so this will need to be developed. 

Using wp_ajax hooks is not ideal. You'd need a lower priority to run before our functions (it runs from lowest to highest, default 10).

Since we don't know what you need here, probably best you sent the PR for this. I'll close this issue out and review your PR when it's ready.

Thanks

**Comment by warezio** [comment]
Same problem here...
There's no way to hook for "save_attribures".
