### ISSUE TITLE
Invalidate cart items when a product is updated

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#16970]
If a product is edited, but is already in the cart, unexpected things may happen, such as paying too much for an item.

To get around this, we should invalidate cart items when edited.

- Store a hash of product/cart item data when it gets added to the cart.
- When the cart is loaded from the session, of the hash changes (maybe the product was edited?) remove it from the cart with a notice:

> Product X" has been removed from your cart because its contents have changed. Please add it to your cart again by clicking here.

This code should end up being pretty similar to https://github.com/woocommerce/woocommerce/blob/5122f29988949ca5882e60686ccbd9235b4e3bd5/includes/class-wc-cart-session.php#L90 which handles products which have no price.

The notice should link to the product page if complex (variable) or can be an add to cart link if simple. This should follow similar logic to the actual add to cart buttons in the store which handle these conditions.

This was originally logged in https://github.com/woocommerce/woocommerce/issues/16779

**Comment by seb86** [comment]
Hi @mikejolley 

Can you assign this one to me, please?

**Comment by mikejolley** [comment]
@seb86 I cannot assign non-org members, but go ahead it's yours.

**Comment by seb86** [comment]
Thanks.

**Comment by raftaar1191** [comment]
@seb86 

Are you working on this ?

**Comment by seb86** [comment]
@raftaar1191 Yes I am.

**Comment by raftaar1191** [comment]
Okay @seb86 If I can contribute to this issues in any way, Just let me know

**Comment by DavidAnderson684** [comment]
A similar issue is items in 'payment pending' orders? i.e. The items aren't in the cart, but in an incomplete order. I once had someone who paid the price of an item from 14 months earlier because they'd created an order but not completed payment ... and they came back 14 months later and completed payment, at the old, lower price. https://github.com/woocommerce/woocommerce/issues/8539

**Comment by mikejolley** [comment]
Orders are already saved/created so thats out of scope @DavidAnderson684 Thats also one of the reasons we cancel pending orders after a time limit :) Must be disabled?

**Comment by DavidAnderson684** [comment]
@mikejolley The orders aren't pending, but payment-processing (PayPal gateway). Should those be getting cancelled automatically? (I've not done something to explicitly prevent them getting cancelled).

**Comment by mikejolley** [comment]
Processing is paid, so paying again wouldn't happen?

**Comment by DavidAnderson684** [comment]
@mikejolley Unless it's changed since I last checked (but it doesn't seem to, as I have very recent ones in this state), if you use PayPal with the "pay on PayPal's site" flow, then orders go into a payment-processing state as soon as they press the button to take them to paypal.com, before payment. Then if they don't complete payment on paypal.com, the order stays in that state.

I now realise I'm not currently using the official Woo PayPal gateway, though I was in March 2015. Both do this (i.e. my current one does, and so did the Woo one at the time). Did something change in the Woo one? (Sorry if I'm wasting your time). If the Woo one changed, was the previous behaviour considered wrong, such that I should notify the developer of my current one?

**Comment by UnholyPhoenix** [comment]
Hi,
im having problems when customers first time load my shop, add item to cart and then when trying to open the cart, the cart becomes empty. When they do it again it starts working (second time always works). Is it a problem with cookies? Any help is appreciated.

**Comment by WPprodigy** [comment]
@UnholyPhoenix Please open up a new support thread, this is not related to the feature request this thread is about.

To save you some time though, this isn't something that belongs on GH at all I'm afraid. This is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by danieltj27** [comment]
Bookmarking; I'll see what I can do to help. Should get to it in next few days at the very least 👍

**Comment by sofyansitorus** [comment]
@mikejolley, I created PR on this.

**Comment by kloon** [comment]
I'm wondering if the removing from cart might be a bit too extreme. Most sites I have purchased on give messages stating the items were updated in the cart since your last visit, so perhaps a notice would suffice here?

**Comment by sofyansitorus** [comment]
Yes I agree with @kloon, removing item form the cart is a bit too extreme. How do you thought @mikejolley? I will update my PR if you agree we do this way,

**Comment by mikejolley** [comment]
Will respond in https://github.com/woocommerce/woocommerce/pull/18772
