### ISSUE TITLE
woocommerce is counting the out of stock products in the loop

### ISSUE THREAD

**Issue by nesbtesh** [woocommerce/woocommerce#17038]
woocommerce is counting the out of stock products in the loop and only showing a few products even do the count is set to 100

http://www.tiendaconceptslife.com/decoracion/decoracion-de-sala/muebles-panama/

**Comment by claudiulodro** [comment]
Looking around the site, I don't think so. On the link you gave, it looks like there are only a few products in stock and in that category. If it was not showing all the products in the category you would have links for page 2, 3, etc. at the bottom.

On [this page](http://www.tiendaconceptslife.com/decoracion/decoracion-de-sala/) there are 100 products shown and links for the next page at the bottom (with 100 products shown on page 2 also). Looks like it's working correctly to me.

**Comment by nesbtesh** [comment]
@claudiulodro yes now its working because I deleted all the products that where out of stock from the database. When there is a product that is marked as out of stock and has 0 in stock is still counts the product in the loop

**Comment by claudiulodro** [comment]
I see. It could be caused by other plugins you have active, by products that didn't import correctly, or by something else. It's impossible for me to tell just by looking at the site. There are some possible causes and solutions in [this issue thread](https://github.com/woocommerce/woocommerce/issues/15455).
