### ISSUE TITLE
Add support for Jetpack floating pin on large image gallery image

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#17046]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1.  Enable Jetpack Sharing on products
2.  Enable Pinterest
3.  Hover a WooCommerce Product Image

## Expected/actual behavior

When I follow those steps, I see...

The floating Pinterest button is positioned absolutely and appears in unexpected locations outside the image depending on which the direction the mouse enters from.  

![](http://cld.wthms.co/KEEm7t+)
http://cld.wthms.co/KEEm7t+
I was expecting to see...

The button should appear in the top left corner of the image.  I'm not sure if this should can be addressed in WooCommerce or if it's something to consider in Jetpack.

**Comment by kloon** [comment]
I tested this on the 3.2 branch with Jetpack 5.4 and was not able to get the Pinterest button to show up over the image, it was only showing in the sharing section underneath the add to cart button http://cld.wthms.co/rIqXcL Not sure if there are any special setup required but I simply enable sharing and then dragged the Pinterest option to enable and checked the product and media boxes.

That being said this is probably something that should be fixed on Jetpack side since it relates to their functionality, this is most likely related to the zoom functionality of the image if I had to guess.

Closing, can reopen if they feel this is something we can fix on our end.
