### ISSUE TITLE
Sorting doesn't appear on custom taxonomies.

### ISSUE THREAD

**Issue by poshwaffle** [woocommerce/woocommerce#17064]
When I create a custom taxonomy i.e. Product Collections which acts like categories and assign some products to this taxonomy, the sorting options don't appear on the archive.

The markup is there in the page source, but nothing displays:

https://cl.ly/3C2I3t2w2x0X

**Comment by claudiosanches** [comment]
> When I create a custom taxonomy i.e. Product Collections which acts like categories and assign some products to this taxonomy, the sorting options don't appear on the archive.

Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

But since is a custom taxonomy should not appear any sorting option on the archive unless you add support for it manually.
