### ISSUE TITLE
Conditional Tag for 1st product behavior in Category or Tag page

### ISSUE THREAD

**Issue by dilipsam123** [woocommerce/woocommerce#17083]
What has been done?
Menu order = 0 (external available products)
Menu order = 1 (external products not available)

Category and Tag pages show products based on Menu Order. So products available are displayed before products not available

What needs to be done?
If the first product in Category or Tag page has Menu Order = 1
then meta tag robots = noindex,follow

This way, I only index category or tag pages that have available products.

**Comment by kloon** [comment]
Not sure I follow what exactly you are after here, would you mind updating the issue with all the details requested initially when you opened it. Also, try and be as descriptive as possible as to what the issue is exactly.

That being said it sounds like you want to make some changes to meta tags based on the menu order, if that is the case this is not something we can add into core as the position is changeable via the wp-admin interface and not everyone would want to use the same scenario you describe.

You are probably best doing this via some custom development in a plugin/theme.

I'll leave this open for another day or two for more feedback just in case I am not understanding what you are trying to achieve.

**Comment by dilipsam123** [comment]
Hi,

1) There are no stock management options for external products
2) To distinguish items in stock, I have set the menu order = 0 (instock) and menu order =1 (for outofstock)
3) I use categories and tags. However, there are categories that sometimes will only have outofstock. 
4) I this case, I want the category and tag pages to follow Google guidlines since this might be of no use to the visitor/user.
5) So, when the first item in the category or tag results has menu order =1 then:

meta tag robots = noindex,follow

I hope you understand, now. Sorry, for being too vague in my first request.

**Comment by kloon** [comment]
Thanks for the more detailed information. Unfortunately, it seems what you are trying to do is custom and you will be better of developing it as a custom plugin.

Adding stock management for external products does not make sense as this is something that is controlled via an external site which will involve complex syncing between the sites that I why I suggest you rather get something developed suited for your own needs.

There are also plans to change the sorting based on the menu_order in the future so I would not rely too much on that https://github.com/woocommerce/woocommerce/issues/13072
