### ISSUE TITLE
wc_update_order_item_meta not updating

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#17097]
Hi,

I'm trying to update an orders `line_item` meta value using `wc_update_order_item_meta`.
The meta value is currently '' (blank) and I want to update it with a text value of 'yes'.
But `wc_update_order_item_meta` doesn't want to update it.
I can delete it using `wc_delete_order_item_meta` and then re add it using `wc_add_order_item_meta` perfectly fine.

You had some caching issues beforehand with `wc_update_order_item_meta` - https://woocommerce.wordpress.com/2017/04/04/say-hello-to-woocommerce-3-0-bionic-butterfly/#comment-3140
Was it resolved?

**Comment by mikejolley** [comment]
No issues any longer; the data store simply uses `update_metadata` core WP function here.

See unit test `test_wc_order_item_meta_functions` for verification that this function is indeed working. I'd guess either usage or prev_value were incorrect, or something else it updating the line item/saving it and overwriting your change, since you're not using CRUD methods.
