### ISSUE TITLE
Use select2 instead of selectWoo

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#17213]
Hello,

The decision of forking select2 into a custom lib should be reconsidered and instead appropriate PR should be made to select2. It is really "annyoing" two have just another library. Even if it is compatible now, it might break things in the future and then just make it even harder for devs to select a lib.

[Reasons ](https://woocommerce.wordpress.com/2017/08/08/selectwoo-an-accessible-replacement-for-select2/) for your fork:

**select2 is "dead"**

This is just not right. "unmaintained since begining of year", really is not a long time. Even when your post was published, there where commits just about 3 months ago. Still, it has slowed down, but this not dead, abandoned, or whatever...  Also the repo is quite active lately.

**select2 two is not accessibe**

Okay,  this really is a problem.

**My suggestion**

- Use selectWoo as long as not everything is sorted
- (Really) get in touch with the select2 authors and negotiate on how WooCommerce can contribute. Maybe there is a some fastlane for Woo's PRs.

**Comment by mikejolley** [comment]
Using Select2 as it stands is not an option. Why are you assuming no one has been in touch with them?

@claudiulodro has been in contact with Select2 contributors. Only recently has it started being maintained actively again. We do plan on raising a PR for them with our fixes and changes we've needed in WC. How long that takes no-one can say.

We had a real problem with accessibility and needed a short-term solution because it was hurting our users. Our fork deals with it. There is nothing wrong with forks. Open source projects are forked all of the time. If our changes make it into Select2 and Select2 is stable again, our wrapper can switch back to Select2 which saves us from maintaining a separate library.

Regardless of whether that happens or not, we're keeping out SelectWoo wrapper in place because it prevents conflicts with other plugins loading in older versions of Select2 which we saw after 3.0 launch.

No one is forcing you to use our library. Both work at the same time without conflicts. Load in the old one if you wish.

Thanks
