### ISSUE TITLE
Customer details are missing in new order admin/customer email

### ISSUE THREAD

**Issue by dominykasgel** [woocommerce/woocommerce#17289]
I did some testing on my several WooCommerce sites and I see that Customer Details in admin/customer new order email are gone. After taking a closer look at customer-processing-order.php I see that this line is not fired: do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );

I took a look at class-wc-emails.php and I see it fails in customer_details() method on line: if ( ! empty( $fields ) ) { }... and I see that $field is NULL in  customer_detail_field_is_valid() function, but... the order has meta data:_billing_email and _billing_phone. Also, I see the same data exists for my user (profile edit page).

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Create a product
2. Buy a product
3. Check admin new order / customer processing order email.

## Expected/actual behavior

When I follow those steps, I see that customer details are gone.

I was expecting to see customer details in an email.

## Isolating the problem
- [x ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/maksimer/wcemails
Site URL: http://localhost/maksimer/wcemails
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.12 (Unix) OpenSSL/1.0.1p PHP/5.6.11 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 5.6.11
PHP Post Max Size: 128 MB
PHP Time Limit: 30000
PHP Max Input Vars: 1000
cURL Version: 7.30.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.79MB
Database Data Size: 1.00MB
Database Index Size: 0.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.48MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wpml_mails: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

page: 5
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
WP Mail Logging: by Christian Zöller – 1.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NOK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by dominykasgel** [comment]
https://wordpress.org/support/topic/customer-details-missing/#post-9586622
https://wordpress.org/support/topic/new-order-notification-customer-email-missing-after-update-to-3-2-0/#post-9599218
https://wordpress.org/support/topic/customer-details-removed-from-new-order-email-in-3-2/#post-9603194
https://wordpress.org/support/topic/customer-details-not-appearing-in-order-emails-since-3-2-0/page/2/#post-9596368

**Comment by mikejolley** [comment]
There is no section - the details are still there though. See this:

![the emails](https://user-images.githubusercontent.com/90977/31830173-40cad2be-b574-11e7-8330-5a52d3ad0563.png)

**Comment by rv8820** [comment]
Hi Mike,

We have the same issue.  We do not display the billing and shipping address in the email notification since the product is meant to be picked up from the store.  We have overridden the templates/emails/email-customer-details.php to display the Customer details in the email notification.  This has been working until the recent update.  We are now using 3.2.1 version of WooCommerce.

Please see screenshots below.

![woocommerce-missing-customer-details-before](https://user-images.githubusercontent.com/343309/31872991-de81dd9c-b7f2-11e7-8309-76d21a7f2fef.jpg)
![woocommerce-missing-customer-details-after-upgrade](https://user-images.githubusercontent.com/343309/31872992-deb92798-b7f2-11e7-95ad-68c6baee7240.jpg)

**Comment by samholguin** [comment]
We are having the same issue.

**Comment by AbdulSamadKt** [comment]
I also have same issue and I added the below code in functions.php 

function woocommerce_email_customer_details( $order ) {
  
    $phone= $order->get_billing_phone();
    $email=$order->get_billing_email();
    ?>
     <h2><?php _e( 'Customer details', 'woocommerce' ); ?></h2>
     <ul>
       <li><strong><?php echo wp_kses_post( 'Email address'); ?>:</strong> <span class="text"><?php echo wp_kses_post( $email ); ?></span></li>
    <?php if($phone) { ?>
         <li><strong><?php echo wp_kses_post( 'Phone'); ?>:</strong> <span class="text"><?php echo wp_kses_post( $phone ); ?></span></li>
      <?php } ?>
     </ul>
    <?php

};

add_action( 'woocommerce_email_customer_details', 'woocommerce_email_customer_details', 10, 4 );

**Comment by mikejolley** [comment]
@rv8820 if you change/remove templates, it would be up to you to add the email to your custom template. Hiding addresses is a customisation we cannot account for here.

Everyone else, to reiterate: yes the **customer details section is gone**, but the **information from it is still in the email**. It has simply moved. There is no issue here. Customise the email templates if you want things presented differently.

**Comment by GitHub2BS** [comment]
WP 4.8.1 & WC 3.2.1

Hi Mike.
Can I please indulge for a total Newbie here please, i have the above problem re: no customers details in Admin Order. 
My issue , (to me) appears to come from the fact that my email templates are not updating with each update (currently @ ver 2.4) because i get i notice to say the theme has overridden the template as so : 
"This template has been overridden by your theme and can be found in: /woocommerce/emails/admin-new-order.php." 
 My end of my current template contains the following lines, i removed line No.3 and tested, but it Did Not fix the issue :  i.e. still no customer email or Tel. No.

code removed for forum display. 

1.  php do_action( 'woocommerce_email_after_order_table', $order, true, false 

2.  php do_action( 'woocommerce_email_order_meta', $order, true, false 

3.  php do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text 

4.  php do_action( 'woocommerce_email_footer' 

Can I please ask for your help with the the 2 ways i can solve this issue I think below

1. Edit existing template in theme
2. Replace old templates with current/latest templates, and where will i find them

Just thought of a 3rd way :-)  , how can i make the templates update automatically with each sys update

Sorry to be a pain, but I Really do need to fix this problem ... with your help , and I am Stumped !! 

Thank You

**Comment by GitHub2BS** [comment]
Sorry Guys.
Re, above ... Although the Email templates say they are overridden by the theme, they are actually identical, maybe just passed on, exactly as they are.

Thought this might be important re: above request for support

Cheers

**Comment by zaehlpixel** [comment]
We're on 3.2.6 and the problem is still here! What can we do??

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17289#issuecomment-338961276
