### ISSUE TITLE
Setup Wizard Redirect Back to Site After Jetpack Signup

### ISSUE THREAD

**Issue by bluehiveinteractive** [woocommerce/woocommerce#17296]
Brand new vanilla WordPress install (ver 4.8.2) and vanilla WooCommerce install (ver 3.2.1) Upon installing WooCommerce I went through the setup wizard. I got to the step where I could enable live shipping and sales tax. I left the options on and was asked to login or create a new WordPress.com account. I chose the option to create a new account. When the account creation was completed I was redirected back to the new WooCommerce install at https://www.example.com/wootest/wootest/wp-admin/?page=wc-setup&step=activate&from=wpcom NOTE: how it included the subfolder twice in the URL /wootest/wootest/ I'm not sure if this a WooCommerce hiccup or if it's coming from WordPress.com or even Jetpack itself....

**Comment by jeffstieler** [comment]
Looks like the issue is coming from the use of `site_url()` here: https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-setup-wizard.php?utf8=%E2%9C%93#L1579

We should probably use `get_admin_url()` and explicitly form a URL to the activate step within the setup wizard.
