### ISSUE TITLE
order action missing in 3.2: "resend order emails" -> "resend completed order" TO CUSTOMERS

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce#17309]
on order details page(post.php?post=xy&action=edit) in widget "order action" inside the dropdown menue there was a option to resend a completed order to the customer, this option in needed and disapeared since 3.2.x

you have "email order details to customer", "resend new order", ...
but no "resend completed order" TO CUSTOMERS.

To sent email to customer again this is needed, to sent to admin in not needed!
-
Issue disscussed also here:
@mikejolley
"resend completed order" is also removed. I need to resend if a customer does not get email without trigger all hooked functions on order completed status. 
Also if the tracking code is added and i want to resent the order, it is needed (i externaly get the tracking code days later, but the payment gateway needs wc-completed status, to pay me my money)

to go from completed to an other status, save and back and save for only sending email order completed again is way to much.

@all the sent to admin function can be easy added back:
https://gerhardpotgieter.com/2017/10/13/woocommerce-3-2-add-back-option-to-resend-admin-order-email/

**Comment by Tobias-Conrad** [comment]
May we need an option to resend mail to customers of the current status. Only one instead of for each order status.

**Comment by mikejolley** [comment]
There are two options in that dropdown on the edit order page:

- Resend order to customer
- Resend order to admin

Use those. They include all details on the order, and won't trigger any additional hooks. Since they are non-event/status based, the two options are clearer.

**Comment by factoryunlock** [comment]
@Tobias-Conrad did you find a workaround? 

When using what mike suggested, an "order receipt" email is sent and not the order completion email. In a similar boat as you

**Comment by dcelsey** [comment]
I use Resend Completed Order regularly when customers have lost their download links or want a copy of the receipt. 

The 'email invoice/order details to customer' option does NOT send the same email. I spent a lot of time getting the Order Confirmation email the way I wanted it. Can't tell you how frustrating it is to have functionality that works and that I need taken away. Makes me feel un-important as a Woocommerce user/customer.

![order receipt email](https://user-images.githubusercontent.com/9269976/32754554-045cf7e2-c886-11e7-9ea2-857cebd9cf43.JPG)
![order details email](https://user-images.githubusercontent.com/9269976/32754566-0e3d94d8-c886-11e7-906b-70e292fa0164.JPG)

Choices at the moment are to not take the latest release (only really a short term option), try to recreate the option via customization or try to customize the order details email to look like the receipt email.

**Comment by factoryunlock** [comment]
Or you can re-mark it as "in process" then RE-MARK again as completed xD

**Comment by Tobias-Conrad** [comment]
a workaround i use:
write a note:
your tracking code is below 
or
your download is below 
or
your access is below 
if order is closed/completed all needed data will be below note in the email.

please @Mike see the missing email option.

**Comment by mikejolley** [comment]
Applying customisations to the invoice template is the same process as all other email templates. Just do it there too?

Again, event based 'resend' does not make sense because it presents invalid options to admin users such as 'resend refunded email' when the order is not even refunded. This is unlikely to be reverted.

**Comment by dcelsey** [comment]
Yes I can customize the customer-invoice template. But I don't use invoices so that doesn't feel like a great solution.  Plus I have to customize it to be an exact duplicate of the order completed email, so I have two templates in my child theme to maintain instead of one.

And I could switch the order to processing and back to completed, but I deliver e products so I don't have orders in the processing status so that's weird from a business process viewpoint as well.

I think what I am expressing here is a bigger frustration around changes to things in the name of improving them that impact existing installations. For example the order complete email was recently changed to move the download links to the top, so effectively all of the products are listed twice. My order complete email is well bedded in and works great and I don't want this change, but I get it when I upgrade and then have to go digging around to customize the change back out. Likewise when upgrading to v3 there were significant changes to the html/css around product archives. I can see the improvements but things like changing the product title from h2 to h3 messes up anyone who has custom css. That just a couple of examples - I feel like it is getting less and less common for me to be able to just take a release of woo and associated plug ins without having work to do.

Improvements are great especially for people who are just getting started with a new install, but your established client base are using Woo because they have businesses to run and need stability and continuity as much as they need improvements and changes.

For me its just extra work because this is what I do, but for my clients I have to explain why there is extra work and expense just to take the latest version of Woo.

I would love for Woo to be the go to choice for eCommerce but things like this push people towards other platforms that claim to remove a lot of the technical complexities.

Anyway - way off topic for this issue, but if there is anyone at Woo who is prepared to hear some genuine feedback from a  customer I would be happy to discuss this further offline.

**Comment by mikejolley** [comment]
> Yes I can customize the customer-invoice template. But I don't use invoices so that doesn't feel like a great solution. Plus I have to customize it to be an exact duplicate of the order completed email, so I have two templates in my child theme to maintain instead of one.

Ignore the naming. It's likely this email will be renamed in the future, but for now and BW compatibility it's been left alone.

> For example the order complete email was recently changed to move the download links to the top, so effectively all of the products are listed twice

Things like this have issues logged (with valid arguments for changing behaviour) e.g. in this case there was a lot of feedback saying customers could not find the download links when buried within the items table. We don't make this stuff up - it's feedback from store owners.

Maybe you could try being involved in these discussions before changes are made if you're concerned? Let's not forget, all changes are logged and coded here in the open, and we have beta testing for a reason. Dev blog announces large changes too.

I'm going to close out comments on this issue. I feel we've justified this change enough,  and we're way part the point of reverting the change.

**Comment by mikejolley** [comment]
> Anyway - way off topic for this issue, but if there is anyone at Woo who is prepared to hear some genuine feedback from a customer I would be happy to discuss this further offline.

cc @msdesign21
