### ISSUE TITLE
Paypal IPN sometimes not triggering webhook v1 webhooks

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#17366]
We have a few customers where the Paypal IPN is updating the view in the woocommerce console but not sending the webhooks required for us to see the update.

When the user clicks save on the order, all the correct information is then sent

**Comment by mikejolley** [comment]
There isn't a lot of information to go by there for us - we at least need steps to replicate an issue to take any kind of action, as well at the status report etc, what versions those sites run, what webhooks are setup etc. It would be helpful if you did some debugging of your own to narrow a problem down - GitHub should really be for reporting issues in detail, rather than requesting support :)

Webhooks run on order status changes, which PayPal does the same as any other action in admin. The logs should reveal is the hooks were sent/tried to send, and the server php error log can indicate if there were problems. If the order had no status update, or if the order notes are missing stating that the order status was changed, the webhook would not have fired.

I'll point out, Webhooks are currently getting a refactor in https://github.com/woocommerce/woocommerce/issues/12439 so you may want to follow this - it will improve the way webhooks get logged to aid with debug, and should improve reliability. I'd say if there is a problem, this update will likely help. 🎆 We're on it.

I'm closing this out due to lack of actionable details, but if you do manage to narrow the problem down or can provide steps to replicate, let me know.

Thanks
