### ISSUE TITLE
WC3 Flex slider removes thumbnail filter content

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#17388]
Anything added to `woocommerce_single_product_image_thumbnail_html` filter gets removed when Flexslider loads.

Reproduce:

`add_action( 'woocommerce_single_product_image_thumbnail_html', function)(){ return 'FLEXSLIDER HAS LOADED' }, 999 );`

Create a product with a gallery, load in flexsldier via theme_supports

**Comment by yratof** [comment]
Looks like @jameskoster noticed with this issue: [10721](https://github.com/woocommerce/woocommerce/issues/10721)

But that specific commit failed: [b0f01bb](https://github.com/woocommerce/woocommerce/commit/b0f01bbe635b049dbd10004805962c053b2e31c8)

**Comment by mikejolley** [comment]
`woocommerce_single_product_image_thumbnail_html` is not an action, it's a filter. Your example code is very wrong :p 

I'm not sure what you mean by something failed either; `woocommerce_single_product_image_thumbnail_html` is present in core as it should be. It filters the images in both the image template and thumbnails template.

If you add extra content via this filter, the content is not removed, it's just hidden because of flexslider styles. I think this is to be expected - it's a gallery after all. Your content is inside the gallery `figure` element and can be seen in the source/inspector.

If you want content outside of the gallery, `woocommerce_product_thumbnails` would be more appropriate, or a new hook. This one is not suitable. If thats needed, raise a PR with justification please so it can be considered.

Thanks

**Comment by yratof** [comment]
Ok, looking deeper into this, i'm seeing that the same filter is used twice:

`/templates/single-product/product-image.php:58`
has
 `echo apply_filters( 'woocommerce_single_product_image_thumbnail_html', $html, get_post_thumbnail_id( $post->ID ) );`

and

`/Users/drivdigital/sites/somab2c/public/wp-content/plugins/woocommerce/templates/single-product/product-thumbnails.php:44
has
 `echo apply_filters( 'woocommerce_single_product_image_thumbnail_html', $html, $attachment_id );`

I was using the filter `woocommerce_single_product_image_thumbnail_html` to add a sales ribbon the the product image. 

When flex slider loads, it applies this filter a few times for each image in the gallery, which makes sense, I imagine the filter isn't designed for attaching new html to images. Flexslider makes your parent div 100% * however many images there are, so an absolute sales banner in the top right of an image vanished into the flexslider parent's position relative overflow hidden etc.

I also, admittedly, found an instance of flexslider being enqueded from the pre-30 WC, which was, after the new theme_support version moved the html offscreen, replaced it with nothing.

**Comment by mikejolley** [comment]
Yeah, woocommerce_single_product_image_thumbnail_html does indeed apply to all images. All images are loaded into flexslider in the same way.
