### ISSUE TITLE
Permalinks when putting everything under /shop/...

### ISSUE THREAD

**Issue by ekussberg** [woocommerce/woocommerce#17411]
Hey there, i have had a headache right now, because any of urls like logout, orders, order-received didn't work, because in my WP they are all children of Shop page. Is there a fix for this permalink bug?

Here is one example:
Not working: /shop/my-account/customer-logout/?_wpnonce=37ce093038
Works: /my-account/customer-logout/?_wpnonce=37ce093038

**Comment by mikejolley** [comment]
After changing the parent of the my account page to shop, you need to go to settings > permalinks and save. This should clear up any 404s. Just tested and confirmed this fixes.

In general, we don't recommend setting child on shop due to risk of conflicts like this (shop is a product archive). By default, all of those pages are top level.

Thanks
