### ISSUE TITLE
Product images & gallery not visible with 21-30 product variations

### ISSUE THREAD

**Issue by Looneycorn** [woocommerce/woocommerce#17426]
Running Storefront & Galleria child theme
Woocommerce 3.2.1

Odd issue:
Adding anywhere between 21 and 30 product variations to a product makes the gallery and product image on the product page invisible.
The main image will still be visible on the shop page.
Less than 21 or more than 30 variations makes the image and gallery visible again.

Happens with all themes.
Deactivated all additional plugins, css, scripts, etc. Makes no difference.

**Comment by claudiulodro** [comment]
I wasn't able to reproduce this. Are there any JavaScript errors in the browser's console? Do the variations have their own images uploaded, or is it just the one main product gallery for everything?

**Comment by Looneycorn** [comment]
Thanks for the reply.

The variations all have separate images, but the error comes up either way.

I tried different browsers, and noticed that the error is only happening in Chrome. It also only happens on the Desktop site. If I browse it with Chrome on the responsive mobile version, the images are showing just fine.

I have attached the Chrome Javascript log. There are a few issues.

If you need any further info, please let me know.


[Javascript.log](https://github.com/woocommerce/woocommerce/files/1423558/Javascript.log)

**Comment by Looneycorn** [comment]
Just to add to this:

If I go above 30 or below 21 variations, there are no Javascript errors.

**Comment by mikejolley** [comment]
@claudiulodro We have different logic if there are more than 30 variations. Test with different `woocommerce_ajax_variation_threshold`.

**Comment by mikejolley** [comment]
@Looneycorn I have a theory.

What looks to have happened is you've hit a PHP memory limit ~21 variations in. From 21-30 if this happened, the footer of the site may not load. This would prevent scripts, like jQuery, loading if enqueued in the footer.

As soon as you go over 30 variations, we have different logic (my last comment) which won't load all variations at once on the same page.

Since we cannot replicate this, I don't think we need to keep an issue open (it seems specific to your environment), but next steps would be to:

1. Look at either the PHP error log on your server, or see if something was logged in WC > Status > Logs. Since 3.2 we log fatal errors.

2. Increase the php memory limit if it's a memory exhausted error https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/

3. Or act on any other fatal errors (paste here and I can look if it's not memory).

4. Or reduce the `woocommerce_ajax_variation_threshold` filter to 20.

```
add_filter( 'woocommerce_ajax_variation_threshold', 'change_woocommerce_ajax_variation_threshold' );

function change_woocommerce_ajax_variation_threshold() {
return 20;
}
```

let me know if none of that helps.

**Comment by Looneycorn** [comment]
Just to add to this, if anyone else comes across a similar error:

I used the code, which fixed the product pages, but I still had similar issues with bundled products, as well as other javascript related errors throughout the page.
Turned out that it was caused by the Cloudfare CDN and their Rocket Loader feature, which did mess with the javascript.

Thanks again for the help.
