### ISSUE TITLE
Deprecated function `WC_Cart::get_cart_url` notice

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#17439]
User in 742886-zen is seeing the following notice in PHP server error log:

`[27-Oct-2017 01:10:35 UTC] The WC_Cart::get_cart_url function is deprecated since version 2.5. Replace with wc_get_cart_url.`

The notice appears with WooCommerce 3.2.1 and Twenty Seventeen theme activated while collecting payment via PayPal Standard. 

Full error log could be downloaded [here](https://cloudup.com/cCnuVSghYFl).

**Comment by pmciano** [comment]
Reported in 750747-zen

**Comment by mikejolley** [comment]
@juliaamosova A few of us just checked and we make no such calls to the deprecated method. It would have to be an extension or customisation of some sort on the site.

You can check this to see no usage of the deprecated method https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=get_cart_url&type=

This is also not being logged on test sites.

(we cannot view the ZD ticket to look for other clues)

**Comment by juliaamosova** [comment]
Thanks for the explanation @mikejolley. I will follow-up with the user and will look into other plugins/themes that may be causing it.

**Comment by cphactualite** [comment]
Hi there..!
-->site error "cphactualite.com"any visitor can see the error on the site, why the error is posted in public?

--translate.google-- French to English
Hi there..!
Wordpress engineers had told me that I needed more memory on my server, so that wordpress works correctly without error, they told me, if I access wp config (.....) Etc , in order to change the memory from 256M to 512, so I used a Wp plugin, to modify it, from 256M to 512, after having modified it on the plug-in, the errors persist, so I recontacted the support of Wp (the Wp engineers), they asked me to disable the plugin, after deactivating the plugin, all the errors are gone, the errors of the plugin jetpark, vaultpress do not show anymore, only a "woocomerce" error, in french
 Notice: WC_Cart::get_cart_url est obsolète depuis la version 2.5 ! Utilisez wc_get_cart_url à la place. in /htdocs/wp-includes/functions.php on line 3831


French
Bonjour..!
Les ingénieurs de Wordpress m'avaient dit, qu'il me fallait plus de mémoire sur mon serveur, pour que wordpress marche correctement sans erreur, ils m'ont dit, si j'ai accès wp config(.....)Etc, afin de modifier la mémoire de 256M à512, alors j'ai utilisé un plugiciel Wp, pour le modifier, de 256M à 512, après l'avoir modifié sur le plugiciel, les erreurs persistent, alors je recontactais le support de Wp(les ingénieurs Wp), ils m'ont demandé de désactiver le plugiciel, après avoir désactivé le plugiciel, tous les erreurs sont disparus, les erreurs de plugiciel jetpark, vaultpress n'affichent plus, seulement une erreur "woocomerce", en français:  
Notice: WC_Cart::get_cart_url est obsolète depuis la version 2.5 ! Utilisez wc_get_cart_url à la place. in /htdocs/wp-includes/functions.php on line

**Comment by cphactualite** [comment]
"server or hosting"

**Comment by cphactualite** [comment]
so I have to disable the woocommerce plugin

**Comment by cphactualite** [comment]
if the error persists

**Comment by wolviex** [comment]
For anyone who's looking:

Some themes use the syntax
`$woocommerce->cart->get_cart_url()`
and some use
`WC()->cart->get_cart_url()`
This string needs to be replaced with
`wc_get_cart_url()`

I found this in both my theme's functions.php, and in my theme-specific includes/boc_framework.php
for convenience:
`grep -R -n "cart->get_cart_url"` 
Will locate the offending code, when run within your theme directory.

**Comment by mackr2015** [comment]
Thank you very much wolviex.

After spending about 4hopurs looking where this is outputed I have finally found that in my theme folder inc/template-tags.php  this was outputed as deprecated verzion WC()->cart->get_cart_url() .

Now I can finally continue with coding....
