### ISSUE TITLE
Rest API - Create Order Issue

### ISSUE THREAD

**Issue by saurabhj91** [woocommerce/woocommerce#17453]
Hi Team,

I am creating an order using API. Below is the order data

```
{
    "payment_method": "cod",
    "payment_method_title": "Cash on Delivery",
    "set_paid": true,
    "status": "processing",
    "customer_id": 142,
    "billing": {
        "first_name": "Saurabh",
        "last_name": "Jain",
        "company": "",
        "address_1": "some address",
        "address_2": "",
        "city": "Mumbai",
        "state": "MH",
        "postcode": "400080",
        "country": "IN",
        "email": "someemailid@gmail.com",
        "phone": "1234567890"
    },
    "shipping": {
        "first_name": "Saurabh",
        "last_name": "Jain",
        "company": "",
        "address_1": "some address",
        "address_2": "",
        "city": "Mumbai",
        "state": "MH",
        "postcode": "400080",
        "country": "IN",
    },
    "line_items": [
        {
            "product_id": 1999,
            "quantity": 4
        }
    ]
}
```
In the response i get "_Unexpected 'o'_", but when i check wp-admin the order is created. Also the stock quantity of the product is not reduced.

**Comment by claudiosanches** [comment]
It's missing a lot of details on this issue, there is not all the steps that from the issue template, and not the full response message.
Your JSON has an incorrect syntax too.

I just tested your data, just removing the `customer_id` since there is none with the same ID in my environment, and I could create the order:

![screenshot from 2017-10-27 15-26-06](https://user-images.githubusercontent.com/1264099/32171524-90686e2e-bd5f-11e7-9463-3120e369ddd3.png)

So I can't see any issue with WooCommerce, probably an issue on your side caused by another plugin.

**Comment by saurabhj91** [comment]
Hey, 

Apologies for not following the template. I checked the same thing on different environment, it was working fine.

Thank you for the help.
