### ISSUE TITLE
Can't use pay_action with ajax

### ISSUE THREAD

**Issue by bruno-rodrigues** [woocommerce/woocommerce#17456]
Hello,

I know that a I can use `checkout` with ajax, but I did not see any way to use `pay_action` with ajax.

In checkout I do have the following available: 
`class-wc-checkout.php:810`
```
if ( is_ajax() ) {
    wp_send_json( $result );
} else {
    wp_redirect( $result['redirect'] );
    exit;
}
```

But in `class-wc-form-handler`'s pay action I do not see how I can return wp_send_json:
```
$result = $available_gateways[ $payment_method ]->process_payment( $order_id );
// Redirect to success/confirmation/payment page
if ( 'success' === $result['result'] ) {
    wp_redirect( $result['redirect'] );
    exit;
}
```

Can I consider this an issue? If so, I can help with a PR since I've make some changes locally already.

**Comment by mikejolley** [comment]
Our pay page does not use AJAX. It has fixed amounts and simply handles payment. No totals update, no address is collected, and no shipping etc is calculated.

We don't want to change this behaviour right now because of https://github.com/woocommerce/woocommerce/issues/10672 which will change the way these pages and endpoints work. Refactoring the pay page will be part of that effort.

Thanks :)

**Comment by NielsdeBlaauw** [comment]
For anyone wondering, this is still an issue in WooCommerce 4.2.1.

You can work around this with the following snippet:

```php
add_filter(
	'woocommerce_payment_successful_result', function( $result ) {
		if ( is_ajax() ) {
			wp_send_json( $result );
			exit;
		}
		return $result;
	}
);
```
