### ISSUE TITLE
Duplicating product does not clone custom taxonomy terms

### ISSUE THREAD

**Issue by tc33** [woocommerce/woocommerce#17487]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Duplicate any product with terms set in one or more custom taxonomies. 

The cloned product will have no terms set for that taxonomy. I'd expect terms to be cloned too. This was the functionality in previous versions. I just checked this on version 2.6.7 which I had a copy of to hand, and the functionality works as expected there.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Our CRUD classes do not handle `custom taxonomies` and we have no plan to include this functionality. Only core WC data is duplicated; so product data, product meta data etc.  Think of it as a **whitelist** of data we want to copy across.

2.6.x did not have CRUD classes which is why you see it working there - it just blindy duplicated everything. 

For custom taxonomies, depending on how these are implemented, `woocommerce_product_duplicate_before_save` action can be used. This gives you the new object (unsaved, no ID) and old object. With this you can save it manually, and then assign terms as needed using whatever methods you have in place.

If you're using CRUD objects in your code implementing these custom taxonomies and think an action would be more useful elsewhere, e.g. the `__clone` method of products, please send a PR and we'll consider including it in core.

Thanks

**Comment by Tofandel** [comment]
Hmm... That's a bit odd that there is no `woocommerce_product_duplicate_after_save` hook

The id not existing yet when the hook is triggered

So you need to save it during the hook (which defeats the purpose and could break things if plugin hooks on this and expect no id to be set)

So this is what I use to copy all the terms of my custom taxonomies

```php

add_action( 'woocommerce_product_duplicate_before_save', function ( WC_Product $duplicate, WC_Product $product ) {
    $duplicate->save();
    foreach ( [ 'material', 'brand' ] as $taxonomy ) {
        $terms = get_terms( $product->get_id(), $taxonomy );
        wp_set_object_terms( $duplicate->get_id(), $terms, $taxonomy );
    }
}, 999, 2 );
```
