### ISSUE TITLE
term description - wp_kses_post

### ISSUE THREAD

**Issue by britner** [woocommerce/woocommerce#17509]
This is in regards to adding wp_kses_post to the term description output here:
https://github.com/woocommerce/woocommerce/blob/9e29ed0bda5c238be3aebf66927b32284d96ec8c/includes/wc-template-functions.php#L689

By adding wp_kses_post() it will strip out simple inline CSS like background-image. 

I just wanted to clarify that it was/is the intent to strip down what can be output through the terms description box. In my experience, many people treat the category and tag description boxes like page or post content. Using html and shortcodes in those areas. 

Thanks for the response and clarification.

Ben

**Comment by spencerfinnell** [comment]
https://github.com/woocommerce/woocommerce/pull/17499

**Comment by britner** [comment]
Thanks @spencerfinnell but that only referenced the shop page output. Which I saw got changed in prep for 3.2.3 but this is in regards to the term description.

**Comment by im-Vad** [comment]
Hi.
I did not understand.
To do what?
Help !!!

**Comment by im-Vad** [comment]
Delete a row
echo '

' . wp_kses_post( $description ) . '
';
Nothing came, the problem remained.
Instead of a slider, here it is:
var htmlDiv = document.getElementById("rs-plugin-settings-inline-css"); var htmlDivCss=""; if(htmlDiv) { htmlDiv.innerHTML = htmlDiv.innerHTML + htmlDivCss; }else{ var htmlDiv = document.createElement("div"); htmlDiv.innerHTML = ""; document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]); } setREVStartSize({c: jQuery('#rev_slider_6_1'), gridwidth: [1240], gridheight: [70], sliderLayout: 'fullwidth'}); var revapi6, tpj=jQuery; tpj(document).ready(function() { if(tpj("#rev_slider_6_1").revolution == undefined){ revslider_showDoubleJqueryError("#rev_slider_6_1"); }else{ revapi6 = tpj("#rev_slider_6_1").show().revolution({ sliderType:"hero", jsFileLocation:"//www.do-mishka.com/wp-content/plugins/revslider/public/assets/js/", sliderLayout:"fullwidth", dottedOverlay:"none", delay:9000, viewPort: { enable:true, outof:"wait", visible_area:"80%", presize:false }, visibilityLevels:[1240,1024,778,480], gridwidth:1240, gridheight:70, lazyType:"smart", shadow:0, spinner:"off", autoHeight:"off", disableProgressBar:"on", hideThumbsOnMobile:"off", hideSliderAtLimit:0, hideCaptionAtLimit:0, hideAllCaptionAtLilmit:0, debugMode:false, fallbacks: { simplifyAll:"off", disableFocusListener:false, } }); } });	/ready/

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17533
