### ISSUE TITLE
Shipping calculator not displayed on Cart page

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#17526]
[Originally noticed here](https://wordpress.org/support/topic/woocommerce-3-1-2-breaks-shipping-calculator-on-cart-page/).

In some scenarios the shipping calculator does not display on the Cart page when it should.

Here is how I reproduced:
1. Enable "shipping calculator on Cart page" setting.
2. Have a Flat Rate and Local Pickup shipping methods.
3. Set default customer location to "No location by default".
4. Browse in incognito mode.

**Comment by chris-brighton** [comment]
Looks like a variant of this bug still persists through 3.2.3 (but was fine in 3.1.2)

We have a situation where:
(1) Shipping Calculator on Cart option is *on*
(2) Customer default location is "geolocate"
(3) Shipping locations is "Ship to Specific Countries only" (let's call them Countries A, B, C)

Now if the site user surfs from Country A, the shipping calculator does show on cart page.
However, if the site user's IP address is from Country D (not a shippable country), the shipping calculator does *not* show. This should not be the case.

The shipping calculator should always show regardless of geolocation, because the Country D site user might want to ship to Country A (because he's actually from Country A and is currently in D, or he's on a VPN through Country D, or he's a relative of someone in Country A).  The behavior in 3.1.2 was that the calculator always showed, regardless.

**Comment by eve1234** [comment]
I am experiencing this issue with store front. I also switched to default themes like Twenty Thirteen and all those but problem persists. It should either calculate shipping accordingly when user selects any shipping method or calculate it when user clicks on 'calculate shipping'. But instead returns -

https://www.domain.com/basket/#

Please, help.

Thank you
