### ISSUE TITLE
Theming: Single product page for non-supported themes

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#17551]
If the theme does not support WooCommerce we should:

- Avoid our own single template and wrappers
- Try to make use of theme's single.php template
- Ensure non-product related parts are removed if possible
- Filter page titles to display relevant text/what is being shown.
- Filter content to show product data.

**Comment by claudiulodro** [comment]
After testing a bunch of themes, these are 2 are the only issues I see from theme to theme:

Sidebar gets shoved under the product. (Doesn't happen with every theme, so we can't just hide the sidebar, but maybe there's a good heuristic)
<img width="786" alt="screen shot 2017-11-07 at 1 58 55 pm" src="https://user-images.githubusercontent.com/7317227/32520361-93d4900e-c3c4-11e7-8a52-f856433fe049.png">

----------

No padding. Content is flush with the left side of the screen.

<img width="1003" alt="screen shot 2017-11-07 at 1 59 52 pm" src="https://user-images.githubusercontent.com/7317227/32520385-ab5d3064-c3c4-11e7-92b2-df6af82b20c2.png">

---------

Bonus: I don't think we'll get WooCommerce looking good on the p2 theme :P 
<img width="1116" alt="screen shot 2017-11-07 at 2 01 29 pm" src="https://user-images.githubusercontent.com/7317227/32520423-cdb74cb2-c3c4-11e7-8d86-5da7e8ded27e.png">

**Comment by claudiulodro** [comment]
Also we probably want to enable the gallery slider by default for these themes. Something like this  screenshot is confusing because I thought it was a gallery slider but clicking on an image opens the image as a new page instead of a lightbox.
<img width="990" alt="screen shot 2017-11-07 at 2 22 56 pm" src="https://user-images.githubusercontent.com/7317227/32521177-61352aa2-c3c7-11e7-9e55-3d95f681a6d5.png">

**Comment by mikejolley** [comment]
Is this using our template though? Or their page template?
