### ISSUE TITLE
User Cannot Edit Display Name

### ISSUE THREAD

**Issue by turtlepod** [woocommerce/woocommerce#17606]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. In My Account Page the welcome message are 

"Hello {name} (not {name}? Log out)"

The {name} is using display name.

2. But when they edit their profile via "Account Details" (endpoint), the options are only "first name" and "last name"

So, they will never able to change their display name.

Possible solution: also update display name, maybe using "{first name} {last name}" format on account details save action.

Use case: miss type my name as "Favid" when I register, and try to update my name via account details buy the display name in dashboard message remain the same.

**Comment by mikejolley** [comment]
How about just not using display name on account pages?

**Comment by claudiosanches** [comment]
> Possible solution: also update display name, maybe using "{first name} {last name}" format on account details save action.

This is not an option, since we had trouble before: https://github.com/woocommerce/woocommerce/issues/15020

But since display name can be used in comments and other public locations, probably easier including a new option.

**Comment by mikejolley** [comment]
@claudiosanches I mean on private account pages use actual name. Display name is for public places.

**Comment by claudiosanches** [comment]
@mikejolley still this not covers if your name is wrong, since we don't allow to edit the display name once that is not an email.

Not to mention the behavior of saving a display name is not the same in all places:

https://github.com/woocommerce/woocommerce/blob/c03520a6614dc364229cd94bbeebab468d84ff0c/includes/data-stores/class-wc-customer-data-store.php#L113-L117

https://github.com/woocommerce/woocommerce/blob/c03520a6614dc364229cd94bbeebab468d84ff0c/includes/class-wc-checkout.php#L884-L887

Both uses first and last names, but on My Account it's different:

https://github.com/woocommerce/woocommerce/blob/c03520a6614dc364229cd94bbeebab468d84ff0c/includes/class-wc-form-handler.php#L207-L208

And another problem is that in none of that places are considered formatting for some languages/countries, like we do in:

https://github.com/woocommerce/woocommerce/blob/c03520a6614dc364229cd94bbeebab468d84ff0c/includes/class-wc-order.php#L788-L796

**Comment by widianto** [comment]
Hi guys, I want to contribute to woocommerce project. This is my first time.

So what's the possible best solution to solve the problem? 
1. Providing edit display name on my-account edit page? (You say this is allowed by Wordpress, right?
2. Or, displaying $user->first_name on Dashboard page?

Need guiding. Thanks!

**Comment by KoolPal** [comment]
Hi all,

My 2 cents.

Perhaps Woocommerce should pick a thing or two from Amazon considering their headstart in ecommerce? 

Woocommerce should emulate best practices from elsewhere and add value by fixing the painpoints from other platforms. Then Woocommerce will truly shine!

In Amazon, Login & Security ( Name, email & password) section can be equated with Woocommerce Account Details page. Add display name field and make it editable in this Account Details page and indicate that this would be used for reviews, etc. Do not modify this display name on every order. This will address the concern of a B2B Store Owner who used the display name to store the Company Name. [https://github.com/woocommerce/woocommerce/issues/15020#issuecomment-302226494](url)

Show Account First Name / Last Name in Dashboard Name. This will not get modified by changes in Billing First Name / Last Name during any order checkout.

In Amazon changes to billing and shipping address DO NOT modify the customer's account details. This should be replicated in Woocommerce

For reviews, Amazon permits change in display name. This could be explored for replication in Woocommerce

Thanks.

**Comment by mikejolley** [comment]
Hi @widianto 

It looks like we need to (based on https://github.com/woocommerce/woocommerce/issues/17606#issuecomment-342486049)

1. Leave the `is_email` display name handling code in place to prevent these being leaked
2. When setting display name, format it like we do in get_formatted_billing_full_name so translations can change how name is formatted
3. Change the display name setting in class-wc-customer-data-store.php to avoid setting to first/last name
4. Add display name to the customer class, data store, and as a new field on the account edit page.

Thats should handle everything.

**Comment by KoolPal** [comment]
@mikejolley I am curious by your obvious disregard for my suggestion. Is there some criteria by which my suggestion failed to elicit a response?

**Comment by mikejolley** [comment]
@KoolPal My suggestion is inline with your suggestion.

**Comment by douglsmith** [comment]
Keep in mind that the display name is also used to represent the user in WordPress comments and other plugins like bbPress and BuddyPress. We need to make sure any changes to the display name are okay with those uses too.

WordPress has a dropdown menu that only allows setting the display name to the username, first name, last name, first + last, or last + first. I don't know why they have those limitations, though. It doesn't stop spoofing someone because a user could just change their first or last name as desired.

**Comment by widianto** [comment]
@mikejolly and all, thanks for clearing out.

Again, this is my first ever contribution to open source project. I hope I can understand how to make contribution correctly and following good practices.

First, current flow are:
- Display name created automatically form part of user email when user registering for new user (only providing email and password)
- So on any edit account page, user will have display_name in place, but empty First Name, Last name

My fixes:
1. In my assumption, I need to change the code in class-wc-form-handler.php, but I still leave the is_email as you state above.
2. For customer class, I don’t change it, because it already have for getting and setting display_name properly.
3. I did some changes to provide update to display_name in these files:
		- includes/class-wc-form-handler.php
		- includes/data-stores/class-wc-customer-data-store.php
		- templates/myaccount/form-edit-account.php

Here is my commit: 
https://github.com/widianto/woocommerce/commit/44425d2951b818a577d74f6927b2f1afeed46bff

It provides editing for display name and saving them.

Please let me know if you have any suggestion or if I make any mistakes in that code. I'll make new branch fix if necessary to provide correct pull request later.

**Comment by mikejolley** [comment]
@widianto Send that as a pull request and we can add feedback directly.

**Comment by mikejolley** [comment]
This has a PR (almost) ready for 3.4 next year. See https://github.com/woocommerce/woocommerce/pull/17861
