### ISSUE TITLE
Integrate PHPCompatibility sniffs into CI toolchain

### ISSUE THREAD

**Issue by danielbachhuber** [woocommerce/woocommerce#17625]
The [PHPCompatibility sniffs](https://github.com/wimg/PHPCompatibility) help to identify PHP compatibility issues between versions. It would be helpful to integrate into the CI toolchain so WooCommerce developers know when code changes have/introduce incompatible code.

In a [data analysis project I'm doing right now](https://github.com/danielbachhuber/php-compat-command/), WooCommerce is a common failed plugin (8% of WordPress installs in a 10k sample).

The PHP 7 failures (and proposed resolutions) include:

1. [RemovedExtensions.mysql_DeprecatedRemoved](https://github.com/danielbachhuber/php-incompatibility/blob/master/RemovedExtensions.mysql_DeprecatedRemoved.md)
    * Proposed resolution: Ignore the warning with `// @codingStandardsIgnoreLine`
2. [RemovedGlobalVariables.http_raw_post_dataDeprecatedRemoved](https://github.com/danielbachhuber/php-incompatibility/blob/master/RemovedGlobalVariables.http_raw_post_dataDeprecatedRemoved.md)
    * Proposed resolution: Always use `file_get_contents( 'php://input' );`
3. [DeprecatedFunctions.set_magic_quotes_runtimeDeprecatedRemoved](https://github.com/danielbachhuber/php-incompatibility/blob/master/DeprecatedFunctions.set_magic_quotes_runtimeDeprecatedRemoved.md)
    * Proposed resolution: Remove call to `set_magic_quotes_runtime()` which hasn't worked since PHP 5.3.

For further reference, here's a [cache of WooCommerce v3.2.3 scan results](https://github.com/danielbachhuber/php-compat-cache/blob/master/plugins/woocommerce/woocommerce.3.2.3.json).

Related https://github.com/Automattic/jetpack/issues/8126

**Comment by claudiosanches** [comment]
All of those code can just be ignored with `// @codingStandardsIgnoreLine`, since we use to support legacy PHP versions.

https://github.com/woocommerce/woocommerce/blob/46d3638089b58b51a2321b67443b83f409c6b4ec/includes/api/legacy/v3/class-wc-api-server.php#L654-L675
https://github.com/woocommerce/woocommerce/blob/0f58d0cfc1e1d00e9443d7d2ebedbfcb490387d9/includes/class-wc-download-handler.php#L321-L334

As you can see, none of them will throw warnings, since are code to just make compatible, but will show up in `PHPCompatibility`.

**Comment by claudiosanches** [comment]
See #17641
