### ISSUE TITLE
Price changed by the client

### ISSUE THREAD

**Issue by sagitaire123** [woocommerce/woocommerce#17644]
Hello,

I'm using woocommerce version 2.4.7, I have a customer who ordered a product which cost 30€ and he managed to change the price at the checkout by setting 0.01€ and he pay via PayPal.
he succeeded to pay the order with a different price (0.01€) than the one I fixed on this product (30€).

i received an email that a new order was received, and i got the following notification on woocommerce notes : **_validation error: Paypal amounts do not match ( gross 0.01). Order status changed from pending payment to Pending._**

Where does the problem comes from ? how he succeeded to change the price? and how can I fix it?

**PayPal logs**

11-09-2017 @ 22:48:25 - Received valid response from PayPal
11-09-2017 @ 22:48:25 - Found order #19812
11-09-2017 @ 22:48:25 - Payment status: completed
11-09-2017 @ 23:08:46 - Generating payment form for order 19812. Notify URL: https://xxxxxx/wc-api/WC_Gateway_Paypal/
11-09-2017 @ 23:09:36 - Checking IPN response is valid
11-09-2017 @ 23:09:36 - IPN Request: Array
(
    [body] => Array
        (
            [cmd] => _notify-validate
            [mc_gross] => 0.01
            [invoice] => WC-19812
            [protection_eligibility] => Eligible
            [item_number1] => 
            [payer_id] => UGFRZG5ML89FE
            [tax] => 0.00
            [payment_date] => 14:09:29 Nov 09, 2017 PST
            [payment_status] => Completed
            [charset] => windows-1252
            [first_name] => Joany
            [mc_fee] => 0.01
            [notify_version] => 3.8
            [custom] => {"order_id":19812,"order_key":"wc_order_556edea8gra0"}
            [payer_status] => unverified
            [business] => payment.sup85@gmail.com
            [num_cart_items] => 1
            [verify_sign] => A1FJEIgrJAjefz95FE2984HrKeifZFUAC5EzqIZlEFbGmFEX
            [payer_email] => lvradi@mail.ru
            [txn_id] => 26542665FL26984D
            [payment_type] => instant
            [last_name] => Stele
            [item_name1] => Black Shirt Designed
            [receiver_email] => payment.sup85@gmail.com
            [payment_fee] => 
            [shipping_discount] => 0.00
            [quantity1] => 1
            [insurance_amount] => 0.00
            [receiver_id] => KDLR59LFALD98
            [txn_type] => cart
            [discount] => 0.00
            [mc_gross_1] => 0.01
            [mc_currency] => EUR
            [residence_country] => FR
            [shipping_method] => Default
            [transaction_subject] => 
            [payment_gross] => 
            [ipn_track_id] => 54tj454vcdja
        )

    [timeout] => 60
    [httpversion] => 1.1
    [compress] => 
    [decompress] => 
    [user-agent] => WooCommerce/2.4.7

Thank you for help

**Comment by kloon** [comment]
You are using quite an outdated version of WooCommerce and we have made changes to the PayPal integration since and also changes to the rounding. We also recently added some changes that improve checking of people that spoof the PayPal PDT result, which is what PayPal sends back to confirm the order in the store.

Chances are that the customer was trying to spoof a payment, there is unfortunately nothing we can do to prohibit someone from trying to spoof a payment, that is why we have checks in place like the above to make sure the order only gets marked as pending when it is from PayPal itself and matches certain conditions.

I would also suggest you look into getting your site updated to the latest WooCommerce, be sure to make sufficient backups before proceeding just in case you need to roll back.
