### ISSUE TITLE
Coupon "Minimum Spend" doesn't account for taxes

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#17697]
In the latest version of WooCommerce, the "Minimum Spend" for a coupon doesn't include taxes.

In the coupon settings if we go to the info text, it shows:

![http://cld.wthms.co/iA9f11](http://cld.wthms.co/iA9f11+) 
Full Size: http://cld.wthms.co/iA9f11

So, it _should_ be counting tax as part of the minimum spend. However, if I add up a cart where the subtotal is under the minimum but the tax brings it above, then it's invalid:

![http://cld.wthms.co/ET4gdM](http://cld.wthms.co/ET4gdM+) 
Full Size: http://cld.wthms.co/ET4gdM

It looks like in `includes/class-wc-discounts.php` starting around line 605 may be the culprit, as it seems to be grabbing the subtotal there vs. the cart total.

791874-zen

**Comment by kloon** [comment]
After some discussion and due to the complexities of how taxes work and differ from store to store we decided to go with the approach that the minimum and maximum spend would be linked to the subtotal displayed on screen. This can differ from store to store with the same products just depending on how you have your tax settings set up.

The reasoning is because we follow the top down approach, discounts comes right after the subtotal in the table so it is just more logical to work it out based on that value then.

#17710 addresses the issue as well as update the tooltips to make it clearer that it is based on the displayed subtotal.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17710
