### ISSUE TITLE
Tax added to manualy set prices in orders when inclusive taxes enabled

### ISSUE THREAD

**Issue by bhouszka** [woocommerce/woocommerce#17693]
It is quite often when I have to add orders manually as I get sales through a lot of different channels or add discounts and not all of them are integrated with my store. Prices vary a bit and also I am asked for a discount on bigger purchases. This bug is very annoying as I only do know the prices of my products including tax. So whenever I enter products manually I need to sit with a calculator and count price of each of them. This takes me a lot of time.

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. In Woocommerce->Settings->Tax select radio "Yes I will be entering prices with tax"
2. Edit or create new order
3. Add product/additional fee/shipping cost manually to order and type in the price
4. Save and recalculate

## Expected/actual behavior

When I follow those steps, I see tax added to the price manually added items.
Example:  I enter product worth $100 and after recalculating the total price is $123 (tax set for 23%)

I was expecting price of the manually added items was with Tax, so the tax is calculated but is not added to product price.
Example:  I enter product worth $100 and after recalculating the total price is $100 (tax set for 23%)

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Line items in orders are entered excl tax. We have no plans to change this - changing it would be a massive breaking change and we'd lose all 'standards' on how prices are stored in orders. This is not a bug.

I'd suggest logging on ideas.woocommerce.com rather than here since it's a feature request and would need a lot of demand to be worth building. 

http://ideas.woocommerce.com/forums/133476-woocommerce

In the meantime, just to point out that if you add products to the order, they are already excl. tax. You can apply coupons in the admin area since 3.2 also, so thats less manual calculations to do if you take that route vs manually entering prices.

Thanks

**Comment by jodamo5** [comment]
> Line items in orders are entered excl tax. We have no plans to change this - changing it would be a massive breaking change and we'd lose all 'standards' on how prices are stored in orders. This is not a bug.

The problem is that the user experience is definitely inconsistent with the current state of things. 

When the WooCommerce tax settings are set to "Yes, I will enter prices inclusive of tax" the full admin experience is tax inclusive, except on orders.  

- When editing a price on a product it shows the tax inclusive price
- When viewing the product on the front-end of the site it shows the tax-inclusive price

But when editing an order, suddenly it is showing the tax exclusive price - even though everywhere else it is the tax inclusive. 

We are not asking for how prices are stored to be changed - just how the prices are **shown** in the orders interface and when editing an order. 

It would make much more sense for the prices on all screens to be tax inclusive, if the setting in the store is to enter prices as tax inclusive.

There is a thread on the ideas forum here where you can vote: 
[https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3885796-prices-display-including-tax-in-the-order-edit-scr](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3885796-prices-display-including-tax-in-the-order-edit-scr)

**Comment by immist** [comment]
This definitely needs to get fixed, it is a huge dealbreaker for many people who have to edit their orders manually. As stated by jodamo5, this can be fixed by just modifying the UI. I don't understand why this issue was marked as closed.

**Comment by tin-soldier** [comment]
+1 for this as a must have UI change. Is there a function that can be added in the meantime.

I've found you can add a tax inclusive column to the line items with this: https://stackoverflow.com/questions/46546482/woocommerce-admin-order-detail-page

but the amounts are not editable. Any ideas?

**Comment by ArneSaknussemm** [comment]
+1 I'm dealing with the same issue

**Comment by timo-cavelius** [comment]
Has someone found a solution for this problem yet? A code snippet would be highly appreciated.

**Comment by camper2020** [comment]
Hi all not sure what happened to my previous comment but I’ve had the same issue and wrote a small plugin to allow showing inclusive tax prices and to edit them  @tin-soldier . Please feel free to try it out and let me know if it works or not. You can find it on the WP plugin repo here https://wordpress.org/plugins/rd-wc-order-modifier/

hope it can help someone!

**Comment by QuiqueCrimson** [comment]
> Line items in orders are entered excl tax. We have no plans to change this - changing it would be a massive breaking change and we'd lose all 'standards' on how prices are stored in orders. This is not a bug.

The problem is that the price **shown** in manual orders is the price including tax. And when recalculate the order, the tax is added again. And this is not correct.

If the price is including tax, the price in the manual orders must be including tax like in the shopping cart.

Or maybe, a check to decide if we want that the price that appears in the manual order is incl or excl tax

Thanks

**Comment by or128** [comment]
I would like to add my voice and say this is really difficult and wrong. The order creation interface should also work with prices that include tax, like the rest of the system. The language needs to be consistent.
