### ISSUE TITLE
Product Count is not updating when i use "woocommerce_product_is_visible" filter

### ISSUE THREAD

**Issue by vicky081** [woocommerce/woocommerce#17704]
Hello there,

I found some issues when i use filter "woocommerce_product_is_visible" when i set the bool value to false for some of the products associated with product category, then corresponding category product count is not updated it still old one

Let say i have 
product a, product b, product c 
Those 3 products are associated with Category A then Category A product count will be 3
Now i set false to Product A using above filter and it is hidden from site as well, but not with category count(3) it is still shows old count, i tried to reset the term count from tools options as well but no luck.

I hope there is no link between the product visibility vs product count of category? Hope it may be a bug.

Please let me know if i miss something.

Thanks.

**Comment by kloon** [comment]
Unfortunately it would be impossible to incorporate the filter into the counts, the filter is dynamic which means you can use it to hide products based on a various scenarios, ie hide for certain users, because of that and the fact that you cannot then cache the data will mean it will have to fetch the counts on each page load which will become very slow.

I would suggest you rather hide the counts instead of having it shown if it is a problem.
