### ISSUE TITLE
WooCommerce admin styles are affecting other areas of the admin section, outside of WooCommerce areas.

### ISSUE THREAD

**Issue by pixelbrad** [woocommerce/woocommerce#17721]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Update WooCommerce to latest version.
2. Install latest version of BackupBuddy or WooShipping DHL.
3. Plugins that use `<table class="form-table">` to manage their settings are affected by WooCommerce admin styles, since WooCommerce is now adding a `woocommerce` class to `<body>`

## Expected/actual behavior

When I follow those steps, I see...

When I'm managing settings inside BackupBuddy or WooShipping DHL, the currently selected option inside `<select>` elements gets cut off from the bottom. As well, text inputs are taller than they should be. The elements are receiving additional padding (6px instead of 2px).

I was expecting to see...

Isolated styles...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Sorry, privacy is a concern here. I'd be more than happy to provide details privately, and/or get someone on the WooCommerce team some credentials to the site I'm managing.
```
</details>

**Comment by pixelbrad** [comment]
![backupbuddy](https://user-images.githubusercontent.com/31455819/32866341-701af6ba-ca24-11e7-8256-2c59ddeedaf3.jpg)

**Comment by mikejolley** [comment]
Unfortunately I cannot test with BackupBuddy because it's premium.

I've checked anyhow - WooCommerce adds no such body class in admin. Clean install, any screen, in this case dashboard, no body class:

![dashboard local wordpress dev wordpress 2017-11-16 11-25-37](https://user-images.githubusercontent.com/90977/32888955-e42eef56-cac0-11e7-8bde-23ad18a7c33a.png)

And no code filtering body class either: https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=admin_body_class&type=

Also, regular settings page has select boxes and you can see no wc styles are applying in the inspector.

You're assuming it's core, but it's very likely an extension doing this. Not sure why they would unless they wanted a way to utilise our styles on their own pages?

Additionally, WooCommerce admin CSS is only enqueued on screens `wc_get_screen_ids()` returns. We use a whitelist. Again, a plugin could be changing how this works.

I don't think you've gone through the "Isolating the problem" steps even though you checked the boxes? I'm pretty certain this will be extension caused :)
