### ISSUE TITLE
Variable Price Range for Our of Stock Products Bug

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#17805]
Steps to recreate issue.

1. Setup a variable product with different price range. (eg. 1000, 2000, 3000$)

2. Hide out of stock products in backend.

3. Make the product costing 1000$ out of stock.

4. Now the price range of the variable product still displays 1000$-3000$ and it is confusing for the customer as he sees only two possible selections of 2000$ and 3000$ which are in stock.

**Comment by mikejolley** [comment]
Hi @shreyans94 

I can see why this might happen, if changing settings in that way. Future saves/updates of that product would update it because it would then see the value of the setting you changed.

Fixing this would require syncing all variable products when updating the option ("Hide out of stock products in backend"). That in itself would be resource intensive and slow because it would have to query all variable products and check each of their variations. That sounds unworkable to me and is probably not worth fixing in bulk.

cc'ing @kloon for second opinion. I'd vote to leave it and let them update on save.

**Comment by kloon** [comment]
This is a difficult one, I get that it is not performant to be going through all variable products when something goes out of stock, but I also think it is needed to keep the pricing updated to what is available. Having the customer resave the product to just update the pricing range is really not ideal.

What if we offload the recalc to a background job when something goes out of stock? That is the only way I can see us incorporate this without having too much of a performance issue?

**Comment by mikejolley** [comment]
@kloon BG process might be viable, on settings change.

**Comment by mensmaximus** [comment]
I just checked the methods involved in displaying the variable price range and found `read_price_data` from class `WC_Product_Variable_Data_Store_CPT` already utilizes `get_visible_children`. I understand the price range gets cached in a transient. Wouldn't it be enough to expire the transient in case the stock changes to 0 and `woocommerce_hide_out_of_stock_items` is true?

**Comment by mikejolley** [comment]
Looks like I made a mistake :)

When the product is made out of stock, transient versions are cleared (at least in master), so the new range (2000-3000) is indeed shown.

No action needed.
