### ISSUE TITLE
Stock status is not updating for 0 quantity products.

### ISSUE THREAD

**Issue by DnyangangabooksPune** [woocommerce/woocommerce#17806]
I have used woocommerce latest plugin with latest wordpress. For some of products, when user buys product quantity of product updates to "0" quantity, but stock status still shows in stock.
This happens for only some products. I have also disabled backorders for all products. It shows 'Read More' button for some products and 'Add to cart' for som even if product quantity is "0".

PFA for reference 
![screenshot 160](https://user-images.githubusercontent.com/33658130/33010770-bb38383e-ce01-11e7-9fe6-0cdb062fc34c.png)

**Comment by mikejolley** [comment]
Hi @DnyangangabooksPune

Unfortunately there is not enough information there for us to attempt to reproduce this. In the past however, for similar issues, it's been one of the following:

- A plugin installed alongside WC changing the logic to prevent out of stock being set
- A plugin installed alongside WC updating products in a way which circumvents the stock status being updated, or throws an error.
- The setting in WC > Products > Inventory for out of stock level being set to something other than 0.

I'd suggest trying to better figure out what circumstances trigger this error, and checking the server php error log for clues. If you can narrow it down or post instructions to replicate on a different install please follow up.

Thanks

**Comment by aaronlp** [comment]
@mikejolley @DnyangangabooksPune I am experiencing this issue too. It is only affecting a subset of products in the store - some of them are set to 0 quantity with 'In stock' status remaining on them whereas others are being set to 0 quantity and changing to 'Out of stock' status. I can't see anything unique about the products the products that don't change status. I have also looked at the orders in which these items were purchased and there are no patterns that I can identify. There are some orders where some items in that order are set to out of stock and others are left in stock even though they all reduced to 0 quantity in the same order. 
I do believe this is a bug and am happy to provide more information if it helps. Please let me know if I should raise a new bug report or you are happy to re-open this one.

**Comment by mikejolley** [comment]
@aaronlp You'd need to narrow it down as I said in my previous comment, otherwise we're no better off and have nothing to work from.

**Comment by tc33** [comment]
@mikejolley I'm experiencing this too and think I can shed some light on when it's happening. Having updated from a pre-CRUD version, products don't have all the product post meta fields. In particular they don't have _backorders. When the stock status is being updated, there's a check to see if backorders are set to 'no' - which they're not because the field doesn't exist. As a result it's assumed that backorders are enabled and the stock status is set to 'instock'. 

The reason it doesn't happen on all products is that once re-saved, the meta fields are added, and it's no longer a problem for that product.

**Comment by mikejolley** [comment]
What version doesn't did you upgrade from to not have _backorders?

**Comment by tc33** [comment]
The relevant update was from 2.6.11 -> 3.1.1. But I wrongly assumed that the former version didn't store the default _backorders value in the DB. So this probably isn't anything to do with the update.

I've checked this on a few existing sites and all have quite a lot of variations without a _backorders value in the database, which definitely seems to be the cause of the stock status being incorrect. I can't explain why that field is missing, but I'm not sure that it matters because products created since updating don't appear to have the problem. So for us it's probably just a case of fixing the existing state by inserting the missing values. 

@DnyangangabooksPune @aaronlp For anyone else experiencing this (assuming it is the same problem), re-saving existing products on the latest version should cause the missing values to be inserted.
