### ISSUE TITLE
TM shows as image instead of text in email confirmations

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#17823]
Ticket: 
796738-zd-woothemes

Steps to Reproduce:
Tested with latest master. 

Create a product that has a TM: `Ship Your Idea  &trade;`
Looks great here:

![](http://cld.wthms.co/fvVQU9+)
Link to screenshot: http://cld.wthms.co/fvVQU9

Purchase and view email

In confirmation emails, the TM is an image instead:

![](http://cld.wthms.co/WBlmpa+)
Link to screenshot: http://cld.wthms.co/WBlmpa

**Comment by mikejolley** [comment]
This is something WordPress does automatically when sending HTML emails. See https://github.com/WordPress/WordPress/blob/a2693fd8602e3263b5925b9d799ddd577202167d/wp-includes/formatting.php#L5294 Not something we can or should work around. Showing an image has no negative impact from what I can see, and I assume they do it because it works across more mail clients. 

Can be disabled if really hated https://drawne.com/disable-emoji-support-in-wordpress/

**Comment by demian1985** [comment]
If you have products with TM, this is a very annoying problem. In my instance the image is 3x bigger than the regular text in the email. Doesn't matter which email client you use, it looks very amateurish. I don't understand the reasoning behind it, the unicode for tm is a regular character, nothing spammy about it.

**Comment by praful2111** [comment]
Add the following line in the bottom of your `functions.php`:

`function disable_emojis() {
    remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
}
add_action( 'init', 'disable_emojis' );`
