### ISSUE TITLE
Switching shop page settings requires second refresh.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#17851]
Switching the shop page settings under **WooCommerce > Settings > Products > Display** requires a second page refresh.

![8bskrh](https://user-images.githubusercontent.com/2876178/33092556-17916506-cec0-11e7-935d-6bb5a6ce1ddf.gif)

Link: http://cld.wthms.co/8bskrH

**Comment by WPprodigy** [comment]
Change shop page to some other page, refresh original shop page, change back to shop page, refresh, see no products the first time.

I can replicate.

**Comment by mikejolley** [comment]
@WPprodigy @johndcoy Rewrite rules in WP are fickle. The refresh is not fixing it, the cron job we queue does:

`wp_schedule_single_event( time(), 'woocommerce_flush_rewrite_rules' );`

The page won't work correctly until rewrite rules regen ^ This cannot be done in the same request because the post types will not be setup correctly until after save.

**Comment by johndcoy** [comment]
@mikejolley https://wordpress.org/support/topic/any-page-set-to-shop-is-blank/

**Comment by WPprodigy** [comment]
Hmm, can't do the rewrite save when the products > display page is saved?

**Comment by mikejolley** [comment]
@WPprodigy No because these settings change the definition of the product post type, and the rewrite rules for those are setup earlier (init).

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17867
