### ISSUE TITLE
Rounding error with VAT tax

### ISSUE THREAD

**Issue by Mixmarko** [woocommerce/woocommerce#17883]
Hi,

i have a problem with the VAT rounding in my woocommerce.
In our test site http://test.realizzazionesitiwordpress.it/ we have woocommerce 3.2.0 and i haven't the problem, but in another site, where we have woocommerce 3.2.5, we have see the rounding problem.
For example here i show you a screenshot: http://test.realizzazionesitiwordpress.it/wp-content/uploads/2017/11/Error-example.jpg
Here you can see that the two price in the middle of the page and on the right are different for 1 cent. I use the price without VAT 4,0163934 (in Italy we have the 22% of VAT/IVA).

Is this a bug of a new version?
We can come back to the older version? If yes, can you link me an official guide?

Bye and thanks a lot

**Comment by mikejolley** [comment]
This is due to the invalid precision being used for the product price - `4.0163934`. Obviously you cannot really charge this amount, it will be rounded. 

I get why you've done it - so you get an end result of 4.90, however, this is why we have the 'prices including tax' setting so you can actually define 4.90 and work back from there.

The price after tax comes to `4.899999948` so display price is 4.90 when rounded. However the totals class will be rounding:

4.0163934 * 4 = 16.0655736 (rounded to 16.07).
16.07 * 1.22 = 19.6054 (rounded to 19.61).

You can follow https://github.com/woocommerce/woocommerce/issues/17863 which aims to deal with irregularities like this, but for now you'd have to do one of the following:

- tweak the product price decimal
- stop using > 2 dp precision and just accept the final (correct) tax result
- Switch to defining prices including tax
- downgrade and stay downgraded which isn't ideal because you lose access to new features and security patches

Closing this in favour of #17863
