### ISSUE TITLE
Product Images and variations deleted after database migration

### ISSUE THREAD

**Issue by jordan314** [woocommerce/woocommerce#17924]
Hello,
We are migrating our install from one server to another. When we download the old database, and upload it to the new server, all of the products appear initially, but within 15 minutes the images get deleted from the uploads folder and the variations disappear. I can see the images in the frontend and backend, but after updating the product in the backend, the product images disappear and the product variations disappear. This is similar to #17923 and #16635, but our images are disappearing as well. I tried an XML import instead but it says the products already exist. I've watched my uploads/2011/11 folder shrink from 79 items to 64 items as it deletes the product images.

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an SQL dump of another woocommerce install
2. Delete all tables and import the SQL file to a local install

## Expected/actual behavior

When I follow those steps, I see...
The products retain their variations and images at first, and then disappear

I was expecting to see...
The products retain their variations and images

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

Home URL: |   | http://testwoocommerce.dev
-- | -- | --
Site URL: |   | http://testwoocommerce.dev
WC version: |   | 3.2.3
Log directory writable: |   | /Users/jordan314/Sites/testwoocommerce/wp-content/uploads/wc-logs/
WP version: |   | 4.9
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by claudiulodro** [comment]
If it worked properly before, you moved from one server to another, and now you have problems, it seems like the issue is almost certainly your new server. Our e2e tests use [an sql dump](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e-tests/data) to populate everything, and this is not a problem we've experienced.

There's a lot of info missing in your system status report, so I have to ask, does this happen with only the WooCommerce plugin active and no other plugins active? If so, does it still happen using the latest (3.2.5) version of WooCommerce? WordPress 4.9 changed the way some things behave and WooCommerce 3.2.5 fixes some important things that broke as a result of those changes.

**Comment by jordan314** [comment]
This happened on three different servers - the local of mine and another developer, and the staging server of our site. Does woocommerce delete product images if they become unlinked somehow in the database?
I can't provide a raw dump of the system report because it includes domains that I can't expose. I could provide them via email.

**Comment by claudiulodro** [comment]
I don't need the full system report; I just need to know that you've actually tried this and have this problem using **only** WooCommerce active and no other plugins active. :) Otherwise the problem could be coming from another plugin you have.

The only place in WooCommerce where images are deleted when products are deleted is the API. You probably don't have something making API calls to your local environment or staging server, though. (Do you?)

First thing I would try is upgrading to WC 3.2.5. If that doesn't solve the issue I can try and debug it further.

**Comment by jordan314** [comment]
This seemed to fix it, sorry, you can close this!
