### ISSUE TITLE
Cannot add multiple products in Cart ( WC - 3.2.5  )

### ISSUE THREAD

**Issue by akash-dhawade** [woocommerce/woocommerce#17994]
While adding products to cart in multiple separate requests the WC()->cart->add_to_cart( ) function only seems to add the product from the first request and ignores the rest. 

For example, If I have two different separate link like this for adding products in the cart:
1. http://localhost/~akash/wc-3.2/index.php/cart/?product_id=90&_wpnonce=77cc0d1d8e  
2. http://localhost/~akash/wc-3.2/index.php/cart/?product_id=93&_wpnonce=77cc0d1d8e 

Then on clicking the first link, the product with ID - 90 gets added to the cart whereas on clicking the second link the the product with ID - 93 gets ignored. 

The WC()->cart->add_to_cart() functionality is written under 'wp_loaded' hook. 

This functionality use to work before WC-3.2

**Comment by mikejolley** [comment]
WooCommerce loads the cart on `wp_loaded` priority 10.

This is probably not a good time to call custom logic because it could happen before/after WC based on the name of your plugin, and the priority used.

You'll want to use a later priority.

https://developer.wordpress.org/reference/functions/add_action/

If you use anything above 10, WC will load the cart before you run your logic.
