### ISSUE TITLE
woocommerce checkout page error

### ISSUE THREAD

**Issue by vivelancer** [woocommerce/woocommerce#17995]
Hi there 

woocommerce  error
 when i click on {proceed to paypal } i see {woocommerce  error}

websites : https://divineschematic.com/checkout/

**Comment by mikejolley** [comment]
You've provided no status report, nor attempted (it seems ) to narrow down the problem. The paypal plugin you appear to be using is not core. Go through the steps in the 'new issue' form before submitting here.

Also, you have not input your shortcodes on the checkout page correctly. The checkout is wrapped in pre/code tags which is why it looks a mess. Edit the page, switch from 'visual' to 'text' editor, and remove the pre/code tags wrapping the shortcode.

Thanks
