### ISSUE TITLE
Event queue: Webhooks deliveries in table, cron to serve from table (periodically)

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#18003]
We could consider store the payload too, improving things like https://github.com/woocommerce/woocommerce/issues/15699

**Comment by thenbrent** [comment]
You could use [Action Scheduler](https://github.com/Prospress/action-scheduler) to achieve this.

To do that would only need the [`wp_schedule_single_event()` function call](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-webhook-functions.php#L24) to use `wc_schedule_single_action()` instead (the params can remain unchanged).

i.e. replace

```
wp_schedule_single_event( time(), 'woocommerce_deliver_webhook_async', array( $webhook->get_id(), $arg ) );
```

With:

```
wc_schedule_single_action( time(), 'woocommerce_deliver_webhook_async', array( $webhook->get_id(), $arg ) );
```

That one line change will ensure webhook deliveries are outside the `cron` option row in the database so the number of scheduled webhooks can scale. It stores the `$arg`/`$args` param in a `LONGTEXT` column, to help with #15699. It will also log the creation, start, completion and/or failure of deliveries (with any errors that happen). It will handle large queues of webhooks gracefully. And it would also make it possible to process webhooks via WP CLI instead of within the context of web requests (which have PHP time limits etc. applied).

The bonus is that once Action Scheduler is included for this, it could then also can be leveraged for https://github.com/woocommerce/woocommerce/issues/16971.

The only downside is that Action Scheduler still uses a Custom Post Type by default, so there are scaling issues when the posts table is large. We have [custom tables](https://github.com/Prospress/action-scheduler-custom-tables/) already in alpha and it's in use on some live sites, so that is being addressed. We plan to ship those publicly with Subscriptions later in the year.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20030 for action scheduler implementation.
