### ISSUE TITLE
404 page after checkout

### ISSUE THREAD

**Issue by Irfan-git** [woocommerce/woocommerce#18046]
Hello,

I have WooCommerce 3.2.0 activated and I get an error 404 after placing an order. When the checkout process redirects to order-received, I get a 404 error instead of thank you page with product details.
The thank you page show if I made the url into WordPress default or dynamic url.

I have refreshed my Permalinks, disabled every plugin one by one but still the problem is coming.

**Comment by claudiosanches** [comment]
There is no steps to reproduce this issue and all issue template has been removed... So there is no way to try test it properly.
For what I'm testing this works just fine, not to mention that if this should be a real bug on WooCommerce core, we probably should have more reports about it.
So this sounds something on your installation, maybe something missing, maybe a plugin causing conflicts or maybe your theme.
That's why I'm closing, no way to reproduce and no way to know what is happening.

**Comment by Irfan-git** [comment]
I've deactivated and activated all the plugins to test plugin conflicts. No error found.
I also notice thank you works fine when I changed the permalinks into dynamic or default WordPress permalink. 
Here is an image of the problem:

![arkeinc order](https://user-images.githubusercontent.com/16193247/33732254-123d7f8e-dbb0-11e7-919f-ec4a428fd586.jpg)
