### ISSUE TITLE
Geolocation with page caching: Random key added twice when using anchor links

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#18083]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Under WooCommerce > Settings "Set Default customer location" to Geolocate (with Page Caching support)
2. Create a page and add a simple link to another page with an anchor in, such as `https://xxxxx/shop/#test1`
3. View the page and click on the link. The page that opens is `https://xxxxx/shop/?v=7516fd43adaa#test1?v=7516fd43adaa` with the random v key repeated twice. 

## Expected/actual behavior

I actually see:

`https://xxxxx/shop/?v=7516fd43adaa#test1?v=7516fd43adaa`

I was expecting to see:

`https://xxxxx/shop/#test1?v=7516fd43adaa`

According to the customer that reported this:

```
PHP parse_url() *does* have a component => fragment parameter: 
https://secure.php.net/manual/en/function.parse-url.php

Or roll your own. For example: 
https://stackoverflow.com/a/23282588
```

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by WPprodigy** [comment]
Happening because:

1) This script adds the location hash / query string to the url on the page: https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/geolocation.js#L15. So `https://example.com/shop/#test1` becomes `https://xxxxx/shop/#test1?v=7516fd43adaa` in the markup, even before the user clicks.

2) Then, once the user clicks the link, this conditional fails during the redirect(https://github.com/woocommerce/woocommerce/blob/220728544ab497abb268401803e25acf15633d9f/includes/class-wc-cache-helper.php#L97), because `$_GET['v']` is empty. This happens I'm guessing because it's assumed to be apart of the hash.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18094
