### ISSUE TITLE
lead time for product / backorder

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#18101]
Hi,
I previously asked to add lead time for product that is out of stock and it was not accepted:
https://github.com/woocommerce/woocommerce/issues/12596

Now I read that you did exactly the same and just called it backorder:
https://woocommerce.wordpress.com/2017/12/06/wc-3-3-product-backorders-and-stock-management-improvements/

My feedback about it:
If customer order a product in backorder than he realize it will take time till it will get on stock then what is the problem adding a value that tells him how much time? Showing it on the product page will help the customer decide if he wants to place an order or not. Some would say the waiting time is acceptable and some will not.

My suggestion : just like we can set that the product is on stock management and allowed backorder than in such cases add also the ability to set value how much time it will take. for example: 1 week, 2 weeks, 1 month etc... This option will be valid only for products that met the criteria of stock management and allowed backorder. It will be displayed on product page and on the invoice sent by email.

**Comment by mikejolley** [comment]
Backorders _are not new_ - the recent post simply explained some changes to the way backorders are stored (dedicated status). Nothing has changed relating to this idea.

What we/I said last time has not changed.

- Add lead time to the product summary, description or title.
- *or* Add it using a custom field https://github.com/woocommerce/woocommerce/issues/12596#issuecomment-270068790
- *or* Wait for http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17427502-lead-time-for-non-stock-product to be picked up

Besides, there are issues with a fixed text field as suggested. If you type '1 month' it will say the same thing in 2 weeks. Thats why an extension would be better for this so you can set dates and have it show a more reasonable time + follow up when the time passes.

Since this is a duplicate I'm closing comments here. If ever taken on in core, #12596 will be reopened. I think an extension is better suited FWIW.
