### ISSUE TITLE
Get consumer key programmatically

### ISSUE THREAD

**Issue by kmligue** [woocommerce/woocommerce#18109]
Is there a way to get consumer key prorammatically or by wc cli(like here https://github.com/WP-API/client-cli)?

**Comment by mikejolley** [comment]
Formal way is logged for dev here https://github.com/woocommerce/woocommerce/issues/15601

Right now you must query the `woocommerce_api_keys` table directly.

Thanks

**Comment by claudiosanches** [comment]
@kmligue @mikejolley once keys are generated is not possible to get it again, since `consumer_key` will be converted into a SHA256 hash.
Still you are free to use https://github.com/WP-API/client-cli and any other authentication method from WordPress, there is no need to just us authentication methods from WooCommerce.
