### ISSUE TITLE
Deprecated notice in master branch

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#18129]
I am getting this deprecated notice for master branch of WooCommerce :)

```
woocommerce_params is deprecated since version 3.3.0! Use woocommerce_get_script_data instead.
wc_checkout_params is deprecated since version 3.3.0! Use woocommerce_get_script_data instead.
```

**Comment by kloon** [comment]
Master branch is 3.3, this was introduced in #18036

**Comment by shivapoudel** [comment]
@kloon after #18036 merge deprecated notice is thrown up in  my development environment :)

**Comment by rodrigoprimo** [comment]
I'm also getting `wc_checkout_params is deprecated since version 3.3.0! Use woocommerce_get_script_data instead.` on my local environment. I didn't have time to investigate this and I'm going AFK for the next two weeks so reopening this issue in case anyone has time to check it. It seems that WC core is still calling this deprecated filter in the line below:

https://github.com/woocommerce/woocommerce/blob/170cf2d3617ab9f58a773ff2c85aa7257d9e71f1/includes/class-wc-frontend-scripts.php#L429

Probably related to #18036 as mentioned in the previous comments (cc @bor0)

**Comment by mikejolley** [comment]
Looking at the code, this means something is using the old filter in your environment. I'm not seeing the same warnings.

`woocommerce_get_script_data` is the new filter. Any usage of the old filter will be warned to move to `woocommerce_get_script_data`.

The old filter (code you referenced) must stay for backwards compatibility. It's an apply_filters statement so won't cause a notice by itself.

Let me know if I'm missing anything. cc @kloon

**Comment by pySilver** [comment]
@mikejolley obviosly the source of issue is here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L287 handle of a script is used here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L598 so it turnes to `woocommerce_params` at https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L443 which triggers a deprecated warning in apply_filter.
