### ISSUE TITLE
All products screen - responsiveness

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#18133]
The case here:

![all-products-screen-woocommerce](https://user-images.githubusercontent.com/5323259/33927583-282600e6-dfe3-11e7-9c4a-9033fd52c3c1.png)

Notice SKU is not being used. Have a process that checks to see which fields are not being used and the automatically hides these columns giving more space to all the other columns.
I know that I manually can turn off the SKU column. Having short titles also leaves a lot of space before the next column begins. It would be nice with a responsive area here.

**Comment by mikejolley** [comment]
There are some problems with this approach;

1. Query intensive to check all products to see if they use certain data such as SKU on each load.
2. SKUs can be filtered, so even if we have no value in the DB it's not certain the column is not used.
3. Hiding columns on narrow screens can be problematic if you start on a narrower screen - if the column is enabled but not visible it can be confusing. I found this when trying to make the order screen responsive and whilst it looked good on my 27" monitor, laptop users didn't see the columns at all.

It's not easy (possible?) to fit to contents with table contents either. I tried doing this with flexbox but the table lost it's 'columns' when some things were wide and others narrow. It's hard to make assumptions about length of titles, and again, if we try to do this programmatically it will cause performance issues.

Since these tables are controlled by WP core, it would make sense to have this addressed in WP core for all post types if it's an issue. They already handle mobile responsive styling - if you shrink the window down you'll see it removes everything but the primary column.

However since you can display columns manually (and you're on a narrow screen) I think it's fine to leave this in the hands of the user.

Thanks
