### ISSUE TITLE
Request failed with code: 400

### ISSUE THREAD

**Issue by mw-subscriptions** [woocommerce/woocommerce#18201]
When I do get products request, the api works fine. But when I do post, it returns the error "Request failed with code: 400". Does someone know why?

**Comment by WPprodigy** [comment]
400 means your request to post the data to the server isn't being accepted because what you are sending is invalid.

Review how to create a product here and double check your syntax: http://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

**Comment by Sands-45** [comment]
You can only create products with the data or properties on their API doc (exclude the categories since they don't exist. Also exclude image id's if the images are external ). Then you can subsequently call update to update the product with other properties. If anything includes an ID just make sure it exist on you woocomerce
