### ISSUE TITLE
NO required field validation for guest customr

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#18204]
For not logged in user there aren't any kind of "live" fields validation. simply try to kept empty a required fileld in checkout.

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enable the giuest checkout 
2. logout 
3.Add to cart a product
4. Go to checkout
5. Click on input required field, in example first name
6. kept empty this field, click in other field in example

You can see that no class woocommerce-invalid are add to this field.
The problem disappear for logged in user.

## Expected/actual behavior

https://www.screencast.com/t/PBoygjMrZwOe

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

Thanks for your time!

**Comment by WPprodigy** [comment]
Can't view the video (no flash), but I think I know what's happening here. The field validation doesn't start until the field is "activated".

When you remove the data from a field and skip it while logged in, the field has already been active so an error can be added. When you are a guest and skip a field, nothing has been entered into the field yet so it's not yet activated.

To understand, try checking out as a guest and fill in both first name and last name. Then go back and remove the first name data and continue to a new field. You'll see the error validation.

Not sure if it's a bug per-se, but could maybe use some different javascript events here to trigger the error when shipping over a required field.

**Comment by mikejolley** [comment]
@WPprodigy Your patch brings back the focus bug (first field gets focus on checkout, checkout updates, first field shows red border due to validation).

FYI the same thing happens if you have a logged in user with no stored address.

TBH I think we should leave this as-is. If you tab through the fields, I don't think we should be validating the value on each tab unless the user changes anything. There are other indicators of required fields, and if the user *does* try to submit checkout, the validation kicks in at that point.

On submit, input change and on input makes the most sense for validation events.

This can of course be looked at again when the checkout flows are redesigned, but at this point we shouldn't mess around with it further and bring back the previous focus/focusout bug.

Track https://github.com/woocommerce/woocommerce/issues/10672
