### ISSUE TITLE
Random Order

### ISSUE THREAD

**Issue by Ejwiseman** [woocommerce/woocommerce#18207]
Hi, I have my suggestion is there anyway you can put random order in your default product sorting in your next update. See screenshot for reference: http://prntscr.com/hnmlwn

Regards

Ej

**Comment by WPprodigy** [comment]
You can add custom sorting options to you site using the filters available. That said, random sort order is a bad idea for quite a few reasons.

1) Why random? What benefit does that serve to your customers over you crafting a specific order?
2) What happens when you have enough product that pagination is required? If the next page is random, then they could end up with some products on page 2 that were also on page 1. Some products could technically never be shown.
3) Random queries are expensive and can slow down your site.

This plugin used to have the options: https://wordpress.org/plugins/woocommerce-extra-product-sorting-options/, but has since removed it due to some of the above reasons. You can find a link to a snippet in that plugin's FAQ section to add a random sort option, but I'd recommend thinking it over a bit more if this is really something you'll need.
