### ISSUE TITLE
Unable to update and delete coupons (Socket hang up)

### ISSUE THREAD

**Issue by rifrayugo** [woocommerce/woocommerce#18213]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I tried to use this function
```
var data = {
  amount: '5'
};
WooCommerce.put('coupons/2017', data, function(err, data, res) {
  console.log(res);
});
```

and i got this error message
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

**Comment by WPprodigy** [comment]
You're getting this error on the request side, or the server side (where WC it installed)? If on the request/client side, then the problem here is just that you aren't getting a timely response from the server. The socket is ending which throws this error.

What version of the rest api are you using? PUT requests aren't used in the later versions, it's POST now: http://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-coupon

It's possible your web server doesn't accept PUT requests.

**Comment by rifrayugo** [comment]
i am getting this error from my request side.
i use this version 1.4.2 for the npm library.
i already tried using post and that already successfully updated the data. but how if i am gonna delete the data?

**Comment by WPprodigy** [comment]
If you need to send a PUT request, then you'll need to get a server that supports PUT requests :)

There is a possible workaround though: https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

**Comment by claudiosanches** [comment]
This is not an issue with WooCommece, sounds like an issue with the library, better report in the library repository instead.
