### ISSUE TITLE
pagination_base on woocommerce

### ISSUE THREAD

**Issue by ered15** [woocommerce/woocommerce#18220]
Hi

I changed wordpress permalink for pagination from default “page” to “pagina” (Spanish word for page) with below rewrite rule in functions.php. It works for all wordpress pages, but for woocommerce the shop paged pages are empty (e.g. http://www.mydomain.com/shop/pagina/2/). Does anyone know a solution for this?
Thank you in advance.

function re_rewrite_rules() {
global $wp_rewrite;
$wp_rewrite->pagination_base = ‘pagina’; //what you want instead of “page”
$wp_rewrite->flush_rules();
}
add_action(‘wp_loaded’, ‘re_rewrite_rules’);

**Comment by WPprodigy** [comment]
Can use this filter: https://github.com/woocommerce/woocommerce/blob/804c7712969d4309ee5456be0792e6b6b4d67b4b/templates/loop/pagination.php#L29

**Comment by claudiosanches** [comment]
As Caleb said, there is filter allowing changing it on WooCommerce, so I'm closing it.

Just a tip: note that you are flush rewrite in all requests to your website, this is a performance problem, you should do it only once.

**Comment by ered15** [comment]
I tried this but still I get nothing:

// define the woocommerce_pagination_args callback 
function filter_woocommerce_pagination_args( $array ) { 
	$array['base'] = str_replace("page", "pagina", $array['base']);
    return $array; 
};

**Comment by claudiosanches** [comment]
@WPprodigy @ered15 not that WooCommerce uses [`get_pagenum_link()`](https://developer.wordpress.org/reference/functions/get_pagenum_link/) to get the page link.

https://developer.wordpress.org/reference/functions/get_pagenum_link/

WP already uses `$wp_rewrite->pagination_base`.
So your code does not sound correct, since should already be working when hit this function.
Not to mention that you can also filter using `get_pagenum_link`.

**Comment by ered15** [comment]
@claudiosanches tx, and just to make my self clear using `$wp_rewrite->pagination_base = ‘pagina’;` code does change the URL slug, but when I click on the link it shows no products on the page, if I change it back to "page" it shows the products.
