### ISSUE TITLE
Woocommerce shipping calculator requires zip code for Suriname

### ISSUE THREAD

**Issue by DollyPop007** [woocommerce/woocommerce#18226]
The country Suriname doesn't have zip codes but woocommerce shipping calculator requires a zip code for fetching rates. How can this be solved?

**Comment by rodrigoprimo** [comment]
Thanks for your report, @DollyPop007. I did a quick test and I was able to calculate shipping for Suriname without entering a postcode. What exactly happens when you try to calculate shipping without entering a postcode? Please share as many details as possible of all the steps that you take so that I can reproduce the issue. If possible, include screenshots as they always help.

You might want to check the filter `woocommerce_shipping_calculator_enable_postcode` (https://github.com/woocommerce/woocommerce/blob/1fbcff023df28bca838a694ea63fe3bdfaf754f5/templates/cart/shipping-calculator.php#L81). You could use it to hide the postcode field.

@claudiosanches, do we want to somehow support countries without postcode and automatically hide the postcode field when a country without postcode is selected?

**Comment by claudiosanches** [comment]
@rodrigoprimo still is required on the checkout, but we can disable.

@DollyPop007 in general is used postcodes from something or we could just hide it from checkout?

**Comment by DollyPop007** [comment]
@rodrigoprimo It only calculates the shipping when you fill in a fake zip code (0000 or something else) but Suriname doesn't utilize zip codes at all. So this may be a little confusing to customers. The calculator is set to "hide shipping costs until address is entered". Maybe that's the problem?

@claudiosanches It could be hidden for this country as well as other countries that don't utilize zip codes right?

**Comment by claudiosanches** [comment]
@DollyPop007 yes, we can hide, but I'm asking you, how people does in your country, I having found any good references, if you could show me some references of forms from Suriname websites that does not require Postcode I'll be happy to remove it.

**Comment by DollyPop007** [comment]
@claudiosanches Do you mean forms from government websites? I'm afraid I have no references for that. The government websites don't have forms requiring your address, just simple contact forms. What else could I show as a reference? Maybe a PDF form of the chamber of commerce or something like that?

**Comment by WPprodigy** [comment]
Any references would help. Generally there are resources on this sort of thing available on wikipedia or such.

**Comment by rodrigoprimo** [comment]
> @rodrigoprimo It only calculates the shipping when you fill in a fake zip code (0000 or something else) but Suriname doesn't utilize zip codes at all. So this may be a little confusing to customers. The calculator is set to "hide shipping costs until address is entered". Maybe that's the problem?

@DollyPop007, I agree that it can be confusing to customers and probably the best solution, as @claudiosanches suggested, is to hide the postcode field when Suriname is selected. I don't think this issue is related to the option "Hide shipping costs until address is entered" being active or not.

@claudiosanches, in case it helps, below is what I found about Suriname and postcodes:

- https://en.wikipedia.org/wiki/List_of_postal_codes: this Wikipedia page says that Suriname has no postal codes. The list of countries without postal codes is bigger than what I would have guessed.
- http://en.world-postcodes.com/Suriname: this page also says that postcodes are not used in Suriname.

**Comment by DollyPop007** [comment]
@rodrigoprimo thanks for those references! There are indeed still a lot of countries that don't utilize zip codes.

Thanks so much for helping with this issue guys, really appreciate it!!
