### ISSUE TITLE
Importing Attributes via CSV remove not declared ones

### ISSUE THREAD

**Issue by AdamQuadmon** [woocommerce/woocommerce#18227]
I don't think this is a bug but **a missing feature maybe**.

Having tons of products and more than 15 global attributes **I like to import product attributes from separate csv files** of attributes set.

But _if I don't declare every attribute_ in a product **the missing attributes are removed**.

Is it possible to skip deleting attributes if the attribute is not declared?
Maybe placing a filter hook somewere.
A blank value maybe can force the deletion.

**Example Import**
Assume we have two different attributes: A and B.

1st CSS import: A values
```
SKU, Attribute 1 name, Attribute 1 value(s), Attribute 1 Global
123, A, a1, 1
```
2nd CSV import: B values
```
SKU, Attribute 1 name, Attribute 1 value(s), Attribute 1 Global
123, B, b3, 1
```
I expect my product to be: `SKU: 123, A:a1, B:b3`
instead my product is: `SKU: 123, **A:null**, B:b3`

WDYT?

**Comment by claudiosanches** [comment]
> But if I don't declare every attribute in a product the missing attributes are removed.

It's not a missing feature, this is the expected behavior, so you can remove or replace attributes without too much work.

So you are required to send all data at once, or avoid the attributes columns in one file and use another to update all attributes at once.

**Comment by coo1k** [comment]
This is a problem when "updating" a product. Say I want to add certain attributes to a product which may already have attributes and variations. In this case I don't know what are the values of existing attributes(or too cumbersome to find out & update csv with). 
Now if I update the product with new attribute, all previous attributes and most importantly "variations" are removed. This is definitely not desired behavior. So I would contest this is a bug.

**Comment by Ljuk67** [comment]
Who thought it's a good idea NOT TO WARN the user that undeclared attributes will be removed during the import process? This is bad. I wanted to update 1 attribute on all my products, so now I have ended up with all products stripped of attributes. 

Seriously, this is backward logic. A deletion should be done by a specified rule/field for the specific attribute, not just by not having it in the import file. No database works like that (nothing in the WordPress DB gets deleted if I import rows into a table without specifying some columns). 

Or at least - highlight this somewhere during the import or in the attributes import spec section. I read the attributes specification for standard import and this didn't shout at me anywhere.

This is either a bug or contra-intuitive logic, therefore bad UX. Whatever it is, it's not doing what users expect it to, what is common sense.

**Comment by shaunjc** [comment]
It may be possible to automatically load in existing attributes using a filter:

    add_filter( 'woocommerce_product_import_process_item_data', function ( $data ) {
        // Skip when not updating attributes for existing products, or if an existing product was not found.
        if ( ( empty( $data['id'] ) && empty( $data['sku'] ) ) || empty( $data['raw_attributes'] ) ) {
            return $data;
        }
        $product_id = ! empty( $data['id'] ) ? (int) $data['id'] : wc_get_product_id_by_sku( (string) $data['sku'] );
        if ( ! $product_id ) {
            return $data;
        }
        $product = wc_get_product( $product_id );
        if ( ! $product ) {
            return $data;
        }
        $existing_attributes = $product->get_attributes();
        foreach ( $existing_attributes as $attribute ) {
            // Define your own function to convert $attribute into a similar format used by $data['raw_attributes'].
            $raw = custom_function_to_convert_attribute_to_raw_data( $attribute );
            foreach ( $data['raw_attributes'] as $raw_attribute ) {
                if ( $raw['name'] === $raw_attribute['name'] ) {
                    continue 2; // Attribute was supplied in CSV
                }
            }
            $data['raw_attributes'] = $raw;
        }
        return $data;
    } );

Regardless, this still seems to be a bit of an issue. Some option to merge in new attributes could be beneficial, otherwise some warning should be added to indicate that old attributes will be overwritten.

**Comment by shaunjc** [comment]
If anyone needs it, my thought of how the `custom_function_to_convert_attribute_to_raw_data` function might work can be found here (not tested).

    function custom_function_to_convert_attribute_to_raw_data($attribute) {
        $attribute_name = $attribute->get_name();
        $values = $attribute->get_options();
        if ( $attribute->is_taxonomy() ) {
            $taxonomy = $attribute_name;
            $attribute_name = wc_attribute_taxonomy_name_by_id( $attribute->get_id() );
            $values = array_map( function( $a ) use ( $taxonomy ) { return get_term( $a, $taxonomy )->name; }, $values );
        }
        return array(
            'name'      => $attribute_name,
            'value'     => $values,
            'taxonomy'  => $attribute->is_taxonomy(),
            'visible'   => $attribute->get_visible(),
            'variation' => $attribute->get_variation()
        );
    }

**Comment by shaunjc** [comment]
After testing a similar implementation to what I supplied above on my current project, I noticed that that the variations can still get a little messed up, and no longer match up to their relevant attributes, indicating one more point of failure when importing product attributes using the bulk importer.

**Comment by capodieci** [comment]
Surely it is not an expected behavior that updating say Attribute 17 would remove attributes 1..16 o_O I say this as if I update the price of all products, it doesn't remove all the other product data. I can just put Product ID and new price and it updates the prices and the rest remains intact. One expects the same behavior with the Attributes. If (as I read above) is a a feature, and not a bug, then there should be a checkbox asking if the imported file would remove the not mentioned fields or just update / add the new ones. My 5 cents.

**Comment by dawidstolarczyk** [comment]
I just encountered this error when trying to bulk add a new attribute to all products (I wanted to add the attribute: Manufacturer). It deleted all attributes across the entire store. Fortunately, I had an automatic backup from 8 hours ago, and it's a new store, so there weren't many orders in that time. Otherwise, I would have spent the whole night restoring everything to avoid losing other data and orders. 

**I WARN** against uploading a CSV with a new attribute. It can really mess up the store. Labeling the newly added attribute, for example, as "99" doesn't help either.
