### ISSUE TITLE
Two endless spinning wheels on checkout

### ISSUE THREAD

**Issue by Multimediatech** [woocommerce/woocommerce#18250]
Hello,

We are currently trying to find a solution for these two endless spinning wheels display at checkout.

Any help is greatly appreciated.

https://mymultimediatech.com

**Comment by WPprodigy** [comment]
In the future, please fill in all of the fields we ask for when you open up an issue. The information asked for is required, as we otherwise have no idea what could be going wrong.

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself and contributions. This is a conflict on your website caused by something else (another theme or plugin).

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by mikejolley** [comment]
Due to javascript errors on your page. 
![checkout multimedia tech 2017-12-21 11-21-20](https://user-images.githubusercontent.com/90977/34253833-23a3ac58-e641-11e7-8c5b-897f5f2efa2c.png)

This is not an error from WooCommerce. Looks like the page is minified so the error is not very specific.

**Comment by Cometeelcoco** [comment]
/** Disable Ajax Call from WooCommerce added in functions.php*/
add_action( 'wp_enqueue_scripts', 'dequeue_woocommerce_cart_fragments', 11); 
function dequeue_woocommerce_cart_fragments() { if (is_front_page()) wp_dequeue_script('wc-cart-fragments'); }
function disable_checkout_script(){
wp_dequeue_script( 'wc-checkout' );
}
add_action( 'wp_enqueue_scripts', 'disable_checkout_script' );

works!

**Comment by WPprodigy** [comment]
I mean, that's definitely not a good solution.

For those that end up on this thread through a google search, don't just copy/paste  that ^. Need to find which plugin or theme is causing a conflict, not just remove scripts.
