### ISSUE TITLE
Variation Scalability Issue

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#18329]
Hi

Some of my products have upto 50 variations.

This is causing a lot of queries to be generated at every page to display the price range and slowing down my site by 3-4 seconds (uncached)

Can we look into a less query intensive solution for better scalability/performance?

I checked how amazon is doing that, - they have all preselected variations, to display, product price in sliders, they only query a single price pulled from the pre-selected variation and not the complete range.

Maybe we can look into a better solution to solve it?

Partick Garman told me we can do fragment caching, sure we can but still I feel the root should be fixed instead of only putting up makeup. Correct me if I'm wrong here

![image](https://user-images.githubusercontent.com/27486232/34498530-04915b1c-f028-11e7-88e6-07952377d145.png)

**Comment by mikejolley** [comment]
There is no quick fix to this beyond turning off the features using this (price slider range) and reducing # of variations used.

FYI we're working on a custom table solution for products and attributes. When this is ready it will be announced on the dev blog and will be the most help here.

r/e price slider, we're considering pre-determined term based bands instead of the min/max slider.

Thanks

**Comment by erikdemarco** [comment]
@mikejolley any update about this? Its almost 2023 now. Still the performance problem of woocommerce is when product have many variations. the product page load so slow.
