### ISSUE TITLE
Refund via paypal is not showing on order page

### ISSUE THREAD

**Issue by vivinblack** [woocommerce/woocommerce#18337]
I am using pay-pal business account for my woo commerce shop . I Checked with Installed pay-pal express checkout plugin with my live papal api, password &signature as well as via sandbox credentials .Test orders are made via sandbox credentials .But on my order page I cant found
"refund via pay-pal " button . I can see "refund manually" & inactive  "refund 18$ via payment gateway button" .And on hover over this inactive button a tool tip message shows as "the payment gateway used to place this order does not support automatic refunds" . Is it due to customers pay-pal not able to receive payments or order made by us are from the sandbox ? help me resolve this issue .

**Comment by mikejolley** [comment]
Hi there

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout supports refunds, so if the button is missing maybe it came from another PayPal gateway? There are multiple.

Since there is no status report I cannot confirm this. This is also not the place to log issues about extensions.

Thanks
