### ISSUE TITLE
Shipping address different than Billing address

### ISSUE THREAD

**Issue by elad5600** [woocommerce/woocommerce#18334]
Hi,

I'm using WC 3.2.6 and WP 4.9.1

I received an order which the shipping address isn't identical to the billing address:

![890](https://user-images.githubusercontent.com/35059540/34512836-7b6a2b8e-f06d-11e7-8cc0-7285e1ff2b60.png)

Customers can't enter a different shipping address on my site:
![120](https://user-images.githubusercontent.com/35059540/34512891-d56d4d3c-f06d-11e7-930b-3d9b57292b23.png)

 so I don't understand how this situation could have happened.

**Comment by mikejolley** [comment]
Possibly billing method updating the address data e.g. When you send a customer offsite to pay and it has a UI for shipping address. There would be no way to do this via WC checkout. 

Since the postcode is not formatted correctly (missing a space) it looks like something has updated it outside of WC. Cannot suggest what - you didn't submit system status report.

Tested locally anyhow - both addresses are set to billing on checkout, and post code formatting is correct. Doesn't look to be a core issue.

Thanks
