### ISSUE TITLE
Dashboard Shipping zones regions does not properly render HTML entities / localized characters

### ISSUE THREAD

**Issue by alexminza** [woocommerce/woocommerce#18355]
Url: /wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=1

The [i18n/states/MD.php](https://github.com/woocommerce/woocommerce/blob/master/i18n/states/MD.php) file contains regions with localized Unicode characters which are properly displayed on the checkout page, however on the dashboard they are encoded and displayed as such, limiting the ability to search/properly configure shipping zones settings.

<img width="695" alt="34557494-1b9fabf8-f143-11e7-8aef-f25c5b994c4a" src="https://user-images.githubusercontent.com/149919/34562144-c17a3cf2-f155-11e7-9dbd-36c5a23d30a9.png">

<img width="607" alt="34557689-ca7b6860-f143-11e7-86cf-0170590d1270" src="https://user-images.githubusercontent.com/149919/34562148-c5293bf0-f155-11e7-8a00-ff9d75ab4c73.png">

**Comment by rodrigoprimo** [comment]
Thanks for your report. I did a little bit of digging and it seems to me that the problem is that `esc_html()` escapes `&abreve;` as it doesn't recognize it as a valid HTML entity.

WooCommerce calls `esc_html()` in:

https://github.com/woocommerce/woocommerce/blob/416fb697f9568fcba6a8449feea654ba8925009c/includes/admin/settings/views/html-admin-page-shipping-zone-methods.php#L50

This function uses a list of allowed HTML entities. See:

https://github.com/WordPress/WordPress/blob/master/wp-includes/kses.php#L454
https://github.com/WordPress/WordPress/blob/master/wp-includes/kses.php#L1643

I'm not sure why `&abreve;` is not included in the list of allowed HTML entities and if it should be. An easy fix to this, that doesn't involve a change to WP core, is to change `MD.php` to use `&#259` instead of `&abreve;`.

I wonder if we should change all HTML entities in the state files to use decimal references instead of named references to avoid similar issues with other HTML entities. cc @claudiosanches

**Comment by alexminza** [comment]
@rodrigoprimo it seems that the states look good in the other admin sections:

https://github.com/woocommerce/woocommerce/pull/18315#issuecomment-355336823

**Comment by mikejolley** [comment]
Escaping may be missing in other places.

@rodrigoprimo I'm happy with that change if it fixes this instance. Let's used named entities. Want to submit a PR?
