### ISSUE TITLE
woocommerce_product_search_fields filter

### ISSUE THREAD

**Issue by smachi** [woocommerce/woocommerce#18358]
The **woocommerce_product_search_fields** filter in the **WC_Product_Data_Store_CPT::search_products** method is not being used, so I'm not able to add extra meta key to be used in searches.

**Comment by claudiulodro** [comment]
`$search_fields` was never used anywhere, so [we removed it](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1309). It may be worth adding it back and actually implementing the ability to search by other meta values.

**Comment by smachi** [comment]
Yes, for me would be very useful, as I'm trying to allow users to search products by other meta keys and this would be the easiest way to do it.

Thank you.

**Comment by mikejolley** [comment]
Looking at this I found that the backend search cannot/does not use our search method because it's controlled by WP. We handle the SKU/ID search differently there. That will likely remain unless we swap the list tables out to custom ones in the future (when we do new data stores?).

Frontend also uses WP search - seeing what we can do there.

I can add the filter back to this method however.

**Comment by mikejolley** [comment]
Ok I did some digging into this and after looking everything over I don't feel we should include a filter here.

@claudiulodro 

First off, noting what is happening:

- The backend search is controlled by WP, not the data store search method. We use `get_product_by_sku` to enhance it.
- The store/frontend  is controlled by WP, not the data store search method.
- Only our custom ajax product search inputs use this method. 

Even if a filter was added here, it would not affect other searches. You'd need to hook into WP based queries to change those. It's not something we can facilitate due to the extra performance issues it would cause.

Additionally, including this filter in our data store for the search_products method goes against the system we're moving towards where the concept of `meta` is removed. We don't want people search for meta keys, we want people querying by product properties. e.g. 'sku' vs '_sku'. Our get_products method is built with that in mind.

If you want to change the WP search results and base them on meta, there are search plugins which can help. SearchWP I believe is one of them.

**Comment by mikejolley** [comment]
Thoughts @claudiulodro? I have the code stashed to add it back if needed.

**Comment by claudiulodro** [comment]
Good points @mikejolley . 

@smachi I don't think it's a good idea for us to add the filter back and do this feature. The filter would probably be around for less than a year or we'd have to build a complicated backwards-compatibility layer just for that filter when we move towards custom tables.

**Comment by smachi** [comment]
OK, no problem then. Thank you.

**Comment by luissimo** [comment]
What happened to this "we're moving towards where the concept of meta is removed"? Almost 4 years have gone by and this filter is still much needed. Just like woocommerce_shop_order_search_fields. @mikejolley
