### ISSUE TITLE
wrong order total calculation

### ISSUE THREAD

**Issue by peter-hon** [woocommerce/woocommerce#18354]
I have an order which have wrong order total calculation. How can I solve it?

![screenshot from 2018-01-04 18-31-44](https://user-images.githubusercontent.com/14814793/34559754-0574c4ae-f17e-11e7-8c08-a7ae405f0135.png)

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try WooCommerce support forums: https://wordpress.org/support/plugin/woocommerce. If you believe you found a WooCommerce core bug please reopen this issue and share all the details asked in the new issue template (expected behavior, actual behavior, steps to reproduce the issue and full system status).

Thanks
