### ISSUE TITLE
Serialized custom metadata in a product is not exported in generated CSV

### ISSUE THREAD

**Issue by okky-rymera** [woocommerce/woocommerce#18379]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a simple product, note the ID
2. Add serialized metadata by using this code:
`update_post_meta( 123, 'serialized_metadata', array('key1'=>'value1', 'key2'=>'value2') );`
where _123_ is the newly created product ID
3. Go to **Products > All Products** and click **Export**
4. Enable **Export custom meta?** and leave the other option empty
5. Generate and check the CSV

## Expected/actual behavior

When I follow those steps, I see that the **serialized_metadata** is not exported

I was expecting to see the **serialized_metadata** is exported in CSV

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: http://mylocalserver.com/rymera/dev/wwsp-wc32
Site URL: http://mylocalserver.com/rymera/dev/wwsp-wc32
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 3.24MB
Database Data Size: 2.05MB
Database Index Size: 1.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.08MB + Index: 0.05MB
wp_postmeta: Data: 0.31MB + Index: 0.34MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.08MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 23
page: 10
post: 2
product: 42
product_variation: 37
revision: 15
shop_order: 2
wafs: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
> Custom meta is supported/imported but only plain text - no support for JSON or Serialised data.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

**Comment by jkohlbach** [comment]
Hey @mikejolley any reasoning behind this? It seems weird. For import/export purposes, serialized data is just a string so its simple to support.

I'd really like to see this supported because the whole point is that WooCommerce is an extension rich environment. Extensions need to store data and they don't always do so in plain text.

The import/export is less useful if serialised data is not supported, plain text only is a weird restriction to have unless there is some other reason I'm missing?

**Comment by jkohlbach** [comment]
If its to do with broken serialised string formatting you could forcefully run it through something like this on import when a serialised string is detected:
http://blastar.biz/2011/10/18/how-to-fix-broken-serialized-string-in-php/

**Comment by mikejolley** [comment]
@jkohlbach Find me a store owner who can read, understand and edit serialised strings :p 

Plugins should filter the data on import/export and handle it in a non-serialised way. Otherwise it's not suited for CSV format.

**Comment by jkohlbach** [comment]
@mikejolley Yep, I get that, but the reality is that it's not only store owners doing the importing/exporting and manipulation, its web devs too and they _do_ know how to manipulate data like this.

Sometimes it's even exported and uploaded to other programs or apps which would know how to handle the data.

Additionally the old Product Import Suite _does_ support serialised data, and since this is replacing that suite it seems like a regression.

**Comment by mikejolley** [comment]
If we added serialised data support, it's not locked down to devs and it's something *we'd* have to support. _Product Import Suite_ caused a lot of support requests due to exporting serialised content by default.

- Serialised data is not easy to work with
- Importing serialised data wrongly can cause errors
- **Core exports no serialised data - it pre-formats it**
- CSV import is not primarily a developer tool

Rather than try to work with raw serialised data, the option we're pushing is to use the filters to format serialised data on export into text, and do the same on import. Yes it takes more effort up front, but once done it's easier for users to work with.

If the core importer is not suitable for this, thats fine. There are many other ways to import data - XML files, SQL queries, WP All import. So web devs have other options beyond the *core* importer.

**Comment by jkohlbach** [comment]
Hehe ok, I sense I'm fighting a losing battle here ;)

My only other suggestion would be to introduce a flag they could put in wp-config.php to allow it. That would mean its available for those who know how to use it, but not going to cause support issues for the everyday store owner.

We've raised dev tickets on our Wholesale Suite extensions to use the filters, so we'll explore that option instead.

Thanks for listening @mikejolley

**Comment by csalzano** [comment]
If you want to live dangerously and enable the export of serialized meta data, make this small change to WooCommerce. Changing plugin code is not recommended because your changes will be lost during the next update. https://github.com/woocommerce/woocommerce/blob/0436d8637f59726202bc4539ec4c4078e1a0e514/includes/export/class-wc-product-csv-exporter.php#L711-L713

					if ( ! is_scalar( $meta_value ) ) {
						//Allow serialized meta data
						//continue;
						$meta_value = maybe_serialize( $meta_value );
					}

**Comment by believethehyped** [comment]
> If you want to live dangerously and enable the export of serialized meta data, make this small change to WooCommerce. Changing plugin code is not recommended because your changes will be lost during the next update.
> 
> https://github.com/woocommerce/woocommerce/blob/0436d8637f59726202bc4539ec4c4078e1a0e514/includes/export/class-wc-product-csv-exporter.php#L711-L713
> 
> ```
> 				//Allow serialized meta data
> 				//if ( ! is_scalar( $meta_value ) ) {
> 					//continue;
> 				//}
> ```

Thanks! Is there also any workaround to import serialized metadata?

**Comment by csalzano** [comment]
If I remember correctly, you don't need a workaround. The serialized fields will import fine along with the non-serialized product meta fields.

**Comment by believethehyped** [comment]
> If I remember correctly, you don't need a workaround. The serialized fields will import fine along with the non-serialized product meta fields.

I have checked and that's correct! Thanks!

**Comment by benrich** [comment]
To import serialised data I also needed to do [this](https://stackoverflow.com/questions/49592027/import-woocommerce-products-with-custom-meta-dynamic-pricing-rules). Hope it helps others
