### ISSUE TITLE
Admin Order URL Filter

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#18405]
Some background on this inquiry can be viewed here:
https://github.com/Automattic/wc-calypso-bridge/issues/18

In our plugin we are over-riding the base Order email template for the sole purpose of changing the admin order URL. This has led to a few reported issues as apparently by us over-riding the template in this manner, any customizations made to the templates in a user's theme are not picked up ( /cc @mikkamp for more background there if needed ).

Ultimately - the easiest fix for us would be to introduce a filter around the admin order URL value. Though it seems like this wouldn't be a widely used filter, so I wanted to see if it was worth pursuing and/or hear some thoughts from others on the topic.

**Comment by WPprodigy** [comment]
Instead of a filter in the template, what if there was a method for `$order`s that just gets the admin link? 

`$order->get_admin_edit_link()` for example. Then that method can have a filter.

Are there any other places you're finding the need to change out the admin edit link?

**Comment by timmyc** [comment]
> $order->get_admin_edit_link() for example. Then that method can have a filter.

That would work well for us too.

> Are there any other places you're finding the need to change out an admin edit link?

I'm not aware of any other instances that have come up, but if there are other emails you can think of that might have a link to edit a product ( maybe low inventory alerts? ) - then that would be another spot we would likely need such a feature.

**Comment by dougaitken** [comment]
> maybe low inventory alerts?

Yes, the low stock inventory alert will link to the WP-Admin product edit screen.

Going to `wp-admin/admin.php?page=wc-reports&tab=stock&report=low_in_stock`, the pencil icon  will link to `wp-admin/post.php?post=[ProductPostID]&action=edit` e.g. `/wp-admin/post.php?post=1079&action=edit`

**Comment by WPprodigy** [comment]
Since Calypso rewrites all of the admin screens, I don't think these are really needed in other places for this purpose.

Template `email-order-details` x2: https://github.com/woocommerce/woocommerce/blob/master/templates/emails/email-order-details.php#L30 & https://github.com/woocommerce/woocommerce/blob/master/templates/emails/plain/email-order-details.php#L48

PayPal IPN emails x 4:
https://github.com/woocommerce/woocommerce/blob/4db2a8aa69700c9db10b5de777d9e8e9b7be95f8/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php

Structured data in emails: https://github.com/woocommerce/woocommerce/blob/93f93e3d5e9e8f822c16c4a57d36657408191908/includes/class-wc-structured-data.php#L371

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18430
