### ISSUE TITLE
There is a non dismiss-able notice across the entire admin

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#18452]
> Connect your store to WooCommerce.com to receive extensions updates and support.

The entire admin has this notice across every page, and is not dismiss-able.

This notice seems to trigger if *any* plugins have the WC helper update code to pull updates from WC.com.

Sometimes sites have a different update process that doesn't include connecting the site to WC.com and those sites shouldn't be required to see this notice on every page. 

Can we make this notice dismiss-able so that once the site owner decides and acknowledges they are not connecting their site to the mothership the notice goes away?

**Comment by kovshenin** [comment]
Adding a callback on the `woocommerce_helper_suppress_admin_notices` filter to `__return_true` will suppress this and some other helper notices. Will that work for your custom update process/setup, or would you still like to be able to actually dismiss the notice in the UI?

cc @garymurray

**Comment by pmgarman** [comment]
Store owners should not have to write a filter if they do not know code. I don’t think that is a good solution for all no.

**Comment by danieltj27** [comment]
A new setting perhaps? Tick a box to `confirm I do not wish to connect to WC.com`?

**Comment by mikejolley** [comment]
No settings needed, we just need to add core WP ui's `x` to dismiss/hide the notice cc @garymurray

**Comment by danieltj27** [comment]
Does it disappear after you've seen it the first time? Or is it there on every page load? If so, there needs to be some logic to remove it even when dismissed because the default `x` behaviour removes it from the DOM but that's it so it'll keep coming back.

**Comment by warrendholmes** [comment]
> Sometimes sites have a different update process that doesn't include connecting the site to WC.com and those sites shouldn't be required to see this notice on every page.

I'm curious which other methods Store Owners have available? I know a lot of people feel strongly about this but our thinking here has been that store owners really should connect their store to WooCommerce.com so they can get security fixes.

Even if there is consensus that this should be removed, I'd like to think about ways that store owners know what that means. I like @pmgarman's suggestion that the store owner "acknowledges" what not connecting means. If it were just a dismissable link, like most WP notices, it would be too easy to for store owners to close the notice without knowing what it really means.

**Comment by mikejolley** [comment]
> without knowing what it really means.

If you state what connecting does (enabled updates and support) surely dismissing it implies the opposite?

**Comment by mikejolley** [comment]
@bekarice suggested keeping them enabled on the plugins screen:

> sorry i missed this one today, but i don’t see why that needs to be dismissable? The previous woo helper notices were not, and i think it’s pretty important that these notices are shown so people can get updates, which has been a huge problem for support as of 3.1. even if they’re forced to be persistent only on the settings pages? we do something like this with many notices rendered by our framework: https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/class-sv-wc-admin-notice-handler.php#L91-L106 --- where they can be persistent on the plugin settings

**Comment by pmgarman** [comment]
My complaint was primarily that on **every** page there was a notice. If it was permanent on select screens I think that would be reasonable. I just don’t need to see about connecting to WC.com when I am uploading media or building a page or modifying settings of an unrelated plugin.

We deal with enough notice spam as it is, we just need to be better about it than the thousands of plugins that feel they also need to share their notice on every screen. Notice spam is one of the truly evil things in the world we live in.

**Comment by bekarice** [comment]
> Notice spam is one of the truly evil things in the world we live in.

@pmgarman I think it's superceded by not realizing you're running really out-of-date code and wondering why things are broken because you didn't know you needed to do something else in order to get updates, or missing a security fix for a plugin because you had no idea it existed 😸 

But yep, I agree every page is excessive, so if this notice is persistent on all screens under the WooCommerce menu, I think that's a good compromise between ensuring people are aware of getting updates vs impeding your ability to work on other parts of your site. thanks for adding this @mikejolley!

**Comment by pmgarman** [comment]
I can live with that, if WC can keep its noticed fixed to the WC areas of the site, anyone who wants them gone can either remove them with code or just connect. The notice I'm pretty sure is smart enough to only show up when plugins exist that would benefit from the connection, and yes you are 100% right I don't have all the scars of having dealt with the support of all the WC plugins being out of date (lately).

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18513#pullrequestreview-89857772

**Comment by jessuppi** [comment]
Am I mistaken, or is this non-dismissable nag notice still not fixed after 4 months?

It should be abundantly clear to users which plugins "need" to connect to WooCommerce.com to receive "updates and support"... this is [not the first time](https://wordpress.org/support/topic/how-to-disable-the-connect-your-store-to-activate-woocommerce-shipping/) Automattic has contradicted WP.org's own plugin guidelines, which call for clarity, honesty, and no Dashboard "hijacking".

P.S. Why does the Woo/WP.com SSO require Jetpack branding? The naming convolution is getting a bit absurd to the point where typical users don't understand the difference between these various domains, logins, and between these free/premium software/services. While Automattic may believe this works to their advantage, I would argue that it's eroding user trust across the board, and is now seeping into the WooCommerce community's reputation as well...

Ref: https://wptavern.com/wordpress-coms-business-plan-gives-subscribers-a-way-to-tap-into-wordpress-orgs-third-party-ecosystem#comment-228402

**Comment by mikejolley** [comment]
@jessuppi The discussion above which you must have skipped over shows what was decided.

It may be obvious to yourself, but if a user **does not** connect their account to receive paid extension updates, they will not be notified if updates do become available, until they connect. Once connected, it's hidden.

- The notice shows on wc screens only.
- The notice can be turned off with a filter if for some reason you don't want updates for extensions purchased. 
- The notice is not against .org guidelines, and the team there have confirmed as much.

**Comment by gpenglase** [comment]
This is **NOT** resolved as you would like to think.
No-one wants to see a persistent message on their dashboard and every other plugin page. It should be dismissable. That's what the plugin update page is there for - to alert users to plugin updates. We don't need another mechanism for this.

jessupi and others are 100% correct in saying this is unacceptable. If Automattic feels the needs to enforce this (unlike other who suggest and allow a "click to dismiss") then after dismissal they can keep it on Woocommerce screens **only**.

**Comment by warrendholmes** [comment]
@gpenglase The message only shows on WooCommerce pages in wp-admin. 

>  That's what the plugin update page is there for - to alert users to plugin updates. We don't need another mechanism for this.

We can't show plugin updates until someone has connected to WooCommerce.com.

> All I see is Automattic continually one-upping other plugin makers, and not sticking to their own guidelines, to make their plugins pre-eminent.

These aren't Automattic's guidelines - they are WordPress.org guidelines. We're not the same entities :)

**Comment by gpenglase** [comment]
So all other plugins can show plugin updates through the update.php, but not Woocommerce?  If the woocommerce plugin provides updates via the usual plugin update mechanism why is the even a need for such a connection? Why do you feel the need to force users to create a separate login/connection to your own site contrary to what other plugins do (except for the very real reason of licensing requirements for premium support)? Isn't the Woocommerce plugin GPL? why does it require such a connection - as far as I can see, it doesn't.

I must be missing something vital from the equation because this just seems to me to be a step away from the usual tried and true update process through the plugins page, to get everyone to register with the Woocommerce site.

**Comment by pmgarman** [comment]
> No-one wants to see a persistent message on their dashboard and every other plugin page.

As @mikejolley already stated and as was decided in the convo above, WC notices will be kept within the WC context. So, no, it doesn't show on other plugin pages, it should only be showing within WC. So that alone sounds like all this is resolved?

**Comment by bekarice** [comment]
@gpenglase to confirm, here's how this message works:

 - it's never shown for users only using WooCommerce and unofficial plugins
 - it's only shown if a user has WooCommerce.com plugins installed
   - and then, it's only shown on (1) the WooCommerce-specific pages, and (2) the plugins page, never throughout the admin.
- the message disappears when the user connects to WooCommerce.com

The connection is absolutely necessary -- without this, users are never notified that plugin updates are available, leaving their site open to potential issues when they miss security updates or compatibility releases. Having done support for dozens of these plugins, I can confirm that users are very upset when they don't know updates are available because this notice was missing for a couple versions after the WooCommerce Helper was moved into core.

Users can't know of updates without the WooCommerce.com connection -- the plugin updater API uses wordpress.org by default. For non-wp.org plugins, those updates must be served from somewhere for you to get notified of them. Therefore, the site has to have a connection with WooCommerce.com to even know if updates are available for plugins on the site, not only to get updates for the plugins. Again, this is only for users who have already purchased and installed WooCommerce.com plugins to ensure they know when updates are available, and to get the updates they need.

Make more sense now? Happy to add further details 😄

**Comment by gpenglase** [comment]
Thanks for your deailed response.
No, it doesn't make sense. WordPress websites already have other mechanisms used for alerting admins to the need to update plugins. They don't require registering and connecting to Woocommerce.com or any other site. So, user *can* and do know about plugin updates from their websites without such a "connection". It is quite possible for this to be done with code within the plugin, using the admin email on the site.

It is *not* necessary to enforce a persistent sitewide message. No other plugin does this, for good reason - constant messages at the top of the admin screen are annoying, but if a good reason quite acceptable, as long as one can dismiss them (even if they reappear in a month or 2 or 6 or 12). 

This is purely something that Woocommerce wish to enforce for the purpose of getting users to register. For those who update in different ways, or so no need for it at all, it is simply a PITA. 

Again, Automattic is not listening to the community. it seems to me that it is enforcing it's own methods for it's own purposes.

**Comment by jessuppi** [comment]
This thread is getting a bit political, but the misinformation is rather obnoxious. The WooCommerce team seemed quite straightforward and acted in "good faith" prior to acquisition by Automattic. It's sad to see the continued shift toward on-again, off-again clarity and ethics, which let's face it, mostly comes down to mental gymnastics in a quest to justify and explain Automattic's inconsistent behavior.

> These aren't Automattic's guidelines - they are WordPress.org guidelines. We're not the same entities :)

This game again, really? Who runs the WordPress Foundation? Cheekily flaunting your disregard for the WordPress.org guidelines lends more credibility to the perceived favoritism/hypocrisy.

If a third party plugin added a notice saying "WordPress updates won't work unless you click over here and register on our website" it would surely be banned within a few days.

> As @mikejolley already stated and as was decided in the convo above, WC notices will be kept within the WC context. So, no, it doesn't show on other plugin pages...

It's a bit incredulous how so many talented WC developers aren't able to run a few simple tests to realize this statement is far from accurate. The notice continues to show on the Plugins page, 6 months after this issue was originally created on GitHub (and elsewhere).

Again, if it's going to show on the Plugins page it should specify which "plugins" need it; but frankly, if it shows up anywhere at all, it should still specify which plugins need it.

> The connection is absolutely necessary -- without this, users are never notified that plugin updates are available, leaving their site open to potential issues when they miss security updates or compatibility releases.

Uh, wrong again, it's only "necessary" because of Mullenweg's pushing the SSO (Jetpack).

==

I think most people in the WordPress community are happy to see WooCommerce take on the likes of Shopify and other privatized fiefdoms of online commerce, and surely a centralized app store (and maybe even an SSO/login) help to achieve this. However, arguably the flagrant "bad faith" decisions being made by WooCommerce in the past 1-2 years as Matt aggressively pushes Jetpack and slicker centralized branding are making everyone question where the line is...

And honestly, the condescending/cheeky comments here only further that negative tone.

**Comment by gpenglase** [comment]
V. nicely put Jesse.

All I (and others) want is for Woocommerce.com to follow in the footsteps of all the other plugin makers who allow notices such as these to be dismissable (even if they reappear after a few months), or only persistent on the specific plugin pages. Simple request really. Funny thing is that we want to get behind Automattic and Woocomerce to make this platform the best it can be - and would be happy to support an open fair-minded company in it's efforts to do this, but these sorts of moves, and the overly expensive yearly subscriptions just to maintain up-to-date versions, alienate us and our clients.

So getting back to the initial topic... None of us want lots of header alert spam especially if it is persistent, (note: error alerts are another thing entirely), and not all of us want to be forced down this update road - especially when there are existing alternate methods, use other update systems, or update our own code, ie. have customised version of said plugins. Yes, I can add a hook to remove the notice (and will do), but seriously?

**Comment by jaclyntan** [comment]
I tried using
`add_filter( 'woocommerce_helper_suppress_admin_notices', '__return_true' );`
and the jetpack message is still there. :( What's the right filter to use to disable this notice?

**Comment by claudiulodro** [comment]
The WooCommerce Services plugin needs to connect with Jetpack, otherwise the plugin will **literally do nothing**. That is why the notice is not dismissible in that plugin. It uses the Jetpack connection for accessing the Services.

I'm closing comments on this issue, as we've already resolved the discussion about notices here.
