### ISSUE TITLE
Handle missing wp_termmeta db table

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18502]
Just debugged a ticket where product categories did not show up after they were created. 

Somehow, the `wp_termmeta` table was missing / never installed. This is a new-er table in WP, and some Google searches show it has happened to a few people.

 Opening up an issue here though because post categories/tags and product tags still worked correctly, just not product categories. So perhaps there could be a check first to make sure the table exists?

Also would be nice if the system status report looked for and alerted about missing core tables.

**Comment by mikejolley** [comment]
@WPprodigy Since this is a WP Core issue I don't think we should handle our side. The min WP supported version for WooCommerce is more recent than the introduction of that table, so we should be safe/within reason to simply assume it exists. Our status report already lists WP tables anyway, so if wp_termmeta is missing you have a problem :)

There is only one way to fix a missing table like this - something like https://technical.sabhlokcity.com/2017/04/recover-missing-wp_termmeta-table-in-wordpress/ manually.

Create a help doc? Cases of this should lesson over time, not increase, because it happened so long ago, so adding code to core for this seems low priority.
