### ISSUE TITLE
Bug fix WooCommerce 3.3.0 RC1

### ISSUE THREAD

**Issue by RAlzar** [woocommerce/woocommerce#18516]
Hello!

In the course of testing of WooCommerce 3.3.0 RC1 the essential mistake which is desirable for correcting has been revealed.

[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/Edit_product_page_with_empty_view_product_page.html) a code of the page admin panel WordPress > Products > Edit of a product page (with the established WooCommerce 3.3.0 RC1) which don't work product pages.
[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/System_report_do_not_work_version.txt) a System report don`t work version.

[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/Edit_product_page_with_work_view_product_page.html) code of the page admin panel WordPress > Products > Edit of a product page (with the established WooCommerce 3.1.2) which work product pages.
[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/System_report_work_version.txt) a System report work version.

I hope that the error of WooCommerce which has appeared in versions after 3.1.2 will be corrected.

With respect and the best regards
Ruslan Pysanka

**Comment by mikejolley** [comment]
You have not even said what the problem is, let alone steps to reproduce it?

I suggest you read https://github.com/woocommerce/woocommerce/issues/new and take some time to report the issue in more detail. The links you've provided are just a mess of HTML so it's impossible for us to see what the issue you're referring to is.

Thanks
