### ISSUE TITLE
[3.3 RC1] grouped.php double .quantity class

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#18542]
Was this standelone `.quantity` class `esc_attr( $column_id )` meant to be added?

https://github.com/woocommerce/woocommerce/blob/06a7570f4bfff1482c2daa710b47342e2bdbe868/templates/single-product/add-to-cart/grouped.php#L87

Because of the `quantity-input.php`  already outputs this class:

https://github.com/woocommerce/woocommerce/blob/65464d3a02be367b3c7b86a51e904d7c03cb97cf/templates/global/quantity-input.php#L31

It will/can cause a problem to attach custom quantity JS scripts and CSS styling.

**Comment by mikejolley** [comment]
Maybe those scripts and styles should be more specific instead of targeting all current and guture .quantity elements on the site...

The single class can go, but it will affect styling of .price and .label. I don't think we should add a conditional here to make the markup inconsistent between cells.
