### ISSUE TITLE
/cart/?add-to-cart=variation_id adds more then 1 quantity

### ISSUE THREAD

**Issue by itjunkii83** [woocommerce/woocommerce#18644]
Visit this link and refresh a few times to see arbitrary quantities added:

https://mario.trifectanutrition.com/cart/?add-to-cart=2401&quantity=1

I have tried to disable all plugins except Woocommerce and Woocommerce Subscriptions and I still get the same results. System report https://pastebin.com/6TkCpgx1

I am happy to audit my code, but I am doing nothing that modifies url's or adding to cart (that I know of) - if I revert to a 2.6.x versions this works fine.

public static function add_to_cart_action( $url = false ) in wc-form-handler.php is getting called 4 times per 1 visit to this url.

**Comment by WPprodigy** [comment]
Just tested using WC 3.3 on a test site and couldn't replicate this. Must be someting else involved here.

**Comment by mikejolley** [comment]
There is something odd in the source above the html:

`
get fbuy_ref_code: <br />
`

Anyhow, the cause is something in the theme most likely - if you view the inspector you can see it loads the same page twice:

![cart - trifecta nutrition 2018-01-30 10-16-57](https://user-images.githubusercontent.com/90977/35560931-c4b41022-05a6-11e8-86fc-6e60f3bfcb17.png)

It doesn't happen on other installs so looks to be theme specific.

**Comment by itjunkii83** [comment]
Wow...embarrassed I didn't look into that - thank you for getting back to me!
