### ISSUE TITLE
[3.3] Everybody can register without password check (on older form-login.php)

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#18688]
If users have a theme that is not updated yet, or don't update at all, the register button is enabled all the time. And can register without proper password check.

Per change of https://github.com/woocommerce/woocommerce/commit/978e693

**Comment by mikejolley** [comment]
In this case I don't think it's worth patching for the client side validation. The template files have been bumped so themes will need to update those buttons to the new format to benefit.

Not doing so doesn't 'break' registration, just disables validation. Thats acceptable and this is certainly not as critical as https://github.com/woocommerce/woocommerce/issues/18674

Due to the nature of templates and their versions, we cannot support old templates forever, thats why there are warnings (and why we discourage template overrides completely).

**Comment by JimmyAppelt** [comment]
It was just an observation, so I reported it.
