### ISSUE TITLE
Not working some function after update woo 3.3.0

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#18687]
Hi Support Team,

We have updated woo 3.3.0  after not working below condition in our theme function file. why ?

`
if (! wc_get_loop_prop( 'is_paginated' ) || ! woocommerce_products_will_display())`

So please you can give me solution for this issue.

Regards!

**Comment by fazlurr** [comment]
Yeah, same problem here.
The function `woocommerce_products_will_display()` is returning `false` even in shop page.

`function woocommerce_products_will_display() {
	$display_type = woocommerce_get_loop_display_mode();
	return 0 < wc_get_loop_prop( 'total', 0 ) && 'subcategories' !== $display_type;
}`

`wc_get_loop_prop( 'total', 0 )` returning 0, because `$GLOBALS['woocommerce_loop']` is `undefined`.

Is there any settings in WooCommerce that can break the `$GLOBALS['woocommerce_loop']` ?

Thanks for the support and the great hard work for providing the last update.

**Comment by mikejolley** [comment]
If called before the hook `woocommerce_before_shop_loop` these props may be empty.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18700

**Comment by presslayouts** [comment]
Yes Mile, But old version is working fine, so why not working latest version?

Please you give me hint for resolve this issue.
