### ISSUE TITLE
Woocommerce product export not working 

### ISSUE THREAD

**Issue by prasidhda** [woocommerce/woocommerce#18774]
While trying the CSV export of products,instead of generating the CSV, it is throwing the raw data in browser. This was happened only in production site. In staging site, it is working fine. Is this issue is server related? 

WooCommerce version: 3.2.6

**Comment by kloon** [comment]
I am unable to replicate this in my development environment so this is likely a server related issue, especially since you are also saying it works on your staging site.

I'd suggest you test this in production with all plugins disabled except WooCommerce and also with your theme set to a default theme like Storefront.

Sounds like something might be intercepting your headers so the correct one is not passed to the browser to make the file download.

**Comment by prasidhda** [comment]
Thanks . It was server related issues. Solved now. :)
