### ISSUE TITLE
No way to insert new setting in particular admin settings group/section

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#18798]
For example, it is possible to add settings to the My Account settings tab via the `woocommerce_get_settings_account` filter (example below shows custom "Registration endpoint" setting). However, this array is totally unordered so you just get new settings dangling off the bottom:

![image](https://user-images.githubusercontent.com/507025/35772362-5396d7b2-0902-11e8-9b27-6ab545c9ae27.png)

My suggestion would be to add some kind of `priority` key and then sort the results, perhaps via `wp_list_sort()`.

So that when filtering the settings you can insert the new settings into the desired position, ex:
![image](https://user-images.githubusercontent.com/507025/35772528-6c6d0136-0906-11e8-8658-382bfbc88cd0.png)

**Comment by mikejolley** [comment]
I understand it's harder to insert options in the place you want, but it's not impossible. You just have to loop over the existing settings and insert into the correct place one you have the numeric array key.

- Priority would be one solution.
- Adding keys to the settings array would be another.

That said, I don't think we should make these changes just yet; one of the things that came up with 3.3 was how the REST API changes whenever we make a settings change in core. Because of this, we're contemplating an API driven settings screen so you'd register settings in a standard way for the API and WP admin settings page. I've noted this down in https://trello.com/c/PiIhOt3v/132-dedicated-settings-api-with-wp-admin-views-which-interact-with-the-rest-api-for-saving so it's not forgotten and we'll try to look at scoping it out in more detail later this quarter.

Cheers
