### ISSUE TITLE
Search for customers doesnt search with guest orders

### ISSUE THREAD

**Issue by LetMeKnow1** [woocommerce/woocommerce#18802]
In Orders screen there is a box to search orders of specific customer.
If the order is done by guest checkout the search won't find it:
![455](https://user-images.githubusercontent.com/35699825/35778293-fd12b99c-09c4-11e8-87ba-49edf08d7d0d.png)

Currently there is no way to search orders placed by guests. This is very much needed to track orders when the order number is unknown (time passed, missing invoice etc...)

WC version 3.2.6

**Comment by WPprodigy** [comment]
That field searched for actual customers only.

You can use the search field here to search for names and email addresses: http://cld.wthms.co/HQBZW8. At least in WC 3.3.1+

**Comment by LetMeKnow1** [comment]
I see that now... In this case I think the UI isn't user friendly.
I consider guests to be customers as well so the "search for a customer" string isn't the best choice to explain what this search box does.

Also, for the field that you mentioned it says "search orders" I understand that it's search per order number not for guest customers nor emails.

May I ask why can't a single search box perform all searches?

**Comment by mikejolley** [comment]
Because a 'guest' has no customer object in your database. Unless they are a real user, there is nothing to display.

Creating customer objects for guests is an option but it may have privacy and other issues making is undesirable. Perhaps put something on ideas.woocommerce.com for this to see if there is any interest.

For now, both strings are accurate - the customer one could be tweaked but I don't know what to. "search registered customers?"

**Comment by LetMeKnow1** [comment]
Hi Mike,
What is the logic in having 2 different search boxes that searches over the same data?
You can handle 1 box that run search for registered customer name, guest customer name , email and ordernumber. See for example the search panel in amazon seller center there is one search box that searches anything. 

From my point of view anyone who bought in my site is a customer regardless if he is registered or not. The text on the box "Search for a customer" is confusing. I expected it to find my non-registered customer but it didn't... that is why I opened this ticket. If you decide to leave the two separated search boxes then it requires to change the text near/in each box so it would be clear what it searches and what not.  I still think that there should be only one search box that searches anything. Registered customer or guest customer makes matter only in where you perform the search in the backend.

**Comment by mikejolley** [comment]
They are not searching the same data.

One searches customer records (registered users) and then once you select a user, it filters the orders to only their own.

One searches order data.

Not the same.

**Comment by LetMeKnow1** [comment]
Hi Mike,

Search for a customer has two steps:
1. Query which finds customer according to given string.
2. When users confirm one of the result it searches for the orders that match.

Search orders has one step:
1. enter string (guest name, email) click button and see the orders that match.

At the end - both gives the same result - Orders filtered to the search pattern.

I claim that the search box should be combined with one step. 
You are already doing it:
![355](https://user-images.githubusercontent.com/35699825/35804229-8ef15f84-0a7f-11e8-83dc-c4eeea3eb8cd.png)

Summary:

1. If you combine the two searches - it would be awesome.
2. If you don't combine it would be better to work on the screen interface.  It's not user friendly (if I was confused other will be too.. it should be easy to understand. For example:
  put both search options one near the other so when we look at one we will see the other too. I didn't even noticed it until WPprodigy showed it to me. 
Please understand that when you speak as a programmer and you say Customer it is clear to everyone that you are referring to Customer table or whatever method you use to save them. When you speak to store owners and you say Customer we think it's ALL our customers.. we don't distinguish between guests and registered hence the confusion.

**Comment by mikejolley** [comment]
Your argument falls apart when you have 2 customers named PAUL.

**Comment by LetMeKnow1** [comment]
@mikejolley  Why so? Normally when people perform search they get less rows.. then they re-search more accurate with to get less until they find what they are after.

I can claim the same thing on the existed method. Say I have 8000 customers named Paul. How do you expect me to filter the 8000 Pauls I see ? I give more letters... It's the same thing.

**Comment by mikejolley** [comment]
Still this is generalising. There could be names/terms which overlap several customers. Names are not unique.

Search lets you search upon all fields and find matching orders.

The customer filter lets you show only orders from a user you can select from the dropdown. The fact it's a 'search' itself is only because a dropdown of 1000's of customers would not be performant or practical. Additionally, other screens link though with customer ID already set so you can see the results of the filter right away. Merging the 2 fields therefore is not an option. 

We can update the placeholder text.

**Comment by LetMeKnow1** [comment]
Any change that will make it easier to understand is great

**Comment by jranavas** [comment]
In the actual operation, I vote for change "Search for a customer" with the more accurate text "**Search by registered customer**", similar as mentioned by @mikejolley https://github.com/woocommerce/woocommerce/issues/18802#issuecomment-363057902
This is because we are searching orders by data, not searching data.

Also, the "Search" button can be "**Filter**", because in both cases, is done a search upon all fields and find matching orders with introduced data.
