### ISSUE TITLE
Filter removed with no deprecation warning

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#18824]
With https://github.com/woocommerce/woocommerce/commit/75041b6dca5c540b363d0bc1dc021c8b3d9b8df2 the `woocommerce_resend_order_emails_available` filter was removed, is no longer triggered and no deprecation warning is logged. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Subscriptions is, for example, hooking onto `woocommerce_resend_order_emails_available` and removing all the email actions as none of them apply to subscriptions with the following code: 

```php
add_filter( 'woocommerce_resend_order_emails_available', __CLASS__ . '::remove_order_email_actions', 0, 1 );
...
public static function remove_order_email_actions( $email_actions ) {
	global $theorder;

	if ( wcs_is_subscription( $theorder ) ) {
		$email_actions = array();
	}

	return $email_actions;
}

```

Because that filter is no longer triggered and the email actions are now added to the `woocommerce_order_actions`, order emails are being displayed on Subscriptions. Now that we've discovered this, we can obviously switch to the other filter however other third-parties wouldn't have any idea that this filter has been removed.

**Comment by mikejolley** [comment]
Hi @james-allan 

I don't think it's possible to trigger a deprecation warning if the filter/action does not exist. In this case the functionality was also removed.

The Email actions themselves (ability to **resend** certain emails) do not exist any more. `woocommerce_resend_order_emails_available` is no longer relevant. If using the filter to remove emails, since there are none, the code would do nothing.

We have only one email sending action now - `send_order_details`. This is essentially the customer invoice email template which is only used in this instance.

It's obviously too late to add a filter like this back now (it went in 3.2 I believe) so if there is a better way of notifying of these changes lemme know.
