### ISSUE TITLE
Stock isn't reduce in variable product.

### ISSUE THREAD

**Issue by vanloc0301** [woocommerce/woocommerce#18858]
WC: 3.3.1

## Steps to reproduce the issue

I using function `wc_reduce_stock_levels( $order->get_id() );` to reduce stock in parent variable product.

But it is not working in the variable product.

I use the variable product creates 3 colors of my product.

Like this: 
Product `Hecquin` is parent product has 21 product in the stock.
```
Hecquin         - blue hair     - 25 product in stock.
                - yellow hair   - 3 product in stock.
                - red hair      - 10 product in stock.
```
![capture](https://user-images.githubusercontent.com/4168981/35940338-5b43c3bc-0c81-11e8-95d8-93447dd72d01.PNG)

At frontend, I choose `Hecquin red hair` has 10 product in stock and buy this product.
![capture1](https://user-images.githubusercontent.com/4168981/35940611-52ab3374-0c82-11e8-8bfb-ba56dd946a6e.PNG)

I using function `wc_reduce_stock_levels( $order->get_id() );` to reduce amount of number in the product.
But it only reduces in parent variable product. Don't reduce the amount of number in the variable product.

You can see here:
![capture3](https://user-images.githubusercontent.com/4168981/35940617-57b4056c-0c82-11e8-89ba-f0388df51d93.PNG)
I check again, it still is 10 product. Don't have any stock in variable product reduce.

Problem is: it only reduce stock in parent product while I choose a variation of this product. Should reduce the stock of product variation instead of parent variable product.

**Comment by claudiulodro** [comment]
What are the line items on the order? When you add a product to the cart, it should be the variation product and not the parent product. `wc_reduce_stock_levels` [reduces the stock from the whatever product is the order line item](https://github.com/woocommerce/woocommerce/blob/05d6e393ae243e080602277f7335a7f649bab79c/includes/wc-stock-functions.php#L97), so if the parent product is in the cart it will reduce that and if the variation is in the cart it will reduce that.

Should be something like this (with a variation ID) if you examine the order line item in the order admin:
<img width="746" alt="screen shot 2018-02-07 at 2 01 17 pm" src="https://user-images.githubusercontent.com/7317227/35943993-d436eb68-0c0f-11e8-88a3-58bcbb05bbb7.png">

I'm going to close this issue because it works fine for me and the code for `wc_reduce_stock_levels` looks correct.
