### ISSUE TITLE
[3.3] Shortcodes Conflict when on Shop Page

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18859]
https://wordpress.org/support/topic/product-shortcodes-not-working-2/

1) Set shop page display to categories or categories and products: http://cld.wthms.co/nwdZ3P

2) Add a shortcode to the main shop page: 
`[products per_page='4' columns='4' category='clothing']`

3) View shop page: http://cld.wthms.co/Da15mE

4) Remove shortcode and view shop page: http://cld.wthms.co/lpcd02

Categories and appended to the shortcode's results. Category+products display settings get you this: http://cld.wthms.co/KjfAl2

**Comment by claudiulodro** [comment]
It seems to be something to do with `woocommerce_get_loop_display_mode` and/or the functions defined underneath it in `wc-template-functions.php`. 

We set the display mode by checking if the current page is the shop page and the shortcodes are getting caught in that. 

The "no products" message happens because we do `$wp_query->post_count = 0;` in category display mode.

**Comment by claudiulodro** [comment]
See #18888
