### ISSUE TITLE
Should `woocommerce_hide_invisible_variations` be true by default?

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18864]
Shouldn't this filter be true, by default?: https://github.com/woocommerce/woocommerce/blob/3300534963f83cb0ec685510e90ef3fd07dd875f/includes/class-wc-product-variable.php#L276

If a variation is disabled, I can't imagine why the shop owner would want it to show up as an option, pending the `woocommerce_ajax_variation_threshold` isn't being met.

Not sure if something around this area has changed recently, but there's been a lot of forum threads about people seeing attribute options that they didn't see before updating.

https://wordpress.org/support/topic/non-enabled-variations-display-on-products-shop-page

**Comment by mikejolley** [comment]
No this has always been false.

https://github.com/woocommerce/woocommerce/pull/6182

I notice the same thing happens all 3.x branches so this is not new with 3.3.

We could grey them out by tweaking variation_is_active to match variation_is_visible. Let's do this for 3.4 because it may have side effects. PR coming.

**Comment by wouter1407** [comment]
Did something changed with this filter? All variations are still showing instead of just the ones with a price. I've tried adding this snippet to my theme functions.php file, without result:

add_filter( 'woocommerce_hide_invisible_variations', '__return_true' );

Something i'm missing here?

**Comment by josecunyat** [comment]
This is still behaving the same way. You added a milestone for 3.4.0 version, but we are in 3.5 and the issue remains the same. I have 52 variations in a product. The variations come from 3 attributes:
-attribute 1: 4 values
-attribute 2: 14 values
-attribute 3: 2 values

When I had the half of the variations this was working properly, but when I did add more then started to behave in a way I don't like. For example in Value 1 of attribute 1 only 8 values of attribute 2 should show up. But I keep seeing all of them. This confuses customers because they can choose many options which are actually not available and will never be. So they need to guess and try/error until they find something that works. I find it as a really unpleasant experience...

**Comment by wouter1407** [comment]
> This is still behaving the same way. You added a milestone for 3.4.0 version, but we are in 3.5 and the issue remains the same. I have 52 variations in a product. The variations come from 3 attributes:
> -attribute 1: 4 values
> -attribute 2: 14 values
> -attribute 3: 2 values
> 
> When I had the half of the variations this was working properly, but when I did add more then started to behave in a way I don't like. For example in Value 1 of attribute 1 only 8 values of attribute 2 should show up. But I keep seeing all of them. This confuses customers because they can choose many options which are actually not available and will never be. So they need to guess and try/error until they find something that works. I find it as a really unpleasant experience...

This snippet added to the theme's functions.php file fixed the problem for me Jose:

```
function custom_wc_ajax_variation_threshold( $qty, $product ) {
     return 50;
 }

 add_filter( 'woocommerce_ajax_variation_threshold', 'custom_wc_ajax_variation_threshold', 10, 2 );
```
