### ISSUE TITLE
problems on mobile phones viewing orders

### ISSUE THREAD

**Issue by legion33** [woocommerce/woocommerce#18893]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
As a online store owner the 3.3.1 version is a nightmare in terms of using it on mobile phone. The new columns settings in the orders section can't be seen properly on mobile phone. The preview column/setting is worthless and should be removed or made as column with the flexibility to remove it.

**Comment by WPprodigy** [comment]
Do you have plugins modifying this screen / adding columns?

This works fine for me on mobile: http://cld.wthms.co/oYxI7R

**Comment by legion33** [comment]
Indeed it seems it was a displaced style of column because of the plugin I use to see purchased items - very  helpful. Now I deactivated and it has same view as yours. In the desktop view in front of of sign # followed by order no appears the word preview. 
Coming back to mobile version - the new version makes me do more actions in order to reach to see the items purchased both pictures and titles.

**Comment by WPprodigy** [comment]
The text preview will only show if either a plugin conflict is happening, or you just need to clear cache and browser cache to get new styles to load.

**Comment by whereskarlo** [comment]
It's a real shame they also removed the order status from the mobile view. Now you had to click every order to even know if it's completed or in process. You even can't select orders on mobile anymore. Who is making these decisions? It makes Woocommerce more cumbersome to use. I can't fathom why anyone would think it's a good idea to remove the order status column from mobile view?

**Comment by mikejolley** [comment]
WooCommerce doesn't style the mobile view, WordPress does. Go look at other screens.

**Comment by whereskarlo** [comment]
Not true. The Woocommerce wp-admin orders page was changed to the new look
that omits important information on mobile (and on desktop too I'd argue).
That wasn't done by Wordpress. The products page still has the old layout
which has an abundance of options and information no matter if on mobile or
desktop.

On Feb 23, 2018 11:17, "Mike Jolley" <notifications@github.com> wrote:

WooCommerce doesn't style the mobile view, WordPress does. Go look at other
screens.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/woocommerce/woocommerce/issues/18893#issuecomment-367968558>,
or mute the thread

**Comment by mikejolley** [comment]
Post list tables in WordPress all hide everything but the title column. Go look at posts/pages.

**Comment by whereskarlo** [comment]
Posts and pages look totally different from the orders page. The orders
page has much less information.

Why did you decide the current layout for the orders page was better than
the old? Keep something like order stats for mobile view otherwise
Woocommerce stops being mobile friendly.

Think about it. You get tens or hundreds of orders daily. Without even
knowing which one is complete and which one is processing how are you going
to do anything useful while accessing via mobile?

**Comment by mikejolley** [comment]
You could use the filters at the top of the page for one.

**Comment by whereskarlo** [comment]
Why was the layout changed?

**Comment by whereskarlo** [comment]
Here's another problem on mobile. You see on the Woocommerce backend that
there is (1) new order. You click on orders and are greeted by a list.
There could be pending payment, on hold orders above the new order. The
only way to find out which one is processing is to click the sorting
filters up top. The list serves no purpose whatsoever on mobile if there is
no distinguishing attributes between the orders except name.

Please add back the status indicator on mobile. It makes no sense to remove
it. You're just making the plug-in more difficult to use on mobile. You
could have kept the little icons you had been using since the last 4-5
years. Or should third party plugins take over the role of status
indicator? This is feedback from a real world user, please take it
seriously. I'm sure there are others why are frustrated by this change as
well.

Removing the status indicator does not add utility. It removes utility.
There is no justifiable argument for removing utility from a system when
the removal doesn't serve a better purpose.

**Comment by mikejolley** [comment]
I don't think you're listening to anything I'm commenting, just ranting the same thing?

> The
only way to find out which one is processing is to click the sorting
filters up top. The list serves no purpose whatsoever on mobile if there is
no distinguishing attributes between the orders except name.

The filters will show all orders of a certain status. So if you want to process orders, click it and look down the list/preview each order. You know the status will be the one you selected.

> Please add back the status indicator on mobile. It makes no sense to remove
it

> You're just making the plug-in more difficult to use on mobile.

There is limited space on mobile. So for obvious reasons, leaving all the order columns in place won't work.

As I said, WordPress handles the mobile views. To even add columns back in mobile view would require custom CSS on top of the WordPress CSS, and then the thing is not going to look great as you'd need to either have horizontal scroll or stack items utop one another.

**Comment by mikejolley** [comment]
Because I know what CSS is responsible and I'm not making this up?

WooCommerce changed the columns in desktop view, but the mobile view is handled by WP where all columns are hidden except for the main column.

![orders local wordpress dev wordpress 2018-02-23 11-58-08](https://user-images.githubusercontent.com/90977/36593249-d6f12fc0-1890-11e8-993f-db8cea18c94a.png)

**Comment by whereskarlo** [comment]
In that case I'm guessing the status indicator used to be part of the main
column on the order screen, because it used to be visible on mobile. After
you changed the desktop layout, the status indicator no longer was part of
the main column and thus not visible on mobile. Sounds plausible?

Would you consider this use case and if you can make the status indicator
part of the main column like it used to? Or just consider if there are ways
to preserve the status indicator on mobile? I'm not trying to shit on your
show, but I use Woocommerce all day everyday and now it's really difficult
on mobile due to the status column not being visible. The order page is
just a long list of names and numbers with nothing to discern what belongs
where in a chronological context.

**Comment by mikejolley** [comment]
> The order page is
just a long list of names and numbers with nothing to discern what belongs
where in a chronological context.

I don't understand whats wrong with filtering by status, and then you see new to old orders in a list. What is the problem? If you filter the list there is not need to show an order status column.

**Comment by whereskarlo** [comment]
The problem is that I loose very valuable insight into the status and
health of the store. Knowing if the last 5 or 10 orders are in process, on
hold or pending payment requires different types of response by the store
manager.

All this nuanced chronological detail is lost on mobile. The filters are
great once you are ready to take action, like exporting orders in process.
But it is incredibly helpful to see the status of orders chronologically on
the order page because it gives insight into customer behavior and
potential store problems.

There might be 5 processing orders and 25 payment pending orders. The 5
processing orders can be dealt with by using the filter, but it is likely I
won't notice there are 25 orders pending payment preceding the processing
orders unless I use desktop. Knowing this detail is important because it
shows something is off in the checkout flow, or perhaps there are issues
with the gateway. The order page with visible status is very helpful in
getting a real life snapshot of the health and status of the store and is
what I base most actions on.

The filters' main drawback is that they don't show the relationship between
the different order statuses. I want to know the proportion of different
statuses in relation to each other to know if everything is alright in the
store.

Most Woocommerce/e-commerce shops will receive a wide variety of processing
orders, orders in need of manual attention/on hold, pending payment,
cancelled orders and so on. Being able to see the statuses helps the store
manager discern if there are problems and also easily check that everything
has been dealt with.

On Feb 23, 2018 14:05, "Mike Jolley" <notifications@github.com> wrote:

The order page is
just a long list of names and numbers with nothing to discern what belongs
where in a chronological context.

I don't understand whats wrong with filtering by status, and then you see
new to old orders in a list. What is the problem? If you filter the list
there is not need to show an order status column.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/woocommerce/woocommerce/issues/18893#issuecomment-368003932>,
or mute the thread

**Comment by whereskarlo** [comment]
PS: even just the colors yellow, green and red from before would be
helpful. Or can I manually bring back the old layout by using an older
stylesheet for the desktop view?

**Comment by mikejolley** [comment]
> I want to know the proportion of different
statuses in relation to each other to know if everything is alright in the
store.

The statuses have counts beside them! And thats at a glance, vs scrolling to view every row. I don't know if I'm missing your point here but it sounds like the filters do everything you're complaining is missing?

**Comment by whereskarlo** [comment]
You're missing the point. The counts are not in chronological order. If I
have 20 pending payments, I don't know if they are 6 months old or all came
within the last 48 hours. The point is being able to browse a chronological
order list on mobile with visible statuses to be organized and know what's
going on, compared to clicking view on every single row or going into the
filters without seeing the bigger picture.

The current unfiltered mobile view tells me nothing important. It is just a
list of names and order numbers without context. Without knowing what is
complete and what needs processing, what's the point of having an
unfiltered list at all?

**Comment by mikejolley** [comment]
So I just checked the older version. On mobile the only difference is the status icon is visible. Everything else is pretty much the same. 1 column of data.

> I don't know if they are 6 months old or all came within the last 48 hours

It's still not obvious in the old version. There is no date visible.

Why would the status name in mobile view help you? What are you intending to do when you look at orders on mobile?

**Comment by whereskarlo** [comment]
Regarding the lack of date, since the orders are chronological and ordered
by date, I can still discern which orders are new and which orders are old.
I check the orders page a few times per day. If orders are processing, I
need to send them to the corresponding warehouses for shipping. If orders
are on hold, certain information like bank details need to be sent to them.
If  they are pending payment we need to investigate why the payment didn't
complete by contacting the customer.

I use mobile and desktop interchangeably. For regular store management I
have been able to do it all on mobile for days at a time thanks to the
excellent interface. It's quite an achievement when your plugin allows
people to work for days on end from mobile only. Thumbs up.

Here's the issue: The orders page in Woocommerce is the central point of
order management. When I can see the order statuses on a chronological
list, I know instantly which orders to ignore because they are completed
and can focus my attention on those processing or on hold. If I see a bunch
of completed orders I can focus my attention on the orders above because
they are all in chronological order. I also see the order flow and know if
a lot of pending payments have come in. It is a great tool to know whats
going on *without wasting time*.

On mobile on the orders page, I just see a list of orders but *without
anything to discern what I should direct my attention to*. I don't know
where the completed orders end and the in process or on hold orders begin.
I don't get the full snapshot without having to click the eye icon and
memorizing at which order number I have completed orders to. With a colored
symbol I know instantly which orders need my attention. *With no symbol I
have to manually inspect with the eye icon (and also double check to avoid
errors) and memorize order numbers, to know which orders in the
chronological list I should focus my attention on. *

I am trying to do the exact same thing on mobile and desktop, which is
order management. The main orders page is the greatest tool for this
because it adds context and a superb overview. The status is needed to make
sense of the orders and help where to focus attention. Otherwise too many
clicks and memorization is needed to be useful. The status symbols solve
that by showing what is complete what what is not.

**Comment by mikejolley** [comment]
> If I see a bunch of completed orders I can focus my attention on the orders above because
they are all in chronological order.

I'm still not sure why you'd rather scroll through than just filter by processing. If you filter by processing, the orders are still chronologically, and you know all the orders in the view need action.

I get your point about the main view being less useful, but I don't understand why you're dismissing the idea of using the filters.

**Comment by whereskarlo** [comment]
I also use the filters, I am not dismissing them at all. I'm just saying it
is very useful to know, by looking at unfiltered orders, whether or not the
latest order is processing, cancelled, on hold or pending payment, without
clicking the eye icons. These statuses are so important for order
management, so having them visible makes the unfiltered order list a lot
more useful. Without them, the only use for the unfiltered view is clicking
on the eye icon, unless you already know which order number you are after.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19111

**Comment by whereskarlo** [comment]
That's a great solution! Thanks for listening.
