### ISSUE TITLE
Do we need to bring back a dedicated size for gallery thumbnails?

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#18910]
There has been some push back on the decision to have just one thumbnail size, mostly due to the gallery.

Typically the gallery shows the thumbnails at a smaller size, cropped squares. The display size is smaller than the actual catalog thumbnail size so there are concerns that this will damage page speed etc.

Not keen on adding a whole new settings section for these. Thinking about options:

- We could add image size options for the gallery thumbs
- We could use the WordPress thumbnail size so it's at least configurable
- We could add some filters and allow themes to configure this size independently.

Would like to get feedback before making any changes.

**Comment by cyihats** [comment]
after i made updates on woocommerce/archive-product.php. my thumbnails are smaller size and cropped squared in my mobile version of my site i think were having the same problem ive tried everything to fix this problem but ran into a brick wall

**Comment by WPprodigy** [comment]
Another possible option: Since gallery full-size images are also loaded on the page, what about just using the single product images size instead for both thumbnails and enlarged? Then only one image needs to be loaded versus two different sizes.

**Comment by cyihats** [comment]
My products are not the same size as they used to be In my store pages in mobile version 


CYi Hats
Rep Your City
www.CYiHats.com

**Comment by yatgirl** [comment]
My 2 cents I was initially upset over the change - but then I always found the image sizes confusing and I would prefer to keep things as is and just adjust my thumbnails size with CSS as for supported themes, it is not possible to change the size any other way anyway.  Using Storefront and Boutique theme, with just 1 css adjustment for category thumbnails and related products thumbnails, my site looks just as before. The gallery images are a perfect size - so is everything else.

**Comment by spencerfinnell** [comment]
I think if you can get past the initial push back having fewer options is better. Add some filters for themes if they need it, but otherwise the image sizes have always seemed to confuse our users more than help them. 99% of sites are responsive so having "fixed" image dimensions only confuses people when an image might not appear exactly the same size as the dimensions entered.

I would vote use global thumbnail settings for gallery thumbnails by default with the necessary filters to adjust if needed.

**Comment by cyihats** [comment]
My product images are fine in desktop mode my problem is in mobile mode I can’t find a way to fix this 



CYi Hats
Rep Your City
www.CYiHats.com

**Comment by WPprodigy** [comment]
@cyihats Would you mind opening up a support thread in the WordPress.org forums? This issue isn't for debugging image problems.

**Comment by WPprodigy** [comment]
Regarding your edit @yatgirl 

> Themes are made to be customized, not dictated

This is true. But changing an image size in the settings will have no affect unless the theme planned for those images sizes to be used. It will at a minimum require custom CSS.

If changing a setting has no visual change without also adding custom code, the user is going to be confused. (Can post 100's of support requests for this exact reason)

**Comment by ywatt** [comment]
I would like to have an additional setting for the thumbnails. With the 3.3.1 update, the only way for me to have a thumbnail is to resize in the CSS (to 90px for example), but the image served is still the 300px one (size of the product in the product list).
If the size of the main image would be the same (300px) then it would not be too much of a problem, as the images needs to be loaded anyways. But if the size is set higher (for example 500px) then if I am not mistaken the 300px and the 500px images will be loaded, instead of 90px and 500px. If you have big gallery that could make a difference for the user experience.
Note: I like very much the fact that these options are now in the appearance/customize with real time update, cool stuff :)

**Comment by SorinGFS** [comment]
@mikejolley and @WPprodigy 
I think we should look at the problem from a greater distance: 

There are two basic scenarios:
1) themes could use default woocommerce gallery or
2) themes are replacing the woocommerce default gallery with their own (most of the cases)  like:
`remove_action('woocommerce_product_thumbnails', 'woocommerce_show_product_images', 5); 
add_action('woocommerce_product_thumbnails', 'theme_show_product_images', 5); `

In the past there were no side effects for the second scenario, but since this enforcement to have two image sizes instead of three a lot of functionalities have been broken. I tried to prevent you about this, with no luck. Just think a bit: there not just the gallery thumnails are using the old thumnail size, but checkout page, cart page, emails, view order, product sliders, and so on... All those have been broken. 

So this is not just a matter of page speed, or of thumnail regeneration mechanism, or of crop positioning, or any other problem that woocommerce didn't think of before release. The third image size must exist!

Now, talking about woocommerce style image gallery... Most important: it must work as espected out of the box! It must have separate filter for thumnails and main image, it must be responsive especially for mobile! Personally I like the zoom functionality, but mean while I need a slider for thumnails, so if I cant have it directly from woocommerce ... I must replace it completely. 

Another thing that should be taken into consideration is the product editing speed: think you have to edit 1000 product, each one of them having 10 images. In this scenario the most important factor is automation. You should be able to just upload the images and have them displayed as espected without any further customization. So, by estabilishing an aspect ratio of image being used and setting the same aspect ratio in woocommerce settings should solve the problem. By this, you should be able to get everywhere images cropped corectly. 

Just my 2 cents.

**Comment by ajgw** [comment]
I do not see any reason why we should get back to more images sizes til now. But I wasn't able to do some tests about pagespeed. If this makes our site slower than before, only then it should be as before. How about extensions like Product Bundles, Composite Products or Variation Swatches and Photos? Did they work that way? In case of Variation Swatches and Photos were I have often ten to fifteen thumbs as color swatches, are they loaded at full size too?

**Comment by mikejolley** [comment]
@SorinGFS 

> In the past there were no side effects for the second scenario, but since this enforcement to have two image sizes instead of three a lot of functionalities have been broken.

Why do you say enforcement? WC doesn't block anyone from registering their own image sizes?

**Comment by SorinGFS** [comment]
@mikejolley 
Your question sounds like WC doe block anyone to build their own plugins and themes? @mikejolley

**Comment by mikejolley** [comment]
> Another possible option: Since gallery full-size images are also loaded on the page

Need to look into this. If it's true, this is a non-issue as the optimisation argument will be void.

If it is a problem, one option would be to base the thumbnail size on single size / number of columns. Our gallery shows the thumbnails in columns below main image. We can allow themes to set the width.

**Comment by SorinGFS** [comment]
@mikejolley 

>  

> Our gallery shows the thumbnails in columns below main image. We can allow themes to set the width.

**Comment by mikejolley** [comment]
Looking at the network view in chrome I can confirm, the gallery slider loads the larger version of the image (single) for each image in the gallery.

So right now, for a gallery of 4 images, it loads:

- 4 thumbnail categories
- 4 single size images

Full is loaded on the fly by zoom plugin.

It looks like this could actually be optimised by loading single sized images for each gallery item. We can wrap in a filter to make this easy to customise should you disable the gallery for any reason. 

Best of both worlds?

**Comment by SorinGFS** [comment]
@mikejolley 

>

**Comment by mikejolley** [comment]
@SorinGFS Why load a small image, AND a large image when we can just load 1 image (large)

**Comment by SorinGFS** [comment]
@mikejolley 

no no, I think your solution is good, to load a single size image for both situations, the main image and the thumnails since it will be wrapped properly, but I mean is there any reason left not to have the third size back for other possible purposes?

**Comment by mikejolley** [comment]
@spencerfinnell ah good point. Will need to test how that works since large is uncropped.

What do you think of a size based on single width, for the number of columns flexslider would use?

**Comment by SorinGFS** [comment]
@mikejolley 
I think the number of columns must be configurable within settings.

**Comment by SorinGFS** [comment]
@mikejolley 

Please consider that in most of the cases site owners want to load a variable number of thumbnails (images) and use a slider to have them on a single row. For this reason we need to have distinct filter for the thumbnail part, for being able to load only the zooming image and replace the second filter (the thumbnail part) with custom slider.

**Comment by mikejolley** [comment]
@SorinGFS Please stop making off topic feature requests...there are already filters for the gallery as a whole. 

In the context of this issue, we only care about the core gallery.

**Comment by SorinGFS** [comment]
@mikejolley 
I meant not filters for gallery as a whole, but separate filters for main image and thumbnails part. Is there any filter for main image only? Or for thumnails only?

**Comment by SorinGFS** [comment]
@mikejolley 
please put yourself in the theme editor shoes, what can you do if you want to use the zooming part because it works nice, and don't want to use the thumnails part because of the lack of options? Or because you want to use a slider, or because you simply want to put the thumnails elsewhere?

**Comment by mikejolley** [comment]
PR open for feedback https://github.com/woocommerce/woocommerce/pull/18947
