### ISSUE TITLE
Custom product booking

### ISSUE THREAD

**Issue by heldervilela** [woocommerce/woocommerce#18926]
I'm creating a store with a booking system.
I do not want to use any third party plugin to create the booking system.

So I am developing my custom code to be able to create a system that allows managing the stock of the product by the date of the reservation.

I'm having a hard time knowing how to manage product availability by date.

eg: If someone makes a reservation to a product on day X it should be out of stock only for this day, and that information should be saved so I can remove the product of the search page.

I'm not looking for code, I only want some opinions on how it will be the best way to do it. 
eg: what hooks to use, if I should create a table or use meta options to save the info.

**Comment by LetMeKnow1** [comment]
Why not simply use stock management? You can set a stock for the item and once it goes 0 it will be shown as out of stock and customer won't be able to order it.

**Comment by WPprodigy** [comment]
For performance reasons, you're definitely going to want to have custom database tables. There is a lot of data to track when it comes to bookings - each day of the month, possibly hours, different resources / quantities, different costs for different time periods, etc.

Can't really help with customizations like this here though. If you're determined to build your own system rather than extending/using extensions that already exist, then good luck :)
