### ISSUE TITLE
The admin products table is styled to make adding columns difficult

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#18972]
My subtitle code adds a column to the products list table. At desktop view it's a little narrow, but passable. When shrinking to tablet view it's only 1 character wide. The strict widths on all WooCommerce core columns don't leave much space for any custom columns.

![edit products table at tablet width](https://user-images.githubusercontent.com/507025/36230219-541a1014-119f-11e8-9aba-b263aeba59fa.png)

**Comment by mikejolley** [comment]
Not sure much can be done here. Some px can be cut off those icon columns. The others however are just % based column widths. 

I'd probably say it would need to be pretty important data to justify adding a custom column, and data which you can sort by. And you'd definitely need to add CSS to enforce a width like all the others or it will be crushed.

Responsive styles can help by hiding columns on smaller screens but this leads to confusion due to screen options i.e. "the column is on but I cannot see it".

Could move SKU into Name column because you'll lose ability to sort on SKU. Not sure if thats important.

Could reduce data in date column. Could also combine cats and tags, or move elsewhere.

**Comment by helgatheviking** [comment]
>And you'd definitely need to add CSS to enforce a width like all the others or it will be crushed.

True. I didn't want to load a stylesheet for just that plugin because it's fine with other WP post types, which have less aggressive styling, but I will find a way to make that work.

Looking at it from another way, if there was a hook in `render_name_column()` a subtitle might sit well just beneath the title and not in an extra column.
