### ISSUE TITLE
Need a way to exclude a product from WC_Discounts->validate_coupon_product_ids()

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#18971]
I was thinking that the products added by Free Gift Coupons as free products, should not be counted towards satisfying the requirements of a product (or product category's) usage restrictions. 

It's pretty edge case, but if for some reason you make "Widget A" a free gift but require the same "Widget A" be in the cart to use this coupon, you can skirt the usage restriction. 

"Widget A" can be added to the cart, the coupon applied which adds a second "Widget A" to the cart. Now, the first paid "Widget A" can be removed from the cart, but but since there's still a "Widget A" in the cart, the coupon is still valid since `WC_Discounts->validate_coupon_product_ids()` still finds the free "Widget A" in the cart.

I'd say a free gift product should also be excluded from counting towards `validate_coupon_product_categories()` and perhaps the product and category exclusions? My thought is that it just shouldn't be counted. Perhaps `set_items_from_cart()` and `set_items()` could use a filter?

This is fairly low priority, just thought I'd throw it out there.

**Comment by mikejolley** [comment]
Sounds reasonable. Would you raise a PR for this instead of issue? I took a quick look at the code and I think the best way to handle this would be to add a new `get_items_to_validate` method which returns `$this->items` with a wrapping filter. This could then be used in all validation functions.

Reason I ask for a PR is that I could add this, but you can test this with your plugin prior to submission to ensure it does everything needed :)

Thanks!

**Comment by helgatheviking** [comment]
I'll see what I can do about a PR.

**Comment by helgatheviking** [comment]
@mikejolley there's already `get_items()` method. Should I just add a filter there or do you want a new method?

**Comment by mikejolley** [comment]
@helgatheviking No a new method is better as that old method should get ALL items in the class (it's just a getter). The new function will have added context.
