### ISSUE TITLE
State/Country Dropdowns do not work on Checkout Field

### ISSUE THREAD

**Issue by Laura-Sol** [woocommerce/woocommerce#18987]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

For example on this product: http://wilsonsworkouts.nl/product/strength-training-runners/
When I get to the checkout, the country drop down doesn't work, and because of that the payment options don't appear. 

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
Pretty sure you have your settings at WC > Settings > General a bit messed up. Looks like you have it set to only sell to specific countries, but didn't select any countries.

If that's not the case though, then please fill out the full issue report template. Need your system status report, and also need you to test whether or not this happens when only the WooCommerce plugin is active along with a default WordPress theme.

Will re-open once you've filled out all the required information.
