### ISSUE TITLE
Bug fix WooCommerce after 3.1.2 version

### ISSUE THREAD

**Issue by RAlzar** [woocommerce/woocommerce#19013]
Hello!

After updating of a plugin WooCommerce 3.1.2 to the new version, instead of contents of pages with goods, empty pages open.

[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/Edit_product_page_with_empty_view_product_page.html) a code of the page admin panel WordPress > Products > Edit of a product page (with the established WooCommerce 3.3.0 RC1) which don't work product pages.
[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/System_report_do_not_work_version.txt) a System report don`t work version.

[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/Edit_product_page_with_work_view_product_page.html) code of the page admin panel WordPress > Products > Edit of a product page (with the established WooCommerce 3.1.2) which work product pages.
[Here is](http://files.drealm.nu/Downloads/WooCommerce_bug_fix/System_report_work_version.txt) a System report work version.

I hope that the error of WooCommerce which has appeared in versions after 3.1.2 will be corrected.

With respect and the best regards
Ruslan Pysanka

**Comment by GlennMartin1** [comment]
WC 3.3.1 is the present version. 

There were known issues in WC 3.3.0 regarding a range of issues which have since been addressed, as explained here: https://woocommerce.wordpress.com/2018/02/01/woocommerce-3-3-1-status-update/

Upgrade to WC 3.3.2, and confirm your theme is up-to-date. 

If issue persists, try with Storefront theme, and if issue still persists, deactivate all plugins except WC. 

Only after that is complete should any issue be opened here.

**Comment by RAlzar** [comment]
That's just the point that this mistake arose in all versions after 3.1.2

**Comment by GlennMartin1** [comment]
Your system report says you're running WC 3.3.0. That's not the latest version.

Your system report says you have 31 active plugins. You're to test with only WC active.

Your system report shows you're not testing it on a WP theme or Storefront.

**Comment by mikejolley** [comment]
This is likely due to using SHARED versions of themes/plugins - wplocker etc. You do realise these can contain malware? I've seen them insert malicious code into plugins/themes. **Not good for a store - think of your customers!**

Suggest you get the site cleaned by a pro and only install purchased extensions and themes. The output on your screenshot doesn't look like anything any other user has ever reported since 3.1.
