### ISSUE TITLE
GET Payment Gateways - no pagination support

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#19016]
The docs for the REST API state that "Requests that return multiple items will be paginated to 10 items by default".

I've just noticed that this doesn't appear to be the case with the payment_gateways endpoint. The following will return all Payment Gateways instead of just the first 10:

`GET wp-json/wc/v2/payment_gateways?page=1`

I get 14 returned instead of the first 10.

**Comment by mikejolley** [comment]
"Requests that return multiple items will be paginated to 10 items by default" is in general. Gateways AFAIK don't paginate; it just returns all of those available. Same for shipping methods. Doesn't make sense to paginate these and having > 10 sounds rare. Think about if you had for example a settings screen for gateways; this wouldn't be paginated.

Rather than change the code, we should just update the docs and state these are unpaginated.

@claudiosanches I'm updating the docs.

**Comment by claudiosanches** [comment]
On the headers you have information of there is any page there.
Always check the headers before try pagination.
