### ISSUE TITLE
Please stop changing the product image and thumbnail code every time !!!

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#19052]
Can you please stop changing the product image and thumbnail php over and over again?

Please make the new function pluggable and add a filter for the classes in the returning div.

Every time i have to change my theme code over and over again because of the woo changes made. 

That function should not be static but pluggable.

`function wc_get_gallery_image_html( $attachment_id, $main_image = false ) {

}`

This class within that function should have a filter

`class="woocommerce-product-gallery__image"`

**Comment by mikejolley** [comment]
A filter on the return may be possible but please don't adjust the markup too much as themes/plugins may rely on it.

**Comment by BackuPs** [comment]
@mikejolley 

The theme I use, uses its own on the fly resizing and lightbox for single woo product pages. They add classes to the div around the image and the image itself. Since their are no filters for that in the new function they can not use that anymore and have to replace the new function in total.  In the previous version the complete image code was in the php files itself making it easy to alter. Now you moved it and altered it and did not add filters on every element that could be changed.

_________________________________ below not related to my question ______________________________

What i read and hear on other forums is that people dont like the woo lightbox for the single product page. No thumbs and no indicators on mobile that there are more images. I read on  forums theme users complaining about the blurry images (thumbs and single product image) since those themes removed their product image and thumbs php files from their customized woo templates. 

Asking them why they did remove their own image coding they replied that they got tired having to customized their code over and over again when woo changes their code without being backwards compatible.

Woo changed the single image and thumb code in v 2.x.x, again in 3.10, in 3.3.0 you removed the width, height and cropping settings as they used to be and replaced them with completely different settings in the customizer. Themes where using these old settings  ! And now in 3.3.2  again you change the code for the single image files creating new issues on themes again.

I have bought a lot of themes and what used to work nicely and looked ok, changed for worse during updates of the woo plugin. On updates shops and single pages start looking different and not as nice as they used to be. I bought those themes because i liked the designs.

Developers, i guess, have better things todo then always to run after code changes because of a plugin, especially on such short intervals.

**Comment by mikejolley** [comment]
I'm not sure why you are here speaking for the theme author. Seems counter productive.

I'm going to go into a little more detail here so we can document this/refer back, and so there is no confusion about this going forward.

---

**template files**. Template files work in isolation. There is no 'backwards compatibility' between them, and this is why they are versioned. Each file has a disclaimer:

>  HOWEVER, on occasion WooCommerce will need to update template files and you (the theme developer) will need to copy the new files to your theme to maintain compatibility. We try to do this as little as possible, but it does happen. When this occurs the version of the template file will be bumped and the readme will list any important changes.

If you change a template files, you do so understanding that they will change. There is no point moaning about changes to these files when they are inevitable. If we need to fix something, or add a feature, templates have to change. They cannot remain stagnant for all time.

Don't want to deal with that? Don't override templates. Use hooks and filters instead.

**Functions;** these belong to WooCommerce and do specific things. We will no longer be making these pluggable because it adds uncertainty around how they should work vs what they do if plugins replace them. If we add a function, it has a specific purpose (for core) which should not be changed without good reason.

Don't like how a function works? Create a custom function. No one forces you to call the one we use in core. 

---

> Asking them why they did remove their own image coding they replied that they got tired having to customized their code over and over again when woo changes their code without being backwards compatible.

Don't cry foul when template files and functions change in WooCommerce core to support new features/fixes. It's inevitable. It's documented. It should be clear. There are other options.

In this use case, this function has been created to move php logic out of a template file so future updates to that logic does not need a version bump. It will not be made pluggable. It does not need a filter. The CSS classes inside are sufficient.

**If replacing the entire gallery; there is no need to edit template files. Unhook our gallery, replace with your own custom gallery. That will be independent from changes in core and work going forward.**

> On updates shops and single pages start looking different and not as nice as they used to be. I bought those themes because i liked the designs.

It frustrates me that theme authors get eCommerce functionality for "free" and use it as a marketing tool, but when it comes to contributing, testing, helping the platform, most do nothing. If there is a change, most blame WooCommerce. This doesn't sit right with me. Why do we scramble to fix compatibility problems with themes who didn't bother to test? IMO this should change. If not willing to support the platform, don't integrate with it.

> What i read and hear on other forums is that people dont like the woo lightbox for the single product page. No thumbs and no indicators on mobile that there are more images.

It would be in everyones interest to contribute to the core gallery rather than fragment the marketplace and replace the gallery with custom implementations. Consider that.

cc @warrendholmes 

> Developers, i guess, have better things todo then always to run after code changes because of a plugin, especially on such short intervals.

Like count their money from theme sales? :)

**Comment by BackuPs** [comment]
@mikejolley 

Thank you for the extensive reply.

> Don't want to deal with that? Don't override templates. Use hooks and filters instead.

There is no filter or hook to override the  class="woocommerce-product-gallery__image" and add your own classes.

This is what i have been asking for. Consider adding it!

**Comment by mikejolley** [comment]
> Because every time woo updates i have to run behind these template builders informing them that stuff does not work anymore and wait for fixes.

I think that says something about the themes you're using. It's not your job to chase theme devs. If they "support" woocommerce, they should be keeping on top of things. Not you, the customer.

**Comment by BackuPs** [comment]
@mikejolley 

You are not answering my question. Can you pls do so?

> There is no filter or hook to override the class="woocommerce-product-gallery__image" and add your own classes.

> This is what i have been asking for. Consider adding it!

**Comment by mikejolley** [comment]
I responded in my long reply. The answer is no; replace the function.

**Comment by BackuPs** [comment]
i am not asking for a replace function. I am asking for a filter to be able to add my own classes to the classes in that function !

**Comment by mikejolley** [comment]
It's not needed. Lightbox scripts can use the `.woocommerce-product-gallery__image` class, or the theme author can use their own function and not call ours. As explained above.

**Comment by alessiolovecchio** [comment]
> Unhook our gallery, replace with your own custom gallery. That will be independent from changes in core and work going forward.

This solved instantly a problem that I'm having today. So simple, so brilliant. Thank you @mikejolley

**Comment by sasanmoradidev** [comment]
@mikejolley your nice answer lightened my way on theme developing. Thank you.
