### ISSUE TITLE
Declaring theme support, template overrides not working.

### ISSUE THREAD

**Issue by wcjonathan** [woocommerce/woocommerce#19063]
As of the latest update, if you have a custom theme you have to add the following line to functions.php

`add_theme_support( 'woocommerce' );`

Not having this line in the functions.php meant that any template overrides were ignored.

This is not in the documentation for WooCommerce (i couldn't find it anywhere). Could this be added to the documentation? I don't believe this is clear enough.

Thanks to @adamfaux85 for finding this fix.

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/guide-for-declaring-woocommerce-support-in-themes/
https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes

Theme docs are a WIP. We'll get them updated.

No need for an issue because it's not a bug/issue in core.

cc @claudiulodro @californiakat  Can we get something added to https://docs.woocommerce.com/document/template-structure/ in the meantime?

**Comment by californiakat** [comment]
@mikejolley It's already on my To Do list. I've just come back from AFK, I have deadlines for marketing to meet, and I'm trying to get caught up
