### ISSUE TITLE
Method for retrieving tax status on shipping rate

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#19131]
As far as I checked, there is no way to retrieve a shipping rate status.

The use case is as follows:
I'm in `woocommerce_after_calculate_totals`, trying to get the shipping tax totals, so there's a tax rate defined and shipping is applied from it. But the shipping rate used is "Flat Rate" with status taxable = false.

So in the DB, there is this information:
```
mysql> select * from wp_options where option_name = 'woocommerce_flat_rate_24_settings';
+-----------+-----------------------------------+-------------------------------------------------------------------------------------+----------+
| option_id | option_name                       | option_value                                                                        | autoload |
+-----------+-----------------------------------+-------------------------------------------------------------------------------------+----------+
|     16385 | woocommerce_flat_rate_24_settings | a:3:{s:5:"title";s:9:"Flat rate";s:10:"tax_status";s:4:"none";s:4:"cost";s:2:"10";} | yes      |
+-----------+-----------------------------------+-------------------------------------------------------------------------------------+----------+
```

But if you use the cart contents, you get `WC_Shipping_Rate` instances which do not have this method defined.

So the problem is in general, there is no neat way or helper method (as far as I've checked) to get the data for the chosen shipping rate given cart contents.

See how the workaround was addressed: https://github.com/woocommerce/woocommerce-shipping-multiple-addresses/pull/176

**Comment by mikejolley** [comment]
A rate does not store all of the data of the shipping method. Current way of doing so, in line with your workaround, is to:

- Get shipping method using instance ID/method ID
- Use `is_taxable()` method.

The code you linked to looks like a workaround for a workaround. It would make way more sense to refactor core to use the PACKAGE shipping address for taxes rather than the customer. 

https://github.com/woocommerce/woocommerce/issues/19137
