### ISSUE TITLE
No access to feature products in products

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#19147]
Hi Devs, I set in my store products to featured product. But if I like to change the products marked as featured, there is no sorting or selecting option in admin. In this case I have to go through all my products and mark them manually. Isn't there any sorting or filtering possible?

**Comment by mikejolley** [comment]
This will require a snippet - found this https://gist.github.com/lukecav/5263416ca83aaf9b5f94cee4b1458285

It cannot be sortable by featured due to technical limitations of terms. I think a good solution in the future would be to have a unified search/filter box so you could limit to features but this is a long way off and would need the design teams input. These screens are due a revamp over the next year anyhow.

Thanks
