### ISSUE TITLE
 Firefox: form inputs have placeholder text cut off

### ISSUE THREAD

**Issue by R33D3M33R** [woocommerce/woocommerce#19152]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Expected/actual behavior

The inputs in woocommerce forms have line-height set to 1. They render fine in Chrome and IE11, but in Firefox (I'm using 58 on Debian Stretch) the input is rendered with lower height and placeholder text gets cut off:

![woocommerce-line-height-firefox](https://user-images.githubusercontent.com/12114725/36729686-4d324fc0-1bc5-11e8-999a-ec956d805a34.png) 

The simplest solution would be use line-height: normal or not set it at all.

Best Regards,
Andrej Mernik

**Comment by rodrigoprimo** [comment]
Thanks for your contribution, @R33D3M33R. I was not able to reproduce the issue you described on WooCommerce `master` branch and using the theme Storefront. I tested using Firefox 58.0.2 on Ubuntu 17.10.

Below is a screenshot of what I see on my cart page and the line height of the coupon code input seems right:

![screenshot from 2018-02-27 10-07-47](https://user-images.githubusercontent.com/77215/36730461-3680de28-1ba6-11e8-8974-80c5dcd1b64f.png)

Maybe the problem is in the theme that you are using?

If you still feel that this is a WC core issue, could you please share more details? Specifically, could you please share your system status report (WooCommerce > System Status in WordPress admin)?

**Comment by R33D3M33R** [comment]
Hello,

Storefront uses a normalization ruleset which sets the line height of inputs to 1.618 and therefore it displays nicely in Firefox.

If you are developing a custom theme with core woocommerce.css included, you must always manually override these line-height rules if you wan't the text to display properly in Firefox.

I think we should let the browser compute the line-height instead of forcing it to 1 in core woocommerce.css.

Best Regards,
Andrej

**Comment by rodrigoprimo** [comment]
I appreciate you taking the time to give more details.

> I think we should let the browser compute the line-height instead of forcing it to 1 in core woocommerce.css.

Makes sense to me but I'm not the best person to make a call here. @tiagonoronha and @jameskoster   any thoughts on this?

**Comment by mikejolley** [comment]
Seems ok to remove. See https://github.com/woocommerce/woocommerce/pull/19174
