### ISSUE TITLE
Missing States for many countries

### ISSUE THREAD

**Issue by NitinPrakash** [woocommerce/woocommerce#19180]
Hi, I have noticed States/Provinces missing for many countries. I am using WooCommerce version 3.3.3

1. AF
2. AL
3. DZ
4. AS
5. AD
6. CM
7. KI and many more

I hope these, all countries are also important if developing a global e-commerce application.
Thanks in advance

**Comment by mikejolley** [comment]
Hi @NitinPrakash 

If users from those countries request states/send a PR we'll happy merge. We don't want to include states for all however because some countries don't use them predominantly on checkouts.

For example, here in the UK it's very uncommon to have a dropdown of states/counties because we just type them and they don't affect shipping.

if you're from one of those countries and wish to add them, please go ahead and raise a PR. 

https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md
