### ISSUE TITLE
Sorry, it seems that there are no available payment methods 

### ISSUE THREAD

**Issue by ayyaz66** [woocommerce/woocommerce#19182]
I have an online store everything is fine  some time  user facing an error 
"Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements."

i am using COD payment method  . i am trying to solve but still not solved . I will be very thank full if any one can help me .

**Comment by WPprodigy** [comment]
Rule out plugin/theme conflicts: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

**Comment by mikejolley** [comment]
Also note COD has some rules which could cause it to become disabled:

![woocommerce settings local wordpress dev wordpress 2018-03-01 09-58-26](https://user-images.githubusercontent.com/90977/36838463-1f71dbd2-1d37-11e8-97b8-e3c9823661ff.png)

Configure those properly and consider a fallback gateway for those who cannot use COD.

**Comment by Architechnium** [comment]
> Go to Woocommerce > Settings > Subscriptions (tab) > Renewals (section) > and check Accept Manual Renewals. Your payments should work.
Thank you! this saved me so much time

**Comment by ukprinter** [comment]
I dont see a subscriptions TAB...what am I doing wrong?

**Comment by jamenl** [comment]
I also encountered this error when using COD i.e. cash on delivery. Issue is not payment gateway but payment setup. Unlike old advice recommended above their is also not tab for subscriptions in the latest woo commerce.  This is how I solved it.

1. Under Woocommerce click on settings. You will see the following tabs; General, Products, Shipping, Payments, Accounts & Privacy, Emails, Integration, Advanced.

2. Click 'Payments' tab. You will see a list of payment gateways, Direct Bank Transfers, Check payments, Cash on Delivery, Paypal including the ones you have setup i.e credit card, stripe, mpesa etc. 

3. Enable the payment tab you have setup for your site.

4. Click 'manage'

5. You will see a list of options under Enable/Disable click Enable. 

6. Skip title and description, scroll down to option titled - "Enable for shipping methods" Click on the whitebox and you will see the shipping zones you had set under shipping zones i.e Flat rate, Local Pick up, Free. Click on the shipping zones you are offering that you want the payment gateway to be able to process

If it is not there got to shipping zones and create the shipping zone by location and rate charged either Flat rat, local etc.

7.That its it. Error doesn't appear. Its an error which is generated when you do not include the shipping zone under the payment gateway. It has nothing to do with currency or subscription

**Comment by rickfisk** [comment]
This error can also happen when your live key does not get stored. I had the same issue as described. I had tested payments in test mode which worked as expected, reset to live mode, pasted in the live secret but the live key I pasted in was not the live key. So the value wasn't stored in the database (it filters on pk_test and won't save the key).

When I went into settings for stripe, I saw that the field wasn't populated and a second time entered in the wrong value. (wrong value in the paste buffer). Finally I saw that the plugin says it won't even attempt to save a test key if its in live mode. Smart actually because it would be pretty lousy to save the wrong key and have things look as if they were working.

**Comment by webbeddevelops** [comment]
Often this can be caused by API/Key/Cert issue, if not then a piece of information is missing in the settings. For Woocommerce it could be no shipping zones, in my recent case I was using Square and I had not selected a "Business Location". If API is good make sure all fields are filled out in Woo and Gateway settings, and be sure the payment tab is set to on.

**Comment by laurenproctor** [comment]
For me, the solution ended up turning on Enforce settings for my LetsEncrypt SSL certificate. The second the checkout was on https://, the message went away.

**Comment by Faisalgroup** [comment]
I facing the same problem.. how to solve it?

**Comment by karstengresch** [comment]
Same problem here. There's COD enabled and displayed as available in the block editor, delivery zone is setup, but still this weird error message occurs.
