### ISSUE TITLE
Woocommerce is rounding discount coupon down

### ISSUE THREAD

**Issue by ncpmt** [woocommerce/woocommerce#19223]
I have a problem in making the coupon discount on checkout to work properly.

The subtotal is: 3,65
discount 10% is: -0,36 it should be -0,37

For more details: 
https://imgur.com/a/1KP8b

Anyone had the same problem? How to round it up?

**Comment by Uriel1339** [comment]
That's interesting because I just tested a product here which is at $199.99 with a 10% discount and it applies $20, which rounds up accurately from 19.999.

See screenshot:
![image](https://user-images.githubusercontent.com/13288488/36929003-6207a076-1e59-11e8-9903-a2dd7e4a83e5.png)

But when I re-did your items I got the same result. 0.36 instead of 0.37 are deducted. The exact difference is 0.365.

And furthermore I did take my testing to the next level. I increased the cost of the 1st item from 2.06 to 2.07. So that the 10% discount comes off to a -0.366 discount and properly applies a -0.37 discount.

So I believe that all that needs to be done is to fix the round-up from .005 up, instead of at .006. 

See Screenshot:

![image](https://user-images.githubusercontent.com/13288488/36929183-69748d90-1e5b-11e8-8e23-5c62dbf4adb3.png)

**Comment by ncpmt** [comment]
Thank you for the testing. How can I change the rounding up to be from .005?

Thanks@

**Comment by mikejolley** [comment]
Constant `WC_DISCOUNT_ROUNDING_MODE` uses round half down. This is so a 50% discount would be in the favour of the store. Change `WC_DISCOUNT_ROUNDING_MODE` constant to 1 to round half up.

**Comment by ncpmt** [comment]
I have inserted define( 'WC_DISCOUNT_ROUNDING_MODE', 1 ); in my themes functions.php and nothing changes. Should I insert it somewhere else?

**Comment by ncpmt** [comment]
Nothing works..maybe any other ideas?

**Comment by imknight** [comment]
facing the same problem, for my case is due to the woocommerce store credit plugin, might want to check is there any other plugin that call woocommerce_coupon_get_discount_amount filter and mess with result.

**Comment by Chunkford** [comment]
@mikejolley this may be a stupid question, but a constant is a fixed value is it not?
So changing it outside of woocommerce will throw an error
e.g. `PHP Notice:  Constant WC_DISCOUNT_ROUNDING_MODE already defined in....` as I'm getting currently in my debug file.

For an easy and quick solution, would it not be better to store the option value in the options table instead? I'm happy to do this if you think this is correct.

**Comment by mikejolley** [comment]
@Chunkford you need to define it earlier e.g. in wp-config.php
