### ISSUE TITLE
REST API not working at all on PHP 7 and above

### ISSUE THREAD

**Issue by danielmoorehbd** [woocommerce/woocommerce#19251]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Rolled back PHP to 5.6, it works!
2. Added the consumer key and secret to the end of the GET request, still an issue on PHP 7
3. Tried multiple clients, same issue presists, but only when on PHP 7 and above.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by WPprodigy** [comment]
Can't replicate, and I know for sure it works on PHP 7 for others.

You might have a plugin or some custom code that isn't PHP 7 compatible on your server?

**Comment by kloon** [comment]
Also not able to replicate, I run PHP 7.2 and tested this with 7.1 and in both instances the API functioned correctly for me.

I suggest you disable all plugins except WooCommerce and then switching to a default theme like Storefront and test again, as @WPprodigy mentioned this could be due to a plugin or theme you are running.

In the future when logging an issue it would help immensely if you can also provide the system status report as that contains details that could help us pinpoint where the issue lies on your side.
