### ISSUE TITLE
Woocommerce Search Result showing post result not product result

### ISSUE THREAD

**Issue by prafullwizorbit** [woocommerce/woocommerce#19263]
Hi, 
I am using by default product search of woocommerce but search result is showing result like post NOT like product. my search get query is like mydomainname/?s=men&post_type=product means my theme only taking post so what can do for getting product type result.
 Any help. 
 Thanks

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try WooCommerce support forums: https://wordpress.org/support/plugin/woocommerce. If you believe you found a WooCommerce core bug please reopen this issue and share all the details asked in the new issue template (expected behavior, actual behavior, steps to reproduce the issue and full system status).

Thanks
