### ISSUE TITLE
Can't register new accounts on my-account page

### ISSUE THREAD

**Issue by alexscro** [woocommerce/woocommerce#19329]
Hey everyone! 

We are currently experiencing issues with the my-account page. On submit, the page reloads but no account is created. It just reloads the page. Already activated all types of error logging, nothing to see. 
Also deactivated several plugins with no success.
Version of WooCommerce is the latest one.

Currently testing with localhost.

Best,
Alex

**Comment by mikejolley** [comment]
> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action

There are no reproducible steps here. You need to go through everything on the new issue form.

If I had to guess (which is all I can do) I'd say it may be page caching. You should at least see errors if nothing happens.

**Comment by mikejolley** [comment]
@alexscro 

https://github.com/woocommerce/woocommerce/issues/19332#issue-303778707

I don't think you understood my last message.

- This is not a support forum
- Testing with extensions off/default theme is mandatory, otherwise how do you know it's a core issue, and why are you logging it here?
- Steps to reproduce need to apply to any store, not just your own. We do not have access to your store. We need to be able to reproduce the issue. In this case, you're the only one with the problem so it's likely conflict/cache.

As I said, cache is a common cause and this can be at server level.
