### ISSUE TITLE
Select2 enqueues css file in footer

### ISSUE THREAD

**Issue by ontiuk** [woocommerce/woocommerce#19379]
Currently the select2 / selectwoo css file is enqueued to be output in the footer. 

This really should be in the header, and before any/the theme css file is output. This would enable standard theme css overrides to be done without the need for masses of !important.

Tested: v3.3.3

**Comment by mikejolley** [comment]
SelectWoo/Select2 is loaded conditionally, only when needed. When the header is rendered, we don't yet know if anything on the page will need it. 

- On cart/checkout its in the header fine because we know it's needed.
- On pages with a dropdown layered nav which uses selectwoo, it's not enqueued until that widget is rendered.

Extensions could also enqueue it later than header.

Solutions I can think of;

- reregister the style and enqueue your own custom version
- use more specific selectors to avoid important
- enqueue it on all pages so it appears in header

Hope that helps.

Thanks
