### ISSUE TITLE
Variable image html replacement hook

### ISSUE THREAD

**Issue by gerharddt** [woocommerce/woocommerce#19396]
Hi

I currently have an issue where I change the output HTML for images for all products on teh front-end and the admin area and it's working fine for everything except variations. I'm currently using the 'post_thumbnail_html' and 'woocommerce_single_product_image_thumbnail_html' hooks to get the job done. I can't seem to find a hook to working with the HTML that gets generated on the variation's image in the admin area and on the magic AJAX thing you do with adding images when you select a variable from the dropdown.

I googled for the last 4 hours without any resolve. Can you please point in me in the right direction for this? 

I basically just need the hook that will provide me with the ability to intercept the HTML for the images of the variations.

Kind regards
Gerhard

**Comment by mikejolley** [comment]
There is a bug with the switcher right now https://github.com/woocommerce/woocommerce/pull/19335

There is no hook to control the image which gets replaced but that PR includes the `woocommerce_gallery_thumbnail_size` if you need to control sizing.

If you need something more, submit a PR and justify why it's needed. That will make more sense since we don't know your use case.

Thanks
