### ISSUE TITLE
JQuery throws an error if the product description contains a link in it

### ISSUE THREAD

**Issue by n-for-all** [woocommerce/woocommerce#19400]
- jQuery v1.12.4
- New wordpress and woocommerce installation with the default theme

![image](https://user-images.githubusercontent.com/171367/37423026-3acee72c-27d6-11e8-85ce-beaea11b21f9.png)

https://github.com/woocommerce/woocommerce/blob/feba3bd3ed6b84c82a21d3f88b5f3ad5440db3f2/assets/js/frontend/single-product.js#L28

`'.wc-tabs li a, ul.tabs li a'`

to

`'.wc-tabs > li > a, ul.tabs > li > a'`

https://github.com/woocommerce/woocommerce/blob/feba3bd3ed6b84c82a21d3f88b5f3ad5440db3f2/assets/js/frontend/single-product.js#L38

Thanks

**Comment by mikejolley** [comment]
Like your other issue, I suspect this is because the markup for the tabs has been changed to add `.tabs`. to the content too. So core works, but your theme is changing this.

Again, if you'd like it to support both we'd be open to a pull request to do so if it doesn't break anything else, but core itself so not have this issue.

Thanks
