### ISSUE TITLE
is_sold_individually() on variable products

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#19443]
![2018-03-17_1227](https://user-images.githubusercontent.com/11464425/37555427-dbde468a-29de-11e8-81ee-95f0a94387c4.png)

If you have a variable product set up and the box ticked for Sold individually under Inventory, I was expecting not to be able to add different variations of the variable product to the cart.
At the moment, I can't add the same variation but I can add different variations to the cart.

It doesn't make sense to me to have the tick box that relates to the variation at the variable level.
Is this a bug or is it intended to be this way?

**Comment by mikejolley** [comment]
> Is this a bug or is it intended to be this way?

Intended, and changing behaviour now would be breaking for those relying on it.

Sold individually works based on the ID of the thing being sold. For regular products this is the product ID. For variations this is the variation ID. So you can add different variations to the cart, but can only purchase one of them (there will be no qty input).

Since you can place multiple orders anyway, this doesn't seem like a big issue. Maybe think of this option as one which disables the qty input :)

Thanks

**Comment by iLoveSarabear** [comment]
This sucks. Is there any way to stop users from adding this product to the cart with the "**Enable this to only allow one of this item to be bought in a single order**" is actually selected?

**Comment by webdados** [comment]
@Chunkford @iLoveSarabear I just submitted a small plugin to the WordPress.org repo that will allow changing this behavior at a product level. I'll get back to you guys when it's approved.
