### ISSUE TITLE
Question about line item calculations with tax inclusive prices

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#19453]
Working on 1020091-zen I was stepping through the process of taxes being calculated on a manual order for a product that is 3.50 in a store with tax inclusive pricing and 6% tax. This is the code I was looking at and getting the values from:
https://github.com/woocommerce/woocommerce/blob/3.3.3/includes/class-wc-tax.php#L150-L153

These are all the values here:
```
	$regular_rate       = 6.0000
	$regular_tax_rate   = 1.06
	$the_rate           = 0.056603773584906
	$price              = 3.5
	$non_compound_price = 3.5
	$net_price          = 3.3018867924528
	$tax_amount         = 0.19811320754717
```

The `$net_price` is shown as `3.3018867924528`, so I would think this number (or a similar one) would be used if there were multiples of this item purchased. For instance, 8. 
```
8 * 3.3018867924528 = 26.4150943396224 (26.42)
```

Instead, what I see when creating a manual order is this:
![](http://cld.wthms.co/v062vf+)
Image Link: http://cld.wthms.co/v062vf

I know the code mentioned above isn't where the total is determined, but I ran out of time while searching and need some help from the big guns :)

**Comment by mikejolley** [comment]
We don't work with net prices when using tax inclusive prices. A few points to note:

1. Taxes are calculated for the line, not per item.
2. To avoid precision errors we get the line total and work out the tax backwards from that.
3. We show prices exclusive of tax in admin so the setting does not affect how orders are displayed. 
4. Totals you see in admin are rounded.

So rather than:

```8 * 3.3018867924528 = 26.4150943396224 (26.42)```

We do:

```8 * 3.50 = 28``` and then calculate the tax on 28, which works out as `28-(28/1.06) = 1.58`

Both are valid ways or working if you're consistent. We don't however support per item taxes in core, and probably won't (there is no demand and this adds lots of additional complexity for gateways and extensions.

Not sure if you've seen it but we explain the calculations in https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#tax-calculations-simplified

Let us know if anything else needs explaining.

**Comment by jessepearson** [comment]
@mikejolley Makes sense about the per item taxes and calculations. I had seen the link but it did not cover the per item vs per line, unless I missed it. Thanks again 👍

**Comment by mikejolley** [comment]
Adding a line about it to clarify. Thanks.
