### ISSUE TITLE
Passing simple product id to WC_Product_Variation constructor causes product title clearing.

### ISSUE THREAD

**Issue by svolkov-provectus** [woocommerce/woocommerce#19454]
If $product_id is ID of simple product (not variation).
`new WC_Product_Variation($product_id);`
Cleared product title.

Seems there no check is product really have parent before syncing title with it in
https://github.com/woocommerce/woocommerce/blob/b8700c51e20b935e5bbb95b00d289d4ced2868ea/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L77-L84

**Comment by mikejolley** [comment]
This is a misuse of `WC_Product_Variation` surely? This is why you're meant to use `wc_get_product( ID )` method rather than initialising classes directly because you won't know the 'type'.

How it works could be changed (want to send a PR for that?) but it's not a bug IMO because `WC_Product_Variation` is being used incorrectly.

Hope that makes sense.

**Comment by svolkov-provectus** [comment]
It called automatically during unserializing cart from user's session.
Looks like other 3rd party plugin messed up some products variations in cart before.
I'll try to contact with it team also.
