### ISSUE TITLE
Coupon code restriction issue

### ISSUE THREAD

**Issue by UmeedEmad** [woocommerce/woocommerce#19466]
One of my customers keep complaining of getting error while trying to make a purchase in my website. She can not add coupon code and place order. The error message is here:

"Sorry, it seems the coupon "couponcode" is not yours. it has now been removed from your order."

I want to know when the WC through this error? I checked my coupon code setting and there is no any restriction for this user. like email or country or anything else. What can be the issue and how to handle it?

**Comment by mikejolley** [comment]
This is only flagged here:

https://github.com/woocommerce/woocommerce/blob/5a8c1ee81c30250276127f1a0fb552792256b73c/includes/class-wc-cart.php#L1470-L1472

It happens when email restrictions are in place and the user email is not valid.

- Check the email restrictions are empty
- Check the coupon code is duplicate and the other coupon doesn't have email restrictions either :)
- Ensure an extension is not adding this value and causing the check to run.

Unable to replicate an issue with core with given instructions. I'd expect no-one would be able to use coupons on any install if there were a core bug.

Thanks
