### ISSUE TITLE
add-to-cart-variation.js doesn't work with select option without value

### ISSUE THREAD

**Issue by ziehm** [woocommerce/woocommerce#19492]
I am facing a problem with the display of variations.

Setup: The select fields for choosing attributes in the frontend include an empty option with "Choose an option" (German in this case):

```
<select id="pa_groesse-32" name="attribute_pa_groesse-32" data-attribute_name="attribute_pa_groesse-32" data-show_option_none="no">
		<option>Wähle eine Option</option>
		<option value="45x30cm" class="attached enabled">45x30cm</option>
		<option value="60x40cm" class="attached enabled">60x40cm</option>
		<option value="75x50cm" class="attached enabled">75x50cm</option>
		<option value="90x60cm" class="attached enabled">90x60cm</option>
		<option value="120x80cm" class="attached enabled">120x80cm</option>
		<option value="150x100cm" class="attached enabled">150x100cm</option>
		<option value="180x120cm" class="attached enabled">180x120cm</option>
</select>
```

On page load, there is a note the visitor: "No products match your... Please choose a different combination". I asked myself why this occurs directly after page load.

In add-to-cart-variation.js lines 404 to 426 I found a problem within the function 
```
VariationForm.prototype.getChosenAttributes = function() {
		var data   = {};
		var count  = 0;
		var chosen = 0;

		this.$attributeFields.each( function() {
			var attribute_name = $( this ).data( 'attribute_name' ) || $( this ).attr( 'name' );
			var value          = $( this ).val() || '';

			if ( value.length > 0 ) {
				chosen ++;
			}

			count ++;
			data[ attribute_name ] = value;
		});

		return {
			'count'      : count,
			'chosenCount': chosen,
			'data'       : data
		};
	};
```

If jQuery doesn't find a value to an option of a select field, it returns the .text() instead. This lead to var value always being not empty and var chosen being raised by one even for the "Choose an option".

Now, within the variations, there is no available variant with the combination "Choose an option", which leads to the note the visitor: "No products match your... Please choose a different combination".

**Comment by peterfabian** [comment]
Hi ziehm, 

I've tried to reproduce this, but was not able to do so:
- with default variation set, made it out of stock
- with default variation set, made it out of stock & hide out of stock products set to true
- without default variation set

In neither of those cases the notice to customer you see is displayed in default WooCommerce with Storefront theme.

As you found out, the `text` is selected instead of `value`, but that is because there is no `value` attribute in the first `<option>`. 

However, as you can see in default [WooCommerce code](https://github.com/woocommerce/woocommerce/blob/28a4e88811abd53280cc05f20067ce26e54826e4/includes/wc-template-functions.php#L2468), this option actually has `value` set to empty string.

Therefore, it's quite possible that one of the extensions or your theme might override this and it's possible that it's not done correctly, or perhaps it's out of sync with the rest of the code. 
I would suggest to try to follow the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to rule out plugin/theme conflict (basically to turn off all plugins and custom themes and then enable them one by one to find the problem).

For future requests, please follow the template provided when creating the issue, it helps us speed up the troubleshooting.

**Comment by ziehm** [comment]
Hi Peter,

thanks for your response. I investigated the issue further (with plugins deactivated) and found out that at least my Chrome (Version 64.0.3282.186 (Official Build) (64-Bit)) has a problem with `current_attr_select.val( '' ).change();` in add_to_cart_variation.js:
```
// Choose selected value.
			if ( selected_attr_val ) {
				// If the previously selected value is no longer available, fall back to the placeholder (it's going to be there).
				if ( selected_attr_val_valid ) {
					current_attr_select.val( selected_attr_val );
				} else {
					current_attr_select.val( '' ).change();
				}
			} else {
				current_attr_select.val( '' ); // No change event to prevent infinite loop.
			}
```

The fallback to the placeholder fails in Chrome (works in IE though). Please see the attached screenshots for details. `current_attr_select.val( '' )` sets the select option not back to the placeholder but to blank.

Best regards
Hauke

Before val( '' ) is applied to the select box
![screenshot before val](https://user-images.githubusercontent.com/1223163/37838716-f1a272be-2eb8-11e8-88ac-d263c3b7c007.jpg)

After val( '' ) is applied to the select box
![screenshot after val](https://user-images.githubusercontent.com/1223163/37838724-f549afb8-2eb8-11e8-8e70-d8dd7a497644.jpg)

**Comment by ziehm** [comment]
@peterfabian 

Hi Peter,

the general problem can be reproduced in a simple jsFiddle: https://jsfiddle.net/8xhtxxzr/1/

Best regards
Hauke

**Comment by peterfabian** [comment]
Hi,

What I was trying to say that a correct theme should include the `value` attribute in the same way as default theme does. 

```
<select id="pa_color" class="" name="attribute_pa_color" data-attribute_name="attribute_pa_color" data-show_option_none="yes">
  <option value="">Choose an option</option> <!-- see the attribute here? it's missing in your HTML, but it's included in default -->
  <option value="blue" class="attached enabled">Blue</option>
</select>

```


Therefore, I think you should not normally see this problem.

As you can see in the updated jsFiddle: https://jsfiddle.net/8xhtxxzr/17/
if you comment out one or the other javascript line, it sets the dropdown correctly
