### ISSUE TITLE
Woocommerce orders section alignment issue in the Admin panel

### ISSUE THREAD

**Issue by vijaykumarim** [woocommerce/woocommerce#19517]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.In the Woocommerce dashboard - Orders menu the alignment is not working for order number, Date, status, billing etc. 
2. Screenshot is here: https://imgur.com/a/bwd9S

![woo](https://user-images.githubusercontent.com/37114244/37864199-80f85d38-2f91-11e8-864f-94459a4d70e0.jpg)

3. Here you can see all the items moved to right.

## Expected/actual behavior

I removed all the plugins tested with woocommerce. It once happened in past but then I completely removed the wordpress and re installed then it started working fine but again I got same problem

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment
WordPress 4.9.4
Woocommerce 3.3.4

**Comment by mikejolley** [comment]
This looks like a CSS/cache issue, but could also be a plugin adding/removing columns and affecting this. 

You can see that one of the headers are missing in the table, hidden with CSS possibly. That could be due to a plugin applying CSS to the columns but not the headers, for example to show a column we hide by default. 

- Open screen options top right and see if you can enable all columns there to clear up the display issue.
- Rule out plugin conflicts properly; I know for certain some plugins do like to mess with column visibility. 

Since this does not affect other installs it's not a core WC issue so I'm closing this, but feel free to come back if you find anything we should know about. If you need someone to look at the admin area and offer more clues, you'll need to use the helpdesk since you cannot provide credentials in Github.

p.s. I'm not sure why you posted a 1 star review linking to this issue. I assume it was to get attention, but all Github issues are reviewed anyway -.- Don't do that to other authors, it's pretty annoying and I doubt will help your case.

Thanks

**Comment by vijaykumarim** [comment]
Solution found on the issue page... https://github.com/woocommerce/woocommerce/issues/11764
