### ISSUE TITLE
Suggestion: Add 'Menu Order' field to Product Page 'Quick Edit'

### ISSUE THREAD

**Issue by AJerm** [woocommerce/woocommerce#19516]
As above, this would make it much easier to edit and compare the display order of a large number of products when organising your shop.

Currently you have to completely load the product and navigate the to the Advanced tab of the Product Data section, which is quite slow and cumbersome and makes it hard to compare order numbers between products as you have to open each product in separate tabs.

**Comment by mikejolley** [comment]
The entire menu order system in WP is cumbersome and TBH I'd like to drop it at some point. If the drag and drop ordering is not working for you (there is a sort products link in the admin area), you could also consider a CSV export/import to update the order in bulk.

Since menu order is handled by WordPress I don't want to introduce this to quick edit, but I'd you can log this on ideas.woocommerce.com for feedback/other ideas.

Thanks
