### ISSUE TITLE
Issue with Translation after Updating to 3.3.4

### ISSUE THREAD

**Issue by djacidck** [woocommerce/woocommerce#19523]
After Updating to 3.3.4 i have problems with the translation to german. Translation File is correctly translated but in the frontend there are some english translations.

Do you know these Problem?

LG

**Comment by peterfabian** [comment]
Hi djacidck,

Can you please check the [guide for missing translations](https://wordpress.org/support/topic/updating-translations-after-updates/) posted on the support forum?

Since German translation is almost complete, please check that you are using the latest translation file via Dashboard > Updates (alternatively, you can try to [update manually](https://docs.woocommerce.com/document/woocommerce-localization/#section-4)).

It is also possible that the strings missing translation are coming from a theme or plugin, they might be coming from a different domain.

Another possibility is that there could also be a conflict or translation plugin breaking the translation.

If the translation is missing, it would be great if you could [contribute and help with translation](https://docs.woocommerce.com/document/woocommerce-localization/#section-2).  

Finally, it could be the case that some developer missed a translation string, but that is quite unlikely due to automatic checks performed on codebase. Please let us know if this is the case here. Otherwise, it should be sorted out by following the guides mentioned above.
