### ISSUE TITLE
WooCommerce problem rounding tax calculations

### ISSUE THREAD

**Issue by HuGoSm1th** [woocommerce/woocommerce#19525]
Hello,

I have problem since version 3.2.6 with tax calculation that does not want to calculate tax per total instead it does per line even tho I have set it to "Round tax at subtotal level, instead of rounding per line".

Tax calculation now is performed with 6 digits after coma that make no sense to me and I think rounding to 2 digits should be enough .

» _line_subtotal 	4.166667 	
» _line_subtotal_tax 	0.833333 	
» _line_tax 	0.833333 	
» _line_tax_data 	a:2:{s:5:"total";a:1:{i:1;s:8:"0.833333";}s:8:"subtotal";a:1:{i:1;s:8:"0.833333";}} 	
» _line_total 	4.166667 	
» _product_id 	114575 	
» _qty 	1

It causes added £0.01 added to sales with more than 1 item that confuses people

Is there a way to make actual settings to work?

br
Arnis

**Comment by varunsridharan** [comment]
Some of my plugin users are also facing this issue.

@mikejolley Do you have any idea on this issue ?

**Comment by mikejolley** [comment]
> I have problem since version 3.2.6 with tax calculation that does not want to calculate tax per total 

This is not supported. The option is called "Round tax at subtotal level, instead of rounding per line".

"Round tax". Not calc tax. Tax is always calculated on line items, not the totals. Line items can have different tax classes.

Using the round at subtotal option is very uncommon - I highly doubt you'll really want this enabled, and using it will cause 1 cent discrepancies due to the nature of the rounding. Certainly won't need this if UK based. I'd suggest turning it off. I think we may remove this in core at some point.

> I think rounding to 2 digits should be enough

2 digit precision also causes rounding issues :) Especially when using things like prices including tax. So we store high precision, and round on display.

See https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce for an explanation of tax calculations in WC. That should explain how things work. If you have an actual calc issue we can reproduce after disabling the round at subtotal option, let me know, but we do have unit tests in place which are passing.

Thanks

**Comment by HuGoSm1th** [comment]
I understand you are right about  per line calculation if there are more tax rates used and super precision 6 digits after coma, all that is super cool. 

But what to do with the £0.01 added to total when customer buy more than 2 items?

Is that misconfiguration on my side or it is an actual problem?

**Comment by mikejolley** [comment]
Can you explain the item cost + tax and show a screenshot of the total?

And again, please do this without rounding at subtotal.

**Comment by HuGoSm1th** [comment]
here whole transaction: http://prntscr.com/iwhzz4

Per line meta log: http://prntscr.com/iwi12k

**Comment by mikejolley** [comment]
What would be clearer is if you told me the price you've entered for the product and the tax it's producing. I don't know the original price from this output because it's excl. of vat.

**Comment by HuGoSm1th** [comment]
Here:  http://prntscr.com/iwi9iq

Here VAT settings: http://prntscr.com/iwi9sl

**Comment by mikejolley** [comment]
Ok so I don't see the issue in the screenshots, but just going from the wiki, and £8 product should be:

8 - ( 8 / 1.2 ) = 1.33 tax.

For 2 of them, 2.67 tax:

16 - ( 16 / 1.2 ) = 2.6666666667

As I said earlier, taxes are calculated on the line not per item, which is accepted by HMRC as long as you're consistent.

**Comment by HuGoSm1th** [comment]
Can you see issue now?
http://prntscr.com/iwimxi

**Comment by mikejolley** [comment]
have you done this transaction again with round at subtotal OFF like I said earlier or not?

**Comment by HuGoSm1th** [comment]
Sorry,

Yes, disabling that function "Round tax at subtotal level, instead of rounding per line" have solved the problem, something just got stuck for a while.

Thank you for your time.
