### ISSUE TITLE
Very slow TTFB Times on category pages

### ISSUE THREAD

**Issue by ggrrraaaa** [woocommerce/woocommerce#19566]
Hi,

We are having category TTFB times of between 3-8 seconds. We have several variations on most product pages such as YES or NO options with the yes increasing the price and adding an additional matching item but I can't see this making these load times so slow.

Even blog pages and product pages have a TTFb of 1-2 seconds. Only the homepage has a semi-decent time of 500ms.

We are using SSL and PHP 7 on a cloud NGINX server with lots of resources.

I am genuinely our of options now. I have read several other people complaining about this but didn't find a confirmed solution.

Any advice would be appreciated.

**Comment by mikejolley** [comment]
I'd suggest posting on one of the user groups for feedback on this i.e. Facebook or Slack communities to see if others have come across and solved/improved this, or may be able to offer services to help you. 

The main reason I say this is because the issue doesn't have steps we action on; it could be caused by many things from plugins, to product data, to host itself, _and doesn't affect all sites_. 

For example, WooCommerce.com has a higher TTFB on the homepage than a category page (https://woocommerce.com/product-category/woocommerce-extensions/marketing-extensions/reporting-extensions/). If there were a problem across all sites on category pages specifically, I'd expect it to be consistent across sites but it's not.

FYI we're committing lots of time to improving general WC performance this year with the introduction of custom tables and other performance improvements. You can follow out dev blog to be updated about these as released.

https://woocommerce.wordpress.com/
