### ISSUE TITLE
Possible BUG - woocommerce_wp_select to multiselect

### ISSUE THREAD

**Issue by gonzalesc** [woocommerce/woocommerce#19619]
Hi.

I have created a select multiselect using woocommerce_wp_select() function to show the categories.

```
<option value="15">Category1</option>
<option value="17">Category2</option>
```

Then when Woocommerce gets the values it is a array with numeric values:

```
#includes/admin/wc-meta-box-functions.php : 197
'value'             => get_post_meta( $thepostid, $field['id'], true ),

```
and when the script use selected() function, in there is  a in_array(1st,2nd,true), this 3th parameter compare type format and always it give false, cause it compare a numeric with a string.

```
#includes/admin/wc-meta-box-functions.php : 227
echo '<option value="' . esc_attr( $key ) . '" ' . selected( $field['value'] === $key || ( is_array( $field['value'] ) && in_array( $key, $field['value'], true ) ), true, false ) . '>' . esc_html( $value ) . '</option>';
```

Regards

**Comment by peterfabian** [comment]
Hi Alexander, 

I have a question:

`in_array` function in `wc-meta-box-functions.php:woocommerce_wp_select` tries to find value `$key` (coming from array `$field['options']`) in an array of values returned by `get_post_meta`.

In your particular case, you say that the array returned from `get_post_meta` is an array of integers.

Based on the HTML snippet, I'm guessing your `$field['options']` look something like this:
```
$field['options'] = array(
  15 => 'Category1',
  17 => 'Category2',
);
```

So `in_array` should be looking for value 15 in integer values returned by `get_post_meta( $thepostid, $field['id'], true )`, then for value 17, etc and that should work fine I think.

One thing that could be a problem is if `get_post_meta( $thepostid, $field['id'], true )` would return an array of strings, e.g.
```
array(
 [0] => '15',
 [1] => '17',
)
```
then one would not be able to find value 15 in this array using a strict matching. 

If that is the problem you're facing, please try if branch https://github.com/woocommerce/woocommerce/tree/fix/19619 fixes your problem.

**Comment by ragulka** [comment]
I would also add that a similar issue affects regular (not only multi) select fields as well. Given an options array, where the keys are numeric (for example post ids) and the field id is a meta field key, which contains the selected value, the comparison will always fail, because the keys will be integers, but the meta value will always be a string.

For example, given this:
```php
update_post_meta( $product_id, '_my_custom_field', 222 );

woocommerce_wp_select( array(
  'id' => '_my_custom_field',
  'options' => array(
    122 => 'Some value',
    222 => 'Another value'
  )
);
```

One would expect the select to have "Another value" selected, and it works fine in WC 3.3, but breaks since this commit: https://github.com/woocommerce/woocommerce/commit/70e92302f5827a1893b8cf52d1a70d983cb6791d#diff-2a79926dc1383541b89eac74d53f391eR227 - specifically the strict comparison here: `$field['value'] === $key`.

It seems `selected()` itself [casts the values to strings](https://github.com/WordPress/WordPress/blob/7630cc1bad97e7f3d3a894ac7691cf42a1ce5818/wp-includes/general-template.php#L4367) before doing a comparison, which is why it worked before this change.
