### ISSUE TITLE
ChangeRequest: Order overview -  optimization and reorder columns

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [woocommerce/woocommerce#19614]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

I have two issues with the new design:
1) The "send to" column has no conditionals regarding the delivery option. It is very hard to difference between "local pickup" and real shippings and is very prone to errors in the working environment. Ideally, the address should be only listed if there is a real delivery. If it's an order with  
"local pickup" the address is not needed and could be hidden.

2) I don't know if wordpress supports it but to be able to rearrange the columns would be great.

## Steps to reproduce the issue

1. Order Overview
2.Activate Sceen option "Send To"

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
The shipping method is available right under the address, so you can see it is local pickup.

<img width="587" alt="screen shot 2018-04-05 at 8 36 26 am" src="https://user-images.githubusercontent.com/7317227/38376032-853538d4-38ac-11e8-8acb-67d99479bb16.png">

I do not think we need to hide the shipping address on local pickups, as you can see it is local pickup right there. If it is causing problems, there is [a filter](https://github.com/woocommerce/woocommerce/blob/bc7846c41205855faa4cbfde059df18ac07e33f0/includes/class-wc-order.php#L884) available for customizing the shipping address [when it's rendered](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/list-tables/class-wc-admin-list-table-orders.php#L313). You can easily make the address "Local Pickup" or no address using that filter.

Regarding the column orders, [here is a simple way to rearrange the columns](https://make.wordpress.org/docs/plugin-developer-handbook/10-plugin-components/custom-list-table-columns/#horizontally-reordering-columns). If you are thinking something easier to use, it could be worth putting it [on the idea board](http://ideas.woocommerce.com/forums/133476-woocommerce) and seeing if there is demand for the feature.

Closing this issue because I believe I've given you the tools to solve these problems. :)
