### ISSUE TITLE
Failed Stripe credit card order came through webhook as "pending"

### ISSUE THREAD

**Issue by Shotster** [woocommerce/woocommerce#19631]
Not sure if this is intended behavior, but it doesn't seem right...

A charged Stripe order identified by both Stripe and WooCommerce as having "failed" came through the WC "order.created" webhook with a status of "pending". It shows up in the dashboard as "Pending payment" even though the **Order Notes** states the card was declined and a "Failed Order" admin email was sent. A Stripe webhook also indicates a type of "charge.failed".

This doesn't seem correct and is, at best, confusing. Shouldn't there is a WC status of "failed" or something?

**Comment by mikejolley** [comment]
There is a failed status but it's down to the gateway to set it. In this case, it may be that the order was not updated because the response was not received or handled from Stripe. Please use the helpdesk so they can gather more details; Stripe is not part of core (which this repository is for).

Thanks
