### ISSUE TITLE
$order->get_total() is always zero in woocommerce 3.3

### ISSUE THREAD

**Issue by aoguren** [woocommerce/woocommerce#19644]
$order->get_id() can get the correct value, but the $order->get_total() is always zero.

**Comment by aoguren** [comment]
$order = new WC_Order($order->get_id());
$total = $order->get_total();		
$log = new Logger();
$log->logInfo(" *****test ************: " . $total);

$items = $order->get_items();
foreach ($items as $item)
  {
      $goods_amt = $item['line_total'];
      $log->logInfo("line_total : " . $goods_amt);
  }

logger:
*****test ************: 0
line_total : 333

**Comment by mikejolley** [comment]
Unable to replicate an issue here. As @kloon suggested, the calculation has to be ran before it will return something. This happens when updating line items via the CRUD, or calling the `calculate_totals` method. We don't support calculations outside of this system/CRUD so if working with items directly or editing meta, it will mismatch until the order is updated/saved/calculated.
