### ISSUE TITLE
Woocommerce activation error!!!

### ISSUE THREAD

**Issue by Manucharyan** [woocommerce/woocommerce#19650]
Hi. 
There is a huge problem with woocommerce activation. After activation website goes down and gives an internal error like error 500.

"website link" is currently unable to handle this request.
HTTP ERROR 500. 

Every time the same. Help to resolve the issue.

Sincerely,
Gor

**Comment by kloon** [comment]
@Manucharyan this can be anything, since you have not provided us with more information as requested when opening the issue it is difficult to assist.

Best bet would be to check your PHP error logs and see what the error is, 500 errors are PHP coding errors so it might be a conflict with a plugin or your theme.

If I tests this locally with just WooCommerce and a default theme like twenty seventeen or storefront I am not getting any errors.

**Comment by Javaher21** [comment]
I have had the same experience with WooCommerce. My Wordpress version is  4.9.5. I uploaded and unzipped the WC 3.3.4 on plugins folder and it worked just fine but when I tried to activate WC it caused a crash in the website. I think this error has something to do with memory limits or WP settings but there are no documentations for that.

**Comment by Javaher21** [comment]
@Manucharyan  Okay so I did fix it by changing PHP version to 7.0 . Also check WC's [ Server Requirements and Recommendations](https://docs.woocommerce.com/document/server-requirements/) for more info
