### ISSUE TITLE
Woocommerce crash after updating

### ISSUE THREAD

**Issue by limbbc** [woocommerce/woocommerce#19683]
Hi, 
i have update the latest woocommerce today, then error came out and my site are not running.

PHP Fatal error: Class 'WC_Deprecated_Hooks' not found in /home/beauchic/public_html/wp-content/plugins/woocommerce/includes/class-wc-deprecated-filter-hooks.php on line 17

please advise what should i do to fix this.

**Comment by mikejolley** [comment]
The class is included here: 

https://github.com/woocommerce/woocommerce/blob/dc7aa3069466f1b7e23fd7ef468760a6a9ddd241/includes/class-woocommerce.php#L291

And you can see this class for sure exists:

https://github.com/woocommerce/woocommerce/blob/9a95441c611d931fdc510b80159520f204e034ad/includes/abstracts/abstract-wc-deprecated-hooks.php#L19

Sounds like you're missing files. Make sure the update process has fully completed, if not, reupload the WooCommerce plugin to wp-content/plugins via FTP

See: https://codex.wordpress.org/Managing_Plugins#Manual_Plugin_Installation

Once done, it should be detected just fine.

cc @peterfabian ^ for your reference. This sometimes crops up after updates and isn't a bug, but usually caused by server timeout/error/permissions during the update process.

**Comment by limbbc** [comment]
Hi mike,
thanks. it works after using manually uploading. 
Thank you
