### ISSUE TITLE
Export/Import: Unlimited downloads/time on downloadable products conflict

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#19720]
## Steps to reproduce the issue

1/ Create a product with unlimited downloads/days available.

2/ Export products using the native exporter. The column has `'-1` as the value.

![http://cld.wthms.co/EP3cr1](http://cld.wthms.co/EP3cr1+)
Link to image here: http://cld.wthms.co/EP3cr1.

3/ Import the product after making a small change (e.g. changing the name), and use option to **Update existing products**.

![http://cld.wthms.co/MUceNV](http://cld.wthms.co/MUceNV+)
Link to image here: http://cld.wthms.co/MUceNV.

4/ The download limit is now changed to `0` rather than `Unlimited`

![http://cld.wthms.co/nKElSn](http://cld.wthms.co/nKElSn+)
Link to image here: http://cld.wthms.co/nKElSn.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by saimonh3** [comment]
@kloon Hello, could you please review the pull request?

Regards

**Comment by tmas73** [comment]
I do have a similar issue even with the latest version of Woo.

I imported the CSV with a "0" in my trestings. I wanted to change it to unlimited downloads so I removed all "0" entries in my spreadsheet and updated the import with the hope it having no entry in the spreadsheet to be listed as unlimited. It seems though that the "0" entry is permanent and that it will not see it as unlimited because the field is not empty. How would I import the spreadsheet that all products have a unlimited option?  Thanks Thomas
