### ISSUE TITLE
WooCommerce Variable Product Price not showing

### ISSUE THREAD

**Issue by HolgerHahn** [woocommerce/woocommerce#19727]
I have the problem attributes/prices do not change... i de-activated most  plugins but the  problem persists.
The different variation pictures show up correctly but the prices (eg.10.- 20.- or 30.-do not change...
any help  is well appreciated

I use avada theme
demo product: https://adult-toys.online/product/testproduct/

![screenshot_2](https://user-images.githubusercontent.com/38418997/38794506-ab697c66-4155-11e8-952a-cdf7f3688da1.jpg)
![screenshot_3](https://user-images.githubusercontent.com/38418997/38794507-ab865804-4155-11e8-95d2-b13e3714c1a0.jpg)

**Comment by peterfabian** [comment]
Hi,

Unfortunately, github repository is not a support forum, but a place to report bugs in WooCommerce core. I would recommend to try to get help from one of the sources below:

- https://wordpress.stackexchange.com/
- https://woocommerce.com/customizations/
- https://wordpress.org/support/

Also, using a Storefront theme and deactivating other plugins might be a good troubleshooting start, please refer to [Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) for a more complete troubleshooting guide.

This looks to me like a plugin conflict or a theme issue, since Storefront theme normally displays price of the selected variation above the Add to Cart button:
![variation_product_price](https://user-images.githubusercontent.com/2207451/38810159-2ca738ba-4186-11e8-9cae-6f5496775f5a.png). 

If you discover this is actually a WooCommerce core problem, please feel free to open a new issue or report on this one.
