### ISSUE TITLE
Allow write access to WP API by authorizing with WOO API

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#19730]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upload files using wp-json/wp/v2/media endpoint with woo api oauth authorization

Please note, this is not a problem with cookie authentication (oauth only)

## Expected/actual behavior

**Expected**:
Still be authorized as when using woo rest api

**Actual:**
"Sorry, you are not allowed to create posts as this user."

**Additional notes:**
The user which requested credentials for woo api does also have permission to do wp admin stuff. (is main admin)

Wp auth should be able to inherit from woo auth, so you dont need an additional plugin to handle auth for doing stuff outside of woo, like JWT Plugin.

F.ex **media uploading** is a heavily used feature also for woocommerce users.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
We don't plan on supporting this, thats out of the scope of the WooCommerce API.

1. It would open up other endpoints previously out of scope for the API and thus could cause security issues
2. There are other auth plugins which can be used for both
3. When/if WordPress implements a new auth system (key based) we'll remove our custom one.

I'd say if there is an endpoint lacking in WC core API, make the case for it to be included on https://github.com/woocommerce/wc-api-dev/issues - maybe images is something we can support since you can set an image via API. Not sure how that would look however.

cc @claudiosanches

**Comment by steffanhalv** [comment]
Ty, posted suggestion here:

https://github.com/woocommerce/wc-api-dev/issues/105

**Comment by claudiosanches** [comment]
I don't think that is necessary including a clone of the WP media endpoint just to work with the same authentication like WooCommerce... If you are fetching data from WP core endpoints you should install a plugin for authentication and use the same authentication for all WP endpoints, even for WooCommerce.
We have an authentication method for now just to follow our legacy REST API, but we have plans to remove it as soon as WordPress implement something.
