### ISSUE TITLE
ERROR: Sorry, this product is unavailable. Please choose a different combination.

### ISSUE THREAD

**Issue by wc2ether** [woocommerce/woocommerce#19738]
WC 3.3.5 

Variable subscription with three variations (all with prices). 
They are all correctly selectable the first time or until the user selects one, proceeds to the check out and then goes back to the product's page. In such case only the previously selected variation is still selectable while the other two are greyed out and both trigger the error: 

_Sorry, this product is unavailable. Please choose a different combination._

The only way to fix the error is to "disable" and then "enable" again all the product variations but, of course, users can't do that.

**Comment by mikejolley** [comment]
This is due to the complexity of the product, and there being no variations matching those other attributes. Without a link I cannot be more specifc - your report is missing basic information.

Briefly,

- When you choose an attribute on a variation page, other attributes which would not match are removed.
- When you view a product from the cart, your previous selections are pre-selected.
- To view ALL attributes again, the form needs to be cleared.

Example:
2 variation shirts. One is LARGE and BLUE and one is SMALL and RED. When RED is chosen, only SMALL can be chosen because LARGE does not match a variation.

Usually WooCommerce removes the options rather than greying them out so I assume the theme is changing this to use greyed out options, or it's a customisation. If they are removed, the notice you're seeing cannot be triggered.

Thanks
