### ISSUE TITLE
WC_AJAX->get_endpoint() improvements break polylang based addins

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#19741]
Until at least woo 3.1.2, wc-ajax calls were made to [current url]?wc-ajax=[ajax call]

Since this commit ajax calls are instead directed to $home/?wc-ajax= 
https://github.com/woocommerce/woocommerce/commit/5721bc6044eed3f17b6b9e290efb6166b633b8fe#diff-133db5662c51f5686d87611121a05a3b

Previously until version 3.1.2, Polylang was detecting current language based on the url in the ajax call.
With the new code, the url is the default home page so the language is always detected as site base language.
In 3.3.x and possibly earlier, this is causing problems with order review always resetting to site base language, due to Polylang being unable to determine the language from the ajax call.  
Since the review order section including the checkout button have switched to base language, the order is then placed in base language even though the user is trying to checkout in a different language.

While the call is filterable, the checkin adding home_url doesn't seem to have related issue which justifies changing the wc-ajax url to make it based on home_url(), so the home_url() call could be removed.

If there are no compelling reasons for the change then I would restore the 3.1.2 version of the function which seems to work:
```
	public static function get_endpoint( $request = '' ) {
		return esc_url_raw( apply_filters( 'woocommerce_ajax_get_endpoint', add_query_arg( 'wc-ajax', $request, remove_query_arg( array( 'remove_item', 'add-to-cart', 'added-to-cart' ) ) ), $request ) );
	}
```

If there are compelling reasons for the change then we need to know what they are since filtering the endpoint to restore the 3.1.2 functionality won't be a good solution either.

**Comment by Jon007** [comment]
to be precise I can see the behaviour changed as of:
https://github.com/woocommerce/woocommerce/pull/16991

The home_url() function was originally added with home_url( $_SERVER['REQUEST_URI'] ) which didn't change the behaviour but did add bug, then in removing the bug with this change, the functionality was changed.

**Comment by mikejolley** [comment]
There have been a few changes to this due to server config conflicts and security issues.

- The code in https://github.com/woocommerce/woocommerce/commit/5721bc6044eed3f17b6b9e290efb6166b633b8fe#diff-133db5662c51f5686d87611121a05a3b fixes a potential security issue where by the current page URL is used in full. On some setups (I forget the exact report) this could allow someone to form a special checkout link which when used sends the AJAX request to an external site. By forcing  it to use home, this is mitigated.
- Then as you say, the SERVER variable was removed in https://github.com/woocommerce/woocommerce/pull/16991 to fix that other bug.
- And finally more recent, home_url was made relative to fix a separate bug. https://github.com/woocommerce/woocommerce/pull/19139

With the above in mind we cannot revert this to the original code. It's not secure. I think for Polylang to fix this once and for all it just needs to append it's lang variable to the endpoint via `woocommerce_ajax_get_endpoint`.

Thanks

**Comment by theleemon** [comment]
@Chouby

**Comment by Chouby** [comment]
Hi,

@theleemon Polylang for WooCommerce already uses the `woocommerce_ajax_get_endpoint`. I added this about 6 months ago to adapt to the changes introduced in WooCommerce 3.2.
