### ISSUE TITLE
REST API - Endpoint for modified post

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#19750]
Hoping this is the right place to add feedback/request this REST API enhancement. 

1095603-zd-woothemes

> The list-all-products API call supports querying http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products created after a given date, but doesn't provide a way to query products modified since a certain time.

> The same issue exists for Customers and Orders too

> Our customer wants to be able to sync products from WooCommerce into a backend database, and it makes so much more sense to query all products modified since the last sync, than it does to sync all products each time.

> Please add support for querying objects by the last time they're modified.

**Comment by mikejolley** [comment]
Feature requests should really go to the ideas board. However, developers asking for these types of additions can contribute to wc-api-dev repository.

I've updated https://github.com/woocommerce/wc-api-dev/issues/65 to include products as this was just for orders previously, but the same system can apply since all resource types are similar.

No plans to do this short term.
