### ISSUE TITLE
Currency/price format issue 3.3.5

### ISSUE THREAD

**Issue by AndreiNateasin** [woocommerce/woocommerce#19780]
Currently using 3.3.5.After update the formatting for the price and currency was defaulted to some format.
Changes from general woo setting are not taken in account. When activating a module "Price formats" from Woo Booster I was unable to edit ore access any order and as a result I received a page not found result.
After disabling Price Formats orders work but price formats are as originally defaulted.

**Comment by claudiosanches** [comment]
For what you are reporting, the problem is on Woo Booster, better contact the author from that plugin.
This report is missing steps to reproduce and a lot of information from the issue template that has been completed deleted... So there is anything else that seems a problem besides Woo Booster.
About the default format, you can change on WooCommerce settings.
