### ISSUE TITLE
Issue with wp_kses_post and wc_get_relative_url with port in the URL

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#19819]
In the template cart.php, the new wp_kses_post of the thumbnail image is breaking the link when using a port in the url ( like localhost:8080, for example ). Since wc_is_external_resource is removing the protocol from the url of the picture to make the link relative, when wp_kses_post is checking the string, the regex of wp_kses_post is not finding no protocol, but identify the port of the URL as protocol, breaking the link of the picture.

**Comment by peterfabian** [comment]
Hi,

Can confirm: `wp_kses_post` calls `wp_kses_split()` calls `_wp_kses_split_callback`, then `wp_kses_split2`, then `wp_kses_attr`, then `wp_kses_hair`, and finally `wp_kses_bad_protocol` which cuts off URL before the port part as an invalid protocol.

Ideally, wp_kses should support protocol-relative URLs, but not sure if that is feasible to add to WP core now.

We should maybe be steering away from protocol-relative use of resources to be able to take advantage of newer protocols like http/2, as mentioned in:
- https://www.paulirish.com/2010/the-protocol-relative-url/
- https://jeremywagner.me/blog/stop-using-the-protocol-relative-url/
- also previously discussed in issues, e.g. https://github.com/woocommerce/woocommerce/issues/17577

Since some other assets don't use protocol-relative URL, e.g. https://github.com/woocommerce/woocommerce/pull/15944/files, I would propose removing the protocol-relative URLs also for images.
It's true, though, that some assets, like some CSS files, still use protocol-relative URLs, e.g. https://github.com/woocommerce/woocommerce/blob/master/includes/theme-support/class-wc-twenty-seventeen.php#L47

@mikejolley what is your take on this?

**Comment by mikejolley** [comment]
This is fixed in https://github.com/woocommerce/woocommerce/pull/19934
