### ISSUE TITLE
Please consider adding back the `woocommerce_product_default_attributes` filter

### ISSUE THREAD

**Issue by jnachtigall** [woocommerce/woocommerce#19814]
There used to be a `woocommerce_product_default_attributes` filter for the default variation attributes. I used this in 2.6 for programatically selecting a certain a certain product variation. (e.g. 3 different variants, but 2 of them are sold out, so we select the only one being not sold out).

This filter does not work anymore in WC 3 since it has been move to a deprecated method that is not called any more from core:

https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/legacy/abstract-wc-legacy-product.php#L157-L166

I cannot find any upgrade, migration or changelog notes on how to do handle the removal of this filter.

At [Stackoverflow](https://stackoverflow.com/a/46080598/1129950) a user suggests to use the `woocommerce_before_add_to_cart_form` **action** to get the default variation, mangle it and then set them back to the product. This seems overly complicated and a **filter** should be there for this.

Would you consider adding the old `woocommerce_product_default_attributes` or a filter with a new name back to either `public function get_variation_default_attributes()`:

https://github.com/woocommerce/woocommerce/blob/d5e98e8d081574f3ce6ccd1d35357a6e011ff610/includes/class-wc-product-variable.php#L235-L240

or `get_default_attributes()`:

https://github.com/woocommerce/woocommerce/blob/28a4e88811abd53280cc05f20067ce26e54826e4/includes/abstracts/abstract-wc-product.php#L526-L535

? 

Otherwise I'll go down the `action` road but as said there should be a filter for this.

**Comment by lomars** [comment]
You can use the filter `woocommerce_product_get_default_attributes` which has 2 arguments  `$attributes` and `$product`.

**Comment by jnachtigall** [comment]
@lomars thanks so much, this works! The 2 arguments are even the same like for the old filter, so in fact it looks like it was more or less just renamed.

FWIW, I find it strange that this filter can neither [be found on GitHub](https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=woocommerce_product_get_default_attributes&type=) nor [on the hooks API docs](https://docs.woocommerce.com/wc-apidocs/hook-docs.html). That's and also with DDG is where I search for 1h or so without finding...

**I'll change the subject, so maybe to docs could be made to include this filter, too.**

**Comment by lomars** [comment]
Explanations: Since Woocommerce 3 and new introduced CRUDS setter methods, when a method is using `get_prop()` `WC_Data` method, a dynamic hook based on the object type and the method name can be used (essentially for frontend)… 

**See this line:** `$value = apply_filters( $this->get_hook_prefix() . $prop, $value, $this );` [located in `WC_Data` `get_prop()` method](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L703)
and this line: `return 'woocommerce_' . $this->object_type . '_get_';` [located in `WC_Data` `get_hook_prefix()` method](https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/abstracts/abstract-wc-data.php#L597)

So the filter hook is dynamically made this way: 
`'woocommerce_' . $this->object_type . '_get_' . 'default_attributes'`

with 2 arguments: 
- $value (the property value to be returned, so `$default_attributes` or `$attributes` )
- $this (the class instance object, so `$product` here, for an instance  of the `WC_Product` object)
