### ISSUE TITLE
Filter by variations?

### ISSUE THREAD

**Issue by robizzt** [woocommerce/woocommerce#19825]
EXPLANATION OF THE ISSUE
Let's say product has 1 attribute _(size)_  and _size_ has 5 variations _(36, 37, 38, 30 and 40)_.
Each of these sizes has stock and ,let's say, size 38 is out of stock. Now when I add widget "filter by attribute", and select size 38, that product which has size 38 out of stock still pops up.

I understand that "filter by attribute" does exactly that, filters by attribute... But is there any way not to show products with selected variation, if that variation for that prodcut is out of stock ("hide out of stock" dosen't help)?

Same for "Additional information" (picture below)
![size](https://user-images.githubusercontent.com/30315895/39132462-3184b68c-4712-11e8-8b3b-c1182dd6eaaf.jpg)

Same if you click on size 38 in Additional information, product has attribute 38, but variatiton is out of stock, and will still pop up.

Any solutions?

**Comment by mikejolley** [comment]
This is still the case: https://github.com/woocommerce/woocommerce/issues/5840#issuecomment-50601474

It's a performance issue we'll revisit when custom tables are released for product data, since that will give us more flexibility and faster queries. Until then there is no solution for this request.
