### ISSUE TITLE
Add ability to control over view of Orders page

### ISSUE THREAD

**Issue by James1S10** [woocommerce/woocommerce#19862]
In Orders page I can control over which columns will be shown (Status, Billing,Shipping etc..)
But I have no control over the filter.
It always goes by default to 'ALL'
I want the default will be 'Processing' orders  - This make scene as most of my work is with these orders. It's annoying always changing it with every refresh of the screen.
Other stores may choose differently according to their prefrences...

Please allow to select which 'Status' will be default for record filtering.

**Comment by peterfabian** [comment]
Hi, 

Thanks for the suggestion. We have a place to suggest new ideas at http://ideas.woocommerce.com/, so it would be best if you could add your idea over there.

There is a link from the dashboard directly to orders awaiting processing, that might help you get directly to the screen you want if I  correctly understand what you want?
![dashboard](https://user-images.githubusercontent.com/2207451/39317703-879149de-497c-11e8-8de3-218d362da9b5.png)

Otherwise, you could also customize your woocommerce with a bit of code to get the desired behavior, but I would recommend to contact one of the certified developers to modify the functionality for you: https://woocommerce.com/customizations/

**Comment by claudiosanches** [comment]
This probably can be considered on WooCommerce 4.0 while we are doing a new dashboard for WooCommerce. So closing in favor of #16974
