### ISSUE TITLE
Woocommerce cause high MySQL usage and slow down my VPS server.

### ISSUE THREAD

**Issue by DrMTR** [woocommerce/woocommerce#19898]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Disabled all possible plugins into my site.
2. Site is loading normally when Woocommerce is disabled. 
3. After enabling Woocommerce site startingto be too slow and not respondable at times. Before activating Woocommerce i have 25 queries executed, after enabling number goes up to 65 queries.

## Expected/actual behavior

I expect to work normally as worked before some month. After enabling Woo my site starting to be too slow, and not respond.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WordPress Umgebung
--
Home URL: |   | https://www.onegiftfor.me
Site URL: |   | https://www.onegiftfor.me
WooC-Version: |   | 3.2.6
Log-Verzeichnis beschreibbar: |   | /home/onegif5/public_html/wp-content/uploads/wc-logs/
WP-Version: |   | 4.9.3
WP Multisite: |   | –
WP Memory Limit: |   | 256 MB
WP Debug-Modus: |   | –
WP Cron: |   |  
Sprache: |   | de_DE

Server-Info: |   | Apache
-- | -- | --
PHP-Version: |   | 7.1.16
PHP Post Max Size: |   | 128 MB
PHP Time Limit: |   | 30
PHP Max Input Vars: |   | 1000
cURL-Version: |   | 7.59.0, OpenSSL/1.0.2o
SUHOSIN installiert: |   | –
Maximale Upload-Größe: |   | 128 MB
Standard-Zeitzone ist UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte-String: |   |  
Remote Post: |   |  
Remote Get: |   |  

</details>

**Comment by kloon** [comment]
@DrMTR This is likely a server configuration issue. We have a lot of sites running on a range of servers from very small shared hosting to very large multicluster servers without any issues.

Yes, WooCommerce will add to the number of queries that runs but we try and keep our queries as fast as possible by evaluating the performance impact it might have, and in most cases, there is really no noticeable difference.

Might be worth enabling the MySQL Slow Query Log and posting the log here so we can look at identifying what is causing this for you and if it really is WooCommerce https://dev.mysql.com/doc/refman/8.0/en/slow-query-log.html

**Comment by DrMTR** [comment]
Hi Staff, thanks for asnwering.

Before enabling Woocommerce Queries was about 20. After enabling Woocommerce only, queries grow up to 2.300. See:

]https://i.imgur.com/rivkuVy.jpg

I also make a log with all queries when woocommerce is enabled, but list is too long to upload here, so i make a archive with files. In attachment.
[queries.zip](https://github.com/woocommerce/woocommerce/files/1960273/queries.zip)

Waithing to hear from you. Thanks

**Comment by kloon** [comment]
@DrMTR Unfortunately that does not give me much of an idea. Since you have query monitor running can you perhaps check what the query is that is slowing your site down? And on what page is this triggering?

**Comment by DrMTR** [comment]
when load homepage number of queries grow up to 2300 queries.

**Comment by makeonlineshop** [comment]
Sorry but it seems that so many people do not want to understand that Woocommerce causes problems and at least slow down so many servers. It happened to me also, even on a good server without configuration issue. 
Woocommerce database structure is the problem and I wonder how long it will take before it is improved/fixed.
Turn on and off Woocommerce on any install and you instantly see the speed difference.

**Comment by mikejolley** [comment]
@makeonlineshop If you have nothing constructive to add, please don't comment here :) We do understand and if you'd been following the dev blog/dev chats you'd know a feature plugin for custom tables is in the works/open sourced.

@DrMTR 

> Site is loading normally when Woocommerce is disabled.

Stating this is not helpful because this is an eCommerce site with eCommerce theme and plugins. Those plugins have a WooCommerce dependency, so when you turn WooCommerce off, you also disable all the bits adding *to* WooCommerce. 

This section shows the speed of the queries:

![slack - a8c 2018-05-01 10-31-44](https://user-images.githubusercontent.com/90977/39468442-eb2f7572-4d2a-11e8-9da3-b103a1905438.png)

Total is around 1s. So the other 4s could be attributed to images, plugins, calculations, un-neccessary content etc combined with the volume of products you're showing on the homepage.

Some examples I can see on the page:

- The sale amount calculation runs per product
- Quick view runs per product
- The extra gallery/zoom runs per product
- Caching looks to be disabled which isn't normal unless a plugin is doing something with session data.

You should:

- Do some testing with certain WC extensions disabled e.g. the quick view + zoom
- Consider showing less sections on your homepage so less products need to be loaded at once
- Dump the hover zoom effect
- Use Jetpack lazyload/CDN

The query count is excessive but most appear to be from priming caches e.g. update_meta_cache. We'll look into this but there is no "1 thing" causing the issue on your store. it's a combination of things adding to that query count and slowness.

Hope this helps anyhow.
