### ISSUE TITLE
Can't create order, get products or get categories as a "customer" using REST API Node.js client

### ISSUE THREAD

**Issue by vhb56** [woocommerce/woocommerce#19896]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use any frontend framework.
2. Install official WC node.js rest api client 
3. Generate some keys for user with role "customer"

## Expected/actual behavior

4. Using those keys unable to get a list of categories, list of products by category, create new order.
Both with http and https.
Is is even possible, if not - why?
Always 401, 403

If keys are generated by admin and for admin they are working, but customer keys can do.. nothing?
Can't get it. Am i going crazy?

Thx.

**Comment by kloon** [comment]
The WooCommerce API applies the roles and capabilities of the selected user for the keys. Users with customer role does not have access to any backend functionality like you listed above. I would suggest you use an API key tied to at least a shop_manager user role instead to be able to create orders, list products etc.

**Comment by vhb56** [comment]
But this doesn't make sense, as a customer i should be able to buy stuff (create an order for my self only).
And also able to see products that i can buy.
I am making an app ang giving away shop_manger keys to users that should be able only to see & buy is unsecure, because shop_manager can do much more than that.
I am forced to extend existing API in that case.

**Comment by mikejolley** [comment]
The API is not built to manage a cart or checkout. The API allows a privileged user (between your app and store) to create an order.

**Comment by vhb56** [comment]
Well, i understand now that it was done intentionally.
But if it was supported "natively" by API it would easier for anybody who develops with modern frontend frameworks like Angular, React, Vue, Ember ..etc, to build modern sites with WP & WC as backend.
Basically the whole idea of WP REST API was about that.
Anyway, thank you for your help.

**Comment by claudiosanches** [comment]
@vhb56 but it's already easy, there is no secret to handle sessions on Angular, React, Vue, Ember and etc, the REST API already provide all tools necessary for it, on the JS side you just need to call REST API endpoints, use browser storage (cart, results from REST API and so on) and sessions, at least all of those things should be easy to do in any JS library.

**Comment by nik-lampe** [comment]
Sorry to pick up that old topic, but I'm surprised that I haven't found much on this. Maybe I'm searching for the wrong things, but it looks like no one but @vhb56 came up with this.

Do I understand right, that I have to add additional API methods to create an order, retrieve product data, etc. without authenticating with a key which has write access?

I can't use an writeable authentication on the client side because it'll expose the credentials to the user and this could be easily exploited to do whatever you want with my shop. 
Actually even with a read-only role I would expose all my business data to the client.

**Comment by nik-lampe** [comment]
@vhb56 how did you solve this eventually?

**Comment by giacomodeglinnocenti** [comment]
> But this doesn't make sense, as a customer i should be able to buy stuff (create an order for my self only).
> And also able to see products that i can buy.
> I am making an app ang giving away shop_manger keys to users that should be able only to see & buy is unsecure, because shop_manager can do much more than that.
> I am forced to extend existing API in that case.

Fully agreeing. By the common case scenarios it would be very useful to have the APIs handle distributed front end operation such a 'register a new user', 'just create an order for user X', 'just list users' with granular access permission selection and the ideal support for client side cases, instead of capabilities to handle all the powers of a common user, especially if it would not be possible to assign peculiar role access, but only standard roles, that in instance, other than create new users, could also update the core or upgrade other users role.
