### ISSUE TITLE
Disalign woocoomerce order

### ISSUE THREAD

**Issue by bear07** [woocommerce/woocommerce#19901]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
![disalign](https://user-images.githubusercontent.com/38830534/39404404-2502617c-4bc5-11e8-83fd-40d87363944f.PNG)

**Comment by kloon** [comment]
@bear07 In the future please provide a bit more details when creating an issue, you did not enter any description of what the issue is, just attached a screenshot.

I am unable to recreate this on a local copy http://cld.wthms.co/bexiRs

I'd suggest you use the screen options tab an ensure all the columns are selected there. If the problem persists it could be a plugin or your theme adding a roque column somewhere that is causing the issue.

I would test this by disabling all plugins except WooCommerce and switch to a default theme like Twentyseventeen or Storefront and test again. You can find the culprit by enabling plugins again one by one and switching back to your theme testing.
