### ISSUE TITLE
[improvement] allow editor in order notes

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce#19906]
When writing an order note that will get sent to the customer, could we please have the ability to add line breaks (and ideally, formatting)?  Also would be good if when clicking in the note box to write, it could pop open a larger box to make it easier to write?

Typically, the order note that gets sent to the customer has line breaks stripped out and a large paragraph can be hard to read.

Thanks for the consideration.

**Comment by kloon** [comment]
Order notes does accept line breaks and limited HTML tags. If the formatting is missing from the email then it might be the mail client stripping it out due to incorrect html tag usage. I know email clients can be very temperamental with the usage of html, certain elements may not always be supported by all email clients.

The formatting does carry through to the order sidebase as well as the customer my account page correctly for me http://cld.wthms.co/WYqpiI http://cld.wthms.co/iVHzzA

**Comment by kloon** [comment]
The editor is in the sidebar so there is not much space to expand it or include the WYSIWYG editor. Notes also utilise the WordPress comment system so there are limitations on what can and what cannot be used.

I'd even argue and say that notes should not be used for long paragraphs of text, it is for quick notes on the order. What is a note? a brief record of points or ideas written down as an aid to memory.

We have no plans to support markdown or include an WYSYWYG editor anytime soon. It seems like you are after functionality not indented for note taking on an order?
