### ISSUE TITLE
Product quantity not decreased on manual order creation

### ISSUE THREAD

**Issue by Aerendir** [woocommerce/woocommerce#19931]
I've just created a new order manually (on the phone) and I'm noticing that the product quantity is not decreased.

It seems that the event is not notified as other plugins that require to know about quantity changes are not notified (eBay and Amazon plugins).

## Steps to reproduce the issue

1. Create a manual order clicking on "Aggiungi Ordine (New order)" in the Orders list (WooCommerce > Orders > Add Order)
2. Add a product to the Order and other details about shipping
3. Save the Order

## Expected/actual behavior

I expect the quantity of the products in the Order decreases but it doesn't.

## WordPress Environment

<details>

```
WooCommerce Versione 3.3.5
WC Database Version: 3.3.5
```

</details>

**Comment by kloon** [comment]
@Aerendir because backend orders are a manual process the taxes and stock also require some action from the person creating the manual order to calculate and reduce stock.

The stock reduction settings are currently not very intuitive and we know that, we will make this better when we redesign the screen in the future, but for now you can simply click on an item which will reveal the button to reduce the stock http://cld.wthms.co/DoNEuO

**Comment by Aerendir** [comment]
Ok, I understand, but leaving this to a human being is prone to errors: if I add a product to an order it simply should decrease its quantity not leaving the operator to do another additional action.

Imagine I'm on the phone, creating the order: I add the product to the order, then before I click "Reduce stock" the customer asks me something distracting me, then I forgot to reduce the quantity... Result: the quantity is not reduced and this is an error caused by humans.

It is way more logical to automatically decrease the quantity once the order is created, doesn't it?

**Comment by mikejolley** [comment]
This is a duplicate. See https://github.com/woocommerce/woocommerce/issues/13359
