### ISSUE TITLE
Products Updated via API with 0 stock and no backorders, show as On Backorder

### ISSUE THREAD

**Issue by PixelHeroMedia** [woocommerce/woocommerce#19956]
This bug is identical to #19485 except it occurs when updating products via the API. 

Exactly the same scenario. The API class has 'no' as the default backorder value, but we have every out of stock product that gets updated showing as 'On Backorder' even when the Backorders field is set to Do Not Allow.

**Comment by mikejolley** [comment]
Do you want to provide a sample API requests?

**Comment by mikejolley** [comment]
![monosnap 2018-05-03 15-22-09](https://user-images.githubusercontent.com/90977/39582472-ee068562-4ee5-11e8-839e-dd6b94a4ec1f.png)

No issue it seems. The bug is unlikely to be the same because unlikely the importer, only fields passed to the API are updated.

Will need system status report + example of the request you're sending to see if this really is an issue, but first attempt I tried doing a stock update and it was fine; backorder status did not change, and stock status changed between in stock/outofstock depending on whether I sent stock_quantity of 1 or 0.

Thanks

**Comment by PixelHeroMedia** [comment]
My 'backorders' value is false - not "no". Is there any recent change of this value? The rest is the same.

**Comment by mikejolley** [comment]
@PixelHeroMedia No, it's a string in rest api v2 as documented on https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties
