### ISSUE TITLE
Hidden fields without underscore prefix are visible in emails sent to users

### ISSUE THREAD

**Issue by GeorgeBotsev** [woocommerce/woocommerce#19968]
The problem happens when there are some hidden fields that are without underscore prefix.
In our plugin, we add the fields via "woocommerce_hidden_order_itemmeta" filter to the order items.
Our field names are without the underscore prefix and this used to work up to now and it works in the backend.
However, once you send an e-mail to the user - the fields are added to the product and displayed there - and should not be displayed.
Here is an example of the problematic email
![image](https://user-images.githubusercontent.com/4906133/39629883-3fd0a00a-4fb6-11e8-9db0-c0356fffd0ba.png)

**Comment by kloon** [comment]
woocommerce_hidden_order_itemmeta is only used when displaying the order items after an order. Emails and backend tables uses [get_formatted_meta_data ](https://github.com/woocommerce/woocommerce/blob/2a4b3640696542488644c15ba92490081458b53f/includes/class-wc-order-item.php#L257) which by default will hide all fields starting with an _ only.

You have 2 options In order to hide it from emails, prefix your meta keys with an _ or hook into woocommerce_order_item_get_formatted_meta_data and just unset the field from there if present.
