### ISSUE TITLE
Not autoloading all Wordpress options being used by WooCommerce

### ISSUE THREAD

**Issue by louiswalch** [woocommerce/woocommerce#19979]
During an analyzation of my websites performance I noticed a number (29) of Wordpress options which are coming from WooCommerce and are being queried on every page - even a content-only page. The 29 queries don't negativly impact the execution time terribly, but every little bit helps. 

I'm curious why they are not being autoloaded?

```
woocommerce_ga_id
woocommerce_ga_standard_tracking_enabled
woocommerce_ga_support_display_advertising
woocommerce_ga_support_enhanced_link_attribution
woocommerce_ga_use_universal_analytics
woocommerce_ga_ecommerce_tracking_enabled
woocommerce_google_analytics_settings
woocommerce_tax_display_cart
woocommerce_lock_down_admin
woocommerce_shipping_cost_requires_address
woocommerce_shipping_debug_mode
woocommerce_simplify_commerce_settings
woocommerce_gateway_order
woocommerce_bacs_settings
woocommerce_bacs_accounts
woocommerce_flat_rate_settings
woocommerce_free_shipping_settings
woocommerce_international_delivery_settings
woocommerce_local_delivery_settings
woocommerce_local_pickup_settings
woocommerce_cod_settings
woocommerce_stripe_sepa_settings
woocommerce_stripe_bancontact_settings
woocommerce_stripe_sofort_settings
woocommerce_stripe_giropay_settings
woocommerce_stripe_ideal_settings
woocommerce_stripe_p24_settings
woocommerce_stripe_alipay_settings
woocommerce_stripe_bitcoin_settings
```

**Comment by GlennMartin1** [comment]
Related - see https://github.com/woocommerce/woocommerce/pull/19918 which is set to ship with WC 3.

**Comment by mikejolley** [comment]
`woocommerce_lock_down_admin` is deprecated and can be deleted.

 #19918 as @GlennMartin1 points out tweaks the core ones so they are autoloaded instead of queries.

The others (gateway specific) are out of core's control. By default settings are set to autoload. If they are not autoloading, it means the option was added with autoload disabled. That could have been from the plugin itself, or something else (external to WC) may have changed this behaviour.

The core shipping method ones are odd - they are definitely autoloaded my side. Perhaps this is due to an older setting in an old WC version. I'll tweak the class to force autoload on for those. It won't trigger until save though so be aware.

Thanks

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19998
