### ISSUE TITLE
Password Strength Meter - Deletes Element

### ISSUE THREAD

**Issue by mrgrt** [woocommerce/woocommerce#19970]
The [password-strength-meter.js](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/password-strength-meter.js) script adds and removes the element with the class 'woocommerce-password-strength' dynamically (which is used to indicate password strength). This prevents template customisations in the [myaccount/form-login.php](https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/form-login.php) (for example) as the script assumes where the 'woocommerce-password-strength' element should be. 

Expected Behaviour: Add element with the class 'woocommerce-password-strength' and script should use that element to indicate password strength. 

Actual Behaviour: Element with class 'woocommerce-password-strength' removed and added after password field. 

Steps taken to create the issue: Create element with class 'wocommerce-password-strength'. Input password and then delete password and finally start typing password again. 

Files effected - [password-strength-meter.js](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/password-strength-meter.js)

![password-strength](https://user-images.githubusercontent.com/1732738/39630983-e4db2498-4fa8-11e8-91c5-9d7f4842538a.gif)

**Comment by madeincosmos** [comment]
We just discussed this chat, and from what I understand the original password strength label is removed when user deletes the password:

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/password-strength-meter.js#L49

When it's added back again it's always right after the password field which may not be compatible with the theme. Using `display: none` instead of removing that field should solve the problem.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20006
