### ISSUE TITLE
Duplicate named variables.

### ISSUE THREAD

**Issue by btassone** [woocommerce/woocommerce#20008]
Re-wrote this for brevity.

So not necessarily a bug, but maybe poor variable naming? wc-template-functions.php the function 'woocommerce_grouped_add_to_cart' loads the grouped.php template.

The parent grouped product at the time of that call is assigned to $grouped_product which is immediately overwritten by $grouped_products first child on the first foreach call.

This is not a bug perse, but def a code smell. Can we change one of those 2 variables to be more reflective of what it actual is? I would suggest the one in the template functions file be changed from $grouped_product to $grouped_product_parent to avoid confusion.

**Comment by claudiulodro** [comment]
If I follow what you're saying correctly [this `$grouped_product`](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1513) is getting overriden by [this `$grouped_product`](https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/add-to-cart/grouped.php#L36).

In order to maintain backwards-compatibility the best solution would be to rename the `$grouped_product` in the `foreach` loop to something else. Changing the name of the "global" `$grouped_product` would likely break things for custom themes with template overrides.

PR incoming.

**Comment by btassone** [comment]
@claudiulodro Yes, that was exactly it. Thank you for the speedy response and action! You guys rock!
