### ISSUE TITLE
From OOP to Structured architecture

### ISSUE THREAD

**Issue by dyszczo** [woocommerce/woocommerce#20026]
While I was developing a plugin depentent on WooCommerce I found some rather strange refactor approach in the WC code. For example the reduce_order_stock method from WC_Order class was extracted and put into library file wc-stock-functions.php as standard function without OOP context.
I’m wondering why decision like that could be made? If the purpose of this change was to slim down the WC_Order class I could easly imagine that the WC_Order_Stock or even WC_Stock class(decorator maybe?) could be written to deal with the stock managing issues.

I've even seen the comment like "* This is a private function (internal use ONLY)" because there is no private/protected keyword when the function is outside of class so there is no language tool to properly manage encapsulation.

I was wondering why reduce the OOP and enlarge static function base? Is this because structural code seems easier to maintain?

**Comment by mikejolley** [comment]
> I've even seen the comment like "* This is a private function (internal use ONLY)"

Yes, a function which wraps a WordPress function has this. Likely because when WP adds support for what the wrapper does it will be removed. _Reminder; most of WP itself is not written with Object Oriented paradigms._

>  If the purpose of this change was to slim down the WC_Order class I could easly imagine that the WC_Order_Stock or even WC_Stock class(decorator maybe?) could be written to deal with the stock managing issues.

- `WC_Order` previously did everything; stock reduction, sending mails, handling templates, saving, loading.
- It was decided `WC_Order` should only represent an order object so this logic needed moving out.
- Rather than further complicate the codebase with new classes/patterns, these functions (`wc_reduce_stock_levels`) and so on were simply moved out into functions.

Could we have used <insert pattern here>, probably. 

The immediate goal was to remove this logic from `WC_Order`. I'm sure there are many ways to approach the same problem. There will be differing opinions on any and all approaches.

I'm not sure what your motivation was for opening this issue. It certainly cannot be reverted now. If you have cleaner patterns you'd like to propose feel free to contribute some examples/PRs. Just be aware that:

1.  We need to maintain backwards compatibility where possible.
2. We still have a committment to older versions of PHP where certain language features won't be available.
3. It should only be implemented at this point if there are tangible benefits to moving from procedural code, such as performance improvements or ease of use, not personal preference or ego.

Thanks!

cc @claudiulodro

**Comment by dyszczo** [comment]
Thanks for your answer :)
My motivation for creating this issue was that as I'm creating the plugins for WC I'm trying to follow example/foundations set by the WC architecture. Some of my decisions would be easier to make If I understood better what was the reason behind some steps and in which way in future the WC will go.
For example should I put more pressure on OOP in peer review code because that the direction WC team set or be more flexible on that matter.
My goal is not the criticism for the sake of my ego but rather better understanding.

**Comment by mikejolley** [comment]
👍 Some of the decisions inside WC are legacy or just following conventions in WP. I think it depends on your project :)
