### ISSUE TITLE
Loading error on checkout page

### ISSUE THREAD

**Issue by ced--ced** [woocommerce/woocommerce#20043]
When going to the checkout page, the page is loading and then gets all blank only with the store email address. We have uninstalled all the plugins but WooCommerce and tried with different themes including WP defaut ones, WC Storefront and Divi.

WP v.4.9.5
WC v.3.3.5

**To Reproduce**
1. Go to https://www.ibrostudio.com/projets/karethic3
2. Add a product to the cart
3. In the cart block in the header, click on "Commande" to go to the checkout page, or go through the cart page first ("Voir le panier")

**Screencast**
https://www.useloom.com/share/2eaf0ec5f9594108acf5188c96a4ecb0

**Comment by mikejolley** [comment]
This doesn't appear to be happening now so I assume you're working on finding the conflict.. The checkout loaded on your store for me and I was able to hit the place order button. I couldn't fully check out because of missing shipping.

For future ref, please also provide the system status report as requested. Ideally the steps to reproduce should work on a clean install too, otherwise it indicates a conflict/plugin issue on your store.

```
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
```

Let me know if you find anything that needs our attention if it turns out not to be a plugin conflict.

Thanks

**Comment by ced--ced** [comment]
Hi,

We've found indeed the problem and it was a code to display and protect an email address in a page content... So it wasn't a WC problem nor a plugin conflict at the end.

Thanks anyway for looking at it so quickly.
