### ISSUE TITLE
Wrong dependency for custom image id in single product image template

### ISSUE THREAD

**Issue by jannis24** [woocommerce/woocommerce#20064]
**Describe the bug**
Inside of the single-product/product-image.php template is a wrong dependency for customized image id's. This bug happens for example if you want to show a different product image by hooking into `woocommerce_product_get_image_id` to change the current one. Even if it is done, it will show the Woocommerce placeholder image.

**To Reproduce**
To reproduce the bug, we can simply make a change to the single product image template.
1. Create a new product and DON'T Set a thumbnail.
2. Upload an image to your WordPress media.
2. Go to your single product image template '/wp-content/plugins/woocommerce/templates/single-product/product-image.php'
3. Check out the line 29 '`$post_thumbnail_id = $product->get_image_id();`'
4. Change it to '`$post_thumbnail_id = 0000;`' - (Where 0000 is your media image id)
5. Check out the single product view in the frontend and it won't display your customized image.

**Expected behavior**
The expected behavior should be to display the customized image.

**Solution**
The error is caused by line 40 '`if ( has_post_thumbnail() ) {`'. At this state, the dependency is based on the product object, but not on the product thumbnail. 
The full solution would include two steps:
1. Change the line 40 to the product thumbnail id: '`if ( $post_thumbnail_id ) {`'
2. Change line 32 to '    '`woocommerce-product-gallery--' . ( $post_thumbnail_id ? 'with-images' : 'without-images' ),`'

**WordPress Environment**
<details>
```
This error is independent of the WP version.
```
</details>

**Comment by mikejolley** [comment]
Even if we changed our implementation for this, other places in themes would remain broken when using standard WordPress loops. `has_post_thumbnail` is common and standard WP theme code. This uses https://developer.wordpress.org/reference/functions/get_post_thumbnail_id/

`get_post_meta` does include filters, so you can add one there to return a custom ID based on post ID to work around this.

Since the `has_post_thumbnail` call is in a template file, not one of the core data classes, that will be your best option.

Thanks
