### ISSUE TITLE
API Creating order even if the payment method is disabled

### ISSUE THREAD

**Issue by ZainSohail** [woocommerce/woocommerce#20073]
**Describe the bug**
The API is creating the order even if the payment method I entered is disabled or even if it doesn't exist. Just ran the create API call from here: http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

**To Reproduce**
1. Disable all payment methods.
2. Run create order call from API.

**Expected behavior**
If the payment method is disabled it should notify and should not create the order. Probably send some error notification

**Comment by mikejolley** [comment]
This is not validated and allows open input; since this is a manual order and doesn't actually take payment no validation is performed. Also important to note that adding validation here would:

1) Break update requests if a past order was paid with a no longer existing method
2) May break custom implementations where a custom string is used for the payment method

As such this validation should not be added IMO. cc @claudiosanches for his feedback

**Comment by claudiosanches** [comment]
Mike is correct, should not validate it, since it's something manual, you should create your own payment integration on your app.
