### ISSUE TITLE
jQuery UI styles changes default WordPress Metabox style

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce#20124]
When WooCommerce is active, WordPress Metaboxes style changes, the most noticed change is in the header of the Metabox, but also it changes the font and other elements like the border of the Metabox.

Here is an example with the differences:
![01](https://user-images.githubusercontent.com/456223/40228562-d6bd8394-5a91-11e8-8180-80d3bc7c3cfa.jpg)

Will be great if we can get rid of `jquery-ui-style`, either by removing it from WooCommerce or at least provide a filter for dequeue it safely.

I´m considering dequeue it in the pages where the Metabox appear, but I´m not sure about the consequences. Is it safe to dequeue it only in some pages where the Metaboxes appear?

Here is a related issue #19173 about jQuery ui styles.

**Comment by mikejolley** [comment]
This script is loaded only on WooCommerce screens - it's used for our jQuery UI implementations. You can dequeue it with the `'jquery-ui-style'` handle. 

No filter is needed - it can be dequeued via WordPress hooks. Just bare in mind any extensions using jquery UI will likely break. 

There is nothing else that can be done since that meta box pictured is loading a different set of jquery UI styles, and that style is enqueued via a different plugin. There is no CORE WordPress UI stylesheet both can share.

Thanks
