### ISSUE TITLE
New Zealand Region not shown in orders or confirmation emails

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#20145]
**Describe the bug**

1169381-zen-woothemes

Customer is from New Zealand and includes a region in address for billing/shipping. The Region does not show in Order or the emails. It is shown however when clicking the edit icon in the order.

**To Reproduce**
WC 3.3.5

Purchase a product and add a NZ address. Fake one I used:

209 Waimea Street
Brooklands 4310
Bay of Plenty, New Zealand	

In Order and in the confirmation emails, Bay of Plenty does not show.

**Screenshots**

In the order:

![](http://cld.wthms.co/6E7sb6+)
Link to screenshot: http://cld.wthms.co/6E7sb6

In the emails:

![](http://cld.wthms.co/kZIGzx+)
Link to screenshot: http://cld.wthms.co/kZIGzx

When editing the address in order:

![](http://cld.wthms.co/0bsVLY+)
Link to screenshot: http://cld.wthms.co/0bsVLY

**Comment by tarkan123** [comment]
Yes we are seeing the same issue  - the state/county is not even displayed in the admin order details or preview page.

If you edit the billing or shipping address, the correct state is correctly set in the drop-down selector.

**Comment by tarkan123** [comment]
I should add technically it is not needed, and how the address is represented by Woo is correct per NZPost guidelines. I have read all the published standards and they never make mention of state/region in the addressing.

Per NZPost guidelines address format is as-

Street number + name 
Suburb
Town/City + Postcode

**Comment by mikejolley** [comment]
> Don’t use a province, region, district or territory name instead of (or in addition to) the town or city name.

https://www.nzpost.co.nz/personal/sending-within-nz/how-to-address-mail/correct-address-formats-envelope-layouts

We appear to be using the correct format. Postal addresses do not need regions. I've also looked at several address examples and none include this. 

To include the state or change how the postal address is formatted there is a filter `woocommerce_localisation_address_formats`

https://github.com/woocommerce/woocommerce/blob/c61e0688c667c04d1eec42acfb4a147e74766b5f/includes/class-wc-countries.php#L498

Due to this I'm closing as wontfix.

On a related note, I imagine region is useful for tax/shipping zone rules only. It might be worth asking some NZ based users if it's actually needed because if not we can remove it from our addresses/checkout and avoid collecting useless data. @warrendholmes adding to your list - maybe tracker can identify some users to ask.
