### ISSUE TITLE
[API] Creating new product via API is not setting post_parent of the image attachment post.

### ISSUE THREAD

**Issue by bigtomjp** [woocommerce/woocommerce#20150]
When creating a new product via API the post_parent of the image attachment posts is not set to the ID of the product post it is attached to. This results in all product images being classified as unattached. This causes a number of issues with maintaining a large media library.

Having this issue with WC 3.0.8 and WP 4.7.5. Is this addressed in a later version?

Expected behavior
post_parent of product image attachments should be set to the ID of the product post they are attached to.

WordPress Environment
4.7.5

**Comment by mikejolley** [comment]
If you want them attached you can do so when creating the media library item - https://developer.wordpress.org/rest-api/reference/media/#create-a-media-item

We don't link them when adding to a product via the API however. This is because the attachment parent ID is a 1:1 relationship and we may have cases where a gallery image is linked to multiple products, something the WooCommerce gallery supports. Changing post parent IDs could therefore cause breakage or undesired results. As such, we've no plans to change this.

Hope this makes sense.
