### ISSUE TITLE
Woocommerce Displaying Duplicate Product Categories On Front End 

### ISSUE THREAD

**Issue by kanyevest** [woocommerce/woocommerce#20161]
**Describe the bug**
Since upgrading from an early 3.0 release to 3.3.5 product categories are duplicating on the front end of the store. 

As can be seen here: http://aurello.co.uk/product-category/splashbacks/

I've tried to add:

.products .products.container-fluid .product-category { 
display: none; 
}

To the CSS as a fix but it doesn't work. 

I apologise for the bare bones description, I have little experience coding and am just trying to find the source of the problem. At the minute I am thinking of rolling back to the previous version of Woocommerce (I believe it was 3.1.4). I am appreciative of any help or advice that can be given.

**Comment by mikejolley** [comment]
This one is caused by out of date template files. There is some duplication in the archive template.

If you look at WC > Status it should tell you which files are outdated in the theme. If the theme has updates, run them - it's likely fixed if this is a WooCommerce theme. If not, compare your versions to those in core and update where needed: https://github.com/woocommerce/woocommerce/tree/master/templates

https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

Thanks

**Comment by kanyevest** [comment]
Thanks Mike! Found the culprit in the archive template.
