### ISSUE TITLE
Since 3.4, product do not use gutenberg interface anymore

### ISSUE THREAD

**Issue by emmanuelhonore** [woocommerce/woocommerce#20201]
So it's not 100% related to woocommerce but since 3.4 release, products use the wp classic editor when gutenberg is installed. I couldn't find any info about that, any way to make to it work again ?

**Comment by mikejolley** [comment]
Hi there

This has been disabled on purpose. Since WooCommerce is not optimised for the Gutenberg editor we've decided to keep the old editor for now so sites do not break when WordPress 5.0 is released. Products are not content focussed so using Gutenberg with our meta box placed awkwardly at the bottom is not ideal.

See:
https://github.com/woocommerce/woocommerce/blob/9abc28d03d90e1b7b9d05b8c6b7946f0e2f3d316/includes/class-wc-post-types.php#L29
https://github.com/woocommerce/woocommerce/blob/9abc28d03d90e1b7b9d05b8c6b7946f0e2f3d316/includes/class-wc-post-types.php#L579

There are plans to look at new options for editing products, potentially using Gutenberg as a framework, later in the year :)

Thanks!
