### ISSUE TITLE
Force secure checkout setting need to be accessible to bypass gateway ssl notices

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#20229]
In v3.4 if the site address URL has `https` then the "Force secure checkout" setting is automatically hidden — the result is that you can't get rid of the Square notice unless of course, you access wp-admin/options.php page and manually change `woocommerce_force_ssl_checkout`

Steps to reproduce the behavior (when site address URL is https): 

1. Go to wp-admin/admin.php?page=wc-settings&tab=advanced (no setting)

This is the notice (Square) 

<img width="822" alt="screen shot 2018-05-25 at 11 03 32 am" src="https://user-images.githubusercontent.com/6198774/40536392-467a11f0-600c-11e8-8ee8-46517e17f22e.png">

This is where to manually go in and change it to bypass the notice

<img width="667" alt="screen shot 2018-05-25 at 10 50 52 am" src="https://user-images.githubusercontent.com/6198774/40536425-5bc29fbe-600c-11e8-988d-7371104c4f7b.png">

**Comment by mikejolley** [comment]
@rynaldos and cc @bor0 / @roykho 

Force SSL is *not* required to have a secure site using HTTPs. This is a legacy setting we'll be phasing out since we recommend entire sites are served over HTTPs.

Gateways should not force users to enable this setting without first checking `wc_site_is_https()` - this is what hides the setting also. Already secure sites don't need it.

Recommend finding gateways which tell users to enable this option and adding a second check for `wc_site_is_https()`. If That is true, no notice is needed.

Hope this makes sense.

**Comment by reubensimute** [comment]
I have the same problem in that my Site has SSL however, I am receiving notification that "Square is enabled, but the force SSL option is disabled; your checkout is not secured! Please enable SSL and ensure your server has a valid SSL certificate." 

The option to force SSL is NO longer available on the specified URL and because WooCommerce has moved the Checkout Tab to somewhere else and supposed removed these options. And though I was able to navigate to the Checkout setting, the option to force SSL or Allow Guest checkout is NOWHERE to be seen.
How can work around this?

**Comment by mikejolley** [comment]
Ignore it until patched...it doesn't affect functionality.

**Comment by cp-bwg** [comment]
This is still an issue.  2 years later.

**Comment by jshuadvd** [comment]
Can we get some updates here?
