### ISSUE TITLE
woocommerce_add_to_cart_validation won't validate based on shop archive page with AJAX add to cart.

### ISSUE THREAD

**Issue by giulianorapoz** [woocommerce/woocommerce#20255]
When validating the cart using `woocommerce_add_to_cart_validation`. The hook is not behaving as expected and wont apply the rule `is_page()`, based on the unique shop archive page the user is currently on. This is when using AJAX to add items to the cart, so should work as default behaviour? 

**See example function:**

```
add_filter( 'woocommerce_cart_redirect_after_error', '__return_false'); 
add_action( 'woocommerce_add_to_cart_validation', 'restrict_cart_items );

 function restrict_cart_items ($cart_item_data) {

   global $woocommerce;
   $item_count = $woocommerce->cart->cart_contents_count;

//THE IS_PAGE() DOESN'T CHANGE HOOK BEHAVIOUR
   if((is_page('strongshop') || is_page('strongshopmobile')) && $item_count >= 20){
      return false;
   }
   return $cart_item_data;
}
```

**Comment by giulianorapoz** [comment]
Solved! Needed to call return on the shop pages instead of using them in the IF loop. The function works.

```// Prevent Redirect after cart error
add_filter( 'woocommerce_cart_redirect_after_error', '__return_false');
add_action( 'woocommerce_add_to_cart_validation', 'restrict_cart' );

 function restrict_cart($cart_item_data) {

   global $woocommerce;
   $item_count = $woocommerce->cart->cart_contents_count;

   if($item_count >= 20){
      return false;
   }
   return $cart_item_data;
   return is_page('strongshop');
   return is_page('strongshopmobile');
}```

**Comment by kloon** [comment]
Unfortunately, that is just how WordPress works, If it is executed within an ajax request, is_page() won't be set because the page you're making the request from was a previous request.

There's a product_id and a quantity passed to the woocommerce_add_to_cart_validation filter, which you can use for validation should you wish. Just as a note, you are using woocommerce_add_to_cart_validation as an action and not a filter as it should be.
