### ISSUE TITLE
Product category / subcategory display broken

### ISSUE THREAD

**Issue by Tsukimara** [woocommerce/woocommerce#20292]
After updating WOOCOMMERCE from 3.2.3 to the latest 3.4 version our pages seem to be broken.
We are using a product category / subcategory hierarchy, but instead is now just displaying the products by itself and not even all of them.

Correct display on the 3.2.3 version
<img width="1301" alt="schermafbeelding 2018-05-29 om 15 01 06" src="https://user-images.githubusercontent.com/3288855/40660627-d459ae8e-6351-11e8-8056-22888aedad4d.png">

Broken page after updating to 3.4
<img width="1293" alt="schermafbeelding 2018-05-29 om 15 01 17" src="https://user-images.githubusercontent.com/3288855/40660629-d84ec916-6351-11e8-84a5-ec96756eb6db.png">

The only thing we've done is updating and all of the settings have not been touched.

**Comment by mikejolley** [comment]
The theme system changed in 3.3. This looks to be a custom theme - you'll need to define support in order to continue using template overrides.

See the following wiki articles:

- https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes
- https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

After defining support, your overrides should be used again. Please note; we don't support custom themes here.

Thanks
