### ISSUE TITLE
Prices in woocommerce

### ISSUE THREAD

**Issue by jhosewinett** [woocommerce/woocommerce#20299]
Hi! i am having troubles wiith woocommerce. I wrote certain prices for my products but suddenly, like 3 days later, the prices changed. When i got in the part of the products, the prices still the same as i put in before but in the preview of my website, there are another prices totally differents. I dont know how i can fix this. Please, i need some help.

**Comment by kloon** [comment]
@jhosewinett In the future please include the information requested when opening an issue as that helps us troubleshoot and resolve issues faster.

Unfortunately I do not have much to work with here as the info requested was omitted, but I would look at caching first, do you have any caching plugins running on your site? Chances are you are caching the product pages and it is loaded an old outdated cached version.

Alternatively look and see if you do not perhaps have sale prices entered on the products? If you have they will show instead of the original price.
