### ISSUE TITLE
"account already registered with email address"

### ISSUE THREAD

**Issue by christiaanyork** [woocommerce/woocommerce#20357]
When new customers go to checkout and input details including email address they cannot go to next page to pay. Instead this comes up: 'An account is already registered with your email address. Please login'.
It is a new customer and email address has never been used at my website before. 

How to resolve this? Do I need to deactivate and delete the woocommerce plugin and download and activate it again? 

If I delete it will my current customer orders disappear even after I reactivate it??

**Comment by kloon** [comment]
Unable to replicate this locally so do not think this is a bug. What happens when you try and do a password reset with the email that is giving the error it already exists, do you get any errors or do you receive the password reset email?

Also it is unclear if this happens with just one customer or all customers on your site?

**Comment by christiaanyork** [comment]
Hi kloon, thanks for responding. It appears I've found the problem. One part of the theme I installed needed updating since I've updated to the new WooCommerce. So the problem was not with WooCommerce. Many thanks!!
