### ISSUE TITLE
WC-CLI update image and demensions get Error responding

### ISSUE THREAD

**Issue by Zorion-zozo** [woocommerce/woocommerce#20350]
Hello master:

Today i used wc-cli to update my product item, but i could not update the dimensions and images attributes. They both came into a same problem like:

```
Invalid parameter(s): dimensions {"status":400,"params":{"dimensions":"dimensions is not of type object."}}
```

My original code is as following:
```php
$dimensions = json_encode(array('length'=>'8.25','height'=>'2.15','width'=>'4.75'));
$str = "wp wc product update 940 --dimensions='$dimensions' --user=aaa";
system($str);
```

So ,what's wrong with my code??

**Comment by kloon** [comment]
A proper call should look like this ` wp wc product update 195 --user=admin --dimensions='{"length":"100","width":"100","height":"100"}'`

I suspect because you as building a variable between double quotes and then the $dimensions variable contains double quotes around values as that is how proper json is formatted, it is resulting in unescaped strings breaking the command.

I tested the example I provided on my local and it updates fine.

Print out $str and see how it looks, you will notice you have double quotes in the middle of your string which is breaking it, those you will need to escape, so try passing $dimensions through addslashes.
