### ISSUE TITLE
Price filter slider min/max handle should be reversed for RTL sites

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#20372]
**The bug**
The left handle on the slider alters the minimum price rather than the maximum.

**Screenshots**
![Screenshot](http://cld.wthms.co/9gjoxr+)
Image Link: http://cld.wthms.co/9gjoxr

**Expected behavior**

The left maximum handle on the slider should alter the maximum number and the minimum price is with the right.

See: #20221 

Tested against current `master`

**Comment by mikeyarce** [comment]
This is a bug in Storefront right now, because it loads it's own `woocommerce-rtl.css`

Let's keep this bug open though because this also happens on Twenty Seventeen right now because bey default it also doesn't load `woocommerce-rtl.css`.

**Comment by claudiulodro** [comment]
This [doesn't seem to be supported in jQuery UI slider](https://bugs.jqueryui.com/ticket/10658). There is a third-party workaround library [here](http://keith-wood.name/rtlsliders.html), but it will have to be reviewed/tested.

**Comment by mikejolley** [comment]
@mikeyarce The missing RTL sheet in 2017 will be fixed in 3.4.2. cc @tiagonoronha about missing storefront RTL file.

@johndcoy @claudiulodro This is an issue with the jQuery UI library we're using which has a trac issue here: https://bugs.jqueryui.com/ticket/10658

> There is a third-party workaround library here, but it will have to be reviewed/tested.

I'd recommend passing this on to the user to implement rather than including this in core. We should probably wait for jQuery UI to patch this for a few reasons:

1. The 3rd party lib changes how jQuery UI works and may have side effects. 
2. Using a 3rd party lib means extra review and maintenance in core.
3. [We're likely going to be removing jQuery in the future, so including more jQuery scripts now should be avoided where possible.](https://github.com/woocommerce/woocommerce/issues/18395)
4. The price slider itself does not scale well and we've had discussions about replacing this with pricing band taxonomies instead. I think we should look into this again as an alternative to using sliders.

For those reasons I suggest we mark this as won't fix, wait for a jQuery solution, or for the slider to be removed from WooCommerce core, and we document/recommend users use the other library if desired.
