### ISSUE TITLE
Custom webhooks topics are not persisted in admin UI despite data being saved

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#20404]
#### PR in #20406 

**Describe the bug**

If a third party tries to create a custom webhook, the topics can be correctly shown in the WooCommerce > Settings > Advanced > WebHook edit screen page when creating or editing a webhook. However, upon saving the webhook, the topic chosen is not persisted in the enhanced dropdown. However, the data is correctly stored in the Webhook, pointing to an issue with the HTML view that outputs the selected topic in the edit screen.

This can be reproduced creating a custom webhook or with a plugin like Subscriptions that introduces custom webhooks.

This is not a custom code issue (PR incoming).

**To Reproduce**

1. Ensure you have Subscriptions active or add a custom webhook via custom code
2. Go to WooCommerce > Settings > Advanced > Webhooks
3. Select one of the Subscriptions topics
4. Hit save
5. You'll notice that the selected topic is not persisted
6. However, if you dump data for that Webhook, you'll notice the topic selection is currently stored in the Webhook object

**Expected behavior**

Custom webhook topics should be persisted in the admin UI dropdown.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
I think this is something on your end. I tested the Subscriptions webhook saving with WC 3.1 through 3.4 and it doesn't save properly in any of them. In <=3.2 you get this behavior:

It shows up and can be selected:
<img width="665" alt="screen shot 2018-06-06 at 8 03 11 am" src="https://user-images.githubusercontent.com/7317227/41047017-72d68f0a-6960-11e8-9d38-cb0384526926.png">
But after saving it still does not match the select:
<img width="663" alt="screen shot 2018-06-06 at 8 03 24 am" src="https://user-images.githubusercontent.com/7317227/41047019-74d5794c-6960-11e8-895f-dc3b5010f87f.png">

I believe these issues are because the topic you register comes across as 'custom' in `WC_Admin_Webhooks::get_topic_data` instead of e.g. `subscription.created` (possibly because of how the webhooks are registered).

As another data point, [the basic custom webhook example](https://gist.github.com/jessepearson/66a0e72706b99c15b52dee7ce59e1d31#file-adding_new_webhook_topics-php-L4-L49) saves/selects fine.
