### ISSUE TITLE
Rest API - Sideload of Downloadables

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#20415]
**Is your feature request related to a problem? Please describe.**
Images is now sideloaded into media library for external sources when updating a product from rest api.

This makes it possible to side load images into media library, without any third party plugin / theme. This way woocommerce is the only requirement to support this feature.

To allow side load for other filetypes into media library (for product downloads usage), you would need an additional plugin if api is used from another origin than which site is served from.

Which means I cant upload or side load downloadables into media library using woocommerce rest api alone, it forces me and my customers to install other plugins like JWT authentication to use core WooCommerce features which I find unnecessary and a potential security risk.

**Describe the solution you'd like**
Sideload could be added for downloadables the same way as your doing with images to handle this.

**Describe alternatives you've considered**
* WP Core Rest Api for upload - Not an option as this would need another plugin as JWT explained above and would be a potential security risk as WP Core rest api adds additional permissions for the user which is not wanted and not needed. Authentication process is also being allot more complex for the user & developer.

**Additional context**
Most of functionality should not be hard to implement as this is already completed for images. It would only be to do the same for the 'downloads' property for a product.

**Comment by claudiosanches** [comment]
> This makes it possible to side load images into media library, without any third party plugin / theme. This way woocommerce is the only requirement to support this feature.

We can do something to improve it, still need to allow external sources while downloading, many users does not upload all files into their WooCommerce installation, that's why this already is not done.

Leaving for voting, but still I should try include it into our REST API v3.

> WP Core Rest Api for upload - Not an option as this would need another plugin as JWT explained above and would be a potential security risk as WP Core rest api adds additional permissions for the user which is not wanted and not needed. Authentication process is also being allot more complex for the user & developer.

Ok for what you are saying, still out of WooCommerce scope, since the REST API is part of WordPress REST API, WooCommerce only provide new endpoints, still your app needs to control your whole WordPress installation, so you should use the WordPress REST API.

About Authentication methods will probably be better when WordPress introduce some standard one, so we should also remove ours from WooCommerce in the future, not to mention that you can enable WooCommerce authentication methods for all endpoints, even for WordPress ones, you just need it: 

```php
add_filter( 'woocommerce_rest_is_request_to_rest_api', '__return_true' );
```

**Comment by steffanhalv** [comment]
Thank you! Appreciate your fast feedback :)
