### ISSUE TITLE
Wrong Order Number on WP Dashboard

### ISSUE THREAD

**Issue by revendo** [woocommerce/woocommerce#20434]
Hi

When using a Plugin to achieve Sequential Order Numbers, the Woocommerce Order number displayed on the Wordpress Dashboard (Network Orders) is displayed wrong. It's using the WP Post Number instead.

**Comment by claudiulodro** [comment]
Hi there. That widget is new in WooCommerce 3.4, so this is an issue with the sequential order number plugin you are using not being updated yet to work with the new widget. I would contact the plugin author and see if they can put out an update. Thanks.

**Comment by ChaseWiseman** [comment]
@claudiulodro looks like the issue here is that WooCommerce is [using the order ID](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-dashboard.php#L363) for display in that new widget, but should be using the order `number` as is the case elsewhere in the admin.

Once that's fixed up, Sequential Order Numbers will display correctly 😄

**Comment by bekarice** [comment]
@claudiulodro see #20457 -- as Chase noted, needs core patch, not a plugin issue

**Comment by claudiulodro** [comment]
Good call, thanks @bekarice and @ChaseWiseman!
