### ISSUE TITLE
Import variable product in french

### ISSUE THREAD

**Issue by philochardbleu** [woocommerce/woocommerce#20430]
It seems that nobody can import csv files with attribute if not importing with first line in English.
The facts (very easy to reproduce) :
Product export CSV is correct when using WordPress in english or french.
CSV Product import does not import columns with attributes (for variable products) if french is set as wordpress language.
CSV Product import works correctly with wordpress in english language or with attributes on first line of CSV is changed to english titles.
A quick look in product_importer.php did not show an obvious mistake.
Probably a hard coding has been made instead of a $variable.

**To Reproduce**
1. Wordpress in french export a variable product
2. Wordpress in french import the file previously exported
3. There is no more variation neither attributes in the imoported csv. If exported column with variable attributes are blank on the CSV file.

**Comment by claudiulodro** [comment]
I think this is most likely the issue:

<img width="691" alt="screen shot 2018-06-07 at 11 10 51 am" src="https://user-images.githubusercontent.com/7317227/41118382-a2341de6-6a44-11e8-8026-0b3bdc059e9d.png">

The attribute values column is not automatically matching when the language is French,
(`Valeur(s) de l'attribut 2 -> Ne pas importer`) so the attribute values don't get imported if you are not paying close attention. This is most likely because of some escaping/sanitizing.

**Comment by philochardbleu** [comment]
That is true, but if you remap it, it does not work either.

**Comment by claudiulodro** [comment]
If I remap, it works when I try it. Can I get a CSV file that you have generated to see?

**Comment by philochardbleu** [comment]
Yes, this is my file. I tried again without success... I am sorry... a csv file
[wc-product-export-7-6-2018-1528404755909.txt](https://github.com/woocommerce/woocommerce/files/2082065/wc-product-export-7-6-2018-1528404755909.txt)

**Comment by claudiulodro** [comment]
The import works great on a site with only WooCommerce active when I map all the attribute columns:
<img width="690" alt="screen shot 2018-06-08 at 12 34 32 pm" src="https://user-images.githubusercontent.com/7317227/41177288-55107968-6b18-11e8-9e69-c059386e37eb.png">
Just to re-confirm, you have done this for all the attributes when importing? If you have done that and it works fine with English column names, it will most likely be fixed by the sanitization changes we'll do to solve the automatic mappings not matching.

<img width="1395" alt="screen shot 2018-06-08 at 12 32 24 pm" src="https://user-images.githubusercontent.com/7317227/41177193-0efd7bb0-6b18-11e8-9c29-bf24fbdb0b22.png">

**Comment by philochardbleu** [comment]
Unfortunately, it does not work with me. Just to show what I have done.
Remap has been done for all attributes as shown : 
![screenshot_2](https://user-images.githubusercontent.com/37799557/41178753-8db2e3be-6b68-11e8-889a-e735c3eff7f7.jpg)
Import seem to work great :  
![screenshot_3](https://user-images.githubusercontent.com/37799557/41178792-adeb792a-6b68-11e8-92a3-617237fe30ed.jpg)
![screenshot_4](https://user-images.githubusercontent.com/37799557/41178818-bd7ce126-6b68-11e8-8d0f-85441ab1ef66.jpg)
But no variation neither attributes : 
![screenshot_5](https://user-images.githubusercontent.com/37799557/41178851-dc9107ae-6b68-11e8-8dfe-6bcaf7ac0b91.jpg)
The re-exported file shows the new imports with blank column (starting at line 36).
[wc-product-export-8-6-2018-1528488236879.txt](https://github.com/woocommerce/woocommerce/files/2085913/wc-product-export-8-6-2018-1528488236879.txt)
My wordpress configuration has a lot of plugins, woocommerce is nearly pure (with stripe and name your price)....
I am very surprised that it works in your configuration.

**Comment by mikejolley** [comment]
Same results my side as @claudiulodro  - import worked but only after manually mapping that field which won't auto-map.

That is the issue we need to fix.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20486

**Comment by philochardbleu** [comment]
Good job ! Thank you.
