### ISSUE TITLE
This plugin breaks my hamburger menu on mobile.

### ISSUE THREAD

**Issue by shawnaleahsunshine** [woocommerce/woocommerce#20492]
I'm not sure how long this has been broken but it was brought to my attention that my main menu isn't working on the mobile site. I've searched everywhere for a way to fix it. I turned off all of my plugins and turned them back on one by one, refreshing as I go to see which one is causing it. Turns out it's this one. I've turned off my miniturizing of things on my website, reverted to an older version of WC back to 3.0, cleared my iphone cache and nothing works. The website is alwaysshineyourheart.com.

I would love it if I could use this plugin the way it was intended and what to do or look for if this were to happen again in future updates.

**Comment by mikejolley** [comment]
Hi,

The hamburger menu appears to require javascript, and your page has errors on it:

![shop for vegan leather clutches and yoga mat bags in designer fabrics 2018-06-12 11-33-21](https://user-images.githubusercontent.com/90977/41285562-7edde3a6-6e34-11e8-9c4a-f49d414f4fcf.png)

One of those scripts is from `//downloads.mailchimp.com/js/signup-forms/popup/embed.js`. Is this something you've added?

I'd try a few things;

1. Removing that script above (I assume it's a mailchimp plugin?)
2. Turning off script minification (you are using a plugin to optimise scripts and minify source code)

See if that clears it up. Otherwise post to the help desk so someone can take a deeper look/login.

Just to note:

> Turns out it's this one. 

You're likely using several plugins which only load when WooCommerce is turned on. Therefore this is misleading. If you just enabled WooCommerce and no other plugins I don't think you'd see the same issue if that makes sense :)

Thanks

**Comment by shawnaleahsunshine** [comment]
Hey Mike, 
Thanks for the info. Where do I locate that .js file or the code snippet to delete it? I've turned off that mailchimp plugin and it didn't do anything. I turned off all of the plugins aside from Woocommerce and still have the same issue. I had already tuned off minification before asking for help. 
If you can tell me where that code is, I'll delete it and see if that fixes the issue. 
thanks

**Comment by shawnaleahsunshine** [comment]
I figure it out. It was in the head of my documents. thanks for your assistance xo
