### ISSUE TITLE
Huge volumes of queries: /wp-json/wc/v2/orders/network

### ISSUE THREAD

**Issue by shanemarsh28** [woocommerce/woocommerce#20495]
I am seeing a rather alarming number of database queries upon logging into a blog where Woo commerce is activated. 

Upon login, our databases are getting pummled with requests that look like this:

`GET /wp-json/wc/v2/orders/network?_wpnonce=9f942d0321&network_orders=true&blog_id=16 HTTP/1.1" 200 577`

Our blogs are within a multisite setup and it this appears to be looping through all blogs that have woo commerce activated. This is more that 160 sites!!

As this loops through, it creates a new database connection each time. At it's peak, this is almost exceeding the 180 DB connection limit that our two backend servers allow combined. This momentarily brings our system to a crawl while the backlog clears. Our servers Load average also increase to an unacceptable level.

![image](https://user-images.githubusercontent.com/16979556/41286472-87526eaa-6e37-11e8-92a3-e9ced8d380c4.png)

This is a screenshot from our access log:
![image](https://user-images.githubusercontent.com/16979556/41286659-22c47a7c-6e38-11e8-95c5-fb71bcbb3191.png)

I do not see why Woo Commerce needs to loop this for each site and I would like you to change the behaviour so that Woo Commerce only pulls in JSON queries for the blog in question - not all of them that are activated within a given multisite setup. 

**Steps to reproduce:**
Login to any site that has Woo Commerce Activated. 

**Environment**
Server: Ubuntu 16.04
PHP: 7.2
MySQL: RDS (Master & Slave)
Woo Commerce Version: 3.4.2
Wordpress Version: 4.9.6–en_GB

**Comment by shanemarsh28** [comment]
OK our technical team has put it's heads together and we believe we have found the root cause. 

In the file **/woocommerce/includes/admin/class-wc-admin-dashboard.php** it generates a widget that pulls in all the orders from all blogs that a given user has access to. For me, this is pulling data from hundreds of sites containing thousands of orders. Our systems are simply not setup to deal with such a large amount of data in one go. 

So I have commented out line 56 in class-wc-admin-dashboard.php and disabled the widget entirely. This appears to have stabilised our systems. 

We do not want or require this widget. Please can you add an option to disable it more elegantly.

**Comment by mikejolley** [comment]
You can do this; the widget (WooCommerce network orders) can be disabled in screen options:

![dashboard wordpress wordpress 2018-06-12 12-52-06](https://user-images.githubusercontent.com/90977/41288801-79d297fc-6e3f-11e8-800c-7fb8e0e13caf.png)

This will disable it and disable the functionality to gather your orders across stores you own/manage.

Thanks

p.s. cc @claudiulodro If this receives other similar reports we should consider limiting the number of blogs accessed in this way, cap it somehow, or paginate.

**Comment by shanemarsh28** [comment]
Hi Mike, thanks for your reply.

I was hoping for something I could add into a functions.php file. I don't want to be constantly  responding to server alarms and then reminding users to set their screen options.

**Comment by mikejolley** [comment]
@shanemarsh28 All users are admin of all blogs on the network? This only pulls in the blogs/stores you admin.

https://codex.wordpress.org/Dashboard_Widgets_API#Advanced:_Removing_Dashboard_Widgets

**Comment by shanemarsh28** [comment]
No, most of our users are administrators of their own sites only but there are several network administrators and these people are added to every site on the system. Our client managers are not network admins but are members of all the sites they manage - which is quite a large number. 

Thanks for sending your removing dashboards widget link but sadly can't identify the correct classes and each time I test, the server load average goes over 15 and the database falls over! This is a very annoying issue.

**Comment by shanemarsh28** [comment]
Ok we've cracked it. 

This added to functions.php removes the widget entirely. 

`function remove_woocommerce_network_metabox(){
	remove_meta_box( 'woocommerce_network_orders', 'dashboard', 'normal' );
}
add_action( 'do_meta_boxes', 'remove_woocommerce_network_metabox' );`

Issue resolved :)

**Comment by cabgfx** [comment]
We've been experiencing the same issue, but did not have luck in using the snippet above from @shanemarsh28, nor the variation proposed by @JulienMelissas in #20891 ([link](https://github.com/woocommerce/woocommerce/issues/20891#issuecomment-409040319))

[Turns out](https://wordpress.org/support/topic/how-can-i-remove-the-network-orders-widget/#post-10687086), we had to use `dashboard-network` as the second parameter, for it to go away completely:

```php
function remove_woocommerce_network_metabox(){
  remove_meta_box( 'woocommerce_network_orders', 'dashboard-network', 'normal' );
}
add_action( 'admin_init', 'remove_woocommerce_network_metabox' );
```

(note, I've opted to use the hook `admin_init`, [as suggested in the Codex](https://codex.wordpress.org/Dashboard_Widgets_API#Advanced:_Removing_Dashboard_Widgets), but `do_meta_boxes` works as well.)

**Comment by cabgfx** [comment]
> [Turns out](https://wordpress.org/support/topic/how-can-i-remove-the-network-orders-widget/#post-10687086), we had to use `dashboard-network` as the second parameter, for it to go away completely:

Actually, if it helps anyone else, we ended up having to do it twice; one for `dashboard-network`, and one for `dashboard`.

**Comment by ablears** [comment]
I just experienced this. I noticed 100% CPU load caused by MySQL for about 10 seconds after an admin dashboard page load. Looking at the Network -> XHR tab in dev tools showed a request being made to each Woo site on the network. This is over 100 sites! 

I tried doing as @mikejolley suggested and removing the widget via Screen Options but this did not stop the requests. Doing what @cabgfx suggested did work.

Woo team - please remove or limit this widget.

**Comment by jasonpierson** [comment]
I had the same problem, but the actions did not stop the queries from being ran. I think those actions load after the plugins load; at least according to this: https://wordpress.stackexchange.com/questions/26537/between-functions-php-widgets-and-plugins-which-is-loaded-first

So I had to go into wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php and comment out the contents of the init() function.

**Comment by ablears** [comment]
I found the fix here stopped working recently. I had to move the code from a plugin into the parent's theme in order for it to work. 

This is an especially hideous widget because the massive CPU/memory usage happens even when the widget is not selected in Screen Options. If nothing else, that behaviour needs to be fixed.

**Comment by cabgfx** [comment]
@ablears:

> the massive CPU/memory usage happens even when the widget is not selected in Screen Options. If nothing else, that behaviour needs to be fixed.

+1 !
