### ISSUE TITLE
Multiple coupon order issue

### ISSUE THREAD

**Issue by dhmusman** [woocommerce/woocommerce#20584]
I have two coupons one in percentage and second is fixed amount.
In WC version 3.1 or older version it work like that,
First applied fixed price coupon and then percentage coupon for example
Total Amount = $100
Coupon1 = $10
Coupon2 = %10

$100 – $10 = $90
$90 – ($90 % 10 ) = $81

But in latest WC version its working like that

$100 – ( $100 % 10 ) = $90
$90 – $10 = 80

**Comment by mikejolley** [comment]
The old behaviour led to bugs if multiple coupons of the same type were applied, depending on the order they were applied.

e.g. apply coupon 2 before coupon 1 differs from applying coupon 1 then coupon 2. This is now fixed; the coupons apply percent first then fixed. This is the expected behaviour.

cc @claudiulodro 

Thanks
