### ISSUE TITLE
Use Select2 for Product Categories widget

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#20603]
The Product Categories widget doesn't use Select2 while other core widget dropdowns do.  

![http://cld.wthms.co/AYMmvM](http://cld.wthms.co/AYMmvM+)
Full Image: http://cld.wthms.co/AYMmvM+

**Comment by claudiosanches** [comment]
@mikejolley @jameskoster @claudiulodro We used to avoid Select2 in the front end, should we start implementing it now in places like this?

**Comment by claudiulodro** [comment]
@claudiosanches I think we can definitely move widgets to select2 when possible. We are already using select2 in some widgets and for all the checkout/cart select menus, so it's definitely on the frontend.

**Comment by kloon** [comment]
I think the reason we never added it to this specific widget was due to the fact that the widget could be used on just about any page on the site, what this means is now all of a sudden we need to load SelectWoo and Select2 on all page loads which can add some extra loading time, where it currently just loads on cart, checkout and account pages.

**Comment by mikejolley** [comment]
@kloon It does, but only when the widget is used right?

Dropdown is also no mandatory fwiw.

**Comment by kloon** [comment]
I was looking at the code that adds it to the frontend, however, I just checked now and layered nav also uses it and it gets loaded only when the widget is used, so we can go that route then.
