### ISSUE TITLE
WooCommerce plugin self deleted when updating to 3.4.3

### ISSUE THREAD

**Issue by blue928** [woocommerce/woocommerce#20620]
I'm researching an issue that occurred when updating from 3.4.2 to 3.4.3.

Was the file 'class-wc-rest-setting-options-controller.php' altered in these updates recently?

Background:
We run a multisite network on an Ubuntu 17.10 LAMP stack, and we use wp-cli to manage updates. 

What happened: 
For months we've had no problem with plugin updates. All of our files are owned by www-data and have permissions 644. We updated Woocommerce to 3.4.2 on June 5th. We have never had a problem with file permissions up to this point.

But, you can see in the image, on line 8, the above mentioned file was altered on June 6 and had ownership of tbadmin:tbadmin. This is indeed my login, but the 'last' command shows only access from my IP address on June 6 (So, no one logged in as me and altered the file, is what I'm saying.)

As you can also see in the image, after I changed ownerships, the plugin updated, but then during the update it self deleted.

Do you guys have any idea how this could have happened? I have very limited knowledge of security, but I wanted to report to both understand better and bring awareness to a possible security issue. If no one ever logged in as me, couldn't that mean there is a vulnerability in the file that could have been accessed remotely?

This is on a development server, thankfully, but it mirrors the exact security config of the production server. It's interesting to note that the files are exactly the same file size 17644 on both servers. I can't access the deleted file, but I would have assumed if that file had been altered, it would not have been the exact same file size. Production is up to date, and that same file has the correct ownership.

There is one other interesting thing to report, whether or not it's related, I have no idea.  When we updated to 3.4.3 on production server, we logged in an noticed that the WooCommerce plugin had been deactivated. But, people could still access the shop and everything seemed to be working properly. We reactivated it and haven't noticed any problems, but we thought that was very out of place.

In any case, any insight is appreciated.

![screen shot 2018-06-25 at 9 25 33 am](https://user-images.githubusercontent.com/6431043/41855704-4bd2b86a-7861-11e8-9bfa-c3b869ff2e1a.png)

**Comment by vlaskiz** [comment]
This is how WordPress updates plugins.
Deactivates -> Deletes ->downloads fresh updated copy of a plugin in a place of it.

If you had issues with your FTP permissions, it might be just that.

Just my first thoughts, devs might tell more.

**Comment by blue928** [comment]
@vlaskiz Right, I thought that was the process by which the update process happens. But even though that is the process, you can see that, at least from what WP-CLI says, the whole download, delete and reinstall process to be handled successfully.  What's really odd is that when the getcwd() failed, it said that "this isn't a wordpress install." I thought my entire website had been deleted as a result of this. But that wasn't the case, so I don't understand why WP-CLI couldn't detect that it was still in a wordpress install. Only the WooCommerce directory proper was emptied.

 Related to FTP, we actually don't allow FTP on the server and everything is done through ssh. How the permissions of that file got changed the next day is still a mystery for us, and it was only that file.

UPDATE:
I did want to convey more of the story as something else strange happened, but this may be by design.

I went back to the website and noticed that woocommerce was still working, but there was an "Update database" button in the admin screen. I clicked that, and everything seemed to update correctly. I went back to the command line and woocommerce files were there again.

This made me feel like there is something in the WooCommerce update procedure that doesn't allow WP-CLI to work properly with it? Could that be the case here that requiring that db update or visiting the website finally triggered the rest of the update sequence that finally copied the files into the directory? In other words, could there be something here that doesn't allow the plugin to be updated via WP-CLI? Still doesn't explain the file per mission change, but maybe that's a separate issue.

**Comment by rodrigoprimo** [comment]
Thanks for opening this issue to share what you experienced so that we can take a look a make sure it is not a WooCommerce problem.

> Was the file 'class-wc-rest-setting-options-controller.php' altered in these updates recently?

Last change to this file was shipped in 3.4.0. In case it helps, you can see the full history in this link: https://github.com/woocommerce/woocommerce/commits/master/includes/api/class-wc-rest-setting-options-controller.php

> As you can also see in the image, after I changed ownerships, the plugin updated, but then during the update it self deleted.

I haven't tested but I have a theory that could explain the problem that you are experiencing. As @vlaskiz mentioned, WP will first delete the plugin directory and then download and install the new version. You are running the WP-CLI command from the WooCommerce directory, the problem is probably that this directory is deleted during the update routine. When the process finishes, the bash will remain in the now deleted directory and that is why `ls` doesn`t return anything and WP-CLI is not able to the WP install.

To workaround this problem, you should run WP-CLI from the root WP directory (or any other directory that is not one of the plugin directories that will be deleted). Not sure if it is worth reporting this to WP-CLI developers, maybe WP-CLI should fail if you try to update a plugin running the command from its own directory to avoid this confusion? I'm not sure.

> Do you guys have any idea how this could have happened? I have very limited knowledge of security, but I wanted to report to both understand better and bring awareness to a possible security issue. If no one ever logged in as me, couldn't that mean there is a vulnerability in the file that could have been accessed remotely?

From what you reported, it doesn't seem like there is a security vulnerability in the file that you mentioned. But I don't have an explanation to what could have cause the change in ownership. It is not possible to know it without knowing your server configuration and, unfortunately, this is outside of the scope of this channel.

> I went back to the website and noticed that woocommerce was still working, but there was an "Update database" button in the admin screen. I clicked that, and everything seemed to update correctly. I went back to the command line and woocommerce files were there again.
> This made me feel like there is something in the WooCommerce update procedure that doesn't allow WP-CLI to work properly with it?

All plugins updates are handled by WordPress/WP-CLI and WooCommerce should update fine via the command line. The WooCommerce database update is separate from the plugin code update by design. Probably what happened when you went back is that you entered in the new plugin directory, whle before your shell was still in the old directory that was deleted.

I hope that the above helps. Closing this issue as, as far as I can tell, WooCommerce is not the culprit of the problems described.
