### ISSUE TITLE
Default variations are missing after update

### ISSUE THREAD

**Issue by codehouseno** [woocommerce/woocommerce#20651]
When updating WooCommerce from v3.4.0 to any of the more recent versions, all the default variations seems to be missing.

1. Start up with a WC 3.4.0 store with variable products and default variations set
2. Update WooCommerce to newest version
3. Go to product page and see that no default variation is selected anymore

**WordPress Environment**
WP 4.9.6

**Comment by mikejolley** [comment]
You've not provided the details requested on https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md nor stated you've gone through prerequisite steps. 

Your steps do not apply for me. This I what I tried.

1. Switched to 3.3
2. Saved variable product with default variation values
3. Updated to master (and 3.4 just in case)
4. Viewed product. Values are selected.

Therefore I'm unable to replicate the issue you're reporting. Go through the issue report again, rule out conflicts, _provide more details_ e.g. link to affected product. Otherwise you can post on the helpdesk if you want to give support staff access to look for themselves.

Thanks
