### ISSUE TITLE
Unable to update the Price used BULK Edit

### ISSUE THREAD

**Issue by klo5678** [woocommerce/woocommerce#20653]
Unable to update the Price used BULK Edit... 

Did anyone can fix?

**Comment by claudiulodro** [comment]
Hi there.

I wasn't able to reproduce this issue. Bulk editing the price worked correctly in my testing. One thing you may want to check is that you are not editing the price on a variable or grouped product, as that won't do anything.

Since there is no further information I cannot really investigate it any further. I recommend the [troubleshooting guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to better pinpoint your issue. Thanks.

**Comment by claudiulodro** [comment]
Hi Kelly,

Bulk edit won't work on variable products, as there could be many variations with different prices for the product. If you don't have a lot of variable products there is the "Set regular prices" feature for updating all of the variation prices for one product at one time:

<img width="860" alt="screen shot 2018-06-29 at 7 28 45 am" src="https://user-images.githubusercontent.com/7317227/42098014-87cec1f0-7b6e-11e8-8175-c37cfcc136d3.png">

If you do have a lot of products and are looking for an easy way to update the prices, the CSV importer is a good way to do it. First export a CSV of your products with the ID and price columns (and any other columns you want):

<img width="694" alt="screen shot 2018-06-29 at 7 31 07 am" src="https://user-images.githubusercontent.com/7317227/42098007-80ff7446-7b6e-11e8-88de-2eaa8a217db0.png">

Once you have that CSV file you can just update the prices in the file whenever you need to update prices and import the CSV file to apply the changes.

Thanks.
