### ISSUE TITLE
Setup wizard: Skips "Activate" and "Ready!" step

### ISSUE THREAD

**Issue by kellychoffman** [woocommerce/woocommerce#20671]
**Describe the bug**
When going through the setup wizard for the first time, the last 2 steps are skipped. 

**To Reproduce**
1. Install WC on a fresh WP install
2. Activate and run through setup wizard. Choose a US location and keep the default payments and shipping options.
3. On the "Recommended" screen, click "Next"
4. Instead of the next screen, you are brought to the WP dashboard instead. 

**Expected behavior**
It should bring you to "Activate" screen next and not close out the wizard. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WC version 3.4.3

**Comment by peterfabian** [comment]
I just tried this locally with PHP 5 (installed via Local) as I thought it might be caused by a red MailChimp notice urging to upgrade to PHP 7, but no luck. So far I could only replicate on poopy.life. Also at pressable or locally in VVV I had no luck to replicate this.

**Comment by LevinMedia** [comment]
I initially encountered this bug last Friday using Poopy.life - I just encountered it again using a scriptalious install of WP v4.9.6 on my own server. I was logged out of WordPress.com this time around. 

Running WC version 3.4.3 and PHP 5.6.36. mySQL was flagged in status because it is version 5.5.59

**Comment by peterfabian** [comment]
I was intrigued by this a bit, so by poking around, I found the culprit is probably the activation of MailChimp plugin. When that step is skipped, the wizard continues without problems. Not sure how to work around this problem as the code is already wrapped in `try` .. `catch` block.

Side note: I originally thought that the problem might be related to [use of `$wpdb->prepare` without any parameter during the activation](https://plugins.trac.wordpress.org/browser/mailchimp-for-woocommerce/trunk/bootstrap.php#L643) which calls `_doing_it_wrong` from WP core. 
However, removing `wpdb->prepare` from MailChimp's code does not seem to help with the fact that the wizard stops mid way.

**Comment by peterfabian** [comment]
It was caused by MailChimp plugin forcing the redirect during its activation. Proposed fix in #20879.
