### ISSUE TITLE
Bulk edit - sale price

### ISSUE THREAD

**Issue by fistukidz** [woocommerce/woocommerce#20675]
I try to bulk edit few products and change sale price,
I choose 
Set to regular price decreased by (fixed amount or percentage %)
Then I type in: 20%
Press apply. 

If I do that for 2-3 products it’s loading like it’s done but nothing changes. 
If I do that to more then 20 products it loads for few minutes and then crushes. 

The products I want to change have different regular price which I want to apply to them a sale price of 20%.

How can I overcome this issue and apply sale on multiple products. 

Thanks.

**Comment by peterfabian** [comment]
Hi, 

Are you trying to change the price of variable products?

Just tested it and bulk price update seems to work for _simple_ and _external_ products from Admin interface > All Products, but **not** for variable products.

For _variable products_, you need to open the actual product, go to variations section and edit the price from bulk actions for variations. 

It seems that this was implemented in this way by design, but I'm not familiar with the exact reason behind this. @claudiosanches / @claudiulodro maybe you guys have an idea? Was it performance or something else?

**Comment by fistukidz** [comment]
hello. 
yes I'm trying to create sale price for variation products. thats a shame we need to open each product. 
we have many products that we want to start their sale together. 

so for the moment i use a plugin for that. 
thanks, anyway.

**Comment by claudiulodro** [comment]
For variable products it doesn't make sense to have the bulk edit change the price of all the variations, as a product's variations generally have a range of different prices. [Here's a flexible way to do it if you need to regularly update variation prices](https://github.com/woocommerce/woocommerce/issues/20653#issuecomment-401373380)

**Comment by fistukidz** [comment]
But we want to make a sale which is 20% on all variations. Why it doesn’t make sense?
If you work with percentage then the different prices doesn’t metter.
