### ISSUE TITLE
Sale date always in GMT

### ISSUE THREAD

**Issue by wongkediri** [woocommerce/woocommerce#20680]
We have woocommerce setup using local date,
and we found that product in sale, not using wordpress local date

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1470

```php
public function is_on_sale( $context = 'view' ) {
		if ( '' !== (string) $this->get_sale_price( $context ) && $this->get_regular_price( $context ) > $this->get_sale_price( $context ) ) {
			$on_sale = true;
			if ( $this->get_date_on_sale_from( $context ) && $this->get_date_on_sale_from( $context )->getTimestamp() > current_time( 'timestamp', true ) ) {
				$on_sale = false;
			}
			if ( $this->get_date_on_sale_to( $context ) && $this->get_date_on_sale_to( $context )->getTimestamp() < current_time( 'timestamp', true ) ) {
				$on_sale = false;
			}
		} else {
			$on_sale = false;
		}
		return 'view' === $context ? apply_filters( 'woocommerce_product_is_on_sale', $on_sale, $this ) : $on_sale;
}
```

when checking is_on_sale() function forced using GMT, 
`current_time('timestamp', true);`
https://codex.wordpress.org/current_time

Is there a way to use localtime/wordpress datetime setting, for product in sales?

Thank you

**Comment by claudiulodro** [comment]
Hi there.

The date is saved in UTC time so that the saved sales time is not broken when a user changes the site's time zone. 

If you are trying to programmatically set a sale time in the site time you can do this by following the explanation in [`set_date_on_sale_from`](https://github.com/woocommerce/woocommerce/blob/2a3cedddcd2554dc28b6592d4c07abf9275829f1/includes/abstracts/abstract-wc-product.php#L842). That method can take a date in UTC or site time and automatically converts it to the correct format for storage.

Thanks.

**Comment by wongkediri** [comment]
@claudiulodro thanks for the explanation,
the problem actually is the product on sale always start at UTC, 
we set on wordpress local setting as utc+10.
so on local time, product on sale, show as sale at 10 am.

is there any tips for achieving this we want sale start at local time.
