### ISSUE TITLE
Problema with Stock using Variations

### ISSUE THREAD

**Issue by alissoncs** [woocommerce/woocommerce#20735]
I am using a theme called Storefront to my ecommerce website, wordpress and woocommerce.
The problem is when I create a product and apply some **variations**, it works fully, but after I edit that product, or someone buy the product, the stock in the front website is assigned as **"has no stock."**. 
In the wordpress product edit page, the stock is properly assigned.

Looks like the variation stock is updated by witchery... or cache, or a bug with these both stock variable references.

PHP 7.1
Apache 2.4
Mysql 5.5
Wordpress version: 4.9.5
Woocommerce: 3.2.5
(I was using 4.9.7 and Woocommerce as 3.4, but both have the same problems.

**Comment by claudiulodro** [comment]
Hi there,

Did you roll back the version of WooCommerce on your site from 3.4 to 3.2? WC 3.3 introduced [automated stock status management](https://woocommerce.wordpress.com/2017/12/06/wc-3-3-product-backorders-and-stock-management-improvements/), so if you went from a version >3.3 to a version <3.3 you may have to go in and check the product settings and maybe re-save the product.

My recommendation is to update to the very latest version 3.4.3 as there [was a bug fixed with the automatic variation stock management](https://github.com/woocommerce/woocommerce/blob/release/3.4/readme.txt#L191), check the product settings to make sure everything looks good, and re-save the product.

I wasn't able to reproduce the issue on a site with only WooCommerce and Storefront, so I'm closing this issue as non-reproducible. If 3.4.3 doesn't solve the issue, please post some screenshots of your variation settings so I can try and reproduce the issue better.

Thanks.
