### ISSUE TITLE
Product titles

### ISSUE THREAD

**Issue by ofirk12** [woocommerce/woocommerce#20734]
Hey, In page that show all the product i saw that the titles was cut i understand  that function woocommerce_template_loop_product_title make the title, in the page i saw that there is h3 tag and in this function there is h2 tag also i tried to change alot  location to find the source of the title to understand why is cutting the words in the title. i tried also to do function in the function file but nothing work.. i have woocommerce 3.3.3

Thanks for help

**Comment by claudiulodro** [comment]
Hi there.

I'm not sure exactly what the problem you are describing is or how to reproduce it since you haven't filled out the issue template or given much info about it.

If you are describing a bug in the WooCommerce plugin please [open a new issue](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md) and fill out all of the information that is requested when opening a new issue.

If you are describing something you need support or help with, please ask [on the support forums](https://wordpress.org/support/plugin/woocommerce), as we can't do that sort of support on GitHub.

Thanks.
