### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by reezalaq** [woocommerce/woocommerce#20805]
##test2.py##

from woocommerce import API
import json

wcapi = API(
url='https://gmoiltraders.com/',
consumer_key='ck_***',
consumer_secret='cs_***',
wp_api=True,
version="wc/v2",
timeout=15
)

wcapi.get("products/categories").json()

##error##
Traceback (most recent call last):
  File "/Users/reezalaq/PycharmProjects/project/__not-used__/test2.py", line 13, in <module>
    wcapi.get("products/categories").json()
  File "/Users/reezalaq/PycharmProjects/project/venv/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/reezalaq/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/reezalaq/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/reezalaq/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
@reezalaq just to get a better understanding as the issue lacks some information. Do you have any categories defined in the site? If you have, mind sharing what the categories are?

**Comment by peterfabian** [comment]
Hi, 

First, I would urge you to invalidate the customer key & secret included in this issue, as it could allow people to access your server in ways you would not like them to.

Second, I'm not sure you configured your WordPress installation correctly/to use with REST API. You can check this easily by going to `https://gmoiltraders.com/wp-json/` and see if you get a valid JSON response. In your case, it returns Object not found, so it might be caused by a lot of different problems--from web server misconfiguration to problems with WordPress or plugins you run. 

I'm not even sure you are running WordPress and WooCommerce on the site you linked. 

If you believe this is a bug, we would need steps to reproduce this on a vanilla WooCommerce installation. 

Otherwise, if you need support, please reach out to [WooCommerce support page](https://woocommerce.com/contact-us/) or submit your question to the [user forums](https://wordpress.org/support/plugin/woocommerce).

**Comment by DeanForde** [comment]
I have the same issue using the storefront theme, all other requests work fine except for wcapi.get("products/categories").json() or wcapi.get("products/categories/{id}").json()

**Comment by tomjn** [comment]
@peterfabian please **do not send people to WP Stack Exchange for help with WooCommerce**, WooCommerce questions are off-topic and will be closed. They and other 3rd party plugin dev support questions are off topic there.

_Note that I am a WP Stack exchange community moderator_

**Comment by peterfabian** [comment]
Thanks for reaching out @tomjn. Apologies, I wasn't aware of the rules. Edited the response.
