### ISSUE TITLE
Downloadable product file field cannot handle relative paths when wp-content dir is not in ABSPATH

### ISSUE THREAD

**Issue by PaulineL** [woocommerce/woocommerce#20820]
**Issue**
In our environment, ABSPATH only contains the WordPress Core and wp-content dir is in an other location defined in WP_CONTENT_DIR. (WordPress Core provides this built in solution).
In this configuration, if the URL for a downloadable file is a relative path, then you get a "The downloadable file cannot be used as it does not exist on the server" error.
According to the code, there is a solution for relative path, but this doesn't work in our case because, at this line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-download.php#L108, it is expected to get the wp-content directory according to ABSPATH. It can't work because WP_CONTENT_DIR doesn't exactly contains ABSPATH.

**To Reproduce**
1. Have wp-content and wordpress core in separate locations (https://codex.wordpress.org/Editing_wp-config.php#Moving_wp-content_folder).
2. Create a "virtual" and "downloadable" product
3. In the download section, click "Add file"
4. Add a file to the product using the "Choose file" button
5. In our case, the path is relative. Otherwise, remove the "https://domain" part
6. Save/update the product
7. You'll see the "The downloadable file cannot ..." error message

**Expected behavior**
We would expect a way to check the wp-content folder without necessarily using ABSPATH, in order to validate that the file exists. 

**WordPress Environment**
We use Wordpress version 4.9.7 and Woocommerce version 3.4.3.

**Comment by kloon** [comment]
The reason ABSPATH is part of the check is a security one. If we do not check that the file is part of the ABSPATH you can basically put a location to any file on the server in the download box and have someone download that file.

If you look at the examples of moving the folders you will see they always reference the ABSPATH in those, using dirname(__FILE__). Also since see the uploads section since uploads is part of WP_CONTENT see this reference `It is always relative to ABSPATH`

I have not personally tested it but are you sure your site is functioning correctly if you set the WP_CONTENT folder to somewhere that is not relative to the ABSPATH? Seeing as the path needs to be accessible via a URL I would suspect it needs to be relative to the ABSPATH in order to also be under the same URL?

**Comment by PaulineL** [comment]
Thank you for your answer.
We use bedrock as folder structure https://roots.io/bedrock/, which works good.
According to the bedrock's structure, ABSPATH would be /web/wp and WP_CONTENT_DIR would be /web/app

**Comment by kloon** [comment]
OK, personally I do not think this is something we would change, that said there is a filter available which you can use to let this go through, woocommerce_downloadable_file_exists

Something along the line of this would work, which makes sure the file is part of the path you are allowed to access. You might need to tweak the path to suit your needs

```
add_filter( 'woocommerce_downloadable_file_exists', 'bedrock_allow_download_outside_abspath', 10, 2 );
function bedrock_allow_download_outside_abspath( $exists, $file_url ) {
    if ( 0 <= strpos( $file_url, '/web/app' ) ) {
        return file_exists( $file_url );
    }
    return $exists;
}
```
