### ISSUE TITLE
iOS 11.4, safari not able to log in - only chrome

### ISSUE THREAD

**Issue by smwilson31** [woocommerce/woocommerce#20825]
**BUG ISSUE**
Customer is having issues logging in on phone when using Safari, Safari version unknown but IOS is 11.4. When logging in via Safari user get redirected back to log in screen and cannot make the log in.

Customer has:
- Cleared Cache
- Rebooted phone
- Using a bookmark from mobile desktop
- Works fine on chrome

Waiting to test to see if bookmark link is broken, but problem seems to have occurred since update

**Comment by peterfabian** [comment]
Hi, 

sorry, I was not able to replicate this issue on WooCommerce 3.4.3 using Safari with iOS 11.4.1 on iPhone 5S. Safari version comes with the iOS, so it should be the same for the same iOS version. 

Most likely it is caused by something else, hard to say what exactly, as not too much info has beed provided. 

Please try to rule out potential theme and plugin conflict and provide a system report, both are described in the [Self-service guide for WooCommerce](https://docs.woocommerce.com/document/woocommerce-self-service-guide/).

**Comment by smwilson31** [comment]
Sorry I believe I submitted this to the wrong github
