### ISSUE TITLE
WooCommerce Shipment-Tracking "No Route Found"

### ISSUE THREAD

**Issue by thedonmon** [woocommerce/woocommerce#20918]
Hello,

Looks like we are having issues with a few clients who are using the Shipment-Tracking plugin. The client has activated the plugin and sees the box on the Woocommerce backend to enter tracking information. However, when we try and post tracking information via the API, we get `No route was found matching the url and request method.` I have been noticing this for a lot of clients and am running out of recommendations for them to try and get these endpoints added to their Rest Client. 

Does anyone have any suggestions on how to proceed?  We are using Basic Auth to authenticate.

**Comment by peterfabian** [comment]
Hi, 

I'm not sure if this is an error with the Shipment-Tracking plugin or our REST API, but if you think it's a problem with REST API, please provide information on how to reproduce this issue on a site running latest WooCommerce version without any other plugins active, i.e. which endpoint you are sending requests to, what data is sent if it's a POST/PUT request or query parameters in case this is a GET request, etc.

Thanks.

**Comment by claudiulodro** [comment]
Hi there,

Looking at the error message you are getting I would double-check and make sure your API requests are structured correctly and pointed to the correct endpoints. That error happens when the server doesn't recognize the API endpoint you are trying to hit.

We can only investigate bugs in the core WooCommerce plugin on GitHub and not on associated plugins, so you will have to contact the plugin author/support for further investigation.

There are a few Shipment Tracking plugins for WooCommerce. If you are using [the official WooCommerce Shipment Tracking plugin](https://woocommerce.com/products/shipment-tracking/) please [open a support ticket](https://woocommerce.com/my-account/create-a-ticket/) and someone will help out.

If you are using a third-party shipment tracking plugin you will have to contact the author of the plugin to investigate your issues.

Hope this helps. Thanks.
