### ISSUE TITLE
Wrong dependencies for wc-add-to-cart

### ISSUE THREAD

**Issue by nyordanov** [woocommerce/woocommerce#21000]
`wc-add-to-cart` uses jQuery BlockUI (see https://github.com/woocommerce/woocommerce/blob/3.4.4/assets/js/frontend/add-to-cart.js#L77) but it is not listed in its dependencies: https://github.com/woocommerce/woocommerce/blob/3.4.4/includes/class-wc-frontend-scripts.php#L257

Ideally, given that #18395 is now closed, please reconsider merging #18299 which removes jQuery BlockUI entirely from the front end, which has the added benefit of saving about 10kB of JavaScript. [Current best practices recommend limiting JS to 150kB.](https://infrequently.org/2017/10/can-you-afford-it-real-world-web-performance-budgets/)

If you see any reason not to do this, then please add `jquery-blockui` to `wc-add-to-cart`'s dependencies.

**Comment by kloon** [comment]
@nyordanov although the block ui script should always load on the frontend due to the woocommerce script always being loaded, I have added the dependencies in #21007 just in case a theme or plugin dequeues the woocommerce script for some reason.

Merging #18299 is not an option as stated in the PR, it will be a big breaking change as some plugins/themes might rely on the CSS classes etc, the removal will form part of a bigger change where we completely remove jQuery which in itself will be a very big task that will be in a major release.
