### ISSUE TITLE
OBW: Fullscreen should always open upon installation + activation

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce#21017]
Sometimes, the OBW does not open fullscreen after installing WooCommerce. This bug is not 100% reproducible, but happens often enough.

Steps:
1. Start with a new WP installation
2. Install WC, activate WC
3. See that the fullscreen for the OBW does not open. Expected: the fullscreen to open upon installation & activation.

Came from @aleftick's walkthrough of WCS, and @dechov reports this happening sometimes.

**Comment by dechov** [comment]
Seems like it opens on poopy.life but doesn't on jurassic.ninja – http vs https is one difference, but there may well be more relevant differences.

**Comment by mikejolley** [comment]
Hey,

I span up a jurassic.ninja site and installed/activated WC and did see the redirect.

I span up a second jurassic.ninja site with WC pre-installed. This did not redirect. This also did not redirect after deactivating and reactivating WC.

There are also some other cases where there is no redirect, like bulk activation of plugins.

It's possibly because the time you access admin the installer has ran and set the DB verison/version, in which case WC doesn't think it's a new install and skips the redirect.

I'll see if there is a better way such as setting an option once the wizard has been 'seen'.

When there is no redirect there is a banner/notice to run the wizard so it's not end of world.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22977
