### ISSUE TITLE
Cart Totals Not Adding Up 

### ISSUE THREAD

**Issue by tolentogroup** [woocommerce/woocommerce#21082]
Why is the line item price $0 and the total is $0 but below it adds up. I have deactivated all plugins and it still does it, I have added new products and it still does it, there is no applied css either. 

![screenshot 2018-08-16 at 7 01 39 pm](https://user-images.githubusercontent.com/42456780/44244059-e1c0d200-a186-11e8-8dfd-d9c080c4a37f.png)

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). If you believe you found a WooCommerce core bug, please provide all the details requested in the [bug template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md) so that we can try to reproduce the problem and investigate the issue.
