### ISSUE TITLE
Bacs pay in my-account

### ISSUE THREAD

**Issue by p3psic** [woocommerce/woocommerce#21163]
Hello.

When the customer changes the payment method to bacs in the my-account, the quantity of goods decreases. The bug is that the user can do this as many times and the goods will be reduced again.

**Comment by claudiulodro** [comment]
Hi there,

Can you describe the process in detail for reproducing this bug, as well as include the system status report? We need the information that is asked when you open a bug report in order to reproduce the problem so that it can be fixed if it is a bug.

It isn't possible in regular WooCommerce for a customer to just change their payment method after placing an order, so I'm not sure what you are describing.

I tried the following:
1. Create an order with "Pending Payment" status.
2. Email the invoice to the customer.
3. Use the payment link in the invoice and select "BACS" gateway
4. Try and use the payment link again to re-select "BACS" gateway. Encounter "This order’s status is “On hold”—it cannot be paid for." message and am unable to do what you describe.

Thanks.

**Comment by p3psic** [comment]
I use the theme Scalia. In woocommerce/myaccount/orders.php creates a payment link $order - >get_checkout_payment_url(). By clicking on it, you can change the payment method. How to detect an error:
1. Create an order with online payment, but do not pay. 
2. Go to myaccount.
3. An order that is pending payment has a pay button. It will take you to a page where you can change the payment method.

Here you can change the method of payment as much as you want, it is not always intentional, but for this reason there is a multiple write-off of goods. This can be seen in the order logs in the right column of the admin panel. If I understand correctly, this is due to the payment method bacs. Even if the payment method has been changed from bacs to bacs, the quantity of the goods will be reduced again.

**Comment by kloon** [comment]
The reason stock is reserved is because bacs is an offline payment method, if a customer selects this payment method then they are committing to pay you offline and stock needs to be reserved. There is no way for us to check if an offline payment has actually happened so it is up to the store manager to adjust the stock again if no payment was made when an offline payment method was used.

**Comment by p3psic** [comment]
>  When someone attempts to pay via an online payment method and abandon the payment the order is created as pending and the stock is reserved, then the customer can select bacs from my account and pay for that order and have it subtract the stock again?

Sometimes the user cannot pay and he changes the payment method to bacs in order to reserve the goods, but sometimes he sends several times a change to bacs, which repeatedly writes off the same goods. We often see a large number of goods after the inventory, which is not in stock. I began to suspect that this is due to this problem. Users send the bacs method several times and so write off the goods that they do not buy, and we do not know about it and goods just dusts on the shelves.

> Unpaid orders a have stock reserved, you can control how long the stock should be reserved for or you can disable stock reservation completely by changing the setting to a blank in WooCommerce -> Settings -> Products -> Inventory. 

Bacs payment method is configured correctly. The problem is not the time for the reserve, and that I clicked on the button "change pay method" 10 times and charged 10 cart.

**Comment by claudiulodro** [comment]
Once the user goes to the payment page and selects BACS, it should change the order status to on-hold status and prevent changing the payment method again.

<img width="683" alt="screen shot 2018-09-04 at 10 54 28 am" src="https://user-images.githubusercontent.com/7317227/45048559-14951200-b031-11e8-9678-64c85ce12652.png">

I can't reproduce what you are describing using a default WP theme, so it sounds like a bug in the theme you are using or a bug in a plugin you are using.
