### ISSUE TITLE
List all product attributes doesn't allow Pagination

### ISSUE THREAD

**Issue by revendo** [woocommerce/woocommerce#21187]
When making a GET Request at this Endpoint with these parameters, no pagination is applied. 

`wp-json/wc/v2/products/attributes?per_page=20&page=12`

**Comment by kloon** [comment]
As per the [docs](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-attributes) those parameters are not supported when listing products attributes.

Good news is we are busy working on the next version of the API which will be in the next release, just looping in @claudiosanches so we are aware of this and can see if we can implement something.

My guess is that it was left out due to the way custom attributes are stored on a product level, which complicates the pagination.

**Comment by claudiosanches** [comment]
This endpoint does not support pagination for now. We don't support pagination in all endpoints.
You check the collection params doing a `OPTIONS wp-json/wc/v2/products/attributes` request, you'll see that does not support `per_page` or `page`.
