### ISSUE TITLE
Price slider overlapping circles

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21237]
**Describe the bug**
1. The price range slider circles can overlap.
2. And when they are overlapping then it's possible to move price handles in only one direction (the one that you slid from last, e.g. if you made them overlap from the right side then now you can only move these handles to the right until you separate them, after which you can also move the left handle).

**To Reproduce**
1. Go to https://themes.woocommerce.com/storefront/product-category/clothing/
2. See error

**Expected behavior**
The slider must (obviously) work like this:
<img src="https://i.imgur.com/K750sg4.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Hi, 

it actually seems to me that the problem is not caused by overlapping of the circles, but that the right/max price handle can cross the left/min price handle and be positioned to the left of min price handle. What's more, only then the price of both are equal (at least that's how I see it behaving in Chrome, Firefox and Safari on MacOS). 

It might be worth it to rethink the slider interaction, as sliders are not really encouraged from the UX perspective as far as I know. 
@tiagonoronha  what is your view?

**Comment by tiagonoronha** [comment]
Sliders like this are quite tricky, specially when they rely so heavily styling from themes which can create a very inconsistent experience across stores.

I'd rather have this be two separate input text fields.

I'll have a look at the issue in Storefront.

**Comment by mikejolley** [comment]
For performance we'd replace the slider with terms (bands) which would allow a simple term based query on products. Until then, we should fix up the display of the handles.

**Comment by mikejolley** [comment]
After investigating it does not look like we can effectively control this with jQuery sliders. There is some hacky code floating around to swap the selected handle based on mouse direction but it breaks with every update reading the comments.

We'll need to leave this as-is and plan to replace jquery UI slider with bands or some other solution in the future.
