### ISSUE TITLE
Grouped Product "when I add just 1 product quantity, other products increase too" WHY?

### ISSUE THREAD

**Issue by klinklin** [woocommerce/woocommerce#21249]
I create groped product, and when i trying its not work. When i add quantity "Jog K.Tidur" from 0 to 1, "Jog K. Mandi" also increase from 0 to 1. That product linked increase and decrease, How to unlinked each product when I change the quantity?
![capture1](https://user-images.githubusercontent.com/42907703/44954538-73417b00-aecd-11e8-8e45-a3b1ea588a8e.JPG)

You can visit to trying my problem :( https://www.klinklin.co.id/product/jog-rumah-daily-cleaning/

**Comment by kloon** [comment]
This is likely your theme or another plugin you have installed. The default behavior in WooCommerce will not update all the quantities when you change one. I just tested this and can confirm it does not update so you definitely have a conflict somewhere.

I suggest you disable all plugins except WooCommerce and switch your theme to twenty seventeen or Storefront and test again. You can then enable the plugins one by one testing inbetween and eventually switching your theme back to find where the issue is introduced.
