### ISSUE TITLE
Order by do not works

### ISSUE THREAD

**Issue by rsandrade** [woocommerce/woocommerce#21254]
**Describe the bug**
The combo box for order products by any kind of filters are not working

**To Reproduce**
1. Go to http://www.flaneur.pt/home/
2. Use the combo box to change the order for another 
3. See error

**Comment by peterfabian** [comment]
Hi, 

I can't reproduce this problem on 3.4.5 stable or on master branch. Please follow the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to rule out problems caused by other plugins or themes. If you find out this is a problem with WooCommerce core (i.e. this still happens with only WooCommerce plugin active and Storefront theme), please create a new issue with steps to reproduce the problem and your [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).
