### ISSUE TITLE
Country field select box issue

### ISSUE THREAD

**Issue by luicephillips** [woocommerce/woocommerce#21262]
Hi,
I am having issue with Woo-commerce checkout page. When i open the any drop-down (like state, country etc) and select any country/state, there is a blank listing appear in iPad only.
Please check attached file more detail.
I am using below version of WordPress and Woo-commerce:
WordPress : 4.9.8
Woo-commerce : 3.4.5
![after-drop-down-selection](https://user-images.githubusercontent.com/19268452/44984863-f6310700-af9b-11e8-8e3c-14696f66aa04.jpg)

**Comment by kloon** [comment]
@luicephillips first of all you did not complete the issue template with all the questions not provided any details that was asked in there.

This issue is not present with just WooCommerce active and using a standard theme like Storefront or Twentyseventeen. Please tests by disabling all plugins except WooCommerce and switching your theme to a default one.
