### ISSUE TITLE
State / country doesn't update in checkout

### ISSUE THREAD

**Issue by zetaweb** [woocommerce/woocommerce#21287]
**Describe the bug**
In the checkout page of our client's site the state / country dropdown doesn't update after choosing a nation. So, If I initially have  Italy, the state / country will show italian provinces, but if I choose Greece it won't update the list with greek provinces, and it will keep showing the italian ones.

**To Reproduce**
1. Go to http://www.agriverde.it/checkout/. You'll have to put a product in the cart first.
2. Click on the nation dropdown field, just below the company name field, ad select different states
3. Scroll down to the state / country dropdown.
4. you'll see that the dropdown won't be updated.

I have woocommerce on other websites, so far as I know, the issue could be due to the theme.

**Expected behavior**
I'd like the state / countyr dropdown to update. But if there is a way to transform it from a dropdown to a free text input it would be allright too.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Hi, 

I could not reproduce this on the test sites I have access to--both stable 3.4.5 and latest master branch work fine. It seems to me that it's caused by a conflict introduced either by one of your plugins or the theme. I can see that your website includes both select2 and selectWoo js dropdown libraries, which might be causing the conflict you see. Please follow the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to find the plugin/theme conflict.

If you find out you can reproduce the problem using only WooCommerce with 2017 or Storefront theme, please post your system status report and we'll reopen the issue.
