### ISSUE TITLE
Woocomerce Blank Page after add to cart (Official Woocomerce demo)

### ISSUE THREAD

**Issue by Ulverist** [woocommerce/woocommerce#21289]
**Describe the bug**
I was testing the official Demo of Woocomerce Storefront , on many kind of sites that test the responsivness of a website like http://ami.responsivedesign.is/ , http://responsivedesignchecker.com/ etc.

What i found in woocomerce Unlike other cms is that , after cart page , if you go to checkout , you take a blank page . Yes is only to this sites showing up the problem , but just leting this here .

**To Reproduce**
1. Go to 'http://responsivedesignchecker.com/' or onother site like this 
2. Add link 'https://themes.woocommerce.com/storefront/ ' (official woocomerce demo)
3. Add a product to cart and after proceed to check out.
4. See error there , there is a blank page !

**Screenshots**

**Expected behavior**
To see the cart page 

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiulodro** [comment]
Hi there.

This isn't really an issue in WooCommerce. If you check the JS console when the error happens you will see `"Refused to display 'https://themes.woocommerce.com/storefront/checkout/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` This is because the checkout is set to not allow embedding in iframes (a reasonable security measure). Since those sites use iframes for testing the responsiveness, it will break there.

My recommendation is to use the built-in responsiveness testing features of Chrome or Firefox, as those will work on every site and don't require a third-party site.

Thanks.
