### ISSUE TITLE
Inputing variable product CSV Delimiters not working in Woo anymore

### ISSUE THREAD

**Issue by liquiddi** [woocommerce/woocommerce#21319]
**Describe the bug**
Any time I input in a CSV file and change the delimiters over to | woo commerce doesn't understand what they are anymore.  Worked last week.  Also if I just use , between values it still understands that but when it loads in the values it has them all together.  Example sizes 0,2,4,6,8 should go in as drop down attributes on their own but go in as all of that together??????  I've also tried imputing product with 3 different import tools with the same results. as you can see in the second screen shot wp all import doesn't understand | and has no drag in options.

**To Reproduce**
create a csv spread sheet and try to import variable products.

**Screenshots**
![error](https://user-images.githubusercontent.com/42848136/45361100-f5e5cc80-b596-11e8-9b02-af374930bed7.jpg)
![error2](https://user-images.githubusercontent.com/42848136/45361567-31cd6180-b598-11e8-9a6f-e7cb3c29e79e.jpg)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
@liquiddi your issue seems to be related to WP All Import and not the WooCommerce importer. The WooCommerce core importer can be found at WooCommerce -> Products and then clicking the Import button at the top of the page.

Just a note that WooCommerce core only supports CSV imports, but you can also import XML files through the WordPress core importer for products, the preferred method is using CSV though.

So my suggestion would be to either use the WooCommerce core CSV importer, or get in touch with the developers of WP All Import and have them look into the issue for you on their plugin.

**Comment by liquiddi** [comment]
I got it to work.  You just have to use "," for everything other then the attributes.  Those have to be separated with "|"
