### ISSUE TITLE
order editing issue

### ISSUE THREAD

**Issue by sanhet** [woocommerce/woocommerce#21369]
When editing a large order, (Eg: removing items not in stock, changing prices), on the edit order page, all the products after 100 cannot be edited. Lets say there is an order for 200 different products, when editing this order, all the product after the 100 mark cannot be deleted or have its price changed. Currently, to get around this, I sort the order reverse alphabetically so that the products at the bottom come to the top where I can edit them, 

**To Reproduce**
First place an order with over 100 different product.
1.Go to dashboard
2. Go to woocommerce and then orders
3. Click on order wanting to be edited
4. Try editing the last product, it should not edit

**Expected behavior

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Can you perhaps post your system status report? I suspect this is related to the maximum post vars limitation of your server.

Can you try the following solutions provided at the link https://docs.woocommerce.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/

What is happening is you are reaching your default server POST limitation, since you have orders with unusual large amounts of products this is very edge case and not something we will likely try and address in WooCommerce core hence why we have the document already with fixes you can implement on your sever.

Please let me know if this solves your issue, closing for now but will reopen if this is really a bug.
