### ISSUE TITLE
WooCommerce cookies causing PCI fail

### ISSUE THREAD

**Issue by woodsygrant** [woocommerce/woocommerce#21382]
Referred here from technical support.

**Is your feature request related to a problem? Please describe.**

WooCommerce client continues to fail a PCI compliance scan. The two failures noted are related to WooCommerce cookies, listed below with the accompanying message. How can we change these values?

woocommerce_items_in_cart
The website software on this server appears to be setting session cookies without the HttpOnly flag set. This means the session identifier information in these cookies is susceptible to attacks such as Cross-site Scripting which may allow attackers to read this cookie's data.

woocommerce_items_in_cart
The website software running on this server appears to be setting session cookies without the Secure flag set over HTTPS connections. This means the session identifier information in these cookies would be transmitted even over unencrypted HTTP connections, which might make them susceptible to interception and tampering.

**Describe the solution you'd like**

It would be great to be able to toggle these cookie values, or at least overwrite them easily.

**Describe alternatives you've considered**

Overwriting the cookie values in a theme file or custom plugin file would be great alternatives.

**Additional context**

**Comment by claudiosanches** [comment]
Both are false positives because all data from`woocommerce_items_in_cart` is used by WooCommerce using JavaScript, if changed to HttpOnly makes impossible to keep working our mini cart widget (even in themes that already have some mini cart).
Also mini cart is loaded in all front-end, even when not using HTTPS in all pages, that's why is not setting a Secure flag, still this is not sensitive data, only to display the mini cart, so as I said, all false positives.
