### ISSUE TITLE
Order.update webhook not fire

### ISSUE THREAD

**Issue by KingWu** [woocommerce/woocommerce#21464]
Wordpress version : 4.5.2
woocommerce version: 2.5.5

I create order.update, order.create and product.create webhook. I can get three first 'ping'. 
But, i try to create a new product and order. I cannot get webhook events.

Any idea to debug?

Thanks

**Comment by kloon** [comment]
Have you checked the logs? In wp-admin under WooCommerce -> Status -> Logs and then select the webhook delivery log file with the latest date, you will find details on the events that fired and the status of each event.

**Comment by KingWu** [comment]
Where is no logs for webhook delivery log? Does the server not have write permission?

**Comment by kloon** [comment]
@KingWu the logs can be found in WP-Admin under the menus WooCommerce -> Status -> Logs and then select the webhook delivery log file with the latest date.

Log files are written to the wc-logs folder in wp-content/uploads if you want to go and find them via FTP.

**Comment by claudiulodro** [comment]
WooCommerce 2.5.5 is super old and is not a supported version. If this is a valid bug in that version it would have been fixed in a more recent version. Additionally, many plugins and themes will likely not work on versions below 3.0 correctly. I recommend updating to a recent version of WooCommerce.
