### ISSUE TITLE
Item key of meta should not be translated

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#21474]
**Describe the bug**
When a package is passed to a shipping method, the method add_rate add a meta to the shipping rate listing the products in the package (which is great). Unfortunately, the line
$rate->add_meta_data( __( 'Items', 'woocommerce' ), implode( ', ', $items_in_package ) ); of the abstract shipping method adds a meta with a translated key and not something universal like 'items'.

Later on, when using get_formatted_meta_data() on a shipping item  (Class WC_Order_Item_Shipping), the array returned uses the translated key, which make a filtering of the array complicated and risky (if the translation would change, for example ). The key of the meta should be set to "items" and later on in get_formatted_meta_data() the display_key should be set to the translated string and the key itself should stay the same.

![meta](https://user-images.githubusercontent.com/25102786/46312967-ed494a80-c5c6-11e8-92c2-7fda2c2ec7e7.jpeg)

I would be happy to make a PR for this, but I'm not sure if my tactic of translating the 'items' meta key first in the get_formatted_meta_data function sticks to your strategy.

**Comment by mikejolley** [comment]
I think the intention of `Items` isn't something thats supposed to be parsed by a plugin/other code, but to be a line for reference for the shop owner. Thats why it's a translated string and not hidden meta data (not a bug, just how this particular data is being stored and presented).

Because we don't support translations of stored strings, the only way to make that translatable would be to add a special case/handling for 'items' in `get_formatted_meta_data`. I'm not sure we need that here (core doesn't) but if you had a use case for this, you could indeed open a PR with some explaination.

Thanks

**Comment by pierrebuet** [comment]
Hi and thank you so much to have taken the time to review my issue! I found in the meantime a different solution to filter the meta, so I don't need a tweak anymore to not save the translated value for "items".
