### ISSUE TITLE
Shop Manager account can't save embedded youtube videos in a post

### ISSUE THREAD

**Issue by oquirozm** [woocommerce/woocommerce#21522]
**Describe the bug**
So this is kind of weird. When using an account with the 'Shop Manager' role, if you create or edit a post and try to add a youtube embedded video in the post's content, once you publish or update the post the YouTube embedded link disappears. Only happens with 'Shop Manager' accounts, that's why I'm relating it to WooCommerce. Regular text updates on the post work fine.

**To Reproduce**
1. Install WooCommerce
2. Create a new account with a 'Shop Manager' role.
3. Create a new post from the user account with the 'Shop Manager' role.
4. Edit the post and in the content paste an 'embed video' link from any YouTube video you want.
5. Update the post and you will see how the embedded video link simply vanished.

**Expected behavior**
The post should save the embedded video.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 4.9.8
WooCommerce 3.4.5
PHP 7.2.9
MySQL 5.7.23

**Comment by claudiulodro** [comment]
Hi there,

This is because Shop Manager users don't have [`unfiltered_html`](https://codex.wordpress.org/Roles_and_Capabilities#unfiltered_html) capabilities, so those types of embeds will be stripped out for security. You should still be able to insert videos using [oEmbed or the embed shortcode](https://codex.wordpress.org/Embeds), or you can give shop managers `unfiltered_html` capabilities using one of the capability management plugins out there. Hope this clears things up.

Thanks.

**Comment by oquirozm** [comment]
@claudiosan oh, that makes sense. Thank you, I had no idea there was an embed shortcode around. That solves it.
