### ISSUE TITLE
Update a order changes time to time - 2hrs

### ISSUE THREAD

**Issue by hko01** [woocommerce/woocommerce#21535]
Hi, I use Woocommerce 3.4.6.

If i open an order and just click on Update the time (created date) is changed to shown time - 2hours.

So everytime i save the order after changing it, the time is desreasing.

Is there any help for me ?

**Comment by kloon** [comment]
@hko01 are you referring to the date listed when you edit the order in the admin area? What is your site timezone settings? From the looks of things the date shown on the edit order screen seems to be UTC, which is not the same as my timezone as well, just want to double check what your timezone settings on the site are, but this is a possible bug yea.

**Comment by hko01** [comment]
Yes. i open an order in the admin area, change the state and click on update. The time zone is Europe/Berlin. But it seems that the update process does not care about the time zone we use...

**Comment by kloon** [comment]
OK, so I did a bit of digging and this is all intended behavior, the order date/time is stored in UTC, this is to accommodate different timezones, specially ones which adjusts during a year. Say you have an order placed the day before a timezone change and you save the order date in the current timezone time, the next day that time will be off, so to accommodate this we save the date and time in UTC and then convert it to the correct timezone based on your site settings for display purpose.

The reason it is not converted on the edit order screen is because it is an editable field you can use to update the order date and time. That said it can be made a bit more clear to say the time needs to be in UTC, or we should show the date and time in the current timezone and then convert it when updating the order.

Probably a feature request, will defer to @claudiulodro to hear what he thinks.

**Comment by hko01** [comment]
Is there a workaround for that ? How can i avoid the update of the time ? I can't set the time zone to UTC.

**Comment by kloon** [comment]
If you do not change the date then it should not update, I just tested this and confirm it is not updating for me. It just displays in UTC.

If you are getting weird behavior then it is likely a plugin/theme conflict, which you can debug by following the steps as requested when you opened the issue.

**Comment by hko01** [comment]
ok, so i have to debug, cause i didn't change date or time manually. Just click on Update....

**Comment by kloon** [comment]
Yes, please do the debugging as originally asked when you opened the issue, this could possibly be a conflict with your theme or another plugin. I am unable to reproduce this issue locally using just WooCommerce on a default theme.
