### ISSUE TITLE
Free shipping is not available for below $50 spent

### ISSUE THREAD

**Issue by kiranupadhyak** [woocommerce/woocommerce#21536]
What is the minimum subtotal required for free shipping?. Right now free shipping will be enabled only if cart subtotal is greater than $50. I have tried all the possibilities to provide free shipping for below $50, but I still get any solution. Is $50 is minimum spend for free shipping?. 

In the `Woocommerce->Settings->Shipping->Shipping zones` I have added Shipping methods & set the Free shipping requires to **N/A**. In the `/woocommerce/templates/cart/cart-shipping.php` file, $available_methods always returns empty for the below $50 subtotal. Is there any other settings to do!.

Please provide the solution, thanks in advance.

**Comment by kloon** [comment]
Please not for future reference this is not a support channel, if you require support then please use the forums or if you are a paying customer you can contact support http://woocommerce.com/contact-us

In order to provide free shipping you net to specify the minimum spend, to make it an option for all order no matter the value you can use these settings http://cld.wthms.co/DGxZVs
