### ISSUE TITLE
Issue with Safari Desktop / Iphone (and all Iphone browsers as based on Safari)

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/woocommerce#21544]
@gbruzzo commented on [Fri Oct 12 2018](https://github.com/woocommerce/storefront/issues/973)

Dear All

Encountered this issue on Safari (12.0) on Mac (Mojave), as well as on every iOs browser we tested on Iphone (they are all Safari mobile based - all most recent versions )

using Safari Desktop (12.0) or latest Safari / Firefox / Opera / Chrome on iOS 12

Go to https://themes.woocommerce.com/storefront/shop/ 

add two simple products to cart 
cart fragments update (bottom right)

Now scroll to the bottom, jump to a another page on shop 

add a few more products 
cart fragments update. 

now click on the back button. 

the cart fragments regress to before the first products were added. 
Safari is either not refreshing fragments (cart hash is "")

now click the forward button. 
Cart fragments still are not updating. 

FYI: the problem does not manifest itself when trying to replicate the above on Chrome / Firefox for Desktop or Chrome for Android 

Is this to be expected?

**Comment by tiagonoronha** [comment]
Related: https://github.com/woocommerce/woocommerce/commit/747a6d51d1a38b11d84b731d40ec69eb81fd8b4c

It seems we previously fixed the issue by listening to that event, but something must have changed in Safari recently and that workaround is not working anymore.

**Comment by gbruzzo** [comment]
Hi there 

It seems Safari Back Button. pulls cart-fragments (and other ajax requests) from cache, not server. 
Seems it's a manifestation of the b/f caching policies of Safari that has been around for a long time.

Looking at the event listener added to deal with this problem originally.    
It seems the condition e.originalEvent.persisted is never set to true. 

// Refresh when page is shown after back button (safari)
		$( window ).on( 'pageshow' , function( e ) {
			if ( e.originalEvent.persisted ) {
				$( '.widget_shopping_cart_content' ).empty();
				$( document.body ).trigger( 'wc_fragment_refresh' );
			}
		} );

pageshow is a very broad event to listen to. Tried popstate and hashchange events, but they are not being fired 

for now I can only envisage using this hack

		$( window ).on( 'pageshow' , function(  ) {
                                   refresh_cart_fragment();
		} );

this results in two ajax calls (one cached, one from server), that force the cart to update. 

Ugly, sorry.

Giacomo

**Comment by gbruzzo** [comment]
Hello there 

Another option came to mind - why not pass a header expires : -1 to the ajax fragment update? 

like so 

	var $fragment_refresh = {
		url: wc_cart_fragments_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'get_refreshed_fragments' ),
		type: 'POST',
		**headers: {
		"expires": "-1"},**
		success: function( data ) {
			if ( data && data.fragments ) {

				$.each( data.fragments, function( key, value ) {
					$( key ).replaceWith( value );
				});

				if ( $supports_html5_storage ) {
					sessionStorage.setItem( wc_cart_fragments_params.fragment_name, JSON.stringify( data.fragments ) );
					set_cart_hash( data.cart_hash );

					if ( data.cart_hash ) {
						set_cart_creation_timestamp();
					}
				}

				$( document.body ).trigger( 'wc_fragments_refreshed' );
			}
		}
	};

this solves the issue squarely - seems to force safari to stop caching ajax requests 

thoughts?

**Comment by gbruzzo** [comment]
Hi there 

I Noticed that cache-control header 'no-store' is not set for cart fragments. 

changing  wp-includes/functions.php from 

function wp_get_nocache_headers() {
	$headers = array(
		'Expires' => 'Wed, 11 Jan 1984 05:00:00 GMT',
		'Cache-Control' => 'no-cache, must-revalidate, max-age=0',
	);

to 

function wp_get_nocache_headers() {
	$headers = array(
		'Expires' => 'Wed, 11 Jan 1984 05:00:00 GMT',
		'Cache-Control' => 'no-cache, must-revalidate, no-store, max-age=0',
	);

results in the cart not being cached anymore by Safari and not being served by back cache anymore.

There is probably a better way to do this?  Could someone please chime in? 
Could it be associated with this issue https://github.com/woocommerce/woocommerce/pull/16360?

Cheers

**Comment by gbruzzo** [comment]
Looking at Wordpress Trac, it seems that the issue of nocache_headers not stating no-store explicitly is one that was debated, and which was decided agains - see  https://core.trac.wordpress.org/search?q=no-store, in particular https://core.trac.wordpress.org/ticket/21938

Because there is a nocache_headers filter, the headers can be set at will, see for example
https://github.com/markjaquith/feedback/issues/48

so adding something like this to the theme's function.php should do the trick 

function no_cache_with_no_store( $headers ) {
    $headers = array(
		'Expires' => 'Wed, 11 Jan 1984 05:00:00 GMT',
		'Cache-Control' => 'no-cache, must-revalidate, no-store, max-age=0',
	);
    return $headers;
}

add_filter( 'nocache_headers', 'no_cache_with_no_store', 9999 );

This resolves the issue completely and if anything seems to make the safari pageshow-related code in cart-fragments.js redundant.

My 2c is to argue that this issue was not a bug - it's a setting that can be altered. at will. 

May I ask https://github.com/tiagonoronha and https://github.com/claudiulodro for a comment? 

it may be that setting no-store uniformly is too strong a setting and that a more subtle application is to be pursued (only add no-store to the headers of cart-fragments and nowhere else etc. 

I am happy with this setup for the moment, but further clarification is welcome. 

Giacomo

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22751
