### ISSUE TITLE
NON Sale prodcuts getting displayed on the sales section in the sidebar

### ISSUE THREAD

**Issue by anhdq1801** [woocommerce/woocommerce#21559]
**Describe the bug**
Our site has about 7 sale products. We add widget "Products" to sidebar and choose Sale products and show 5 products. The widget show sale products but also show non sale products http://take.ms/EiQ8y
**To Reproduce**
1. Go to 'Apperance > Widgets > Add "products" widget to sidebar'
2. Choose "on-sale products" http://take.ms/L9vPR

**Screenshots**
http://take.ms/EiQ8y

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
http://take.ms/L9vPR

WordPress environment
--
Home URL: |   | http://...
Site URL: |   | http://....
WooCommerce version: |   | 3.4.5
Log directory writable: |   | wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 512 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by kloon** [comment]
The product in question, is it perhaps a variable product? If so check all the variation and make sure none of them are set to on sale, WooCommerce will show the whole product as on sale when only a single variation is on sale for that product.

I am unable to replicate this locally, and since you omitted your system status report I cannot tell how you did your testing or how your site is set up and what plugins/themes you are running that might cause interference.

**Comment by anhdq1801** [comment]
Hi,

It issue with simple product not only variable product.
