### ISSUE TITLE
[REST API]: Include variations when fetching products

### ISSUE THREAD

**Issue by ChristianGerdes** [woocommerce/woocommerce#21616]
From what I can tell, I can't find any documentation and issues regarding this feature. 

**Feature**
Expand resource with nested resource sets like variations on products.

**Problem**
When fetching products and variations, you'll need to make a ton of http requests. Lets make an example and try to reduce the number of requests:
1000 x products
8 x variations pr. product

Get all products = 10 requests
Get all variations = 1000 requests
Total = 1010

**Solution**
Provide an array of resources to expand.
Endpoint: ../products
```php
['expand' => ['variations', 'attributes', ...]]
```
When doing this, you'll only have to make 10 requests to get the same outcome. It's a lot more scaleable. I know the requests file size increases, but when using the _fields query, you can reduce the file size a lot.

**Alternatives**
I know it's possible to achieve this outcome by altering the code myself, but that's not sustainable when working with hundreds of customers.

**Comment by rodrigoprimo** [comment]
cc @claudiosanches for your input

**Comment by claudiosanches** [comment]
Thanks for the suggestion @ChristianGerdes.

We'll keep an eye on the [popularity of this request](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md#feature-requests) :)

**Comment by homes2001** [comment]
Instead of querying products one by one (with `/v2/products/123`), we are batching requests to get products by using `/v2/products?include=123,234`.

It works to get a variation by calling `/v2/products/{variationId}`, however, getting multiple variations with `/v2/products?include={variationId1},{variationId2}` does not work and returns an empty array. Why? Is it intended the the call to `/v2/products/{variationId}` works? And if yes, shouldn't the call to `/v2/products?include={variationId1},{variationId2}` work too?

**Comment by averydev** [comment]
We're having to use the V1 endpoints because of this.
Thousands of API requests to retrieve this data is not maintainable and puts massive stress on both the sending and receiving servers.
