### ISSUE TITLE
 woocommerce ipn takes over paypal’s ipn

### ISSUE THREAD

**Issue by orielm33** [woocommerce/woocommerce#21628]
hello there,

i tried setting an ipn through pay:
https://www.greeninvoice.co.il/api/v1/plugins/paypal/ipn

all settings are saved and updated.

the fact is, on any transaction ID – i get woocommerce ipn, on the url notification:
https://******/wc-api/WC_Gateway_Paypal/
instaed of the ipn that has been set before.

(i even tried to solve it with paypal. they implied the something on woocommerce causes that)

is there any way to change it?
why does woocomerce ipn “takes over” any transaction?

thanks in advance.

**Comment by orielm33** [comment]
sorry. i meant "i tried setting an ipn through paypal"

**Comment by kloon** [comment]
The IPN through PayPal option is a fallback and old way PayPal used to work. PayPal has since changed and now it takes preference when you pass a IPN url to it via the code.

The IPN URL WooCommerce passes to PayPal is the IPN that needs to be pinged on your WooCommerce store in order to validate the payment. The URL you are wanting to use has nothing to do with the WooCommerce PayPal gateway so not sure what you are trying to achieve here.

If you want to reuse the same credentials for other non WooCommerce payments then you can try and pass the different IPN url when you setup the request, although I would think it would not be recommended to reuse the same credentials, you can easily create new credentials under the same PayPal account.

This is not something WooCommerce core related so cannot debug this much more for you, if you want support for PayPal and a custom app then you should probably contact PayPal or alternatively if you are developing some sort of WooCommerce integration then you can also try and contact support for assistance http://woocommerce.com/contact-us
