### ISSUE TITLE
Clicking 'Return to Merchant' button in PayPal (after payment successfully completed) cancels order

### ISSUE THREAD

**Issue by bbceg** [woocommerce/woocommerce#21670]
This issue appears to have been raised in various guises over the years and while I agree with @mikejolley in #6810 that the customer is cancelling the order before IPN is completing I don't think they intend to do so and I believe PayPal / WooCommerce is partly to blame in one particular use case:

1. The customer checks out and completes their payment on PayPal
2. The payment successfully completes and this is confirmed to the customer
3. The customer clicks the back button in their browser in an attempt to return to the store
4. The customer is presented with a page that states 'Your payment has completed' and also a button entitled 'Return to Merchant'. 
5. On clicking 'Return to Merchant' the customer is returned to the store but is presented with a message stating that the order is cancelled.
6. In some cases the IPN payment kicks in a short while later and marks the order as processing

The reason the order is cancelled after clicking the 'Return to Merchant' button is because its hyperlink contains an instruction to cancel the order.

I would not expect a button entitled 'Return to Merchant' to cancel the order so I don't think the customer is at fault. If possible I'd change the link to not cancel the order or change the button text (not ideal as the payment has already completed at this point).

**Comment by kloon** [comment]
The return to merchant button is not linked to a page that cancels the order [see the code here](https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L120-L121), it simply links to the Order received page, visiting that page will tell the customer the order is unpaid if the IPN is still to arrive. There is, however, a cancel order button on PayPal side as well, which will definitely cancel the order if clicked.

Orders are also canceled after a period when no payment is made on PayPal, or if the IPN is not delivered for some reason.

I do not think your issue is related to the back to merchant button, but perhaps an issue with the customer clicking the cancel order button, or the order not receiving the IPN and then being canceled due to non-payment.

For IPN issues please see https://docs.woocommerce.com/document/debug-subscriptions-paypal-ipn-issues/

**Comment by bbceg** [comment]
Thanks for the update, but I think you may be looking at a different button/link. When clicking back in the browser the 'Return to Merchant' button definitely includes a cancel link as shown here:

![return-to-merchant](https://user-images.githubusercontent.com/7188545/47647757-df5bfa80-db6f-11e8-9cf4-afd8bc593fd7.png)

It may well not be something Woocommerce can control (as you have demonstrated in what you're sending through to PayPal) but it's worth being aware of and ideally PayPal would either change their wording or alter the functionality.

**Comment by kloon** [comment]
That definitely should not happen, as per the code you can see we do not pass a cancel link to the return to merchant parameter. Do you have auto return enabled on your PayPal account? Try testing with that and see if it makes a difference https://www.paypal-community.com/t5/Sandbox-Environment/Activate-the-auto-return-to-merchant-on-a-sandbox-account/td-p/1348855

The cancel link on PayPal side should definitely not read Return to Merchant, unfortunately, that is not controllable by us and you will have to contact PayPal for assistance there as it is on their website.

**Comment by bbceg** [comment]
I know, rubbish isn't it :)

As it happens we've turned on AutoReturn as a result of this problem in the hope that if the user is automatically redirected they won't be tempted to click back and find that button!

So I think we are agreed it is a PayPal issue. I was thinking WooCommerce/Automattic might have more weight with PayPal than myself but I will attempt to raise it with them.
