### ISSUE TITLE
Product preview button gone?

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#21723]
Hi

Can anybody tell me where the product preview button has gone?  On existing published products it is missing even if you alter the product and dont save it.

What happened, why is it changed?

Can you please advice how to preview a published product on changes made to it?

Thank you !

**Comment by claudiulodro** [comment]
Hi,

It was removed on published products because most WooCommerce product fields are not set up to work with the "Preview Changes" feature of WordPress, so the button did not really do anything. You can read more at https://github.com/woocommerce/woocommerce/issues/20641. Hope this clears things up.

Thanks.

**Comment by BackuPs** [comment]
Hi

I am talking about the changes i made to the content. Not the custom fields.  I want to be able to preview my content changes instead of the custom fields. Btw their are plugins and themes that have no issues with previewing changes made to custom fields. Why can't woo not do such?

Please advice.
