### ISSUE TITLE
Performance regression in WC_Regenerate_Images::maybe_resize_image for certain image sizes

### ISSUE THREAD

**Issue by siliconforks** [woocommerce/woocommerce#21800]
**Describe the bug**
In WooCommerce 3.5, `WC_Regenerate_Images::maybe_resize_image` is very slow for image sizes which have both a width and a height specified but which are not cropped.  For these image sizes, `maybe_resize_image` is attempting to resize the image every time it is called.

**To Reproduce**
1. The easiest way to reproduce this issue is probably to create a variable product with a large number of variations (e.g., 10 variations) as that will call `WC_Regenerate_Images::maybe_resize_image()` a lot of times (the more variations, the more noticeable the issue will be).  The product should have a product image configured (it is not necessary to have an image configured for each individual variation).
2. Add this code to your theme:
```php
add_filter( 'woocommerce_get_image_size_single', function( $size ) {
	return array(
		'width' => 100,
		'height' => 100,
		'crop' => 1,
	);
} );
```
3. Visit the page for the variable product (described in step 1) and measure the page load time.
4. Change the code in your theme to use the sizes below. (The exact width and height values do not matter much as long as the ratio does not match the product image exactly.  The values below are chosen to make that unlikely.)
```php
add_filter( 'woocommerce_get_image_size_single', function( $size ) {
	return array(
		'width' => 100,
		'height' => 1000,
		'crop' => 0,
	);
} );
```
5. Visit the page for the variable product again and measure the page load time.

**Expected behavior**
I tested this in WooCommerce 3.4.7 (using a product with 12 variations) and the page load time was about the same for both image sizes (as expected), but in WooCommerce 3.5.1 there was a big difference:

Size | WooCommerce 3.4.7 | WooCommerce 3.5.1
---- | ----------------- | -----------------
100x100, crop = 1 | 2 seconds | 2 seconds
100x1000, crop = 0 | 2 seconds | 6 seconds

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).  [I tested it with a child theme of Twenty Seventeen - the only thing in the child theme was the `woocommerce_get_image_size_single` filter above.]
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: http://host.test/wordpress-woocommerce-3.5
Site URL: http://host.test/wordpress-woocommerce-3.5
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win32) OpenSSL/1.0.2p PHP/5.6.38
PHP Version: 5.6.38 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.6.41-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.00MB
Database Data Size: 2.13MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.52MB + Index: 0.02MB
wp_postmeta: Data: 0.08MB + Index: 0.06MB
wp_posts: Data: 0.03MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 10
customize_changeset: 1
page: 11
post: 2
product: 5
product_variation: 12

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #42 - /shop/
Cart: #43 - /cart/
Checkout: #44 - /checkout/
My account: #45 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Twenty Seventeen
Parent Theme Version: 1.7
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by clifgriffin** [comment]
We are experiencing the same issue. Following.

**Comment by mikejolley** [comment]
There is a check to see if cropping mode changed, which regens the image. Seems this PR will fix this case https://github.com/woocommerce/woocommerce/pull/22638

Thanks

**Comment by timtitch** [comment]
This problem gets worse when you use wp offload media to save to Amazon S3 and delivery via CDN. When I look at my S3 bucket it seems the thumbnail variants for an image have been updated each time you visit your shop page for example - load times are 8-10 seconds - for a site that has been optimised that hurts.

**Comment by warflower** [comment]
The PR #22638 doesn't seem to solve this bug/performance issue for me so it would be nice if the issue can be re-opened.

Let's say that WooCommerce gallery thumbnail images (woocommerce_thumbnail) are configured to be 300x300. In case an uploaded product image is smaller, and isn't 300px in width or height, then no 300x300 thumbnail will be created by Wordpress by default. WooCommerce though will still attempt to regenerate the thumbnail every time a user visits a page that displays gallery thumbnail images, and it will do so for each image that is too small and doesn't have the aspect ratio WooCommerce expects. In case of large galleries with many small images and other plugins that hook into the `wp_generate_attachment_metadata` method this can take a lot longer than it should to render the page. Since Wordpress in this case will be unable to generate the thumbnail size that WooCommerce expects, regenerating thumbnails will have no effect at all on the images on the rendered page. It will merely make page renders slower.

For example, if I have an image that's originally 250x150 then Wordpress will not create a 300x300 thumbnail because the original isn't large enough. The code in `maybe_resize_image` will then attempt to match the aspect ratio of the 250x150 original with the thumbnail it expects (300x300). Obviously, the aspect ratio's aren't the same, which causes `resize_and_return_image` to be called. This function then calls `wp_generate_attachment_metadata` to create new image sizes which can't be created, and it might trigger callbacks in other plugins that hook to the `wp_generate_attachment_metadata` function. Even though no new thumbnails have been created, still a lot of code has been executed that shouldn't necessarily have been, slowing down page renders extensively in some cases.

In cases where the width is large enough but height isn't then the thumbnail file will be recreated on each pageview. For example, with a 531x299 image, I noticed that `maybe_resize_image` is passed the original 531x299 image with a 300 width and 169 height. It then creates a 300x299 thumbnail because of the 1:1 cropping setting in WooCommerce, and keeps doing that each time the page is refreshed. When using this in combination with a plugin that syncs images to ie. S3 it can happen that on each pageview where it shows the thumbnail it also uploads it to S3 because the file on the local file system changed.
I've been able to reproduce this on a clean Wordpress 5.0.3 install with the latest WooCommerce (current master) and the Twenty Nineteen theme with default settings.

Before WooCommerce 3.5 this wasn't ever an issue for regular users browsing webshops because `maybe_resize_image` would only be called when the site was being previewed in the Customizer. It is obviously a good idea to make recreating thumbnails as easy as possible, but currently it can cause quite a lot of negative effects for users visiting webshops and admins running webshops with smaller images, which shouldn't be necessary.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22818 I've made some addional checks to prevent it trying to resize small images.

**Comment by warflower** [comment]
@mikejolley: Thanks for the additional checks. I've briefly tested your PR and it successfully fixes the issue for images with `width >= $target_size['width']` and `height < $target_size['height']`. I guess the same applies for `height >= $target_size['height']` and `width < $target_size['width']` but I haven't tested that.

Unfortunately, it doesn't yet cover the use case where an image doesn't have a 1:1 aspect ratio and both width and height are smaller than the `$target_size`. It will still attempt to recreate the thumbnail for those on each page view.

**Comment by mikejolley** [comment]
Can you provide example settings? I did test a smaller image and the new check didn't bother resizing small images.

**Comment by warflower** [comment]
Just now I tested it with a 250x141 pixels image that I uploaded in an almost stock Wordpress 5.1 with WooCommerce, using 300x300 thumbnails for the `woocommerce_thumbnail` image size. Make sure that you test it with an image that is small enough and doesn't match the 1:1 ratio it expects.

**Comment by mikejolley** [comment]
Got it, that seems to be the last edge case I missed - both sizes samller than target. Will update PR.

**Comment by siliconforks** [comment]
I was testing the beta release of WooCommerce and it includes the fix for this but it doesn't actually seem to work for the original test case I posted (at least, it doesn't work for all image sizes).

```php
add_filter( 'woocommerce_get_image_size_single', function( $size ) {
	return array(
		'width' => 100,
		'height' => 1000,
		'crop' => 0,
	);
} );
```

Suppose you upload an image that is larger than 100 x 1000 in both the width and the height, e.g., 1500 x 1500.  Then in `maybe_resize_image` it won't be caught by any of the checks that are currently present and it will end up calling `resize_and_return_image` and regenerating the image every time.

The problem is that `maybe_resize_image` doesn't actually check `$target_size['crop']` anywhere even though that makes a difference for the expected ratio.  (There's an `$uncropped` variable, but that's being used for something else and doesn't take `$target_size['crop']` into account.)

**Comment by planetahuevo** [comment]
I am not sure why, but this is still happening to me on a installation. 
I am replacing the images with a 1:1 crop and the problem has gone. In case is useful.
