### ISSUE TITLE
Product categories dropdown widget isn't using native iOS scroll option

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#21847]
**Is your feature request related to a problem? Please describe.**

(Not 100% sure this is a bug or enhancement.)

When trying to scroll through a long list on product categories on mobile (use a mobile device and not a browser set to width to experience the problem), it's made difficult because contrary to the brands widget and post categories for example, it doesn't use the native iOS scroll option.

**Describe the solution you'd like**

Using the native iOS scroll option

**Describe alternatives you've considered**

This would mean that the search is no longer disabled but that seems to be quite common even with country lists.

**Additional context**

Link to screencast here: http://cld.wthms.co/8fuFzx.

* Can be tested at: https://www.abanista.com/
* Or: https://mytestsite.works/

**Comment by kloon** [comment]
WooCommerce utilises enhanced select boxes that is why it does not work like a regular drop-down. I would argue and say it is easier to use as it has search capabilities which a normal drop-down does not. Also with a regular drop-down, you will not have the ability to nest options to indicate subcategories, so there are definitely a few wins to use the enhanced select boxes instead of regular drop-downs, removing the functionality would not be seen as an enhancement IMO.
