### ISSUE TITLE
"Only 0 left in stock" instead of "out of stock"

### ISSUE THREAD

**Issue by Arnone** [woocommerce/woocommerce#21862]
Hello,
When a product is no longer in stock, I have the following mention which appears: “Only 0 left in stock” (surrounded by green).
I would like to have the mention “out of stock” (and with an order button unavailabled)

I thought it was a mistake of the theme used, but I tried with other themes and it’s the same thing…
, I’ve also desactivated all my plugins…it’s the same…

My configuration:
wordpress version : 4.9.8
woocommerce version : 3.5.1

In the configuration of my woocommerce:

in woocommerce >product > inventory:
![01-1](https://user-images.githubusercontent.com/3018866/48214078-78b0bb00-e37f-11e8-9e93-6a7317081880.jpg)

in the configuration of inventory management in the product page: 
![2-1](https://user-images.githubusercontent.com/3018866/48214132-98e07a00-e37f-11e8-9021-04c601bae5a9.jpg)
![3-1](https://user-images.githubusercontent.com/3018866/48214175-b31a5800-e37f-11e8-872a-5192d44e04f1.jpg)

here is other image to illustrate my stock display problem :

![screenshot-2](https://user-images.githubusercontent.com/3018866/48214198-bf061a00-e37f-11e8-88e6-67380f6a3ae6.jpg)
![stock2](https://user-images.githubusercontent.com/3018866/48214213-caf1dc00-e37f-11e8-835c-161d6db2dfd9.jpg)
thank you

**Comment by kloon** [comment]
@Arnone I am not able to replicate this, I tested with just WooCommerce enabled, no other plugins/extensions and the Twentyseventeen theme. I set up my stock options as per your screenshot, set the product with 1 in stock and then placed an order for that product, upon visiting the product again after the order it showed the "Out of stock" message http://cld.wthms.co/BFYesH

Since I am unable to replicate this is clearly an issue with either your theme or a plugin that is causing the error, it could also be some custom code you are running that hooks into the stock status filters.

Closing, will reopen if you can provide instructions to replicate on a clean install with just WooCommerce and Twentyseventeen.
