### ISSUE TITLE
Extending WC_Cart - class always results in an empty cart

### ISSUE THREAD

**Issue by RobertoDonPedro** [woocommerce/woocommerce#21870]
**Description**
Extending the WC_Cart - class always results in an empty cart.
Note: Even if you just apply the original WC_Cart class again (instead of an extended custom class) the cart is always empty.

**Simple Steps to reproduce the issue:**
The easiest way to reproduce this issue is to directly adapt the` init()` function in the original WC file `class-woocommerce.php` by just duplicating the line `$this->cart = new WC_Cart();`. 
Then add a product to your car. The result will be an empty cart.

Alternatively you can copy the line `$this->cart = new WC_Cart();` right beyond the line `do_action( 'woocommerce_init' );` (This is pretty much the same than using the hook `do_action( 'woocommerce_init' );`)
Then add a product to your car. The result will be an empty cart.

**Advanced steps to reproduce the issue:**
If you want to use the hook to reproduce this issue, you can do:

> class My_Sample {
> 	public function __construct() {
> 		  add_action( 'woocommerce_init', array( $this, 'woocommerce_init' ), 15 );	
> 	}
>   	
> 	public function woocommerce_init() {		
> 		if ( !is_admin() || defined( 'DOING_AJAX' ) ) {			
> 			WC()->cart = new My_Cart();			
> 		}
> 	}
> }
> 
> class My_Cart extends WC_Cart {
> 	public function __construct() {
> 		parent::__construct();	
> 	}
> }

**Comment by kloon** [comment]
You will also have to extend WC_Cart_Session with a custom one and change a lot of functionality in there as that class is what is used to store the cart in cookies and sessions and display it again. You will notice that there are a few references in there to WC_Cart so your extended WC_Cart_Session class will need to replace all those methods with your new custom cart class.

There might also be some changes required in the session class for this to work right. Unfortunately I can't do much more than this as we do not provide technical support on here.

Have you checked if what you are trying to achieve is not possible via the existing hooks instead of creating a brand new class?

**Comment by RobertoDonPedro** [comment]
Thats what I assumed initially, too, but since it does not even work with the original WC_Cart object (simple by duplicating the line `$this->cart = new WC_Cart();` it seems to be a deeper problem. Have you tried this, too?

Regarding the proposed alternative of using a hook, please understand that currently there is no relevant hook available, this is tied to another issue already reported here: ([https://github.com/woocommerce/woocommerce/issues/21855#issuecomment-436748094]) (Remove mandatory caching of tax rates in class-wc-cart-totals). 
Would it please be possible to get this hook soon?

**Comment by kloon** [comment]
Yes I tested it, the custom class actually loads fine so the issue is not with that. The default cart class always loads as empty when you initialise it as well. The issue stems from the Cart Session class where it tries to fetch the cart content from the session, it has a check for example right before populating the cart class to make sure it is of type WC_Cart, which your new class is not.

We will look into the other issue, but will need some steps to reproduce and understand why the hook is needed as requested in the other issue.

**Comment by RobertoDonPedro** [comment]
Please do not test it with the custom class. Test it with the WC_Cart Class as described, simple by duplicating the line and creating the same object again. Then you can be sure, that it is a WC_Cart type and that it results in the symptoms described.

________________________________
Von: Gerhard Potgieter <notifications@github.com>
Gesendet: Monday, November 19, 2018 1:31:32 PM
An: woocommerce/woocommerce
Cc: RobertoDonPedro; Author
Betreff: Re: [woocommerce/woocommerce] Extending WC_Cart - class always results in an empty cart (#21870)


Yes I tested it, the custom class actually loads fine so the issue is not with that. The default cart class always loads as empty when you initialise it as well. The issue stems from the Cart Session class where it tries to fetch the cart content from the session, it has a check for example right before populating the cart class to make sure it is of type WC_Cart, which your new class is not.

We will look into the other issue, but will need some steps to reproduce and understand why the hook is needed as requested in the other issue.

**Comment by RobertoDonPedro** [comment]
Hi, have you tested it yet with the orginal WooCommerce WC_Cart - Class as described?
Please believe me, it does not even work with this class.
If there is no immediate fix available, it should be at least signed as a bug.

**Comment by MechComp** [comment]
Hi, I hope that this can still can help someone. I have solved this issue. The problem is that you need to hook initialization of your extending class to another hook 'before_woocommerce_init' instead of 'woocommerce_init'. When I have checked the code I realized, that there is a call to a function wc_load_cart which fills WooCommerce cart session with a session created from normal WC_Cart even before call of the 'woocommerce_init' hook, then you would have to also replace this session with new from your custom session. However, if you fill $woocommerce->cart on the earlier hook, everything will work as expected with your new class.
If there is a problem with this approach, please let me know. As I'm in early stage of testing, I can be seriously wrong ;-)
