### ISSUE TITLE
Product gallery images showing as "unattached"

### ISSUE THREAD

**Issue by seanreloaded** [woocommerce/woocommerce#21875]
**Describe the bug**
Product gallery images are showing as "unattached" in the Media Library.
(Using WooCommerce 3.5.1 and WordPress 4.9.8)

**To Reproduce**
1. Go to Media Library and add a new image.
2. Create a new product, or edit an existing one.
3. Add a product gallery image.
4. Select the already existing image from the media library and add to the gallery.
5. Click Update.
6. Go back to the Media Library. Make sure the mode type is set to list.
You'll see the image is shown as unattached, despite it just being used in a WooCommerce product.

The only way the image doesn't show as unattached is if you upload a new image from within the add product gallery images inside the product edit page.

**Expected behavior**
I expected the image to show as attached in the media library, regardless of whether I added a new image or an existing image to the product gallery.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rrennick** [comment]
You can repeat those steps with a regular Post (when adding the image to the post add it as a gallery) and see the same results in the media library.

**Comment by kloon** [comment]
Yea, this is not an issue with WooCommerce but how WP manages attachments from the Media Library.

I believe the reason it is this way is that you can add existing images that are already attached to a post/custom post type to another one, if you were to attach it to the new post it will be removed as an attachment from the original post which is not ideal.

Not a bug we should be fixing or looking at since this happen in WP core with posts as well.
