### ISSUE TITLE
Calculate Tax Based On does not work with Amazon Pay

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#21911]
I use **Calculate Tax Based On: Customer shipping address** in my shop. Also I have activate Geolocation. It works fine with Prepay, Stripe and PayPal but not with Amazon Pay.

If a user pays with Amazon Pay, the tax is always calculated depending on his location based on the IP address. If his physical address is in Germany and he is in Austria while ordering, the tax will be calculated by Austria and not that of Germany.

Without Geolocation, no tax will be charged at all.

I noticed the problem since WooCommerce 3.5. It seems to worked before.

* WooCommerce 3.5.1
* WooCommerce Amazon Pay Gateway 1.8.5
* WooCommerce Germanized 2.2.4
* WooCommerce Germanized Pro 1.9.7

**Comment by kloon** [comment]
Amazon Pay uses an embedded pay form which is hosted by Amazon and as such WooCommerce does not have any control over how they calculate taxes on their end. I suggest you contact support for and report it there, they can perhaps apply a fix in the extension to force a location for taxes to Amazon Pay.

https://woocommerce.com/contact-us/

**Comment by Babelfisch** [comment]
Please read my report here! It's not an Amazon problem, it's a problem of WooCommerce and the WooCommerce Amazon Pay plugin. The taxes are calculated in WooCommerce and not by Amazon.

**Comment by Babelfisch** [comment]
No that's not correct. WooCommerce calculates on the checkout page the correct tax based on the customers billing or shipping address. This tax has nothing to do with the used payment gateway. It works with all my payment gateway like Stripe, PayPal oder prepay but not with Amazon Pay.

The problem is, that the WooCommerce Amazon Pay plugin hides the shipping/billing address if there are only virtual products in the basket. Without the customers address on the checkout page, WooCommerce can't determine the customers country (and state), and uses the country based on the IP address. But that’s not correct.

For me I could solve the problem with prevent of hiding the shipping address:

```php
function my_woocommerce_amazon_show_address_widget() {
	return true;
}
add_filter( 'woocommerce_amazon_show_address_widget', 'my_woocommerce_amazon_show_address_widget', 10, 0 );
```

However, it’s a bug in the WooCommerce Amazon Pay plugin and/or WooCommerce.

**Comment by Babelfisch** [comment]
A helpful link how WooCommerce calculates taxes: [Setting up Taxes in WooCommerce](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/)

**Comment by kloon** [comment]
As I said previous, this is something that will need to be fixed in the Amazon Pay plugin and not WooCommerce core. What I tried to explain is that it is up to the payment gateway to push the correct taxes to the gateway and not WooCommerce core, payment gateways are extensions that operate with their own code and own set of rules which determine how much the customer is charged in the end.

I know how taxes work and how WooCommerce calculates them. WooCommerce core will not disable billing fields for virtual products so the taxes will always be correct based on what the customer enters, this something unique to Amazon Pay from the looks and as such will need to be fixed in that codebase.

**Comment by Babelfisch** [comment]
Sorry, but what you write is wrong! Maybe you are confusing Amazon's fees with the order taxes.

And the WooCommerce Amazon Pay Gateway is developed by WooCommerce and I think this is the best place for an issue.

**Comment by kloon** [comment]
@Babelfisch I have pointed you numerous times now to please contact support for assistance on this issue and yet you refuse. If you continue refusing I am going to have to lock this issue.

Yes, WooCommerce Amazon Pay Gateway is developed by WooCommerce/Automattic but this is not the place to handle issues with it. We are different teams working on WooCommerce core and extensions please follow the correct flows for reporting and getting issues fixed with extensions.

**Comment by Babelfisch** [comment]
I can’t find a repo for WooCommerce Amazon Payment Gateway. That’s why I posted the problem here.

But it's ok to close this issue. I found a solution and that’s enough for me.

**Comment by kloon** [comment]
There is no repo, you contact support https://woocommerce.com/contact-us/ and they will assist.

**Comment by santiazpi** [comment]
> I can’t find a repo for WooCommerce Amazon Payment Gateway. That’s why I posted the problem here.
> 
> But it's ok to close this issue. I found a solution and that’s enough for me.

Can you share your solution @Babelfisch ?

**Comment by Babelfisch** [comment]
I had already posted my solution here. You have to write this snipped in your `functions.php`.
