### ISSUE TITLE
Salutation /Greeting in emails

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#21912]
Starting with WC 3.5.0 a salutation / greeting has been added to all email templates starting with `customer-`. The salutation is built only from the customers first name using `$order->get_billing_first_name()`.

In Germany and some other countries within Europe many shops prefer a formal greeting using the first and last name of a customer. Adding the salutation as the first step to modernize WC email templates is welcome. However now we have to overload each template if the shop owner does not want to call customers by their first name because again code has been added directly to templates. Wasn't it one of the goals to get rid of those hardcoded lines? Please add at least a filter like `email_customer_salutation` to allow a quick modification without the need to overload 16 template files.

In addition I see in some templates the greetings get escaped but no in others. Why?

\emails\customer-completed-order.php
`printf( esc_html__( 'Hi %s,', 'woocommerce' ), esc_html( $order->get_billing_first_name() ) );`

\emails\customer-on-hold-order.php
`printf( __( 'Hi %s,', 'woocommerce' ), $order->get_billing_first_name() );`

**Comment by kloon** [comment]
Hi @mensmaximus, thanks for the suggestions. Emails are still an ongoing work, we plan to do more changes in the next release. Adding a filter is a good idea, but adding in the next fix release will not be viable as that will mean anyone that changed template will need to manually update them again and since we will be working on improving emails more in the next minor release which will likely mean template changes again this can be a pain for those that override the template.

You are welcome to override the template yourself and change the value there.

Regarding the escaping, that is probably just an oversight when we implemented the changes.

I can assure we have plans to make emails easier to edit without the pain of having to override templates and update them constantly when core changes its templates.
