### ISSUE TITLE
Meta referrer interferes with item removal from the cart

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#21946]
**Describe the bug**
Clearing an item from the cart using the "x" icon doesn't seem to do anything. When the cart is reloaded, the item is removed.

**To Reproduce**
1. Add this to the HEAD section in header.php: `<meta name="referrer" content="origin">`
2. Add a product to the cart
3. Remove the item from the cart
4. Reload the cart page

**Expected behavior**
Cart should be displayed, minus removed item, OR empty cart message if last item was removed.

**Isolating the problem (mark completed items with an [x]):**
I've narrowed it down to having the meta referrer tag in the HEAD.

**WordPress Environment**
<details>
```
N/A
```
</details>

**Comment by rrennick** [comment]
> Add this to the HEAD section in header.php:

You can use back ticks to mark description content as code so it doesn't get stripped.

**Comment by galbaras** [comment]
Oops. Thanks for noticing. All good now.

**Comment by kloon** [comment]
This happens because that line intereferes with the WordPress core function wp_get_referer which is used to determine where to redirect to after an action is performed on the cart. If you inspect the content of the blank page you will see it actually loads the homepage inside the cart but it is hidden due to css as it is trying to load the homepage inside the cart page which won't look good at all.

I'd say you should not use origin, but rather origin-when-cross-origin, using just origin can have SEO impact when it comes to indexing your other pages on your site, it is also likely to break a lot of things relying on the wp_get_referer function on your site.

Unfortunately, we cannot rely on the raw referrer headers as that imposes a security risk and can open up sites to XSRF attacks. If you must use origin as the referer then I suggest you apply that via conditionals so ensure it is not set on the cart or checkout pages.

Closing as I do not think this is a bug but rather a site setup issue.
