### ISSUE TITLE
Ordering product attribute values by name in variable add to cart

### ISSUE THREAD

**Issue by marcopetersamazing** [woocommerce/woocommerce#21951]
**Describe the bug**
When trying to get the attribute value selection on a variable add-to-cart ordered by name, this is not possible. When looking into the code of WooCommerce, it will always order by de custom order in the database, and will never look at the default order setting for the attribute. The issue seems to be in /includes/wc-term-functions.php:488-500.

**Expected behavior**
When setting the default order of an attribute to 'Name', the order of the attributes in the dropdown select in the product detail page, is not ordered in that way.

**Comment by rrennick** [comment]
I tested and was not able to reproduce this. Can you provide some details on your product & attributes?

**Comment by kloon** [comment]
There is code in wc_terms_clauses that adjust the order by, but only when not ordering by name. As @rrennick I cannot replicate.

Since you omitted your System Status Report and provide additional testing details it is hard to tell if you have tested this with all plugins disabled except WooCommerce and using a default theme like Twentyseventeen or Storefront.

Please test using that and if you are still able to replicate provide the steps for use to replicate this, ie how your attributes are set up as well as your variations.

Will reopen once we have clear steps to replicate.
