### ISSUE TITLE
Order.updated webhook sends multiple events for auto-draft orders

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#21952]
When subscribed to the order.update webhooks, you'll get multiple webhooks send for the order.updated topic, many of which have "auto-draft" as a status. For example, when I manually create an order, I get 6 auto-draft webhook events and 3 "order updated" events, all from creating an order with pending status: http://cloud.skyver.ge/1f1b839f1967

1. I don't think webhooks should be sending for auto-draft updates
1. I'm not sure why this sends the `order.updated` webhook rather than `order.created` either

**To Reproduce**

1. Create an order.updated webhook and send it to a test URL (I'm using Beeceptor and have no other webhooks registered)
1. Create an order manually in WP admin for an existing customer. I added a couple of products and a shipping address. I didn't change status so it was set to "pending"
1. Click "Create" for the order.
1. Check your Beeceptor log and see that several events have been fired, many of which were for the auto-draft status

**Screenshots**

http://cloud.skyver.ge/1f1b839f1967

**Expected behavior**

I expected manually created orders to only send the `order.created` webhook, and not to send webhooks for auto-draft updates.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Local environment with WP 4.9.8, WC 3.5.1 only

**Comment by dipeshparashar** [comment]
Same Issue : Woocommerce 3.5.1

**Comment by kloon** [comment]
If you want to just trigger an order created event then you will need to set up your webhook with the order.created topic.

The order.updated topic will fire multiple times depending on how often the order is saved, extensions can also trigger this by just calling $order->save(), we could argue that drafts should be excluded and I kind of agree, but there might be some stores that rely on webhooks to fire for drafts, technically saving a draft is updating the order.

As for the multiple events, that is all dependant on how the data is saved, extensions can also manipulate this by calling the save method on the order object.

I'll let @claudiosanches comment on the draft events and whether that should be excluded since he has the most experience with the webhooks implementation. Personally, I think we should leave it as is as it could break for stores potentially relying on it, much easier to fix this on your own webhook consumer than making a change to the software which has this working in older version and then with an update could break functionality for stores that rely on it.

**Comment by bekarice** [comment]
> If you want to just trigger an order created event then you will need to set up your webhook with the order.created topic.

@kloon I meant moreso that I didn't expect the order.updated topics to be delivered until the order was actually created, as this was triggering while I was manually adding a new order, it hadn't been "created" yet.

I'm less concerned about the multiple events, but am questioning whether the auto-draft status should trigger the order webhooks or not. We can certainly exclude this from anything consuming the API, it just feels unexpected given the auto-draft status isn't [listed in the API index](http://demos.skyverge.com/wp-json/wc/v3), for example, as a valid order status, so API consumers don't expect auto-draft orders hitting their system. I see the point about backwards-compat, so perhaps this is a docs issue if the behavior won't be changing?

**Comment by kloon** [comment]
Ah, gotcha. Missed the part that it was not saved at all yet. I agree that the order should at least have an ID first before it starts sending update topics.

**Comment by Robbertdk** [comment]
I had the same issue with missing ID's for orders added via the backend and resolved it via a filter.
I my use case we didn't need to send orders with the status auto-draft at all.

```
/**
 * Don't trigger wehbooks for orders with the status auto-draft
 * 
 * @param Boolean $hould_deliver Check if the webhook should be send
 * @param Object $hook WC_Webhook 
 * @param Mixed $arg first hook argument 
 * 
 * @return Boolean true if webhook should be delivered, false otherwise
 */
add_filter('woocommerce_webhook_should_deliver', function($should_deliver, $hook, $arg) {
	if (!$should_deliver) return $should_deliver;

	$resource = get_post( absint( $arg ) );
	if(!$resource) return false;

	$status = $resource->post_status;
	if(empty($status) || $status === 'auto-draft') return false;

	return true;
}, 10, 3);
```

**Comment by mikejolley** [comment]
This should be resolved in https://github.com/woocommerce/woocommerce/pull/22731
