### ISSUE TITLE
Store notice not showing up in browser when once dismissed

### ISSUE THREAD

**Issue by vivulazi** [woocommerce/woocommerce#21963]
When a customer dismissed once a store notice, he will never receive any further store notices.
Woocommerce uses the cookie "store_notice" with a value of "hidden" when the user presses dismiss.

When the admin creates or updates a store notice a timestamp or incremented value should be implemented. The browser should check against this value when a customer previously dismissed a store notice.

**Comment by kloon** [comment]
The store notice was originally added as a way to indicate if a store is a demo store, it has since been adopted as a way to show messages to customers but the underlying functionality was never added to make it function like a multi-banner system where you can dismiss the banners per message.

We will look into adding this functionality in the near future.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22645
