### ISSUE TITLE
WC_Payment_Gateway->get_return_url() reveals key/order password to unauthenticated user

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/woocommerce#22049]
In some payment gateways (form based), user is redirected back to callback url `/wc-api/callback` after (successful/unsuccessful) payment, and the only thing they return is an `order_id`.

Consider following code:

<img width="1064" alt="screen shot 2018-11-26 at 9 18 18 pm" src="https://user-images.githubusercontent.com/8479569/49030465-d2f3ad80-f1c0-11e8-996f-3e8e5dce92a6.png">

notice `$this->get_return_url( $order )`

This is how return url looks:
`checkout/order-received/170/?key=wc_order_5bfab4a6a5c4b`

As you can see order password is reveled in the url, and unauthenticated malicious person can download digital products attached to this order.

Obviously this can be fixed on the gateway/plugin level, checks can be added, to the example code I've posted, that user is logged in and that order belongs to this user:

<img width="772" alt="screen shot 2018-11-28 at 12 37 06 am" src="https://user-images.githubusercontent.com/8479569/49110046-cc8b3180-f2a5-11e8-93eb-e59ad88d07b9.png">

But I believe for everyone's sake these checks should be done inside `get_return_url` method. So data is not leaked accidentally by a plugin developer.

What do you think?

**Comment by rrennick** [comment]
> unauthenticated malicious person can download digital products attached to this order.

Can you describe the steps used to download these files without being logged into an account that has authorized access to the files?

**Comment by mikejolley** [comment]
I think what is being explained here is:

- Gateway plugin has a wc-api endpoint which they return the user to after payment
- Gateway plugin does not verify the user actually owns the order
- Gateway plugin redirects user to the WooCommerce 'return url' which contains order ID + key so they can view the thanks page.

Theoretically if you knew the IDs of downloads as well as the order details you could download products, but the main issue above is the data leakage, which is the fault of the gateway,

The problem with the proposed solution is that not all users are logged in - we support guest checkout.

Ideallly, the gateway would have it's own validation in place to ensure the user being redirected is the owner. e.g. it could verify the order key against the stored order key before doing a redirect. **In fact, if a gateway plugin is updated order statuses without validating this first, thats an even larger exploit because you could trick the order into thinking it's paid and access downloads that way.**

@sandrodz If you've found a gateway doing the above, I'd suggest disclosing this to the author privately so they can fix their code and add some security checks. The redirect is not the only issue.

For future reference, please also use https://hackerone.com/automattic for disclosure of security issues. Then it can be investigated privately and you'll get a bounty if valid.

In this case, because the gateway needs it's own security measures in place (e.g. order key validation) before doing the redirect, a workaround in core should not be required.

let us know if I've missed anything.

cc @claudiosanches @claudiulodro
