### ISSUE TITLE
Zero Tax rate products display the text ( inc VAT ) in the cart and checkout

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#22047]
**Is your feature request related to a problem? Please describe.**

HC: 6098957-hc

When you have products which are both standard and zero tax rates added to cart the text ( inc VAT ) displays next to the product total even although the total has no tax added, the totals are correct. The product of Drinks - 12 x Berry is using the tax class of Zero Rate and the product Drinks - 12 x Tropical is using the Standard text class and is applying a 20% rate for GB.

The totals below are correct but the Drinks - 12 x Berry which is zero tax is displaying the ( inc VAT ) even although it has no tax calculated on the total.

![w4f2ye](https://user-images.githubusercontent.com/1190565/49028270-e7707f80-f199-11e8-95e2-0195fdd97381.png)

This occurs when the setting **WooCommerce > Settings > Tax > Display prices during cart and checkout** is set to **Including Tax**

**Describe the solution you'd like**

When the setting **WooCommerce > Settings > Tax > Display prices during cart and checkout** is set to **Including Tax** products which have no tax calculated would not display the ( inc VAT )  text next to them in cart and checkout.

**Describe alternatives you've considered**

We considered setting the  **WooCommerce > Settings > Tax > Display prices during cart and checkout** is set to **Excluding Tax** and the  **WooCommerce > Settings > Tax > Display tax totals** is set to **As a single total**. Whilst this does kind of work it's not ideal.

**Comment by rrennick** [comment]
If you set the product to no tax instead of Zero rated then the inc. tax label is not added to the price.

**Comment by mikejolley** [comment]
Regarding the display, I think it could be considered correct. You're showing a tax inclusive price at 0% VAT. If this was not shown, it would not be clear if the price was inclusive or exclusive of VAT unless you knew the rate was 0% for the goods.

From memory, if you're selling goods at 0% VAT you still need to show that it's 0 rated on things like invoices.

> Zero-rated means that the goods are still VAT-taxable but the rate of VAT you must charge your customers is 0%. You still have to record them in your VAT accounts and report them on your VAT Return. 

As @rrennick pointed out, you can work around this by turning off tax for the item rather than setting a zero rate. Since you can hide them by doing this, we can serve needs of those who want it to show, and those who don't, without customisation. Unless this is proven wrong by someone such as an accounted, I'd leave it as is.
