### ISSUE TITLE
reset_image should not be called on page load

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#22061]
`reset_image` is called on page load for variable products.

Nothing is being reset but the event is being triggered.

**Comment by mikejolley** [comment]
When the variation form is loaded, it init's by doing an inital check for matching variations. This allows it to work with default selections, and after post.

Since the attribute dropdowns are empty, reset is fired. Nothing get's 'reset', but the event is fired regardless. Any 3rd party code should be able to deal with this.

Let me know if there is something than cannot cope with this event.

Thanks
