### ISSUE TITLE
Coupon calculation bug

### ISSUE THREAD

**Issue by krbvroc1** [woocommerce/woocommerce#22145]
I have encountered two coupon issues with an steeply discounted order I was asked to investigate today.
- User attempted an order on 11/23 using a black friday coupon - order consisted of 1 subscription and 4 download items (all virtual/downloadable products, so no inventory involved). Order failed due to failed credit card and sat in pending payment state.
- Coupon was Fixed product discount of $25 with 11/30 expiration that only applied to the subscription product.
- 'Pending payment' order as viewed by user and via admin did show a discount total of $25. This display appears correct.
![selection_093](https://user-images.githubusercontent.com/1335118/49543841-38bdf480-f8a7-11e8-82be-a07c99024a37.png)

- Today the user returned to the site, logged in, and decided to pay the failed order. Checkout page shows the coupon magically changing from $25 to $64.96. Not to mention the coupon is expired and should not be allowed. 
![selection_094](https://user-images.githubusercontent.com/1335118/49543928-7ae73600-f8a7-11e8-8957-7e6cfb0d55e4.png)

Somehow the $25 expired coupon resulted in a $64.96 discount. 

So it would appear to be there are two issues - you should not be allowed to use an expired coupon when paying a stale/pending order. And a WCS calculation bug. Assuming my analysis is correct, the calc bug seems serious.

Using WC 3.5.2, WCS 2.4.4, and WP 4.9.8

**Comment by kloon** [comment]
For the Subscriptions bug can you please open a ticket with support so the developer of subscriptions can take a look into this.

Regarding the expired coupon, coupons, when applied, are stored as part of the cart, we do not recalculate and check coupons on every page load for performance reasons. That said if the user tries to complete the checkout it will not proceed and notify the user the coupon has expired. So even though the coupon showed, it is only because it was applied before the coupon expired, but would not have let the user checkout with the expired coupon.

**Comment by krbvroc1** [comment]
@kloon 
> For the Subscriptions bug can you please open a ticket with support so the developer of subscriptions can take a look into this.

I already did at the same time as reporting this here.

> 
> Regarding the expired coupon, coupons, when applied, are stored as part of the cart, we do not recalculate and check coupons on every page load for performance reasons. That said if the user tries to complete the checkout it will not proceed and notify the user the coupon has expired. So even though the coupon showed, it is only because it was applied before the coupon expired, but would not have let the user checkout with the expired coupon.

Before dismissing/closing my bug report, the screenshot I posted was from the scenario you claim is impossible. Maybe it wasn't fully clear from my description, the order was was placed on 11/23 with a coupon that expires on 11/30.  The payment gateway failed and the order was left in a 'pending payment' state. On 12/5, **after coupon expiration**, the user visited their My Orders page and clicked 'Pay' on the order. The order **successfully completed using the expired coupon**. I am not sure if this scenario is unique to subscriptions, but it doesn't match the what you describe as impossible.

**Comment by kloon** [comment]
OK, thanks for the update. From the screenshot, it looked like you simply tested up until checkout and did not try a checkout, although the remove coupon link looks like it is on the checkout page.

The reason the coupon was still valid is as you describe, the order was created in your database prior to the coupon expiry date, just had a failed/pending status? In essence, that means the customer applied the coupon before it expired but the payment was just not processed correctly, they then proceeded to pay the failed order via my account.

When you pay pending/failed orders you do not go through the standard checkout again, but you simply pay an existing order in the database, from my testing you cannot edit a failed order from the pay page as the order is already saved in the database, it just loads the order and allows you to pay for it.

I guess it is debatable whether this should be allowed or not, I think it is probably fine since the order was created before the coupon expired, you will probably differ with my opinion on that.

If you are able to apply the coupon to a new order after it expired I would definitely consider that a bug though, but my testing shows that is not possible.

**Comment by krbvroc1** [comment]
@kloon - Yes, I can see how it might be debatable, perhaps there was a temporary credit card failure, and they fix it shortly. However if the pending payment lingers for weeks or months it should not be allowed. I am trying to understand how I can prevent this. Even if I manually change the pending order to 'failed' or 'cancelled', the pay button is still there. I have been unable to find a way to move the failed order to a state that disallows the 'Pay' button with the expired coupon. Maybe trashing it is the only way but I am not sure I want to be that severe so there is a record in the system of the failed order.

Searching the code for `E_WC_COUPON_EXPIRED` I don't see that error code used anywhere in woocommerce except for a single unit-test. Where is the code you the reference, I would like to look there and see if I can understand what might be happening. Is there a hook/action when paying from a pending/failed order where I can do my own checks and prohibit the checkout from proceeding? The cart/checkout/sessions code is very confusing to follow.

**Comment by kloon** [comment]
Coupon validation are done in two places, when you apply it in the cart/checkout it calls WC_Discounts::is_coupon_valid, and then when it creates the order it calles WC_Order::apply_coupon

As you can see none of those fires after an order is already created since well the order is already created and totals calculated.

The only way around this would be to utilise the Stock Management functionality in WooCommerce -> Settings -> Products -> Inventory. There is an option to hold stock, once that period has passed WooCommerce will update any pending orders to cancelled, and then the customer cannot pay the cancelled.

**Comment by krbvroc1** [comment]
@kloon I am not sure stock management applies to virtual and/or downloadable stuff. Regardless, the problem with that is that while moving it to the cancelled state will prevent the Pay button, it marks the subscription as cancelled which has its own set of issues. Failed is really what I want, but that doesn't remove the Pay button. IMO, cancelled means something different than failed and really this is a scenario where the order failed due to lack of payment and thus the subscription failed. 

What I am really looking for is where some sort of 'create checkout from existing order' is happening--that is where I need to hook into and add my own validation. Any ideas what this code path is?
