### ISSUE TITLE
Why not use __DIR__ instead of dirname( __FILE__ )

### ISSUE THREAD

**Issue by ianwijma** [woocommerce/woocommerce#22154]
**Is your feature request related to a problem? Please describe.**
So my IDE keeps telling me I should use `__DIR__` instead of `dirname( __FILE__ )`. So I decided to check out why `dirname( __FILE__ )` is even used. And saw `__DIR__` did not exists prior to PHP 5.3. Then I checked what the minimum required version of WooCommerce is. And I saw it was PHP 7 or greater. So is there any issue with changing `dirname( __FILE__ )` to `__DIR__`?

**Describe the solution you'd like**
replace `dirname( __FILE__ )` with `__DIR__`

**Describe alternatives you've considered**
Unsure what alternatives there are.

**Additional context**
I'm willing to make the change! Just wanted to get to know why this is not changed yet. 

PS. Also this is my first time making a contribution to an open source project in any way. so excuse me if I make any mistakes.

**Comment by rodrigoprimo** [comment]
Hi @ianwijma,

Great to see your interest in contributing to a free software project.

PHP 7.0 is the minimum version we recommend, but we still support PHP 5.2 (https://wordpress.org/plugins/woocommerce/#installation). That is why we can't make the change you are proposing.

**Comment by faisal-alvi** [comment]
**Their result is exactly the same** ; so, no difference on that.

For example, the two following lines :

```
var_dump(dirname(__FILE__));
var_dump(__DIR__);
```

Will both give the same output :

`string '/home/squale/developpement/tests/temp' (length=37)`

But, there are at least two differences :

- `__DIR__`  only exists with PHP >= 5.3 ( which is why `dirname(__FILE__)` is more widely used )
- `__DIR__` is evaluated at compile-time, while `dirname(__FILE__)` means a function-call and is evaluated at execution-time.

so, `__DIR__` is (or, should be) faster

[Ref](https://stackoverflow.com/a/2749423/3422447)

**Comment by ianwijma** [comment]
> PHP 7.0 is the minimum version we recommend, but we still support PHP 5.2

Aahh my excuse. I only checked the website. where it says it was 7.0, I missed a piece lower where it talks about PHP 5.2.* [woocommerce.com/server-requirements](https://docs.woocommerce.com/document/server-requirements/)
