### ISSUE TITLE
v3.5.2 Wrong post_author. Order's post no longer belong to customer in wp_posts database table

### ISSUE THREAD

**Issue by gdmonnezza** [woocommerce/woocommerce#22169]
In versions < 3.5.2, when customer places an order, a new database entry in wp_posts is created.
This new post record has
- order number as wp_posts.ID field
- "shop_order" in wp_posts.post_type field
- customer's userID in wp_posts.post_author field.

This is usefull and was introduced to speed searches into orders, as wp_posts is an indexed table.
I made a plugin using this criteria to populate other tables.
In version 3.5.2 this behaviour is now broken, and new order adds post record always with fixed wp_posts.post_author = 1 (admin)

Anyone has some clues?

**Comment by kloon** [comment]
By default the customer will never be set as the author of the order, we did try it in 3.5.0 but reverted it in 3.5.1 due to issues it caused with other plugins and orders created via the backend.

We might revisit it in a future release again but for now it remains as it was prior to 3.5.0 where it sets the order author id to 1.
