### ISSUE TITLE
Cannnot install woocommere

### ISSUE THREAD

**Issue by ckirk08** [woocommerce/woocommerce#22192]
I try to click to install plugin and the plugin doesn't install. Clicking the install button does nothing. I return to the plugin and press install again and the button reappears stating install again. I click install again and nothing happens. I have tried to contact web hosting services (godaddy) and they told me to contact the owner of the plugin which I am doing. Please assistance in the following matter.

Thank You,

Candice L. Kirkland

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Since WordPress handles the installation functionality of all plugins your best would be to ask on the WordPress.org forums https://wordpress.org/support/

Chances are you have some sort of conflict on your site causing this. Unfortunately, this issues tracker is only for reporting bugs with WooCommerce core functionality and not a support forum.
