### ISSUE TITLE
Orders statuses are now being changed to 'cancelled' instead of 'in progress' via PayPal

### ISSUE THREAD

**Issue by leeneilson** [woocommerce/woocommerce#22202]
Orders statuses are now being changed to 'cancelled' instead of 'in progress' when payment is processed via PayPal. The payments are going through ok and as before, this happened since the latest update to the plugin.

**Comment by kloon** [comment]
WooCommerce cancels unpaid orders after a certain period as defined via WooCommerce -> Settings -> Inventory. There is a hold stock option, once that threshold is reached the order is cancelled.

I suspect your issue might be that PayPal is not communicating with your store correctly which is causing orders not to be marked as paid since you say the payment was successful.

See the Debugging IPN issues section to debug this and find out why PayPal cannot communicate with your store to update the order statuses https://docs.woocommerce.com/document/paypal-standard/#section-21
