### ISSUE TITLE
Inventory "Hold Stock" feature not working

### ISSUE THREAD

**Issue by onusgit** [woocommerce/woocommerce#22206]
I’ve enabled the “Hold stock (for unpaid orders) for 30 minutes, I want to cancel order if user not make payment withing this time. I did one order and order status "pending payment" but its not cancel after 30 min.

I have installed "Cron Manager" to review, I can see single event "woocommerce_cancel_unpaid_orders" set.

Manage stock is enabled.
Woocommerce Version 3.5.2
 
![capture](https://user-images.githubusercontent.com/15248145/49868841-9a94d600-fe34-11e8-9b6d-8b56501b1674.JPG)

**Comment by kloon** [comment]
If the cron event is set then it should eventually fire. Remember that WordPress cron requires traffic to your site in order to process the cron events. If you are saying that you can see the event woocommerce_cancel_unpaid_orders then it is set to run, your site might just need some traffic for it to fire reliably, which if you are testing on a development environment is not going to be the case.

**Comment by onusgit** [comment]
Thanks @kloon 
Site is in production and I am getting daily 4-10 orders.  There is enough traffic,  150-200 users daily visit. 
How I can further debug
