### ISSUE TITLE
Coupon amount getting tax added when prices entered exclusive, but displayed inclusive

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#22239]
**Describe the bug**
Expanding on #22196 where the subtotal is incorrect, if a coupon is applied, it is also showing as incorrect. The coupon below is for 4.99 and is being increased by the 20% tax:

![](http://cld.wthms.co/FpwmIa+)
Image Link: http://cld.wthms.co/FpwmIa

**To Reproduce**
1. Set prices to be entered exclusive of tax
1. Set prices to show inclusive of tax
1. Set tax rate to 20%
1. Create product with price of 41.625
1. Create coupon with a fixed cart discount of 4.99
1. Add item to cart
1. Add coupon
1. You will see the subtotal and coupon are both incorrect as in screenshot above. 

Found in 8770563-hc.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
This isn't a bug - it's showing the discount "inclusive" of taxes.

The discount amount is 4.99. But because taxes are calculated before discounts, the actual discount will seem a bit higher.

Simplified example. 

Product price is $20
Tax rate is 10%
Discount is $5

If I do this excl. tax, it would be:

20 - 5 = 15, then 15 * 1.1 for tax = 16.5 final price.

Without discount that would be:

20 * 1.1 = 22

The discount is 5, but the difference in total is 5.5 because of the taxes.

Showing this in the cart excl of tax makes sense. However, when you show totals INCLUSIVE of tax, showing it would "appear" as 22 - 5 discount = 16.50. Mathmatically this looks wrong :) So to fix this, we add the tax amount to the discount amount so it looks like 22 - 5.50 and adds up.

Hope that makes some sense.
