### ISSUE TITLE
100% coupon on product with a price with three decimal places doesn't discount full amount

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#22267]
**Describe the bug**
Found this by accident and thought I'd report it, even though it's a small issue. 

If a product has a price that is 3 decimals and a 100% off Percentage discount coupon is used, the full amount is not removed from the cart. 

**To Reproduce**
1. Create product with price of 41.625
1. Create coupon with Percentage discount of 100%
1. Add product to cart, apply coupon
1. .01 remains as the Total

**Screenshots**
![](http://cld.wthms.co/ftjhxW+)
Image Link: http://cld.wthms.co/ftjhxW

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by jayupadhyay01** [comment]
Hi @jessepearson 

Thanks for finding issue,

Here is the Solution.
#22295

**Comment by rrennick** [comment]
I wasn't able to reproduce this with any combination of tax exclusion/inclusion settings

<img width="825" alt="screen shot 2018-12-28 at 2 58 29 pm" src="https://user-images.githubusercontent.com/343847/50525337-2eaba200-0ab1-11e9-8d03-1ecec19a0d0a.png">

**Comment by jessepearson** [comment]
@rrennick Set your decimals to 2 under WooCommerce > Settings > General > Currency options

**Comment by mikejolley** [comment]
I took a look into this. Officially 3dp prices in a 2dp currency/store shouldn't be supported. It adds discrepencies in discounts as well as taxes.

In this case, the discount amount gets rounded down using the store's DP setting precision which leaves a .005 left to pay. This in turn gets rounded up to 1p as shown.

As a workaround, you can set WC_DISCOUNT_ROUNDING_MODE to 1 in the config file. This will force the discount to round up, and cover that .005. This change cannot be made in core because it would affect current users, and break unit tests which rely on discounts rounding down.

> Another alternative would be to warn shop managers that the precision of the price might adversely affect the shop calculations.

Thats a posibility if this comes up more often cc @claudiosan
