### ISSUE TITLE
Cloudfront Host Returning 403

### ISSUE THREAD

**Issue by f3bruary** [woocommerce/woocommerce#22341]
**Describe the bug**
It looks like the host for the changelogs is returning 403 Forbidden. The base url is http://dzv365zjfbd8v.cloudfront.net/.

**To Reproduce**
1. Go to WooCommerce > Status
2. Have the Query Monitor plugin active
3. View QM Errors

**Screenshots**
![image](https://user-images.githubusercontent.com/5641933/50693602-b3f60000-1037-11e9-954c-de108e57bd0a.png)

**Expected behavior**
I expected it not to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WP 5.0.2
WC 3.5.3

**Comment by mikejolley** [comment]
This happens if a changelog does not exist e.g. for woosidebars which has no changelog on cloudfront.

A working example: http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-waitlist/changelog.txt

The code uses wp_remote_retrieve_response_code and checks the response code. 200 it exists. Query monitor is just picking up the fact it does not exist. I don't think this needs a patch (without running the request there is no way to know if the file exists).

Thanks

cc @claudiulodro
