### ISSUE TITLE
Woocommerce error when checking out with PayPax

### ISSUE THREAD

**Issue by eeeeeeehsan** [woocommerce/woocommerce#22434]
Hello

This issue shows up after clicking on the Place order button on the checkout page:

There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out.

I use the PayPax gateway. The API on the test mode works fine, but on the live mode shows up this error.

**Comment by kloon** [comment]
Please contact the developers of the PayPax gateway to assist with this since this is not a payment gateway bundled with WooCommerce core this is not something we support.

Testing with a bundled gateway like PayPal completed the order for me on my development environment so definitely something with the Gateway causing the issue.

**Comment by eeeeeeehsan** [comment]
> Please contact the developers of the PayPax gateway to assist with this since this is not a payment gateway bundled with WooCommerce core this is not something we support.
> 
> Testing with a bundled gateway like PayPal completed the order for me on my development environment so definitely something with the Gateway causing the issue.

You're absolutely right, kloon. But the problem is I contacted them a lot and their response was that their other integrations are working fine and the issue is with my Woocommerce website! While I changed the theme as well but error still exists. Don't know what to do! I gave the access of my panel and server to an expert developer and he came up with some "False" error during the integration too. Really appreciate your help, kloon.
