### ISSUE TITLE
Star ratings not editable when reviews are disabled

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#22470]
**Describe the bug**
When the **Enable reviews** option is disabled the review stars still show on the shop and category pages. In turn, then **Product ratings** is no longer editable from the Settings > Product page.

**Expected behavior**
Because the star option within **Product ratings** isn't dependant on **Enable reviews**, it should not be hidden based on the **Enable reviews** configuration. The problem this creates is when **Enable reviews** is set to disable, the expectation is assumed stars should remain enabled without the ability to control otherwise.

**Screenshot to reproduce**
Here is a screenshot of the stars option not longer becoming available after reviews are disabled([#](http://cld.wthms.co/D6GIGC))

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
The rating functionality all forms part of the review system, looking at the code you need to have reviews enabled to be able to add star ratings to products. So my understanding would be that if you disable reviews then the star ratings should also not show since you can only add a star rating when you have reviews enabled.

This is a bug and I can confirm, but not as you describe. It is relating to the shop page only looking at the enable star reviews setting and not also looking at the enable reviews setting.

**Comment by kloon** [comment]
See #22476
