### ISSUE TITLE
Make the Price Filter Widget great again, with hooks

### ISSUE THREAD

**Issue by psaikali** [woocommerce/woocommerce#22516]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a Shop Page sidebar with many different filters. One of them is the Price Filter Widget from WooCommerce, and some others are handcrafted.
The Price Filter Widget:
- outputs its own `<form />` tag
- does not offer any hook in this `<form>` element

So we have no way to add other additional filters in the Price Filter Widget form, to use the same submit button.

**Describe the solution you'd like**
It would be great to refactor the Price Filter Widget output so that we can inject custom code inside its `<form>` tag.

**Describe alternatives you've considered**
No "clean" alternative to do that ¯\_(ツ)_/¯

**Comment by mikejolley** [comment]
Hi @psaikali 

I think there is an alternative to this, and thats not to use price filter. Hear me out.

> I'm trying to create a Shop Page sidebar with many different filters.

The proposed approuch in #22517 would mean all of your custom filters have to go inside the price filter form in order to work. Actions let you add, but they don't let you remove the wrapping form tags or move/add the submit buttons. You would be forced to output either before or after, but you wouldn't be able to change the price filter itself.

That doesn't seem ideal.

A template could allow more flexibility, but by then you're basically creating a custom widget anyway so you may as well keep your custom filters separate.

The price filter widget isn't overly complex and is not coupled to the query classes in any way, so you could include a price filter in your custom widget/sidebar and use the same input names--it would still function.

So my suggestion would be to take the price filter inputs, and move them either into your custom sidebar or a custom widget which has the extra non-core filters you seem to be attempting to add.

Also FWIW, if price filter was separate to your other filter form, it would still respect your custom filters even if it has a different submit button because `wc_query_string_form_fields` will detect and output hidden inputs for each custom query var.

Hope this makes sense.
