### ISSUE TITLE
Product Review form No alert for Your review, Name and Email

### ISSUE THREAD

**Issue by navnit-viradiya** [woocommerce/woocommerce#22618]
**Describe the bug.**
When submit review form, it not give any alert (js validation) for enter Your review, Name and Email. 
Or it redirect to other page.

**Solution**
Need to add js validation.

**Comment by faisal-alvi** [comment]
Hi @navnit-viradiya , Thank you for creating an issue ticket. I have tried to regenerate the issue but validations are working fine for me. Please have a look at the screenshot.

![review-form-validations](https://user-images.githubusercontent.com/25176325/52044010-11ae3700-2567-11e9-9a4d-a9b49d6a358d.png)

Maybe you have some other Plugin/JS which could conflict with validations. Can you please describe more about your system or share a live demo if possible.

**Comment by navnit-viradiya** [comment]
Hi @faisal-alvi,

Thanks for tried to regenerate.

Please check after select rating. 
Need to add alert in Your review, Name and Email..

Thanks

**Comment by mikejolley** [comment]
Hi,

We only add the JS validation for the star ratings since it's a custom input. The rest of the form is not WC specific i.e. it's a comment form generated by WP and/or the theme. The review itself has a `required` attribute which means browser based validation will prevent empty submissions.

On top of that, there is the standard PHP based validation ran after submission.

With those in place, adding extra JS validation on top is not something I feel we should add to WC itself. There is a risk this could conflict with validation added by themes and plugins.

Thanks
