### ISSUE TITLE
Checkout Button Missing when checking out with cart

### ISSUE THREAD

**Issue by zinerunner** [woocommerce/woocommerce#22640]
**Describe the bug**
When using checkout through the cart, there is space to fill out all required information, but no "checkout" button to further proceed with the transaction. The Paypal Buy Now button works fine but the cart can't be used for checking out.

**To Reproduce**
installed Woocommerce with all default settings.

**Expected behavior**
Expected there to be a checkout button.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Are you perhaps using the PayPal Checkout extension? If so, PayPal deployed a change on Friday that caused it stop working in certain instances. Our extensions team released an update yesterday which works around the issue. Please update to the latest version.

Also in the future be sure to contact support instead of using Github as we only deal with WooCommerce core issues on here.

Let me know if you do not come right after updating and I can reopen and look into it further.
