### ISSUE TITLE
Order details page not displaying variation/attribute name

### ISSUE THREAD

**Issue by db123v** [woocommerce/woocommerce#22670]
I have a variable product setup. When a customer places an order, they are able to see the variations and it all works fine, however when i view the order in the orders page on the dashboard, the variation names are not displayed instead a variation id is displayed.

1. Place an order of a product which is a variable product.
2. Go to the orders menu page on the dashboard.
3. Click on the relevant order you placed.
4. The order details page will be displayed.
5. On the order details page under the product that you purchased, you will see the issue that i am referring to.

Please see attached screenshot.

**Expected behavior**
I was expecting the variation name to be displayed.

I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
This bug happens with a default WordPress theme active.
I can reproduce this bug consistently using the steps above.

Please see attached system status report screenshots.

Thank You

![status capture 1](https://user-images.githubusercontent.com/36286515/52313168-9256b280-2a01-11e9-9b60-e29724547984.png)
![status capture 2](https://user-images.githubusercontent.com/36286515/52313169-92ef4900-2a01-11e9-805e-1dd6ef7de8ee.png)
![status capture 3](https://user-images.githubusercontent.com/36286515/52313170-92ef4900-2a01-11e9-9f70-dfd1f7d27423.png)
![status capture 4](https://user-images.githubusercontent.com/36286515/52313171-9387df80-2a01-11e9-915c-2f8dadb1849a.png)
![status capture 5](https://user-images.githubusercontent.com/36286515/52313173-9387df80-2a01-11e9-815f-d8740cbd6d51.png)
![status capture 6](https://user-images.githubusercontent.com/36286515/52313174-94207600-2a01-11e9-85bb-76b93f2cfae8.png)
![status capture 7](https://user-images.githubusercontent.com/36286515/52313176-94207600-2a01-11e9-8052-5b91dcf34d89.png)
![status capture 8](https://user-images.githubusercontent.com/36286515/52313178-94b90c80-2a01-11e9-9883-5bfae025be15.png)
![status capture 9](https://user-images.githubusercontent.com/36286515/52313179-9551a300-2a01-11e9-8d9a-41b1e0274c71.png)
![status capture 10](https://user-images.githubusercontent.com/36286515/52313181-9551a300-2a01-11e9-8f3c-d91ebe4b5f54.png)

**Comment by rrennick** [comment]
Can you provide details on your variable product? Here's a screenshot of a new order I just created & the variation is included in the product name
<img width="820" alt="screen shot 2019-02-06 at 9 22 02 am" src="https://user-images.githubusercontent.com/343847/52344372-ec02b100-29f0-11e9-9f32-4e2cd7ab2102.png">

**Comment by db123v** [comment]
Hi, Please see attached images of product setup and order details page of working and not working.

As you can see in the working window which is an order that was placed through a POS that the Attribute and the relevant variation that was selected are displayed on the order details page, however in the not working screenshot which is an order that was placed through the web the attribute and variation is not displayed.
Your help with this would be highly appreciated.

![product setup 5](https://user-images.githubusercontent.com/36286515/52409117-9cbf9c00-2b28-11e9-868b-af3f688f72cb.png)
![product setup 4](https://user-images.githubusercontent.com/36286515/52409118-9d583280-2b28-11e9-8c90-b0aade58fb2d.png)
![product setup 3](https://user-images.githubusercontent.com/36286515/52409119-9df0c900-2b28-11e9-8e35-226a36fce265.png)
![product setup 2](https://user-images.githubusercontent.com/36286515/52409121-9df0c900-2b28-11e9-881d-4f87acfaf4d9.png)
![product setup 1](https://user-images.githubusercontent.com/36286515/52409124-9e895f80-2b28-11e9-8b21-2a55c43cc7ff.png)
![not working](https://user-images.githubusercontent.com/36286515/52409132-a5b06d80-2b28-11e9-8688-c75f2515db00.png)
![working](https://user-images.githubusercontent.com/36286515/52409134-a6490400-2b28-11e9-9f16-9956c0ce4a00.png)

Thanks

**Comment by mikejolley** [comment]
The selected weight is part of the product name (where possible) - we do this during cart/checkout and in admin to save space.

See the suffix on variation name is `- 250g`. This is expected behaviour.

**Comment by thurefransen** [comment]
Having the same issue... its actually been happening on several orders since the beginning of the year...

The issue is the "suffix" isn't being displayed on the order... I understand that is the "expected behavior" but its not working correctly. That's the issue.

![image](https://user-images.githubusercontent.com/16464449/57476952-aa8ad780-7265-11e9-895a-364c3a968eb3.png)

**Comment by reijerstevens** [comment]
I'm experiencing this issue also. Is this thread still open?

**Comment by JohnS0N2** [comment]
I am experiencing the same issue. Why was this thread closed :(

**Comment by MitchEff** [comment]
Yeah, this isn't working on our end either. @mikejolley can you re-open this?

**Comment by MitchEff** [comment]
FWIW I've tested this on 3.2.6 _and_ 3.8, bug is present in both. I tried digging through the source to see if I could spot the issue but there's too many hooks and filters and whatnot. 

Definitely an issue, seems to be applied randomly as some orders still have the variation name but most don't...

**Comment by JustinCAdams** [comment]
I'm experiencing this too since WooCommerce has been updated. Here is what all my new orders coming in look like via order details:
<img width="630" alt="Screen Shot 2019-12-09 at 11 22 43 AM" src="https://user-images.githubusercontent.com/58687881/70429942-f9a61e80-1a79-11ea-986c-66544fe105bc.png">

And here is what they looked like before:
<img width="635" alt="Screen Shot 2019-12-09 at 11 40 41 AM" src="https://user-images.githubusercontent.com/58687881/70429949-fdd23c00-1a79-11ea-8b84-3e75ff85915b.png">

This is also impacting the invoices and emails that go to customers - they are now only getting the product name and no longer any product variation information (e.g. size and color).

**Comment by dipakparmar** [comment]
Same issue can't see the attributes 
<img width="1140" alt="Screen Shot 2019-12-20 at 5 50 29 PM" src="https://user-images.githubusercontent.com/24366206/71301214-4aa6f400-2351-11ea-9816-ff15de6c39b5.png">

**Comment by JohnS0N2** [comment]
Hey who knows... maybe in this decade this will be looked at. We didn't have much luck in the previous one. Happy 2020!

**Comment by zvaigznux** [comment]
For me, this was because I'm writing all possible attribute names also in the product title. (Size)
And so there is a function "get_formatted_meta_data" in plugins/woocommerce/includes/class-wc-order-item.php
and on line 282 there is this code:
`			// Skip items with values already in the product details area of the product name.
			if ( ! $include_all && $product && $product->is_type( 'variation' ) && wc_is_attribute_in_product_name( $display_value, $order_item_name ) ) {
				continue;
			}`

Which tells if there is already an attribute name in the product title, then ignore returning this variation name. And you can't override it.

It would be nice that they could fix this issue :)

For a short-term solution, just comment out this part of code and you are good to go.

**Comment by zvaigznux** [comment]
> The selected weight is part of the product name (where possible) - we do this during cart/checkout and in admin to save space.
> 
> See the suffix on variation name is `- 250g`. This is expected behaviour.

Hey, mate if you read this check my comment above. 
I'm writing attribute names (sizes) already in the product title and I will never know or see which size has been chosen. (Example: Red Dress S, M, L . And my attributes are: Size = S | M | L ).
I would suggest improving or removing this code in plugins/woocommerce/includes/class-wc-order-item.php
and on line 282:
`// Skip items with values already in the product details area of the product name. if ( ! $include_all && $product && $product->is_type( 'variation' ) && wc_is_attribute_in_product_name( $display_value, $order_item_name ) ) { continue; }`

**Comment by POGgg42** [comment]
Why is this marked closed? It is clearly still an issue, we just encountered this today on a new launch. 
<img width="944" alt="Screen Shot 2020-04-24 at 12 09 42 PM" src="https://user-images.githubusercontent.com/46264600/80233482-8b2abd00-8624-11ea-9c49-77b133ecb917.png">

**Comment by Meloman-zz** [comment]
Same issue only for variations on some new products since last update to WP 5.5.1 / Woo 4.5.2 (PHP 7.4.10) ! very strange.

I flushed my LiteSpeed caches and today have seen some products are ok, maybe cause-and-effect relationship !?

**Comment by AmitAzran** [comment]
The same problem with me in some orders, how do you check what variation the customer has chosen after that? Do you contact them? Please fix this problem because I'm really worried when I get an order ..
![Capture1](https://user-images.githubusercontent.com/20659768/99183800-2c0ad200-2747-11eb-902c-781ae7c87de9.PNG)
