### ISSUE TITLE
Document about restrictions in WC_Order_Query regading to date_paid/date_completed and status

### ISSUE THREAD

**Issue by shakaran** [woocommerce/woocommerce#22688]
**Is your feature request related to a problem? Please describe.**
I was reading several times [this WC_Order_Query article](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query) in your wiki
because I am implenting a custom function which bring all the articles (post/subscriptions) for a given WC_Customer which match with only a certain type of product IDs, so this allow me identify kind of products and enable monthly/biannual/annual access to a given areas.

For that, I am bringing all the orders in status processing and completed. Since I only can match the query with ONLY one state, I have to write the same query two times

```
$args = array(
                'customer_id' => $id,
                'currency' => 'EUR',
                'orderby' => 'post_date', 
                'order' => 'ASC',
                'date_paid' => $to_date->timestamp . '...' . $from_date->timestamp,
                'status' => ['processing']
            );
            $query = new \WC_Order_Query( $args );
            $subscriptions_processing = $query->get_orders();
```

And for completed:

```
$args = array(
                'customer_id' => $id,
                'orderby' => 'post_date',
                'order' => 'ASC',
                'date_paid' => $to_date->timestamp . '...' . $from_date->timestamp,
                'status' => ['completed']
            );
            $query = new \WC_Order_Query( $args );
            $subscriptions_completed = $query->get_orders();
```

`$subscriptions = $subscriptions_completed + $subscriptions_processing;`

Which is my surprise, that I only was receiving always the processing and no completed in any place. So I have several days of hard debugging until I found the issue.

It seems that for "completed" status WC_Order the date_paid field is empty and it only has the date_completed filled with info. So my query was failing always, but after I modify only one word (see date_completed) I was very happy to see it working finally!

```
$args = array(
                'customer_id' => $id,
                'currency' => 'EUR',
                'orderby' => 'post_date', 
                'order' => 'ASC',
                'date_paid' => $to_date->timestamp . '...' . $from_date->timestamp,
                'status' => ['processing']
            );
            $query = new \WC_Order_Query( $args );
            $subscriptions_processing = $query->get_orders();

$args = array(
                'customer_id' => $id,
                'orderby' => 'post_date', 
                'order' => 'ASC',
                'date_completed' => $to_date->timestamp . '...' . $from_date->timestamp,
                'status' => ['completed']
            );
            $query = new \WC_Order_Query( $args );
            $subscriptions_completed = $query->get_orders();

            $subscriptions = $subscriptions_completed + $subscriptions_processing;
```

**Describe the solution you'd like**

I would like that someone with documentation experience will edit the wiki page, and add a good reference that if you use the date_X and some status, you need explicit use that, since are empty, because with the current status of the documentation, you cannot figure out that you will get empty fields given a status

**Comment by claudiulodro** [comment]
It sounds like a bug somewhere if there is `_date_completed` meta but no `_date_paid` meta for an order. Looking at the code, the logic looks correct to me: `date_paid` gets set when the order goes to either 'processing' or 'completed' status, and `date_completed` gets set when the order goes to 'completed' status.  

In my testing on a site with regular orders (not subscriptions) and no other plugins, the queries worked correctly. Even this one (which would save you a whole query) worked correctly:
```
$args = array(
                'date_paid' => time() - WEEK_IN_SECONDS . '...' . time(),
                'status' => ['completed', 'processing']
            );
```

Can you post the system status report and/or test on a site without a bunch of other plugins active? The bug could be either in the Subscriptions plugin, the payment gateway, or elsewhere.

**Comment by mikejolley** [comment]
I don't think this needs documentation specifically because as @claudiulodro pointed out, `date_paid` is indeed set for these orders. It's perfectly valid to include it in the query.

Date paid is set on payment events here:
https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/class-wc-order.php#L116

And here when missing: https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/class-wc-order.php#L291 when the status changes here https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/class-wc-order.php#L269

I'd suspect a gateway or plugin on your store is either bypassing the CRUD code above or doing something to avoid setting date_paid. Since this is working on other stores it would be a conflict.

The only thing I notice that could potentially be an issue from that line is if the filter woocommerce_payment_complete_order_status was used to prevent it setting date_paid when processing, and then used again to prevent it setting date_paid when completed. Whilst unlikely, I'm going to put in a patch to harden that.

**Comment by mikejolley** [comment]
Change that in https://github.com/woocommerce/woocommerce/pull/22735
