### ISSUE TITLE
Order - Postmeta - empty keys or duplicate values

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#22697]
When new order is created the postmeta table gets populated with duplicates or empty values as described below. Is this a bug or desired functionality?

An order with billing address filled in only, no "Ship to different address" checked. The postmeta table gets populated with billing and shipping postmeta values either. So it stores 2x more values. 1x - billing, 1x - shipping.

When you have a billing field for example billing_address_2 that is not required, only optional, or change anything to optional and an order is made. The row still exists for that order in postmeta with empty value.

Wouldn't it be better to not create those empty, duplicate values to save rows count in postmeta and thus loading speed with millions of records?

Thank you

**Comment by kloon** [comment]
This is intentional as when you leave out your shipping address it by default gets populated with your billing address. We store it so code that wants to retrieve a shipping address can reliably call the shipping address methods and get a valid shipping address.

Yes we can leave it out but then we need to add additional logic to use billing address when no shipping address is present and this can result in confusion in the codebase and methods used to retrieve the shipping address fields.

Just to note that there is no duplicate values, an order will always have a set of values that can be referenced so this needs to be saved, the only values that can be the same is shipping and billing addresses so not that much more values to save per order.

We have sites with 10+ million meta rows and they run fine performance wise, if you are having issues with performance due to the table size I would suggest you consult with your hosting company and have them look into implementing object caching as well as a master-slave DB setup for your site.
