### ISSUE TITLE
Extensions: Link extension Download button to my-account/downloads

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#22695]
The Download button on an extension on the wp-admin > WooCommerce > Extensions > WooCommerce.com Subscriptions page 1) doesn’t download the extension and 2) doesn’t point to a page where you can download the extension - it points to the product page instead.

When the merchant is connected to WooCommerce.com, it seems to me that an unexpired extension's Download button should link instead to https://woocommerce.com/my-account/downloads/

**Comment by kloon** [comment]
@allendav with what extensions did you test this? I just tested this against the master branch of WooCommerce and the download buttons link to the actual file download. Clicking the download button does download the file to my local drive.

![](http://cld.wthms.co/uS1xfU+)

**Comment by mikejolley** [comment]
Refers to this code block https://github.com/woocommerce/woocommerce/blob/b70fed6868bd4fdd2d5fb0a1bad58b7200527dee/includes/admin/helper/class-wc-helper.php#L166-L170

That logic should be tweaked to download if the package is found, even if installed.

**Comment by mikejolley** [comment]
@garymurray Is this something Alpha can modify? I could try but I'm not entirely sure if there are reasons for current behaviour.

**Comment by garymurray** [comment]
@kovshenin can you take a look here? cc @mattyza 

(I'm not on Alpha anymore)

**Comment by mikejolley** [comment]
Sorry :D 👍

**Comment by mikejolley** [comment]
@mattyza I did some more digging into this and it seems I'm actually not able to reproduce a problem.

The code I linked above sets the download URL to the correct URL if

a) the product is not installed locally
b) update data was returned from woo.com

The button/link is displayed in html-main.php and only shown if:

a) the product is not installed locally
b) the subscription has not expired.

The case reported (not installed locally) would only occur if _update data was not returned from woo.com_. Thats in `WC_Helper_Updater::get_update_data();`. 

That could be missing if the store was unable to hit woo.com API or request was blocked. Under this circumstance, since there is no update data its not actually possible to show a download link to the package, and thus it's falling back to the product page.

Therefore, the only 'solution' for this case (which seems an edge case) would be to link to the account page on woo.com instead of the product page, since thats where you can download extensions manually. I'll find that URL and send a patch.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23146
