### ISSUE TITLE
Hong Kong should be a state of China

### ISSUE THREAD

**Issue by qwqoffice** [woocommerce/woocommerce#22755]
**Describe the bug**
should not show in country list at least.

**Comment by kloon** [comment]
Hi @qwqoffice, everything I read online indicates that yes it is part of China but for the most part operates as an independent country with its own currency, legal and parliamentary system.

Since I don't know much around the situation apart from what I read online we definitely welcome feedback. Can you provide some more information as to why you would suggest it be added as a state of China? Links would help a lot.

Perhaps we can even look into adding it as a country as it is now, as well as a state of China? cc @woocommerce/proton

**Comment by DavidAnderson684** [comment]
> Perhaps we can even look into adding it as a country as it is now, as well as a state of China?

As an author of a plugin relating to taxes, this sounds like opening the door to unwanted complexity. e.g. Double-entries for Hong Kong everywhere in tax tables + reporting.

**Comment by kloon** [comment]
Closing this since I have not had any feedback and all sources online indicate that it operates as an independent country even though it forms part of China. Online stores I checked like Amazon also have Hong Kong listed as a separate country.

Can revisit this in the future if there is enough evidence to prove it should be included as a state of China.
