### ISSUE TITLE
Customer details changed to billing address after order

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#22765]
**Describe the bug**
Our current "My Account" page allows any user can change account names so there is no need to force it after checkout.

**To Reproduce**
1. View account details ( https://cld.wthms.co/fkrGMy )
2. Checkout using a different name for billing ( https://cld.wthms.co/bpzwgr ) 
3. Confirm name change with previous display name still stored ( https://cld.wthms.co/9MsTBr )

Customer update hook: https://github.com/woocommerce/woocommerce/commit/5bfb372f01b27e996f8c042db74ec386c7d599bb

**Expected behavior**
For shipping and billing details to remain independant to customer account details.

**Comment by mikejolley** [comment]
If they details were not updated it wouldn't remember the details for future checkouts. e.g. I update my address when placing an order. Then next time I'd have to make the same changes because my account was not updated.

Surely both should be kept in sync otherwise whats the point in having the address inside my account?

**Comment by kloon** [comment]
As Mike mentioned, this is intended behavior.  The addresses are updated with the last checked out addresses.

**Comment by johndcoy** [comment]
The user can make that change for future purchases on the My Account page, so forcing the decision isn't necessary, right? Looping in @claudiosanches

**Comment by claudiosanches** [comment]
> Surely both should be kept in sync otherwise whats the point in having the address inside my account?

The thing here is changing the account first name and last name, both should not sync with billing details, since you may using billing details from some family member or friend, and for sure you don't want your account get renamed with someone else names.

So let's fill account details only when is empty.

**Comment by claudiosanches** [comment]
See #22765
