### ISSUE TITLE
Product sorting issue

### ISSUE THREAD

**Issue by Pixelstart** [woocommerce/woocommerce#22798]
**Description**
The default sorting option (Products > Sorting) is not working as it should. After saving a product, it will move to the top of the sorting list, which makes the sorting absolutely useless. It happens on all my shops, so it's not a plugin/theme related issue.

**To Reproduce**
1. Go to 'Products > Sorting'
2. Sort the products in a way
3. Check the shop page to confirm the sorting
4. Go to a random product within wp-admin (not the one at top of the sorting)
5. Make a small change to the product and hit save/publish
6. The just saved product will be at top of the sorting list

**Expected behavior**
Saving products should not change the sorted products list. Saving products should be added at the bottom of the list.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
I tested this and it didn't happen. I made a short recording to prove it.

![2019-02-26 12 04 40](https://user-images.githubusercontent.com/90977/53411628-e3354780-39be-11e9-88f9-fd0e9c3c3ab7.gif)

Confirmed menu_order is set in the database, and confirmed it's stored correctly after save.

The only way I can think of this happening is that before save, none of the other products had a menu order, or were all 0. 

> It happens on all my shops, so it's not a plugin/theme related issue.

Not sure how true this is of course, and without status I have no way of checking. Let me know if you can recreate this consistently on a clean install and how, beyond what I showed above.

Thanks

**Comment by pdobrescu** [comment]
Hi @mikejolley,

I'm coming back on this issue with the request to re-open it. Here's some more information about the issue:
- it can be replicated in 100% of the cases on our hosting platform ([Presslabs](https://www.presslabs.com), with Storefront theme and only WooCommerce active
- after a lot of debugging, we identified that the issue comes from the way the plugin handles the object caching (we use memcached on all sites)
- we have tried several memcached implementations, with no real success
- the issue happens in the [product_ordering](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L1735) function, either here (when the actual update is done):

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L1778

or here, where maybe some other functions hook and do things that affect the object cache saving:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L1780

We tried hooking in the same place as above, with triggering a `wp_cache_flush();`, but it doesn't do the trick. However, adding `wp_cache_flush();` on line 1781, right after the `do_action` and before the `wp_send_json` seems to solve this issue. 

And just to clarify: the storage of the `menu_order` in the DB is correct, but after a product gets edited (for anything else than the actual order), another value reaches the DB, most probably because that value is fetched from the object cache, where it wasn't properly refreshed after the `$wpdb->update` on line 1778 or maybe some other function that gets hooked on the `do_action` from line 1780.

Any further ideas or advice is much appreciated, we obviously cannot keep this fix directly in the plugin code, so we're looking for a permanent solution. Would you be able to get this tested with an object caching turned on? 

Thank you!

**Comment by mikejolley** [comment]
Cc @kloon
