### ISSUE TITLE
Woocommerce throwing major schema errors!

### ISSUE THREAD

**Issue by JimmyRaz** [woocommerce/woocommerce#22842]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Just go you any shop using the latest version of woocommerce an test it with googles structured data testing tool. 
2.
3.

## Expected/actual behavior

When I follow those steps, I see...  4 schema mark up errors on every product page and dozen on any shop of category page.

I was expecting to see...
None,  You do not even have a markup for the Sku or the review, 
## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by JimmyRaz** [comment]
Guys,

Your shopping cart has just started throwing off 4 schema errors per product. On category pages it is adding up to dozens.

How could you not know this?

Google started picking this up weeks ago.

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fproduct%2Fninja-silhouette%2F

warning: brand
The brand field is recommended. Please provide a value if available.
warning: description
The description field is recommended. Please provide a value if available.
warning: image
The image field is recommended. Please provide a value if available.
warning: sku
The sku field is recommended. Please provide a value if available.

YOU DO NOT EVEN HAVE A STRUCTURED DATA FIELD FOR THE REVIEW.

Look at this on the shop page.

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fshop%2F

What is going on here?

**Comment by karinwerner** [comment]
Also causing Product schema issues for a property type of availability.

**Comment by galbaras** [comment]
Just to clarify, this only happens on archive pages. On single product pages, things seem to be OK. See [here](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fproduct%2Flowepro-slingshot-edge-250-aw%2F)

Also, it’s not a new thing, so it doesn’t see like 3.5.5 has changed anything in schema output.

See also [respective forum thread](https://wordpress.org/support/topic/woocommerce-throwing-major-schema-errors/).

**Comment by btrfabrications** [comment]
+1 on these issues, though it's not just archive pages.

**Comment by TimBHowe** [comment]
Hey Everybody,

We have also run into the same issue with some client sites where the brand, description, product image and SKU have been absent from the shop and product category pages.

Also due to recent update to [Google Search Console](https://webmasters.googleblog.com/2019/02/help-customers-discover-your-products.html) we have started receiving an error message for the same pages that reads `Either "offers", "review", or "aggregateRating" should be specified` due to the absent of product prices and ratings being added to the schema markup.

It appears in the [WC_Structured_Data](https://github.com/woocommerce/woocommerce/blob/b65f93c756c5bec185c5d5f374dcafb9bc0cb87b/includes/class-wc-structured-data.php) class when it is generating the product structured data there is the [`woocommerce_structured_data_product_limit`](https://github.com/woocommerce/woocommerce/blob/b65f93c756c5bec185c5d5f374dcafb9bc0cb87b/includes/class-wc-structured-data.php#L206) filter that checks if it is generating the product data for a product taxonomy page or the main shopping page that will then exit the process at that point and only return the `@type`, `@id`, `name` and `URL` for the product.

It appears the filter is used to add the product URL to the schema markup for the pages where products where index and those pages only. While also limiting the information sent.

I would suggest that they remove the return from the filter letting it send the additional information to the product index pages. I will submit a PR that does just that.

In the mean time user can use the `woocommerce_structured_data_product_limit` filter to allow it to skip the return and add all the data, and then use the `woocommerce_structured_data_product_offer` to arr the product URL meta data to the product index pages where applicable.

Or use the `woocommerce_structured_data_product_limited` filter to add the additional brand, description, product image and SKU as mentioned, or even the offers, aggregateOffers, or aggregateRating to the product index pages.

Hopefully this helps.

Resources
https://webmasters.googleblog.com/2019/02/help-customers-discover-your-products.html
https://developers.google.com/search/docs/data-types/product

**Comment by claudiosanches** [comment]
For most of the fields I can see only warnings and not errors or major errors like the title describes:

![screenshot from 2019-02-25 15-41-35](https://user-images.githubusercontent.com/1264099/53360277-de678980-3913-11e9-8ace-49e5c3c29cde.png)

> The description field is _recommended_. **Please provide a value if available**.

So again, this doesn't sound like a major error or something like that.
Also we can't include all fields in archives, there's performance implications on it too.

I'm going to stop a few of those warnings, but not that some of those may still show, since you need some custom thing to fill `brand`, also not all products have `sku`.

**Comment by claudiosanches** [comment]
Also possible use this snippet if you like to patch it right now:

```php
add_filter( 'woocommerce_structured_data_product_limited', function( $markup, $product ) {
	$markup['image']       = wp_get_attachment_url( $product->get_image_id() );
	$markup['description'] = wp_strip_all_tags( do_shortcode( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) );
	$markup['sku']         = $product->get_sku();
	$markup['brand']       = '';

	return $markup;
}, 10, 2 );
```

**Comment by JimmyRaz** [comment]
Claudios,
 
Many people are also getting errors in these fields.
warning: offer Count	
The offer: Count field is recommended. Please provide a value if available.
warning: aggregateRating	
The aggregate Rating field is recommended. Please provide a value if available.
warning: brand	
The brand field is recommended. Please provide a value if available.
warning: review	
The review field is recommended. Please provide a value if available.

What happened here?  Why has this just popped up over the last couple of weeks?  

These "Warnings' are being considered errors in google search console and will have an impact in search ranking.  I included a screenshot.

**Comment by btrfabrications** [comment]
@JimmyRaz as per the following post, the 'Products' report in Search Console is new, that's why the errors/warnings weren't shown previously:
https://webmasters.googleblog.com/2019/02/help-customers-discover-your-products.html

@claudiosanches 
 - What 'custom code' is needed for the brand attribute?
 - For the non-programmers (me), where do we put that snippet you provided?
 - What magnitude are the performance implications of filling all fields?

@JimmyRaz and @claudiosanches 
 - Has Google directly said that these warnings and/or errors will/won't affect ranking?

Thanks!

**Comment by JimmyRaz** [comment]
@btrfabrications 

If google is calling it an error in search console it is wise to get it fixed quickly.  I posted a screen shot of that. 

However, If these are some new fields that have been recently added then Google will most likely give developers time to get the proper fields added.  

Thanks for the information.

**Comment by btrfabrications** [comment]
@JimmyRaz 
I wouldn't worry _too_ much - remember 404s are still called 'crawl errors', but they do no direct harm to your ranking. As with most benign issues, I'm confident Google's algorithm will re-crawl the offending pages a few times before taking any action. I was just wondering if google had given any specific information on these factors. However, like you I really want to have all items fixed, regardless of whether they're called an error or a warning - certainly neither are helping search performance! 

I think the report only went live on the 22nd, though the change was actually made in google's algorithm/crawling around 2 weeks ago. I received an email notification from Search Console on the 24th, though the review/offers/aggregaterating error was first detected on the 14th, for my site. So I think it's only been a few days, rather than weeks, that the errors/warnings have been visible.

Thanks

**Comment by btrfabrications** [comment]
@claudiosanches Just implemented the code snippet (with help from Automattic support - seems to be working fine, except the brand attribute, as you mentioned.

For anyone who doesn't know, the code goes in the functions.php file.

**Comment by davemktg** [comment]
Hi! thanks for this snippet. I have a question about it: I have the products brand as product attribute, how can I recall it? 
Furthermore this snippet fix the warnings, but how can we fix the "offers, reviw and aggregateRating" error? 
Among other things, for me it's even more strange because I use woocommerce as a catalog with the possibility to request quotes.

thanks

**Comment by AmeliaAkh** [comment]
This snippet does not fix the error of offers, review and aggregateRating if you do live test in google search console, the problem stays the same

**Comment by AmeliaAkh** [comment]
Thanks for the snippet:) but the error "offers, review and aggregateRating" is still there. Is it possible to disable schema markup for product archive pages? Maybe Woocommerce will fix it with a new update?

**Comment by Lando-RoHe** [comment]
Oh nice, there is something going on. One of the problems seems to get fixed... will try it tomorrow.

But two questions remain:
1) What about the archive pages that throw an error cause offers, review and/or aggregateRating is missing? Archive pages are relevant to SEO too.
2) When will an official fix be included in a WC-update? Hey, it's OK to work with a workaround for some time. But this is not the final solution of WCs markup problem.

**Comment by TimBHowe** [comment]
@btrfabrications it sounds like a caching issue. You might want to try clearing the cache, and they you can submit a few URLs in Search Console to with the [Fetch as Google tool](https://support.google.com/webmasters/answer/6066468?hl=en) to test a few URLs. Also the [crawling](https://support.google.com/webmasters/answer/6065812?hl=en) can take anywhere from a few days to a few weeks to re-crawl a site. Be patient and monitor progress using either the Index Status report or the [URL Inspection tool](https://support.google.com/webmasters/answer/9012289).

As for the Brand name in the snippet it was left blank as there is no product brand field in WooCommerce core and it can't be assumed. You can set it as a static brand name in the function to use for all products, but as it is only a warning it may be better to leave it blank then give it false information.

@davemktg In your case since you have the custom product metadata with a brand name value you should be able to get it from the product object, but it depends how and where it is stored. Most-likely you can use something like `$markup['brand'] = wp_strip_all_tags( get_post_meta( $product->ID, '_product_brand_name', true ) );`. Replacing the `_product_brand_name` with the metakey that the data is saved under. If you are not sure where that is or how to find it I would suggest consulting a developer to help you look into it deeper.

@AmeliaAkh and @Lando-RoHe it looks like it is planed to be fixed with the next release WooCommerce 3.5.6 release. In the mean time you can try adding the following snippet to your themes function file.
```php
/**
 * Filter the woocommerce_structured_data_product_limit if statment to always add the full structure.
 *
 * @param  boolean $is_archive_page returns true or false based on is_product_taxonomy() || is_shop() WooCommerce Conditionals.
 * @return boolean                  Return false to force the function to continue and not limit the product data on the archvie page.
 */
function wc_unlimit_product_structed_data( $is_archive_page ) {
	return false;
}
add_filter( 'woocommerce_structured_data_product_limit', 'wc_unlimit_product_structed_data', 10, 1 );

/**
 * Add items to the product schema markup.
 *
 * @param array      $markup  Array of the product scheme markup.
 * @param WC_Product $product Product data (default: null).
 * @return array              Altered $markup.
 */
function wc_add_product_structed_data( $markup, $product ) {
	// Add the brand to the product schema markup.
	$markup['brand'] = '';

	// If is it a product archive page add the URL to the product schema markup.
	if ( is_product_taxonomy() || is_shop() ) {
		$markup['url'] = get_permalink( $product->get_id() );
	}

	return $markup;
}
add_filter( 'woocommerce_structured_data_product', 'wc_add_product_structed_data', 10, 2 );
```

Hope this helps

**Comment by btrfabrications** [comment]
@TimBHowe Thanks for your help. Would be interested to try @davemktg solution for brand, but sounds like I'll need some help with that!

**Comment by galbaras** [comment]
Before everybody gets too excited, remember the possible performance impact on index/archive pages, where I'm not even sure we want product markup that competes with individual product pages for search placement.

You can open the champagne after the PR has been full tested and approved for inclusion.

While we're at it, @TimBHowe and @claudiosanches , perhaps a default setting for "brand" can be introduced into core and used in schema markup, given how useful it is for product feeds as well?

**Comment by AmeliaAkh** [comment]
With the code it becomes warning instead of error. Does someone know how to disable product schema markup on archive pages only? Is it better to disable woocommerce schema markup completely and markup with a schema plugin? Nobody recommends to markup product archive pages as products for SEO.

**Comment by marksda1** [comment]
Not remotely my area of expertise but I started getting error messages via email today from Google for my sites and found my way here. Using the code up above "fixed" it but I am wondering if it's the right fix. Looking at the equivalent of archives on some other major shopping sites, I see they have theirs set up as 

> @context":"http://schema.org","@type":"ItemList","itemListElement":[{"@type":"ListItem","position":1

So I'm thinking maybe the archive pages should be handled that way instead of as it is:

> @context":"https:\/\/schema.org\/","@graph":[{"@type":"Product","@id

Maybe this needs to be looked at a bit more first... I"m not sure if one way is preferable to the other but if it is, I'd sure like the correct way to be implemented.

**Comment by karinwerner** [comment]
I currently am getting zero errors or warnings after applying the following:
1.) Adjusted woocommerce/includes/class-wc-structured-data.php
So that brand, AggregateRating, reviews, (in my case) sku, priceValidUntil, availability, url and a few others show up in the Product Structured data.
2.) Switched out the description WooCommerce was pulling with what was fed to Yoast. Since our short description did not fit this scenario.
3.) Added the  Microdata for the same items I added in (1) above in the child templates. In my case; price.php and content-single-product.php

**Comment by JimmyRaz** [comment]
@galbaras  Interesting point.  Does Google really put any value in having the markups on shop pages? If the products are listed on the page then there may be some value in it.  I would like to know the answer.

**Comment by galbaras** [comment]
From what I know, category pages should be optimised for keywords that are common to all the products, like "smartphone", while product pages should be more specific, e.g. "iPhone 8 Plus".

When showing a product page in search results, Google uses the product markup to display the price, ratings, etc. For a category page, which one can it show? So it shows none.

Compare the search "iphone 8 plus site:apple.com" to "iphone site:apple.com" and you'll see what I mean.

**Comment by ronikbhauryal** [comment]
> For most of the fields I can see only warnings and not errors or major errors like the title describes:
> 
> ![screenshot from 2019-02-25 15-41-35](https://user-images.githubusercontent.com/1264099/53360277-de678980-3913-11e9-8ace-49e5c3c29cde.png)
> 
> > The description field is _recommended_. **Please provide a value if available**.
> 
> So again, this doesn't sound like a major error or something like that.
> Also we can't include all fields in archives, there's performance implications on it too.
> 
> I'm going to stop a few of those warnings, but not that some of those may still show, since you need some custom code to fill `brand`, also not all products have `sku`.

where to put this code on wordpress please tell me the file name i m not a deveoper thats why asking

**Comment by waqarabro** [comment]
Hello Guys, I have the same error on my all products. I will highly appreciate if somebody could help me. 

Please take a look at the images i have attached here. I have different errors. I tried to test in Google Structured Data and found 4 to 5 errors. I am not a developer but i will be highly thankful if i am helped. 

Just list down what i need to do to fix this mess. Its stressing and upsetting  thx 

![1](https://user-images.githubusercontent.com/48058072/53493744-e82cf080-3abd-11e9-9f3e-382425c30e65.png)
![2](https://user-images.githubusercontent.com/48058072/53493751-ebc07780-3abd-11e9-97f0-9378fff95e34.png)
![3](https://user-images.githubusercontent.com/48058072/53493753-ec590e00-3abd-11e9-9438-f7421483f2e4.png)

**Comment by mikejolley** [comment]
@galbaras Are you proposing removing all schema markup from archives?

The performance impact is negligible for the PR I merged - the variation price logic is still not ran.

**Comment by galbaras** [comment]
At this point, it seems to be a better option to me, if only to make the page slightly faster and slightly smaller, with a slightly better text to HTML ratio, all of which are good for SEO, while apparently losing nothing.

However, it may be good to keep scratching our heads for a bit before releasing a change.

Google Search Console is spooking people with a new report, but it also fails miserably to detect mobile friendliness on Australian sites, because it fails to get their stylesheets and scripts. We can't rush to make changes over new features from Google, which may very well be toned down with some feedback.

So far, I've sent them feedback on mobile friendliness. Let's do that about schema markup, because they don't seem too consistent with their own documentation at the moment.

**Comment by mikejolley** [comment]
@claudiosanches @timmyc Can we flag this in dev chat? I wouldn't mind killing that on archives if it's not useful as it would indeed boost performance.

Otherwise I still feel we should leave the PR in place. It takes care of some notices and doesn't impact performance any more than schema generation already does.

**Comment by waqarabro** [comment]
> I currently am getting zero errors or warnings after applying the following:
> 1.) Adjusted woocommerce/includes/class-wc-structured-data.php
> So that brand, AggregateRating, reviews, (in my case) sku, priceValidUntil, availability, url and a few others show up in the Product Structured data.
> 2.) Switched out the description WooCommerce was pulling with what was fed to Yoast. Since our short description did not fit this scenario.
> 3.) Added the Microdata for the same items I added in (1) above in the child templates. In my case; price.php and content-single-product.php

Can you guide me this process?  
Which line i should edit or add in structured data php file? 
2. how you switched out? 
3. which microdata you added?

**Comment by JohnDost** [comment]
I am having the same issue and also I am facing this as well Missing field "name" which didn't exist till February 14th

**Comment by waqarabro** [comment]
> I am having the same issue and also I am facing this as well Missing field "name" which didn't exist till February 14th
> I am also getting several warnings
> For the review I knew it would happen as I have product reviews closed as my employer doesn’t want it active but for the other issues it makes no sense.
> 
> Warning	Missing field “brand”
> Warning	Missing product ID
> Warning	Missing field “aggregateRating”
> Warning	Missing field “review”
> Warning	Missing field “description”
> Warning	Missing field “sku”
> Warning	Missing field “image”
> Warning	Missing field “priceValidUntil”

This thread has been closed. Please post queries here thx https://github.com/woocommerce/woocommerce/issues/22896

**Comment by OnlineLogoMaker** [comment]
Same here, I have 6000 pages for my shop with errors, ranking also dropping because of that...  I contacted support and they said they will release a patch soon to fix the issue.

**Comment by AmeliaAkh** [comment]
@OnlineLogoMaker 
Yes, mine too, I thought it was very strange how since 14 or 15.02 it started to happen. Will this take long? Is it possible to get someone to fix this issue, a developer? Because if it will take very long for woocommerce to fix it's better to hire a developer to do this. My archive pages and my products have very good SEO, I worked on it a lot. Is there a possibility to disable schema markup for archive pages, will it be fixed. What would be the best option?

**Comment by waqarabro** [comment]
> @OnlineLogoMaker
> Yes, mine too, I thought it was very strange how since 14 or 15.02 it started to happen. Will this take long? Is it possible to get someone to fix this issue, a developer? Because if it will take very long for woocommerce to fix it's better to hire a developer to do this. My archive pages and my products have very good SEO, I worked on it a lot. Is there a possibility to disable schema markup for archive pages, will it be fixed. What would be the best option?

I have the same story. Worked like hell to rank but now these error make my site down btw
This thread has been closed. Please post queries here thx #22896

**Comment by mikejolley** [comment]
Replying in #22896
