### ISSUE TITLE
PayPal Standard: can products send as individual line items if tax is included?

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#22864]
Currently with PayPal Standard, products are sent as individual line items only if either `wc_tax_enabled() == false` or `wc_prices_include_tax() == false`). 

Question: Is it possible to show prices in WooCommerce _including_ tax and get the summarized list in the PayPal after placing the order _including taxes_ and showing all products lined up? 

What are the ramifications of changing this code? 

I'm asking on behalf of a customer whose store is in Germany where it is standard to show prices including tax, yet the PayPal summaries are always showing items excluding tax because they want to display all line items and this confuses the customers. Currently, if they choose to include taxes in the prices in WC, items will not be sent to PayPal as individual line items, and customers can only see one line in the PayPal summary.

TIA!

**Comment by mikejolley** [comment]
It won't be possible. We have a filter to force the opposite (woocommerce_paypal_force_one_line_item) however, doing what this customer wants will cause issues.

The main problem is that PayPal does not support prices inclusive of tax if you're sending taxes. 

- If you send prices including tax, and the tax total, it will error due to mismatch of grand total
- If you send prices including tax, and skip sending the tax total, it will show 'tax = 0' on the PayPal site and in reporting 

Thats why to get around this, WC sends the order as 1 line item - to avoid mismatches which would lead to the customer not being able to make a payment.

`woocommerce_paypal_args` filter can be used to implement their own logic and replace all line items.
