### ISSUE TITLE
Nonce verification failed

### ISSUE THREAD

**Issue by DastanIqbal** [woocommerce/woocommerce#22876]
Hi I am getting this Nonce verfication failed, all api's working fine, I am only facing issue when signing up new customer, existing customer can login with no issue , Just only sign up. seeking some help to resolve this issue. 
 
**Request**
https://www.example.com/wp-json/wc/v2/customers?consumer_key=ck_consumer_key&consumer_secret=cs_consumer_secret

**Body**
{"email":"john.doe@example.com","first_name":"John","last_name":"Doe","username":"john.doe","password":"Pas$w0rd","billing":{"first_name":"John","last_name":"Doe","company":"","address_1":"969 Market","address_2":"","city":"San Francisco","state":"CA","postcode":"94103","country":"US","email":"john.doe@example.com","phone":"(555) 555-5555"},"shipping":{"first_name":"John","last_name":"Doe","company":"","address_1":"969 Market","address_2":"","city":"San Francisco","state":"CA","postcode":"94103","country":"US"}}

**Response**:
{"code":"nonce_verification_failed","message":"Nonce verification failed","data":{"status":400}}

**Comment by mikejolley** [comment]
This is working my end.

![insomnia wc rest api - products 2019-02-27 10-43-14](https://user-images.githubusercontent.com/90977/53484779-813b1780-3a7c-11e9-8a30-1dc9472423e5.png)

What I think may be happening is a plugin is injecting validation logic, checking for a nonce. You need to identify which plugin is responsible and ask the author to exclude REST API requests from the validation since no nonce is sent with API requests.

Thanks

**Comment by DastanIqbal** [comment]
@thanks Mike, that I am trying to to figure out which plugin, if you got any tips then please comment.
