### ISSUE TITLE
WooComerce WP REST API doesn't support custom endpoints

### ISSUE THREAD

**Issue by smgom** [woocommerce/woocommerce#22974]
I am trying to extend WooCommerce REST API to support custom endpoints but the custom created endpoints is not working on wp-json endpoints. I am also suplying API credentials that are consumer key and consumer secret.

So this URL is not working for custom route :
test.com/wp-json/wc/v3/notify

But the legacy endpoint works for custom route :
test.com/wc-api/v3/notify

This is the code that I am using
```
add_action( 'woocommerce_api_loaded', 'load_Custom_endpoint',10 );

function load_Custom_endpoint() { 
		require_once UPS_PLUGIN_PATH . '/inc/custom-endpoints/class-wc-api-notify.php';
		add_filter( 'woocommerce_api_classes', array($this,'add_to_api_class'),10,1 ); 
}
function add_to_api_class( $classes ){
		 $classes[] = 'WC_API_Notify';
		 return $classes;
} 

class WC_API_Notify extends WC_API_Resource {
	protected $base = '/notify';
	public function register_routes( $routes ) {
		$routes[ $this->base ] = array(
			array( array( $this, 'get_notify' ),WC_API_SERVER::READABLE )
		);
		return $routes;
	}
	public function get_notify() {
		echo json_encode(array( 'notify' => 'Data' ));die;
	}
} 

```

**Comment by mikejolley** [comment]
You need to register the routes - core only takes care of it's own.

Use the `rest_api_init` action hook. See how we do it here https://github.com/woocommerce/woocommerce/blob/7a1536eb5b3f8c4f9027a383fcd2aa499c6479aa/includes/class-wc-api.php#L245-L351

`woocommerce_api_classes` is legacy only.

Please also note, since your new endpoint isn't actually part of WC Rest API, you could consider your own route/base. e.g. `wp-json/wc-notify/v1`

Best of luck.
