### ISSUE TITLE
Review contact form not working

### ISSUE THREAD

**Issue by mafa89** [woocommerce/woocommerce#22995]
Hello, I'm using
WordPress 5.0.3
Avada 5.8.2
WooCommerce 3.5.4

I created a store, having few simple products with review enabled by any user. From the front end I see the products and, when I open one, I see the form to send reviews. However, filling this form and sending it does not work. It looks like the review is "lost".
P.S. on the same website, comments to the blog posts are working.

Things checked:
- different browsers
- registered/unregistered users experience same problem
- plugin incompatibilities
- reviews option is enabled on all products
- browser inspector does not show errors

I understand you might need more details. Please let me know what to provide/check.
Thanks

**Comment by mikejolley** [comment]
What about the theme? Tried default?

The form here shows what details we need to reproduce an issue https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=

This issue however seems specific to your site rather than a reproducable bug.

I'd suggest:

- Ruling out the theme
- Disabling all plugins bar WooCommerce
- Ensuring the hosting has no caching or spam protection active which could block new comments coming in
- If you have access, you can post to the support desk for advice and share details there.

If you want to test comment functionality on a different install, you can setup a temporary test site on https://jurassic.ninja/ :)

Let us know what you find. For now I'm closing this as non-reproducable.
