### ISSUE TITLE
/wp-json/wc/v3/products/categories/ takes on avarage 13,2 seconds

### ISSUE THREAD

**Issue by yulumadavid** [woocommerce/woocommerce#23017]
**Describe the bug**
Not 100% sure if this is a bug. But i've done some testing on this shop with 13k products and when we update product categories (/wp-json/wc/v3/products/categories/) it takes 22 minutes to update 100 categories which comes down to 13,2 seconds per call.

We have a Laravel application that pushes changes from this Point of Sales system trough the Woo REST API.

**Expected behavior**
Updating products is much much faster and takes max 4 seconds per call. Is it known that updating Woo Product Categories takes so long?

Any help would be appreciated. I would love to take the time to search for the exact numbers with microtime but only if this is not a known issue. Did take 20 min to search the web but could not found this precise situation/behavior.

**Comment by mikejolley** [comment]
Nothing stands out in the endpoint. Can you provide some sample calls? Are you only sending the fields you want to modify? Sending an image for example would be slow because it needs to fetch and upload the image.

**Comment by mikejolley** [comment]
I did some test requests and didn't encouter this issue - I only sent fields I as updating.

As I suspected earlier, I think it could happen if you sent all category fields, including images, rather than just the fields you want to modify, It is however impossible to verify this without example requests or confirmation from yourself.

If this is the case, the app making those requests could be modified to only send the changes and/or avoid sendnng `image`. Let me know if this isn't the case. For now I'm marking closed.

Thanks

**Comment by yulumadavid** [comment]
Hi @mikejolley 
thanx for you answer. We did a seperate test with Postman and the request took 500ms to the delay is not on the side of the Woo API.

**Comment by yulumadavid** [comment]
@mikejolley after some debuging we pinned it down. When we take a clean install with nothing in it postman responses within 0,2 sec. When we test the same call to update a category to our client site it takes up to 2,4 sec. I can imagine this could be caused by a trillion things within the total build of the site/theme etc. Could it be of any interest of the community to test this? We could create a staging env.

PS: site is stand-alone on a VPS solely for this client with 6 cores. CPU % is lower than 5% according to new relic. Amount of products: 13k, Categories: 255
