### ISSUE TITLE
quantity before/after

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#23029]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Stas0238** [comment]
I would like to have two hooks to have posibility to insert custom code inside div.quantity just before label and after input 
woocommerce/global/quantity-input.php.

**Comment by mikejolley** [comment]
In this case, it might not be neccessary.

1. You can override the template itself
2. There are hooks fired before/after the template itself is called. You can insert content before/after that way, you'd just need to wrap it in a new div if you wanted that html grouped a long with the qty input itself.
3. woocommerce_quantity_input function is pluggable

Otherwise propose a pull request to justify the additon.

Thanks

**Comment by Stas0238** [comment]
@mikejolley thanks
