### ISSUE TITLE
[REST API] Re-enable to get customers own orders in the REST API

### ISSUE THREAD

**Issue by diegopego86** [woocommerce/woocommerce#23086]
In the legacy api we were able to access a customer orders from the customers endpoint
https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#view-customer-orders.

Currently we can only retrieve orders from the orders API, which can return all the orders I don't want a user to be able to access the other orders just the ones he/she made.

Currently I can access a customer orders by using this endpoint:
/wp-json/wc/v3/orders?customers=12
To do this, I need to add to the user the capability read_private_shop_orders, which means he/she would be able to access all the other orders.

**Describe the solution you'd like**
It would be awesome to have an endpoint like:
/wp-json/wc/v3/customers/me/orders

That returns the orders from the current customer.

Or validate using the:
/wp-json/wc/v3/orders

Validate that if the current user has permissions to read_private_shop_orders then it returns all the orders, but if it only has permission to read_shop_order then return only the order from the current user.

**Additional context**
I'm creating a theme using ReactJS and JWT for Authentication. I'm creating custom Roles in the backend using the Capability Manager Enhanced (https://wordpress.org/plugins/capability-manager-enhanced/).  When Authenticated with JWT, the current user in wordpress becomes the JWT authenticated user.

**Comment by mikejolley** [comment]
The orders endpoint itself does allow filtering by customer (https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders) so it's unlikely we'll want to duplicate this functionality on the customers endpoint. They should be separate.

It's important to note, the REST API does not have fine grained access control. Users who can access the API should be **priviledged**, otherwise you risk leaking sensitive data to users who should not have access. Customers should certainly not have access to their data by the API unless you want to risk them updating order details themselves or gaining access to other endpoints such as settings...

I'd suggest extending the API if you need such an endpoint, or extending the orders endpoint to only return results for the current user. _I would not recommend you allow customers access to your store's API._ If you want a customer facing API, build it separate with it's own authentication system so there is zero risk to them accessing other store data endpoints.

Hope this makes sense.

**Comment by andreyberezhnoy** [comment]
@mikejolley are you planning to revise this? maybe in v4

**Comment by mikejolley** [comment]
@andreyberezhnoy Not the idea of running the API in a customer-based context, no, not yet.
