### ISSUE TITLE
Get orders paid within the current month not working correctly

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#23095]
I've tried to get all orders which are paid within the current month with this function:

`$orders = wc_get_orders( array( 'date_paid' => date( 'Y-m-01' ) . '...' . date( 'Y-m-t' ) ) );`

The output of the date_paid is following:

`2019-03-01...2019-03-31`

And these are the returned orders:

`object(WC_DateTime)#37886 (4) { ["utc_offset":protected]=> int(0) ["date"]=> string(26) "2019-03-14 22:41:09.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" } object(WC_DateTime)#37976 (4) { ["utc_offset":protected]=> int(0) ["date"]=> string(26) "2019-03-14 22:15:39.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" } object(WC_DateTime)#38013 (4) { ["utc_offset":protected]=> int(0) ["date"]=> string(26) "2019-03-14 20:34:20.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" } object(WC_DateTime)#38050 (4) { ["utc_offset":protected]=> int(0) ["date"]=> string(26) "2019-03-09 23:18:33.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" } object(WC_DateTime)#38090 (4) { ["utc_offset":protected]=> int(0) ["date"]=> string(26) "2019-02-28 14:34:06.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(13) "Europe/Berlin" }`

So there is an order from `2019-02-28` which seems to be not correct because the min is `2019-03-01`.

**Comment by mikejolley** [comment]
@Johnny99211 No that actually looks correct. You're looking at the UTC datetime. The actual date and time (based on your WordPress timezone) was 2019-03-09 23:18. The filtering uses the WP timezone settings to gather orders, so those results are all valid.

If you want to filter by UTC rather than the WordPress timezone, instead of providing a date such as `2019-03-01`, provide a numeric timestamp.

Hope that helps.
