### ISSUE TITLE
Unable to add product variants

### ISSUE THREAD

**Issue by Fazyyy** [woocommerce/woocommerce#23094]
**Describe the bug**
Infinite "loading" when clicking "Add variation".

Just a note- I have tried this with the shop-isle theme and the storefront theme with all plugins deactivated except for WooCommerce. I've also tried changing between every version of PHP that my host allows. 5.something up to 7.2

**To Reproduce**
1. Go to individual Product
2. Add Attributes
3. Go to Variations
4. Click "Go" with dropdown "Add Variation" selected

**Screenshots**
![Loading Icon](https://user-images.githubusercontent.com/16117981/54697201-12a22480-4b25-11e9-99b1-e27be5398037.png)

**Expected behavior**
Options to add details for product variant should appear

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

Home URL: |   | http://t2w.x10host.com
-- | -- | --
Site URL: |   | http://t2w.x10host.com
WooCommerce version: |   | 3.5.7
Log directory writable: |   | /public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by mikejolley** [comment]
The steps to reproduce only work on your site - this is working our end. You can test this on a temp site here https://jurassic.ninja/specialops/ if you want to confirm it's working for others and the issue is specific to your install.

It's likely a conflict with something on this store, or the hosting. 2 things you should look at:

- Browser inspector. View > Developer > Javascript console. See if there are errors shown when you add variation. This should give you an error message you can then resolve.
- DEBUG Log (https://codex.wordpress.org/Debugging_in_WordPress) or check the server error_log which can sometimes be found in `wp-content`. This may also give you an error message you can act on.

If you left WooCommerce related plugins on when testing, those would also need ruling out.

Otherwise you'll need to contact the helpdesk so someone can login and debug this for you. We cannot do this via Github because it's public and logins are sensitive.

Hope this helps you narrow down the issue. Let us know if you find anything or find an error message we can look at.
