### ISSUE TITLE
Dropdown "order by" is shown for one article

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#23126]
**Describe the bug**
Dropdown "order by" (function woocommerce_catalog_ordering) is shown although there is only one article in category

**To Reproduce**
create category for one product

**Expected behavior**
No ordering dropdown is shown

**Related**
It seems there was a fix in the past which got lost - see https://github.com/woocommerce/woocommerce/issues/12608, https://github.com/woocommerce/woocommerce/issues/2136

**WordPress Environment**
WP 5.1.1 with Woo 3.5.7, no other plugins

**Comment by mikejolley** [comment]
I'm unable to find the exact issue/commit this changed back but I recall it being intentional. Having consistent elements on all archive pages regardless of results makes it easier for themes to style output. The cost of checking if only showing a single result can also be expensive, and buggy, depending on context, and for this edge case (1 product in archive) doesn't seem worth it.

If you need to change the behavior, the template function which shows orderby.php is pluggable (`woocommerce_catalog_ordering` function).

Thanks
