### ISSUE TITLE
Admin screen headings

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#23185]
Consistency matters in interface design. Should admin page headings be present above the tabs?

Wordpress menu screen:

https://twitter.com/lutrov/status/1111648637036064769

Woocommerce settings screen:

https://twitter.com/lutrov/status/1111648829235879939

Which one is wrong?

**Comment by mikejolley** [comment]
With the absence of actual standards for WP admin screens provided by WordPress, neither is "wrong". It's likely the UI will diverge further as WooCommerce moves towards a react powered interface. I'm not sure if it's worth changing this at this point since because of the [wc-admin](https://woocommerce.wordpress.com/2018/10/18/wc-admin/) project, but I'll see what the design team think.

**Comment by kloon** [comment]
Closing out this issue for now. Don't think we will be spending time on this with the inclusion of wc-admin soon, so not worth the effort if this is all going to be replaced anyway in the near future.
