### ISSUE TITLE
update page when shipping method has been choose - woocommerce

### ISSUE THREAD

**Issue by amir0147** [woocommerce/woocommerce#23228]
hey guys i used this code to make shipping address disapper when local pickup is on
but the problem is that refresh ing is needed to update the content ( if any one know how to fix it i will be more than happy) 
and the second question: is it possible to auto refresh the page when you choose and shipping method?

**Comment by peterfabian** [comment]
Hi, 

I think your question is missing the code you used to hide the shipping address?
I think WC supports changing shipping method on cart or checkout pages, both update fragments of the page affected by the change I think. Do you want the whole page to reload or change? Maybe it would help to know what you're are actually trying to achieve instead of giving specific technical advice?

In addition, github is a channel to report bugs, not to ask support questions. For future reference, please use either support forum: https://wordpress.org/support/plugin/woocommerce/ or https://woocommerce.com/my-account/create-a-ticket/.

**Comment by amir0147** [comment]
> Hi,
> 
> I think your question is missing the code you used to hide the shipping address?
> I think WC supports changing shipping method on cart or checkout pages, both update fragments of the page affected by the change. Do you want the whole page to reload? Maybe it would help to know what you're are actually trying to achieve instead of giving specific technical advice?
> 
> In addition, github is a channel to report bugs, not to ask support questions. For future reference, please use either support forum: https://wordpress.org/support/plugin/woocommerce/ or https://woocommerce.com/my-account/create-a-ticket/.

oops sorry- https://businessbloomer.com/woocommerce-hide-shipping-local-pickup-selected/

i used this code
as i said, it worked but only if i refresh the page.
i thought if i will add refresh command (the whole page) the moment someone click on local / delivery it will do the job
