### ISSUE TITLE
Add new fields: Phone numbers

### ISSUE THREAD

**Issue by pretzelhands** [woocommerce/woocommerce#23279]
**Is your feature request related to a problem? Please describe.**

As part of the [new 3-D Secure standard](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) that is coming into force in Europe, there are a number of new parameters that should be sent to credit card acquirers. 

Some of these parameters relate to the tracking of a user's phone number. Currently there is only one field (`billing_phone`), whereas the standard proposes three separate ones (`mobile_phone`, `work_phone`, `home_phone`).

**Describe the solution you'd like**

It would be great to have a way to track the three different types of phone numbers within the default checkout workflow of WooCommerce so that full compliance with 3DS 2.0 can be ensured.

**Comment by mikejolley** [comment]
Similar to https://github.com/woocommerce/woocommerce/issues/23275 this would be overkill for the majority of stores.

Using the Amazon example again, it only has a single phone number field. Most customers I'm sure would only input the number they want to be contacted on, having extras is simply unnecessary. 

And again, this doesn't really block compliance if the fields are optional anyway.

If the gateway implementing 3ds wants to register these fields it can via the hook system, but I'd encourage you to allow them to be disabled in the settings because I cannot see these being desirable by store owners.

Thanks

cc @peterfabian
