### ISSUE TITLE
Moving metabox of post excerpt of product breaks the WP Editor.

### ISSUE THREAD

**Issue by lwxbr** [woocommerce/woocommerce#23282]
**Describe the bug**
When I move the metabox of post excerpt of the product, The editor stops the work.

**To Reproduce**
1. Go to Wordpress Dashboard
2. Click on 'Product' Menu.
3. Try to move the postexcerpt metabox.
4. See error: you can't type in editor.

**Screenshots**

**Expected behavior**
Move the metabox and WP Editor works normally.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
This is unfortunately a WordPress issue specific to TinyMce which we cannot workaround, unless we disable drag and drop or use a more basic version of the editor (https://wordpress.stackexchange.com/questions/49901/post-custom-metabox-textarea-using-wp-editor), both of which are not desirable. 

See trac ticket https://core.trac.wordpress.org/ticket/19173

Because of this, it won't be fixed on the WooCommerce side. For the future a new UI is being built for  WooCommerce (https://github.com/woocommerce/wc-admin) which will eventually include product screens. This won't have the issue :)

cc @peterfabian 

Thanks

**Comment by lwxbr** [comment]
Yes, it's not a WooCommerce issue. But the bug was opened 7 years ago. It's strange that it is untouched by core team. And now they want to push Gutenberg to us to use even with this kind of error in WP Editor.
