### ISSUE TITLE
"Show more comments" in Product reviews meta box may produce inconsistent results

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#23313]
**Description**

If a product has > 10 reviews, and a user clicks on the "Show more comments" link at the bottom of the "Reviews" meta box in the admin product edit screen page, the loaded reviews are repeated from the bottom of the list of comments/reviews, and it is not necessarily showing more reviews that weren't previously shown above.

**To Reproduce**

1. Have a product with more than 10 published reviews / comments
2. Go to the corresponding admin product page
3. Scroll down to the Reviews meta box
4. You will see the first 10 comments / reviews listed
5. Click on the "Show more comments" link at the bottom
6. Observe the new comments not matching the expected results
7. This is more noticeable when you actually have several more comments (e.g. 30, 40, 50...) as you may be prompted to click the same link more times until you get comments that have not been listed before

**Expected behavior**

The action link should only load additional comments / reviews that have not been shown already.

**Isolating the problem:**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
I've tracked this down to a core WP bug and logged it here https://core.trac.wordpress.org/ticket/46963#ticket

From our side, fixing would require adding a custom `comment` class or remaking the meta box. I don't think that is worth it, it would be better fixed in WP core since it affects all custom comment types, not just those from WooCommerce. Marking wontfix on our side. Monitor https://core.trac.wordpress.org/ticket/46963 for resolution.
