### ISSUE TITLE
Sale price not visible on Photos theme

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce#23426]
#### Steps to reproduce 

- Setup a product with sale price
- Activate `Photos` theme on the site. The theme is available [here](https://wordpress.com/theme/photos). Note that a self-hosted version of this theme is available as well.
- Visit the product.

#### What is expected 

The sale price is visible.

#### What happens instead 

The sale price is not visible. It appears in white.

<img width="725" alt="Screenshot 2019-04-22 at 18 15 13" src="https://user-images.githubusercontent.com/18581859/56500970-97200280-652a-11e9-8828-2a0ac9c14986.png">

I can see that this white color is caused by this CSS declaration: 

![Screen Shot 2019-04-22 at 18 19 22](https://user-images.githubusercontent.com/18581859/56501131-49f06080-652b-11e9-8030-cbc224a74af0.png)

#### Notes

I am not entirely sure if this should be a theme-specific bug report, or something handled by WooCommerce. The reason behind submitting this bug report on WooCommerce repository is because this sale price feature is not used on the theme otherwise. 

Happy to move to `Automattic/themes` should needs be. This theme is made by Automattic.

**Comment by kloon** [comment]
@arunsathiya not sure this is WooCommerce related, we do not set any color on <ins> and in your screenshot something changes it to white, by the looks it seems it might be coming from the theme stylesheet? Difficult to tell since the screenshot is cut off on the sides.

Closing for now, but will gladly reopen if there is more proof this is related to a CSS rule in WooCommerce core. Best would probably be to fix this in the theme since `<ins>` can be used in posts and pages as well which might give the same results on those pages.
