### ISSUE TITLE
wc_get_template issue

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#23448]
Since WooCommerce 3.6 the $args array passed to the function gets examined after a template has been located. Plugins passing the default_path to the template within the $args now fail. Despite the fact those plugins should pass any path information as third or fourth param to wc_get_template WooCommerce should fetch this issue in wc_doin_it_wrong. While it does with some parameters it does not with 'default_path'.

The payment gateway from Novalnet passes 'default_path' within the $args array, which now fails to load the template. The error message is:

Failed opening '/www/htdocs/wp-content/plugins/woocommerce/templates/render-redirect-form.php' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 249

The plugin author got informed about his bug but imho WooCommerce shoud fetch the default_path within wc_doing_it_wrong because this argument could be passed before WooCommerce 3.6

**Comment by mikejolley** [comment]
Hi @mensmaximus 

I understand what you're saying. 3.5 used an extract which would overwrite the actual passed `default_path` if something with the same name was passed in `args`.

If this was a supported and/or documented practice, I'd be with you - we could extract that still and use it with a notice.

However, this case is unique because

a) `$default_path` was a supported param in 3.5, it was not added in 3.6. Overwriting that is a bug. 
b) `$args` is documented as being what is passed to the template. It does not control which template should be loaded. That would also be a bug.
c) what if there are cases for `default_path` being passed to the template? Anyone doing that since 3.6 will also face breakage if this is reverted or handled with a doing it wrong.

Since this is a bug caused by Novalnet doing things in undocumented ways, ignoring the actual documented arguments, I don't think we should add a workaround for this case. The fix has to go in Novalnet. The fix in Novalnet would work in 3.5.x and 3.6.x because the handling of  `$default_path` remains unchanged.

cc @peterfabian 

Thanks

**Comment by mensmaximus** [comment]
Thank you for your explanation. I understand and agree. I have rewritten the faulty part in the Novalnet plugin, published instructions to the public on their wordpress support forum and sent it to the Novalnet developers to be included in their next update.
