### ISSUE TITLE
No Shipping options on checkout using WC 3.6.2

### ISSUE THREAD

**Issue by woocommercecodes** [woocommerce/woocommerce#23501]
PHP 7.2, WP 5.1.1 with WC 3.6.2
Fresh install, tried 10 different themes. This video explains it.

https://www.loom.com/share/b5405a05ba4c41a1bd10962d25d00368

**Comment by kloon** [comment]
Could you please provide a screenshot of your shipping settings? Because shipping is based on address details at the checkout page the way you have your shipping set up could determine what is shown there. You also have your address fields blank on checkout in the video so there could be no matches that is most likely why you are not seeing any options.

Checkout works from top down so customers will usually first enter their details before confirming the shipping, there is also no sense in showing then shipping options on checkout that is not available for their address as that will just throw an error when they try and place the order.

**Comment by woocommercecodes** [comment]
My apologies. I did not put in an address on the checkout page. Once I did, the shipping option became available. Personally I think that is the wrong of doing it considering the customer most likely want to have the shipping options available directly before filling in their address -- and especially so considering that many shops skips over the cart page making the process into a one-page version.

But to answer this "problem", yes -- it works.

**Comment by peterfabian** [comment]
@woocommercecodes 
Maybe you need to add in shipping zones for `Locations not covered by your other zones`? Shipping options are based on country/city/zip code, so it kind of makes sense some options are available only once you fill in some info.
You might find useful turning on Debug mode in WooCommerce > Settings > Shipping > Shipping options
