### ISSUE TITLE
Product ordering not working after upgrade to 3.6.2

### ISSUE THREAD

**Issue by david-strejc** [woocommerce/woocommerce#23527]
Product ordering stoped working in default shop view after upgrade to 3.6.2

**Comment by GlennMartin1** [comment]
I assume you're using Storefront?

A long-standing bug was corrected in WC 3.6.2, but requires Storefront to address the change. Storefront 2.5.0 will soon be released with a fix. See https://github.com/woocommerce/storefront/pull/1112.

**Comment by smallstar67** [comment]
Having the same issue after woo commerce update to 3.6.1 and 3.6.2. The filter to sort through products based on stock status does not function.   using Generate Press theme.

**Comment by claudiosanches** [comment]
Hello @smallstar67, can you please fill all the information:

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
</pre>

Are you using Storefront? If so, need to update, also have you tried to run the "Product lookup tables" tool? After triggering it should take a few minutes to conclude, you can check it in the "Scheduled Actions" tab.

**Comment by smallstar67** [comment]
**Describe the bug**
The filter to sort through products based on stock status does not function

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Products
2. Click on "Filter" - Products out of stock
3. Scroll down to N/A
4. See error:  Does not show products out of stock, shows all products, "in stock", "out of stock" and "back ordered".

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
When I press the filter to see products out of stock, I expect to only see products that are out of stock.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. (This is a live site turning off all plugins is not an option, this issue squarely began a moment we upgraded to the new woo commerce version 3.6.1 last week.  No other plugin have been changed or updated.)

- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).  (This is live site, we can not change up themes.)

- [ ] I can reproduce this bug consistently using the steps above.

**WordPress 5.1.1 WooCommerce: 3.6.2. Generate Press theme 1.8.1

**Comment by kloon** [comment]
@smallstar67 is this on the frontend? If so WooCommerce does not have sorting like out of stock, this is likely something in your theme? Can you please test this with Storefront or a default theme like Twentynineteen and let us know if you get the same results there?

As it stands I am unable to replicate this with the current version of WooCommerce and Storefront or Twentynineteen theme.

**Comment by smallstar67** [comment]
No this is on the back end, in products

*--HK Bowman *



*"What is the difference between genius and stupidity? Genius has limits."
- Albert Einstein. *

**Comment by kloon** [comment]
Possibly related to #23587 please test #23590 and see if that fixes the issue for you.

**Comment by bennyboyworld** [comment]
**Confirmed 2x bugs in WooCommerce Plugin 3.61 + 3.6.2** 

Bug 1) WooCommerce filtering order by select form on product archive (front end) not sorting correctly with stores with +20 products
e.g. URL: domain.com/shop/?orderby=price

Bug 2) WP Admin using the post type table sort by column "price" with stores with +20 products.
e.g. URL: domain.com/wp-admin/edit.php?post_type=product&orderby=price&order=asc

**Bug traced in: WooComerce Version 3.6.1 + 3.6.2**

**Resolved: by reverting to: 3.5.8**

Developers experiencing this issue can resolve by rolling back WooCommerce to version 3.5.8.

> Resolution tested on: WordPress Latest (version 5.2) + Storefront theme Latest (Version 2.5.0) + Only WooCommerce installed (Version 3.5.8)

> There isn't a plugin conflict. There's a WooCommerce plugin issue on release versions of 3.6.1 and 3.6.2.

> Note to WooCommerce fix developer: test on a store with > 20 products. The bug seems to affect stores with more than 20 products (i.e. it is sorting a sample of products not the entire product range)

Please can you release an update to WooCommerce v 3.6.2 to resolve the sort by issue? 

Thanks
Ben

**Comment by kloon** [comment]
@bennyboyworld Please see [this link](https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update), the issues you describe has been addressed already.

**Comment by bennyboyworld** [comment]
Yep that did it. The issue was still marked as open. Thanks for closing.

Tools > Scheduled Actions > Pending (click run next to each task).
