### ISSUE TITLE
Product tag

### ISSUE THREAD

**Issue by tjtommy** [woocommerce/woocommerce#23557]
when I go to product tag i see a list of all mine tags.
Behind a tag it show amount of products that has that tag.
When i click on the count of the products, then i don't see the products.
So i can't filter on product tags.

**Comment by claudiosanches** [comment]
I can't reproduce this issue with the steps you provided, it's working just fine.
Something missing?
Can you fill the bug report:

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
</pre>

Thanks.

**Comment by kloon** [comment]
Unable to replicate this, in the future when opening an issue please fill out the template provided when opening and test by disabling all plugins except WooCommerce and also with a default theme like Storefront or Twentyseventeen before opening.

Will gladly reopen when you can provide steps to replicate this with just WooCommerce and a default theme.
