### ISSUE TITLE
Strings from wp_print_media_templates at bottom of products table and categories

### ISSUE THREAD

**Issue by inonkp** [woocommerce/woocommerce#23574]
Description
On the bottom product categories page and edit products table, there are strings from wp_print_media_templates, such as "Maximum upload file size: 40 MB."

**Expected behavior**
No such prints.

- [x ] I have confirmed through placing error_logs that woocommerce is the initiator of the prints.

WP version version 5.1.1
WC version 3.6.2
PHP version 7.2.13

I am quite sure that the fault is on my own customizations of woocommerce but still would like to understand how exactly. screenshot lower left corner describes this.

![woocommerce_bug](https://user-images.githubusercontent.com/13364814/57019485-58c3cb00-6c2f-11e9-90e6-28579b655a14.PNG)

**Comment by rrennick** [comment]
> wp_print_media_templates, such as "Maximum upload file size: 40 MB."

That is a core WordPress template/message. Github is for reporting WooCommerce issues not support. 

For support contact https://woocommerce.com or the support forums https://wordpress.org/support/plugin/woocommerce . In this case, it's unlikely that your issue is specific to WooCommerce so you might be better posting your question in the general WP support forum https://wordpress.org/support/.

Closing the issue.
