### ISSUE TITLE
cash on delivery not working..

### ISSUE THREAD

**Issue by 007richboy** [woocommerce/woocommerce#23598]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by peterfabian** [comment]
Please fill in the template with information relevant to your problem.

**Comment by kloon** [comment]
Closing due to no feedback and missing information. I tested and COD works fine with WooCommerce 3.6.2 for me. In the future please fill out the template with the correct information and test with just WooCommerce activate and a default theme.

I will gladly reopen if you can provide steps to replicate this with just WooCommerce active and a default theme.
