### ISSUE TITLE
Allow a setting to make sure the blocks style.css asset is not loading on every page

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#23594]
If WooCommerce product blocks are not being used on a site and the Gutenberg block editor is disabled, the blocks style.css is still being loaded on every page on a site.

woocommerce/assets/css/blocks/style.css

**Comment by ryelle** [comment]
@lukecav How are you disabling the gutenberg editor? I've just tried adding the Classic Editor plugin and I still see the core `block-library` styles enqueued. If you're using a different method that is more aggressive, maybe we can hook into that somehow?

If a code snippet will help, you can de-register the CSS with this:

```php
wp_deregister_style( 'wc-block-style' );
```

**Comment by claudiosanches** [comment]
I'm checking if `enqueue_block_assets` loads scripts only when the Block Editor is enabled.

**Comment by ryelle** [comment]
@claudiosanches If you make any changes make sure to make the PR to https://github.com/woocommerce/woocommerce-gutenberg-products-block & base it off the `branch/2.0.x` branch– this way we can bump to 2.0.2 for inclusion into 3.6.3 🙂

**Comment by claudiosanches** [comment]
@ryelle yes, I'll send a PR, just studying first how this works.

**Comment by lukecav** [comment]
Using either the Classic Editor or Disable Gutenberg plugins, will still result in the blocks style.css being loaded by WooCommerce.

**Comment by claudiosanches** [comment]
Studying how WordPress enqueue block editor styles, seems like that's intentional to keep loading styles on front end, probably to avoid trouble if you have any block into your content, see that `/wp-includes/css/dist/block-library/style.min.css` is still loaded, even after the block editor is disabled.

Also all styles are only registered on our side, then WordPress load all block styles, see:

https://github.com/WordPress/WordPress/blob/3a772651488c87e96b9c6862e1c243dd5cb67dd3/wp-includes/default-filters.php#L498-L501

Note that [`wp_common_block_scripts_and_styles()`](https://developer.wordpress.org/reference/functions/wp_common_block_scripts_and_styles/) will register `do_action( 'enqueue_block_assets' )`, after WordPress start loading all block assets into `enqueue_block_assets` with [`wp_enqueue_registered_block_scripts_and_styles()`](https://developer.wordpress.org/reference/functions/wp_enqueue_registered_block_scripts_and_styles/).
So if a block is already registered, WordPress will keep enqueue styles.

It's possible to complete remove any block styles using (still doesn't remove WP default block styles):

```php
remove_action( 'enqueue_block_assets', 'wp_enqueue_registered_block_scripts_and_styles' );
```

See this similar thread from Classic Editor: https://wordpress.org/support/topic/block-editor-assets-still-enqueued/#post-10962191

I'll close as `won't fix`, since sounds like something WP does intentionally.

**Comment by Jeppeskovsgaard** [comment]
@claudiosanches 
Is there a way to just disable packages/woocommerce-blocks/build/style.css instead of any block style, as you mentioned? I can't find a hook for that.
