### ISSUE TITLE
HttpClientException: JSON ERROR: Syntax error

### ISSUE THREAD

**Issue by s3v3ns** [woocommerce/woocommerce#23608]
I get the following error message, when i update a order: 

Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /var/www/web28/html/api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378 Stack trace: #0 /var/www/web2/html/api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 /var/www/web28/html/api/vendor/automattic/woocommerce/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('orders/3542', 'PUT', Array) #2 /var/www/web28/html/api/test.php(32): Automattic\WooCommerce\Client->put('orders/3542', Array) #3 {main} thrown in /var/www/web28/html/api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

Its the same if i create a brand new product :/

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

This is not a bug on WooCommerce, also the library you are using is not party of WooCommerce, you could report it in the libraries repository, not to mention that is missing to catch this PHP exception, just a regular try/catch should do the job for you...
But this exception is because "Syntax error" on JSON, so probably your website is throwing HTML in the response, this happens in most of the cases when PHP errors are being thrown on the site, someone forgot to disable PHP's `display_errors`, still I recommend you to read the errors in the error log of your website and fix all before trying to use the REST API.

**Comment by korosh5656** [comment]
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in C:\laragon\www\shopbot\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:411 Stack trace: #0 C:\laragon\www\shopbot\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(455): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 C:\laragon\www\shopbot\vendor\automattic\woocommerce\src\WooCommerce\Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('products/2983 ', 'PUT', Array) #2 C:\laragon\www\shopbot\edit_product.php(19): Automattic\WooCommerce\Client->put('products/2983 ', Array) #3 {main} thrown in C:\laragon\www\shopbot\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 411
