### ISSUE TITLE
country/state dropdown blank 

### ISSUE THREAD

**Issue by Hukmaram-Bishnoi** [woocommerce/woocommerce#23646]
I am trying to add store address in WooCommerce but country/state dropdown not having any item value.
Please help me out.
Thanks
Hukmaram

**Comment by Hukmaram-Bishnoi** [comment]
It is very urgent. Please let me know if need more information from my side.

**Comment by claudiosanches** [comment]
This but report is missing several information in order to debug and try to replicate this issue.

<pre>
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
</pre>

**Comment by claudiosanches** [comment]
> I am trying to add store address in WooCommerce but country/state dropdown not having any item value.

Sounds like you are not allowing all countries, best check your "Selling location(s) " settings:

![Screenshot from 2019-05-08 20-20-00](https://user-images.githubusercontent.com/1264099/57414487-b5def400-71ce-11e9-87b2-fb02dff9b0df.png)

If is set like this screenshot, should not allow select any country, so you need to enter all countries that you allow or change this option to "Sell to all countries".
