### ISSUE TITLE
cannot filter by out of stock since last update

### ISSUE THREAD

**Issue by Rockstarfabrics** [woocommerce/woocommerce#23677]
**Describe the bug**
cannot filter by stock status since last update

its really annoying as i have to manually search for the out of stock items to amend or delete

**Comment by kloon** [comment]
Hi, as per the template you were presented with before opening the issue we require some more info. Also if you followed the steps and searched you would have seen there have been numerous reports and the bug has already been fixed and is due to go out with 3.6.3.

This issue is due to Yoast SEO.

#23587
