### ISSUE TITLE
nonce_user_logged_out filter breaks REST API cookie auth

### ISSUE THREAD

**Issue by tylerdigital** [woocommerce/woocommerce#23682]
**Describe the bug**
New filter for 'nonce_user_logged_out' (introduced in v3.6) breaks REST API cookie auth. REST API depends on `wp_create_nonce( 'wp_rest' );`  The nonce is created using the new session-based UID, but the rest_api_init (when it's verifying REST authentication) fails now because the session doesn't exist in the REST API.

**To Reproduce**
1. wp_create_nonce( 'wp_rest' ); inside another plugin
2. make an API call with the X-WP-Nonce value set to the value generated in step 1

**Expected behavior**
REST API call should authenticate successfully. Instead, 403 forbidden is returned because the "session" doesn't exist when WP receives the REST API request.

Solution is to modify the filter. Don't modify the UID if the $action is 'wp_rest'

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
not environment specific

**Comment by claudiosanches** [comment]
> wp_create_nonce( 'wp_rest' ); inside another plugin
> make an API call with the X-WP-Nonce value set to the value generated in step 1

Not able to reproduce, I'm testing with:

```php
add_action( 'admin_footer', function() {
?>
<script>
    jQuery.ajax( {
        url: '<?php echo esc_url_raw( rest_url() ) . 'wc/v3/products'; ?>',
        method: 'GET',
        beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-WP-Nonce', '<?php echo wp_create_nonce( 'wp_rest' ); ?>' );
        },
    } ).done( function ( response ) {
        console.log( response );
    } );
</script>
<?php
} );
```

**Comment by tylerdigital** [comment]
This bug only manifests when you are logged out (incognito window is fine), go into the browser, visit a product page, and add product to your shopping cart. This initiates the session/cookie (which is what triggers the change in nonce). 

After that, REST API call will fail with 403 forbitdden. If WooCommerce is just active but you don't have a session/cookie so it's unaffected.

**Comment by tylerdigital** [comment]
Also, you should be triggering this on `wp_enqueue_scripts` or `wp_footer`. This doesn't affect logged in users, only logged out users who have started the checkout process (and therefore have a WooCommerce session/cookie)

**Comment by claudiosanches** [comment]
> This bug only manifests when you are logged out (incognito window is fine), go into the browser, visit a product page, and add product to your shopping cart. This initiates the session/cookie (which is what triggers the change in nonce).

Now makes sense, it's for sure missing steps to reproduce this issue, please try to be as descriptive as possible when reporting something, so help everyone to fix it as quickly as possible too.

**Comment by vedanshujain** [comment]
@tylerdigital I am interested in learning more about your use case. Can you tell what exact rest API requests you are trying to make (are those endpoints present in Core, or added by your plugin, are they in wp-admin or public etc)?  It appears you would want to start a WooCommerce session by the plugin itself instead of waiting for the user to perform an action that does it. 

Or we might want to modify the rest_api_init method to make sure the session is already initialized before we get there. Please comment back with details, thanks.

**Comment by tylerdigital** [comment]
Thanks for following up @vedanshujain. This is a custom REST API endpoint in our own plugin that was affected. Something about the WooCommerce cookies were affecting the nonce value. I'm a little fuzzy on the details since this was 6 months ago, but I believe WooCommerce created a little session and "fake user" to store the cart data once visiting the cart page. So the "user id" affecting the nonce value was affected. Our API endpoint expected a logged out user to have one nonce, but the "actual nonce" of a user who added something to their Woo cart and got in this "woo cookie" state was different. So all our API requests were failing.

Again, I'm fuzzy on the details, but I know we ultimately had to add the equivalent of a `!important` to get around this issue for our customers:

```
add_filter( 'nonce_user_logged_out', 'fix_woo_cookie_issue' ), 1000, 2 );
function fix_woo_cookie_issue( $uid, $action ) {
		if ( 'wp_rest' === $action ) {
			if ( ! is_user_logged_in() ) {
				return 0;
			}
		}

		return $uid;
	}
```

I think your suggestion of `modify the rest_api_init method to make sure the session is already initialized` is probably the correct approach. Please let me know if you address this in an update. I'd like to remove the `!important` code from our plugin :) Thanks

**Comment by ObliviousHarmony** [comment]
This issue is caused by the nonce generated on page load becoming unusable once the session cookie has been created by a cart action. The `nonce_user_logged_out` hook allows unregistered users to be uniquely identified and prevents them from being susceptible to CSRF attacks. Since all unregistered users normally share UID 0, any nonce generated for any unregistered user can be used by any other.

The correct usage pattern for resolving this issue involves updating the nonce with a new one returned by the AJAX response. The `X-WP-Nonce` header will contain a valid nonce for you to use. If you store this and use it for subsequent requests, you will no longer encounter any issues. We do this internally with the wpApiSettings global defined in the `wp-api` and `wp-api-request` script dependencies.

We might also want to look at just initializing the cookie for all users, but I'm not sure what other consequences this might have.

**Comment by justanotherco** [comment]
@ObliviousHarmony Hm, the official Rest API documentation says the correct way to authenticate via cookies is to generate a nonce on page load, etc:

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Can you elaborate on what you mean by or better yet, share an example of:

> the correct usage pattern for resolving this issue involves updating the nonce with a new one returned by the AJAX response. 

Because this bug has cost me days of local debugging, stress and frustration, and it turns out to be a WooCommerce bug... It really should stay at high priority.

**Comment by ObliviousHarmony** [comment]
> Hm, the official Rest API documentation says the correct way to authenticate via cookies is to generate a nonce on page load, etc:

The issue with this is that if the nonce changes after the page load, the nonce you have stored will no longer work. For this reason, API requests also return a nonce that should be used for the next request. Here is an example of this pattern.

```javascript
let test_nonce = '<?php echo wp_create_nonce( 'wp_rest' ); ?>';

jQuery('#testing_button').on('click', function () {
    jQuery.ajax( {
        url: '<?php echo esc_url_raw( rest_url() ) . 'testing/v1/test'; ?>',
        method: 'GET',
        beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-WP-Nonce', test_nonce );
        },
    } ).done( function ( data, text_status, xhr ) {
        test_nonce = xhr.getResponseHeader( 'X-WP-Nonce' );
    } );
});
```

The problem though is that none of the actions in the `wc-ajax` file do this, nor do they have any interest in the `wp_rest` nonce in the first place. So once an action initializes the cart, the nonce you have stored in the file is unusable.

I'll see what we might be able to do about this.

**Comment by lepinko** [comment]
Hello, new to WooCommerce here. I have the same issue. I have this code:

```php
function TEST_nonce_user_logged_out ($uid, $action) {
    if (WC()->session === NULL) {
      $session_class = apply_filters( 'woocommerce_session_handler', 'WC_Session_Handler' );
      
      // Prefix session class with global namespace
      if (strpos( $session_class, '\\' ) === false) {
        $session_class = '\\' . $session_class;
      }
      
      WC()->session = new $session_class();
      WC()->session->init();
    }
    
    if (WC()->session->has_session()) {
      
      if (WC()->session->get_customer_id()) {
        
        return WC()->session->get_customer_id();
      }
    }
    
    return $uid;
  }
}
```
I am trying to manually create a session cookie before the nonce is created. The function is called multiple times, with different $action values. Log below (from a simple refresh of the product page):
```
[30-Jan-2020 17:56:02 UTC] SPD: wp_rest
[30-Jan-2020 17:56:02 UTC] SPD: wp_rest
[30-Jan-2020 17:56:02 UTC] SPD: wp_rest
[30-Jan-2020 17:56:02 UTC] SPD: wp_rest
[30-Jan-2020 17:56:02 UTC] SPD: reset_password
[30-Jan-2020 17:56:02 UTC] SPD: woocommerce-edit_address
[30-Jan-2020 17:56:02 UTC] SPD: save_account_details
[30-Jan-2020 17:56:02 UTC] SPD: wp_rest
[30-Jan-2020 17:56:02 UTC] SPD: #################### created nonce: _wpnonce=8e889aa477
[30-Jan-2020 17:56:02 UTC] SPD: log-out
[30-Jan-2020 17:56:03 UTC] SPD: wp_rest
[30-Jan-2020 17:56:03 UTC] SPD: wp_rest
[30-Jan-2020 17:56:03 UTC] SPD: wp_rest
```
Not sure why all these actions appear there as they seem irrelevant (i just refreshed the product page while being logged out). Also not sure if that "log-out" in there messes things up, as it's called after the nonce has been produced. I can't find where this log-out action is created or handled though.

Any ideas please?

**Comment by lepinko** [comment]
I have noticed that the nonce stops working after 2 minutes. Within the first 2 mintues I it works fine when logged in as well as logged out. Then gives error on both occasions.

**Comment by budzanowski** [comment]
From what I see, for the plugins I am working with the problem is gone after updating to WC3.9

**Comment by lepinko** [comment]
> From what I see, for the plugins I am working with the problem is gone after updating to WC3.9

Hello, I have tried it with a version 3.9 WooCommerce but it still gives me the 2 minutes error. Can you tell me what you are doing exactly to avoid getting this error?

**Comment by budzanowski** [comment]
I do nothing. In WC 3.9 it just works for me.

**Comment by justanotherco** [comment]
Any updates on merging #25971? Without that PR, WooCommerce will continue to break nonces for logged out users. And as I mentioned before, the official Rest API documentation says the correct way to authenticate via cookies is to generate a nonce on page load:

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

This is surely a critical WooCommerce bug, I'm surprised it's marked as "low priority".

**Comment by claudiosanches** [comment]
Hello @justanotherco, I understand your frustration, but removing it creates a security issue, we need to prioritize making WooCommerce secure for everyone.

**Comment by brezocordero** [comment]
> I'm trying to look into another ways to fix or improve it.

@claudiosanches Would you have some guidance or recommendations on how to handle the issue? 

On our case, the issue after adding items to the cart was gone with 3.9 but we still have one scenario where API requests fail, because of nonce validation.

**Comment by claudiosanches** [comment]
@brezocordero Hello, I'll take a look on the scenario you are talking about, because seems like it's trying to set session too, so I need to investigate it.

**Comment by themike007** [comment]
Hi,
after updating to WC 4.3.0 it is fully broken now and the temp fix code (which worked before 4.3.0) is not working either

**Comment by ObliviousHarmony** [comment]
Hello @themike007,

Could you share the temporary fix code you're using? Nothing about this mechanism was changed in WooCommerce Core and so everything you were doing before should still be working.

**Comment by themike007** [comment]
add_filter( 'nonce_user_logged_out', 'codetipi_fix_woo_bug', 1000, 2 );
function codetipi_fix_woo_bug( $uid, $action ) {
    if ( 'wp_rest' === $action ) {
        if ( ! is_user_logged_in() ) {
            return 0;
        }
    }
    return $uid;
}

**Comment by ObliviousHarmony** [comment]
Hello @themike007,

While this solution fixes the `wp_rest` nonce it's important to note that it doesn't fix any others. If a plugin generates its own nonce you'll experience the same problem there.

I can currently only suggest two solutions to the problem, both with their own pitfalls:

### Create Sessions for **ALL** Users
```php
function create_cart_on_first_visit() {
	if ( WC()->session->has_session() ) {
		return;
	}

	WC()->session->set_customer_session_cookie( true );
}
add_action( 'woocommerce_init', 'create_cart_on_first_visit' );
```
**Please note that this snippet will probably break _ALL_ page caching for logged-out users.** Many services like CloudFlare only cache pages if there is no session cookie present. This will give every visitor a cookie, leading to potentially slower page load times for first-time visitors. This will also unnecessarily create sessions for crawlers unless you implement checks for that here yourself.

### Disable Filter Entirely
```php
add_filter( 'nonce_user_logged_out', '__return_zero', 11 );
```
**Please note this snippet will enable CSRF attacks on logged-out users.** Each visitor is given a customer ID once they add their first item to the cart. This allows us to generate unique nonces for that session and protect against bad actors who may want to modify the cart or change the order without you noticing. By disabling this functionality you give all logged-out users the same set of nonces, opening them up to this attack vector.

**Comment by paymentplugins** [comment]
Hi All,

Hoping I can add some color to this discussion and provide a scenario in which I encountered this issue, the cause, and what the fix/workaround was:

1. Product page loads for logged out user and server side code generates a nonce using `wp_create_nonce( 'wp_rest' )` during page load.
2. User adds product to their cart, which triggers a WP REST call and item is added to their cart. When item is added to the cart, a WC session is created for the logged out user.
3. After 200 response from API add to cart call, page is refreshed, resulting in `wp_create_nonce( 'wp_rest' )` again being generated during page load. Since this is a logged out user, filter `nonce_user_logged_out` is called. The `WC_Session_Handler ` instance is hooked in to this filter and returns an ID that represents the session. 
4. User again adds an item to the cart, resulting in WP Rest call, except this time 403 response is returned due to the nonce check failing.

The reason the nonce check fails is because by default, WC does not load the session handler for REST API requests. On line 572 of `class-woocommerce.php` there is the following code:

`if ( $this->is_request( 'frontend' ) ) {
	wc_load_cart();
}`

WC returns false for WP Rest calls, because it does not consider those as frontend requests, thus the session handler is not loaded. Since the session handler is not loaded in the REST call, filter `nonce_user_logged_out` returns the regular uid of 0 for the logged out user. The nonce check then fails because it's compared against a nonce that was created using the WC session ID  vs a uid of 0 now.

I am investigating the following two workarounds:

1. For logged out users, when the REST API for the cart is called, do not include a X-WP-Nonce request header. In rest-api.php, if there is no nonce present, WP treats it as an unauthenticated requests and everything proceeds as normal, with no 403.
2. When registering the cart rest route, if the `$wp->query_vars['rest_route']` value contains a string that is part of my cart REST API, then I load the WC session, which then hooks in to the `nonce_user_logged_out` filter.

Kind Regards,

**Comment by divergeinfinity** [comment]
Gosh, I hate to confuse an issue, but I've been back and forth over this ticket and the issue, ... as it seems for my particular circumstance and the '_rest_cookie_invalid_nonce_' 403 warning ... is very much a 'Chrome80' issue and the 'SameSite' parameter.  And for those experiencing a 2 minute failure, that is the sign that it's Chrome and that parameter because without that bit in the cookie, Chrome defaults to 2 minutes and stops allowing the cookie.

When not specified, Chrome will take the 'SameSite' value it insists on having now, and fill it with 'Lax'.

This will break 3rd party REST API call requests for adding to the Cart.  The value coming from an external server must be 'None' AND with the Secure value set.

WordPress itself provides a pluggable function 'wp_set_auth_cookie`, but I can't seem to get very far over-riding this as Woo itself is using `function wc_setcookie` (which is not pluggable) in the file `wp-content/plugins/woocommerce/includes/wc-core-functions.php`

Instead of the current `setcookie` call in that function, I have the following and it then is all golden and works:

```
		  setcookie (
			$name,
			$value,
			[
			  'expires'   => $expire,
			  'path'      => COOKIEPATH ? COOKIEPATH : '/',
			  'domain'    => COOKIE_DOMAIN,
			  'secure'    => $secure,
			  'httponly'  => apply_filters('woocommerce_cookie_httponly', $httponly, $name, $value, $expire, $secure),
			  'samesite'  => 'None'
			]
		  );
```


I need that 'samesite' value set accordingly, and we need Woo to allow for this.  Perhaps a filter we could tag into for the 'samesite'?

**Comment by pmallek** [comment]
Don't you feel ashamed? You break the default behavior of WordPress because it is easier for you and other developers waste a lot of time. The problem was reported over a year ago.

**Comment by divergeinfinity** [comment]
I believe there may be several issues at work in this thread, and you haven't really said what your issue is @pmallek, but here is what I ended up going with for the Chrome Samesite issue:

```
function g3d_set_cookie() {
	if ( is_admin() ) {
		return;
	}
	$expire   = 0;
	$secure   = true;
	$httponly = true;
	foreach ( $_COOKIE as $name => $value ) {
		// the following is only available with PHP 7.3 or greater.
		// 3rd party API calls (such as those that come from other sites via the iFrame 'add_to_cart'), will require the 'samesite' cookie value set to accommodate Chrome80 and better.
		// WooCommerce sets the session cookie name depending on the user.
		// un-authenticated and authenticated users will have different session cookie name prefixes that we need to alter.
		// if we have a matching session cookie name, set a cookie using the Chrome80 'samesite' required value of 'None' along with a secure flag.
		// the following session cookie names are appended with a hash for the current user by WooCommerce to make it unique.
		// we don't care about the individual, just set all matching cookies.
		if ( false !== strpos( $name, 'wp_woocommerce_session_' )
			|| false !== strpos( $name, 'wordpress_logged_in_' ) ) {
			// all header modifications must be before any HTML output.
			if ( ! headers_sent() ) {
				// we need to exactly match the WooCommerce cookie for the user, with the 'samesite' added.
				setcookie(
					$name,
					$value,
					array(
						'expires'  => $expire,
						'path'     => COOKIEPATH ? COOKIEPATH : '/',
						'domain'   => COOKIE_DOMAIN,
						'secure'   => $secure,
						'httponly' => apply_filters( 'woocommerce_cookie_httponly', $httponly, $name, $value, $expire, $secure ),
						'samesite' => 'None', // 3rd party API calls (from Custom Gateway) require 'None' for the 'samesite' and the 'secure' flag set.
					),
				);
				break;
			} else {
				headers_sent( $file, $line );
				trigger_error( "{$name} cookie cannot be set - headers already sent by {$file} on line {$line}", E_USER_NOTICE ); // @codingStandardsIgnoreLine
			}
		}
	}
}
add_action( 'woocommerce_init', 'g3d_set_cookie', 9999 ); // try to run after all other inits.
```

May not be perfect, but this fixed it for me.

**Comment by therealgilles** [comment]
Somewhat related question: Wouldn't it be better/safer to narrow down the usage of nonce_user_logged_out to the actions used by WooCommerce? It seems a little odd that it would apply to all possible actions just because WC needs it.

PS: I use custom ajax requests and either have to put my own filter on top of the existing one, or disable the nonce check for non-logged in users (which seems less safe).

**Comment by webpalych** [comment]
Any solutions? v4.9.2 and problem is still presents. After visitor added product in the cart rest api calls return 403 rest_cookie_invalid_nonce

**Comment by therealgilles** [comment]
@webpalych: You can add a custom filter such as:

```PHP
// Set nonce user ID to 0 for non-logged in users for <whatever-you-need>
add_filter('nonce_user_logged_out', 'my_nonce_user_logged_out', 100, 2);
function my_nonce_user_logged_out( $uid, $action ) {
  if (<your-condition-here> && (!is_user_logged_in())) {
    return 0;
  }
  return $uid;
}

**Comment by Tabrisrp** [comment]
👋🏼 This is also causing an issue for us at WP Rocket, as customers are opening support tickets related to `nonce` (used in login/forms and such) and caching, but the root cause is this custom implementation of nonce from WooCommerce for logged-out users.

We do have a compatibility file and methods in place, but having to maintain a list of `nonce` to revert is a PITA on the long run: 
https://github.com/wp-media/wp-rocket/blob/c05805521714c9a7e986bb13b44921a6f0e72754/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L439
https://github.com/wp-media/wp-rocket/blob/c05805521714c9a7e986bb13b44921a6f0e72754/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L461

It would be great if, as proposed earlier in this issue thread, the use of the nonce_user_logged_out filter from WC, would be limited the actions used by WooCommerce, or any other solution that would prevent this issue and the additional work that comes with it.

Our team is available to talk in more details about it if needed!

**Comment by jbeales** [comment]
#28364 is part of the same problem.

**Comment by cabrerahector** [comment]
So this has been going on for almost two years now (at the time of writing.) Can we please have an status update on this?

**Comment by claudiosanches** [comment]
Hello @cabrerahector, this issue is part of our current sprint, so we are working on it, and we'll have some news soon.
