### ISSUE TITLE
Create new order in admin: Using shipping dropdown does not work

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#23684]
Not sure if a bug or if I'm missing how this is meant to work? 

**Describe the bug**
When creating a new order in admin, adding a shipping fee & using the dropdown, the chosen dropdown doesn't show / do anything.

**To Reproduce**
1. Set up a new order in admin 
2. Add shipping fee
3. Use shipping fee dropdown 
4. Save 

**Screenshots**
![image](https://user-images.githubusercontent.com/19706428/57608549-7537ff80-756d-11e9-956b-58dd39305df3.png)

**Expected behavior**
I would expect the chosen value from dropdown to be used as shipping name / fee. 

I'm on Woo 3.6.3 on a WP Multisite install v 5.2

**Comment by kloon** [comment]
Just above the dropdown is a Shipping Name field, what you enter there will be the value saved to the order and displayed.

![](https://cld.wthms.co/AhKuzW+)
![](https://cld.wthms.co/TIhabY+)
![](https://cld.wthms.co/cPysjP+)

Not a bug but intended since adding orders via the backend should be customizable, you also have instances where store owners would want to create a custom order and assign custom shipping based on existing methods, like waiving shipping fees for certain customers etc.

**Comment by EdithAllison** [comment]
Understood. As the dropdown doesn't "do" anything, I would argue to remove it from admin and just have the custom field / value to avoid confusion. This would however be an enhancement request. Thank you for replying!
