### ISSUE TITLE
Downloadable product files indexed by google giving free access to products

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#23681]
**Describe the bug**
The direct download links, e.g `yoursite.com/wp-content/uploads/woocommerce_uploads/product-name.pdf`, for downloadable products are indexed by Google and easily findable (and downloadable) on the web. 
Force Download seems only to protect the URL at the moment of buying the product, but it does not avoids indexing.

**To Reproduce**
1. Under WooCommerce >> Setings >> Products >> Downloadable products, set the file download method to "Force Download"
![](https://cld.wthms.co/tyi1x7+)
Link to screenshot: https://cld.wthms.co/tyi1x7

2. Create a virtual/downloadable product, and add a file to your media library and add the link 
![](https://cld.wthms.co/lEMPh1+)
Link to screenshot: https://cld.wthms.co/lEMPh1

3. Order the product

4. The order confirmation page allows the download via a button, so does the confirmation email: 
![](https://cld.wthms.co/wOtKQM+)
Link to screenshot: https://cld.wthms.co/wOtKQM

Wait for a couple of days/weeks and search for the exact product name, which will end up on Google. 

Recommendations so far: 
* Do not call your products by their real name, but give them a non-findable URL. 
* Host files outside of your own WooCommerce Install and cloak the link with a plugin. 

Is this something that can be solved on core level - making sure that Google does not index the product download links themselves?

**Comment by kloon** [comment]
That folder is only protected when using the Force and X-Send download options. Due to how redirects works the folder will not be protected.

We put an empty index.php file in the directory as well as an htaccess file with rules to control that the contents are not discoverable of that folder when you have Force or X-Send selected as the download method.

I would start by checking the site to ensure that these files are present, it might be that the files were deleted which will result in it being discoverable and indexable. To have the files recreated, server permissions permitted, you can change the download method to either of those and just save the settings again, this should recreate the files and protect it again.

I tested this and the files are created and folder is not accessible

![](https://cld.wthms.co/162KnC+)
