### ISSUE TITLE
Unable to use validate_posted_data() - protected access

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#23719]
I'm writing a multistep checkout plugin. I'd like to use the default `validate_posted_data` function for validating the checkout fields, but it is marked as `protected`.

Any chance to change that, so we can use the validation in custom plugins?

**Comment by mikejolley** [comment]
The validation functions are available outside of that method e.g. via the WC_Validation class. You could use those (which may make sense for multistep because you'll want to validate specific fields, not all of them).

**Comment by kloon** [comment]
As per Mike's comment. You will need to implement your own validation function for a multistep checkout since the general one will probably give errors due to missing fields due to the nature of multistep checkout.

Using the woocommerce_after_checkout_validation is probably your best bet, then you can clear the general errors that might get thrown and implement your own error checking from there.
