### ISSUE TITLE
error load page because of variation product

### ISSUE THREAD

**Issue by hennn** [woocommerce/woocommerce#23725]
hi every body
i have one product with 256 variation.  at the first i had a problem to show properly product but after that i increase the woocommerce_ajax_variation_threshold over the 256  the problem became solved
but after that i updated the wordpress to 5.2 and woocommerce to 3.6.2 then the page cant load  and when i decrease the woocommerce_ajax_variation_threshold under the 256 the page become ok but the product dont show properly and all the product shown at once not step by step of attribute.

**Comment by claudiosanches** [comment]
We have `woocommerce_ajax_variation_threshold` to avoid loading all variations at the same time, because this causes performance issues, this is what you are experiencing, since you are loading several variations, you server probably is running out of resources and throwing "PHP Fatal error: Out of memory" errors.
If you like to really load all those variations, probably you need to improve your server memory, or the memory allocate to PHP, however I don't recommend you do this, the performance loss is not going to be worth it, it's still better to load less variations or even split this product into more products if possible.
