### ISSUE TITLE
REST API - Order products by price. Still not possible?

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#23762]
**Is your feature request related to a problem? Please describe.**
Is it still not possible to sort products by price using Woo Rest API? ->
https://github.com/woocommerce/woocommerce/issues/16215

**Describe the solution you'd like**
If this is possible now, could you please provide an example?

**Describe alternatives you've considered**
Only alternative is to create extra plugins which we are trying to avoid if possible.

**Additional context**
@mikejolley

**Comment by kloon** [comment]
Hi @steffanhalv I have forwarded the request to the team currently working on the next iteration of the API. Hopefully, we can get this included in the next API version.

**Comment by mbs1337** [comment]
Hmm. Is this bug open, or closed? Because i’m having the same problem on some Woocommerce sites. 
Here is a test with Twenty Twenty theme, and Woocommerce activated as the only plugin.

The price sorting is not working. Here is the test, with default Woocommerce sample products. https://www.mbstech.dk/test/shop/?orderby=price
