### ISSUE TITLE
Unable to cache products

### ISSUE THREAD

**Issue by senky** [woocommerce/woocommerce#23767]
**Is your feature request related to a problem? Please describe.**
I display a lot of products on my custom front page. They don't need to be always accurate, so I try to use cache to speed up my front page by refreshing products only once an hour. I fetch products using `wc_get_products` function, then [Symfony Cache PHP Files Adapter](https://symfony.com/doc/current/components/cache/adapters/php_files_adapter.html) to cache them. But the problem is that the only data that are cached are product IDs! So when Symfony Cache tries to hydrate the objects, all product data are fetched from the DB anyway.

**Describe the solution you'd like**
I expect full product object be cached as a whole so once retrieved from cache, it can be instantly used without any DB call.

**Describe alternatives you've considered**
I tried to switch from Symfony Cache to standard serialize/unserialize, but the result is the same.

**Additional context**
I think the problem is that `WC_Data`'s `__sleep()` function only allow storing `id`.

**Comment by kloon** [comment]
As per the comment in sleep, we do that to avoid serialization. Since a lot of external object caches that are used in WP does not support this and also for the fact that extensions are allowed to manipulate data, this can cause inaccuracies when you cache whole objects.

We have caching in place but on a more granular level, not sure how your applications works seeing as it uses another PHP framework which is not what we support. If you use WordPress' built in caching mechanisms all should be well. We use WP_Cache which integrates with external object caches such as Redis or Memcached.
