### ISSUE TITLE
No VAT fallback

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce#23777]
**Describe the bug**
There seems to be a bug when you have a store configured with tax which sells to a country that is missing a tax class.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a UK store with GB VAT enabled
2. Add an additional country you sell to such as Latvia (do not add a tax class for this country)
3. Add product and proceed to checkout with a Latvian address
4. See error where no VAT is charged.

**Expected behavior**
The expected behaviour would be to default to Shops local VAT class if no country-specific VAT class is configured. It would be easier to refund extra VAT paid due to incorrect setup then lose the VAT on the order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
This is not a bug but a setup issue. If you want a blanket VAT rule you will have to add one. If you specifically set up a VAT rule for GB only then that rule will only apply to that country. In order to setup a blanket rule that will cover countries not matched just ensure you have a * rule at the bottom of your tax table.

![](https://cld.wthms.co/gR5LUd+)
