### ISSUE TITLE
GET dosent show all products or categories

### ISSUE THREAD

**Issue by Mehran-Amp** [woocommerce/woocommerce#23803]
Hello
GET dosen't  show all the produces or categories (only 5 or 6 produce) I dont know why , but
with id , GET worked for all produces.

https://example.com/wc-api/v3/products

postman screenshot
[https://pasteboard.co/Ig22w7B.jpg](url)

thanks.

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. 
Still there's pagination, you can check in https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#pagination
Also you are using a deprecated version of our REST API that should be removed from WooCommerce very soon. Better to update your app to the latest version of our REST API: https://woocommerce.github.io/woocommerce-rest-api-docs/

I'm closing this thread since is not an issue on WooCommerce.

Thanks!
