### ISSUE TITLE
Please rename column "virtual"

### ISSUE THREAD

**Issue by javadev** [woocommerce/woocommerce#23813]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

Virtual column name is not acceptable for postgresql.

**Describe the solution you'd like**

I propose to rename this column.

**Describe alternatives you've considered**

It may be removed from table or replaced with enum good type - virtual

**Additional context**

It will help with support postgresql.

**Comment by kloon** [comment]
AFAIK using the column name that forms part of reserved keyword is fine as long as you escape it by wrapping it with quotes or backticks.

Would help us debug this if you can provide details on the error you are getting? It is possible we are not escaping it correctly in all places?

Also not noticing the word virtual in the postgresql keywords list https://www.postgresql.org/docs/current/sql-keywords-appendix.html

**Comment by javadev** [comment]
I use postgresql 11.

In my adapter pg4wp I have to rename column from `virtual` to `virutal1`.

https://github.com/php4dev/heroku-wordpress/blob/master/wp-content/pg4wp/driver_pgsql_install.php#L261

**Comment by kloon** [comment]
The issue is most probably in your adapter library. I see you remove all backticks in there, which makes sense since Postgre does not support it, instead, you might want to replace backticks with double quotes as that is used to quote system identifiers; field names, table names, etc which is the equivalent of backticks in MySQL.

From a WP standpoint, we are using the correct escaping to avoid issues with system identifiers, it is the adapter library you are using which is removing things and not replacing it with the correct alternatives for Postgre.

**Comment by javadev** [comment]
I tried to escape the column `virtual` with double quotes but it was not helped.
