### ISSUE TITLE
Looking for a product in the back office

### ISSUE THREAD

**Issue by ingndjana** [woocommerce/woocommerce#23825]
**Description**
The search for a product in the back office is not refined and does not allow to find precisely the product that is sought.

**Comment by kloon** [comment]
@ingndjana could you perhaps elaborate what you had in mind to refine it more? Currently, the search allows for searching by SKU, ID as well as title and variation for variable products. It also tries to match values from within the description of the product to the search term.

We have found that usually when people are not finding the correct products it is in most cases due to the search terms they use. For example, try and use terms that are specific to the product you are looking for and not terms that are used on a lot of products. Don't search for shoes if a lot of your products include the keywords shoes in their title or descriptions.

However, I have 25000 products in my store, but I can find a single product by just using the correct search term. In my case I am looking for a product called Sleek Iron Bottle with the color violet, this is a variable product with a variation with the color set to violet.

![](https://cld.wthms.co/zPeCjF+)

I have multiple products with the name Sleek Iron Bottle and I was able to find the exact one I wanted by just using the correct search terms.

![](https://cld.wthms.co/lBfmXo+)
