### ISSUE TITLE
Add Signed CloudFront URLs to Amazon S3 Support

### ISSUE THREAD

**Issue by davidbitton** [woocommerce/woocommerce#23833]
**Is your feature request related to a problem? Please describe.**
I need the ability to serve private content through CloudFront. CloudFront signed URLs are not the same as S3 V4 auth URLs.

**Describe the solution you'd like**
I want the ability to enable CloudFront, enter a CNAME, and the necessary keys for signing

**Describe alternatives you've considered**
I tried WP_Offload_Media but it's not working quite right too

**Additional context**
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html

**Comment by kloon** [comment]
Out of the box WooCommerce does not support CloudFront or Amazon S3. There is however an extension that adds integration for S3 support and I would assume that has support for CloudFront since the integration between S3 and CloudFront is done on Amazon side https://woocommerce.com/products/amazon-s3-storage/

Unfortunately for support with the S3 plugin you will have to contact [WooCommerce support](https://woocommerce.com/contact-us/) since this platform is only for dealing with WooCommerce core issues.

**Comment by davidbitton** [comment]
The folks at Woocommerce support told me to post this. That plugin does not support cloudfront.
