### ISSUE TITLE
Gigantic Padding in new WooCommerce Admin

### ISSUE THREAD

**Issue by oitent** [woocommerce/woocommerce#23832]
**Describe the bug**
When some kinds of "notices" are displayed, for some reason, a gigantic padding is used and all settings and panels go off-screen down below…

**To Reproduce**
1. Go to 'Settings > Product'
2. No Click needed
3. Scroll down to 'find the panels'

**Screenshots**
Sorry, forgot about it… If it happens again, I'll update this report.

**Expected behavior**
No padding added bellow the notices.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce Admin plugin is active.
- [x] This bug happens with Flatsome theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 5.2.1 running Flatsome
```
</details>

**Comment by claudiosanches** [comment]
We didn't changed anything in the CSS, you can check in https://github.com/woocommerce/woocommerce/pull/23659

It's still the same padding that we always used.
If this happens again, please provide some screenshot, but for my tests seems ok, that's why I'm closing for now, but please feel free to post back in case you have this issue again.

**Comment by oitent** [comment]
If it happens again I'll be sure to post a screenshot… Regards…
