### ISSUE TITLE
virtual product address is not must field

### ISSUE THREAD

**Issue by CaryQY** [woocommerce/woocommerce#23866]
hi,

I updated woocommerce version to 3.6.4, I find country, street address, postcode and city  are not must fields in checkout page when product is virutal product ,

this  is a big error for us , because our site use these must fields  to count tax.

any suggestion about how to fix these or any default config is new to woocommerce 3.6.4 to change this config to must fields

thanks

**Comment by claudiosanches** [comment]
> I updated woocommerce version to 3.6.4, I find country, street address, postcode and city are not must fields in checkout page when product is virutal product ,

I can't reproduce this issue with the steps you provided. By default WooCommerce doesn't behave the way you are describing, sounds like some 3rd party plugin or custom code is causing this unwanted behavior.

**Comment by claudiosanches** [comment]
I'm closing this issue since is not an issue on WooCommerce, please, feel free to post back if you find something else that is related to WooCommerce. But my adivice is for you try deactivate all plugins one by one to try find what is causing it, also trying to change to Storefront or any default WordPress theme in order to isolate possible problems caused by custom code inside the theme's `functions.php`
