### ISSUE TITLE
Problem with credit cards on customer payment link

### ISSUE THREAD

**Issue by edemonair** [woocommerce/woocommerce#23902]
The problem concerns customer payment link and custom payment gateways. The main thing is that customer can't effect payment by credit card. These (WireCard and Micropayment) and most of other plugins alike store payment data in session. Such customers usually visit web-site the first and maybe the last time. It is worth mentioning that shopping cart is empty for such customers. 

After a set of tests a problem of non-complete setting of session cookie in browser was found.  WC_Session/WC_Session_Handler classes restore woocommerce session, but check whether this cookie is based on $_COOKIE variable. During the render of 'pay-order page' WC_Session/WC_Session_Handler miss functionality for setting wc_session into $_COOKIE. Unfortunately, this functionality for setting cookie into $_COOKIE variable initializes only on the cart page or when customer adds/removes products from shopping cart. Thats why the customer hasn't got any  possibility to complete such order as payment gateway passes explicitly to woocommerce session (that wasn't completely set).

1. Go on to 'pay-order' page (http://wp.artemanokhin.com/checkout/order-pay/18/?pay_for_order=true&key=wc_order_PzEY1bg8YMVfw);
2. Select one from credit card (CC) payments and submit the order.
3. After that you will get non loading CC form (WireCard) or crashed thank-you page (Micro-Payment). 

To sum up, at the point of getting session data, method [has_session()](https://github.com/woocommerce/woocommerce/blob/9eca72849dba6c3c491e5822dee7a3b47c8bead4/includes/class-wc-session-handler.php#L152) is always false, as $_COOKIE hasn't got any woocommerce_session_ param. In addition, before rendering order-pay page or at the point of init_session_cookie(), the app needs to initialize method [set_customer_session_cookie()](https://github.com/woocommerce/woocommerce/blob/9eca72849dba6c3c491e5822dee7a3b47c8bead4/includes/class-wc-session-handler.php#L124) with true param for $cookie = false (and only for the case of pay-order page) for correct payment process with custom gateways (lots of them don't care about pleasant storing of data without session).

![non_complete_session_setting](https://user-images.githubusercontent.com/29947811/59267059-e7296480-8c51-11e9-91be-43f138956fc3.png)

**Comment by kloon** [comment]
Give the new [wc_load_cart](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php#L2265) function a go and see if this resolves the issue for you?

**Comment by DigitalEden** [comment]
It doesn't resolve. This bug is present in up-to-date release version 3.6.4. Order-page renders through wc_load_cart() method. But there isn't any process that correctly and fully sets woocomerce session cookie into the browser.

**Comment by alorbach** [comment]
I have a simular problem, customers clicking the order-pay/[ordernum]/?pay_for_order=true&key=[orderkey] link can see the shopping card, but once they want to pay with Paypal Plus in my case, they are redirected to the Shopping Card which is empty. 

This worked well versions ago :(

**Comment by mikejolley** [comment]
I realise this is a very old issue which hasn't had any updates in some time, so this may be out of date or had fixes or workarounds in place, but to summarise it seems that:

- This is a problem affecting certain 3rd party payment gateways, rather than core ones
- It affects paying for a previous order, not the full cart -> checkout flow, so a user may not have a session

I think if a payment gateway needs to make use of sessions outside of the full cart/checkout flow it should ensure a session is in place. However, I understand that this is not straightforward because cookies need to be set early so the payment method may not get a chance to do so.

I think the best workaround we could implement would be to ensure that a session is created upon entry to the pay for order page, or checkout. It might be difficult to test without an effect extension however. Looking into it.

**Comment by mikejolley** [comment]
I've added a fix here: https://github.com/woocommerce/woocommerce/pull/43858
