### ISSUE TITLE
Special characters in password not working

### ISSUE THREAD

**Issue by hoangc7** [woocommerce/woocommerce#23922]
Hi there, 

I had a customer notice that when he added the single or double quotes characters (' or ") into their password it would be accepted upon registration. However, when they entered the password with those characters it failed to work during login. After he changed his password and removed the ' and " the password would work. 

I've tested those characters in my password and I too have noticed problems with them. It works when I change the password but they don't work when I try logging on. Is there any way you guys could double check this? I've only tested this using single quotes and double quotes in my password and not other special characters.

**Comment by vedanshujain** [comment]
Similar to https://github.com/woocommerce/woocommerce/pull/23499/

Looks like this is happening because [we are removing slashes from Password fields in our reset password form](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L1052), while Core WordPress does not do it. Fix would be to add a check to prevent `unslash` from password field. 

```php
foreach ( $posted_fields as $field ) {
	if ( ! isset( $_POST[ $field ] ) ) {
		return;
	}
	$posted_fields[ $field ] = wp_unslash( $_POST[ $field ] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
}
```

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23926.
