### ISSUE TITLE
Woo Structured Data Markup Change Description Field

### ISSUE THREAD

**Issue by SuperCoolTotes** [woocommerce/woocommerce#23949]
Hi,

My structured data for my Woo products is taking the 'Description' data from the short description. I would like it to take the full product description instead. Is this possible? Thanks.

https://www.supercooltotes.com/

**Comment by kloon** [comment]
If you leave the short description field blank on your products it will use the long description. We prioritize using the short description because that is usually where you would put a short precise description of your product that will be relevant to user and search engines.

You can also go about changing it to use the long description via custom code, something like below

```
add_filter( 'woocommerce_structured_data_product', 'my_custom_structured_product_data', 10, 2 );
function my_custom_structured_product_data( $markup, $product ) {
    if ( isset( $markup[ 'description' ] ) ) {
        $markup[ 'description' ] = do_shortcode( $product->get_description() );
    }
    return $markup;
}
```

Please note I have not tested the above code so please test and adjust before using.
