### ISSUE TITLE
Use a fresh product instance in function wc_update_product_stock()

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#23952]
Pull request https://github.com/woocommerce/woocommerce/pull/23534 introduced an improvement to optimise the logic in `wc_update_product_stock`. In commit https://github.com/woocommerce/woocommerce/pull/23534/commits/1a1b3e765461a42b5246198187aa9b5c9f6515a3, the following code was added:
~~~
$product_with_stock    = $product_id_with_stock !== $product->get_id() ? wc_get_product( $product_id_with_stock ) : $product;
~~~

The purpose of this code is clear: it allows to reuse a product instance, rather than loading a new one every time. However, this is not always desirable. In some cases, the product instance might have had one or more attributes altered. For example, its price might have changed, due to custom logic such as discounts, role prices, currency, country and so on. In such case, the product instance carries around such changes, which are committed to the database together with the stock when `$product->save()` is called.

Quick example
--
~~~
add_action('wp_footer', function() {
  // Let's load a product. Suppose that the product price is 100
  $product = wc_get_product(123);
  // Discount the regular price by 10%. This is a simple example,
  // but we can suppose that the calculation is significantly more 
  // complex
  $discounted_regular_price = $product->get_regular_price() * 0.9;

  // Setting the price against the product instance is an easy way
  // to avoid having to recalculate the regular price (or final price, or 
  // sale price) every time. 
  // Plugins like Bundles, Smart Coupons, the Currency Switcher
  // and so on use this approach. The set price is only to be used
  // on that specific product's instance, not to be saved/ in the 
  // "regular_price" meta
  $product->set_regular_price(1234);

  // Saving the stock also saves the price against the regular_price field
  wc_update_product_stock( $product, 1, 'decrease' );

  $product = wc_get_product(123);
  // This will now return 90 (i.e. the regular price discounted by 10%)
  echo $product->get_regular_price();
});
~~~

This is just an example, but it applies to any other attribute. Calling `$product->set_something()` before updating the stock will result in the product's meta being updated as well.

Of course, this behaviour is by design. Saving a product also saves all the attributes that changed against that instance. However, in some cases this is not necessarily desirable. In my opinion, the logic that changes the stock should only update the stock, not also everything else that might have changed.

Why the issue didn't occur before
--
Up until WooCommerce 3.6.2, the update stock logic created its own product instance. That instance was "clean", as it wasn't manipulated by any 3rd party. Due to that, changing the stock and saving the product had no side effects. The new check added in WC 3.6.3 reuses a product instance (see https://github.com/woocommerce/woocommerce/pull/23534/commits/1a1b3e765461a42b5246198187aa9b5c9f6515a3), whose attributes might have been altered by 3rd parties.

Proposed solution
==
A quick way to prevent the issue would be to restore the original logic in `wc_update_product_stock()`, so that a fresh product instance is used. The impact should be negligible, unless the function is called dozens of times, and it would be consistent with the logic used in all previous versions.

If that is deemed unsuitable, then a filter could be added to the "product pass through" logic, so that 3rd parties that might have altered the product can enforce the use of a fresh product instance. For example:
~~~
$product_with_stock = $product_id_with_stock !== $product->get_id() ? wc_get_product( $product_id_with_stock ) : $product;
// Allow 3rd parties to override the product instance
$product_with_stock = apply_filters( 'woocommerce_product_with_stock', $product_with_stock, $stock_quantity, $operation, $updating );
~~~

This would keep the existing optimisation, while still allowing 3rd parties to "remove" it when needed.

**Comment by kloon** [comment]
I am curious to know why 3rd party code is altering the product object temporarily? That should not happen, when you alter the product object it should be for keeping that changes, that is the whole idea behind using a CRUD datastore so we can keep a copy in memory and update settings and then only save it once, it avoids multiple reads/writes to the DB and avoid conflicts where multiple code reference changes the same settings.

The whole reason why it was changed is to avoid issues with stock not updating correctly due to different code trying to change the same setting, it is also more performant.

If you want to alter products in the cart there are other ways to achieve that, there are plenty of filters in place that allows you to alter the data of a product when it gets added to the cart or checkout.

You proposed solution while it might work it will need changes to the 3rd party code anyway to make it work, so why not update the 3rd party code to be correct instead of relying on a filter which I think is just a hack anyway.

There are also already filters in place you can hook into before a product is saved to achieve the same results if you want to go that route, but again I would advise against it, you should not be altering the product object with changes that are temporarily, only settings destined to be changed permanently should be done to the product object.

Closing this as a won't fix because there are filters in place you can utilize that allows you to achieve what you want to do, but more because the third party code needs to be updated to rather later the cart object and not the product when making temporary changes.

**Comment by daigo75** [comment]
In my case, I need to alter the prices of a product instance, and that doesn't mean that such changes would have to be persisted, as such price can change depending on the circumstances. Any given product can multiple sets of prices, only one of which is loaded at a given time. Due to that, calling `$product->get_price()` in different circumstances returns a different result.

In terms of "how" this is done, calling `$product->set_something()` doesn't necessarily mean wanting to save the changes to the database. That is a setter for a product instance's property (and, as far as I understand, there is no other way to set such properties), and doesn't necessarily imply the need to persist that change. When the changes have to be save, one calls `$product->save()`. Until then, the modified instance doesn't affect the database, and that's fine.

I'm aware that there are already filters in place to calculate and return custom prices, but the calculation can be CPU intensive, and repeating it every time could dramatically slow down the page load. Due to that, it makes perfect sense to calculate a product's price and set it against the instance, so that it can be returned from that moment on. Of course, that doesn't mean that such price should be persisted. 

This logic has been working perfectly since WooCommerce 1.6, even after the introduction of the CRUD system. The optimisation in the stock update logic triggered the issue I reported, until now there has never been a case of unwanted changes being persisted to the database.

I will have to disagree with it being an "incorrect approach", in fact the following sounds incorrect to me:
> you should not be altering the product object with changes that are temporarily, only settings destined to be changed permanently should be done to the product object.

Calling a setter against an object is a perfectly legitimate way to alter the object's properties, and **doesn't imply the will to persist the changes**. I've never seen any system where the above holds true. If, in your design, an object's method, such as `$product->set_something()` should only be used when storing properties into the database, then there should also be a way to set the **instance** properties, **only for that instance**.

The issue, therefore, remains open: saving the inventory of a product should not also save other properties that might have changed in the meantime, which are not meant to be stored in the database. If you reckon that it's already possible to avoid this with existing filters, I would be interested in knowing how to do that. I already looked for a solution to that before posting this issue, but I couldn't find it.

**Comment by daigo75** [comment]
As a further note: if the statement that it has to be assumed that a call to any setter method will result in the new values being persisted to the database is official, I would need to know it for sure. I don't agree with it, but I have to know for future reference. Thanks.

**Comment by kloon** [comment]
> In my case, I need to alter the prices of a product instance, and that doesn't mean that such changes would have to be persisted, as such price can change depending on the circumstances. Any given product can multiple sets of prices, only one of which is loaded at a given time. Due to that, calling $product->get_price() in different circumstances returns a different result.

If this is for just displaying a product and not the product in the cart then you should rather use the filter for altering the price and not the product object itself. For the cart, you should also use a filter, a different one than the price one as the cart object persist in memory for a user and also gets cached.

> I'm aware that there are already filters in place to calculate and return custom prices, but the calculation can be CPU intensive, and repeating it every time could dramatically slow down the page load. Due to that, it makes perfect sense to calculate a product's price and set it against the instance, so that it can be returned from that moment on. Of course, that doesn't mean that such price should be persisted.

CPU is way less expensive than DB read and write, also much faster since it does not have to do network traffic.

> This logic has been working perfectly since WooCommerce 1.6, even after the introduction of the CRUD system. The optimisation in the stock update logic triggered the issue I reported, until now there has never been a case of unwanted changes being persisted to the database.

It might be true that it was working fine, but that is not how we designed the CRUD system to work, stock was an oversight we missed and corrected recently due to the fact that there was race conditions where some functions/code could update stock outside of the object causing inaccurate stock numbers.

> Calling a setter against an object is a perfectly legitimate way to alter the object's properties, and doesn't imply the will to persist the changes. I've never seen any system where the above holds true. If, in your design, an object's method, such as $product->set_something() should only be used when storing properties into the database, then there should also be a way to set the instance properties, only for that instance.

To a degree you are right, but doesn't it defeat the whole purpose of a getter and setter object then? To me the idea behind it is so you can be efficient and performant due to all properties being changed in memory before doing a one time write to the DB. Also,  what happens when another 3rd party plugin or code calls save on an object? You will sit with the same issue as now.

> I already looked for a solution to that before posting this issue, but I couldn't find it.

Perhaps give me an idea of what you are trying to achieve and I can point you in the right direction. As an example on WooCommerce.com we also alter pricing of product as they are displayed and added to cart but we do that without touching the product object, so definitely possible.

> As a further note: if the statement that it has to be assumed that a call to any setter method will result in the new values being persisted to the database is official, I would need to know it for sure.

It might not always the case, but you cannot work on the assumption, as mentioned above any other plugin or piece of code can intercept the product object as you are doing atm and then call save on it, so it is not always in WooCommerce core's control. Personally, I would say it is safe to assume that if you make a change to the product object chances of that change persisting is there.

**Comment by kloon** [comment]
Also, you mention bundles use these setters, however, I just checked and they do not, they actually use the filters as I suggested.

For cart data you would need to use woocommerce_add_cart_item, there is also woocommerce_cart_item_price and a bunch of other filters that can assist. Do a search for those filters in core to see how to use them.

For displaying the price you need to use woocommerce_get_price_html which product bundles also use, nowhere looking at the code does it set the price anywhere using the setter methods on the product.

**Comment by daigo75** [comment]
> Calling a setter against an object is a perfectly legitimate way to alter the object's properties, and doesn't imply the will to persist the changes. 
> 
> To a degree you are right, but doesn't it defeat the whole purpose of a getter and setter object then? To me the idea behind it is so you can be efficient and performant due to all properties being changed in memory before doing a one time write to the DB. 

Actually, it doesn't. Getter and setter methods exist to allow processing the input and output related to an object's properties. Setters allow to control the input (e.g. to validate and process it, before using it), while getters can process the input. For example, `$object->set_height($value)` could just check that the value is greater than zero, then store the value in `$object->height`, while `$object->get_customer()` could return an object with all the details of a customer. In this case, neither of them would be tied to the persistence layer, nor would they affect the loading or saving data to the database.

Due to that, a method that always triggers a "changed property, save to DB" is no longer just a setter (which could be used freely), but a "persistence layer method", whose purpose is very specific and dependent on the existing design. This should be made clear, as the "setter method/persistence" coupling is not obvious, nor it is the assumed pattern for objects.

**Comment by daigo75** [comment]
As a further note, the Bundles plugin does call `WC_Product::set_price()`. File class-wc-pn-cart.php, line 826.
~~~
$cart_item[ 'data' ]->set_regular_price( 0 );
$cart_item[ 'data' ]->set_price( 0 );
$cart_item[ 'data' ]->set_sale_price( '' );
~~~

This code is from Bundles 5.10.0. As you probably know, `$cart_item[ 'data' ]` is a product instance, which seems to indicate that calling `WC_Product::set_price()` is a perfectly legitimate way to set a product's price **temporarily**, without wanting to have it persisted to the database.

I don't know If this logic is going to change in future updates of the Bundles plugin, but I thought it was worth pointing it out, as it raises the question of what the "best practice" is.

**Comment by daigo75** [comment]
The Free Gift Coupon plugin uses the same logic I just described:
~~~
public static function add_cart_item( $cart_item ) {
	// Adjust price in cart if bonus item.
	if ( ! empty ( $cart_item['free_gift'] ) ){
		$cart_item['data']->set_price( 0 );
		$cart_item['data']->set_regular_price( 0 );
		$cart_item['data']->set_sale_price( 0 );
	}
		
	return $cart_item;
}
~~~

This makes me wonder if that plugin needs an update too. From my point of view, either it is allowed to call `WC_Product::set_price()` without having to worry about the price being persisted, or it's not. I don't think it makes much sense to have a condition where such call is allowed in some cases, but not in others. That would require tracking every single context and would be quite impractical.

**Comment by daigo75** [comment]
Please disregard https://github.com/woocommerce/woocommerce/issues/24064 altogether.
