### ISSUE TITLE
www and non www cart items issue

### ISSUE THREAD

**Issue by vebtopalli** [woocommerce/woocommerce#23984]
Woocommerce cart different session on www and non www in same domain

1. Go To Website . ex: [https://www.site.com]
2. add any product to cart
3. go to cart [https://www.site.com/cart] , product is on cart
4. remove the 'www' -> [https://site.com] , and cart is empty
5. retrieve the 'www' -> [https://www.site.com] , product is on cart,

**Expected behavior**
To have same cart on both non www and www

**Comment by kloon** [comment]
Sessions and cookies are tied to domains. It also works like this due to multisites, on a multisite you do not want to share the cart across all stores as each store has different products and settings.

If you want it to work correctly you will have to setup your site to have a primary domain and then redirect the other domain to the default one. Most hosts should do this by default as it is the correct way to have it.

If you operate www and a non-www domain on the same site you will also experience issues with SEO and duplicate content, so please set a default domain with a redirect to that.
