### ISSUE TITLE
When adding a variation to cart using the "add-to-cart" URL parameter the attributes are not loaded

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#24000]
When adding a variation to cart using the "add-to-cart" URL parameter the attributes are not correctly loaded into the "variation" array on the cart item.

**To Reproduce**
1. Add a variation via the product screen
2. Add the same variation using its ID on the "add-to-cart" URL parameter

You get the variation doubled on the cart.

**Screenshots**
![image](https://user-images.githubusercontent.com/6853605/60105831-ff25db80-975b-11e9-8b72-aeeb4f38084f.png)

**Video**
https://cld.pt/dl/download/65164caa-e38e-4932-bac5-5461f34227d7/woocommerce-variation-add-to-cart-url.mov

**Cart item var_dump**
Added via the product page on the left and using the "add-to-cart" URL parameter on the right
![image](https://user-images.githubusercontent.com/6853605/60106006-50ce6600-975c-11e9-8d4b-3aac7af2ee19.png)

**Expected behavior**
When using the "add-to-cart" the quantity should be increased instead of creating a new cart entry.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bradleysa** [comment]
It would be nice to increase the priority for this issue.

Note, because of this issue, the plugin "[WooCommerce Sold Individually for Variations](https://wordpress.org/plugins/woo-sold-individually-for-variations/)" does not work as intended.

I'm using a pricing table for subscription based memberships. A customer should only be able to purchase one membership level. The membership levels are set as variable products. I'm using the add-to-cart URL for each product variation in the price table.

<img width="979" alt="price-table-variable-products-add-to-cart" src="https://user-images.githubusercontent.com/2933792/76270390-58726400-6232-11ea-9f5d-b50b25a134b1.png">

**Comment by webdados** [comment]
@bradleysa that plugin is actually mine :-D
