### ISSUE TITLE
Base Archive and Product page taxes on the language / region currently visited

### ISSUE THREAD

**Issue by MarcusFuto** [woocommerce/woocommerce#24057]
Show prices in archive and product pages based on the hreflang of a page.

This feature would make it possible to use translation plugins such as WPML in order to easily decide on when to show or not show taxes, and how much the taxes should be.

The hreflang could be entered in a new column inside the tax table where taxes are defined. Comma separated if needed on several languages or regions.

Thoughts on that?

**Comment by vedanshujain** [comment]
You can already customize taxes based on customer billing address, and then adding different tax rates for different countries. IMO this way seems better because `hreflang` is just a targeting method and not a hard directive, and users can directly go to pages targeted for different geographies.  

I am closing this issue, but please comment if I am missing something.
