### ISSUE TITLE
issues with Credit card form in the Add payment method -my-account page

### ISSUE THREAD

**Issue by latheeshvmv** [woocommerce/woocommerce#24088]
**Describe the bug**

The problem is the same as 
: https://wordpress.org/support/topic/problem-with-tokenization-developing-a-custom-gateway/

**To Reproduce**

- Add tokenization to payment gateway
- Add add_payment_method to the gateway
- add form()
 
**Screenshots**

**Expected behavior**
$_POST has to be working on the add payment page with default credit card form?

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerc

**Comment by claudiosanches** [comment]
There's no name attribute because it should not get posted to the server every time, since there's already tokens, you need to generate the token before using the gateway API for it, generally is in JS so you'll generate this token before submit the form.
This is not a bug, you can see the docs of how to implement this functionality: https://github.com/woocommerce/woocommerce/wiki/Payment-Token-API
