### ISSUE TITLE
Stock quantity reduced when a line item is added to a non-existing order

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#24097]
As per [the forums](https://wordpress.org/support/topic/manualy-add-order-stock-problem/), here are reproduction steps:

1. Suppose we have a product called “Vneck Tshirt” and Stock quantity is 14
2. Now we go to orders and press “add order”
3. Add item(s) > add product(s) and add “Vneck Tshirt” (but don't create/save the order)
4. Now close this page or tab, or ignore this order (set status to cancelled / failed)
5. Check the inventory of “Vneck Tshirt”, is 13 and this is wrong, and there is no order for “1x Vneck Tshirt”

One solution is to not render the `woocommerce_order_items` part during order creation screen (i.e. for non-existing orders).

The customer has also supplied a [screen recording](https://youtu.be/xApAlvusHtA) which demonstrates the issue.

**Comment by galbaras** [comment]
I think the case of ignoring the order (uncertain) differs from the case of closing it (certain). It's reasonable to "earmark" stock while an order references it, so that the order can go through if it is saved.

Possible solutions: stock allocation can time out after a while, stock can have a third status ("allocated"), stock can only be allocated during order save and double checked (in case another order snatched the stock while it was open).

Alternatively, force order save when adding items, or after adding the first item.

**Comment by softmastx** [comment]
Turn out that an unsaved woocommerce order status is set to "auto-draft" automatically and woocommerce don't know it so, registered a custom status and named it as "auto-draft" solved the issue.  
Check out my question on stackoverflow:
[https://stackoverflow.com/questions/59907534/unsaved-orders-created-by-admin-not-showing-up-in-woocommerce](https://stackoverflow.com/questions/59907534/unsaved-orders-created-by-admin-not-showing-up-in-woocommerce)

**Comment by swatipawarGS** [comment]
Hi @bor0 ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version  . 


Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/144835482-1cfd09a9-d3b7-4c5c-8823-77b29d137f2e.mp4



Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.
