### ISSUE TITLE
CSV import fails if image URL contains a comma

### ISSUE THREAD

**Issue by paulcee** [woocommerce/woocommerce#24110]
There is apparently a bug in the CSV importer if you specify an external image URL and it contains a comma, such as this one:
"https://example.org/images/123_High_Street,_London.jpg"

Although the fields in my CSV file are quoted correctly, the importer seems to cut off these URLs where the comma occurs, and reports that the truncated URL could not be found:
"https://example.org/images/123_High_Street"

(Given the choice, I simply wouldn't use a comma! But there are tens of thousands of files to import, and these are existing filenames that the client used when uploading.)

**Comment by kloon** [comment]
The reason for splitting is because you can specify multiple images in the field separated by a comma.

To be honest I do not think there is much we can do to fix this, as allowing commas in the image URLs will break our functionality to import multiple images for a product.

While it's definitely possible to use commas in URLs, it's not a widely used practice, nor is it recommended.

The only suggestion I have for you is to write some sort of script that rewrites the filenames on the server where you are importing from and then also apply that same rewrite rules to the image filenames, or if the files are still live and used then copy them over to a local folder on your machine, apply the script to change the filenames on your local folder and then copy over the modified files to the new server under wp-content/uploads/product_images/ and then just add the new filenames to the import file, that way the import will also be much faster.

https://docs.woocommerce.com/document/product-csv-import-suite-faq-troubleshooting/#section-9

**Comment by paulcee** [comment]
Okay, I will find a workaround. But here is an idea for the future: instead of separating URLs with commas, why not separate them with a character NOT allowed in a URL, to avoid the ambiguity?

See Internet RFC 3986. The URL characters are:
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=

So you could use something like the | pipe that you already use to separate categories.

**Comment by kloon** [comment]
Thanks @rrennick for the suggestion and patch to make this more flexible. Fixed in #24120, once released you will be able to set the separator for images via the `woocommerce_product_import_image_separator` filter.
