### ISSUE TITLE
Checkout Credit Card Field Confusing Customers

### ISSUE THREAD

**Issue by DynAggelos** [woocommerce/woocommerce#24124]
**Describe the bug**
The credit card field output via [this script](https://github.com/DynAggelos/woocommerce/blob/master/includes/gateways/class-wc-payment-gateway-cc.php) seems to be causing confusion/difficulty to customers in the following ways.

1. The JS code is glitchy. It appears that it's meant to automatically add spaces after each fourth number, but in actuality what happens is a space is added after the first four numbers, and then is removed and nothing else is added as you type. The placeholder attribute suggests these spaces should be there, but users cannot add them manually.
1. The field relies on the placeholder attribute to help customers determine the format they should type their credit card number in. The problem with this is as soon as the user starts to type their number in, the format disappears. (This could be solved with JS, but some customers may not have JS working. Adding a hint to the label itself is suggested.)
1. When JS is off, the customer can enter any amount of numbers into the field, because the maxlength attribute is not utilized.
1. When JS is off, the customer is given no visual queues about whether they are typing in their credit card information correctly. This could be done using the pattern attribute and the invalid pseudo-class CSS selector, as shown at [Mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel#Validation).

**To Reproduce**
* add a product to the cart
* go to the check out page
* start entering numbers into the credit card number field

**Comment by claudiosanches** [comment]
> When JS is off, the customer can enter any amount of numbers into the field, because the maxlength attribute is not utilized.

`maxlengh` depends on the credit card brand, also backend validation needs to be in place in case there's no JS, even more because you can just change HTML before submit, so HTML validation is not good enough.

All things that you are reporting you can fix on your store by filters or templates.
Still not possible to enforce `maxlength`, and visual placeholder doesn't help all users, like users that have credit card with more than 19 numbers.

Closing since all those changes can't apply for credit cards in all over the world, some of the things you are reporting should be fixed on your store or even improved in payment methods plugins, instead of changing for everything simple install or WooCommerce.

**Comment by DynAggelos** [comment]
If nothing else, you could at least use the format attribute to keep users from accidentally typing in anything but spaces or numbers. (And what you said about users being able to change HTML in their browsers applies to JavaScript as well, so that argument doesn't really have anything to do with my suggestions, especially since this is not about validation, but user friendliness.)

**Comment by claudiosanches** [comment]
@DynAggelos please feel free to submit a Pull Request that will be user friendly for all kinds of users with different credit cards.
