### ISSUE TITLE
Update failure 3.6.5 attributes

### ISSUE THREAD

**Issue by demoasister** [woocommerce/woocommerce#24135]
Hello, after updating WooCommerce 3.6.5 I have an error. 
My attributes and variations of my products disappear, 
The database is broken and attributes can not be added again.
Can someone help me with this error?

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe your problem is caused by a WooCommerce core bug please open another issue following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=).
