### ISSUE TITLE
504 Error when trying to view products

### ISSUE THREAD

**Issue by benjaminthedev** [woocommerce/woocommerce#24141]
Hi folks,

I’ve many years of experience with WooCommerce and think is it great but I have an issue with this demo / live site.

The products are loading slowly or creating a 504 timeout error.

WooCommerce Plugin and DB are all up to date.

I’ve removed the original theme and now using Storefront. I removed all plugin but left WooCommerce and can confirm it is Woo.

So what should I do?

Cheers!

**Comment by tahsin352** [comment]
@benjaminthedev Could you please tell more specific about this error? Or a screenshot? Thanks.

**Comment by kloon** [comment]
Please attach your system status report and provide us with a bit more details as to how to recreate this issue? What are you doing before you are noticing the issue?

In my local test environment, I have 25k products and everything loads perfectly fine.

**Comment by anjamray** [comment]
![Screenshot_2019-07-15-10-41-37-62](https://user-images.githubusercontent.com/52838923/61223370-6b20b180-a714-11e9-8a7f-0760407b0237.png)
![Screenshot_2019-07-15-10-41-37-62](https://user-images.githubusercontent.com/52838923/61223403-74aa1980-a714-11e9-8869-65b60c6409a5.png)

**Comment by claudiosanches** [comment]
Missing the whole issue template in this issue, no steps to reproduce, no system status, that's why I'm closing this issue.
if you are still experiencing this problem, please start a new bug report, and please fill all the information, we need your help in order to properly debug and be able to help you too.
You can start a new bug report in https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=
