### ISSUE TITLE
Shipping Address Changed on PayPal, Not Reflected in WC

### ISSUE THREAD

**Issue by HFW105** [woocommerce/woocommerce#24222]
We had a issue twice recently where someone made an order on WooCommerce, then while processing their payment on PayPal changed their shipping address to their credit card billing address. This new information did not make it back to WooCommerce, so we had a shipping address on WC that was very different to the one PayPal accepted, which is a worry as PayPal Seller Protection requires us to ship to the address they have validated.

Is there any way to get Woo to update the shipping address on receipt of the IPN notification? Looking at the IPN message, the detail is in there.

I’m worried, as I can see this has massive potential for fraudulent behaviour.

**Comment by claudiosanches** [comment]
> I’m worried, as I can see this has massive potential for fraudulent behaviour.

Doesn't sounds like a potential for fraudulent behavior, even more because WooCommerce validates several information back with PayPal, also WooCommerce should handle shipping information while payment methods needs to process and sent responses about the statuses, a different address on PayPal is just for PayPal conference.

Also changing based on the response from PayPal may make you sent to a wrong address, maybe the user changed by accident, why they should want to change a shipping address only in PayPal?

Anyway you can hook into `valid-paypal-standard-ipn-request` hook and save the shipping address if you like.

See my example:

```php
function custom_get_paypal_order( $custom ) {
	// We have the data in the correct format, so get the order.
	$custom = json_decode( $raw_custom );
	if ( $custom && is_object( $custom ) ) {
		$order_id  = $custom->order_id;
		$order_key = $custom->order_key;
	} else {
		return false;
	}

	$order = wc_get_order( $order_id );

	if ( ! $order ) {
		// We have an invalid $order_id, probably because invoice_prefix has changed.
		$order_id = wc_get_order_id_by_order_key( $order_key );
		$order    = wc_get_order( $order_id );
	}

	if ( ! $order || ! hash_equals( $order->get_order_key(), $order_key ) ) {
		return false;
	}

	return $order;
}

add_action( 
	'valid-paypal-standard-ipn-request',
	function( $posted ) {
		$order = ! empty( $posted['custom'] ) ? custom_get_paypal_order( $posted['custom'] ) : false;

		if ( $order ) {
			// Your code here to save shipping address from PayPal.
		}
	}
);
```

**Comment by HFW105** [comment]
Hi Claudio,

Many thanks for your response and the code snippet - very useful.  

However I disagree with your view on the potential for fraudulent behaviour.

> Doesn't sounds like a potential for fraudulent behavior, even more because WooCommerce validates several information back with PayPal, also WooCommerce should handle shipping information while payment methods needs to process and sent responses about the statuses, a different address on PayPal is just for PayPal conference.

No, the address on Paypal is very important.  The address on Paypal is the one they have validated to ensure the card is not being used fraudulently.  It is also the address you MUST send to if you are to be covered by Paypal's Seller Protection (as per Paypal terms and conditions).

This is especially a problem where, like us, you use Paypal to process credit card transactions.

> Also changing based on the response from PayPal may make you sent to a wrong address, maybe the user changed by accident, why they should want to change a shipping address only in PayPal?

OK, the fraud could go like this:

1) Person buys goods on WooCommerce system and enters a fraudulent address where they can receive the goods.
2) Payment made by credit card via Paypal using stolen credit card details.  Person changes shipping address in Paypal to the real address of credit card owner.  Paypal approves payment based on this address.
3) Vendor ships to (fraudulent) address on WooCommerce 
4) Cardholder notices fraudulent transaction on credit card and initiates a chargeback
5) Paypal reverses payment and so vendor does not receive money for the goods sent out. Vendor's claim for Seller Protection is refused as the goods were not sent to the address approved by Paypal. The thief has the goods, the vendor gets no money.

It really is a rather significant security hole.

**Comment by HFW105** [comment]
Claudio,

 

Thank you for your reply – can you read my response <https://github.com/woocommerce/woocommerce/issues/24222>  on the issue?  I am very sure there is a security issue here and I have outlined a method for the fraud on the thread and so would like you to reopen the report.

 

Thanks,

**Comment by claudiosanches** [comment]
@HFW105 

> Payment made by credit card via Paypal using stolen credit card details. Person changes shipping address in Paypal to the real address of credit card owner. Paypal approves payment based on this address.

This is something that PayPal should deal, it's not in the WooCommerce scope to validate credit card data entered on PayPal. Also PayPal will receive the address submitted by WooCommerce, so they have means to properly validate it.

> Vendor ships to (fraudulent) address on WooCommerce
> Cardholder notices fraudulent transaction on credit card and initiates a chargeback

Still sending the product to the credit card holder is not a solution, it's even worse, and as I already said, you need to trust in the information placed on WooCommerce instead of what is used by PayPal, it's PayPal job to process that data and handle any fraud.

Also if you did a purchase to a friend, using your own address as billing address on PayPal, now you should get the product as well instead of your friend?

So still I don't agree with your viewing about it, as I said, you can use that code to get address from PayPal if you like.

Also you really found any security issue, please do not post on GitHub, there's a proper place for it: https://hackerone.com/automattic/
