### ISSUE TITLE
Shipment Tracking action/filter hooks

### ISSUE THREAD

**Issue by andrewminion-luminfire** [woocommerce/woocommerce#24340]
**Is your feature request related to a problem? Please describe.**
I'm building a product that uses the REST API to read and update Shipment Tracking information, and would like to see a couple of action/filter hooks added, specifically:

1. An action hook when shipment tracking data is added/deleted
2. A filter when data is added/updated via the REST API, similar to `woocommerce_rest_prepare_{$this->post_type}_object` as in https://docs.woocommerce.com/wc-apidocs/source-class-WC_REST_Product_Variations_Controller.html#98

**Describe the solution you'd like**
I’d like to see some action and filter hooks added.

**Describe alternatives you've considered**
I looked at the metadata and helper functions, but that doesn’t help when trying to access and update shipping information via the REST API.

**Additional context**
WooCommerce support suggested I can modify the plugin on my site. I am planning on doing that, but it would be great to get the action and filter hooks into the public plugin so my users and others can continue to update the plugin without modifying it every time.

Support also mentioned that the Shipment Tracking plugin is a private repository. I’m happy to provide patch files or a PR to that repo with my suggested changes if you like.

**Comment by claudiosanches** [comment]
Not sure if you want to include new filters into WooCommerce or Shipment tracking plugin.
On WooCommerce side I don't see any extra filter that we have to include, since there's filters already available that works just fine. If you want some new filter, please feel free to submit a Pull Request.
Also GitHub is primarily for reporting bugs about WooCommerce core only, so if you need filters for Shipment tracking plugin you need to contact the WooCommerce.com support.

**Comment by andrewminion-luminfire** [comment]
@claudiosanches Thanks. I meant the Shipment Tracking plugin and already contacted WooCommerce support; they directed me to this repo.

**Comment by andrewminion-luminfire** [comment]
I’d love to submit a PR directly to the Shipment Tracking plugin—any chance you could grant me some access to it?
