### ISSUE TITLE
Filter Products by Price widget does not return variable products with variations in range

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#24349]
**Describe the bug**
Unsure if this is a bug or by design. 
If a variable product has two variations, one being $5 and the other being $20, if the price filter is set to $0-10, then the variable product will not be returned in the results, even though it partially matches. 

**To Reproduce**
1. Create variable product with two variations.
2. Price variations at $5 and $20.
3. Add _Filter Products by Price_ to site.
4. View site and set filter to $0-$10, the variable product will not show in results.

**Expected behavior**
Unsure if this is expected behavior or if it incorrect. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Affected tickets**
https://wordpress.org/support/topic/woocommerce-price-filter-doesnt-work-with-variation-price/

**Comment by januszkotlet** [comment]
There's even more to this issue. When you’ve got a product with 2 variants, let’s say a t-shirt with:

– L size for 10$
– XL size for 20$

You cannot find the product at all if you set your filter to the exact value (so 10$-10$ or 20$-20$) non of those work. Also you cannot display the product if you go higher than the minimum price and/or lower than the maximum. So 15$ is not going to work either, even tho it fits between the price range.

This renders the filter almost unusable with variable products at the moment 🙁 Please fix.

**Comment by tropicaldev** [comment]
It's a bug obviously!

Should present all products within range.

Please, this is urgent...store owners are loosing money!

**Comment by DaniilMai** [comment]
Hello everyone, I encountered such a problem that the filter does not show the products I need in the range. Suppose there is a product with a minimum price of 2000 and a maximum of 6000, if you select a filter from 2001 or to 5999 in the filter at the price, then the filter will not show me this product.
Expected Action:
Over the entire filtering interval of variable products from 2000 to 6000, the display of this product to the user.

What did I do:
Disabled plugins and tested work – yes!
Turned off the topic and translated into standard – yes!
I tried the standard filter – yes!
If there are mistakes commercially – no!

Site url: https://www.agrolavka.net ;
Help me pls

**Comment by stefanok** [comment]
I confirm that we have come across the same issue.

My suggestion would be for the filter to rather filter by max variable amount, to filter by lowest variable amount.

**Comment by writ3it** [comment]
Hi everyone! 
(@stefanok @DaniilMai @tropicaldev @januszkotlet @jessepearson)
I think that I have solution for you thats resolving Price Filter problem. Solution is implemenented as plugin. You can find it here https://wordpress.org/plugins/the-best-price-filter-for-woocommerce/.  I know that this is "Yet Another Plugin For ..." but it's very simple and uses additional mysql table, which (imo) is not Woocommerce-way but is acceptable in independent plugin.

**Comment by stefanok** [comment]
@writ3it

Thank you so much for sharing this. I will check it out.

**Comment by Stiropor** [comment]
@writ3it My team just tested it and says it works perfectly! Thank you!

**Comment by TIMON72** [comment]
> Hi everyone!
> (@stefanok @DaniilMai @tropicaldev @januszkotlet @jessepearson)
> I think that I have solution for you thats resolving Price Filter problem. Solution is implemenented as plugin. You can find it here https://wordpress.org/plugins/the-best-price-filter-for-woocommerce/. I know that this is "Yet Another Plugin For ..." but it's very simple and uses additional mysql table, which (imo) is not Woocommerce-way but is acceptable in independent plugin.
@writ3it I find error in yours plugin: if my good cost 15-15000 and filtering by 10-5000 it's ok, but if filtering 10000-15000 then "no goods here"

**Comment by writ3it** [comment]
@TIMON72 thanks for your feedback. I will try to repeate bug that you described, during the weekend. Please, discuss about plugin here https://wordpress.org/support/plugin/the-best-price-filter-for-woocommerce/. I would like to keep main subject of original issue topic.

**Comment by mensmaximus** [comment]
The issue is caused by the where clause in method `price_filter_post_clauses`.

Because it is an AND relation only products that match both criteria in the `wc_product_meta_lookup` table get fetched by the price filter. Variable product withs a lower price than the minimum price an/or a higher price than the maximum cabn't match.

The where clause needs to be modified:
```
$args['where'] .= $wpdb->prepare(
	'
		AND ( wc_product_meta_lookup.min_price >= %f AND wc_product_meta_lookup.max_price <= %f )
		OR ( wc_product_meta_lookup.max_price <> wc_product_meta_lookup.min_price
			AND NOT ( wc_product_meta_lookup.max_price < %f OR wc_product_meta_lookup.min_price > %f )
		)
	',
  $current_min_price, $current_max_price, $current_min_price, $current_max_price
);
```

This will match all products within the filter range as well as variabale product ( min price is not equal max price) if the max price is not smaller than the min range or the min price is not higher then the min range (negative reverse logic). 

This worked well in my tests but would need a lot more people to try it out with many variable products.

**Comment by fergushoang** [comment]
> The issue is caused by the where clause in method `price_filter_post_clauses` of class `WC_Query` (/woocommerce/includes/class-wc-query.php around line 547).
> 
> Because it is an AND relation only products that match both criteria in the `wc_product_meta_lookup` table get fetched by the price filter. Variable products with a lower price than the minimum price an/or a higher price than the maximum can't match.
> 
> The where clause needs to be modified:
> 
> ```
> $args['where'] .= $wpdb->prepare(
> 	'
> 		AND ( wc_product_meta_lookup.min_price >= %f AND wc_product_meta_lookup.max_price <= %f )
> 		OR ( wc_product_meta_lookup.max_price <> wc_product_meta_lookup.min_price
> 			AND NOT ( wc_product_meta_lookup.max_price < %f OR wc_product_meta_lookup.min_price > %f )
> 		)
> 	',
>   $current_min_price, $current_max_price, $current_min_price, $current_max_price
> );
> ```
> 
> This will match all products within the filter range as well as variable products ( min price is not equal max price) if the max price is not smaller than the min range or the min price is not higher then the max range (negative reverse logic).
> 
> This worked well in my tests but would need a lot more people to try it out with many variable products.

It worked for me. Thank you so much!

**Comment by walpap** [comment]
> @TIMON72 thanks for your feedback. I will try to repeate bug that you described, during the weekend. Please, discuss about plugin here https://wordpress.org/support/plugin/the-best-price-filter-for-woocommerce/. I would like to keep main subject of original issue topic.

@TIMON72 
I tried your plugin today with version 3.8.1, 3.8.0 and 3.7.0 and it didn't show results at all.
Then i tried the last code above inside /woocommerce/includes/class-wc-query.php and it is working great. I hope you could fix your plugin code and/or the next woocommerce update includes this fix.
Thank you all!

**Comment by walpap** [comment]
@writ3it 
I tried your plugin today with version 3.8.1, 3.8.0 and 3.7.0 and it didn't show results at all.
Then i tried the last code above inside /woocommerce/includes/class-wc-query.php and it is working great. I hope you could fix your plugin code and/or the next woocommerce update includes this fix.
Thank you all!

**Comment by writ3it** [comment]
@fergushoang @walpap @mensmaximus I have another example:
Product variations prices: 21$ 50$ 100$ $2000, user filter range 200$-500$. Product should be in results?

**Comment by walpap** [comment]
@writ3it 
The code above works as it should. But answering your question I think product should appear of course, because 21, 50 and 100 are included in the filter range.

**Comment by writ3it** [comment]
@walpap 
Thank you for your opinion. I can understand your point of view. For my purposes is not acceptable BUT if you like my plugin and this way to makes woocommerce modifications I have an idea. I can implement both strategies that we will can switch in wpadmin. Default will be current plugin strategy because some people are using plugin.

@mensmaximus Are you agree that I will implement similar solution in my own plugin?

Although I am involved in solving this problem, I am not Woocommerce contributor. Now I see that is not too hard to contribute so, in future if Woocommerce team doesn't implement solution and I will have a little more time, then I can prepare built-in solution.

**Comment by walpap** [comment]
@writ3it First of all, thank you very much to get involved on this and try to solve the issue.
By the way, when you say you don't agree, can you explain how should it work for you? I mean.. I don't understand what's your proposal then.

**Comment by writ3it** [comment]
@walpap 
Ok, maybe my english isn't too understandable (it's not native for me). Let me explain again.

In my example, filter range is 200-500. Prices of variants are 21, 50, 100 and 2000. In filter range is no product variants but product will appear in result. 
21 ∉ [200,500]
50 ∉ [200,500]
100 ∉ [200,500]
2000 ∉ [200,500]

In my current project I need to show products which have variants in filter range and prices of variants are very varied so it's very easy for anybody to choose similar filter range that not contain  variant. 

Plugin strictly compares each price with filter range, so each product from result has one variant at least in range and meets the financial expectations of the potential customer.

**Comment by walpap** [comment]
@writ3it I am sorry, but I don't understand you very well. My english is not native also so maybe we are talking about the same thing, but understanding different lol

I give you a different example:
Suppose we have 4 SIMPLE products (not variable) with those prices: 21, 50, 100 and 2000.

- If we use a filter range between $0 ------- $500, then the only products that may appear in the result should be the ones with 21, 50 and 100 prices.
- If we use a filter range between $80 ------- $3000, the products that should appear will be the ones that cost $100 and $2000.

Do you agree with that?

So, if you agree.. then we know that a variation of a product in the end is a simple product but attached to a parent product. We could say that this 4 simple products act as childs of a parent product. In that case.. it doesn't matter if they are inside the parent (as variants) or outside (as simple), they should appear always, because their prices exists inside the price range.

Do you understand me now? Were you thinking the same? I don't understand what should be the different way if it is not this one.. 

Anyway, you could try to modify your plugin and then I'll try it and give you my feedback!

Thanks again!

**Comment by writ3it** [comment]
@walpap 
Yes, I am agree. We are talking about the same thing. 

My example shows that solution provided by mensmaximus  doesn't work as we wish. The example shows that solution can add to the results some product that are outside the range. Result computing doesn't uses all children prices but only minimum and maximum prices. Original woocommerce filter isn't good with the same reason. But my plugin should work as you described. (I am using additional table with all prices.) Last week I made some bugfixes.

**Comment by walpap** [comment]
@writ3it 
Hello my friend. Sorry for the delay.
I installed your last plugin version 1.0.3 but it happens the same as in the first version. Every time I use your plugin, it shows no results when filtering.

I regenerated the lookup tables as you said.

Look this is a product with 4 variations with different prices (50, 60, 70 and 200): https://tienda-canvas.com/test/producto/tshirt/

If you go to the shop and filter https://tienda-canvas.com/test/tienda/?min_price=10&max_price=180 there is no results.

Your plugin never worked for me. If I deactivate it, it shows the default woocommerce results.
The only solution that worked for me until now was the one from @mensmaximus 

Also, you say that mensmaximus solution don't work well because it shows the product even if the variable prices are not inside the filter range, but it is not my case. It works perfect for me.

Are you testing on a clean woocommerce? I have woo 3.8.1 and storefront only.

**Comment by writ3it** [comment]
@walpap I'm impressed. Of course, I tested on clean woocommerce and in several other projects. I've never had a similar problem. I will try to repeat the error myself. I will continue this thread in the plugin support forum.

**Comment by Tofandel** [comment]
Any news on this?

**Comment by htdat** [comment]
3006948-zen

**Comment by basserd** [comment]
Is this something that will get patches in any of the coming updates of WooCommerce? And if so, can anyone give an estimate on when this will happen?

**Comment by vinodglobalstep** [comment]
Hi @jessepearson ,
Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using the WooCommerce 5.6.0 version.

I followed the exact mentioned steps and was able to see the variable products with variations when search by price filter.
![filterByPrize](https://user-images.githubusercontent.com/46351294/132350945-f713de13-20ca-44ef-8df3-be8b1d2984f1.JPG)

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by kazimierzfilip** [comment]
Just set min price to something greater than 0. You will see that grouped products and probably variantion products will disappear.

**Comment by vahidmalii** [comment]
> The issue is caused by the where clause in method `price_filter_post_clauses` of class `WC_Query` (/woocommerce/includes/class-wc-query.php around line 547).
> 
> Because it is an AND relation only products that match both criteria in the `wc_product_meta_lookup` table get fetched by the price filter. Variable products with a lower price than the minimum price an/or a higher price than the maximum can't match.
> 
> The where clause needs to be modified:
> 
> ```
> $args['where'] .= $wpdb->prepare(
> 	'
> 		AND ( wc_product_meta_lookup.min_price >= %f AND wc_product_meta_lookup.max_price <= %f )
> 		OR ( wc_product_meta_lookup.max_price <> wc_product_meta_lookup.min_price
> 			AND NOT ( wc_product_meta_lookup.max_price < %f OR wc_product_meta_lookup.min_price > %f )
> 		)
> 	',
>   $current_min_price, $current_max_price, $current_min_price, $current_max_price
> );
> ```
> 
> This will match all products within the filter range as well as variable products ( min price is not equal max price) if the max price is not smaller than the min range or the min price is not higher then the max range (negative reverse logic).
> 
> This worked well in my tests but would need a lot more people to try it out with many variable products.

What is the solution if I want the WooCommerce search results to not consider the maximum amount in variable products?
Because when a variable product's maximum amount exceeds our search range, the result will not be displayed even if the minimum amount is within the search range.
