### ISSUE TITLE
Span inside button in checkout

### ISSUE THREAD

**Issue by shiziksama** [woocommerce/woocommerce#24372]
I want to use custom button, with span inside it. But when fragments updated - span removes from button

I think this part of code must be removed from checkout.js
```
if ( $( this ).data( 'order_button_text' ) ) {
	$( '#place_order' ).text( $( this ).data( 'order_button_text' ) );
} else {
	$( '#place_order' ).text( $( '#place_order' ).data( 'value' ) );
}

```

**Comment by claudiosanches** [comment]
We can't remove, but feel free to submit a Pull Request to help keep any HTML markup.
Closing since it works fine, and this issues is not using any template, not sure if this is a feature request or something else, there's no explanation if you think if is a bug or not, is very vague this issue.
Let me know if you have more information.
