### ISSUE TITLE
Got fatal error after update to wc 3.7

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#24386]
I started the update on few sites but at one I received a fatal error mail from WordPress Health Check from my site and found in wc logs fatal error too. This came up few minutes after update and finished update of database.

2019-08-12T18:24:07+00:00 CRITICAL Uncaught Error: Class 'WC_REST_Coupons_V1_Controller' not found in /www/htdocs/…/bremerhaven-shopping.de/wp-content/plugins/woocommerce/includes/class-wc-api.php:360
Stack trace:
#0 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/class-wp-hook.php(286): WC_API->register_rest_routes(Object(WP_REST_Server))
#1 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/rest-api.php(475): do_action('rest_api_init', Object(WP_REST_Server))
#4 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/rest-api.php(433): rest_get_server()
#5 /www/htdocs/…/bremerhaven-shopping.de/wp-includes/rest-api.php(1394): rest_do_request(Object(WP_REST_Request))
#6 [internal function]: rest_preload_api_request(Array, '/wc/v3')
#7 /www/htdocs/…/bremerhaven-shopping.de/wp-content/plugi in /www/htdocs/w00ffce5/bremerhaven-shopping.de/wp-content/plugins/woocommerce/includes/class-wc-api.php in Zeile 360

**Comment by rodrigoprimo** [comment]
Hi @ajgw, thanks for your report.

A few other users reported the same error (https://wordpress.org/support/topic/error-after-latest-update-20/) and we are investigating it. So far, in all cases, despite the error, the update finished and the site is working fine. Are you experiencing the same? Could you please share the WooCommerce status report of the site that had this error so that we can take a closer look? You can find it under WooCommerce -> Status in WP-Admin

Thanks

**Comment by claudiosanches** [comment]
This is caused because the way that WordPress update plugins, probably you have WooCommerce Admin or another plugin that tried to trigger any REST API endpoint during the update, and since WooCommerce have several files, it may take some seconds.
This should not cause any problem in the update, also we can't patch line `360`, since doesn't exist in WooCommerce 3.7, so this is for sure a outdated file requested before the update is complete.

**Comment by ajgw** [comment]
OK, Woocommerce Admin 0.16 is installed. It seems outdated, is not compatible with Woocommerce 3.7? Anyway site works fine, no other log entries like that. 

Fatal errors not the best. Be aware that site owner gets a email from his WP health check in this case – panic? Any idea?
