### ISSUE TITLE
WooCommerce API is super slow

### ISSUE THREAD

**Issue by CodingLukas** [woocommerce/woocommerce#24449]
Hello, 10 products to upload takes 15 seconds. Is it possible somehow to speed it up?

**Comment by claudiosanches** [comment]
This depends on your server performance too. We are working in general performance improvements on WooCommerce, those includes improvements for the REST API, we include some of those improvements into 3.7, also we are looking into GraphQL, not to mention that this performance issue is not only on WooCommerce, this comes also from WordPress REST API, they are working on improve it as well.
Closing since is not something only on WooCommerce core, and we also improving it already.
If you have more issues with REST API, please free feel to log in our REST API repository: https://github.com/woocommerce/woocommerce-rest-api
