### ISSUE TITLE
Woocommerce Email attachment not geting user id for welcome email attachment

### ISSUE THREAD

**Issue by jitendra-cygnet** [woocommerce/woocommerce#24454]
**Is your feature request related to a problem? Please describe.**
My Goal is to sent userid, usermeta etc details with license key in email attachment to user..

I have sent dynamic email using "`customer-new-account.php`" file. and i am able to get user id in email template but not in attachment content` (woocommerce_email_attachments)` .

Now i want to sent dynamic email attachment for each email.

I have used below code and i am able to get user id for order email but not for welcome email.
```

add_filter('woocommerce_email_attachments', 'attach_dynamic_pdf_with_user_id',10,3);
function attach_dynamic_pdf_with_user_id($attachments, $type, $object) {

  $current_user = wp_get_current_user();
  $user_id = $current_user->ID;
  $customer_id = get_user_meta( $user_id, 'customer_id', $single );

$excel_path = '/www/...mydynamicgenerated_file.pdf';

    $attachments[] = $excel_path;
    return $attachments;
}
```

So in above code i get user_id for order email but for welcome email i am not getting user_id how can i get it?

I have also tried below code in attachment hook but its also not working

```
$user_email = $user_login;
$user       = get_user_by('login', $user_login);
if ( $user ) {
    $user_email = $user->user_email;
    $user_id = $user->ID;
}

```

Hook I am using - `woocommerce_email_attachments` Looking for user_id in welcome email using above hook

Email Content - I am able to get user id in content of all email
Email Attachment - I am able to get user id in all email expect register email

[Stackoverflow link](https://stackoverflow.com/questions/57218170/woocommerce-email-attachment-not-geting-user-id-for-welcome-email-attachment)

**Comment by claudiosanches** [comment]
GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

But trying to help you and give some tips... It's possible to get the receiver email using list `array_map( 'trim', explode( ',', $email->get_recipient() ) )`, then get try get the user by login or email, in this case you need to use `add_filter('woocommerce_email_attachments', 'attach_dynamic_pdf_with_user_id',10,4);` in order to get the last key.

But note that is passed `$object`, and in the case of the `customer-new-account.php` will return `WP_User` object, see more details: https://developer.wordpress.org/reference/classes/wp_user/

Also `wp_get_current_user()` should not be reliable, since other users (admins and shop managers) could trigger email and may expose data from wrong users. I should avoid using this function for this case.
