### ISSUE TITLE
Empty order received page after PayPal auto return

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#24492]
**Describe the bug**
After PayPal payment is complete, you are redirected to empty order received page. Well, it's not completely empty, but it only says "Thank you. Your order has been received." Normally you can see order details, items, etc. there

**To Reproduce**
Set return URL in PayPal account to http://example.com/checkout/order-received/?utm_nooverride=1
(source: https://docs.woocommerce.com/document/paypal-standard/#section-7)

**Expected behavior**
Order details are displayed.

Woo 3.6.5, WP 5.2.2

Any ideas what is missing here? Thanks!

**Comment by kloon** [comment]
Hi @uok, the issue is most probably that you are setting the return URL manually. You do not need to set the URL as we pass the return URL to PayPal when a payment request is initiated.

When you set the URL manually to a static one like the one you are, there is no way for WooCommerce to know which order that return URL is for.

My suggestion would be to remove the return URL from the PayPal settings and WooCommerce will automatically handle everything and load the correct thanks page with the correct order details after returning to store from PayPal.
