### ISSUE TITLE
Is there way to reduce Hold stock values under a minute?

### ISSUE THREAD

**Issue by remymedranda** [woocommerce/woocommerce#24491]
I'm having issues where customers are racing to site to buy a 1 wysiwyg (what you see is what you get item) and multiple customers are able to buy the product if they checkout within the 1 minute hold stock value. I'm wondering if there would be a way to set that time down to seconds, to prevent so many backorders.

**Comment by kloon** [comment]
Hi @remymedranda, unfortunately, 1 minute is the minimum. The reason is some payment gateways can take up to a minute to respond with payment results especially if it is an offsite payment gateway.

What you can however do is implement your own cleanup routine which will run every 30s for example. To do that you will need to make a copy of the `wc_cancel_unpaid_orders` function and give it a unique name.

In your new function, you will firstly have to remove the `held_duration` check.

You will then have to modify the scheduling of your new event to not * 60 as we do, but just use seconds.

`wp_schedule_single_event( time() + 30 ), 'woocommerce_custom_cancel_unpaid_orders' );` for 30 seconds.

Hop that helps, please be aware that this requires development experience so it is advised you get someone that with experience that can assist.
