### ISSUE TITLE
Nested Category Permalinks

### ISSUE THREAD

**Issue by michacassola** [woocommerce/woocommerce#24497]
Please make the permalinks also nesting aware.
For example, instead of:
`https://domain.tld/product-category/men/shoes-men/loafers-shoes-men/`
`https://domain.tld/product-category/women/shoes-women/loafers-shoes-women/`
,it should look like this, which is also very important for SEO(!):
`https://domain.tld/product-category/men/shoes/loafers/`
`https://domain.tld/product-category/women/shoes/loafers/`
The subcategory slugs should be parent aware and allow for duplicates as the nesting makes unique URLs.

**Comment by kloon** [comment]
Permalinks are nesting aware to a degree. How are your categories set up and how are you assigning these categories to the products?

If a child category is assigned to multiple parent categories it is near impossible for us to figure out what parent category to select for a specific product, that is why I said to a degree.

If you want perfect hierarchy then you will need to stick with one to one relationships on your categories. Unfortunately, due to the nature of how WordPress works you cannot have duplicate category slugs so that is also out of our control and you will end up with slugs where a duplicate child category will contain a prefix of the parent.

There is nothing we can do about that unfortunately as that is just the nature of how WordPress is designed when it comes to taxonomies.
