### ISSUE TITLE
Uncaught Error: Call to undefined method WC_Order_Refund::get_billing_first_name()

### ISSUE THREAD

**Issue by kish2011** [woocommerce/woocommerce#24531]
**Call to undefined method WC_Order_Refund::get_billing_first_name()**

I am trying to fetch order details using order id. $order = wc_get_order( $order_id ); I am getting this issue Uncaught Error: Call to undefined method WC_Order_Refund::get_billing_first_name() if order is already refunded. 
 $order->get_billing_first_name() throws error if order is already refunded. 

I have used a hack like this. 
$order = wc_get_order( $order_id ); 
if ( ! is_a( $order, 'WC_Order' ) ) {
     $order = new WC_Order( $order_id );
}

**WordPress Environment**
<details>
Using latest verison of WP & WC
</details>

**Comment by kloon** [comment]
That is because WC_Order_Refund is an extension of WC_Abstract_Order and not WC_Order where the function is defined. A WC_Order_Refund is linked to the original order via the parent_id and then only contains the negative amounts in it's scope.

The check you are doing is perfect for this, if you need the billing name from the WC_Order_Refund object then you can use something like the following:

```
$order = wc_get_order( $order_id );
if ( is_a( $order, 'WC_Order_Refund' ) ) {
    $order = wc_get_order( $order->get_parent_id() );
}
```
