### ISSUE TITLE
Problema activación Woocommerce

### ISSUE THREAD

**Issue by elvis316** [woocommerce/woocommerce#24548]
Buenas tardes, tengo un problema con el plugin de Woocommerce. Cuando intento activarlo, todo mi panel administrativo de Wordpress se vuelve blanco y las letras cambian de posición hacia la izquierda, en un formato muy básico.

Espero me puedan ayudar a solucionarlo, porque no encuentro la manera de hacer que funcione correctamente el plugin.

Muchas gracias.

**Comment by addedlovely** [comment]
Oi! This is an area for reporting technical bugs / issues - not general support.  Post over at [https://wordpress.org/support/](https://wordpress.org/support/ ) and if the problem is related to a specific plugin - post on that plugins' forum.

To give people as much help - to help you - give them information - like the version of WooCommerce you are running, the version of the plugin you are running, screenshots and steps to reproduce the issue. You can find this in the WooCommerce Status Report:
[https://woocommerce.com/videos/woocommerce-system-status/
](https://woocommerce.com/videos/woocommerce-system-status/
)

**Comment by kloon** [comment]
Hi @elvis316, as @addedlovely mentioned this site is for reporting verified bugs in the WooCommerce plugin. The issue you describe sounds like a plugin/theme conflict, to rule that out please disabled all plugins except WooCommerce and switch your theme to a default one like Storefront or Twentynineteen and test again.

If you require assistance debugging issues you are welcome to contact support if you are a paying customer at https://woocommerce.com/contact-us/ alternatively you are welcome to post on the WordPress.org support forum where one of our support personnel or a community member will gladly help assist where possible https://wordpress.org/support/plugin/woocommerce/
