### ISSUE TITLE
Changing text of sale label on single product page is not possible

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#24556]
Woo outputs a small label if a product is on sale.
But if you override it with a custom function, only the labels in the loop (e.g. in "customers also bought" section) are changed. The label above the product title is not affected on single product page.

The reason for this seems to be that the filter `woocommerce_sale_flash` exists twice: 
in `/templates/single-product/sale-flash.php` and `/templates/loop/sale-flash.php`

WP 5.2.2
Woo 3.6.5

**Comment by kloon** [comment]
Hi @uok, I am not able to reproduce this. The reason this filter name is the same is that it targets the same label, one is just for the shop loop and the other for the single product page.

In my tests when I used the woocommerce_sale_flash filter it changed it in both places

![Single Product Page](https://cld.wthms.co/qmKBFl+)
![Shop Loop](https://cld.wthms.co/uIRs8C+)

The reason why it might not always show is because you might be replacing the label without providing markup causing it to not have any styles associated with it and being hidden. See the code below I used to change the on sale label

```
function my_custom_on_sale_label( $label ) {
	return '<span class="onsale">Oh yeah! On Sale!!!!</span>';
}
add_filter( 'woocommerce_sale_flash', 'my_custom_on_sale_label' );
```

**Comment by uok** [comment]
Thanks for commenting!
This code changes both labels, but I only want to change the single product label on top and add number of days left for limited offers.
That is what is missing.

**Comment by kloon** [comment]
Ah, you can just use the is_single() conditional then inside the code to only output it on the single product page. ie.

```php
function my_custom_on_sale_label( $label ) {
        if ( is_single() ) {
	        return '<span class="onsale">Oh yeah! On Sale!!!!</span>';
        }
        return $label;
}
add_filter( 'woocommerce_sale_flash', 'my_custom_on_sale_label' );
```

**Comment by uok** [comment]
Thanks, I also had that idea but it does not work (`is_single()` seems to be on page level)

**Comment by kloon** [comment]
Try is_product(), that should work. Since is_single will also fire on regular pages which your homepage is.

**Comment by uok** [comment]
same result, also seems to be on page level. Only difference is that it works on category pages

**Comment by kloon** [comment]
The other option you have is to override the template for the single product page in your theme and then make the changes there. Then you do not have to use the filter.

**Comment by uok** [comment]
which brings me back to my initial suggestion ;-)

**Comment by kloon** [comment]
There is ways around this, try using this

```php
function my_custom_on_sale_label( $label ) {
        if ( ! is_shop() ) {
	        return '<span class="onsale">Oh yeah! On Sale!!!!</span>';
        }
        return $label;
}
add_filter( 'woocommerce_sale_flash', 'my_custom_on_sale_label' );
```
