### ISSUE TITLE
Deletion of Product Tag implies all products associated with that tag will be deleted.

### ISSUE THREAD

**Issue by splaquet** [woocommerce/woocommerce#24576]
**Describe the bug**
When you click on 'delete' for any given tag, the warning flag reads 
"You are about to permanently delete these items from your site.  This action cannot be undone. "

...this is not the case with Product Attributes (reads correctly), but *is also* the case with Product Categories

**To Reproduce**
1. Go to Products > Tags
2. Click on Delete (for any Tag)
3. The warning box pops up

**Screenshots**
https://www.dropbox.com/s/59es204zl6cdggz/Screenshot%202019-09-05%2009.21.12.png

**Expected behavior**
A warning display box, more like the Delete Attribute display box (in following screenshot), would be a more accurate reminder (for Tag & Product Categories).  As an experienced WooCommerce user, I even had to double check that it wasn't going to delete all of my products.
https://www.dropbox.com/s/1dygryesd5o962u/Screenshot%202019-09-05%2009.22.15.png

**Isolating the problem (mark completed items with an [x]):**
- [X] Native functionality

**Comment by claudiosanches** [comment]
Products don't get deleted if you delete a tag or category, this message is a default from WordPress, this message works even if you are deleting multiple tags, that's why uses plural. 

You can find it here:

https://github.com/WordPress/WordPress/blob/bd344c19eaf0dbb540d87fc8b91339f66083fc2c/wp-includes/script-loader.php#L980-L989

Anyway probably going to refactor those screens in the future for WooCommerce Admin, so maybe this will get changed.
