### ISSUE TITLE
Adding Zone info to Shipping Calculator response 

### ISSUE THREAD

**Issue by AlchemyUnited** [woocommerce/woocommerce#24577]
This falls somewhere between feature request and bug report (in a bad UX sorta way), and perhaps in the short term a bit of Support. 

Note: I'm going to be speaking to using UPS (because that's what the client / project is using. I'm not familiar enough with anything else to say how this might work for say USPS or some non-USA based shipping provider). 

Currently, the shipping calculator returns the shipping methods available and the associated rates; and from that the customer is asked to pick a level of shipping service. However, the customer is missing The Key piece of info to make that decision. That is, how many via-ground days would it take for the cart to get from the store to the destination? 

For example, in theory, as it is now, a customer placing an order could be one-day via ground and select 3 Day. ** 

So there are actually two problems

-- Customer doesn't have all the data they need to make an informed decision. 
-- Customer can pick something that not in their best interest (read: over-pay)

Finally, might there we a JS event or something (callback?) in the Shipping JS to do something custom once the stock shipping calculator is done working its magic? Maybe we could take advantage of that somehow? 

** Note: Why UPS returns rates to what are effectively completely irrelevant shipping methods is beyond me. I understand why there's ground and Next Day, as ND comes with delivery time guarantees, etc. But 2 day or 3 day?? Those should be removed or at least have a flag for "you probably want to ignore these".  Perhaps this is in the USP API response and WC is ignoring it? 

The client is NOT using the official WC UPS plugin. Made the official WC plugin does this?

**Comment by claudiosanches** [comment]
This is beyond the scope of WooCommerce core, since WooCommerce provides ways for 3rd party integration may use to display any kind of information, I myself developed a plugin for a Brazilian delivery company where I used to display how many days to delivery with each method, but this will depends in the response from the API of the delivery company, and also will depends on the plugin that you are using, it's not WooCommerce that is ignoring, it's the plugin that provides the integration that needs to include this kind of information.

**Comment by AlchemyUnited** [comment]
@claudiosanches - I have to honest, I find "This is beyond the scope of WooCommerce core" to be disheartening/upsetting. As mentioned, after picking products the shipping decision is The Most important decision in the Experience that the customer must make. But it's not important to core? Are you sure about that? And even if it's not important to core, it seems that it would be important to WooComm / Automattic. But no? That's a tough pill to swallow. 

I'd have to go back and look but I don't recall seeing a hook or anything that would make it easy to add that info to the shipping choices experience. Yeah, you can insert the shipping services (radio) lists but that's about it.

**Comment by claudiosanches** [comment]
@AlchemyUnited You are mixing things, sorry but those need to be done in the shipping method plugins, WooCommerce already provides ways for plugins to do it, like hooks and meta data for shipping in cart, where you can use to save it.

I'm not saying that this is not important for WooCommerce core, but this is something that WooCommerce core can't control, since plugins that provide integration with shipping providers that should implement it.
It's not like we don't want to do it, WooCommerce can't control it, since WooCommerce doesn't directly connect to any of those shipping providers, and you should ask it for support in the plugins you are using for shipping, since they may be able to integrate it, but note that not all shipping providers will give such information.
