### ISSUE TITLE
Wrong count and page count after using admin end product category filter ...

### ISSUE THREAD

**Issue by Aaron-Wang777** [woocommerce/woocommerce#24645]
**Describe the bug**
this issue occurs when we set the "Screen Options > Number of items per page" to 20, 

generally, the product list page would display 20 lines of product per page, but every time when we use the "category filter" to filter out one of the category, would get strange result, which contains only 10 lines of product per page, but the pagination of total page would still stay as total result divided by 20...

which makes unable to browse all filtered products...

**To Reproduce**
1. Go to 'All product page > set Number of items per page to 20 and Apply it'

2. Click on 'category filter' and choose one of the category to filter

https://imgur.com/TpUkcrt

3. Says we choose one category which contains 38 items, but after filter the page display 10 lines each, in that way total page should be 4, but somehow the total page shows 2 only...

https://imgur.com/LK6TqR9

**Expected behavior**
after filter the page display 10 lines each, in that way total page should be 4, but somehow the total page shows 2 only...

**WordPress Environment**

WooCommerce version: 3.4.6
WordPress version: 4.9.11
PHP version: 7.2.13

https://imgur.com/zrDbtZV

Any help would be appreciate !!

thanks.

**Comment by kloon** [comment]
Hi @Aaron-Wang777 I tested this with the latest version of WooCommerce and am unable to replicate this.

![](https://cld.wthms.co/GwexlC+)

Since you are running an outdated version of WooCommerce the issue might have been present and resolved in a recent version so I suggest you try and test this with the latest version instead.

Please make sufficient backups before updating any plugin, theme or WordPress core in case something goes wrong and you need to restore.

I am closing this issue as I am unable to replicate this with the latest version of WooCommerce. Will gladly reopen if you can provide steps to replicate this using the latest version.
