### ISSUE TITLE
Filter not working any more - “If product is already in the cart” = Show no message but just show cart

### ISSUE THREAD

**Issue by mika2017** [woocommerce/woocommerce#24689]
I’ve added the following filter (see below) for the scenario that a customer adds another (individually sold, digital) product to the cart that is already in the cart.

It was a nice way to disable the kind of ugly “you cannot add another product” message in a case that happened and just show the cart (as a reminder that the product is already in the cart)

With the new 3.7 woocommerce update, the appearing circle on top of the ajax "buy button" is stuck in an endlessly spinning loop.

In the version before the circle started spinning, it stopped, the cart appeared to show the customer that the product is already in the cart.

```

// if product is already in cart, just go to cart and don’t show ugly “you cannot add another product” message
add_filter( ‘woocommerce_add_to_cart_sold_individually_found_in_cart’, ‘spark_redirect_to_cart’ );

function spark_redirect_to_cart( $found_in_cart ) {
if ( $found_in_cart ) {
wp_safe_redirect( wc_get_page_permalink( ‘cart’ ) );
exit;
}
return $found_in_cart;
}
```

**Comment by rodrigoprimo** [comment]
Hi there!

I just tested and the snippet you provided works as you described on a clean WooCommerce install so the problem that you are experiencing doesn't seem to be a bug in WooCommerce core.

I will close this issue since this is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

Please leave a comment with more information if I missed something and I will take a second look.
