### ISSUE TITLE
Billing County Bug Should Say Country

### ISSUE THREAD

**Issue by landed1** [woocommerce/woocommerce#24724]
**Describe the bug**
I am finding through observing hotjar recordings that people are unable to order. Every time is the same issue I have asked for help on other channels and wonder if it is better here?
Here is a link to the screenshot - https://www.evernote.com/l/APEpYnXIxINFaItW9pAljXC_twd9wDYBcSY

I have seen 5 people struggle here in the space of a week. Would be great to understand if I can control if this field is needed or not. 

**To Reproduce**
Order and do not select England because you assume it's not needed or other. You will not be able to checkout and it's confusing. 

**Screenshots**
https://www.evernote.com/l/APEpYnXIxINFaItW9pAljXC_twd9wDYBcSY

**Expected behavior**
A proper correct error- it is not county but Country which sould be the issue.

**Comment by peterfabian** [comment]
Hi @landed1 

I'm a bit confused as `County` field should not be required for checkout in the UK.

The config for GB looks as follows by default, County is not required:

```

					'GB' => array(
						'postcode' => array(
							'label' => __( 'Postcode', 'woocommerce' ),
						),
						'state'    => array(
							'label'    => __( 'County', 'woocommerce' ),
							'required' => false,
						),
					),

```

If you want to change the name of the field, you can filter `woocommerce_get_country_locale`, e.g. by adding code

```

function change_county_to_country( $arr ) {
	$arr['GB'] = array(
		'postcode' => array(
			'label' => __( 'Postcode', 'woocommerce' ),
		),
		'state'    => array(
			'label'    => __( 'Country', 'woocommerce' ),
			'required' => false,
		),
	);
	return $arr;
}
add_filter( 'woocommerce_get_country_locale', 'change_county_to_country', 10, 1 );


```

**Comment by claudiosanches** [comment]
The field label is correct, also the error you are showing doesn't seems to come from WooCommerce core, since some of those places listed are not part of WooCommerce.
Sounds like this comes from a 3rd party plugin.
Closing since this seems to come from a 3rd party plugin, also this PR ignores the "Bug" template from https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title= and don't provide all information to debug further or prove that this is a bug on WooCommerce.
