### ISSUE TITLE
Failed foreign key addition on importing database / wp_wc_download_log

### ISSUE THREAD

**Issue by oliviercay** [woocommerce/woocommerce#24769]
**Describe the bug**
#1215 - cannot add foreign key constraint

ALTER TABLE `wp_wc_download_log`
  ADD CONSTRAINT `fk_wp_wc_download_log_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `wp_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE

This notice appeared when importing a wordpress database from another site

``` ` ### WordPress Environment ###
WC Version: 3.7.0
WP Version: 5.2.3

**Comment by claudiosanches** [comment]
Not able to reproduce this issue, also missing a lot information of how to debug, almost the entire bug template has been ignored.
I'll close for nonce, since it's not reproducible, if you still have problems with it, please open a issue again and fill all information, please: https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=
