### ISSUE TITLE
Canadian postal codes are not recognized

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#24777]
**Describe the bug**
When a shipping zone is set to Canada's region, it's not matched via a postal code.

**To Reproduce**
1. Create a shipping zone for `Ontario, Canada`:

![https://cld.wthms.co/O3XOWh](https://cld.wthms.co/O3XOWh+) 
Full Size: https://cld.wthms.co/O3XOWh

2. Make sure that you're shipping zones are properly set up so that this zone would match first:

![https://cld.wthms.co/eFBofS](https://cld.wthms.co/eFBofS+) 
Full Size: https://cld.wthms.co/eFBofS

3. Try a valid postal code for Ontario `L3T 3M7`:

![https://cld.wthms.co/bhURvR](https://cld.wthms.co/bhURvR+) 
Full Size: https://cld.wthms.co/bhURvR

4. Observe that it didn't match our Canada shipping zone:

![https://cld.wthms.co/RTmIrZ](https://cld.wthms.co/RTmIrZ+) 
Full Size: https://cld.wthms.co/RTmIrZ

It does work if I type Canada, Ontario:

![https://cld.wthms.co/MkxtBV](https://cld.wthms.co/MkxtBV+) 
Full Size: https://cld.wthms.co/MkxtBV

**Expected behavior**
I'd expect a shipping zone to match via country and postal code only, as it works in the same scenario for the United States, for example.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WooCommerce: by Automattic – 3.7.0
</details>

**Comment by claudiosanches** [comment]
>  I'd expect a shipping zone to match via country and postal code only, as it works in the same scenario for the United States, for example.

"Province" will be required in this case, since you haven't used any postcode in your shipping zone, but you have included the provinces. There's no conversion from postcode to provinces, since those depends in regulatory governmental organizations in each country to control it, so it's not part of WooCommerce.

Not sure if this works in United States, but if works, probably is something from an integration with WooCommerce Connect or some shipping method plugin.

In Brazil I'm about to write a plugin that can fill the address based in the postcode, still uses an API controlled by a governmental organization from Brazil, so this can't be part of WooComerce, that's why including in a 3rd party plugin.
