### ISSUE TITLE
Wrong shipping tax in order

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#24784]
I have my store set to 2 decimal places in `Settings -> General`. I believe that means that the tax calculations are based on 4 decimals. I'm entering prices tax excluded.

In my shipping, I entered the price `8,2644`. My tax is 21%, so that should mean `8,2644 * 1.21 = 9,999924`, round to two decimals should be 10,00 total.

It works correctly in the cart, but once the order is placed, for the shipping I get `8,26` tax excluded and `1,73` tax, which is 9.99 total.

Am I missing something, or is this a bug in the calculations?

**Comment by DanielMarklund** [comment]
Hi @vasikgreif, I believe this is related to this issue:
https://github.com/woocommerce/woocommerce/issues/23694

I haven't found a resolution for this so far, I'm experiencing the exact same issue as you describe.

**Comment by vedanshujain** [comment]
This is a bit different than #23694, the fix requires to use the same calculation logic in orders and in cart which is a little bit different right now.

**Comment by vasikgreif** [comment]
@vedanshujain I just need to get the shipping price of `10.00` both in cart and order - any way to achieve that currently? It causes major issues in the invoicing systems...

**Comment by vedanshujain** [comment]
I looked at this yesterday and this is happening because shipping rate 8,2644 rounds off to 8.26 when order is saved to DB because of 2 decimal places. The correct fix is to allow for entering shipping inclusive of taxes as requested in #24502 as well. 

Meanwhile, I would recommend one of the following workarounds:

1. You enter the flat rate of 10,00 and don't apply any more taxes.

OR

1. Add a new tax class for shipping rate in `wp-admin/admin.php?page=wc-settings&tab=tax`
2. Set shipping tax class to this newly created class. 

![Screenshot 2019-10-18 at 2 38 51 PM](https://user-images.githubusercontent.com/7571618/67081814-8557a900-f1b5-11e9-9db6-99584110ae03.png)

3. Enter the shipping rate of 8.26 instead of 8.2644.

![Screenshot 2019-10-18 at 2 43 09 PM](https://user-images.githubusercontent.com/7571618/67082013-ea130380-f1b5-11e9-9e7d-829dbc0baa04.png)

4. Enter the tax rate for this new class to 21.02% instead of 21% for this shipping class.

![Screenshot 2019-10-18 at 2 42 47 PM](https://user-images.githubusercontent.com/7571618/67081954-d23b7f80-f1b5-11e9-924d-4b29a5936499.png)

Let me know if this workaround works for you.

**Comment by vasikgreif** [comment]
@vedanshujain Thanks for the workarounds, sadly I cannot use any of these. I have the store integrated with the external invoicing system, so  I need the tax being applied, and also need more than 2 decimal places price entered in the shipping settings because otherwise, the rounding in the invoicing system goes wrong..:/

**Comment by vedanshujain** [comment]
> also need more than 2 decimal places price entered in the shipping settings because otherwise, the rounding in the invoicing system goes wrong..:/

This has been requested before, but unfortunately, the problem with calculating with more decimal places than there will discrepancy in what we display to the customer vs what we calculate. If a customer wants to see tax breakup in the current case, they will see 8,26 as shipping cost, which will be 9,99 after 21% tax and not 10.

For cases like this when someone wants to have a final cost including taxes, we introduced the concept of entering prices inclusive of taxes, but as of now, shipping is not covered by that feature.

I am closing this issue in favor of #24502, but also open to see if there are more benefits in actually storing more than 2 decimal places. Please feel free to comment back.
