### ISSUE TITLE
Remove specific variation option selected from order details

### ISSUE THREAD

**Issue by DiogoMelo-CodexDesign** [woocommerce/woocommerce#24789]
Hi, 

Is there a way to remove a specific variation option selected from order details? (from cart, checkout, order user dashboard and e-mails).

I would be very grateful if someone could help us,
Diogo Melo,
Portugal

**Comment by juliaamosova** [comment]
Hi @DiogoMelo-CodexDesign, GitHub is primarily for reporting bugs and is not a support forum. Your request is categorized as `custom development` which we don't provide here on GitHub. 

I recommend you ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce. 

I am closing this issue as this is a custom developement request rather than a bug report.
