### ISSUE TITLE
How is change order uptades comment tittle 

### ISSUE THREAD

**Issue by sszr22** [woocommerce/woocommerce#24799]
Hi, I have the problem on user dashboard / Orders tab, I want to translate 'Order Updates' Title and Order updates comment tittle, how can I do that? thanks!
![hata_mesajı](https://user-images.githubusercontent.com/54851114/66549114-44271f80-eb4b-11e9-8567-a5d442801c79.JPG)

**Comment by juliaamosova** [comment]
Hi @sszr22, GitHub is primarily for reporting bugs and is not a support forum. As a one time exception, here are some steps you can take to troubleshoot your issue further:

- Take a look at our [Translating WooCommerce (Localization)](https://docs.woocommerce.com/document/woocommerce-localization/) documentation. 
- Contact our support team to help you further: https://woocommerce.com/contact-us/.

For now, I am closing this issue as this is a support request rather than a bug report.
