### ISSUE TITLE
Use loose type comparison in wc_modify_map_meta_cap()

### ISSUE THREAD

**Issue by TimothyBJacobs** [woocommerce/woocommerce#24813]
**Describe the bug**
`wc_modify_map_meta_cap()` uses a strict type comparison to compare the user ID you are checking permissions for to the `$args[0]` user ID you are checking can be edited.

While core uses a loose type comparison. https://github.com/WordPress/wordpress-develop/blob/8ec0a2116162d87725ada4166a5595e24acad732/src/wp-includes/capabilities.php#L57

This means that if someone calls `user_can` with a numeric string, such as `'1'` instead of `1`, WooCommerce will block the request.

WooCommerce should use the same type comparison as WP core.

**To Reproduce**
Not reproducible in WC core.

**Expected behavior**
Given the current user has an ID of `1` and the `shop-manager` role, for the function call `current_user_can( 'edit_user', '1' );` to return true.

**Comment by TimothyBJacobs** [comment]
Happy to submit a PR.

**Comment by kloon** [comment]
@TimothyBJacobs Thanks for reporting. I am not sure if we want to do loose type comparison here. While I see that core does do it, I think that is more due to that function being written before adhering strictly to coding standards.

In the wc_modify_map_meta_cap docblock we do mention we expect an Int so I would say we are explicitly implying already we want an integer value. Also, PHP is smart that it would convert a string like '1' to an Int when you put it in a variable unless you typecast it as a string specifically.

The only issue would be if you call wc_modify_map_meta_cap by explicitly passing in a string value, which would be incorrect as the function does expect an integer.

For now, I would say let's keep the strict comparison in place, happy to hear from you if you disagree and provide a valid use case for not making the comparison strict.

**Comment by TimothyBJacobs** [comment]
The use case we ran into was by using a `$_POST` variable. There are a number of places as well where the user ID may be stringly typed.

For instance, `WP_Post::$post_author` which is `["post_author"]=> string(1) "1"`. And `WP_Comment::$user_id` which is `["user_id"]=> string(1) "1"`

I don't think WooCommerce should be stricter than WP Core.
