### ISSUE TITLE
Spelling Mistake In WooCommerce Message for Update Email Template Database 

### ISSUE THREAD

**Issue by danielshawellis** [woocommerce/woocommerce#24857]
WooCommerce is creating the message _"We need to update your email template database for some improvements. Please take a backup of your databases for your piece of mind"_ at the top of the WordPress admin area. The word _"piece"_ is misspelled in this context. 

Screenshot of the issue below:

<img width="949" alt="spelling-error" src="https://user-images.githubusercontent.com/28659191/67030327-cc21a200-f0d4-11e9-9a84-1d818a08f12d.PNG">

**Comment by claudiosanches** [comment]
For sure some Iron Maiden fan wrote that message!

![imagem](https://user-images.githubusercontent.com/1264099/67130829-e9d82f80-f1d8-11e9-84d5-2bfd19066740.jpg)

But sorry, I made a search into WooCommerce code base and there's no message like that, so sounds like not an Iron Maiden fan from our side :laughing: 
Seems that this message come from another plugin, note that WooCommerce doesn't have an "email template database" by default, so some plugin should be responsible for it.

I'm closing since it's not an issue on WooCommerce core, but please let me know what plugin :pray:

**Comment by Feenterlix** [comment]
This related to this plugin : https://wordpress.org/plugins/woocommerce-abandoned-cart/
