### ISSUE TITLE
GET customers trough API get empty body  or rest_no_route

### ISSUE THREAD

**Issue by samsagaz** [woocommerce/woocommerce#24868]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Woocommerce 3.7.1
2. Using API Rest v2 or v3
3. Wordpress 5.2.4

## Expected/actual behavior

When I try to use REST API to retrieve customer by email address i get...

empty body response when use 
customers?emailemail=<email>

and rest_no_route when use
customers/email/<email>

I was expecting to see...

customer information about customer with <email> values

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
>empty body response when use
>customers?emailemail=

There's no filter like `emailemail`, this value is incorrect, you should use only `email`, also if don't find any value, will return an empty response.

>and rest_no_route when use
>customers/email/

This route is not registered by WooCommerce REST API, sounds like you aren't following our documentation, you can find the documentation on https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers

Closing since both questions aren't a problem on WooCommerce, only misuse of the REST API.

**Comment by samsagaz** [comment]
sorry looks like github hide some values because i was using `<` and `>` characters

`
customers?email=<email>

`

I already read the documentation

trying to get it working since 2 days ago.

From Documentation: 
`Retrieve a customer
This API lets you retrieve and view a specific customer by ID or email.

HTTP request
GET /wp-json/wc/v3/customers/<id>
`

**Comment by samsagaz** [comment]
sorry looks like github hide some values because i was using < and > characters

im using 
customers?email=\<my_email\> and customers/email/\<my_email\>/ are the routes that im using without luck

from woocommerce/includes/legacy/api/v3/class-wc-api-customers.php (and v2 version too)i get this route, this is not working anymore?

```
		# GET /customers/email/<email>
		$routes[ $this->base . '/email/(?P<email>.+)' ] = array(
			array( array( $this, 'get_customer_by_email' ), WC_API_SERVER::READABLE ),
		);

```

I already read the documentation

trying to get it working since 2 days ago.

From Documentation:
`Retrieve a customer
This API lets you retrieve and view a specific customer by ID or **email**.

HTTP request
GET /wp-json/wc/v3/customers/\<id\>
`

**Comment by claudiosanches** [comment]
> from woocommerce/includes/legacy/api/v3/class-wc-api-customers.php (and v2 version too)i get this route, this is not working anymore?

This file is from our legacy REST API that is deprecated and will be removed soon.

>  This API lets you retrieve and view a specific customer by ID or email.

Sorry, looks like I forget to update it when I wrote the new documentation, I already fixed it, because if you read the code responsible for that endpoint you'll see that will only accept numbers for an ID.

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version1/class-wc-rest-customers-v1-controller.php#L75
