### ISSUE TITLE
Additional filter that help to set the specific webhooks are synchronous

### ISSUE THREAD

**Issue by corentinalcoy** [woocommerce/woocommerce#24968]
**Is your feature request related to a problem? Please describe.**

I am using the webhooks to get information about a customer, order, and product.
The issue is by default the webhooks are asynchronous. I just need to get the customer created webhooks synchronous. For the moment, I want to just set the webhooks as synchronous or asynchronous. I can not specify which webhook will be synchronous or not. The issue is if all webhooks are synchronous, the website will possibly be slow.

**Describe the solution you'd like**
The solution I suggest is **additional filter that helps to set the specific webhooks to be synchronous**.
For example `woocommerce_webhook_customer_created_deliver_async`

**Comment by juliaamosova** [comment]
@corentinalcoy you can make use of a filter here which looks like exactly what you are looking for:

https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/wc-webhook-functions.php#L22

It already passes the webhook, so you can check if you would like to send this right away or not, by returning false/true.

I am closing this issue for now since it looks like there is already solution in place. Feel free to reopen if I missed something.
