### ISSUE TITLE
Order email bounce back if the customer email address starts with www.

### ISSUE THREAD

**Issue by asperty567** [woocommerce/woocommerce#25099]
On receiving an order from a customer that has an email address starting with "www." such as "www.joebloggs@gmail.com", woocommerce or wordpress automatically turns it into a web address, adding http:// in front of it and so all the emails sent from woocommerce including order status emails bounce back.

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @asperty567. I was able to reproduce it:

![email](https://user-images.githubusercontent.com/19143190/69533789-6268a380-0f70-11ea-9f3c-70460366a890.jpg)

We call the WordPress function [`make_clickable( string $text )`](https://developer.wordpress.org/reference/functions/make_clickable/) on the order screen - that function matches anything that starts with `www.` or `ftp.` to get it processed by `_make_web_ftp_clickable_cb`:

https://github.com/woocommerce/woocommerce/blob/822d1ebb40cb149ea1b99c466139c810c9926297/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L346

It is a bug but a low priority since it likely doesn't affect many people.

**Comment by peterfabian** [comment]
I tested this a bit more and the emails themselves seem to be sent and delivered fine, at least via MailHog and default WP php mailer. Maybe some additional filtering happening somewhere else?

<img width="1701" alt="Screenshot 2019-11-25 at 12 41 27" src="https://user-images.githubusercontent.com/2207451/69537791-225dec80-0f81-11ea-98c9-7913c048fe2e.png">

Submitting your [system status](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) report and providing more information about the email configuration might help us solve your issue faster.
