### ISSUE TITLE
No form revalidation on customer checkout page from admin / user dashboard

### ISSUE THREAD

**Issue by gpsidhuu** [woocommerce/woocommerce#25121]
## Prerequisites

 

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  lets have two or more payment gateways enabled  ( eg COD & paypal )
2.  I have additional fees associated with the payment  gatweys ( eg $10 for COD , $20 for payapl )
3.  Now  a customer tries to place an order using paypal but the order fails
4. Now  the customer go to his order list in dashboard and click the pay  button against the failed order
5 . The payment  which opens now wont update the additionals fees or revalidate any thing when a  payment gateway is changed. So in this case if i OPT to pay via COD now .. i ll be charged   $20 as additional fee ( of paypal ) instead of $ 10

## Expected/actual behavior

When user changes the payment gateway it should re-validate the form just like it do on the checkout page . 

 

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Default woocommerce +  storefront theme
Payment Gateway Based Fees and Discounts for WooCommerce ( to add payment gateway based fee )

**Comment by juliaamosova** [comment]
@gpsidhuu thanks for raising the issue. However, it seems to me that the issue is related to the 3rd party plugin you are using (Payment Gateway Based Fees and Discounts for WooCommerce ( to add payment gateway based fee )) not working correctly.

**Comment by gpsidhuu** [comment]
@juliaamosova sorry but that is not a plugin issue . Even if i remove that plugin there is no ajax call for validating the order when the payment gateway is changed.

**Comment by juliaamosova** [comment]
Hi @gpsidhuu,

Apologies for the delayed response here. We had a few more reports of the same issue. I take my words back as the issue seems to be on the WooCommerce side of things indeed. 

I documented my steps of how I reproduced it in https://github.com/woocommerce/woocommerce/issues/25777 so we are going to use https://github.com/woocommerce/woocommerce/issues/25777 for further discussion and tracker for a fix. Because of this, I am going to close your issue - thank you for reporting it. Please add any additional comments or thoughts if needed on https://github.com/woocommerce/woocommerce/issues/25777. Thanks!
