### ISSUE TITLE
Clarify documentation for negative fees

### ISSUE THREAD

**Issue by siliconforks** [woocommerce/woocommerce#25124]
**Describe the bug**
At one time negative fees were not considered a supported feature (see #13224 for details).  Then, for version 3.2 it was [announced](https://woocommerce.wordpress.com/2017/08/24/coupon-and-cart-improvements-in-3-2/) that "We also know that some users are currently exploiting fees to apply negative amounts, so we’ve fixed the way in which taxes get applied in those cases."

However, the API documentation still says (in a number of places) that negative fees are not allowed:

- https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/class-wc-cart.php#L1767
- https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/class-wc-order-item-fee.php#L6
- https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/legacy/abstract-wc-legacy-order.php#L99 (although this function is deprecated so it probably shouldn't be used anyway)

**Expected behavior**
If these comments are considered obsolete, then they can probably simply be removed.

On the other hand, if negative fees are still not recommended for some reason, e.g., they have limitations or may not work in certain cases, it might be better to document these more clearly.

**Comment by claudiosanches** [comment]
It's supported because 3rd party developers have been using, like we have said in the 3.2 announcement post.
But ideally we still want to provide a better API for discounts like that, instead of using a feature not designed for that.

> On the other hand, if negative fees are still not recommended for some reason, e.g., they have limitations or may not work in certain cases, it might be better to document these more clearly.

Currently fees work, at least for most of the things, but may cause problems in 3rd party plugins, like some payment gateways could not process the discounted value, they may could not expect a negative value, since the feature is called `fee`.
So again, ideally we should avoid using negative fees, but we make it work in WooCommerce, like we plan to make negative product prices works too, but both out of the box may cause problems for 3rd party plugins.

**Comment by juliaamosova** [comment]
@siliconforks we are going to close this issue at this time since we marked https://github.com/woocommerce/woocommerce/issues/25037 as an `enhancement`. When we'd come back to reevaluating https://github.com/woocommerce/woocommerce/issues/25037, we will see how to best address the issue itself as well as the documentation.
