### ISSUE TITLE
Problem woocommerce multilingual 4.7.5

### ISSUE THREAD

**Issue by stefanov76** [woocommerce/woocommerce#25146]
When I updated WOOCOMMERCE MULTILINGUAL (originally in version 4.7.4 updated to version 4.7.5) an error message appeared that required others two plugins update as well: WPML Multilingual CMS, WPML String Translation. 
After this step the shop in English no longer works. Or rather when I try to buy a product appears the words "Sorry, no products matched your selection. Please choose a different combination."
This problem occurs only with the English language, in Italian everything works correctly.

You can try from this link: https://dance4travel.com/en/product/inside-20/
![Screenshot_2](https://user-images.githubusercontent.com/58361536/69901020-b82bba00-137b-11ea-92ea-b349ae7f7b19.png)
![Screenshot_3](https://user-images.githubusercontent.com/58361536/69901021-b9f57d80-137b-11ea-992b-93c020507126.png)

**Comment by juliaamosova** [comment]
Hi there @stefanov76,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin only.

It looks like your issue is related to the WooCommerce Multilingual plugin. Please contact the authors of this plugin to troubleshoot this issue further. 

I am closing this issue as it seems to be not related to the WooCommerce core plugin. If I missed something, please leave a comment and I will take a second look.
