### ISSUE TITLE
WC_Payment_Gateaway not found

### ISSUE THREAD

**Issue by martinowren** [woocommerce/woocommerce#25153]
class WC_rm_Gateway extends WC_Payment_Gateway gives error "WC_Payment_Gateaway not found" in the new 3.8.1. Causes website to crash 

Deactivating the plugin that adds the custom payment gateaway fixes the issue, so I rolled Woocommerce back to 3.8.0 which fixed the issue. 

**WordPress Environment**
Wordpress 5.3

**Comment by claudiosanches** [comment]
> Deactivating the plugin that adds the custom payment gateaway fixes the issue, so I rolled Woocommerce back to 3.8.0 which fixed the issue.

I don't see anything that may cause this kind of problem, since we haven't changed anything related to it, 3.8.1 only fixes CSS for WordPress 5.3 and Product's schema for Google Structured Data.

>* Tweak - Include 5 latest reviews to Product's schema. - #24278
>* Fix - Improve select2 style and admin screen button alignments in WP 5.3 #25125
>* Fix - Fix order action button centering for WP 5.3. #25119
>* Fix - Improved WooCommerce and Twenty twenty styling. #25085

Above is the 3.8.1 changelog, so you can also check.

> class WC_rm_Gateway extends WC_Payment_Gateway gives error "WC_Payment_Gateaway not found" in the new 3.8.1. Causes website to crash

The cause for this problem may be that extensions registering the class too early for some reason, maybe you also updated that extension, and I recommend you to ask for the extension developer to debug it.

I'll close since we haven't changed anything in 3.8.1 that may affect it, sounds like a problem in the 3rd party plugin that you are reporting, but please feel free to comment back, and if you can please post back here the comment from the 3rd party developer about this issue.

Also note that the [issue template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=4-Bug-report.md&title=) have been deleted, there's no steps to reproduce, there's not even the extension name in question, so please in the future fill the issue template, it will helps a lot for us to debug.

**Comment by martinowren** [comment]
I created the plugin myself. 
The action hook used is 'plugins_loaded' isn't this the correct hook for creating a payment gateaway class that extends WC_Payment_Gateway?
