### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by MRHEI14** [woocommerce/woocommerce#25163]
![Screen Shot 2019-12-04 at 12 01 46](https://user-images.githubusercontent.com/31472594/70111720-16afab80-168e-11ea-823b-5a203f3745e6.png)
Not able to select Friday and Saturday as an option as it's out of the frame

**Comment by juliaamosova** [comment]
Hi there @MRHEI14,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs specific to the WooCommerce plugin only. It looks like your bug is related to the WooCommerce Bookings extension. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in our [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case.

Other than that, it looks like you are a paying customer of WooCommerce (since you are using paid WooCommerce Bookings plugin) - subject to be verified by the support tem. You can contact WooCommerce support by [live chatting or opening a ticket here](https://woocommerce.com/contact-us/). They will be able to help you troubleshoot it further there. 

I am closing this issue since it is not related to the WooCommerce core plugin.
