### ISSUE TITLE
ToggleAttr

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#25166]
**Is your feature request related to a problem? Please describe.**
In your collection of utilities for js_vars you have css, html, style and toggleClass functions. I have thought about toggleAttr function because in some cases it is needed (ex. below)

**Describe the solution you'd like**
The same work as you have for toggleClass() but for attr 

**Describe alternatives you've considered**
No alternatives at this time

**Additional context**
			'transport' => 'postMessage',
			'js_vars'     => array(
				array(
					'element'  => '.header-sticky',
					'function' => 'toggleAttr',
					'attr' => 'sticky-type',
					'attr_value' => 'sticky',
					'value' => 'sticky'
				),
				array(
					'element'  => '.header-sticky',
					'function' => 'toggleAttr',
					'attr' => 'sticky-type',
					'attr_value' => 'smart',
					'value' => 'smart'
				),
			),

**Comment by claudiosanches** [comment]
>  In your collection of utilities for js_vars you have css, html, style and toggleClass functions. I have thought about toggleAttr function because in some cases it is needed (ex. below)

What you are reporting sounds like part of WordPress core, and not WooCommerce, we don't control anything for `js_vars` like that, also I guess `toggleClass` is from the jQuery library: https://api.jquery.com/toggleclass/

I'm closing since we don't introduce any new functionality for developers related to the WordPress customizer.
