### ISSUE TITLE
Not displaying variation/attribute name on order details page 

### ISSUE THREAD

**Issue by Navas-ahmed** [woocommerce/woocommerce#25185]
I have a variable product setup. When a customer places an order, they are able to see the variations and it all works fine, however when i view the order in the orders page on the dashboard, the variation names are not displayed instead a variation id is displayed(https://prnt.sc/q6zoj7). But when we will change any of the one attribute slug names, then the variation name displaying correctly(https://prnt.sc/q6znhi).

**To Reproduce**
1-Place an order of a product which is a variable product.
2-Go to the orders menu page on the dashboard.
3-Click on the relevant order you placed.
4-The order details page will be displayed.
5-On the order details page under the product that you purchased, you will see the issue that I am referring to.
6- Then Go to dashboard -> Attribute -> Change any attribute slug name -> then back to the above procedure, then the  order details page under the product that you purchased, there I can see all the variation displaying correctly.

**Screenshots**
before changing the attribute slug name ( https://prnt.sc/q6zoj7 ) , after changing slug ( https://prnt.sc/q6znhi )

**Expected behavior**
I was expecting the variation name to be displayed.

-I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
 This bug happens with a default WordPress theme active
 I can reproduce this bug consistently using the steps above.

**WordPress Environment**

https://prnt.sc/q6zwqx
https://prnt.sc/q6zwws
https://prnt.sc/q6zxdm
https://prnt.sc/q6zxq0
https://prnt.sc/q6zy5k
https://prnt.sc/q6zyf4
https://prnt.sc/q6zz0z
https://prnt.sc/q700lf
https://prnt.sc/q700zt
https://prnt.sc/q7016v

**Comment by juliaamosova** [comment]
Thank you for raising this issue @Navas-ahmed. 

There are a few things to point out here:

If the product has more than 2 variations (of if the product has 2 variations but one of the variations has more than 1 word), the variations will be displayed under the product title. Depending on the length of the variation name, it can become difficult to read. It's been working like this since WooCommerce 3.0. 

The following filter can be used to control where the names of the variations appear if the product has more than 2 variations (in the title or under the title):

```
add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_true' );
```

Before applying the filter:

![before](https://user-images.githubusercontent.com/19143190/69048176-c4675d00-09f4-11ea-948e-aece69e0c952.jpg)

After applying the filter:

![after](https://user-images.githubusercontent.com/19143190/69048184-c9c4a780-09f4-11ea-9e85-9136ac7a0eb4.jpg)

In your case, before changing the attribute's slug, the variation names appear in the title:

![variations_variations](https://user-images.githubusercontent.com/19143190/70435621-345e8580-1a7f-11ea-9120-33e75f40bbfd.jpg)

I've tried to follow the steps to reproduce the issue but I am not able to place an order or even a product to the cart after I change the slug of the global attribute. I am getting one of the following depending on whether I refresh the product page after I change the attribute's slug:

![var1](https://user-images.githubusercontent.com/19143190/70436101-6c19fd00-1a80-11ea-91fb-d777960ef41c.jpg)

Didn't refresh the page - can still select a size:

![мфк2](https://user-images.githubusercontent.com/19143190/70435963-20675380-1a80-11ea-8d39-93fb43b3179c.jpg)

But getting the following after placing the item to the cart:

![var3](https://user-images.githubusercontent.com/19143190/70436162-923f9d00-1a80-11ea-8076-05a7c6e6d7dc.jpg)

Here is a screencast as well:

![](http://g.recordit.co/vq7h07bBYE.gif)

I modified the size's attribute slug from `small` to `smallsmall`:

![var4](https://user-images.githubusercontent.com/19143190/70436357-011cf600-1a81-11ea-93da-28472f909093.jpg)

Overall, can't reproduce this so far. 

This issue could also possibly be connected to this one: https://github.com/woocommerce/woocommerce/issues/25133

**Comment by Navas-ahmed** [comment]
Thanks for looking at my request @juliaamosova . You Can change the Attribute slug name(https://prnt.sc/q8b3ol). From my end I can add the product to cart, there is no issue is facing for adding the product to cart after changing the attribute slug name.
Is there any Solution have to show my all variations on the order details page? (https://prnt.sc/q6zoj7).

**Comment by JaneH2019** [comment]
Where do I add this
add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_true' );

**Comment by juliaamosova** [comment]
>Where do I add this
add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_true' );

@JaneH2019 you can either add it to your theme's `functions.php` file or by using a [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin (which will easily preserve changes not to be lost during updates).

**Comment by JaneH2019** [comment]
Thank you for responding.  Working perfectly now

**Comment by juliaamosova** [comment]
Hi @Navas-ahmed, it seems that this thread can be closed here. However, please feel free to comment back in case I missed something and we'd take another look.
