### ISSUE TITLE
Having a new filter for woocommerce_product_edit_{prop} to filter values while edting a field in backend

### ISSUE THREAD

**Issue by dakshhmehta** [woocommerce/woocommerce#25229]
We at Romin Interactive, are having a use case, where we have a requirement that needs to change the value of regular_price in edit product form only.

We found that in WC_Data get_prop method, we have all props getting the filter in the following way:
woocommerce_product_get_{prop}, In our case, we can filter woocommerce_product_get_regular_price which actually only gets filtered when the context is view i.e tables and front-end views.

The code we found at https://github.com/woocommerce/woocommerce/blob/4bd6156bbb02f75b784d1ef5b31802c8ab0ea694/includes/abstracts/abstract-wc-data.php#L751

Now, we managed to add the following code to have a filter by adding the following snippet:
```php
	else if ( 'edit' === $context ) {
		$value = apply_filters( 'woocommerce_' . $this->object_type . '_edit_' . $prop, $value, $this );
	}
```

PS: A new function for edit_hook_prefix can be created to follow the standard of the existing codebase for that class similar to we have for get_hook_prefix method.

This has created the ability to filter specific property on the product, including variants to change a value of product before it being displayed to the form, and filtered value gets assigned to value attribute on a text field in the edit product page.

Hope this addition will help others as well.

If this is valid use case, we would love to send a PR for the same as we already have working and tested code in one of the production environment.

Thanks,
Daksh

**Comment by claudiosanches** [comment]
If this is valid use case, we would love to send a PR for the same as we already have working and tested code in one of the production environment.

By design we don't allow to filter or change raw (`edit`) values in our CRUD class, so this new filter isn't something that we are looking for include. You haven't said exactly what you hope to accomplish or solve with it, but generally if you are including an extra price it can be handled while saving the order data, for example.
