### ISSUE TITLE
Price filter excludes variations

### ISSUE THREAD

**Issue by Joyful99** [woocommerce/woocommerce#25261]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create variable product
2. Have a price filter in sidebar
3. Set price filter to exclude one of the variations (example cheapest variation is $10 most expensive one is $175. Set price filter to range between 0-100)

## Expected/actual behavior

When I follow those steps, I see...
That the variable product disappears when one of the variations doesn't fit the filter. While other variations might still be to the clients satisfaction. 

I was expecting to see...
The product still shown as part of it fits the requirements and the option could be well suited for the client. It shouldn't be ruled out just because one of the variations doesn't apply.

We sent this to support and they told us to put it here.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by tammullen** [comment]
Hi @Joyful99, thanks for raising this!

I can reproduce this on my test site using this variable product.
![Screenshot_2019-12-20_at_12_56_29](https://user-images.githubusercontent.com/24649833/71265694-a916a700-233e-11ea-97d9-4fe343523506.png)

Filtering works when my range includes all the variable prices
![Screenshot_2019-12-20_at_12_57_30](https://user-images.githubusercontent.com/24649833/71265698-aa47d400-233e-11ea-84f2-4450660d8cf9.png)

Doesn't work when one of the variations is outside the filter
![Screenshot_2019-12-20_at_12_57_53](https://user-images.githubusercontent.com/24649833/71265700-acaa2e00-233e-11ea-88cd-6e170c445a73.png)

I discovered this had been working as might be expected in v3.58 but started behaving like this in v3.6 onwards.
This screenshot is from v3.58
![Screenshot_2019-12-20_at_15_40_39](https://user-images.githubusercontent.com/24649833/71265902-27734900-233f-11ea-8c75-76481460da41.png)


I think this might have been caused by one of the commits prior to 3.6 beta release on March 15th 2019
https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-price-filter.php

**Comment by Joyful99** [comment]
Okay thank you. But... Now what? Will it be rectified in a future release? Do you have a solution that we can use? What do we do? :)

**Comment by KarlvanMen** [comment]
I must add that this is the reason I exclude price filter... Please, raise the priority. Cannot find a plugin that would solve this issue.

**Comment by gabrielfreisan** [comment]
I have a plugin that solves this problem "Advanced Product Filters"

**Comment by gabrielfreisan** [comment]
> I must add that this is the reason I exclude price filter... Please, raise the priority. Cannot find a plugin that would solve this issue.


I have a plugin that solves this problem "Advanced Product Filters"

**Comment by GeoJunkie** [comment]
Adding a report in 24201982-hc

**Comment by cl0udres** [comment]
Our customers asked us why the price filter doesn't work on variation products. It is very important to fix it asap, to let help our customers to search their perfect products to purchase.

Please, prioritize the fix of this issue!

Thanks.

**Comment by masteradhoc** [comment]
Same here, waiting for a fix

**Comment by ldr2273** [comment]
Also reported in 25351762-hc. 

As this is affecting more customers, is there a chance we could update the priority on this one?

**Comment by tammullen** [comment]
Thanks all for the additional feedback, raising the priority to High.

**Comment by Konamiman** [comment]
[Here's a pull request that fixes the issue](https://github.com/woocommerce/woocommerce/pull/29043), however the fix works only when the "Hide out of stock products" option is disabled. When it's enabled then variable products having variations within the price range will always be displayed, even if all of these are out of stock.

Example: a product has two variations with prices 150 and 250. The user filters for prices between 100 and 200. If the 150 variation is out of stock then the product should not be listed, but it will.

The reason why this case is not fixed is that due to how WooCommerce is currently architected it's not going to be as easy as the two-liner introduced in this pull request, it's a similar problem as [the infamous variations filtering issue](https://github.com/woocommerce/woocommerce/pull/26260) and fixing that "main" one will probably also help in completely fixing the filtering price issue. We at the Proton team are currently discussing what's the best way to approach such fix.

**Comment by cl0udres** [comment]
We're occurring the issue also without using the stock managing on our eCommerce, @Konamiman. Why?
