### ISSUE TITLE
Product data click close the entire box (only on block editor)

### ISSUE THREAD

**Issue by mariovalney** [woocommerce/woocommerce#25354]
**Describe the bug**
Product type select needs two clicks to work with blocks. First click just hide the content, second click shows correctly.

Update:
It happens on all inputs (including the checkboxes).  
Please, read first comment.

**To Reproduce**
1. Go to product edit page
2. Click on product type select
3. Click again on the same item

**Screenshots**
<img src="https://i.imgur.com/Z4kHH1J.gif">

**Expected behavior**
It should works as on classic editor: only with one click.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.18
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
```
</details>

**Comment by mariovalney** [comment]
I found the code:
```javascript
$( '#woocommerce-product-data' ).find( '.hndle' ).unbind( 'click.postboxes' );
// from assets/js/admin/meta-boxes-product.js
```
is loaded before
```javascript
$handles.on( 'click.postboxes', this.handle_click );
// from wp-admin/js/postbox.js.
```

As we can't rely on this "unbind", one fix would be:
```
$( '#woocommerce-product-data' ).find( '.hndle' ).bind( 'click.postboxes', function ( e ) {
    $( '#woocommerce-product-data' ).toggleClass( 'closed' );
    $( this ).unbind( 'click.postboxes' );
} );
```

As I don't like this so much (unbind inside bind), we can simply do not unbind event (removing this line) and toggle the class on the following event:
```
// Changing "click" to "click.postboxes"
$( '#woocommerce-product-data' ).on( 'click.postboxes', '.hndle', function( event ) {
  // If the user clicks on some form input inside the h3 the box should not be toggled.
  if ( $( event.target ).filter( 'input, option, label, select' ).length ) {
    $( '#woocommerce-product-data' ).toggleClass( 'closed' );
  }
});
```

**Comment by juliaamosova** [comment]
Hi @mariovalney,

Thank you for raising the issue. However, Gutenberg for products feature had been disabled in WooCommerce since version 3.4 - see https://github.com/woocommerce/woocommerce/issues/20201 for more details. 

Can you please confirm that you used a snippet below to activate it? I want to make sure that you don't have it working in WooCommerce 3.8.1 by default. 

```
function wplook_activate_gutenberg_products($can_edit, $post_type){
	if($post_type == 'product'){
		$can_edit = true;
	}
	
	return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'wplook_activate_gutenberg_products', 10, 2);
```

We are still working on enabling Gutenberg to create products but there are no concrete plans we can share at the moment. 

I see that you opened a PR to fix an issue (thank you for it!) but it will need to be closed since we officially don't support the feature in WooCommerec at the moment.

**Comment by juliaamosova** [comment]
@mariovalney,

As a part of this repository’s maintenance, I am closing this issue due to the fact that we don't officially support Gutenberg for products. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

I will need to close your PR as well, sorry!

**Comment by mariovalney** [comment]
Hi @juliaamosova.

I didn't know about [#20201](https://github.com/woocommerce/woocommerce/issues/20201) :sweat_smile: Thank you for explain that.

As I have to support blocks for my site, I [submitted a plugin](https://github.com/Vizir/blocks-for-products) which toggles into classic editor with WooCommerce meta_boxes and block editor without they. Maybe it can help people until support Gutenberg.
