### ISSUE TITLE
Variations show out of stock when inventory is managed at parent level

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce#25387]
**Describe the bug**

This problem occurs for a variable product where the inventory is managed at the parent level.

When the product goes out of stock, if an item is refunded and 'restock items' selected, the variations remain out of stock. In the product details, the parent shows `In stock`, and in the products page list it shows `Out of stock (1)`. 

**To Reproduce**

1. Create a variable product, where stock is managed at the parent product level. Set stock level to 1.
2. Purchase a variation
3. Refund the order, select 'Restock refunded items', confirm stock is returned
4. Go back to products list, see item shows `Out of stock` but also (1) item available
5. On the front-end product page, all variations show out of stock
6. In the admin, the product details show the parent item is in stock

**Screenshots**
Confirm stock returned

![https://d.pr/i/Fwc9qO](https://d.pr/i/Fwc9qO+)
Full Image: https://d.pr/i/Fwc9qO

Out of stock but 1 item available

![https://d.pr/i/YXs6r4](https://d.pr/i/YXs6r4+)
Full Image: https://d.pr/i/YXs6r4

Out of stock on product page

![https://d.pr/i/TNlso1](https://d.pr/i/TNlso1+)
Full Image: https://d.pr/i/TNlso1

In stock in product data

![https://d.pr/i/0hI3ur](https://d.pr/i/0hI3ur+)
Full Image: https://d.pr/i/0hI3ur

**Expected behavior**

On returning an item, using the 'restock items' checkbox, the item should go back in stock.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WooCommerce 3.8.1
WordPress 5.3.2
Theme: Storefront

**Comment by miroruse** [comment]
Hi, I reported the issue 5 months ago. Since then I have updated to the latest version of woocommerce 4.1.0 but the problem still persists. It doesn't matter 1 or 14 pcs are bought and tehn restocked, the variations remain out of stock while the general inventory displays 1 (14) pcs available. Is there going to be a solution for that?

**Comment by feofilaktov** [comment]
Hi! Unfortunately, we've got the same problem since Feb 2020, but there is no message of encreasing stock after cancelled order.  Just -1 every time. [Plugin](https://wordpress.org/plugins/woocommerce-auto-restore-stock/ ) doesn't work.  I've tried to make some modification - failed. Nothing happened. We were testing on Woocommerce 3.7.1 and 4.1.1 (last ver.).

**Comment by raharjoandrew** [comment]
Hai, I'm having the same issue. When can we expect an update for this? Thanks

**Comment by feofilaktov** [comment]
> Hai, I'm having the same issue. When can we expect an update for this? Thanks

Yes, it almost fixed four days ago. Look at the last pull request from @Konamiman. 
Wating for approving fixes and new versions updated.

**Comment by naman000** [comment]
i am getting same problem guys any solution???

**Comment by Creative5p** [comment]
Having the same issue right now as well.
