### ISSUE TITLE
To make Gutenberg work with WooCommerce and YoastSeo

### ISSUE THREAD

**Issue by kiber-chaka** [woocommerce/woocommerce#25414]
**Is your feature request related to a problem? Please describe.**
I think, if WooCommerce wil work with YoastSeo and Gutenberg it will be a good feature, becose those are very popular plugins. But it is impossible because of this bug: 
https://github.com/woocommerce/woocommerce/issues/25352

**Describe the solution you'd like**
I would like the bug to be fixed. 

**Describe alternatives you've considered**
WooCommerce default editor is very simple to my client, so may be I will try an other plugin editor, but I think, that is better to use something already built in.

**Additional context**
Gutenberg is default editor in WordPress, I think it is a good feature, - WooCommerce to work with WP default editor without a bugs. And it will unify the way of creation content on a website. I hope the bug is not hard to fix.

Thank you!

**Comment by juliaamosova** [comment]
Hi @kiber-chaka,

Thank you for opening this feature request. However, the title you selected is not exactly right:

>To make Gutenberg work with WooCommerce and YoastSeo

WooCommerce works with Gutenberg and WooCommerce also works with YoastSeo. The feature that currently is not a part of WooCommerce + Gutenberg workflow is product editing. 

Please know that we have been working on enabling Gutenberg for product editing for some time now and the work is still ongoing. 

>I think, if WooCommerce wil work with YoastSeo and Gutenberg it will be a good feature, becose those are very popular plugins. But it is impossible because of this bug:
#25352

There is a lot more work that needs to be done to fully enable Gutenberg for product editing than fixing this one bug you refer to. While from a technical standpoint, the Woo dev teams can handle converting our products over to using the new editor, there is the large ecosystem of plugins and extensions hooking into the product editor that will need to be updated to use it as well. That will require an effort and we are currently working on the transition plan. 

>I would like the bug to be fixed.

There is no bug for us to fix at the moment since the report is referring to the feature that we currently don't support. 

>Gutenberg is default editor in WordPress, I think it is a good feature, - WooCommerce to work with WP default editor without a bugs. And it will unify the way of creation content on a website. I hope the bug is not hard to fix.

There is no doubt that Gutenberg for product editing is a much needed and wanted feature but it is not about fixing one bug as I described above. 

I am going to close this issue since the title of it is not representative and also because enabling Gutenberg for product editing is a lot more than fixing one issue of a feature that we currently don't support. Please don't open any new issues related to that. 

You are welcome to subscribe to our dev blog where we often share news on upcoming features and releases: https://woocommerce.wordpress.com/.
