### ISSUE TITLE
Products Mis-labeled with "Free" Badge/Banner

### ISSUE THREAD

**Issue by dstana** [woocommerce/woocommerce#25432]
**Describe the bug**
Woocommerce is mistakenly adding the "Free" Badge to products. This applies to products listed in bulk, not on the product page itself. They also show up when plugins reference them (such as the Yith Product Slider).

**To Reproduce**
1. Create variable product
2. Add product variations
3. Create product variation with price of "0"
4. Disable 0 priced product variation
5. View shop page

**Expected behavior**
Variable products with a 0 priced variation that's disabled shouldn't get the "Free" badge.

**WordPress Environment**
5.3.2

WooCommerce version: |   | 3.8.1

</details>

**Comment by juliaamosova** [comment]
Hi @dstana,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported as I am missing some information to proceed. Can you please specify how do you "Disable 0 priced product variation" so that we could take the exact same steps? 

It will also help if you share screenshots showcasing the issue. 

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by dstana** [comment]
There's a checkbox whether to enable the product or not.

![snip1](https://user-images.githubusercontent.com/15884132/73569012-cb641000-4426-11ea-8690-2234352698f9.jpg)

**Comment by juliaamosova** [comment]
@dstana thanks for additional details. I am not able to reproduce what you are seeing. 

Here are my variations settings with the variation of color `pink` disabled and having a zero price:

![var1](https://user-images.githubusercontent.com/19143190/73771011-61749f00-4775-11ea-9f6d-f3f75d025861.jpg)

As a result, at the front-end I don't even have color `pink` available which is expected:

![Screen Shot 2020-02-04 at 5 36 22 PM](https://user-images.githubusercontent.com/19143190/73771049-73eed880-4775-11ea-9dca-0ee27b5cdb56.png)

Do you have many plugins installed on the site? Do you use one of our default themes?  

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by dstana** [comment]
I resolved this with some css, so it's been a non-issue for me since I reported it. However, it was triggered by an update to Woocommerce so I expect you might hear about it again from someone else.
