### ISSUE TITLE
Version 3.9.0 update

### ISSUE THREAD

**Issue by NicWhitham** [woocommerce/woocommerce#25462]
When running the database updater in the new version it deletes the file GeoLite2-Country.mmdb from the uploads folder.  This file is used by other plugins and should not be deleted.  Whilst I appreciate changes to Geolocation are included in the new release this is no reason to delete files used by other plugins.  The GeoLite2-Country.mmdb is still freely availabel to download the only change being that you need to register for an account now.  I have 11 sites running Woocommerce, it is frustrating enough that I need to log into each site and manually run the updater, but now I have to upload the file deleted by Woocommerce also.  Kindly ensure this does not happen again in future releases.  I would like to hear why Woocommerce is deleting files which are not associated with Woocommerce.

**Comment by claudiosanches** [comment]
Keeping the GeoLite2 database in the uploads folders is a violation of the MaxMind EULA, you can't keep copies of this database in an unprotected directory, so if you come across with plugins like that you should ask for the developers to fix it as soon as possible to comply with MaxMind EULA.

WooCommerce used to keep this file inside the uploads directory, that's why on the update we are moving it into a protected directory, to ensure all our users are complying with MaxMind EULA.
