### ISSUE TITLE
Checkout Address_2 field has duplicate 'optional'

### ISSUE THREAD

**Issue by addedlovely** [woocommerce/woocommerce#25510]
**Describe the bug**
The label for address_2 has a duplication of '(optional)'. 
It's in the field label, then also added in a `<span>` tag.

**To Reproduce**
1. Goto WooCommerce.com
2. Goto checkout.
3. Disable the css on the `.screen-reader-text` CSS class - or view source to see the markup.

**Screenshots**
<img width="1392" alt="Screenshot 2020-01-28 at 17 31 03" src="https://user-images.githubusercontent.com/565669/73302787-fa467000-41f3-11ea-815c-494652510236.png">

**Expected behavior**
Just one '(optional)'

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by addedlovely** [comment]
Suspect this is the offending line:
$address_2_placeholder = __( 'Apartment, suite, unit etc. (optional)', 'woocommerce' );

https://github.com/woocommerce/woocommerce/blob/6bed0db5189832d7094836e5d72d407577c6f61d/includes/class-wc-countries.php#L635

**Comment by juliaamosova** [comment]
Hi @addedlovely,

Thank you for taking the time reporting this bug, we really appreciate your help. I'll mark it as a `first good issue`.

**Comment by stuart-lambon** [comment]
Hi, I wanted to have a go at solving this for my first issue but I can see it’s slightly more complicated that first thought.

The (optional) text should be added here:

https://github.com/woocommerce/woocommerce/blob/86311a9903eae582a3367acf48628bd0c775548d/includes/wc-template-functions.php#L2646

Rather than in the text here:

https://github.com/woocommerce/woocommerce/blob/86311a9903eae582a3367acf48628bd0c775548d/includes/class-wc-countries.php#L653

This works to remove the double `(optional)` issue. However, you cannot really do this otherwise it will remove the `(optional)` from the field placeholder too. The main problem is that `address_2` does not have a label so it uses the placeholder instead.

Should I remove the (optional) from the location that the placeholder is converted to a label or is there a better way?

https://github.com/woocommerce/woocommerce/blob/86311a9903eae582a3367acf48628bd0c775548d/includes/class-wc-checkout.php#L274

I can see someone else tried this route but it seems a little hacky to me:
https://github.com/woocommerce/woocommerce/pull/25621

**Comment by 0dp** [comment]
Hi @juliaamosova 
Totally fine you closed #28984
Be that as it may, this issue was opened over a year ago.
I would love to make a PR, but have no idea about the consensus regarding which direction the team would go. Seeing there is already an unmerged PR (probably stale by now)

**Comment by shiftaltd** [comment]
still on 5.1. will be fixed on next release of woocomerce?

**Comment by juliaamosova** [comment]
>still on 5.1. will be fixed on next release of woocomerce?

@shiftaltd yep, the fix is currently planned to be a part of WooCommerce 5.2 release. You can always check the PR and see the milestone there: https://github.com/woocommerce/woocommerce/pull/29136.
