### ISSUE TITLE
Side-effects and WooCommerce stubs

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#25514]
Hello!
I run a small project that provides WC stubs for static analysis and IDE-s as the current source code [contains side-effects](https://github.com/php-stubs/woocommerce-stubs/blob/master/finder.php#L6-L25): if(defined), if(class_exists), class instantiations etc.
https://github.com/php-stubs/woocommerce-stubs

Do you plan to have clean OOP code?

- files with functions only
- files with 1 class per file

Thanks.

**Comment by peterfabian** [comment]
Hi @szepeviktor 
Thanks for the questions and providing the stubs!

While we do plan to clean up our code, it will be a gradual process and something that would take some time, especially given the backward compatibility constraints.
Side effects in the code are inevitable, otherwise, we could not use databases or files, plus lots of side effects are a consequence of using WordPress filters. Of course, going forward, we would like to minimize this behavior when possible. However, it is currently not our priority to refactor this code constructs.

That being said, we welcome PRs if yuo find good ways how to improve the code. Now that we increased the minimum PHP version to 7.0, we have a bit more room for improvements.

**Comment by szepeviktor** [comment]
Thank you for this length of an answer!

I think the if(defined(ABSPATH)) is here to stay in all files as many WC users are running on shared hosting.
