### ISSUE TITLE
Woo Product Vendors Addon: Backend "My Orders" not mobile-responsive for Vendors

### ISSUE THREAD

**Issue by micscr** [woocommerce/woocommerce#25538]
**Describe the bug**
The overview page in the vendors' backend (talking bout normal mobile browser view) which shows orders received is not responsive, i.e. it is not displayed correctly in smartphone portrait mode. Headlines of the cells overlapping each other and only order nummer is shown. Looks better when you turn the smartphone to landscape mode but this certain page is not mobile-ready at all.

**To Reproduce**
1. Go to Product Vendors Dashboard
2. Click on Orders
3. See error (in portrait mode on Android devices as well as on iPhones)

**Screenshots**
https://imgur.com/a/oh2LsId

**Expected behavior**
Cells shoud get displayed below eachother instead of side by side on mobile..

**WordPress Environment**
Latest versions of WooCommerce and Product Vendors Addons (bug been there before as well tho) - WordPress 5.2.x

**Comment by juliaamosova** [comment]
Hi @micscr,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by WooCommerce Product Vendors plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).

**Comment by micscr** [comment]
Hi @juliaamosova,

I already did - they told me to report the bug here 😃

Regards,
Michael
