### ISSUE TITLE
Tax class zero tax named with 0 in german translation

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#25539]
After each update of WooCommerce tax classes are installed. We had a tax free class which called in german language "Steuerfreie Raten" in earlier versions of WC. Til ver. 3.x they are installed as "0 price rate" or in german language "0 Preis Raten".

If I use too Germanized for WooCommerce, they use the older tax class names before WC 3.x. So after each update reduced and free classes are twice but with different names in tax settings.

It would be fine if you harmonize which class names are used/updated/installed.

**Comment by thomas-zg** [comment]
This is because of the german translation:
<img width="659" alt="grafik" src="https://user-images.githubusercontent.com/25877146/73536633-98ba1780-4426-11ea-89cb-295fbe192a3b.png">

The translation in https://translate.wordpress.org/projects/wp-plugins/woocommerce is maintained by the community, you can suggest the changes there.

**Comment by juliaamosova** [comment]
Hi @ajgw,

Thank you for submitting the issue. However, as @thomas-zg mentioned, you are getting `0 Preis` in German version of WooCommerce because this is how the community translated English `Zero rate`. On our end, we haven't changed the naming of `Zero rate`. 

You can download the German translation file here and verify as well:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/de/formal/?page=1

![Screen Shot 2020-01-31 at 12 01 30 PM](https://user-images.githubusercontent.com/19143190/73538270-7f16d100-4422-11ea-8fff-23a19dce2054.png)

You can use a plugin such as Loco Translate: https://wordpress.org/plugins/loco-translate/ to change the translation of that string to the one you like.
