### ISSUE TITLE
woocommerce_is_purchasable filter behaves like an "OR" filter, but need it to be "AND"

### ISSUE THREAD

**Issue by ytterx** [woocommerce/woocommerce#25558]
My problem is that I have a plugin that allows me to set "vacation time" on my woocommerce site. It allows me to disable purchases between certain dates. As this plugin uses -1 priority, the filter always get's called first. But if some other code/plugin add's another filter with a higher priority number, that overrides the first outcome of the filter, hence the "OR" behavior.

To be save I need to specify that this filter works as a "AND" behavior and stop executing other filters.

I'm aware this might sound more like a bug/feature request for Wordpress itself, as it touches core functionality.

**Describe the solution you'd like**
A feature / change to make the filter "woocommerce_is_purchasable" so I can disable puchases in a "OR" logic way.

**Describe alternatives you've considered**
I also created a bug report on the plugin I'm using:
https://github.com/mypreview/woo-store-vacation/issues/2

**Comment by helgatheviking** [comment]
If you want your filter of the `woocommerce_is_purchasable` to be the definitive one then instead of being _first_ shouldn't you try to be last? A later priority like `9999` might be good. 

Normally I'd say when filtering we should check if `$is_purchasable` is `false` and skip validation if it is, but my own plugin _specifically_ needs to tell WooCommerce that a not purchasable product is in fact purchasable.

**Comment by ObliviousHarmony** [comment]
Hello @ytterx,

Unfortunately, as you've discovered, all hooks are ran when a filter is executed. There isn't a way to short-circuit them. @helgatheviking has done a great job at explaining the possible solutions, so I don't think there's anything else for me to add here.
