### ISSUE TITLE
[4.0 beta] Nudge to update database is not very visible

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#25646]
With WC Admin managing WP notices, our notice to update WC core database could be hidden for a long time until someone notices it. We should find a better way of surfacing this information.

**Comment by DavidAnderson684** [comment]
Why is updating the WP database something that the user is told to do manually, rather than being done automatically? When it has to be done manually, it can get delayed; and the notice requesting it is only visible inside wp-admin (so if you update with another tool, e.g. WP-CLI or ManageWP, InfiniteWP, UpdraftCentral, etc, you don't even get to know it was needed).

If it's just "to remind the user to backup the DB first", then I'd question if this is necessary. The upgrade guide already recommends pre-upgrade backups. If users ignore that then it's unnecessary (and perhaps counter-productive) to ask again later.

**Comment by peterfabian** [comment]
Good question! I would guess it has something to do with the fact that the user might have e.g. automated plugin updates turned on/hit update too soon, but then they want to backup their db before performing the db migration? 

I'll try to find out more.

**Comment by DavidAnderson684** [comment]
It might be worth knowing how often database upgrades actually fail. If they don't, then making all users upgrade the database manually is unlikely to be worth sparing the users who didn't take a pre-upgrade backup. I think I've seen Mike explain somewhere that if you don't upgrade your database, then until you do, features can be broken.

**Comment by peterfabian** [comment]
> I think I've seen Mike explain somewhere that if you don't upgrade your database, then until you do, features can be broken.

From the nature of how things work, I think this is accurate. 

I've heard that the requirement of the user action gives an opportunity to make the db backup, which is a valid argument, I think.

We probably won't be changing this with 4.0 release, so the current course of action is to make the notice more visible.
