### ISSUE TITLE
I am not able to save my settings under woocommerce settings

### ISSUE THREAD

**Issue by giridhar196** [woocommerce/woocommerce#25655]
Hi,
I am not able to save my address details, privacy policy link shop page target everything is going to blank when i am clicking save. I tried to delete woocommerce plugin and install again but i am not able to see any changes still they are saving blank inputs.
![Woocommerce Settings](https://user-images.githubusercontent.com/24917007/74401368-0878cb00-4e47-11ea-8711-48f65b73e1eb.PNG)

**Comment by tammullen** [comment]
Hi @giridhar196 
​
Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​
Label:

**Comment by giridhar196** [comment]
I have disabled all plugins and then it worked
