### ISSUE TITLE
Products admin page does not call `default_hidden_columns`

### ISSUE THREAD

**Issue by gael-ian** [woocommerce/woocommerce#25673]
**Describe the bug**

The `default_hidden_columns` filter allows to define columns that will be hidden by default for every new user on an admin page. The WooCommerce Products admin page does not apply use this filter (but Product Categories, Product Tags and others do).

**To Reproduce**

1. Set a filter on `default_hidden_columns`. ie:  
    ```php
    add_filter('default_hidden_columns', function($hidden, $screen) {
      if ($screen->id == 'edit-product') die("You'll never see this");
      return $hidden;
    }, 10, 2);
    ```
2. Go to the WooCommerce Product page and see it as usual (but the script should have died, due to the filter)

**Expected behavior**

The `default_hidden_columns` filter should be called, as it is on any other page.

**Comment by vedanshujain** [comment]
I added the exact code snippet in my local installation and looks like its executed. `default_hidden_columns` is called by WordPress source code, which means that it should be available for all listing screens (unless it's explicitly removed).

My guess is that the file where you added the snippet is also not loaded (or maybe it's loaded after the `default_hidden_columns` is already applied)?

Anyways, since this does not look like a WooCommerce bug, I am closing the issue. But feel free to comment back if that is not the case and we can investigate more.

**Comment by vedanshujain** [comment]
I tried with Code snippets plugin as well, and it worked.

**Comment by pstoica** [comment]
I just stumbled upon this issue for the orders page. The products page seems to correctly call the filter. Swap `product` with `shop_order` and you'll see it never runs.
