### ISSUE TITLE
Additional Hooks Inside Order Preview Modal

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#25671]
Hi guys,

Could you please consider to add some hooks inside preview order template ( woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php -> get_order_preview_item_html() method )?

For example, in my case I need some hook inside product column case, so I can be able to add additional information about that product. 

You already have hooks for that inside html-order-item.php file

```
do_action( 'woocommerce_before_order_itemmeta', $item_id, $item, $product ); 
and 
do_action( 'woocommerce_after_order_itemmeta', $item_id, $item, $product ); 
```

which I used to add additional content https://imgur.com/xHhcxKU but I can't add it inside preview modal https://imgur.com/VtHQVNe .

Example hooks you can add https://imgur.com/Dg73Om9

Thanks for your time.

Best regards,
Nenad

**Comment by vedanshujain** [comment]
Based on your example images and if you are comfortable with code (which looks like you are) I'd recommend that you go ahead with one of the following approaches:

#### Approach 1
Use these already existing filters to show product details:
1. `woocommerce_admin_order_preview_line_item_columns` to add a new column and then 
2. `woocommerce_admin_order_preview_line_item_column_' . sanitize_key( $column )` to populate this column with the line item details.

This way you will be able to add data using already existing filters, although they will not be shown below the product name, looks like these filters will serve the purpose.

#### Approach 2
If you do want to show the details below the product name itself, you can also use `woocommerce_order_item_get_formatted_meta_data` filter to add data in this format:
```php
array(
	'key'           => "any key",
	'display_key'   => "display label",
	'display_value' => "display format",
);
```
Although, if you go with this approach, make sure that you check and return early if the current screen is anything other than order preview modal. The reason is, `woocommerce_order_item_get_formatted_meta_data` filter is called in lots of other scenarios as well then just in order preview modal, so the potential for bugs and performance issues is bigger if you are not careful.

I would personally recommend going with approach 1.

I am closing this issue now, but feel free to comment if you have any questions.

**Comment by NenadObradovic** [comment]
Hi there,

Thanks for your response.

Regarding approach 1, that can be a solution to add additional columns inside a table but I rather need some hook to add additional information below the product title.

Please check screenshots https://imgur.com/a/NaoDuVc

As you can see, your solution works fine to add additional column inside table but if there is a hook (like I added manually inside your plugin file - screenshot 2) then I will be able to add information below the title - screenshot 3

You already have similar hooks on other places (templates) so maybe you can also add it here :)

Thanks for your time.

Best regards,
Nenad
