### ISSUE TITLE
[4.0 beta1]: Disable WooCommerce Admin plugin when WooCommerce 4.0 is installed? 

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce#25685]
**Is your feature request related to a problem? Please describe.**

This is not really a problem, but since WooCommerce Admin is already included in WooCommerce 4.0, I believe it would make sense to disable WooCommerce Admin plugin when the site is updated to WooCommerce 4.0. 

Currently, if the site is updated to 4.0 and if WooCommerce Admin is already installed, it stays activated.
![https://d.pr/i/JHw5QA](https://d.pr/i/JHw5QA+) 
Full Size: https://d.pr/i/JHw5QA

**Describe the solution you'd like**
Disable WooCommerce Admin when WooCommerce is updated to 4.0, and show a dismissable notice to the site admin informing that WooCommerce Admin is now included in core WooCommerce, so they do not need the WooCommerce Admin plugin separately.

**Comment by rrennick** [comment]
> Disable WooCommerce Admin when WooCommerce is updated to 4.0

@anant1811 Thanks for the suggestion. There are 2 reasons we won't be doing that

- There isn't any way to reliably determine which active plugin is WC Admin. Hypothetically, an install could have WC Admin installed in the `woocommerce` folder and WooCommerce installed in the `woocommerce-admin` in which case WC would be deactivating itself instead of WC Admin.
- We encourage developers and beta testers to use the latest versions of the REST API & Product Blocks by installing the standalone plugin(s) and keeping them at the latest version. WC Admin will follow the same development model.

> show a dismissable notice to the site admin informing that WooCommerce Admin is now included in core

We will be adding a notice for store owners that will vary based on version comparisons.

**Comment by juliaamosova** [comment]
>We will be adding a notice for store owners that will vary based on version comparisons.

The notice was added via https://github.com/woocommerce/woocommerce-admin/pull/3687. 

Closing this issue.
