### ISSUE TITLE
Coupon discount is being applied to multiple products when "Limit usage to X items" set to 1

### ISSUE THREAD

**Issue by mpemburn** [woocommerce/woocommerce#25693]
**Describe the bug**
This bug is related to the WooCommerce Subscriptions plugin.

When adding a coupon to a renewal subscription whose purpose is to apply a 100% discount to only one cart item of a given type, the discount is actually applied to _all_ items of that type.

**To Reproduce**
1. Create a coupon that meets the following criteria:
- Discount type: Recurring Product % Discount
- Coupon amount: 100
- Products: Add several subscription products.
- Set "Limit usage to X items" to 1
- Leave all other settings at default

2. Create a Subscription and add at least two of the products specified in the coupon.
3. Create a Pending Renewal Order
4. Pay for the order.

**Screenshots**
![Coupon Cart Bug](https://user-images.githubusercontent.com/461989/74685600-fc6d7000-519c-11ea-98d2-1aec2796fc32.png)

**Expected behavior**
Only one of the products should receive the discount.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by LukeAbell** [comment]
@thenbrent Any ideas here?

**Comment by LukeAbell** [comment]
I think this is the same issue as reported above: https://wordpress.org/support/topic/woocommerce-subscriptions-recurring-coupon-usage-restrictions/#post-11140792

**Comment by juliaamosova** [comment]
Hi @mpemburn,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/). Over there, they will be able to confirm the issue and file it in the correct repository (as it is private) and keep you updated on the status of it.
