### ISSUE TITLE
WooCommerce Booking Receipts show incorrect dates

### ISSUE THREAD

**Issue by barrymdrone** [woocommerce/woocommerce#25758]
Hello,

Recently we began seeing WooCommerce product booking invoices showing old bookings from the year 2015 that have no relationship with the current customer, date or product. In other words the booking goes through but shows both an old, unrelated, completed booking and the new completed booking. I've attached a copy of the most recent issue;

Booking #12227 for August 15 and 16, 2015 (invalid) shows up on booking #21916 which is a valid booking submitted yesterday.

Let me know if you need anything further on this, thanks.

Barry
[Booking Invoice.pdf](https://github.com/woocommerce/woocommerce/files/4250952/Booking.Invoice.pdf)

**Comment by juliaamosova** [comment]
Hi @barrymdrone,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Bookings plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).

**Comment by MichaelDrumSmith** [comment]
I hope you see this @barrymdrone , did you find a solution?
