### ISSUE TITLE
Fees/order not recalculated on later payment via other gateway

### ISSUE THREAD

**Issue by FritzHerbers** [woocommerce/woocommerce#25777]
**Describe the bug**
Fees are not recalculated on a saved order with payment over another gateway.

**To Reproduce**
We have two payment gateways: PayPal and bank transfer. We add fees when customers use the PayPal gateway. 
When a customer orders with a bank payment and later, via the account/order page, uses the pay action, the order is not recalculated upon changing the payment gateway to PayPal.

We never understood, why woocommerce puts an order with bank transfer ON-HOLD and not on PENDING-PAYMENT, therefor we use the plugin woocommerce-order-statuses to allow the same actions as when the order would be on PENDING-PAYMENT.

Your quickest answer could be that you say, ON-HOLD, the order can not be changed anymore. Changing states/adding actions is not supported.

The problem also exist in the following situation, without the woocommerce-order-statuses plugin. The customer selects PayPal, cancels, there are unexplainable occasions that orders get saved in the PENDING-PAYMENT status, these were calculated with a fee. The customer goes like above via the account/order pay to checkout and selects bank payment. The order gets saved (last state) with PayPal fees.

**Expected behavior**
1. We are using woocommerce-order-statuses only for the above payment button. It would be nice it would be configurable in which state a bank payment order will get saved. In our case we would set it to PENDING-PAYMENT. 

2. On PENDING-PAYMENT a recalculation should be done or should be configurable when changing the payment gateway. Until payment an order is not final.

3. When you can not fix 1 and 2, then the customer should not be able to change the payment gateway anymore. The customer will create a new order via his preferred gateway and we delete the previous order.

9. The "diagram of order statuses" does not seem to be up-to-date: https://docs.woocommerce.com/document/managing-orders/

**WordPress Environment**
<details>
```
Woocommerce 3.8.1
WooCommerce Order Status & Actions Manager 3.5.7
WooCommerce PayPal Checkout Gateway 6.1.8
```
</details>

**Comment by juliaamosova** [comment]
Hi @FritzHerbers,

Thank you for taking the time to report this bug, we really appreciate your help. 

There seems to be a lot going on in your report so let's break it down a bit:

>We add fees when customers use the PayPal gateway. 

Can you please confirm how do you add a fee? Do you use [Payment Gateway Based Fees](https://woocommerce.com/products/payment-gateway-based-fees/) plugin? We need it so that we could reproduce the same issue you are having. 

>We are using woocommerce-order-statuses only for the above payment button. It would be nice it would be configurable in which state a bank payment order will get saved. In our case we would set it to PENDING-PAYMENT.

This is a feature request that should be logged separately. Would you please do that? 

>The "diagram of order statuses" does not seem to be up-to-date: https://docs.woocommerce.com/document/managing-orders/

Would you please specify what is not correct in this diagram in your opinion?

**Comment by FritzHerbers** [comment]
Hello Julia, thanks for reviewing my issue.

We are using the free plugin "Payment Gateway Based Fees and Discounts for WooCommerce" as we only have to set a fee of 5% for PayPal,  https://wordpress.org/plugins/checkout-fees-for-woocommerce/

With checkout `<form name="checkout" method="post" class="checkout woocommerce-checkout" action="https://domain.com/en/checkout/" enctype="multipart/form-data" novalidate="novalidate">` several event handlers exist, without looking deeper into it, pointing to woocommerce.

When paying (from my account/orders/pay) many of the event handlers are gone 
`<form id="order_review" method="post" novalidate="novalidate">`.

Hope you can have a further look into this issue.

For the other two points I will create separate issues.

**Comment by juliaamosova** [comment]
Hi @FritzHerbers,

Apologies for the delayed response and thank you for providing additional details. I downloaded [Payment Gateway Based Fees and Discounts for WooCommerce](https://wordpress.org/plugins/checkout-fees-for-woocommerce/) plugin and managed to reproduce the issue. 

Documenting my steps below. 

1) Enabled `Bank transfer` and `Stripe` payment methods;
2) Added $11 fee for using Stripe;
3) I can see that if I select Stripe during checkout, $11 fee is being added to the total (as expected):

![stripe1](https://user-images.githubusercontent.com/19143190/76467254-92bd3c00-63bf-11ea-9f89-8779e7ebc589.jpg)

4) But I decide to proceed with Bank transfer and no fee is being added (as expected);
5) Next, I go into `My account / orders` and want to pay for the order:

![stripe2](https://user-images.githubusercontent.com/19143190/76467311-b7b1af00-63bf-11ea-828b-4751f6077c3b.jpg)

5) I am being presented with an order payment screen. If I select `Bank transfer`, no fee is added (as expected):

![stripe3](https://user-images.githubusercontent.com/19143190/76467345-d152f680-63bf-11ea-89ea-5407fb6c6e59.jpg)

6) If I select to pay via `Stripe`, still no fee is being added. But I should see $11 fee added:

![stripe4](https://user-images.githubusercontent.com/19143190/76467386-e891e400-63bf-11ea-8e7b-f4418fe3465b.jpg)

7) Placed order. No fee for using Stripe:

![stripe5](https://user-images.githubusercontent.com/19143190/76467406-f3e50f80-63bf-11ea-9662-a18f403bc246.jpg)

I am marking this a `high` priority since we had several reports of this issue over a short period of time. 

>For the other two points I will create separate issues.

I don't think you created issues for these as I couldn't find them. However, if you did, please paste links to them here so I could take a further look. Thanks!

**Comment by vedanshujain** [comment]
@juliaamosova This should actually be moved to https://wordpress.org/plugins/checkout-fees-for-woocommerce/ support forum. Unfortunately, we do not control the effected code, so we can't do much here. Feel free to close the issue after those folks are aware.

**Comment by FritzHerbers** [comment]
@vedanshujain 
@juliaamosova 
The problem is not within the fees plugin. 
The problem is that WooCommerce does not initiate a callback as described in https://github.com/woocommerce/woocommerce/issues/25777#issuecomment-593142212

This problem can only be solved in WooCommerce.

**Comment by vedanshujain** [comment]
@FritzHerbers Events will be different in these cases, because during checkout, the order is not yet created, and events related to cart are invoked, whereas, in the previous orders page, the order is now created and events related to order will be invoked. 

They invoke different events by design, so ideally the fees plugin also needs to hook into orders event along with the cart. That said if there is no order event which fees plugin can hook into, we will definitely look into adding one.

**Comment by juliaamosova** [comment]
@FritzHerbers I am closing this issue as per @vedanshujain's explanation above. Please reach out to the developers of `Checkout fees for WooCommerce` plugin. Vedanshu's comment should help them resolve the issue.

**Comment by FritzHerbers** [comment]
@vedanshujain 
@juliaamosova 
We have opened an issue at the plugin [https://wordpress.org/support/topic/fees-order-not-recalculated-on-later-payment-via-other-gateway/](https://wordpress.org/support/topic/fees-order-not-recalculated-on-later-payment-via-other-gateway/) 

> ideally the fees plugin also needs to hook into orders event along with the cart. That said if there is no order event which fees plugin can hook into, we will definitely look into adding one.
As you mentioned, when there is none, you will implement one. 
Having plugins to look if they can hook into something is just pushing the issue away from you and is in my eyes not goal-oriented. 
Can you please be more specific which hook exists and needs to be used to resolve this issue.

**Comment by vasikgreif** [comment]
@vedanshujain
@juliaamosova
@FritzHerbers 

The order exists already on the pay for order page, and there does not seem to be any infrastructure for adjusting the order. What I did was I added a custom REST endpoint, I'm calling it when the payment method changes, check if the payment method has some fee. If so I check if the fee is already added, if not, I add it. If the method has no fee, I check if the order contains the fee, if so I remove the line item.

Seems like a hack, but it works.

**Comment by Sidlegionair** [comment]
@vasikgreif Mind sharing your solution in a gist or something to help us out?

**Comment by vasikgreif** [comment]
@Sidlegionair Sure, it was something along these lines: https://gist.github.com/vasikgreif/d4ac3d1f619da7a86f3d58319e245094

**Comment by Sidlegionair** [comment]
@vasikgreif Thanks, much appreciated!

**Comment by PV-Web** [comment]
> @Sidlegionair Sure, it was something along these lines: https://gist.github.com/vasikgreif/d4ac3d1f619da7a86f3d58319e245094

Would love to learn how you did this as we have the same problem. But the link seems no longer working. Can you share you code here perhaps?

**Comment by PV-Web** [comment]
Did you found a solution/ hack for this problem?

Would love to learn how you did this as we have the same problem. But the link above seems no longer working. Can you share you code here perhaps?

**Comment by PV-Web** [comment]
@Sidlegionair @vaclavgreif 
The link above seems to be no longer working
Would love to learn how you did this as we have the same problem. Can you share you code here perhaps? Would appreciate it a lot. Thanks
