### ISSUE TITLE
PROBLEMS WITH WOOCOMMERCE AND WORDPRESS

### ISSUE THREAD

**Issue by Pablitomg04** [woocommerce/woocommerce#25789]
I have a problem: My ecommerce webpage (foreverspain.com) is perfect, and I´m happy with that. But when I look at the shop and at the products that appear in the homepage, the products cover the price and the name, and it's like they slide losing all the space between them, making the web look worse.

How can I solve this? Is a Woocommerce problem? A code problem? Or is because of my theme Kona eCommerce?? I hope you can help me

**Comment by GlennMartin1** [comment]
This is a theme issue, not a WooCommerce issue. 

Contact the support folks for your theme.

**Comment by peterfabian** [comment]
Hi @Pablitomg04 , as Glenn said, this is most likely a theme related problem. Please contact your theme developer. If you are unsure about where the problem comes from, a good start is to use the [self-service troubleshooting guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/).
