### ISSUE TITLE
Selling of a produdct when the visibility is hidden!

### ISSUE THREAD

**Issue by emoop** [woocommerce/woocommerce#25803]
**Describe the bug**
When a product visibility is set to visible and a customer puts it in the cart, after that for some reason(wrong picture) we make the product visibility hidden, the next day when the customer finishes his order, this hidden product is also in the order. The product is hidden but is in stock. Woocommerce should check the product visibility at the checkout, because confusing situations may arise. 

**To Reproduce**
1. Create a varaible "product1" with some vairiations and set the visibility to visible
2. In front end add the "product1" to the cart
3. In Admin set the visibility of "product1" to hidden
4. In front end add another product which we wil call "product2", to the cart and finish the order

**Expected behavior**
In the admin you will see that both "product1" and "product2" are in the order, while only "product2" should be available.

**Comment by juliaamosova** [comment]
Hi @emoop 

Thanks for raising the issue. While I can reproduce it, I am not sure I agree with your statement:

>Woocommerce should check the product visibility at the checkout, because confusing situations may arise.

When you mark the product visibility to hidden, it means that it is hidden from the site but it still exists. Anyone, who has the link to the product will still be able to view it which is why it is available via cart if it was already placed there. 

I will mark this issue with the `question` label which means something for us to discuss further with the WooCommerce core team. We will update the issue as soon as we'd be able to review it as a team. Thanks for your patience!

**Comment by barryhughes** [comment]
Going to close this: I agree with @juliaamosova that the described behavior is expected. 

As [described here](https://woocommerce.com/document/managing-products/), setting the catalog visibility to hidden means that the product will be _only visible on the single product page – not on any other pages ..._ but it does not remove it from sale.

What you could do in this sort of scenario in future, though, is set the product to draft. Then if a customer has the item in their cart, it will be removed and they will see a notification looking something like this:

<img width="791" alt="can-no-longer-be-purchased" src="https://user-images.githubusercontent.com/3594411/152067004-b14dd71d-d9cb-4a25-8c8f-cb119d179b28.png">
