### ISSUE TITLE
Woocommerce email order images are cropped

### ISSUE THREAD

**Issue by bon-opina** [woocommerce/woocommerce#25813]
Order images are cropped in email, and there is no option where we can remove the cropping of the image:

STR:
1.) Buy anything with portrait images
2.) Look at the image

It seems it has been cropped.

Example image:
![image](https://user-images.githubusercontent.com/42927885/75838966-1c03bb80-5d8d-11ea-86d5-6c044be03e3c.png)

Can we add an option that this can be removed?

**Comment by juliaamosova** [comment]
Hi @bon-opina,

Thank you for submitting the issue. However, by default, WooCommerce order emails don't include product images. If you have them included, it is likely because you are using a plugin that adds that functionality or you are using some custom code that adds it. 

I can recommend using the following snippet that adds product images to the WooCommerce emails:

```
/**
 * Adds product images to the WooCommerce order emails table
 * Uses WooCommerce 2.5 or newer
 *
 * @param string $output the buffered email order items content
 * @param \WC_Order $order
 * @return $output the updated output
 */
function sww_add_images_woocommerce_emails( $output, $order ) {
	
	// set a flag so we don't recursively call this filter
	static $run = 0;
  
	// if we've already run this filter, bail out
	if ( $run ) {
		return $output;
	}
  
	$args = array(
		'show_image'   	=> true,
		'image_size'    => array( 100, 100 ),
	);
  
	// increment our flag so we don't run again
	$run++;
  
	// if first run, give WooComm our updated table
	return $order->email_order_items_table( $args );
}
add_filter( 'woocommerce_email_order_items_table', 'sww_add_images_woocommerce_emails', 10, 2 );
```

The image comes in full in emails and looks like this after using the snippet above:

![image](https://user-images.githubusercontent.com/19143190/76363351-355eb780-62f9-11ea-863d-a939590eafff.jpg)

In order to use the snippet, it will be great to find the way you are adding images currently and disable it. Then you can add the snippet I provided. You can use a [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin to do that. 

I am closing this issue since there is no action for us to take.
