### ISSUE TITLE
Coupons not working with Subscriptions

### ISSUE THREAD

**Issue by stasbamiza** [woocommerce/woocommerce#25818]
**Describe the bug**
I install WC Subscriptions and when I go to WC Coupons I got error at 

> **Fatal error**: Uncaught Error: Call to undefined method stdClass::get() in  */woocommerce-subscriptions/includes/class-wcs-cart-renewal.php:740*

**To Reproduce**
1. Install WC
2. Install WC Subscriptions
3. Add coupon
4. Check coupon table

**Screenshots**
![image](https://user-images.githubusercontent.com/10279896/75908629-330ce100-5e53-11ea-96b6-486bb7cdd6d0.png)

**Expected behavior**
Should work without errors

**Isolating the problem (mark completed items with an [x]):**
- [ ] I created hot fix and added additional checks
```php
if ( ! is_object( WC()->session ) || !(WC()->session instanceof WC_Session) || !(WC()->session instanceof WC_Session_Handler) ) {
  return $data;
}
```

**WordPress Environment**
```
<details>
WordPress environment
--
WooCommerce version: |   | 3.9.2
WordPress version: |   | 5.3.2
WordPress memory limit: |   | 256 MB

Server environment
--
PHP version: |   | 7.3.15
```
</details>

**Comment by juliaamosova** [comment]
Hi @stasbamiza,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/). 

Our Tech Support Engineers will be able to verify the bug further with you and file it in the right place. They will also provide you with updates on the fix. I can't simply move your issue to another repository and have you follow there as it is not public. Thanks for understanding!
