### ISSUE TITLE
Refunded PayPal-Fees are not correctly booked into the order

### ISSUE THREAD

**Issue by FritzHerbers** [woocommerce/woocommerce#25841]
**Describe the bug**
PayPal refunds work, however the refunded PayPal-Fee on the refunded amount is
- for older Woocommerce versions: subtracted on the PayPal-Fee resulting in incorrect negative amounts. The Customer-Refunded-Amount was shown.
- for Woocommerce 3.8.1: the PayPal-Fee at the totals is not changed. The Net-Refunded-Amount is visible on a separate line. The refunded PayPal-Fee is not visible (not subtracted from the Totals-PayPal-Fee), no Net-PayPal-Fee is shown.

The correct values are returned form PayPal, but not booked in WC.
    [FEEREFUNDAMT] => 18.50
    [GROSSREFUNDAMT] => 420.60
    [NETREFUNDAMT] => 402.10

In the custom fields, the refunded PayPal-Fee doesn't show up either.

**Expected behavior**
After a refund the customer-refunded-amount, the net-refunded-amount and the refunded PayPal-fee should be appended to the order (on the already existing net-refunded-amount line).
It should be possible and also later be visible when a further refund is made (a new line).

**WordPress Environment**
WooCommerce: 3.8.1
WooCommerce PayPal Checkout Gateway: 1.6.18

**Comment by juliaamosova** [comment]
Hi @FritzHerbers,

Apologies for the delayed response! 

I don't fully understand how to replicate the issue here. Can you please provide clear steps with examples of calculations you expect and what do you see instead? Screenshots will be helpful as well. 

Here I made a manual refund via PayPal and here is how the order page looks (using WooCommerce 4.2 beta):

![pp3](https://user-images.githubusercontent.com/19143190/81987513-c870e200-9607-11ea-8672-9c29e29feb21.jpg)

**Comment by FritzHerbers** [comment]
My issue was based on 3.8.1.
What I see from your screenshots, 4.2-beta, the total _customer-refunded-amount_ is shown at the totals.

As PayPal does not refund PayPal fees since April 2020, a distinction of _net-refunded-amount_ and the _refunded PayPal-fee_ are not needed anymore. 
Although during the last month due to Corona they refund PayPal fees again, but this will for sure only be for a very short time.

**Comment by juliaamosova** [comment]
Thanks for your quick follow-up @FritzHerbers!
