### ISSUE TITLE
Rates shouldn’t fail when you select rates for a country with states

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce#25854]
**Describe the bug**
Following this bug here https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/1895 and this discussion here with @mikejolley p1583754141068600-slack-C8X6Q7XQU

What happens is, when you set a shipping zone to a country and that country has states defined in Woo core (spain, US...), calculating shipping based on country alone will fail, for other countries it works fine.

**To Reproduce**
1. Setup shipping zones to a whole country with states (Spain, US)
2. try to estimate shipping on Cart with only setting the country.
3. no rates will return

**Comment by juliaamosova** [comment]
Hi @senadir,

Thank you for submitting the issue. I am not sure this is a bug though and rather works as expected. 

My shipping setup as follows:

<img width="1435" alt="Screen Shot 2020-03-10 at 2 20 02 PM" src="https://user-images.githubusercontent.com/19143190/76345755-464c0080-62da-11ea-9342-1044629d1414.png">

On the cart page, I am presented with a message letting me know that I need to enter the address in order to see the shipping cost:

![ship](https://user-images.githubusercontent.com/19143190/76346292-210bc200-62db-11ea-81b1-8db5171025b4.jpg)

Upon clicking on the option to enter the address, I get the country where I am located prepopulated (United States):

<img width="670" alt="Screen Shot 2020-03-10 at 2 23 59 PM" src="https://user-images.githubusercontent.com/19143190/76346352-3f71bd80-62db-11ea-8d7b-6ff5e22947f0.png">

Upon selected the state, city and zip code, I am getting both `Flat rate` and `Free shipping`:

![shippinbg](https://user-images.githubusercontent.com/19143190/76345936-91feaa00-62da-11ea-904b-bc1b0b342d37.jpg)

AFAIK, this is all working as expected. I am ccing @claudiosanches here to see if he knows more about the nature of this flow.

**Comment by senadir** [comment]
If you try to only enter a country alone, no rates will return, we need rates to return with a country alone since we’re implementing live rate updates while you type

**Comment by juliaamosova** [comment]
Thanks for the reasoning behind the need @senadir. Copying @claudiosanches and @peterfabian here for further discussion and prioritization.

**Comment by peterfabian** [comment]
another report here: https://wordpress.org/support/topic/no-shipping-options-to-canada-uk-new-zealand/

I think it needs to be changed...

**Comment by matteopadovanbox** [comment]
Same problem here in our ecommerce www.fortuny.shop. 
Before the latest Woocommerce update everything worked fine, now it's necessary to fill all the address fields in the checkout in order to display the shipping cost. 
It's very time consuming both for the compay's employees, that quickly need shipping prices for quotations, and for the website users that want to know the amount of shipping costs before buying.

**Comment by vzeazy** [comment]
The patch is here:
https://github.com/woocommerce/woocommerce/pull/25916/commits/8c0f4a1204c6f487811f3853e83904d1a30022ac

A small adjustment to includes/class-wc-shipping.php

Hopefully this is going to be in the next release. For those with issues now, manual application resolves the issue :)

**Comment by matteopadovanbox** [comment]
After another user suggested to me the following solution, I solved the problem:
https://wordpress.org/support/topic/shipping-zones-requiring-states/#post-12550750

You'll have to update the **woocommerce\includes\class-wc-shipping.php** file with the following code at line 287:
`public function is_package_shippable( $package ) {
	if ( empty( $package['destination']['country'] ) ) {
		return true;
	}
	// $country = $package['destination']['country'];

	// $countries = array_keys( WC()->countries->get_shipping_countries() );
	// if ( ! in_array( $country, $countries, true ) ) {
		// return false;
	// }

	// $states = WC()->countries->get_states( $country );
	// if ( is_array( $states ) && ! empty( $states ) && ! isset( $states[ $package['destination']['state'] ] ) ) {
		// return false;
	// }

	//return true;
}`

Now that I clicked on the patch link I see it's the same solution.
Thank you.
