### ISSUE TITLE
Critical error with new Action Scheduler Package

### ISSUE THREAD

**Issue by streamworksaudio** [woocommerce/woocommerce#25909]
I did not notice this last night when I first install WC 4 on my test virtual machine, but today I am getting some strange errors with the Action Scheduler package whenever I visit the Scheduled Actions in WooCommerce or even the WordPress Seceduled Actions page.  Here is the error that is put into the log file....

> 2020-03-13T08:39:29+00:00 CRITICAL Uncaught InvalidArgumentException: Invalid action ID. No status found. in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:740
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(326): ActionScheduler_wpPostStore->get_status('2')
#1 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ListTable.php(533): ActionScheduler_HybridStore->get_status('2')
#2 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php(659): ActionScheduler_ListTable->prepare_items()
#3 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_AdminView.php(94): ActionScheduler_Abstract_ListTable->display_page()
#4 /var/www/html/wp-includes/class-wp-hook.php(288): ActionScheduler_AdminView->render_admin_ui('')
#5 /var/www/html/wp-in in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php on line 740

I do have WP-Cron disabled on this  server, I run cron jobs from Ubuntu and wp-cron.php 

Perhaps a bug in the new package?  Anyway to disable this package?

**Comment by peterfabian** [comment]
Hi @streamworksaudio 

thank you for reporting the problem and apologies for the issues. Since ActionScheduler is now an integral part of WooCommerce, there isn't an easy way how to disable it, as the WC code sometimes expects some queue processing system to exist. We have seen similar reports and are [looking into the issue over at the Action Scheduler repository](https://github.com/woocommerce/action-scheduler/issues/486), please follow the progress over there. 
I will close this as a duplicate report but feel free to comment if you find out more.
