### ISSUE TITLE
Discount not applied on edit subscription

### ISSUE THREAD

**Issue by relinnstest** [woocommerce/woocommerce#25902]
We are implementing subscription base product items, When we are placing an order, a discount coupon is applied on the subscription.
The problem is when we are editing the existing subscription (add items or change quantity of items) then the discount is not updated and the coupon remains the same as at the time of new subscription.

**Comment by juliaamosova** [comment]
Hi @relinnstest,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/). 

Our Techincal Support Engineers will be able to evaluate the issue further, confirm it and file in the right place with developers of WooCommerce Subscriptions. They will also be able to keep you updated on the fix - something that we can't do here. We also can't simply move your issue to the WooCommerce Subscription's repository as it is not public. Thank you for understanding!
