### ISSUE TITLE
[WC 4.0] Shipping methods are not showing in the checkout, because of State/County

### ISSUE THREAD

**Issue by MartaPawlonka** [woocommerce/woocommerce#25910]
**Describe the bug**
In the latest version, WC 4.0 has been added condition if the country has a state/county. If so, the shipping method is not showing when the field is empty.

**To Reproduce**
1. Add the flat rate for Bulgaria in the shipping method.
2. Go to the checkout page.
3. Choose Bulgaria.
4. The flat rate method is not showing. I need to choose State/County.

**Screenshots**
WC 4.0 - http://wpdesk.me/mp/vnpua.png
WC 3.9 - http://wpdesk.me/mp/8l1ks.png

**Expected behavior**
The shipping method should display even if I don't choose State/County.

**Comment by gbruzzo** [comment]
Hi there 

Premise : We are using a flat rate shipping plugin (WP Desk Flexible Shipping)
The issue can be reproduced with all shipping plugins (e.g. Flat Rate)

I can confirm the same bug on our staging installation.

**To Reproduce**
On cart, with Shipping Calculator 
- Enter country, click update => no shipping 
- Enter country, enter State, click update => shipping appears 

On Checkout 
- Enter country, ajax updates => no shipping 
- Enter country, enter State, ajax updates => shipping appears 

**Expected behavior**
The shipping method should display even if I don't choose State/County.

**Comment by peterfabian** [comment]
Hi all, thanks for reporting! We're going to update this in the next release so that it behaves the same as with 3.9. Please follow ticket https://github.com/woocommerce/woocommerce/issues/25854 for progress.

I'm going to close this one as duplicate, but please feel free to comment here with any further findings.
