### ISSUE TITLE
Irregularity in classes for filters on products overview page

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce#25925]
**Describe the bug**
The following filters on the products overview page all have the same class except filter by category which uses a different class.

The input:select for: Bulk Actions, Filter by product type, Filter by stock status & Brand (WC Brands installed) all no CSS class so inherit default WP styling.

However the input:select for: Filter by category has a class "class="select2 select2-container select2-container--default""

This is inconsistent and not sure if its a bug/issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ../wp-admin/edit.php?post_type=product  (Products Overview Page)
2. Inspect Label styling/code.
3. See inconsistency in label styling/classes.

**Expected behaviour**
All input:selects to utilise similar styling/structure

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with Storefront (https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Latest WP & Latest WC

**Comment by vedanshujain** [comment]
Filter by category is actually different than other dropdowns because it fetches options from the server in real-time and is a select2 component (as opposed to other dropdowns which are normal select and have hardcoded options). This is I believe the reason for the inconsistency.
That said, we can (and should) still have consistent class names. However, changing class names breaks backward compatibility with stylesheets, therefore I don't think we are going to prioritize working on this. I am closing this issue now, but let me know if I have missed anything and we can discuss further.
