### ISSUE TITLE
[E2E] Initial data for running e2e tests (settings, products, orders)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25958]
Figure out what is the best way to create initial data needed for running e2e tests (products, orders). 

Currently, in Core, we run the Setup Wizard e2e test that configures WooCommerce on the test site. We also create a product and an order whenever needed within the test itself. 

This doesn't always work for other teams (for example those, that develop extensions) that work with WooCommerce - especially the Setup Wizard test. These teams need WooCommerce set up and ready to use before running their own tests. Creating products and orders can also increase test running time so not ideal. 

Would creating and publishing an official WooCommerce Docker image solve this for us?

**Comment by juliaamosova** [comment]
The first iteration of the package that allows creating initial data for running e2e tests had been done in https://github.com/woocommerce/woocommerce/pull/26948. With this PR, it is now possible to easily create a Simple product.

**Comment by ObliviousHarmony** [comment]
As the scope of the `@woocommerce/model-factories` package has evolved, it became apparent that there were two distinct use-cases being served that could be better served by separating it. In https://github.com/woocommerce/woocommerce/pull/27739 I separated the core functionality into two packages:
- `@woocommerce/api` contains the TypeScript model definitions, API classes, and service classes. This will make a nice modern client library for interacting with WooCommerce installations via the REST API (and more in the future).
- `@woocommerce/e2e-utils` contains the factories themselves. Since the factories would never be used without the E2E test utilities, it seemed wise to move them into this package. Doing this removed the E2E dependencies from the API package and gave it a more specific purpose.

Once we merge https://github.com/woocommerce/woocommerce/pull/27836 the package will be ready for its `0.1.0` release. This initial release of the `@woocommerce/api` package will feature:
- Axios-based HTTP Client
- Immutable model classes
- Repository base class with emphasis placed on type-safety
- Service class for setting shop address and demonstrating abstracted usage of repository
- Repository Implementations:
  - SimpleProduct (Create)
  - SettingGroup (List)
  - Setting (List, Read, Update)

From here we've outlined some more granular tasks as milestones for this task:
- https://github.com/woocommerce/woocommerce/issues/27871
- https://github.com/woocommerce/woocommerce/issues/27872
- https://github.com/woocommerce/woocommerce/issues/27873

**Comment by ObliviousHarmony** [comment]
With the `SimpleProduct` type finished; we can focus on adding other product types and the order type to finish fleshing out the MVP needed to complete this issue entirely!

**Comment by rrennick** [comment]
> These teams need WooCommerce set up and ready to use before running their own tests.

In the process of making the core tests independent we will be making two functions that will 
- set/reset core to the settings we have after running the setup tests
- reset core to default/new install

We can export those functions from the `e2e-utils` package which will be usable in any other project.

**Comment by rrennick** [comment]
I think we have more or less addressed this issue in https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/config/default.json while adding REST API tests.
