### ISSUE TITLE
Variable product price does not show anymore.

### ISSUE THREAD

**Issue by tat-art** [woocommerce/woocommerce#25983]
I made before a lot of products with variations and the price for each variation appeard before the "add to cart" button now it just not appearing anymore. Not sure what happend i didnt install any new plugin just updated the woocommerce to last vervion. 
Example (price is no appearing) this is made today.
![price is not in place](https://user-images.githubusercontent.com/62440265/77188164-40c29780-6ade-11ea-96ec-a66eea27f3ce.png)
Example ( price appearing) this is made before some days.
![price is in place](https://user-images.githubusercontent.com/62440265/77188348-87b08d00-6ade-11ea-9e32-0d33dc375616.png)

**Comment by juliaamosova** [comment]
Hi @tat-art,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end using WooCommerce 4.0.1:

![var](https://user-images.githubusercontent.com/19143190/77189206-93379000-6aad-11ea-91ee-db4185743597.jpg)

Which version of WooCommerce are you using?

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by tat-art** [comment]
> Hi @tat-art,
> 
> Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end using WooCommerce 4.0.1:
> 
> ![var](https://user-images.githubusercontent.com/19143190/77189206-93379000-6aad-11ea-91ee-db4185743597.jpg)
> 
> Which version of WooCommerce are you using?
> 
> Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
> 
> If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

I just deactivate everything except woocommerce 4.0.1 , also using the theme storefront and still appears the same . Here is the link to site as it is now https://tat-art.gr/product/asdsadasdasdas/ . Also the relative photo thanks for you time . 
![still not appearing](https://user-images.githubusercontent.com/62440265/77190393-d6135b00-6ae1-11ea-94bf-00c91af33d00.png)

**Comment by juliaamosova** [comment]
Thanks for your follow-up @tat-art! 

>update : i found that when my variable product has the same price is causing the issue 

I was going to mention that this happens because your variations have the same price. It's been working this way for a while (just went back all the way to WooCommerce version 3.0 to test it). 

We have an enhancement issue open for it as well: https://github.com/woocommerce/woocommerce/issues/25713 - feel free to comment on it to add another vote to it. 

>but is strange because many variable product have the same price for example a paint has many colors but same price.

Not sure I understand this - can you please elaborate?

**Comment by tat-art** [comment]
> We have an enhancement issue open for it as well: #25713 - feel free to comment on it to add another vote to it.

I see so there is no solution for the moment. Thanks for that :) . 
> > but is strange because many variable product have the same price for example a paint has many colors but same price.
> Not sure I understand this - can you please elaborate?
I ment to give an example for the usage of variable product with same price . For example different color on a product but the price remain the same but nevermind that . Thanks for your time hope there will be a solution soon for that !
