### ISSUE TITLE
Improvement on the version 4.0.0 (Variation Price)

### ISSUE THREAD

**Issue by LeoGraphic** [woocommerce/woocommerce#25994]
Hello,

I was able to detect a small concern regarding the display of variation product information on a product page. Because especially when the information areas are outside the form. In one of my cases, in particular on the tabs below with my template.

It is used form.product.find() for change in the file
/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.min.js

I think it would be more judicious to make a $(html).find() that solves the bug of non replacement when certain classes of search CSS are outside the form.

So I replaced in my file, now if there is an update, it will delete this change, because it is in a JS file, specific to the plugin and not to customization.

Line 208 to 210

BEFORE
$sku = form.$product.find( ‘.product_meta’ ).find( ‘.sku’ ),
$weight = form.$product.find( ‘.product_weight, .woocommerce-product-attributes-item–weight .woocommerce-product-attributes-item__value’ ),
$dimensions = form.$product.find( ‘.product_dimensions, .woocommerce-product-attributes-item–dimensions .woocommerce-product-attributes-item__value’ ),

AFTER
$sku = $(‘html’).find( ‘.product_meta’ ).find( ‘.sku’ ),
$weight = $(‘html’).find( ‘.product_weight, .woocommerce-product-attributes-item–weight .woocommerce-product-attributes-item__value’ ),
$dimensions = $(‘html’).find( ‘.product_dimensions, .woocommerce-product-attributes-item–dimensions .woocommerce-product-attributes-item__value’ ),

Thanks for your feedback

**Comment by ObliviousHarmony** [comment]
Hello @LeoGraphic,

We limit our search to children of `form.$product` so that we only perform the searching on that variation's form. If we changed it to `$( 'html' ).find(` it would grab every `.product_meta` class instance in the DOM, including those for other variations and the central product info itself.

As an aside, code changes are better submitted as pull request so they can be more readily reviewed, tested, and tracked.

Thanks!
