### ISSUE TITLE
Variable Product Error Message: "Please select some product options..."

### ISSUE THREAD

**Issue by novelneighbor** [woocommerce/woocommerce#26014]
**Describe the bug**
I have a variable product in my woocommerce store. Whenever I try to submit the order form, I get an error message that reads "Please select some product options before adding this product to your cart." even though the form is completely filled out. 

**To Reproduce**
1. Go to https://thenovelneighbor.com/product/mystery-box/
2. Fill Out the form
3. Click "Add to Cart"

**Screenshots**

**Expected behavior**
I would like the orders to go through instead of getting an error message.

**Isolating the problem (mark completed items with an [x]):**
- I read that this can sometimes happen if WP Rocket is activated. I deactivated it and the error still occurred, but I haven't tried deactivating any other plugins.

**WordPress Environment**
<details>
```

WordPress environment
--
WordPress address (URL): |   | https://thenovelneighbor.com
Site address (URL): |   | https://thenovelneighbor.com
WooCommerce version: |   | 4.0.1
WooCommerce REST API package: |   | 1.0.7 /home/thenove7/public_html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks package: |   | 2.5.14 /home/thenove7/public_html/wp-content/plugins/woo-gutenberg-products-block/
Action Scheduler package: |   | 3.1.4 /home/thenove7/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 1.0.3 /home/thenove7/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | /home/thenove7/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.3.2
WordPress multisite: |   | –
WordPress memory limit: |   | 768 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by juliaamosova** [comment]
Hi @novelneighbor,

Thank you for raising the issue. However, it looks like it is caused by the plugin that adds the form to the variable product. It is easy to check by doing plugins and theme conflict check. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again and see if you can add your variable product to cart (you won't have the form of course).

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue. I suspect it is a plugin that adds the form but it could be something else.

**Comment by novelneighbor** [comment]
Hello,

Thank you for your help! There was an issue with the way the Gravity form was configured, which I have since resolved.

**Comment by juliaamosova** [comment]
Thanks for letting us know @novelneighbor!
