### ISSUE TITLE
Woocommerce Subscription is inactive

### ISSUE THREAD

**Issue by C-Nog** [woocommerce/woocommerce#26032]
Hi I'm using Woocommerce Subscription 3.0.2 and Woocommerce 4.0.1.
The plugin its not working anymore and I keep seeing this warning that makes no sense at all, because Im already running updated versions of both: https://ibb.co/G9WPsjg

Please need help.
Thanks

**Comment by tammullen** [comment]
Hi @C-Nog 

Thank you for raising the issue. However, I can’t reproduce it on my end.
​
I was able to have WooCommerce Subscriptions 3.0.2 active with WooCommerce 4.0.1
​
However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by juliaamosova** [comment]
Hi @C-Nog,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be related to the WooCommerce Subscriptions plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).
