### ISSUE TITLE
Woocommerce emails show no content because space between </titl .. e>

### ISSUE THREAD

**Issue by karinorage** [woocommerce/woocommerce#26036]
**Describe the bug**
All email notifications show the tablestructure but show no content.
I noticed that the html-output of the e-mail produces a blank space the closing title:
</titl e> instead of </title.
==================
<!DOCTYPE html>
<html lang=”nl”>
<head>
<meta http-equiv=”Content
-Type” content=”text/html; charset=UTF-8″>
<title>Skindependent</titl
e>
</head>
==================
When I manually delete the space the content shows.
I am no developer, but it seems to me that somewhere in the process this blank space is added.

WordPress omgeving
--
WordPress-adres (URL): |   | https://skindependent.nl/wordpress
Siteadres (URL): |   | https://skindependent.nl
Versie van WooCommerce: |   | 4.0.1
WooCommerce REST API-pakket: |   | 1.0.7 /var/www/vhosts/126/307437/webspace/httpdocs/skindependent.nl/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks-pakket: |   | 2.5.14 /var/www/vhosts/126/307437/webspace/httpdocs/skindependent.nl/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler-pakket: |   | 3.1.4 /var/www/vhosts/126/307437/webspace/httpdocs/skindependent.nl/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin-pakket: |   | 1.0.3 /var/www/vhosts/126/307437/webspace/httpdocs/skindependent.nl/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-admin
Logmap beschrijfbaar: |   | /var/www/vhosts/126/307437/webspace/httpdocs/skindependent.nl/wordpress/wp-content/uploads/wc-logs/
Versie van WordPress: |   | 5.3.2
WordPress multisite: |   | –
WordPress geheugenlimiet: |   | 1 GB
WordPress debug-modus: |   | –
WordPress cron: |   |  
Taal: |   | nl_NL
Externe object-cache: |   | –

**Comment by tammullen** [comment]
Hi @karinorage 


Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further including the full system status report so we can see what plugins and theme you are using.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​
Label:
Abbreviation:

**Comment by Mtarnuhal** [comment]
Seems to be related to #26015

**Comment by karinorage** [comment]
Hi @tammullen ,
Sorry for not being more specific, the error needed urgent repair, so I didn't make the time to give a more elaborate answer, instead I researched more sources. As @Mtarnuhal mentioned, it is indeed related to #26015 as the trouble started with version 4. 
I was however kindly helped by @DanielRuf who advised me to add the following code to my functions.php See: [https://remicorson.com/remove-the-woocommerce-3-json-ld-structured-data-format/]
See also the topic on [https://wordpress.org/support/topic/woocommerce-emails-html-broken/page/3/#post-12605048].
For me this solution worked so I will close my bug-submission. Thanks!
