### ISSUE TITLE
get_vat_countries() not the same as get_european_union_countries( 'eu_vat' )

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#26105]
**Describe the bug**
On WooCommerce 4.0 the WC_Countries `get_european_union_countries` method `$type` parameter was deprecated and the warning tells us to use `get_vat_countries()`.

Before 4.0 `get_european_union_countries( 'eu_vat' )` returned the 28 EU countries + Monaco and Isle of Man, which was correct.

`get_vat_countries()` returns 80 countries, which may be correct for "the countries that use VAT" but it's not correct as a new method to get the "European VAT zone countries".

**To Reproduce**
Run `WC()->countries->get_european_union_countries( 'eu_vat' )` before and after WooCommerce 4.0
You will get 28+2 countries before WooCommerce 4 and 80 countries after WooCommerce 4 because if 'eu_vat' is passed on to the `get_european_union_countries` method, the new `get_vat_countries` is called, which is wrong.

**Expected behavior**
`get_vat_countries()` should not be announced or used as an alternative to `get_european_union_countries( 'eu_vat' )`.

**Possible solutions**
- A new method should be created to get the EU VAT countries (not a good idea because this will force people to use a new method)
- The `get_european_union_countries` `$type` parameter should work as before (best solution because existing code will work)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by webdados** [comment]
In short:
- Before 4.0 `get_european_union_countries( 'eu_vat' )` returned the countries of the EU VAT zone (28+2).
- After 4.0 the same code now returns all the countries that have VAT around the world (80).

Wait until people find out that Mexico is part of the EU VAT zone because of WooCommerce 4.0 :-D

**Comment by DavidAnderson684** [comment]
N.B.:

1) IM is part of a common VAT area with GB, and so is part of the EU VAT area because of the GB's continuing membership of the VAT area.

2) GB (and hence IM also) will leave the common VAT area on 1st January 2021 (https://www.avalara.com/vatlive/en/vat-news/uk-to-leave-eu-vat-regime-31-dec-20200.html). Presuming that there's not going to be a WC release on the stroke of midnight which everyone will instantly update to, it would be a good idea to put a date check in the routine.
Though, given that WooCommerce 4.0 will still be installed in plenty of sites at that time, probably any sane developer of a plugin that relies on accurate data is going to not be relying on `get_vat_countries('eu_vat')` now anyway because the bug is out there.

**Comment by webdados** [comment]
> Presuming that there's not going to be a WC release on the stroke of midnight which everyone will instantly update to, it would be a good idea to put a date check in the routine.

I agree.

> Though, given that WooCommerce 4.0 will still be installed in plenty of sites at that time, probably any sane developer of a plugin that relies on accurate data is going to not be relying on get_vat_countries('eu_vat') now anyway because the bug is out there.

That's not an argument to not fix the issue ASAP.

**Comment by juliaamosova** [comment]
Hi @webdados,

Thank you for taking the time to report this bug, we really appreciate your help. Thank you for submitting PR as well.
