### ISSUE TITLE
I'd like to change the payment gateway company. But there was a problem. "Disable Gateway: Permalink Settings. You have to use a setting other than 'normal'."

### ISSUE THREAD

**Issue by maxyoun** [woocommerce/woocommerce#26116]
(First of all, English is not my native language. I hope you understand.)

I'd like to change the payment gateway company to "Innopay". So I installed the plug-in provided by Innopay.
However, the plug-in is compatible with PHP 5.4, WordPress 4.9.13, and Woocommerce 3.5.1.
And My homepage uses PHP 7.2.5, WordPress 5.2.5, and Woocommerce 3.5.6.

The problem at hand is that "it is impossible to change the plug-in's configuration settings." When I enter the plug-in's configuration, the site says, **"Disable Gateway: Permalink Settings. You have to use a setting other than 'normal'."** On my website, permalink is not already set to 'normal'. I can't find a solution.

**Q. What caused this problem? What is the solution other than changing permalink? What can I try?**

**Comment by juliaamosova** [comment]
Hi @maxyoun,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by Innopay plugin which is not one of our products.

To get further technical support for it, please contact the developers of the Innopay plugin directly.
