### ISSUE TITLE
[GlobalStep - 4.1 beta 1]Unnecessary product category are displayed in display type i.e., Default and Both

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26147]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on Products.
4. Click on Categories.
5. Click on "Display Type" drop down.
6. Observe that unnecessary product category are displayed in display type i.e., Default and Both.

**Actual Result:**
Unnecessary product category are displayed in display type i.e., Default and Both

**Expected Result:**
Default and Both options should be removed.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for filing this issue. Noting here that it is being related to `Display type` field as shown below:

![cat](https://user-images.githubusercontent.com/19143190/79020815-dda9ab00-7b47-11ea-8600-b4debb5b6828.jpg)

I remember you confirming with me if this is working as expected and I asked you to file an issue. On the 2nd look now, I see that `Default` and `Both` options are not something that we can remove. 

From our [documentation](https://docs.woocommerce.com/document/managing-product-taxonomies/#section-2):

>Choose the **Display type**. Decide what is shown on the category’s landing page. “Standard” uses your theme’s default. “Subcategories” will display only the subcategories. “Products” only displays products. “Both” will display subcategories and products below that.

Since we can't remove `Default` and `Both` options, I am closing this issue without any further action on our end.
