### ISSUE TITLE
WooCommerce 4.0.1 allows product-wide backordering if one of variations do not have pre-set attributes

### ISSUE THREAD

**Issue by sybbear** [woocommerce/woocommerce#26176]
**Describe the bug**
Our customer has spotted a bug, which allowed visitors to order variations, which have 0 in stock and are not backorderable. This is a business-critical issue that causes merchants to tinker with the orders by refunding and cancelling them. 
We reproduced it with two clean Wordpress+WC installations.
WC 4.0.1
WP 5.1.1 and 5.4

**To Reproduce**

1. Make sure your webshop has a product attribute e.g. Size
2. Create a new variable product
3. Create a child variation product A, **set a Size**
  3.1. Set a price, enable stock management, disable backorders
  3.2. Set **stock to 0**
4. Create another variation product B, but **do not set a Size** (leave Any Size hanging)
  4.1. Set a price, enabled stock management, disable backorders
  4.2. Set **any positive stock**
5. Save everything
6. Visit the product page
7. Now you can order any quantity of variation A, up to stock amount of product B.

**Screenshots**
_Set up_
![image](https://user-images.githubusercontent.com/2473385/79223443-0391c100-7e62-11ea-9285-03f9c73fccc5.png)

_Ordering_
![image](https://user-images.githubusercontent.com/2473385/79223516-2ae88e00-7e62-11ea-876c-53ddb8513fc1.png)

**Expected behavior**
When there is a variation with no attribute term set, buyers should not be allowed to backorder any amount of items that are non-backorderable and are out of stock.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vikingmaster** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/26158

**Comment by tammullen** [comment]
Hi @vikingmaster 

Thank you for submitting the issue. 

Using the steps you provided I did see the same behavior however this is to be expected as the 2nd product "variation product B" would appear at the top of the list of variations and would take priority when two products are using the same variation. In this instance the size for "variation product A" is also covered by "variation product B" and so the information for "variation product B" would be used.
If you re-order the variations so that "variation product A" is above "variation product B" you will find that the stock and backordering for "variation product A" will look as you wanted.

![Screenshot_2020-04-17_at_10_27_39](https://user-images.githubusercontent.com/24649833/79554641-420fc180-8096-11ea-946e-e60a7d8753e4.png)

​

**Comment by vikingmaster** [comment]
@tammullen 
Thank you for the investigation and reply.

However, I am not exactly able to understand why is this an expected behaviour.
**Both variations had backordering disabled**. Also the amount that you can order for product A is allowed up for the product B - how does this make sense, is it documented?

And finally, we bumped into this problem via a product import integration, where the plugin does not really `know` or `see` in which order variations are arranged. It doesn't even come to mind to care about it in the first place. So, an empty value for the term has come from an API and created [Any size] product. It made customers order items which would not be possible to order otherwise.

I hope it's not hard to understand, that situations like that causes quite a bit of unnecessary work for webshop managers to do communication and refunding.

**Comment by rrennick** [comment]
Closing this as Tam provided an explanation.
