### ISSUE TITLE
[GlobalStep - 4.1 RC]: On MailChimp "Connect" label in white is non functional.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26279]
Steps to Reproduce:
1. Tested on JN site and JN multisite
2. Complete initial screens.
3. Click on Marketing.
4. Click on "Mailchimp for WooCommerce".
5. Note that "Connect" button on white is displayed having hyperlink.
6. Click on white Connect button.
7. Observe that "Connect" label in white is non functional.

Actual Result:
On MailChimp "Connect" label in white is non functional.

Expected Result:
On MailChimp "Connect" label should be functional.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for raising this issue! According to the [Mailchimp documentation](https://mailchimp.com/help/connect-or-disconnect-mailchimp-for-woocommerce/#Connect_and_configure), this `Connect` label in white is not a button but rather an identifier for the user so they could know at which step of the configuration they are currently located. 

I agree, however, that this is confusing and that the white `Connect` label shouldn't be clickable. 

Since Mailchimp integration was developed directly by Mailchimp, the issue can't be fixed on our end. However, I reported it directly to Mailchimp. 

Below is the screenshot explaining the 2 issues I actually see in the `Connect` section. Aside from the white `Connect` label being clickable, the notices are not at the top of the page like they should be:

![Mailchimp issues](https://user-images.githubusercontent.com/19143190/81074075-8254a980-8eb6-11ea-8554-2377aa9079b0.jpg)

I am closing this issue as it's been reported to Mailchimp.
