### ISSUE TITLE
Woocommerce Webhook order.update not sending correct status when Failed => Processing

### ISSUE THREAD

**Issue by kimma19** [woocommerce/woocommerce#26356]
**Describe the bug**
The woocommerce API order.update wasn't sending correct status when an order change from Failed to Processing. The webhook is fired but it still sending Failed as the status. All other status change behaves correct at this time.

**To Reproduce**
1. Setup webhook for order.update.
2. A user change an order status from failed to processing
3. Webhook sends out the data, but with the wrong status.

**Expected behavior**
It should send out the status as processing.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ❌ Inactive 1.0.3
Log Directory Writable: ✔
WP Version: ❌ 5.4 - There is a newer version of WordPress available (5.4.1)
WP Multisite: –
WP Memory Limit: 356 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Amazon) OpenSSL/1.0.2k-fips PHP/7.3.15
PHP Version: 7.3.15
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

</details>

**Comment by juliaamosova** [comment]
Hi @kimma19,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. Tested using `WC 4.1 rc.3`. 

I have an order 62 that had a `Failed` status:

![web1](https://user-images.githubusercontent.com/19143190/81012795-29d6cb00-8e28-11ea-8171-ae6f2cb13988.jpg)

I created a webhook and then changed the order status from `Failed` to `Processing`. The webhook was fired and reported correct data:

![web2](https://user-images.githubusercontent.com/19143190/81013146-b08ba800-8e28-11ea-8b1c-cf34e3455f7c.jpg)

I see no errors in the log:

![web3](https://user-images.githubusercontent.com/19143190/81013338-f8123400-8e28-11ea-911f-59be78d5ed8c.jpg)

Please provide us with more details about the issue which may help us to evaluate it further. Are there any more specific steps to take in order to replicate the issue you are experiencing?

**Comment by kimma19** [comment]
hi, thanks for check this. And I can't reproduce neither... There were three orders behaves like this but I didn't save the logs.. Might be conflicted with other plugins which I accidentally turned off.. Anyways, it seems working right now. Thanks a lot for helping.

**Comment by juliaamosova** [comment]
Sounds good and thanks for your follow-up @kimma19!

**Comment by WeslleyDeSouza** [comment]
same here.. after payment is done, the order.update sends the wrong status..

**Comment by kimma19** [comment]
> same here.. after payment is done, the order.update sends the wrong status..

Yeah I do see that issue again. But unfortunately I can't replicate myself. Can't find in what situation it happens. Got this situation couple times every week..
