### ISSUE TITLE
Is there a limit for images executing Batch post('products/batch') ??? It breaks

### ISSUE THREAD

**Issue by jdelafuente** [woocommerce/woocommerce#26378]
Hi,

I am importing products using the **batch post('products/batch')**. I get it **working perfect unless too much images are set.**

I got **[internal_server_error]** a lot of times. I have check all the server error logs and there is no register or information about this error anywhere.

Reading the wocommerce api documentation it says **Batch by default it's limited to up to 100 objects to be created, updated or deleted**.

May be the problem is relationated with that limit. I split the calls to execute the batch when the total number of images + products < 100.  It aparently works with 100 total products, but if I set to 1000 products the error comes again.

**May be wordpress has an image processing limitation or something else that make the script break?
How can I get the detail of this error?**

Tried this lines but no details:
`echo '

' . print_r( $e->getMessage(), true ) . '
'; // Error message.

echo '
' . print_r( $e->getRequest(), true ) . '
'; // Last request data.

echo '
' . print_r( $e->getResponse(), true ) . '
'; // Last response data.`

The images array is set and right structured like the woocommerce says:

`'images' => [

[

'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg'

],

[

'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg'

],

[

.......  more images .......

],

]`

The response:

``[internal_server_error]

Automattic\WooCommerce\HttpClient\Response Object

(

[code:Automattic\WooCommerce\HttpClient\Response:private] => 500

[headers:Automattic\WooCommerce\HttpClient\Response:private] => Array

(

[Server] => nginx

[Date] => Tue, 05 May 2020 08:15:50 GMT

[Content-Type] => application/json; charset=UTF-8

[Transfer-Encoding] => chunked

[Connection] => keep-alive

[X-Powered-By] => PHP/7.4.5

[Pragma] => no-cache

[X-Robots-Tag] => noindex

[Link] => ; rel="https://api.w.org/"

[X-Content-Type-Options] => nosniff, nosniff

[Access-Control-Expose-Headers] => X-WP-Total, X-WP-TotalPages

[Access-Control-Allow-Headers] => Authorization, Content-Type

[Expires] => Wed, 11 Jan 1984 05:00:00 GMT

[Cache-Control] => no-transform, no-cache, no-store, must-revalidate

[Set-Cookie] => PHPSESSID=4mkc6j0dtpnor946qtk3vr73ah; path=/

[X-Frame-Options] => SAMEORIGIN

[X-XSS-Protection] => 1; mode=block

)

[body:Automattic\WooCommerce\HttpClient\Response:private] => {"code":"internal_server_error","message":"

Ha habido un error cr\u00edtico en tu web.</p>

Aprende m\u00e1s sobre la depuraci\u00f3n en WordPress.</a></p>","data":{"status":500},"additional_errors":[]}

)``

Hope someone can help me with this. I have been fighting with this error during days and I don´t know the origin so I can´t correct it.

Thank you vey much.

**Comment by peterfabian** [comment]
Hi @jdelafuente,

Whenever you encounter the Internal Server Error, it's a good idea to check your HTTP server's and PHP error log to see what the error is on the server side. 

I'm guessing, but most likely your PHP script timeout is hit (usually set to 30 seconds), so you can either split the batch into smaller sub-batches or increase your PHP time limit. 

Also, our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
