### ISSUE TITLE
Coupon code getting escaped in some browsers.

### ISSUE THREAD

**Issue by will-yellowpeach** [woocommerce/woocommerce#26404]
When entering a coupon code that doesn't exist, WooCommerce behaviour is to add a notice: 
"Coupon {code} does not exist!".

If however you enter a ' or " as part of the code, certain browsers seem to be escaping the characters in the notice bar.
This doesn't seem to be the case for me working on a Mac/Chrome or on my iPhone, however on a PC IE/Firefox or Android devices it does.

Example below of the same code, but different outputs:
![Screenshot 2020-05-07 at 10 37 06](https://user-images.githubusercontent.com/64958924/81282135-ac42d300-9052-11ea-871a-5da03fa54c4f.png)
![Screenshot 2020-05-07 at 10 37 16](https://user-images.githubusercontent.com/64958924/81282146-ae0c9680-9052-11ea-9d82-e707f1e55b75.png)

Have also tested some of the Showcase websites from the WooCommerce website and theirs seem to be the same.

Thanks

**Comment by juliaamosova** [comment]
Hi @will-yellowpeach,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Tested it on macOS Catalina 10.15.4 + Chrome, Safari & Firefox - works well and as expected. 

However, I had an issue with applying the coupon on my Pixel 4 phone that is on Android. 

![ch1](https://user-images.githubusercontent.com/19143190/81332425-14081680-9071-11ea-98fd-001ccc0e1704.jpg)

![sf1](https://user-images.githubusercontent.com/19143190/81332442-19fdf780-9071-11ea-85af-2fea3a791a4c.jpg)

![f1](https://user-images.githubusercontent.com/19143190/81332452-1cf8e800-9071-11ea-8552-9fab9b60da0a.jpg)

![p1](https://user-images.githubusercontent.com/19143190/81332470-21bd9c00-9071-11ea-95a8-33ca4aee8033.jpg)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by swatipawarGS** [comment]
Hi @will-yellowpeach ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version. 

Please find below screenshots  for reference :

Chrome : 

![#26404(chrome)](https://user-images.githubusercontent.com/94531721/145953401-e0a5ed5a-f3d3-47a4-bfbc-58e3f37ae370.png)

Firefox : 
![#26404(firefox)](https://user-images.githubusercontent.com/94531721/145953511-c7cf68e5-01fa-4cd0-81dd-a3b04a0ea9c0.png)

iphone:

![#26404(iPhone)](https://user-images.githubusercontent.com/94531721/145954795-41b4f93f-8c78-4f82-bb1a-765c2101f998.jpeg)



Android devices(Honor): 

![#26404(Honor)](https://user-images.githubusercontent.com/94531721/145954810-151e387b-3528-43fa-8c4e-95c5cb6824a0.JPEG)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by mikejolley** [comment]
Revisiting some old issues today and I tested this on a new Jurassic.ninja site with coupon `test"test'test` to check special character handling. I was unable to replicate this on:

- IOS Chrome
- Mac Chrome
- Mac Safari
- Mac Firefox
- Windows Chrome
- Windows Edge
- Windows Firefox

All notices were formatted correctly. 

It's possible this was fixed by https://github.com/woocommerce/woocommerce/commit/cea1c10122da7c38ea32c005c323afe894edb6c4 but could have just been a browser issue that has since been patched. As I cannot replicate I will close this issue now.
