### ISSUE TITLE
Please decouple the house number and street name fields in class-wc-countries.php

### ISSUE THREAD

**Issue by Marcoevich** [woocommerce/woocommerce#26423]
**Is your feature request related to a problem? Please describe.**
Sometimes our orders cannot be send to the fullfillment provider because of incorrect address errors. Browsers sometimes make errors when autofilling the street + house number field at the billing and shipping section during checkout. When this happens they usually only provide the house number. This field is defined in `class-wc-countries.php`. 

The fullfillment software (MyParcel) provides the following error information:

```
2020-05-08T09:56:37+00:00 DEBUG API response (order 5693):
array (
  'code' => 422 Unprocessable Entity,
  'body' => 
  array (
    'errors' => 
    array (
      0 => 
      array (
        'code' => 0,
        'fields' => 
        array (
          0 => 'data.shipments[0].recipient.street',
        ),
        'human' => 
        array (
          0 => 'data.shipments[0].recipient.street Must be at least 1 characters long',
        ),
      ),
    ),
    'message' => 'Failed validation against JSON-SCHEMA shipment/post_shipments_request.json',
  ),
```

**Describe the solution you'd like**
Break apart the house number and street name address. Make it 2 seperate required fields. Then there's less chance that things go wrong. If either field is unfilled, an error is thrown and the user can correct it.

**Describe alternatives you've considered**
I can change the checkout fields for our own site but I thought maybe others will benefit from this as well, hence this suggestion.

**Comment by negapo** [comment]
We have this problem frequently, but i think it would be a bad practice implementing this on the checkout form fields because the standard accepted UX is two text fields for the address without any type of validation. At one time we removed the second address field and the problem became worse because we were missing the data from the autofillers to the second field.
Addresses do really change a lot, and some of them don't have door numbers (at least in my country). To tackle this we have a piece of javascript that looks for a number in the two fields and asks the user before the checkout if the address really doesn't have a door number in a alert message. Even with this type of validation we have users checking out without door numbers on addresses that clearly have them. So we them have a watchdog program using the API that checks for the address validity and warns someone from our team to check it. It checks other things like postal codes, stock levels, phone numbers, email addresses (we have a lot of clients with a gmail.co**n** email address :) ).
This is the step from the great community of developers that helps build WC and the real world ecommerce stores. I have spent the last two years learning to code so we can adapt out store to this little things.,

**Comment by Marcoevich** [comment]
@negapo sounds like you have experience with these issues. Do you have any recommendations for the woocommerce team to improve the checkout experience? We can ofcourse make our own custom adaptations but my goal in creating this issue is to bring this under attention so that woocommerce can be improved for all users and not just for us.

> We have this problem frequently, but i think it would be a bad practice implementing this on the checkout form fields because the standard accepted UX is two text fields for the address without any type of validation. At one time we removed the second address field and the problem became worse because we were missing the data from the autofillers to the second field.

Actually I am proposing just that. Street and house number are now combined into a single field. I want to seperate them into 2 different fields. Then it becomes the "standard accepted UX" you spoke of.

**Comment by Konamiman** [comment]
Hi @Marcoevich, thanks for your suggestion.

Postal addresses is a tricky subject, especially for a platform like WooCommerce that is available worldwide. As @negapo says, the standard practice is to provide two (or more) free-form text fields for the street or equivalent, including house number where appropriate; and then additional fields for city, state, postcode, etc. This is the "less bad" approach given the diversity of address formats around the world, and deviating from this standard could potentially cause a lot of trouble to existing shops.

Therefore I'd say that the way to go is to adjust the checkout fields on an as needed basis, a thing that you say you considered as an alternative. Also as @negapo points out, no matter what mechanisms you put in place to prevent users from entering an incorrect address, there will always be cases where this can't be prevented.

I'm closing this issue for now, please don't hesitate to reach to us again if you have further suggestions for improving WooCommerce.

**Comment by negapo** [comment]
@Marcoevich you are right, that the way we should think, improve WC even if that means breaking (a little) the wrong UX experiences that people just got acostume to.
I really think that WC checkout could be improved, as many other things with the plug-in, that im sure the developers will work on with the input of people like you and me that run a real business with this plug-in.

The address fields on the checkout (billing and shipping) are as @Konamiman two free form text fields, this is the first thing that i dont understand, why the use of two fields, this is an unstructured field, it doesnt have any rules to it so there is no logic in creating two fields. Even for fields that have rules to it (a kind of structure) like the email, we dont see it in forms likes this:
____________ @ ___________ . _____
[https://ibb.co/7j5Ftsg](url)
 
What we have for email is a free text form field with validation, and this is the important bit, validation. The "First Name" and "Last Name" fields suffer from the same thing, there is no need for two fields, just one field "First and Last Name" with validation (just look for an empty space between two words). And why reducing fields in the checkout form? Because it helps the user (and conversions) [https://baymard.com/blog/checkout-flow-average-form-fields](url)

And why not hide fields that are infrequently use like "Company" under a selection box that show the field if clicked.

So i think we should have "First and Last Name", "Address", "State/Region/City", "Postal Code", "Phone Number" as the basic fields but what is really lacking is good validation. The way WC validates the form is by checking the fields content after a user clicks "Checkout" and then stopping the checkout process, this is unneeded and bad UX. Inline validation is a much better way if done right, when the user leaves a fields (and it has content) then WC (a front end piece of javascript or a ajax request) should validate the field. And what would be great s a way of creating and crafting those rules, in your specific case you could tell the validation rules that the field "Address" should have at least one letter so costumer who input only numbers would be stopped, and at the right time (as they leave the field). 

Reducing the number of fields could create a difficult time for people who use autofillers forcing them to complete some fields, thats the downside.
Thats my 2 cents, inline validation should be implemented in WC.

**Comment by Marcoevich** [comment]
Thank you @negapo. I'm not sure about combining all those fields though.

> The "First Name" and "Last Name" fields suffer from the same thing, there is no need for two fields, just one field "First and Last Name" with validation (just look for an empty space between two words).

We have e-mail campaigns setup that use the First Name field as an introduction. So the e-mail becomes "Dear -first name-, thank you for your order". I wouldn't want to lose that functionality.

I'm sure there are loads of people and business depending on the fields as they are right now. So changing them all at once will be difficult. But the address field is a tricky one for us. As requested, it is often filled in incorrectly. So I wouldn't mind to see them combined. I've checked other shops from which often buy, and they all have them combined.

I also see that for countries with postal codes that the postal code and house number is sometimes enough to do a realtime check for correctness of the address. Then the street will automatically be filled in and the address will be displayed to the user in full.

I know this is tricky to implement for all countries. But one can start with United States and Europe, where these postal code systems are regulated and working correctly for a long time.

I really love these realtime checks so I can see that everything is filled in correctly. Gives me confidence in placing the order:

![image](https://user-images.githubusercontent.com/1243033/81914461-9e9cc880-95d1-11ea-85c1-129f700cf02e.png)

**Comment by negapo** [comment]
That kind of validation is great, we do that check internally after the user has checkout, the postal code database is free and public so we validate the address based on that, the only problem left out for us is when the user lives in an apartment and only inputs address plus door number. It would be great to do that on front end but unfortunately i dont have the skills.
The case of the First and Last name is simple, in the front end the field is "First and Last Name" but on checkout we split the field in two based on the first space character and dump it on "First Name" and "Last Name". So we do the work for the client in some sense.

**Comment by negapo** [comment]
I know its different, but this reminds me of the old practice of asking the "salut" on checkout like "Mr." "Ms." etc. Nowadays we do that internally, we know what to call our costumers based on the type of messaging we want commercially.

**Comment by Marcoevich** [comment]
> I know its different, but this reminds me of the old practice of asking the "salut" on checkout like "Mr." "Ms." etc. Nowadays we do that internally, we know what to call our costumers based on the type of messaging we want commercially.

That's a smart one. One less field to fill in :)

> The case of the First and Last name is simple, in the front end the field is "First and Last Name" but on checkout we split the field in two based on the first space character and dump it on "First Name" and "Last Name". So we do the work for the client in some sense.

Sounds good but this doesn't always apply. In Asian countries the family name is often written first. So then you have the family name in the first name field in your database. The goal is for a system like Woocommerce to make the defeault implementation as broadly applicable as possible. This will be difficult if those fields are combined. Names work differently for different cultures.

**Comment by KoolPal** [comment]
@Konamiman I am sorry to write this. I think the team at Woocommerce should be a little prudent before closing issues raised here. 

Please understand that this is a very valid & critical discussion taking place here. You are getting amazing real-life feedback and input here (which other organizations are willing to pump millions to get even 5% inputs like this)

I can understand that as a development / bug fix approach you may not find any immediate actionable here, but you should keep the issue open for discussion. Please do not be quick to point out that these ideas can be discussed at https://ideas.woocommerce.com because it has been lying neglected for many years now.

Some of us here are store owners - one of your end customers for this plugin. I think we also would have some insights on our business which goes beyond code. Please welcome feedback from us. You should in fact encourage it.

@peterfabian I see you responding in some issues. What are your views here?

I am sorry if my post here seems annoying, it's just that we store owners have many things to deal with and we are always trying to increase focus on business and work towards making things **just work well** as far as possible

Thanks

**Comment by peterfabian** [comment]
Hi @KoolPal ,

Thanks for tagging me and raising your issue. We definitely do value feedback from the community and I think @Konamiman 's response wasn't dismissive but was thoughtful. You're right that this is an important discussion to have, but to be honest, I haven't seen any 

To me, it seems most big commerce platforms and shipping carriers are quite aligned on their address inputs:

Amazon
![Screenshot 2020-07-03 at 12 08 02](https://user-images.githubusercontent.com/2207451/86458713-fc25d980-bd25-11ea-97d0-f04afc228d83.png)

Shopify
![Screenshot 2020-07-03 at 12 08 27](https://user-images.githubusercontent.com/2207451/86458724-0051f700-bd26-11ea-91bd-a8e2120ac492.png)


WooCommerce
![Screenshot 2020-07-03 at 12 08 42](https://user-images.githubusercontent.com/2207451/86458734-03e57e00-bd26-11ea-992d-96138addb846.png)

UPS
![Screenshot 2020-07-03 at 12 10 49](https://user-images.githubusercontent.com/2207451/86459161-aef63780-bd26-11ea-8155-707d74bbdf9d.png)

DHL
![Screenshot 2020-07-03 at 12 13 45](https://user-images.githubusercontent.com/2207451/86459172-b4538200-bd26-11ea-81e4-7ed669193893.png)

I understand that some parcel companies might require separate house number to validate the address, but isn't it then better for the respective shipping extensions to handle this use case than us adding separate fields to structure the address for everyone? 

Please understand that we are trying to keep the repository tidy and if we let similar questions open for a long time, we would end up with thousands of open issues in the repository and it would be very difficult to navigate it. Other community members are questioning our ability to solve problems as we have too many open issues. So everything has multiple points of view. Also, we're not stopping the discussion here, feel free to continue and if enough people raise this problem, we might revisit it, but at this time, it seems like there is just not enough interest to make this a priority for us, apologies.
