### ISSUE TITLE
The Total Sales in the Taxes by date report does not include shipping price excluding Tax

### ISSUE THREAD

**Issue by EtiennePoolman** [woocommerce/woocommerce#26449]
**Describe the bug**
The **Total Sales** column in the **Taxes by date** report does not include the cost of shipping excluding tax, it includes the **product price + tax** and the **shipping tax**.

**To Reproduce**
1. Place an order for a product that requires shipping and where both the product and shipping is taxed.
2. Go to **Reports > Taxes > Taxes by Date** and look at the **Total Sales** column not matching the **Order Total** as the tooltip explains.

**Screenshots**

Report;

![Screenshot](https://d.pr/i/qeHCRy+)
Screenshot direct link: https://d.pr/i/qeHCRy

Order Total;

![Screenshot](https://d.pr/i/Amb6Tb+)
Screenshot direct link: https://d.pr/i/Amb6Tb

Tooltip;

![Screenshot](https://d.pr/i/dZzRGI+)
Screenshot direct link: https://d.pr/i/dZzRGI

**Expected behavior**
That the total sales would match the order total as explained by the tooltip. In the above screenshots, you will notice the report Total Sales is missing the $42.75 shipping charge

**Comment by Konamiman** [comment]
Thanks for notifying this. I've been able to reproduce the issue with the following parameters:

* A product with a price of 100
* Shipping cost is 5
* Tax is 10%

The order total is then 115.50, but the tax report shows 110.50, which is not including the shipping (but interestingly, it's including the taxes for the shipping).

![image](https://user-images.githubusercontent.com/937723/81549491-1cb56100-937f-11ea-8aec-fa1738c95385.png)

![image](https://user-images.githubusercontent.com/937723/81549443-07d8cd80-937f-11ea-9ff8-86ccba1e3824.png)

**Comment by Konamiman** [comment]
Hi, I have news about this issue. Since the legacy Reports section of WooCommerce will likely be deprecated at some point, we won't be working on fixing this. I'm sorry for not having been clear on that point from the beginning.

That said, WooCommerce Admin Analytics section provides an equivalent functionality and displays the proper amounts; this is what the revenue report displays:

![image](https://user-images.githubusercontent.com/937723/81571120-d32a3d80-93a1-11ea-9c04-16ac8bf85f56.png)

And the taxes report:

![image](https://user-images.githubusercontent.com/937723/81571271-ffde5500-93a1-11ea-8e4b-ac8ae4dee14a.png)

**Comment by EtiennePoolman** [comment]
@Konamiman just to confirm, there is no report in Analytics that is the same and now you need to look at two different reports to get the same info as one report in the legacy reports.

The **Analytics > Taxes** report is not the same as the legacy report here - `page=wc-reports&tab=taxes&report=taxes_by_date`
