### ISSUE TITLE
Please listen to all your users! 

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#26499]
Why woocommerce become more and more bloated everyday? 

You force us to use all useless feature like woocommerce Admin and now marketing section.

Oh my God. Please see how bad rating is "woocommerce admin" plugin and you still add it to the new release. It's like you don't want to listen to your users just add a feature that you like.

**Comment by juliaamosova** [comment]
Hi @erikdemarco,

Thanks for sharing your feedback. When we develop new features, we go through the process of extensive user research based on which we make decisions on what to develop further. 

There are many more projects in the works that will hopefully make you more comfortable continuing to use WooCommerce. 

Meanwhile, if you like you can:

- disable WooCommerce Admin in WooCommerce Core using the following snippet:

`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

- disable Marketing section:

`add_filter( 'woocommerce_marketing_menu_items', '__return_empty_array' );`

Full snippet for both:

https://gist.github.com/jconroy/e21c146aefa4301397b65d430f80dc05

I am closing this issue as there is no immediate action for us to take on it.

**Comment by gbruzzo** [comment]
Hello there

up to Woocommerce 4.2 it was possible to remove the marketing tab by using
add_filter( 'woocommerce_marketing_menu_items', '__return_empty_array' );
in a plugin.

This does not work anymore since Woocommerce 4.3 rc1 (maybe already from beta)

The line

$marketing_pages = apply_filters( ‘woocommerce_marketing_menu_items’);

usually on line 77 of woocommerce/packages/woocommerce-admin/src/Features/Marketing.php in function add_parent_menu_item()

was moved to function register_pages() (about 30 lines down) as

$marketing_pages = apply_filters( ‘woocommerce_marketing_menu_items’, []);

add_filter( 'woocommerce_marketing_menu_items', '__return_empty_array' ); now causes a crash.

Do you have any suggestions? The Marketing Tab is, at the moment at least a wholly useless advertising platform.
It would be nice to be able to disable it, if not used.

Thank you in advance

**Comment by jconroy** [comment]
We've rearranged things a little in wc-admin 1.3 / WC 4.3 - because the marketing tab is set up setup as a feature in wc-admin you can actually use the [woocommerce_admin_features](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Loader.php#L129) filter to get selective about what features you wish to enable/disable if you wish.

I've updated my [original gist](https://gist.github.com/jconroy/e21c146aefa4301397b65d430f80dc05) with a basic example.

**Comment by gbruzzo** [comment]
@jconroy 

thank you very much, I will study woocommerce_admin_features now. 

Appreciated

Giacomo Bruzzo
