### ISSUE TITLE
PayPal "style" deprecated on WooCommerce setup payment method

### ISSUE THREAD

**Issue by cl0udres** [woocommerce/woocommerce#26494]
Hello there,

I'm writing after [suggestion of your support](https://wordpress.org/support/topic/paypal-style-field-on-woocommerce/), because it seems that the feature "style" was been deprecated by PayPal. So it's impossibile to setup a style in WooCommerce setup page of the PayPal payment method.

Could you kindly take a look, please?

Thanks a lot.

**Comment by juliaamosova** [comment]
Hi @cl0udres,

Thanks for raising the issue here! 

PayPal Page Style functionality in question:

https://docs.woocommerce.com/document/paypal-standard/#section-3

I can see indeed that it was mentioned by one of the PayPal forum moderators that the customizing payment pages are no longer as functional as it used to be:

https://www.paypal-community.com/t5/PayPal-Payments-Standard/Cant-find-Paypal-custom-payment-pages/m-p/1353008/highlight/true#M417

I also see the same mentioned in PayPal docs in the first paragraph:

https://developer.paypal.com/docs/admin/checkout-settings/#

>This feature is now limited to displaying your logo image on the standard PayPal checkout page.

We will try to work on this sooner rather than later.

**Comment by cl0udres** [comment]
Thanks a lot.

**Comment by phillipcornwell** [comment]
Can someone take a look at 20137553-hc to check if the missing logo in that chat is part of this as well? I was able to replicate the issue and was going to submit a report on it but want to be sure that the deprecated function they mention also blocks the company logos from appearing in the PayPal pages.

![Screenshot](https://d.pr/i/EHXjy1+)
Screenshot direct link: https://d.pr/i/EHXjy1
