### ISSUE TITLE
[GlobalStep - 4.2 Beta] Red star for "Star Rating" is not displayed which is a mandatory field.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26511]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave-10.14.6-Safari(v13.0.5 )

**Steps to Reproduce:** 
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard".
4. Complete all the introductory tabs i.e., Store details, Industry ,Product types, Business details and Theme. 
5. Now on dashboard, Tap on Products.
6. Tap on "Add New" button and fill product details e.g. for a shirt.
7. Tap on Publish.
8. View the Shirt product on Website template.
9. In reviews section, Enter a review in text field and tap on Submit.
10. Note that an error message is prompted to add a star rating as well.
11. Observe that reviews section fails to display red star for  Star Rating (as it is considered a mandatory field)

**Actual Result:**
Red star for "Star Rating" is not displayed which is a mandatory field.

**Expected Result:**
Red star for "Star Rating" is should be displayed.

![#26511](https://user-images.githubusercontent.com/41110392/81950746-fd8a2e00-9621-11ea-8c56-9d8d1d3275fa.png)

[#26511.zip](https://github.com/woocommerce/woocommerce/files/4629221/26511.zip)

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

I made sure ratings are set as required in settings
![Screenshot 2020-05-14 at 21 51 01](https://user-images.githubusercontent.com/24649833/81985328-05e86600-962e-11ea-84f5-0eb9608bcc2a.png)

![Screenshot_2020-05-14_at_21_51_48](https://user-images.githubusercontent.com/24649833/81985556-52cc3c80-962e-11ea-9a66-a12537204c45.png)

I think this is where it is set

https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/templates/single-product-reviews.php#L124

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Fixed"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
