### ISSUE TITLE
missing space between tax rate and percentage sign for german shops

### ISSUE THREAD

**Issue by toxicdemonWP** [woocommerce/woocommerce#26535]
**Describe the bug**
In the german version of WooCommerce we need a protected space between the tax rate and the percentage sign - At the moment Woo provides it like 19%, but it has to be 19 %. 

References:

https://de.wikipedia.org/wiki/Prozent#Schreibweise (german wiki)
See also the DIN 5008 - (German Institute for Standardization)

**Expected behavior**
In the best way german user can choose this option like the currency options in the settings. So the user can pick the correct formatting for their country.

**Comment by tammullen** [comment]
Hi @toxicdemonWP 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

Can you provide us with more details on which screens, fields etc you are seeing this tax rate format.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​
Label:

**Comment by toxicdemonWP** [comment]
Hej @tammullen 

my fault. sorry. i thought the information was so general, but of course i should say where i mean it.

**To Reproduce**
1. Set the shop to German language / tax rates
2. See the product category (screenshot 1)
3. new the price you see the tax rate with percentage sign
3. go straight to any product page (screenshot 2)
4. near the price should be the tax rate with percentage sign. 
5. put the product in the cart (screenshot 3)
6. here you also can see the tax rate with percentage sign
---
everywhere where also the price and tax are displayed in the shop. this is a generally incorrect view. **it is not dependent on the theme or other plugins.**

**Screenshots**
Screenshot 1 - Category view
![category-view-tax](https://user-images.githubusercontent.com/39014251/82652164-71799700-9c1d-11ea-80cf-f9c01e05dc96.jpg)

Screenshot 2 - Product view
![product-view-tax](https://user-images.githubusercontent.com/39014251/82652242-94a44680-9c1d-11ea-9764-c5eb419b86b0.jpg)

Screenshot 3 - Cart view
![cart-view-tax](https://user-images.githubusercontent.com/39014251/82652425-e351e080-9c1d-11ea-8351-8ecb869f887a.png)

**Comment by PaulCityhopper** [comment]
Sorry, but @juliaamosova closed this, but I cant see the solution or feedback for this!?

**Comment by peterfabian** [comment]
Hi folks, I have a feeling this might be coming from another plugin (Maybe Germanized for WC?). Would you be able to share the system status report with us and perform the troubleshooting steps (deactivate other plugins and switch to the Storefront theme temporarily) to ensure it's WooCommerce that is formatting the output here?
