### ISSUE TITLE
Wrong types documented in includes/class-wc-query.php

### ISSUE THREAD

**Issue by jellyNoone** [woocommerce/woocommerce#26537]
While viewing the source code I noticed that two lines in doc blocks specify a wrong type.
[Line 518](https://github.com/woocommerce/woocommerce/blob/8b0d4ef050fad20a96b0438b2050525fd9e38365/includes/class-wc-query.php#L518): I believe the type should be WP_Query not WC_Query
[Line 704](https://github.com/woocommerce/woocommerce/blob/8b0d4ef050fad20a96b0438b2050525fd9e38365/includes/class-wc-query.php#L704): I believe the type should be WP_Query not array

Can someone else confirm this?

**Comment by jonathansadowski** [comment]
Hi @jellyNoone,

Thank you for taking the time reporting this, we really appreciate your help. I have confirmed it on my end. 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by jellyNoone** [comment]
Great, glad I could help
