### ISSUE TITLE
CSV Import Actions vs Filters

### ISSUE THREAD

**Issue by graftedin** [woocommerce/woocommerce#26578]
In class-wc-product-csv-importer.php set_parsed_data you have an action right before the foreach that allows us to hook in to here.  However I can't manipulate and return the data with an action.  There is a filter at the end of the method but by then the data has already been worked on and its too late.

In my instance I have 100s of categories for some of my products.  That combined with depth of the category structure is putting me way over the character limit for an excel field.  I'm using tags (shortcodes) for repetitive strings that brings me under the character limit and I need to swap those tags out for the real string before the categories get saved to the database.  I have to do it at this action point or its too late.

Can we switch this to a filter or add a filter at this spot?  I would argue that any time you have an action a filter should be available at that point.....especially if there is data that might potentially need to get manipulated.

**Comment by claudiosanches** [comment]
Hello @graftedin 

> Can we switch this to a filter or add a filter at this spot? I would argue that any time you have an action a filter should be available at that point.....especially if there is data that might potentially need to get manipulated.

Sorry but we can't switch this action to an filter, the purpose of this action is really run some action while parsing the CSV content, but you can manipulate any data using `woocommerce_product_importer_parsed_data`.

> I have to do it at this action point or its too late.

It isn't too late, you can still access the raw data, and change anything that got parsed on it.

See an example:

```php
add_filter( 
    'woocommerce_product_importer_parsed_data',
    function( $parsed_data, $importer ) {
        $parse_functions = $this->get_formating_callback();
        $mapped_keys     = $this->get_mapped_keys();

        // Gets CSV raw data to parse.
        $raw_data = $importer->get_raw_data();

        // Now you can manipulate anything here.

        return $parsed_data;
    },
    10,
    2
);
```

I hope it helps you.

**Comment by graftedin** [comment]
Why do you close this before I can comment?!

It doesn't need to be "switched" to a filter but we need a filter at this point.  I can't filter data after this point because I need to manipulate the categories and categories have already been switched to ids by the time we get to th woocommerce_product_importer_parsed_data filter.  I suppose we could redo all of the cateogories but we're talking about 900+ products and some of them have 100s of categories.  A FILTER right before the woocommerce_product_importer_before_set_parsed_data action would allow me to EFFICIENTLY manipulate this data before the rest of set_parsed_data can.

And the counter part to set_parsed_data is generate_row_data and there....you have a FILTER that allows me to manipulate the data after its been converted back to text.

I'm not asking that you remove the action.  Just add a filter....which is exactly what I did.

**Comment by claudiosanches** [comment]
Hello @graftedin

I closed because it's a feature request, but there's already a filter that could be used to achieve that you intent to do. But there's nothing stopping you to keep talk with me here and we can discuss more it, but it closed since it isn't something that we could consider implementing at this point.

> I can't filter data after this point because I need to manipulate the categories and categories have already been switched to ids by the time we get to th woocommerce_product_importer_parsed_data filter.

This isn't true as I demonstrate in my example in https://github.com/woocommerce/woocommerce/issues/26578#issuecomment-637586798
You can still access all row data using `$importer->get_raw_data()`.

> I'm not asking that you remove the action. Just add a filter....which is exactly what I did.

I understand that, but as I said you can use `woocommerce_product_importer_parsed_data` change manipulate it, no strong reason to need a new filter.

**Comment by graftedin** [comment]
And then I have to convert 900 * 100 categories back in to ids?  And its already taking over an hour to import this csv and it crashes 1 out of every x times.  You are just adding to the time it takes to import and the likelihood it will crash.

And why on earth would you use an action at this point rather than a filter?  A filter will allow me to act and just return the data.  An action will not allow me to filter.  I would argue all actions should be filters unless the data needs to be protected for some reason.  There's no reason to protect the data at this point.

**Comment by claudiosanches** [comment]
@graftedin sorry if you still believe I’m misunderstanding your use case.

> In my instance I have 100s of categories for some of my products. That combined with depth of the category structure is putting me way over the character limit for an excel field. I'm using tags (shortcodes) for repetitive strings that brings me under the character limit and I need to swap those tags out for the real string before the categories get saved to the database. I have to do it at this action point or its too late.

If I understand correctly, you are using custom shortcodes in the CSV file instead of long strings to describe categories. I understand that you don't want WooCommerce to parse any category before you expand those shortcodes into categories.

I think it could be solved by using `woocommerce_csv_product_import_mapping_options` filter to introduce a new option to the "Column mapping" screen from the CSV importer, and during the importation you should select this new option instead the default "Categories", it will allow you to parse and expand your custom shortcodes, preventing also WooCommerce to parse those categories, in fact you'll tell when WooCommerce can parse.

See my example:

```php
add_filter(
    'woocommerce_csv_product_import_mapping_options',
    function( $options ) {
        // It introduces a new option in the "Column mapping" page.
        $options['custom_categories'] = 'Custom Categories';

        return $options;
    }
);

add_filter( 
    'woocommerce_product_importer_parsed_data',
    function( $parsed_data, $importer ) {
        $mapped_keys = $importer->get_mapped_keys();
        $keys        = array_flip( $mapped_keys );

        if ( empty( $keys['custom_categories'] ) ) {
            return $parsed_data;
        }

        // Gets CSV raw data to parse.
        $raw_data = $importer->get_raw_data();

        // Gets $custom_categories value.
        $custom_categories = $raw_data[0][ $keys['custom_categories'] ];

        // Now you can parse and expand your shortcodes from $custom_categories here.

        // Finally we can let WooCommerce parse the categories.
        // Note that we return the 'category_ids' instead of 'custom_categories'.
        $parsed_data['category_ids'] = $importer->parse_categories_field( $custom_categories );

        // Remove custom mapping from the parsed data.
        unset( $parsed_data['custom_categories'] );

        return $parsed_data;
    },
    10,
    2
);
```

With this example you should select "Custom Categories" instead of "Categories" while mapping your CSV file columns, and as you can see you'll control everything.

Please let me know if it helps you.

**Comment by graftedin** [comment]
Thanks for your reply.  I'll take an other look.
