### ISSUE TITLE
Rounding precision issue possibly related to tax inclusive pricing

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#26582]
**Affected customers**
2996867-zen

**Describe the bug**
Line items are not adding up correctly in orders, but I am not sure if this is related to tax inclusive pricing or not. I've tried changing the _Round tax at subtotal level, instead of rounding per line_, but amounts in the order still do not add up correctly (see screenshots). 

Customer is using [Nets Easy for WooCommerce](https://wordpress.org/plugins/dibs-easy-for-woocommerce/) gateway, which adds up the line items and sends them along with the order total for transactions. Due to they are getting mismatched amounts in their orders, transactions are getting rejected. 

**To Reproduce**
1. Set prices to be inclusive of tax with: _Yes, I will enter prices inclusive of tax_
1. Tax rate is 15%
1. Create 2 products, one with a price of 99.48 and the next with the price of 108.68
1. Create order in admin with 6 of each item
1. Be sure to _Recalculate_
1. Depending on you _Round tax at subtotal level, instead of rounding per line_ setting, either the subtotals do not add up to the total, or the line items do not add up to the subtotal. 

**Screenshots**
This is with _Round tax at subtotal level, instead of rounding per line_ disabled:
![](https://d.pr/i/zDvrZ4+)
Image Link: https://d.pr/i/zDvrZ4

This is with_ Round tax at subtotal level, instead of rounding per line_ enabled:
![](https://d.pr/i/G038XT+)
Image Link: https://d.pr/i/G038XT

**Expected behavior**
For the amounts in the order to add up.

**Comment by billrobbins** [comment]
Possibly also happening in 2997520-zen

**Comment by webdados** [comment]
I also saw a strange behavior on some orders changing the rounding, after hitting "Update" on the wp-admin order screen.

Settings:
- Tax set to 23% (Portuguese default VAT)
- Prices entered with tax: yes
- Rounding: Round tax at subtotal level, instead of rounding per line

See the issue happening here:
- https://www.dropbox.com/t/QImPpSVHzgBpr5IR (expires on June 15)

**Comment by webdados** [comment]
4.3.0 milestone?

I think this is important enough to be part of a 4.2.1 bugfix ASAP.

Payment gateways that rely on the value of the order to match the amount paid are failing because of this. See my comment above, 15 minutes ago:
- After hitting "Update" the value changes
- Now when the payment gateway (in this case Portuguese Multibanco) tries to notify the website of the payment it will fail because the paid value does not match: https://www.dropbox.com/t/0RjglEhw1eZDWFYv (expires on June 15)

**Comment by josefreitas2** [comment]
As this is a question related to taxes, I agree with @webdados It should be a real priority and be part of a bug fix.

**Comment by webdados** [comment]
I don't think we can have an order changing value just by pressing "update" without changing anything on it 🤷🏻‍♂️

**Comment by negapo** [comment]
Any update on this? Its causing a lot of problems, costumers dont understand why they are paying one cent extra or one cent short, invoicing software, that independently calculates the order totals and checks against the amount paid are failing.

**Comment by claudiosanches** [comment]
@negapo it will be released with WooCommerce 4.3.0 in July 7th. You can test a RC version including this fix with https://downloads.wordpress.org/plugin/woocommerce.4.3.0-rc.1.zip

**Comment by negapo** [comment]
Thanks @claudiosanches
