### ISSUE TITLE
False positives on the uploads directory being browsable via the web. 

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#26599]
**Describe the bug**

Following a recent update in WooCommerce core release, specifically, the following change: 

https://github.com/woocommerce/woocommerce/pull/26207

Some folks are reaching out saying that this is a false positive as the directory in question is NOT browsable. It seems to happen for both NGINX and Apache server. 

One of the sites in question: https://gallmet.hu/wp-content/uploads/woocommerce_uploads

As you can see, the directory is not browsable, but the error message remains. 

In the above case, the details is as follows: 

`Apache/ PHP 7.4.6 / cURL 7.62.0`

In other case, it is NGINX setup and `autoindex off;` is already set correctly, but the error remains. 

In another "Apache" case, the information is as follows: 

```
### Server Environment ###

Server Info: Apache
PHP Version: 7.2.31
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.70.0
OpenSSL/1.1.1g
```
A few cases where the issue exists: 

2996060-zen
3000673-zen

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

Thanks!

**Comment by rynaldos** [comment]
Another report: 

> Server architecture     Linux 3.10.0-957.21.3.el7.x86_64 x86_64
> Web server      Apache
> PHP version     7.3.18 (Supports 64bit values)
> 
> Set folder perms to 750 but the error message still appears.

**Comment by stephhjacq** [comment]
Another report in 2996060-zen

Server Info: Apache
PHP Version: 7.2.31
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.70.0
OpenSSL/1.1.1g

**Comment by WillBrubaker** [comment]
I've got a user in #3022956-zen who updated to 4.2 hoping to get this resolved, but it has not worked for them.

**Comment by dmvrtx** [comment]
Same situation with #3626381-zen on version 4.8.

**Comment by CodeSmith32** [comment]
I have this issue as well:

WooCommerce v6.6.0
WordPress 6.0

But I discovered it's happening because of how WooCommerce determines the directory is 'browsable':
- It makes a request to the url: If the response has status 200 and is not an empty body, it shows this notice.

```php
// woocommerce/includes/admin/class-wc-admin-notices.php: line 641
$is_protected = ( 200 === $response_code && empty( $response_content ) ) || ( 200 !== $response_code );
```

The site I'm working on is not public. I've set my 'hosts' file to manually point the domain to the IP.
Therefore, the request WooCommerce makes brings up some random page with status 200, not blank, but not a directory index.

Regardless, it would probably be nice if it at least did additional checking to determine if the content is a directory index page. I think this would fix most of (maybe all?) the recurrences reported above (at least the one mentioned by the OP).

Even a simple Regex check would suffice.
e.g., The following checks that the title of the page is "Index of ..." and that it contains a `<table>`:

```php
$is_protected = (
	200 !== $response_code
	|| empty( $response_content )
	|| 1 !== preg_match( '/<title>\\s*index\\s+of\\s+[\\s\\S]*<table/i', $response_content )
);
```
