### ISSUE TITLE
Some characters are not supported in additional tax class names

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce#26595]
**Describe the bug**
Some characters in other languages such as 关税 or 关税 are not supported in additional tax class names.

**Reported in**

20491082-hc

**To Reproduce**
1. Go to WooCommerce >> Settings >> Tax
2. Add 关税 or 关税 or both under "additional tax classes".
3. Go to a product edit page and try changing tax class to one of those.
4. After saving, the tax class will be reverted to "standard class".

**Screenshots**
<img width="1170" alt="Screenshot 2020-05-24 at 14 03 23" src="https://user-images.githubusercontent.com/13084901/82753641-5fd3f300-9dc7-11ea-90fb-c0aaba19ac67.png">

<img width="1466" alt="Screenshot 2020-05-24 at 14 03 36" src="https://user-images.githubusercontent.com/13084901/82753643-65313d80-9dc7-11ea-91f2-ac7ea1f84107.png">

**Expected behavior**
Characters in other languages should be supported, too.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @grigorijurasov,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end - see gif below:

![](http://g.recordit.co/gj1IOyj6c6.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

Also, referencing https://github.com/woocommerce/woocommerce/issues/26488 as it seems related.

**Comment by swatipawarGS** [comment]
Hi @grig-23 ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version  . 


Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/145377822-b1dd65de-1d7c-480a-883b-4b303704a2fc.mp4


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.
