### ISSUE TITLE
A question about security update

### ISSUE THREAD

**Issue by lutifyme** [woocommerce/woocommerce#26602]
Hi all,

I have a security related question.

This url here https://plugins.trac.wordpress.org/browser/woocommerce/tags/4.1.0/readme.txt?rev=2298743 at line 191 details a security update.

The changelog here https://raw.githubusercontent.com/woocommerce/woocommerce/master/CHANGELOG.txt however doesn't.

My question is, was there or was there not a security update?

Secondly, if there was a security update, fixed in 4.1.0, what happens for those still on 3.x.x?

Do they not get the security update? From past experience with you guys, they should.

I'm asking as I got notified by Wordfence plugin about it.

Thanks.

**Comment by juliaamosova** [comment]
Hi @lutifyme,

Thanks for raising the issue. 

>My question is, was there or was there not a security update?

>This url here https://plugins.trac.wordpress.org/browser/woocommerce/tags/4.1.0/readme.txt?rev=2298743 at line 191 details a security update.

>The changelog here https://raw.githubusercontent.com/woocommerce/woocommerce/master/CHANGELOG.txt however doesn't.

There was a security update indeed in 4.1.0. The difference you see is the misconfiguration on our end - we are fixing it as we speak. Thanks again for noticing it. 

>Secondly, if there was a security update, fixed in 4.1.0, what happens for those still on 3.x.x?

Those on 3.x.x version need to update to 4.1.0 or higher in order to get the latest security updates. All of our security fixes are being released in the newer version of WooCommerce superseding any previous updates.

**Comment by claudiosanches** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/26615
