### ISSUE TITLE
Adding filters to the `$args` for widget_start() from the Widgets.

### ISSUE THREAD

**Issue by basserd** [woocommerce/woocommerce#26618]
**Is your feature request related to a problem? Please describe.**
Well it is not necessarily a problem but for one of my clients I had to style the heading of the price range widget. This is hard since there is not class/element being added to the title. I've also made some widgets myself and then I've just used the arguments `$args['before_title'] & $args['after_title']`.

**Describe the solution you'd like**
It would be nice if there would be an apply filter right before widget_start() is being called. 

The following could be a solution:
````
$current_min_price = isset( $_GET['min_price'] ) ? floor( floatval( wp_unslash( $_GET['min_price'] ) ) / $step ) * $step : $min_price; // WPCS: input var ok, CSRF ok.
$current_max_price = isset( $_GET['max_price'] ) ? ceil( floatval( wp_unslash( $_GET['max_price'] ) ) / $step ) * $step : $max_price; // WPCS: input var ok, CSRF ok.

$this->widget_start( apply_filters( 'woocommerce_price_filter_args', $args );
````

**Describe alternatives you've considered**
I've searched within the `WP_Widget` class that `WC_Widget` is using. I've hooked into the filter `widget_display_callback` and checked for `$args['widget_id'] === 'woocommerce_price_filter'` and then changed `$instance['title']` to the desired content with HTML tags but as you may understand this is not ideal haha. This also caused the added HTML to be rendered as text.

I've found a temp workaround which is:
````
add_filter( 'widget_title', function( $title, $instance, $id_base ) {
	if ( $id_base == 'woocommerce_price_filter' ) {
		return '<div class="woocommerce_essentials__archive_filters__price__title">' . $instance['title'] . '</div>';
	}

	return $title;
}, 10, 3 );
````

**Additional context**

**Comment by vedanshujain** [comment]
You should be able to target styling the title by using classes `woocommerce widget_price_filter`. Is this not rendering for you for some reason?

Also, the workaround you have to build is actually the correct way to modify the title in case you are not able to target using the above classes. We prefer not to add additional filters unless there is no other way for customization because it makes it hard in the future to make changes to the code. 

I am closing the issue now, but feel free to comment back if you'd like to discuss and I will reopen the issue again.
