### ISSUE TITLE
RFE 4.2: could `WC_Cart::$session` refactor itself `protected` -> `public`?

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#26630]
**Is your feature request related to a problem? Please describe.**
We're hitting a platform configuration point (or plugin cross-interaction) where loading cart infrastructure on every frontend request is having a significant (several 100s ms, enough for us) negative effect on page build speed.

We can only partially work with frontend caching, because we have a membership system, which means large amount is dynamic logged-in requests.

This proposal directly ties into concern previously raised at https://github.com/woocommerce/woocommerce/issues/20937#issuecomment-414065757 - more than expected amount of things hook into calculating and modifying cart items. Optimizing this is a long and arduous process, for some vendors might take years, for some might never happen.

**Describe the solution you'd like**
Because our platform is lucky enough to only need cart display on Cart and Checkout pages, I'd like to unhook cart autoloading system implemented at `WC_Cart_Session::init()`

https://github.com/woocommerce/woocommerce/blob/release/4.2/includes/class-wc-cart-session.php#L44-L64

Currently, 99% of this core cart processing work is pure CPU churn and page speed lag for us.

**Describe alternatives you've considered**
Because I can't do `remove_action WC()->cart->session ...`, we remove hooks directly n `$GLOBALS['wp_filter']`.

It works but we must avoid looking at this code later eternally, if we don't want to go blind.

```php
        /**
         * Test: optimize automatic cart workloads out of non-ecommerce frontend requests.
         *
         * Unfortunately `WC_Cart::$session` is protected. Need dark magic.
         *
         * @see https://github.com/herewithme/wp-filters-extras/blob/master/wp-filters-extras.php
         * @see https://github.com/woocommerce/woocommerce/blob/4.1.1/includes/class-wc-cart.php#L92
         * @see https://wordpress.stackexchange.com/questions/36013/remove-action-or-remove-filter-with-external-classes
         * @since 2020.05.28
         */
        add_action( 'wp_loaded', static function(): void {

            foreach ( [
                [ 'wp_loaded', 10, 'get_cart_from_session' ],
                [ 'wp', 99, 'maybe_set_cart_cookies' ],
                [ 'shutdown', 0, 'maybe_set_cart_cookies' ],
            ] as $tag ) {
                if ( isset( $GLOBALS['wp_filter'][ $tag[0] ]->callbacks[ $tag[1] ] ) ) {
                    foreach ( $GLOBALS['wp_filter'][ $tag[0] ]->callbacks[ $tag[1] ] as $id => $array ) {
                        if ( strpos( $id, $tag[2] ) ) {
                            unset( $GLOBALS['wp_filter'][ $tag[0] ]->callbacks[ $tag[1] ][ $id ] );
                        }
                    }
                }
            }

        }, 9 );
```

**Additional context**
My hypothesis is that going `public WC_Cart::$session` won't hurt anyone in the wild, and allows those needing to get performance done, to get it done in a sane fashion.

This code hasn't been touched since @mikejolley first implemented it for WC3 https://github.com/woocommerce/woocommerce/commit/c0368362ced01e40001da80e663986ed38f9d8fe so it's doubtful anything will break.

Your thoughts?

**Comment by ObliviousHarmony** [comment]
Hi @lkraav,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly an area in need of improvement, I'd like to discuss this further with the team before giving a solid answer. I'm going to mark this as a question so that we can review it as a team.

For a little context behind my decision: changing this variable to `public` is indeed harmless at face value but it commits us to maintaining this API for the foreseeable future. One of the reasons we encapsulate variables in classes is so that we're free to change the internal structure of a class without worrying about external consumers of it. This makes it very hard to make future performance optimizations and only further exasperates the problem that you're trying to solve in the first place.

Stay tuned for updates.

**Comment by lkraav** [comment]
Thanks. Please keep in mind that performance is the goal here, and making `WC_Cart_Session` public is possibly only one option of many. But I lack insights into what alternatives there may be. 

Perhaps these potentially resource-hungry actions I'm looking to unhook could be added from already public `WC_Cart` object instance instead?

Anything other way :thinking:?

**Comment by Konamiman** [comment]
The cleanest best solution I can think for this is introducing a new filter:

```php
if( apply_filters( 'woocommerce_autoload_cart', true ) ) {
  //Go ahead and load/hook everything as usual
}
```

Do you think that would make sense @ObliviousHarmony?

**Comment by Konamiman** [comment]
The cleanest solution I can think for this is introducing a new filter:

```php
if( apply_filters( 'woocommerce_autoload_cart', true ) ) {
  //Go ahead and load/hook everything as usual
}
```

Do you think that would make sense @ObliviousHarmony?

**Comment by lkraav** [comment]
> The cleanest best solution I can think for this is introducing a new filter:
> 
> ```php
> if( apply_filters( 'woocommerce_autoload_cart', true ) ) {
>   //Go ahead and load/hook everything as usual
> }
> ```
> 
> Do you think that would make sense @ObliviousHarmony?

I like this optional cart autoloading concept a lot.

**Comment by ObliviousHarmony** [comment]
Looking at the session code @Konamiman, we could put that in `WC_Cart_Session::init()` to short-circuit the initialization. Since all of the hooked methods are public, developers could implement their own handling as desired. A hook name like `woocommerce_cart_session_initialize` might be better too. The method isn't autoloading the cart so much as it is connecting it to various events.

**Comment by Konamiman** [comment]
@ObliviousHarmony There's still a problem, though: if a dev wants to use the filter to disable the hookings, but still wants to later on enable some of the existing hooks from `init`, that's not possible because the cart session object is still inaccessible 🤔

**Comment by ObliviousHarmony** [comment]
That's true @Konamiman, but, is that a desired behavior in the first place? It seems like that could be error-prone since there may be unintended side effects. If we're passing the cart session to the `woocommerce_cart_session_initialize` hook, they will have access to it and can handle more complicated use-cases like that in their plugin's code. What do you think?

**Comment by Konamiman** [comment]
Pull request on its way: https://github.com/woocommerce/woocommerce/pull/34156
