### ISSUE TITLE
Symbols like ; or . in product category names break the import

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#26665]
**Describe the bug**
Symbols like ; or . in product category names can break the import

**To Reproduce**
1. Export a .csv file
2. In wp-admin, delete the product, remove from trash.
3. Change the category name (and add a symbol like . or ; at the end).
4. If there is no category with the same name but no semicolon or a dot - the category is created.
5. If there is already a product category with the same name except for a dot or a semicolon - the product will be added to that category.

**Expected behavior**
A new product category should be created every time when there's an additional dot or semicolon

**Reported in**

3017949-zen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @grigorijurasov 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

![Screenshot 2020-06-03 at 12 13 02](https://user-images.githubusercontent.com/24649833/83630731-37e94a00-a594-11ea-8eaa-a6add6ce7a2d.png)
I created a csv file with the scenarios you described.

![Screenshot 2020-06-03 at 12 11 56](https://user-images.githubusercontent.com/24649833/83630736-3a4ba400-a594-11ea-99a2-c0e211f64dfd.png)
After importing it the product with category `Tshirts;` is added to existing category `Tshirts`. I also tried this with `Tshir;ts` and the same thing happened.
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by juliaamosova** [comment]
Hi @grigorijurasov and @tammullen,

I looked into fixing this issue but so far I am inclined that it won't be possible on our end. Mainly because we rely on WordPress's functions `term_exists()` and `wp_insert_term()` to check for existing categories during import and add a new term (category) to the database if the category doesn't exist. Both of these functions sanitize the initial entry in some interesting way. 

Here is where we parse the category field from CSV:

https://github.com/woocommerce/woocommerce/blob/master/includes/import/class-wc-product-csv-importer.php#L381-L432

We first look to see if the category already exists in the database using [`term_exists()` function](https://developer.wordpress.org/reference/functions/term_exists/):

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/import/class-wc-product-csv-importer.php#L362

Next, in `term_exists()` both the `$term` (Category name) and `$slug` (Category slug) get sanitized:

https://github.com/WordPress/WordPress/blob/master/wp-includes/taxonomy.php#L1398-L1399

After this, the `$term` (Category name) gets to keep the semicolons but `$slug` (Category slug) doesn't (I debugged this locally to confirm it). 

For example, if the initial `$term` was `Clothing;`, after passing sanitization:

- `$term` - stays `Clothing;`
- `$slug` becomes `clothing`

In particular, `$slug` gets sanitized through [`sanitize_title()` WordPress function](https://developer.wordpress.org/reference/functions/sanitize_title/). This function applies a filter of the same name to which Wordpress adds `sanitize_title_with_dashes` by default:

https://github.com/WordPress/WordPress/blob/master/wp-includes/default-filters.php#L249

Finally, `sanitize_title_with_dashes()` strips the semicolon via:

https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L2307

From here, I debugged further locally and identified that after passing the query below the `$term` also gets sanitized and becomes `Clothing`:

https://github.com/WordPress/WordPress/blob/master/wp-includes/taxonomy.php#L1419-L1422

This explains why `Clothing;` doesn't get created when imported via CSV if the category `Clothing` exists. 

Now let's take a look at what happens if the category such as `Clothing;` doesn't exist. 

If the category doesn't exist, we use [WordPress function `wp_insert_term()`](https://developer.wordpress.org/reference/functions/wp_insert_term/) to add an entry (category) to the database:

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/import/class-wc-product-csv-importer.php#L368

https://github.com/WordPress/WordPress/blob/master/wp-includes/taxonomy.php#L2125-L2130

Wild things happen when you pass it a category with semicolons. 

Let's say I have only `Uncategorized` and `Clothing categories`:

![Screen Shot 2020-06-04 at 5 55 43 PM](https://user-images.githubusercontent.com/19143190/83814614-b2959080-a68c-11ea-9003-2dfbf678ddc0.png)

Using `wp_shell`, here is what I am getting:

1) I want to add `Clo;thing`:

![Screen Shot 2020-06-04 at 5 58 07 PM](https://user-images.githubusercontent.com/19143190/83814804-fbe5e000-a68c-11ea-8d03-cca227ad3203.png)

I am getting the following - note that the slug is `clothing-2` while the name of the category added has a semicolon:

![Screen Shot 2020-06-04 at 5 59 27 PM](https://user-images.githubusercontent.com/19143190/83814901-2df74200-a68d-11ea-916a-b3d3dfbb8426.png)

In the DB, it looks like this as well:

![db1](https://user-images.githubusercontent.com/19143190/83815009-6008a400-a68d-11ea-80cf-8fdcb6c18069.jpg)

2) I want to add `Mu;sic;`:
![Screen Shot 2020-06-04 at 6 02 59 PM](https://user-images.githubusercontent.com/19143190/83815179-a65e0300-a68d-11ea-8839-526c79b898d5.png)

Note that the category name was added with semicolons but the slug is just `music`:

![Screen Shot 2020-06-04 at 6 01 53 PM](https://user-images.githubusercontent.com/19143190/83815099-81699000-a68d-11ea-8834-80602213f939.png)

3) I want to add `Music`:

I am getting the category name `Music` and slug `music-2`:

![Screen Shot 2020-06-04 at 6 07 28 PM](https://user-images.githubusercontent.com/19143190/83815494-52075300-a68e-11ea-920e-5340909987b7.png)

4) Finally, I want to add `Music` again and I am getting a message that term already exists:

![Screen Shot 2020-06-04 at 6 08 28 PM](https://user-images.githubusercontent.com/19143190/83815563-706d4e80-a68e-11ea-8eec-0366c4d4dd08.png)

All in all, I am not sure what we can do here. 

What I do think is that us verifying that `term_exists()` is redundant because `wp_insert_term()` verifies that - see description of the function:

https://developer.wordpress.org/reference/functions/wp_insert_term/

So this line of code can be removed:

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/import/class-wc-product-csv-importer.php#L362

I will chat more with someone else on our team to verify my logic and provide further feedback here.

**Comment by juliaamosova** [comment]
Found the way to fix the issue https://github.com/woocommerce/woocommerce/pull/26720.
