### ISSUE TITLE
Tracker snapshots fix

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#26689]
If the user opts-out for usage tracking we should also stop sending the Tracker snapshots.

cc @timmyc

**Comment by juliaamosova** [comment]
I assume this is to be included in 4.3 so assigning the milestone here. cc @peterfabian.

**Comment by rrennick** [comment]
@pmcpinto Do you see data from sites that have opted out of sending data? It looks like sending data is already turned off for opted out sites https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L475 .

**Comment by pmcpinto** [comment]
> @pmcpinto Do you see data from sites that have opted out of sending data? It looks like sending data is already turned off for opted out sites

I don't have a way to confirm that. @deltaWhiskey do you know if it's possible to check this for Tracker data?

**Comment by deltaWhiskey** [comment]
@rrennick is right; snapshots are not sent when a user opts out of Tracking **in WooCommerce**.

However, I see that this issue is a follow-up to this one: https://github.com/Automattic/wc-calypso-bridge/issues/551 . @pmcpinto , is the "opts-out for usage tracking" we're talking about the one in https://wordpress.com/me/privacy ?

If so, this comment looks like a good description of what should be done: https://github.com/Automattic/wc-calypso-bridge/issues/551#issuecomment-638351246

**Comment by pmcpinto** [comment]
> @pmcpinto , is the "opts-out for usage tracking" we're talking about the one in https://wordpress.com/me/privacy ?

Yes that's correct. Sorry, I missed this ping last week

**Comment by rrennick** [comment]
Closing this as it needs to be addressed on WordPress.com. The privacy setting is a user setting vs a site setting and WordPress.com will need to add logic to convert the site owner's setting to a site setting.
