### ISSUE TITLE
"Invalid refund amount" on $0 refund when number of decimals = 0

### ISSUE THREAD

**Issue by VivekManglani** [woocommerce/woocommerce#26686]
When the Number of Decimals setting is set to 0, cannot make a $0 refund.

1. Go to WooCommerce Settings, set Number of Decimals to 0
2. Refund an order by setting the quantity to a number > 0 and the refund amount to 0.
3. Should see a browser alert message "Invalid refund amount"

Issue is in `class-wc-ajax.php` Line 1860.

```
if ( ! $refund_amount || $max_refund < $refund_amount || 0 > $refund_amount ) {
    throw new Exception( __( 'Invalid refund amount', 'woocommerce' ) );
}
```

Should be:

```
if ( ( ! $refund_amount && $refund_amount !== wc_format_decimal(0, wc_get_price_decimals() ) ) || $max_refund < $refund_amount || 0 > $refund_amount ) {
    throw new Exception( __( 'Invalid refund amount', 'woocommerce' ) );
}
```

**Comment by tammullen** [comment]
Hi @VivekManglani 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2020-06-04 at 11 48 47](https://user-images.githubusercontent.com/24649833/83748383-05098980-a65a-11ea-9c96-e3a20771605c.png)
Refund works for $0.00

Changing number of decimals to 0 and trying a refund for $0 triggers alert
![Screenshot 2020-06-04 at 11 54 35](https://user-images.githubusercontent.com/24649833/83748538-4437da80-a65a-11ea-8360-8218502ecfd1.png)


We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
