### ISSUE TITLE
[GlobalStep]On Windows 10 for BLUEHOST Site user fails to unchecke “Enable tax” checkbox from WooCommerce -> Settings ->General.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26709]
**Environment:**
Windows 10: Chrome(v83.0.4103.61)

**Steps to Reproduce:** 
1. Login with BLUEHOST site.
2. Click on WooCommerce.
3. Click on Settings.
4. Scroll to the "Enable Tax" checkbox.
5. Note that checkbox is checked by default.
6. Now uncheck "Enable Tax" checkbox.
7. Note that it gets unchecked.
8. Now save the settings.
9. Again scroll back to "Enable Tax".
10.  Observe that the checkbox is checked by default.

**Actual Result:**
On Windows 10 for BLUEHOST Site user fails to uncheck “Enable tax” checkbox from WooCommerce -> Settings ->General.

**Expected Result:**
User should be able to uncheck the "Enable tax" checkbox and Tax option should be hide from the frontend.

[#2639.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4730998/2639.zip)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for raising the issue. I am indeed not able to disable the taxes in WooCommerce on that particular test site hosted with BlueHost:

![bluehost](https://user-images.githubusercontent.com/19143190/83912068-3a39d880-a73b-11ea-9ad6-5b40ad191f58.jpg)

This is because this particular test site has [WooCommerce Services](https://wordpress.org/plugins/woocommerce-services/) plugin installed which enables automated taxes:

![services](https://user-images.githubusercontent.com/19143190/83913319-550d4c80-a73d-11ea-928f-f994652df0fc.jpg)

When automated taxes are enabled, it is not possible to disable taxes overall on the site via General Settings. I have filed an issue with the WooCommerce Services team some time ago: https://github.com/Automattic/woocommerce-services/issues/2006. 

I am closing this issue since this is not something that we can fix on our end but needs to be fixed on the WooCommerce Services side of things.
