### ISSUE TITLE
Trashing "On Hold" orders doesn't restore stock

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce#26716]
**Describe the bug**
There's a resolved discussion [here](https://github.com/woocommerce/woocommerce/issues/18191) about why "On Hold" orders don't auto-cancel. That said, there's no easy way to "Cancel" an order from the Orders screen; the closest available "Bulk Action" is to trash the order(s).

However, if an On-Hold order is trashed, the stock remains reduced.

**Expected behavior**
 Shouldn't trashing an unpaid order restore stock?

3037663-zen

**Comment by negapo** [comment]
Yes, it should, trashing an order that was set to reduce stock should increase it when cancelled or trashed. Hope this one gets noticed, stock management has come a long way on Woo but it still brings us a lot of headaches.

**Comment by 2GOOD** [comment]
Since several fake orders artacks this is a must have option for Woo

**Comment by vedanshujain** [comment]
We discussed this internally, and unfortunately, stocks cannot be modified on trashing because orders may be trashed, for example, when archiving old orders, among other things. Increasing stock in these cases would led to confusion among existing shop owners who use trashing regularly.

Instead, we will be pursuing adding bulk cancellation support, which does restock orders in #29928
