### ISSUE TITLE
Where is this headed?

### ISSUE THREAD

**Issue by slavicd** [woocommerce/woocommerce#26749]
![image](https://user-images.githubusercontent.com/1071705/84381366-9bf1bb00-abf1-11ea-96a8-c85528f8dc9f.png)

Some of the late decisions make me think this is no longer a community supported project, but rather a company that is using the community as a free workhorse.

Woocommerce 3.9 has been released at the beginning of this year (2020). "will soon discontinue support"? 

What kind of message is this? How can one rely on Woocommerce for production websites when such things happen? People don't like the direction of things in the 4.* version with all the "marketing" root menu nonsense and whatnot and they want to cling on to the 3.9 version. And this is the reaction that comes from Automattic. I am dissatisfied, to say the least.

I hope this will resonate with other people in the community.

**Comment by negapo** [comment]
This is a massive successful project, the most used e-commerce platform in the world, the entry level for a lot of businesses that dont have the budget for other solutions. Unfortunately it seems that Automattic never found a good way of monetizing on this, the interests are not align between them and the users, there are a lot of basic features left out because there is a paid extension sold on Automattic marketplace which is unfortunate. Another issue is that there is some disconnection between the developer community and real life store management, which is natural and happens in every IT company.
I would hope that this project would be more centered in a community development than on Automattic, maybe there are aiming at that, cutting the support. Maybe it's time to fork this out.

**Comment by negapo** [comment]
Just some simple examples of basic stuff one would expect to see:

**Coupons**
- If a coupon amount is not used in full the remaining value should be available to use in future purchases.
- There should be at least an option for coupons to behave like a normal payment in terms of shipping, if the amount of the coupon is above the free shipping value than no shipping is charged, if it's below shipping is charged.

**Stock Management**
- Apply an unified logic to Woo, order types should be by classified in two: orders that manage stock (wc-processing, wc-on-hold, etc,), orders that don't manage stock (wc-pending). If an order manages stock then it should reduce stock when its created (or when the status changes to that order status), and increase when it's cancelled / trashed (or changed to a non manage stock status). There should be an option (a checkbox) to override this (a lot of people have asked for) so when you cancel for example a wc-processing order you have the option to not increase stock levels.
- API should have an option to increment/decrement stock, so a +2 would increment the stock level in 2, and so on, this would facilitate stock management and avoid a first call to the API to check the current stock.

**Performance**
- No need to request all variations images when costumer enters the product page, an http request to pull the image when the costumer selects the proper attributes. This is more problematic when a product has 20 or 30 variations with different images, the probability that the costumer needs to see everyone of them is very small.

**Variations**
- Ability to add more than one picture.
- Ability to list all product variations on the main catalog choosing the attribute/s that are to be treated as a new product (example, create listings for color but not for size).

**webHooks**
- They do not work, have done multiple tests, they are far from reliable.

**Product Filter Widget**
- There has to be a better native product filter with OR and AND type of conditions to help costumers filter the catalog.

This are just some things that i can remember, most of them have open issues here at github or are the type of "there is an extension that does that".

**Comment by peterfabian** [comment]
Hi @slavicd 

Thanks for your input, you brought up good points! 

Automattic's [support policy for WooCommerce](https://docs.woocommerce.com/document/frequently-asked-questions/#wcvers), which currently includes the last 3 releases, will be revised soon, as we're moving on to the monthly release cadence. This policy was formulated earlier when releases were less frequent and we are aware it needs to be revisited. 

Please note, though, that Authorize.NET payment gateway is developed by a 3rd party developer company SkyVerge, so it's ultimately up to them what versions they choose to support. We're trying to produce new versions of WC core that are backwards compatible with previous ones, but if a new version of another plugin requires certain functionality only available in newer WooCommerce versions, it might be difficult to continue supporting older WC versions.

**Comment by peterfabian** [comment]
Hi @negapo ,

Thanks for taking the time to provide good feedback! As you probably know, if you asked 100 people what features they want in an e-commerce platform, you would get 500 different requests and only some of them would be overlapping. What we're trying to do with WC core is to provide a stable and lean core ecommerce platform that serves well for an intersection of features people would request rather than a union of all the requests. 

> If a coupon amount is not used in full the remaining value should be available to use in future purchases.

I believe there are plugins for this. I haven't seen a lot of requests for this feature, so I'm not sure we would add this functionality to core.

> There should be at least an option for coupons to behave like a normal payment in terms of shipping, if the amount of the coupon is above the free shipping value than no shipping is charged, if it's below shipping is charged.

We've had some issues logged to modify this behaviour not so long ago. Please feel free to create one if you think the coupon should behave differently. 

> Apply an unified logic to Woo [Stock management]
We are actually working towards what you described I think (see e.g. https://github.com/woocommerce/woocommerce/pull/26642 or improved stock level management in https://github.com/woocommerce/woocommerce/pull/26395). However, as you can see from the discussion on the first PR, it's not always easy as people use different workflows for their needs, so there are always multiple variables at play.

> API should have an option to increment/decrement stock
I think this is a good idea, we can perhaps add support for atomic operations like check and set to the API. 

> Performance: No need to request all variations images when costumer enters the product page
Performance improvements are always welcome. I think in these cases it's always a tradeoff between pre-fetching those images to provide better user experience when switching variations vs saving time during loading. Perhaps we could do something smarter as well. But again, to be hones, not a lot of people have reached out to change this, so it doesn't seem to be a large factor for most users.

> Variations: Ability to add more than one picture.
Again, this is something plugins can help with. But we're happy to reconsider if we get an indication from our designers or community that the feature is important for most shops.

> Variations: Ability to list all product variations on the main catalog choosing the attribute/s that are to be treated as a new product (example, create listings for color but not for size).
To be honest, I don't recall seeing an e-shop that would do this. But this can be easily achieved by simply creating extra products (unless you have lots of those special variation categories).

> webHooks: They do not work, have done multiple tests, they are far from reliable.
If you can replicate any particular problem reliably, please let us know by raising an issue. We are definitely trying to make them as reliable as possible. 

> There has to be a better native product filter with OR and AND type of conditions to help costumers filter the catalog.
Again, to be honest, all the e-shops I remember always use AND filters. Even the ones that allow for lots of filtering like Booking.com or Amazon or eBay. Maybe they are wrong, but it is possible that it just adds unnecessary mental overhead or confusion for customers. I'm happy to learn otherwise if you have any good sources, though.

I'm closing this issue now, as it's not really a bug we need to fix, but feel free to respond here or open new issues for feature suggestions or bugs.

**Comment by negapo** [comment]
@peterfabian Just let me thank you for taking the time to answer, kudos to you really. Ill take some of these ideas and take it to the proper place (Github, community forum, etc).
