### ISSUE TITLE
Secure cookies

### ISSUE THREAD

**Issue by danieleperilli** [woocommerce/woocommerce#26764]
We need a way to add the "secure" attribute to all cookies set by WooCommerce.
It would be wonderful if you can add a filter inside the wc_setcookie function (something like 'woocommerce_cookie_secure') as you have already done for the httponly attribute ('woocommerce_cookie_httponly').

`setcookie( $name, $value, $expire, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, apply_filters( 'woocommerce_cookie_secure', $secure, $name, $value, $expire), apply_filters( 'woocommerce_cookie_httponly', $httponly, $name, $value, $expire, $secure ) );`

**Comment by tammullen** [comment]
Hi @danieleperilli 

Have a look at this issue https://github.com/woocommerce/woocommerce/issues/20978 and let us know if it helps.

**Comment by danieleperilli** [comment]
Unfortunately, it doesn’t help, because that filter applies only to the session cookie. WC sets other cookies that cannot be intercepted.

**Comment by schferbe** [comment]
As @danieleperilli mentioned the solution form #20978 does not fix it for all cookies. 

I submitted #27653 that would give users the ability to add a hook for the secure cookie. What do I need to do so that pull request gets reviewed?

**Comment by DavidAnderson684** [comment]
I've submitted a pull request - https://github.com/woocommerce/woocommerce/pull/28105 - which is much more flexible. (I want to set the `SameSite` attribute).

**Comment by tj-a** [comment]
> As @danieleperilli mentioned the solution form #20978 does not fix it for all cookies.
> 
> I submitted #27653 that would give users the ability to add a hook for the secure cookie. What do I need to do so that pull request gets reviewed?

+1 for getting this in please - non-secure cookies are likely to throw spanner in the works for future usage of WC because of multiple client security audits. Thanks.

**Comment by danieleperilli** [comment]
Any update? Thanks.

**Comment by danieleperilli** [comment]
Do you have any updates on this?

**Comment by rrennick** [comment]
Removing `needs developer feedback` as discussion will continue on #28105 and #26753

**Comment by selvagem360** [comment]
Hi. it's my first time here. I am not sure if this is the right place to post this, but since I ended up here when I was looking for a solution for woocommerce failing PCI/DSS scan due to cookies not set as Secure and httpOnly... here is what I did and is working for me - at least at the staging website (I will put it live later).

I am using the really simple ssl pro plugin that sets secure cookies options in the wp-config.php and .htaccess (I think  it does work with the free version too).

That made some of the cookies secure and httponly, but not all. I had to disable some plugins that were putting no secure cookies:  Facebook for WooCommerce, for example. The google analytics code also have to be disabled since I've found a way to make the cookie secure, but not httponly (https://www.simoahava.com/analytics/cookieflags-field-google-analytics/).

I also have to add

<IfModule mod_rewrite.c>
Header always edit Set-Cookie (.*) "$1;HttpOnly;Secure"
</IfModule>

to .htaccess

So far, the only cookie i wasn't able to make secure and httponly is the dismiss notice
store_notice4558937508f4f0866101675c5c065647
but I will disable this feature and use a pop plugin instead.

Hope that helps someone to save some hours of research. Again, sorry if this is not the right place to post.
Maybe this is already solved by woocommerce filtets/webhooks, etc. I don't understand much about this.
I am using woocommerce Version 6.2.2

**Comment by selvagem360** [comment]
actually it seems we can't set google analytics to httponly because it won't be acessible by JS...
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies 

I have not idea how websites pass pci/dss scan with analytics enabled. I will research that latre on.

**Comment by danieleperilli** [comment]
I see you added an `apply_filter( 'woocommerce_set_cookie_enabled', ...)` at the beginning of the function `wc_setcookie`, which basically can be used to intercept and replace the secure flag this way: 

`add_filter('woocommerce_set_cookie_enabled', function($enabled, $name, $value, $expire, $secure) {
     if (!headers_sent())
          setcookie($name, $value, $expire, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, true, false);
     return false;
}, 1, 5);`

Thanks!
