### ISSUE TITLE
Disabling manage stock via inventory tab on variable product and then changing stock status on variation reverts to old value until product updated

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#26801]
**To Reproduce**
1. Edit a variable product which has variations and has manage stock enabled via inventory tab and variations with manage stock disabled with stock status: instock
2. Disable manage stock via Inventory tab (Don't update the product)
3. Go to Variations tab, select a variation, change in stock to out of stock
4. Save the variation, after ajax refresh check the option just changed
5. Option has reverted to in stock

**Comment by tammullen** [comment]
Hi @ninetyninew 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 
​

> Go to Variations tab, select a variation, change in stock to out of stock
Save the variation, after ajax refresh check the option just changed
Option has reverted to in stock

When I do these steps the option remains as out of stock after saving variation

![Screenshot 2020-06-18 at 22 34 51](https://user-images.githubusercontent.com/24649833/85074130-f4a5f280-b1b3-11ea-8c94-843d06c33f36.png)
![Screenshot 2020-06-18 at 22 34 41](https://user-images.githubusercontent.com/24649833/85074133-f5d71f80-b1b3-11ea-9d00-d31620529b43.png)

​
Please provide us with more details about the issue which may help us to evaluate it further as well as the remaining details from the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by ninetyninew** [comment]
Please close - Think this maybe a custom plugin issue.
