### ISSUE TITLE
REST API page screen options items per page unable to be saved

### ISSUE THREAD

**Issue by m155y** [woocommerce/woocommerce#26819]
**Describe the bug**
When you go to **WooCommerce > Settings > Advanced** and attempt to change the **Screen Options** `Number of items per page` value, it reverts back to 10 after saving.

**To Reproduce**
1. Go to WooCommerce > Settings > Advanced > REST API
2. Click on `Screen Options`
3. Change the number in **Pagination** "Number of items per page:"
4. Save and see that it reverts back to the default of 10

**Screenshots**
GIF of it in action: https://d.pr/i/vsu2Zo

**Expected behavior**
Number of items per change would be able to be customized and saved.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @m155y,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I also tried to see if pagination works on `All Products` view and it does work there indeed. Video to document my findings:

![](http://g.recordit.co/kMbWO3fTo4.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by jgreys** [comment]
This bug is due to the new filter "set_screen_option_{$option}", the backward compatibility was not ensured in WordPress 5.4.2

https://github.com/WordPress/WordPress/blob/dda0ccdd18f6532481406cabede19ae2ed1f575d/wp-admin/includes/misc.php#L730

Backward compatibility is now ensured on WordPress 5.5

https://github.com/WordPress/WordPress/blob/7ac100615f606144c365a08e89d27f8d62667b3c/wp-admin/includes/misc.php#L732

**Comment by mfs-mindsize** [comment]
@juliaamosova - @jgreys said:

"Backward compatibility is now ensured in WordPress 5.5"

And since I can't reproduce this issue can I presume this bug is not a bug anymore? And this ticket can be closed? 

If I can reproduce it, I'd be willing to work on it. Possibly.
