### ISSUE TITLE
Include '_new_stock' meta in order items meta

### ISSUE THREAD

**Issue by alantygel** [woocommerce/woocommerce#26833]
**Is your feature request related to a problem? Please describe.**
Currently, it is impossible to recover the stock history because only reduced stock is recorded. We don't know neither the initial stock nor the new stock.

**Describe the solution you'd like**
I want the new stock level to be recorded in order item meta.

**Describe alternatives you've considered**
Add the following line:

`$item->add_meta_data( '_new_stock', $new_stock, true );`

before https://github.com/woocommerce/woocommerce/blob/c35c4f1f084bb397a023682229477286b418ad54/includes/wc-stock-functions.php#L184

all the best,
alan

**Comment by ObliviousHarmony** [comment]
Hi @alantygel,

Thank you for taking the time to share this idea, we really appreciate your help. 

It's worth noting that every new meta value comes at a database cost and so these should be adding very sparingly. One of the other issues I see with this approach is that the stock quantity might change dramatically due to concurrent purchases or refunds. For these reasons I'm not sure this would be a good fit for WooCommerce Core.

You could however achieve something similar using the `woocommerce_order_item_quantity` and `woocommerce_product_set_stock` filters. I'm thinking you could store the order item using the filter and then wait for the set stock action to associate the new stock with the item.
 
While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look.
