### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by zeroo5** [woocommerce/woocommerce#26842]
I am Islam from Egypt and use WooCommerce and I want to amend the special regions of Egypt and they are ready for me. I want you to communicate with me and send a form that I fill in so that you can add the governorates and cities of Egypt

Name : Eslam Ghorab
Email : engeslamghorab10@gmail.com

**Comment by juliaamosova** [comment]
Hi @zeroo5,

Thanks for opening the issue. In order to make sure that we are on the same page, can you please confirm that you would like regions to be added to Egypt when you, for example, select Egypt as a shipping zone? You want to be able to select actual regions of Egypt instead of the country, correct? 

![Screen Shot 2020-06-23 at 10 13 18 AM](https://user-images.githubusercontent.com/19143190/85414645-5eb6f280-b53a-11ea-879b-039d051ef3c8.png)

**Comment by zeroo5** [comment]
Yes, I want to add the governorates to Egypt and within each governorate
its own cities. I have collected and arranged them, either in Arabic or
English, to be compatible with the Arab community.

‫في الثلاثاء، 23 يونيو 2020 في 4:15 م تمت كتابة ما يلي بواسطة ‪Julia
Amosova‬‏ <‪notifications@github.com‬‏>:‬

**Comment by juliaamosova** [comment]
>Yes, I want to add the governorates to Egypt and within each governorate
its own cities. I have collected and arranged them, either in Arabic or
English, to be compatible with the Arab community.

Great! You are welcome to submit a PR if you like. Please note that we use UNICODE CLDR format/standard for adding the region to countries in WooCommerce. Regions should be added in the English language. List of regions that can be added for Egypt can be found here:

https://github.com/unicode-org/cldr/blob/release-37/common/subdivisions/en.xml#L1268-L1295

Example PR can be found here: https://github.com/woocommerce/woocommerce/pull/26728

**Comment by zeroo5** [comment]
How can I show them in my site but I have an inquiry these are Egypt's
governorates but there are cities under this provinces I want to add
