### ISSUE TITLE
In WC_Order_Query doesn't work a paginate paramenter

### ISSUE THREAD

**Issue by wppunk** [woocommerce/woocommerce#26859]
In [documentation](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query), we have two types to get a list of orders: `WC_Order_Query` and `wc_get_orders`. So I can't get a `total` or `max_num_page` using a `WC_Order_Query`. 

```
$query = new WC_Order_Query(
	[
		'status'         => [ 'processing', 'on-hold' ],
		'type'           => 'shop_order',
		'posts_per_page' => 20,
		'paginate'       => true,
	]
);
$this->items = $query->get_orders(); // Order list.
$query->total; // null
$query->max_num_pages; // null
```

But when we using a `wc_get_orders()`:

```
$query = wc_get_orders(
	[
		'status'         => [ 'processing', 'on-hold' ],
		'type'           => 'shop_order',
		'posts_per_page' => 20,
		'paginate'       => true,
	]
);
$this->items = $query->orders; // Order list.
$query->total; // 3 (some number)
$query->max_num_pages; // 7 (some number);
```

**Comment by ObliviousHarmony** [comment]
Hello @wppunk,

What you're experiencing is caused by a difference in the arguments expected by `wc_get_orders` when compared to `WC_Order_Query`. In particular you are using the legacy `posts_per_page` instead of `limit`. We have a [wiki page that includes all of the parameters](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query) that should help clear up any confusion!

I hope this helps!
