### ISSUE TITLE
WooCommerce not displaying products with no category or main category while choosing "Show category" option

### ISSUE THREAD

**Issue by theneerajpandit** [woocommerce/woocommerce#26884]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I selected "*Show Categories*" under the "*Shop Page Display*" and "*Show Subcategories*" under the "*Category Display*" options in the "*Product Catalog*" in the WordPress website customization page. Also, my website has the following product category structure:
<ol>
<li>Category 1</li>
<ol>
<li>Subcategory A</li>
<ol>
<li>Product I</li>
</ol>
<li>Product II</li>
</ol>
<li>Category 2</li>
<ol>
<li>Subcategory B</li>
<ol>
<li>Product III</li>
</ol>
</ol>
<li>Product IV</li>
</ol>

While choosing such options in the "*Product Catalog*" customization settings for my website having such shop product category structure, the shop page and *Category 1* page aren't displaying the products which aren't in any category (i.e. *Product IV*) or sub-category (i.e. *Product II*).

Please let me how I can resolve this issue! I would like to get _Product IV_ displayed along with _Category 1_ and _Category 2_ in the main **_Shop_** page because _Product IV_ isn't in any category, and I would also like to get _Product II_ displayed along with _Subcategory A_ in the **_Category 1_** page because _Product II_ isn't in any subcategory of _Category 1_.

Thanks!

**Comment by tammullen** [comment]
Hi @theneerajpandit 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
