### ISSUE TITLE
There should be a filter for low stock.

### ISSUE THREAD

**Issue by squill** [woocommerce/woocommerce#26893]
When I go to WooCommerce / Products, I can filter for ‘in stock/out of stock/backorder’ – but I don’t see any way to filter for low stock. Therefore what I have to do is to scroll ‘all stock’ and look for the ones that are low stock. There should be a filter for low stock.

**Comment by tammullen** [comment]
Hi @squill 

Have you looked at the Stock Report https://docs.woocommerce.com/document/woocommerce-analytics/#section-50
and the Stock Panel https://docs.woocommerce.com/document/activity-panels/#section-3

I believe they can offer what you are after to get a list of low stock items.

**Comment by squill** [comment]
Thank you. That’s exactly what I want and need.

Have I looked at it before? No, I have not. I am a laughing at my failure to ever see that the section existed. How long has it been there?

**Comment by juliaamosova** [comment]
Hi @squill,

No worries at all and thanks for your follow-up. I believe the setting to filter by low stock had been available since the new analytics section was added. And no worries about missing it - it happens to the best of us. 

It looks like you are all set for now so I am closing this thread. Feel free to comment back in case we missed something.
