### ISSUE TITLE
Improve the usability and design of the product data metabox

### ISSUE THREAD

**Issue by passatgt** [woocommerce/woocommerce#26930]
I think it would be a good idea to slightly refresh the product data metabox to make it a bit lighter and friendlier to use. I started designing and this is what i was thinking about:

![woocommerce-product-data-metabox](https://user-images.githubusercontent.com/43415/86283116-b3b0d380-bbe0-11ea-8077-1bbc9f56920b.png)

I replaced the select boxes that only have very few options with easier to use radio buttons. Improved spacing to make things a bit cleaner and consistent. Other small improvements could be made, like the small inventory indicator dot for example. This is not a complate redesign, so it would still be familiar for existing users and also this makes it easier to develop, as most of the stuff can be done via CSS. Tried to follow the built-in WP styles of course, so radio buttons, forms fields, font sizes do match other metaboxes. 

Is this something we should look into? I'm more than happy to work on the other tabs of the metabox.

**Comment by juliaamosova** [comment]
Hi @passatgt,

Thanks for taking the time to work on and submit these redesigns - they look great! We can't, however, immediately act on these changes though as we have plans to fully redesign the UI of WooComerce. Although no specific plans that we can share at the moment as well as no ETA. I will mark this issue with the `design` label for the reference but please don't be alarmed if there will be no action taken on it for some time. 

In order to keep the repository with only relevant issues/bugs, I am going to close this issue. Ince again, thanks for submitting your ideas!
