### ISSUE TITLE
"Order Received" title is misleading when payment failed

### ISSUE THREAD

**Issue by nicomollet** [woocommerce/woocommerce#26977]
Hello

On the "order-received" endpoint, the title always is "Order Received".
If the payment was successful or even if the payment had an error.

Many customers of mine seem to be confused be the "Order Received" that kind of indicates that the order is processing.
Indeed there is an error notice below the title, explaining the error.
If they don't read the small notice, they would think it is all good.

My idea is to contextualize the title, depending on the status of the order.
If status=failed
  title=Payment Failed, 
else 
  title=Order Received

Like the `checkout/thankyou.php` template does actually. 
If status=failed 
  text=Unfortunately your order cannot be processed 
else 
  text=Thank you. Your order has been received

So is this something helpful or conflicts with anything?
Thank you

**Comment by claudiosanches** [comment]
Hello @nicomollet, thank you for submitting this report.

> On the "order-received" endpoint, the title always is "Order Received".
> If the payment was successful or even if the payment had an error.

This is intentional because even if any payment gets failed that order is in fact received and stored on WooCommerce, so allowing that customer to pay again after accessing the "Orders" menu in "My Account" page. There's also an email that gets triggered to notify the shop owner about this order, allowing to send again WooCommerce's "Invoice" email that will also include a link for the customer try pay again.

> Many customers of mine seem to be confused be the "Order Received" that kind of indicates that the order is processing.
> Indeed there is an error notice below the title, explaining the error.
> If they don't read the small notice, they would think it is all good.

I understand your frustration, but there's many ways to improve it, like by highlight those messages better with CSS, it's also possible to over that template or use hooks like `woocommerce_before_thankyou` to include some other message that works best for your business.

And you are also allowed to change that title using filters from WooCommerce. Here an example for what you want to achieve:

```php
add_action(
	'woocommerce_endpoint_order-received_title',
	function( $title ) {
		global $wp;
		$order_id  = isset( $wp->query_vars['order-received'] ) ? absint( $wp->query_vars['order-received'] ) : 0;
		$order     = wc_get_order( $order_id );

		if ( $order && $order->has_status( 'failed' ) ) {
			return 'Payment Failed';
		}

		return $title;
	}
);
```

I'm closing it for now, since it's something that works as expected, and there's alternatives to customize it, but please feel free to still comment on this issue, we can reopen if necessary too. Thanks again for submitting this report.

**Comment by claudiosanches** [comment]
Hello @nicomollet, thank you for submitting this report.

> On the "order-received" endpoint, the title always is "Order Received".
> If the payment was successful or even if the payment had an error.

This is intentional because even if any payment gets failed that order is in fact received and stored on WooCommerce, so allowing that customer to pay again after accessing the "Orders" menu in "My Account" page. There's also an email that gets triggered to notify the shop owner about this order, allowing to send again WooCommerce's "Invoice" email that will also include a link for the customer try pay again.

> Many customers of mine seem to be confused be the "Order Received" that kind of indicates that the order is processing.
> Indeed there is an error notice below the title, explaining the error.
> If they don't read the small notice, they would think it is all good.

I understand your frustration, but there's many ways to improve it, like by highlight those messages better with CSS, it's also possible to over that template or use hooks like `woocommerce_before_thankyou` to include some other message that works best for your business.

And you are also allowed to change that title using filters from WooCommerce. Here an example for what you want to achieve:

```php
add_action(
	'woocommerce_endpoint_order-received_title',
	function( $title ) {
		global $wp;
		$order_id  = isset( $wp->query_vars['order-received'] ) ? absint( $wp->query_vars['order-received'] ) : 0;
		$order     = wc_get_order( $order_id );

		if ( $order && $order->has_status( 'failed' ) ) {
			return 'Payment Failed';
		}

		return $title;
	}
);
```

I'm closing it for now, since it's something that works as expected, and there's alternatives to customize it, but please feel free to still comment on this issue, we can reopen if necessary too. Thanks again for submitting this report.

**Comment by nicomollet** [comment]
Hello Claudio,

Thanks for your complete answer.
I knew about ways to customize, but I thought it would benefit the whole user base.

To me, it would have been more consistent with the status directly in the title.

I will go with my own customization ;)
Kind regards
