### ISSUE TITLE
"you'd" text in Completed Order email template crashes the system

### ISSUE THREAD

**Issue by billipo** [woocommerce/woocommerce#26982]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Adding the word "you'd" into a copied Completed Orders email template crashes my admin interface when I try to mark an order as completed

**Expected behavior**
I want to use the word with out a crash.

**Actual behavior**
Here is a [video of the behavior](https://photos.app.goo.gl/6coJkzNeS6NDdrYQ8).

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodrigoprimo** [comment]
Hi @billipo,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. The type of issue you submitted looks like is a support request and not a WooCommerce core bug. Next time please use our support forums: https://wordpress.org/support/plugin/woocommerce/

Editing an e-mail template means you are altering the PHP code directly. The problem is that adding a single quote comma without escaping it creates a syntax error as, in this case, single quotes are used to delimit the string. You can either replace the string delimiter and use double quotes instead of single quotes or you can escape the single quotes when writing `you'd`:

`esc_html_e( 'Email user@gmail.com with the amount you\'d like to donate.', 'woocommerce' );`

Or:

`esc_html_e( "Email user@gmail.com with the amount you'd like to donate.", 'woocommerce' );`
