### ISSUE TITLE
Subcategory available under 2 urls

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#26992]
We [received a thread in the support forums](https://wordpress.org/support/topic/2-x-urls-for-product-subcategories/) concerning an issue that I am able to replicate. The initial report is:

> I have noticed on my site that when a subcategory is created, it can be accessed from two URLs:
> 
> http://www.domain.com/parent-category/subcategory/
> http://www.domain.com/subcategory/
> 
> As neither URL specifies being canonical, this will be counted as duplicate content and have a negative effect on SEO if both URLs are indexed.
> 
> Is there any way around this?

I set up a fresh WooCommerce install, and did not update permalink structure and was able to replicate. I created a single product and added a parent category, then a subcategory under that parent. I was able to access the subcategory url, then remove the parent category from the url and it still displayed correctly. 

I am not sure if this is something we can fix on our end due to it may be WordPress core doing this. I found the below threads that had similar instances, but not exactly the same:

* https://github.com/woocommerce/woocommerce/issues/3007
* https://github.com/woocommerce/woocommerce/issues/10619

Clearer replication steps:
1. Fresh install of WordPress and WooCommerce
1. Create product
1. While creating product, create category
1. Create subcategory under that new category
1. View subcategory via its url
1. Edit url in browser to no longer have parent category
1. Subcategory page will display, making it a duplicate url with the same content

**Comment by ivatautomattic** [comment]
Hi @jessepearson ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using the steps provided. 

STR:

1. Install WordPress and WooCommerce plugin
2. Create a product -> create a category -> Create subcategory under that parent category
3. View subcategory ( via its URL under **WooCommerce -> Products -> Product categories**) 
4. Manually edit URL in the browser to delete the parent category (e.g. /product-category/parent-category/test/ **- >** /product-category/test/)
**Actual Result**: The link will route to the same subcategory page
![url](https://user-images.githubusercontent.com/70089943/95167442-87b76800-0764-11eb-827d-618169fa7f5a.png)


We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment]
@jessepearson Use your steps to reproduce using post categories instead of product categories. In my install it also works. Being accessible via multiple URLs is a "feature" of hierarchical taxonomies.

**Comment by jessepearson** [comment]
@rrennick Good call, I was thinking it was probably WordPress core. I am going to go ahead and close out this issue.

**Comment by akW-matt** [comment]
@jessepearson @ivatautomattic 
I just found out that this is still the case 4 years later!
Am I missing a setting in Wordpress/WooCommerce that should be turned off?
Thanks!

**Comment by jessepearson** [comment]
> Am I missing a setting in Wordpress/WooCommerce that should be turned off?

I don't believe that's the case, as @rrennick mentioned above, it's how WordPress core works and we're not able to change that in WooCommerce.
