### ISSUE TITLE
Show database name in System Status

### ISSUE THREAD

**Issue by ultrawebmarketing** [woocommerce/woocommerce#26995]
**Is your feature request related to a problem? Please describe.**
Not related to an issue more of just information readily displayed

**Describe the solution you'd like**
In the database section of the System Status page, can we please have the database name displayed? It would really help when managing multiple sites that use their own database.

**Describe alternatives you've considered**
Currently we have to look in the wp_config.php for this information.

**Additional context**
none, just a thank you 😁

**Comment by juliaamosova** [comment]
Hi @ultrawebmarketing,

Thank you for taking the time to share this idea, we really appreciate your help. Sounds like an interesting and useful addition.

**Comment by claudiosanches** [comment]
I'm not sure about this request, the database name is a information on WordPress, not something we can control on WooCommerce.

**Comment by claudiosanches** [comment]
I just confirmed, WordPress shows the "Database name" in the Site Heath, see: `wp-admin/site-health.php?tab=debug`

This is how it shows up for me:

![Screenshot from 2020-07-14 18-21-13](https://user-images.githubusercontent.com/1264099/87477638-d1c5fd00-c5fe-11ea-8d72-6feec8edf4f1.png)

I'm going to close since it's already part of WordPress core.
