### ISSUE TITLE
identify product in the order confirmation email adding photo

### ISSUE THREAD

**Issue by isagofe** [woocommerce/woocommerce#27025]
What I think needs to be improved is not a mistake per se.
It is a suggestion rather than a mistake.

When you receive a notification by email that an order has occurred on a website, woocomerce provides a detailed order note with quantity, product, price, delivery address ...
The point is that when you have a large inventory, or that order is prepared by someone who does not know all the products that are marketed on the web, the name of the item is not enough to identify it.

My proposal is that a photo of the products purchased by the customer appear in the order note next to the product name, in order to more quickly identify the product.

It is the first time that I use this platform, and I do not know if I am doing it in the right place.

Regards
Thank you

**Comment by juliaamosova** [comment]
Hi @isagofe,

Thanks for submitting your improvement idea! There is a way to add a product image to WooCommerce emails. It can be done by using the code snippet that you can find in the article below:

https://jilt.com/blog/add-product-images-or-skus-to-woocommerce-order-emails/

To add a snippet without modifying the actual files of WooCommerce, you can use a plugin called Code Snippets which will allow you to paste the snippet that will be run on your site:

https://wordpress.org/plugins/code-snippets/

Because there is a way to add a product image to emails, I am closing this issue. If I missed something, please comment back and we will take a look further.
