### ISSUE TITLE
On checkout, entering an invalid phone number incorrectly marks the input as valid

### ISSUE THREAD

**Issue by 4refael** [woocommerce/woocommerce#27021]
**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
On checkout, entering an invalid phone number will mark the phone as valid (green border) instead of as invalid (red border).

**Expected behavior**
If phone number is invalid it should get the styling of invalid field (red border)

**Actual behavior**
Invalid phone number gets styling of a valid field (green border)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add product to cart
2. Go to checkout
3. Fill an invalid phone number, for example insert: `a123`
4. See an error message appears indicating phone number is invalid, yet the phone input is marked as valid (green border)

**Screenshots**
![image](https://user-images.githubusercontent.com/2431842/87225711-a392b400-c397-11ea-9a07-c13893a82b82.png)
![image](https://user-images.githubusercontent.com/2431842/87225721-adb4b280-c397-11ea-86c7-949e30409827.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Can be seen also in [Storefront](https://themes.woocommerce.com/storefront/)

**Comment by juliaamosova** [comment]
Hi @4refael,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![phone_number](https://user-images.githubusercontent.com/19143190/87600645-0353cc80-c6c2-11ea-96be-c1f17c2d55a0.jpg)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by mfs-mindsize** [comment]
I take it this should be labeled "Has pull request", yes?
