### ISSUE TITLE
Coupon line discount & discount tax different than discount total & discount total tax using only one coupon

### ISSUE THREAD

**Issue by michael-attal** [woocommerce/woocommerce#27092]
Hello,

I'm using the Woocommerce REST API to create an order.
Everything is working fine, except when I add a coupon.
When the calculation made by WooCommerce is done, I got the good discount and discount tax from the coupon line item but not from the order discount total and discount tax.

The problem, is that this difference is then show inside the email sent and the Woocommerce backoffice.
The difference is the coupon line item discount (discount + discount tax) - the order discount total (discount total + discount tax).
You can see this with screenshots below.

![image](https://user-images.githubusercontent.com/29205422/88141112-3f6fbb80-cbf3-11ea-8874-0d1c8fa4be43.png)

![image](https://user-images.githubusercontent.com/29205422/88141150-4eef0480-cbf3-11ea-9cfa-80c18f2e268e.png)

**Comment by michael-attal** [comment]
Wordpress version is 5.4.2
Woocommerce version is 4.3.1 

Prices entered with tax : 
Yes, I will enter prices inclusive of tax

Calculate tax based on :
Shop base address

Shipping tax class :
Zero rate

Rounding	:
Rounding Round tax at subtotal level, instead of rounding per line

Additional tax classes
Reduced rate
Taux réduit
Taux zéro
TVA 10%
TVA 2,1%
TVA 5,5%
Zero rate

Display prices in the shop : 
Including tax

Display prices during cart and checkout : 
Including tax

Price display suffix : 
N/A

Display tax totals : 
Itemized

**Comment by michael-attal** [comment]
Wordpress version is 5.4.2
Woocommerce version is 4.3.1 

![image](https://user-images.githubusercontent.com/29205422/88141912-ddb05100-cbf4-11ea-8500-be1636bef862.png)

**Comment by michael-attal** [comment]
Wordpress version is 5.4.2
Woocommerce version is 4.3.1 

![image](https://user-images.githubusercontent.com/29205422/88141995-06384b00-cbf5-11ea-965c-d8cf5b2f7820.png)

**Comment by waleedsd93** [comment]
+1

**Comment by rrennick** [comment]
Hi @michael-attal ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
