### ISSUE TITLE
Woocommerce store Pre-order is automatically change to complete after payment completed

### ISSUE THREAD

**Issue by nsajeevan89** [woocommerce/woocommerce#27107]
Hi
I have set up a Woocommerce store and install the plugin "Preoders for WooCommerce" for preorders. But after installing this plugin. I received an order for preorder but the preorder automatically changes to Completed. I try to change the status as "Pre-Order" but the [WooCommerce Pre Orders] change the status again as completed. Please refer to the image.
![order](https://user-images.githubusercontent.com/68690006/88278723-7e3f6780-cd00-11ea-811e-c651f6b16914.JPG)

I don't want automatic completion, What is the solution for this?

**Comment by tammullen** [comment]
Hi @nsajeevan89 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
From your issue description the issue you are having seems to be caused by the 3rd party plugin `Preorders for WooCommerce`. 
​
Please contact the author of the plugin directly for further help.
