### ISSUE TITLE
Single product add-to-cart form ID

### ISSUE THREAD

**Issue by trollwinner** [woocommerce/woocommerce#27126]
Hello there!

I'd want to ask is it possible to add an ID for the single product add-to-cart form elements (these ones: "templates/single-product/add-to-cart/*") as default? Something like "single-product-add-to-cart-form-{$product_id}".

That might help to use extra inputs/buttons with the "form" attribute placed out of this form. And that might give much more possibilities for interesting customizations.

Thank you!

**Comment by claudiosanches** [comment]
Hello @trollwinner 

> I'd want to ask is it possible to add an ID for the single product add-to-cart form elements (these ones: "templates/single-product/add-to-cart/*") as default? Something like "single-product-add-to-cart-form-{$product_id}".

By default there's no template like that, but you can use the WooCommerce functions to register templates like that.
You can also override those templates on your theme or filter creating a plugin and change the fields based on the product ID.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the #developers channel. 

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
