### ISSUE TITLE
HTML showing for variations in ajax product search boxes

### ISSUE THREAD

**Issue by slightlyfaulty** [woocommerce/woocommerce#27154]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
`<span class="description">...</span>` shows in the label for selected variations in ajax product search boxes, e.g. on the coupon edit screen.

**Expected behavior**
HTML should not show in selected labels.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1) Go to WooCommerce > Coupons > Add coupon
2) Under Usage restrictions tab, search for and add any product _variation_ in the Products field.
3) The item added to the box will include text similar to `<span class="description"></span>` after the variation's title.

**Screenshots**
![screenshot-20200728-213500](https://user-images.githubusercontent.com/2036475/88713009-edf78d00-d11a-11ea-9bd0-830bf8055bdd.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress 5.4.2
- WooCommerce 4.3.1

**Comment by juliaamosova** [comment]
Hi @slightlyfaulty,

Thank you for submitting the issue. However, it is not clear how to properly reproduce it. 

Please provide us with exact steps on how to reproduce it so that we could take a look further. Thanks!

**Comment by slightlyfaulty** [comment]
Sorry I thought the description and screenshot were pretty clear. I've added reproduction steps to the issue description.

**Comment by tammullen** [comment]
Hi @slightlyfaulty 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2020-07-29 at 21 20 32](https://user-images.githubusercontent.com/24649833/88849304-9a9c4200-d1e1-11ea-89f2-e2d17160613c.png)

​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by slightlyfaulty** [comment]
It seems this also affects variation titles when adding products to an order:

![screenshot-20200802-152901](https://user-images.githubusercontent.com/2036475/89124160-27dae180-d4d5-11ea-9fdc-cf3a1e11644f.png)

**Comment by juliaamosova** [comment]
It looks like this bug was introduced in WC 4.2.1 (it works well in WC 4.2). I'd argue that this is a `low` priority since the issue is present when adding a variable product while creating a manual order. This is a pretty basic flow that most of the users go through often and it doesn't look good that there is an exposed html:

![html](https://user-images.githubusercontent.com/19143190/89688344-f052a780-d8cf-11ea-9b01-4fdf4f56f34d.jpg)

Changing priority to `high` and assigning 4.5 milestone to it so that we could fix it sooner than later.

**Comment by mintbird** [comment]
This problem not only occurred in woocommerce, but also affect to the third party plugins that use Select2 (such as ACF) in the same page.
I thought that the problem is from these lines of the commit.

https://github.com/woocommerce/woocommerce/blob/14a26aca2cde9c81ade02bdc6dd0a34e184a4202/assets/js/selectWoo/selectWoo.full.js#L1622

and

https://github.com/woocommerce/woocommerce/blob/14a26aca2cde9c81ade02bdc6dd0a34e184a4202/assets/js/selectWoo/selectWoo.full.js#L1756

Since the Select2 document was explained [the way to create a custom HTML markup and escaping](https://select2.org/selections#built-in-escaping), The `SingleSelection` and `MultipleSelection` (in the file selectWoo.full.js) shouldn't block this way.

The one of possible solution is revert to use `.append()` instead of `.text()`.

**Comment by IulianSz** [comment]
Hi there. The issue is still here, i just update to Woocommerce 5.2.0. The issue is is not present when adding products to an order, just when user want to grant access to an extra product. Please see the issue screenshot below.

![issue](https://user-images.githubusercontent.com/16861736/114696685-9db27080-9d25-11eb-9dc1-0f622191c082.jpg)

After that the product can't be activated for download and a error message appear:

![issue 2](https://user-images.githubusercontent.com/16861736/114697190-44970c80-9d26-11eb-90e1-b12bfce87489.jpg)

The messages are in romanian, because my site is in romanian, i hope that the issue will be understand in that conditions.

**Comment by tammullen** [comment]
Hi @IulianSz 

This is likely related to this issue https://github.com/woocommerce/woocommerce/issues/29679
