### ISSUE TITLE
When I have installed WordPress release candidate  and installed the woo-commerce too and I was trying to create a new variable product I am not  getting an option on the product edit page to  select product type  drop-down

### ISSUE THREAD

**Issue by abhayp-cedcoss** [woocommerce/woocommerce#27213]
When I have installed WordPress release candidate  and installed the woo-commerce too and I was trying to create a new variable product I am getting an option on the product edit page to  select product type  drop-down
![wordpres-rc-cersion](https://user-images.githubusercontent.com/25762790/89255506-86bc6a00-d63f-11ea-9c46-51c981f977d1.png)
![product type selction](https://user-images.githubusercontent.com/25762790/89255511-88862d80-d63f-11ea-98d8-0e46130f5d6f.png)

**Comment by juliaamosova** [comment]
Hi @abhayp-cedcoss,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27167. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

We are planning to release WooCommerce 4.3.2 before WordPress 5.5 is released in order to fix this issue.
