### ISSUE TITLE
Cyprus & North-Cyprus are not properly distinguished in WooCommerce

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27220]
Dear,

Please check this video where you can see that Cyprus & North-Cyprus are not distinguishable in WooCommerce shipping zones.

After you add Cyprus in the General selling countries, if you try to select it in the Shipping settings zone, you see two Cyprus line with no distinction in the name (like North/South Korea for instance).

https://sgevcen.tinytake.com/tt/NDUwNTM3MF8xNDI3NDgzOA (if video doesn't load, click on "Download" in top right)

I understand it can be a bit of politics here, but in practice I don't really care, I'm pragmatic and just want to make business in both sides...

Thanks

**Comment by juliaamosova** [comment]
Hi @gevcen,

Thanks for raising the issue. I can indeed see that we have `Cyprus` listed twice:

![Screen Shot 2020-08-04 at 10 24 43 AM](https://user-images.githubusercontent.com/19143190/89305539-c2a20000-d63c-11ea-9c50-a5cc9b91726d.png)

I doubt we have it in order to make a distinction between Cyprus and North Cyprus. Likely it is a bug and we need to keep just one `Cyprus`. 

In general, we adopted UNICODE CLDR standard for adding countries and regions in WooCommerce. With that said, for Cyprus we can add the following regions (as per [UNICODE CLDR](https://github.com/unicode-org/cldr/blob/release-37/common/subdivisions/en.xml#L969-L976)):

- Nicosia
- Limassol
- Larnaca
- Famagusta
- Paphos
- Kyrenia

If you'd like to add your own regions, you can use a snippet below:

https://docs.woocommerce.com/document/addmodify-states/

Or a plugin (note that I did not test it - proceed at your own risk. I am sure there are other plugins that can add the same functionality as well):

https://wordpress.org/plugins/woo-add-custom-states/

I am marking this thread as a bug to remove the double Cyprus entry.
