### ISSUE TITLE
High number of pages in WordPress can cause WooCommerce settings pages not to load

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#27233]
Sorry for not using the template, but I do not believe this fits well into it. 

The issue is that if there are a high number of pages (like 30k+) on a WordPress website, this can cause issues with accessing pages like WooCommerce > Settings > Advanced that include a drop down list of all pages. The customer in 3167881-zen asked if these fields would be able to be made into search fields, similar to how products are searchable when adding new items to an order in the admin. This would get around this for WooCommerce based pages.

The problem would remain in certain sections beyond WooCommerce, such as Settings > Reading and Appearance > Customize > Homepage Settings (it loads similar settings). These are settings pages controlled by WordPress directly.

**Comment by Helpguy01** [comment]
Hi,

Just to add to the above. I have managed to easily resolve this issue with other plugin providers. Instead of using a page dropdown menu the box was replaced with a "textbox" where the "Page ID" could be entered in. This completely resolved the issue for websites with many pages. The last remaning plugin to have this issue now is Woocommerce which is not compatible due to this issue for many pages.

**Comment by juliaamosova** [comment]
Hi @jessepearson,

Thanks for opening the issue and thanks @Helpguy01 for providing feedback. I can definitely see how it will be a good improvement for larger stores to add the search bar in places such as `WooCommerce > Settings > Advanced` and other places (where controlled by WooCommerce). I'll bring it up to the team to see if this is something that we can implement and provide with an update here as soon as I have it. In the meantime, I am adding an `enhancement` label to it.

**Comment by Helpguy01** [comment]
Thanks @juliaamosova , this will a great help. Just to give you an idea, if you do replicate the issue on a large enough scale (enough pages). It will literally crash the backend and corrupt the files of the Woocommerce core plugin after a simple action such as clicking the page list dropdown at WooCommerce > Settings > Advanced  making the Woo Core unusable even after deleting all other plugins and reverting to the default theme. I managed to replicate the issue after rebuilding my site from scratch and isolated the issue to this

**Comment by Helpguy01** [comment]
@juliaamosova - Any feedback on the above?

**Comment by juliaamosova** [comment]
Hi @Helpguy01,

Thanks for your patience while we were discussing this with the WooCommerce Core team. We have assigned this to be a `high` priority to implement in order to address this issue for larger stores such as the one you are working with. We are going to work on this issue as soon as possible. 

It won't make it to the upcoming WooCommerce 4.5 release in September but it is possible we can have it ready for WooCommerce 4.6 which is planned to be released in early October.

**Comment by Helpguy01** [comment]
Hi @juliaamosova this is excellent news! I unfortunately will have to hold out increasing my store size and will have to wait for the update. 

When details are final about which Woocommerce update the above mentioned issue will be released with, the sharing of this "exact date" will be much appreciated as this will greatly assist in our planning moving ahead.

Look forward to hearing from you.
