### ISSUE TITLE
Invalid refund amount when using coupons

### ISSUE THREAD

**Issue by filipecorrea** [woocommerce/woocommerce#27279]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I'm receiving an "invalid refund amount" error while trying to process a refund for an order paid using coupons (Smart Coupons).

**Expected behavior**
Coupon(s) credit should be restored and the order refund should be processed without errors.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. As a customer, purchase a product using coupon credit;
2. As a customer, request a refund;
3. As an admin, process the refund;
4. See error.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @filipecorrea,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the {name of the plugin} plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
