### ISSUE TITLE
Refund email is not fully translated even the translation exist in MO file.

### ISSUE THREAD

**Issue by 5um17** [woocommerce/woocommerce#27288]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A WPML customer reported this [issue](https://wpml.org/fr/forums/topic/split-problem-translate-string-text-order-fully-refunded/) and [here as well](https://wordpress.org/support/topic/order-fully-refunded-not-translate/) but as per my debug the issue should be fixed in WooCommerce.
*Order fully refunded.* string is not translated to site language in customer email.

**Expected behavior**
Since all of the strings from customer email is translated to site language then *Order fully refunded.* should be translated as well.

**Actual behavior**
The string added to the customer email in WP dashboard language.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Standard WC setup
2. Go to the Settings > General  and change the site language to other than English e.g. French
3. Go to Users > Your Profile and change the language to English.
4. Go to the shop and place an order
5. Go to the WooCommerce > Orders > edit the last order, from **status dropdown** select the status *Refunded* and update the order.
6. Check the email sent to the customer, *Order fully refunded.* string is not translated to site language i.e. French. If you keep the same language for back-end and front-end then there will be no issue.

**Additional information**
When customer refund email is sent the string is used from order meta with key name `_refund_reason`. And this meta created in backend where language is different here [`includes/wc-order-functions.php#L784`](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-order-functions.php#L784) therefore, it is never translated to site language.

**Screenshots**
Customer email 
![email](https://i.ibb.co/wQZQMWz/11-08-2020-202936.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @5um17,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

With site language set to French and admin user language set to French, the refund order email has no issues:

![french](https://user-images.githubusercontent.com/19143190/90072396-620e6500-dcc5-11ea-9110-13e2f683f7c6.jpg)

With site language set to French and admin user language set to English, the refund order email contains `Order fully refunded` string in English while the rest of the email is in French:

![english](https://user-images.githubusercontent.com/19143190/90072436-66d31900-dcc5-11ea-940d-5bf0c1fd4f22.jpg)

It seems that the issue was reported a few times and something that users can encounter often which is why I am giving this a `high` priority to fix.
