### ISSUE TITLE
Refund button not working since updating Woo.

### ISSUE THREAD

**Issue by rajsidhux** [woocommerce/woocommerce#27321]
I updated Wordpress and Woccomerce over last few days.

I tried to refund an order today (13/08/2020) and the button clicks but nothing happens.

Is this happening to anyone else?

Is there a fix being worked on?

**Comment by tammullen** [comment]
Hi @rajsidhux 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by peterfabian** [comment]
Hi @rajsidhux ,

Can you please check your browser console if you see any errors in there? WP 5.5 removed a javascript file called jQuery migrate that some of your plugins might have relied on, so until they update, you might want to use this plugin to include the javascript files in the meantime: https://wordpress.org/plugins/enable-jquery-migrate-helper/.

**Comment by rajsidhux** [comment]
@peterfabian Thanks mate. Downloaded the plugin and it's fixed the issue.

Now how log do I need to keep that plugin installed? 
Or will I need it installed from now on?

Thanks again.

**Comment by peterfabian** [comment]
@rajsidhux Thanks for reporting back. 

Ideally, you need to identify which plugin is the culprit (by disabling them one by one and checking when it starts working again). After the plugin you identified gets updated, you can remove the plugin I linked.
