### ISSUE TITLE
White space character

### ISSUE THREAD

**Issue by mikeecho2** [woocommerce/woocommerce#27360]
![Image1](https://user-images.githubusercontent.com/36819653/90433471-28c26480-e0cc-11ea-93a9-3900396f78e6.jpg)
![Image2](https://user-images.githubusercontent.com/36819653/90433474-29f39180-e0cc-11ea-9cd0-7fa86e017091.jpg)

There is an extra space in 
/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.js
/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.min.js
which is causing a white space character.
I believe it should not be there.

See images showing the location of the space
http://24web.co.za/error/Image1.jpg
http://24web.co.za/error/Image2.jpg

**Comment by tammullen** [comment]
Hi @mikeecho2 ,

Thank you for taking the time to report this, we really appreciate your help. 

I can see the space here https://github.com/woocommerce/woocommerce/blob/888a5c40cdf9b57fc8129539415726369774bf2a/assets/js/frontend/add-to-cart.js#L176

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by mikeecho2** [comment]
100%

Tam Mullen wrote on 20/08/2020 12:11:
