### ISSUE TITLE
woocommerce-rest-api without Author !!

### ISSUE THREAD

**Issue by ahmed-ho** [woocommerce/woocommerce#27368]
hello
i am looking for Author of product when i create new product can i find the way to put the Author
Thanks

**Comment by claudiosanches** [comment]
This is done intentionally, we also hide the author meta box in the Product screen, and in our CRUD we don't fetch any information like that, we only set the current user, so the author will be the user that is creating the product using the REST API.

I'm closing this issue because this isn't something that we plan to include in the REST API, since we don't even support it in the WP interface.
