### ISSUE TITLE
Honor "rest_pre_insert_{$taxonomy}" filter

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#27373]
In the WordPress REST API, the terms controller calls the method `prepare_item_for_database()` before inserting or updating a term in the database. One important feature of this method is that it applies the filter `rest_pre_insert_{$taxonomy}` allowing 3rd party plugins to modify the data before they are inserted in the database: https://github.com/WordPress/WordPress/blob/5.3.2/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php#L703-L713.

I propose to honor this filter, or to add a filter with a different name but doing the same.

**Comment by claudiosanches** [comment]
There's already a filter inspired by WP core `rest_pre_insert_{$taxonomy}`, we have this filter since the first release of our REST API: https://github.com/woocommerce/woocommerce/blob/49a9ab4437b1acb95ff03cd894b5be2849d0062c/includes/rest-api/Controllers/Version3/class-wc-rest-terms-controller.php#L431

There's an extra parameter that indicates if it's inserting or updating.

cc @vedanshujain

**Comment by Chouby** [comment]
@claudiosanches Sorry but I believe that it's not the same. Your action  `woocommerce_rest_insert_{$taxonomy}` is indeed inspiredd by the similar WordPress action `rest_insert_{$this->taxonomy}` which is fired after the term is inserted in DB. But I found nothing that could act as the filter `rest_pre_insert_{$taxonomy}` that I requested. It's a filter and not an action and it is applied before the term is inserted in DB and not after.
