### ISSUE TITLE
wc_trigger_stock_change_notifications is much slower than it needs to be, due to unnecessary call to wc_get_product

### ISSUE THREAD

**Issue by lukahund** [woocommerce/woocommerce#27403]
**Describe the bug**
"wc_trigger_stock_change_notifications" in "/includes/wc-stock-functions.php" uses wc_get_product multiple times to fetch a product from $change['product']->get_id().
The problem here is that $change['product'] already refers to a product which means the call to wc_get_product is unnecessary and can add significant time to the checkout with large orders. This can for example be seen on line 233 of "/includes/wc-stock-functions.php"

**Changes needed/considered**
wc_get_product($change['product']->get_id()) should be replaced with simply $change['product']

Please correct me if I'm missing something here, and there is a good reason to call wc_get_product, thanks :)

**Comment by peterfabian** [comment]
I _think_ it might have been to load the product from the database again to get the very latest updates of the stock level, but maybe I'm wrong. Looking at the [PR that introduced it](https://github.com/woocommerce/woocommerce/pull/20458), and the [specific commit](https://github.com/woocommerce/woocommerce/commit/70c9cff608761fcd48b57f709059e00b1ffeee38), I'm unsure about the reasoning. When looking at it now, it seems to me that it's unnecessary to fetch the product 3 times. cc @vedanshujain in case I might be missing something.

**Comment by vedanshujain** [comment]
Repeated `wc_get_product` is generally inexpensive because it reads from cache instead of querying DB (even with sites having no extra cache plugins, WP provides a request level in-memory cache by default).  And `do_action` can, in fact, change product attributes so we need the new product object every time. 

I am closing the issue, but let me know if I have missed something. @lukahund is this causing an issue for you? I would think every wc_get_product will not raise a DB call.

**Comment by lukahund** [comment]
I'm seeing wc_trigger_stock_change_notifications adding about 3-6 seconds of time to the checkout on an order with 32 products
