### ISSUE TITLE
Bug in order notes ajax

### ISSUE THREAD

**Issue by akshuvo** [woocommerce/woocommerce#27413]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I add a first order note, the text "There are no notes yet." still showing:
![image](https://user-images.githubusercontent.com/16398283/90668456-f3f01200-e271-11ea-838b-98f62e5aefe9.png)

**Expected behavior**
The text "There are no notes yet." should hide/remove after adding any note.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to `\assets\js\admin\meta-boxes-order.js`
2. Scroll down to `$( 'ul.order_notes' ).prepend( response );`
3. There you have to do something to fix the issue

**Screenshots**
![image](https://user-images.githubusercontent.com/16398283/90667945-1f263180-e271-11ea-8dee-d51eb4abdee7.png)

**Comment by claudiosanches** [comment]
Hi @akshuvo,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

Please feel free to send a Pull Request with a fix if you like to. Any help will be highly appreciated.
