### ISSUE TITLE
Local Shipping and Free Shipping need to show

### ISSUE THREAD

**Issue by jacsify** [woocommerce/woocommerce#27422]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement, or feature request (Please use the link above if it is).

**Issue Description:**

I have free shipping set for anything over R500 (South African Rand), however, when customers are in a certain region I would the Free Shipping as well as Local Pickup to show up. 

![Screenshot 2020-08-20 at 11 42 36](https://user-images.githubusercontent.com/26250069/90754733-8e843b80-e2da-11ea-9643-1947ff25ff64.png)
![Screenshot 2020-08-20 at 11 43 16](https://user-images.githubusercontent.com/26250069/90754742-90e69580-e2da-11ea-8bd0-06f4753dccd6.png)
![Screenshot 2020-08-20 at 11 43 33](https://user-images.githubusercontent.com/26250069/90754749-92b05900-e2da-11ea-8b4b-8df2fa3a2ea9.png)

Please could someone assist? I have tried code snippets and various plugins, but nothing works. 

Thanks!

**Comment by juliaamosova** [comment]
Hi @jacsify,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
