### ISSUE TITLE
Relevanssi search problems because of adjust_posts_count() 

### ISSUE THREAD

**Issue by msaari** [woocommerce/woocommerce#27420]
With WC 4.4.0, Relevanssi searches broke down. With Relevanssi enabled, all searches that would find more than one result fail and show no results (single-result searches still redirect to the correct post).

I tracked down the issue to the new `adjust_posts_count()` function. What happens is this:

In the `archive-product.php` template, WC uses `wc_get_loop_prop( 'total' )` to see if there are posts to display. This gets the number of posts from the global `$wp_query`, which is where Relevanssi stores the number of posts it has found. In 4.3, this worked without problems. In 4.4, `wc_get_loop_prop( 'total' )` is always 0 when Relevanssi is enabled and thus no results are shown.

So why is this value 0? Relevanssi disables the default WordPress search query by modifying the SQL query with the `posts_request` filter hook, in order to avoid wasting resources: the results of the default query are not used, so best make it as quick as possible.

However, now with 4.4, the `adjust_posts_count()` function comes into play. It fires from the `found_posts` filter hook in WP_Query's `set_found_posts()` – and this runs long before `the_posts`, where Relevanssi would come in and replace the empty search results with the correct search result set.

`adjust_posts_count()` fires `wc_set_loop_product_visibility()`, which fires `wc_set_loop_prop()`, which fires `wc_setup_loop()` – and now the WC Loop is set up using the empty WP_Query instead of the WP_Query that contains the Relevanssi results.

This problem can be fixed by reseting the loop on the `woocommerce_before_shop_loop` action hook (`add_action( 'woocommerce_before_shop_loop', 'wc_reset_loop' );`, I'll have Relevanssi do this starting from the next version released), so I guess the problem isn't that bad, but I still thought this is worth mentioning so you're aware of the side effects of these changes.

**Comment by peterfabian** [comment]
Thanks for letting us know, @msaari. I think this is an unfortunate side effect of changing how the default search and querying work. As we wanted to add the possibility of filtering products (i.e. posts) based on a specific property of its child (stock status and attribute), we had to change the default filtering. If you have a proposal on how we can change things to make them fit better with WP core search and other search plugins like Relevanssi, we're happy to discuss and even happier to review a PR :)

Also, in ideal circumstances, it would be great if these concerns were raised a bit earlier than after the release of a feature. Please join us in the pre-release testing and check your plugins with our beta and release candidate versions and send us feedback so that we can adjust the code before it's released to the public and we have to risk breaking backward compatibility. 

ccing @Konamiman and @vedanshujain who worked on these changes recently.

**Comment by msaari** [comment]
Yes, ideal circumstances would be ideal circumstances, but there are over 57,000 plugins in the plugin repository, so in realistic circumstances these kinds of compatibility problems come up when end users start to complain.

I have enough in my hands testing Relevanssi to make sure it works by itself and supporting Relevanssi users and customers. In this case, I don't have a faintest clue what the new changes are even supposed to be doing, all I know is they're interfering with Relevanssi, and taking hours to understand complicated WooCommerce architecture unfortunately isn't an option, so no pull requests from me.

Relevanssi will simply run `wc_reset_loop()` as that seems to fix the problem. 

And I agree this is not really a bug, but I still thought reporting this issue might be useful. At least now you know there are circumstances where the `$wp_query` you see when doing `adjust_posts_count()` may not contain the final query results. Is that something you should consider in the code? I really have no idea.

**Comment by vedanshujain** [comment]
`wc_reset_loop` does make sense, only thing is to make sure that you only do it if its a Relevanssi request (which I guess you would have already done). I will look into to see if we can hook the adjust post count later in the process.

**Comment by peterfabian** [comment]
Thanks @msaari for taking the time to report this. It's valuable to know how we can improve and better align ourselves with other plugins. I understand it's not possible to test with every plugin the repository, I was just thinking on how to potentially improve things going fwd, that's why I mentioned the possibility to test with prerelease WC versions, but it's tricky for a general-purpose plugin such as yours and I understand that your time might be better spent elsewhere.

**Comment by msaari** [comment]
WooCommerce is definitely one of the category A plugins where compatibility with Relevanssi is very important for me, but getting automated testing working with just Relevanssi alone has been a task difficult enough that I haven't really even considered adding third parties to the mix. It would be really helpful to have key plugins like WooCommerce, Polylang and ACF included in the testing, but it gets very complicated very quick.
