### ISSUE TITLE
No access to the woocommerce page from the admin console

### ISSUE THREAD

**Issue by abdelhakim-atmani** [woocommerce/woocommerce#27476]
After updating the plugin to Version 4.4.1.

When logged in as an admin user and I click on the woocommerce link in the left menu it displays the source code.

**Comment by tammullen** [comment]
Hi @abdelhakim-atmani

Sorry to hear this, can you share any screenshots of this to help show what is happening? Are you still able to access WooCommerce and it's pages?

We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate issues. 
Without this report we won't be able to fully evaluate this issue.

If you are able to still access it the System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it into this issue.

**Comment by abdelhakim-atmani** [comment]
I still have the problem even if I have disabled and renabled the plugin

![DB82DB5F-0DD5-4D4F-9C98-2A0B543FD8F0](https://user-images.githubusercontent.com/15782414/91193938-a18a7780-e6ef-11ea-9d12-b7a2aa00d116.png)

**Comment by Eduardogpe12** [comment]
I have exactly the same problem
![error](https://user-images.githubusercontent.com/70217333/91194290-a2a2b100-e6bd-11ea-929a-0b71ad04a691.PNG)

**Comment by tammullen** [comment]
Thanks @abdelhakim-atmani and @eduardogpe12 for the screenshots.

Can you try testing your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Eduardogpe12** [comment]
Thank you it seems to be elementor version 3.0 is genereting that isue.

**Comment by tammullen** [comment]
Thanks @Eduardogpe12 for that information. Please contact the author of that plugin directly for further help.

**Comment by abdelhakim-atmani** [comment]
Issue fixed. Just updating some plugins and theme.
