### ISSUE TITLE
HTML in 'Title' field of Payment method displays as text on /checkout/order-received/

### ISSUE THREAD

**Issue by jjbbrr** [woocommerce/woocommerce#27518]
**Describe the bug**
- 'Title' field for a payment method in Woocommerce settings accepts HTML. (e.g. Settings > Payments > Paypal > Title)
- On the Checkout page /checkout/ this HTML displays correctly as 'Payment method'.
- In the Order notification email this HTML displays correctly as 'Payment method'.
- On /checkout/order-received/ this field is displayed twice - the first one renders the HTML but the second one does not. See screenshot. 

**Expected behavior**
HTML should be rendered as HTML, not text. 

**Actual behavior**
HTML is display as text - see screenshot.

![Screenshot](https://user-images.githubusercontent.com/3255598/91635363-e6fcbc80-e9ef-11ea-99bd-57aa709a7937.png)

**WordPress Environment**
Wordpress 5.5
Woocommerce 4.4.1

**Comment by jonathansadowski** [comment]
Hi @jjbbrr,
​
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
I added the "Cash on Delivery" payment method to my test shop. In WooCommerce > Settings > Payments > Cash on Delivery, I updated the title of the payment method to `Cash on <strong>Delivery</strong>`. On the cart page, the title displays appropriately as "Cash on **Delivery**", but on the order details page after completing checkout, the HTML is displayed:

![image](https://user-images.githubusercontent.com/363749/96926800-ae231600-147b-11eb-9799-71974e5dafd3.png)

​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by swatipawarGS** [comment]
Hi @jjbbrr ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version. 

Please find below screenshots  for reference :

![#27518(Cash)](https://user-images.githubusercontent.com/94531721/145950188-7aee9230-3778-4061-baa9-56867d7e5602.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.
