### ISSUE TITLE
Wrongly spelled country's region Bizkaia -> Biscay

### ISSUE THREAD

**Issue by Renzik** [woocommerce/woocommerce#27538]
A client brought to my attention that the region Biscay/Vizcaya of Spain is wrongly spelled Bizkaia.

It is currently spelled Bizkaia, but should be Biscay.

Thanks!

**Comment by tammullen** [comment]
Hi @Renzik 

Thank you for taking the time to report this bug, we really appreciate your help. 

I can see we have it called `Bizkaia` here
https://github.com/woocommerce/woocommerce/blob/5f1d2a8a2cf46ca64b22fe11cd9c8750e84525ad/i18n/states.php#L396

We adopted UNICODE CLDR standard for adding countries and regions in WooCommerce.  
In CLDR it is called `Biscay`
https://github.com/unicode-org/cldr/blob/6a0389a7b2ad5b0f4863490bb27a1ce320cc85a6/common/subdivisions/en.xml#L1315
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
