### ISSUE TITLE
Cart and Login Problem Mobile Android: 4.4.2 Chrome: 81.0.4044.138 

### ISSUE THREAD

**Issue by gevv** [woocommerce/woocommerce#27541]
Wordpress 5.5 Woocommerce  4.4.1  Mobile Android: 4.4.2 Chrome: 81.0.4044.138 Cart and Login Problem 
I have the same problem on my own site and on woocommerce demo site
Please watch the video

https://streamable.com/kfsk8b

https://streamable.com/zdozhb

**Comment by ivatautomattic** [comment]
Hi @gevv,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, maybe closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem. **You have provided the video so you can skip this part.**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by gevv** [comment]
Hi,

watch the video ?

8 Eki 2020 Per 10:08 tarihinde ivatautomattic <notifications@github.com>
şunu yazdı:

**Comment by rrennick** [comment]
Closing for lack of feedback.
