### ISSUE TITLE
Annoying loading circle on top of every single page in backend

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27540]
Dear,

Since you added the new admin bar in WooCommerce, there is constantly this circle loading bar that appears on top of the page. This is so annoying, because since then the page loads and then you try to hit on a link in the page but in the meantime the page has scrolled because the circle disappeared as the page got fully loaded.

Get rid of this crap loading circle, we don't need this because the Browser already has a loading circle
https://sgevcen.tinytake.com/tt/NDU4NjMwMF8xNDUzODA4MA

Thanks

**Comment by ivatautomattic** [comment]
Hi @gevcen ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, maybe closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem. **You already provide the video so you can skip this part.**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rrennick** [comment]
Closing for lack of feedback.
