### ISSUE TITLE
& not working on coupon fields for guest users

### ISSUE THREAD

**Issue by gayathri-storepro** [woocommerce/woocommerce#27601]
Special characters like "&" not working with coupon codes for guest users. For example, guest users cannot use coupons a@a. 

It seems that the & symbol is breaking coupons. On Chrome/Firefox on Windows, when a coupon has the ampersand (&), it breaks the coupon and throws the message, "This coupon does not exist!" Replace the & with something "n" and it works; no problem.

Have not tested other special characters, but "!" works just fine.

Screenshot - [https://prnt.sc/uctw3j](https://prnt.sc/uctw3j)

Woocommerce  : 4.3.1
Wordpress         : 5.5.1

**Comment by juliaamosova** [comment]
Hi @gayathri-storepro,

Thanks for reporting the issue. However, it seems to be a duplicate of https://github.com/woocommerce/woocommerce/issues/23655 which we fixed via https://github.com/woocommerce/woocommerce/pull/27140 and released yesterday in WooCommerce 4.5. 

I see that you are using WooCommerce 4.3.1. Can you please update to WooCommerce 4.5, test, and let us know if the issue is fixed for you?

**Comment by gayathri-storepro** [comment]
Thanks, @juliaamosova ,  it works!
