### ISSUE TITLE
Product Add-ons Extension is not passing along all additions to the cost to PayPal

### ISSUE THREAD

**Issue by grrmarketing** [woocommerce/woocommerce#27647]
Hello, when a customer purchases a bookable product and a marks add-ons, which increase the cost of the product, only the last add-on checked is added to the price when passed to PayPal.

For example, if purchasing: https://graphicsremarkable.com/product/real-estate-photography/

And you add-on some additional items, the total price displaying on the website is not the same price that is passed to PayPal when you click the gold PayPal button.

**Comment by juliaamosova** [comment]
Hi @grrmarketing,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the Product Add-Ons plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
