### ISSUE TITLE
Phone number required on order

### ISSUE THREAD

**Issue by TheWebsiter1** [woocommerce/woocommerce#27652]
I made phone number as “require” but still I get a lot of orders without the customer phone number.

**Comment by juliaamosova** [comment]
Hi @TheWebsiter1,

Thanks for raising the issue. However, it is not clear how do you make the phone number to be required. It is required by default in WooCommerce. Unless you custom coded the checkout page in some way. 

Can you please provide steps to reproduce the issue and also specify what theme are you using?

**Comment by GlennMartin1** [comment]
I can't speak for @TheWebsiter1 , but WooCommerce Powerpack has a Customizer option for what checkout fields are required.

**Comment by juliaamosova** [comment]
Thanks @TheWebsiter1. 

Yes, WooCommerce Core has an option to set Phone Number as a required field as well - I missed the fact that we have this option:

![phone)number](https://user-images.githubusercontent.com/19143190/93822641-82b7cc00-fc2e-11ea-9f3b-8294d19b8cc2.jpg)

However, I can't reproduce the issue on my end. If I set the phone number to be required, customers can't checkout without entering it. 

It will be great if @TheWebsiter1 could test site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

In any case, the issue had no feedback for the last 10 days so I am closing it due to inactivity. 

Please feel free to comment on it in case we missed something. We’d be happy to take another look.
