### ISSUE TITLE
"Invalid Payment Method" for COD gateway

### ISSUE THREAD

**Issue by ouija** [woocommerce/woocommerce#27682]
**Prerequisites**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Latest version of WooCommerce v4.5.2 and COD Payment Method will throw an _"Invalid Payment Method"_ error if/when **billing_postcode** field is unset; was not occuring with WooCommerce v4.4.1

**Expected behavior**
Allow COD Payment method to work without needing billing_postcode field to be set

**Actual behavior**
Having billing_postcode unset will cause an "Invalid payment method" validation error on checkout when selecting the COD payment method.

**Steps to reproduce the bug**
1. Enabled COD payment method in WooCommerce
2.  Add the following code to theme's functions.php file to disable billing_postcode field:
```
function custom_woocommerce_checkout_fields( $checkout_fields ) {
	unset($checkout_fields['billing'][ 'billing_postcode' ]);
}
add_filter( 'woocommerce_checkout_fields', 'custom_woocommerce_checkout_fields', 2000 );
```
3.  Try to checkout any product using COD payment method and there will be an "Invalid payment method" validation error.

**Isolating the problem**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @ouija,

Thank you for submitting the issue. However, I can’t reproduce it - The `Cash on Delivery` method is working as expected on my end. See the gif below (from my test site using the COD method):

![](http://g.recordit.co/39g9KidEYK.gif)

Please confirm if you performed theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by ouija** [comment]
I believe I have discovered the cause of the issue -- My client has disabled/unset the default **billing_postcode** filed at Checkout, and not having this set will throw an _"Invalid payment method"_ validation error for the COD payment method (but not other methods, such as the online CC processor)

I'm looking into re-enabling the billing_postcode field for now as a solution to this, although the client would still prefer to leave this field disabeld/unset if possible.  _(They actually use the COD as a method for "pickup", not delivery, so the customers postal code isn't necessary)_

Thank you.

**Comment by juliaamosova** [comment]
Hi @ouija,

Thank you for your follow-up on this issue! Our apologies for the delayed response. 

It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by RaghebAlashqar** [comment]
I fixed the issue by 
1- adding custom css class to the theme to hide the postal code input 
https://www.wpbeginner.com/plugins/how-to-easily-add-custom-css-to-your-wordpress-site/
2- installing this plugin "checkout field editor woocommerce" from "themehigh" to set the custom css class to the postal code input &&&& SETTING a random default value for the postal code input 

That fixed the issue :)

**Comment by rrennick** [comment]
@ouija I tested this with WooCommerce 5.8.0 and was able to check out with COD and the snippet in your description. Can you test this and let us know whether it is still an issue for you?

<img width="958" alt="Screen Shot 2021-10-18 at 1 41 39 PM" src="https://user-images.githubusercontent.com/343847/137773414-aef9a30e-6df8-4b8f-a078-d02f0fb52bc9.png">
