### ISSUE TITLE
MyAccount Page: Explicit Consent for DataProtection Page

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce#27697]
**Is your feature request related to a problem? Please describe.**
On the my account pageby default it looks like this:
![my-account-default-view](https://user-images.githubusercontent.com/6242098/93463590-401d8900-f8e8-11ea-9e09-38acfa61406f.png)

You can login or create a user. When somebody creates a user by default woocommerce informs him about the privacy policy, shares a link so the user knows it. However based on the lastest EU regulations we have more and more sites where we need to go over from just informing to explicit consent. this is not by default possible with woocommerce right now.

**Describe the solution you'd like**
We should automatically force the user to give explicit consent to our privacy policy.
This could look like my quick example below.
![my-account_new](https://user-images.githubusercontent.com/6242098/93463938-bf12c180-f8e8-11ea-9d8e-15041d259c8f.png)

**Describe alternatives you've considered**
Currently site owners add it manually over a documentation like: https://www.businessbloomer.com/woocommerce-add-privacy-policy-consent-my-account-registration/
However this should be handeled by woocommerce in the core plugin in my opinion.

**Comment by DavidAnderson684** [comment]
When I was researching GDPR in 2018, I read several resources advising that it is a fallacy to interpret the concept of "consent" as boiling down to "add a checkbox that has to be ticked".
If someone fills in a form that is clearly labelled as being for purpose X, then they have also consented to X by filling it in. The implication was that adding an extra "Do you actually provide consent for the whole purpose of this form?" is quite literally legalistic box-ticking, and makes no difference (but adds friction). "Explicit" does not mean "extra checkbox". If someone takes action to create an account, then they've consented to their data being used for the thing the account is described as being for, extra checkbox or not.  Obviously you're of a different opinion. Is there some specific legal opinion or extra information driving that opinion?

**Comment by carike-codes** [comment]
:wave:

"Silence, pre-ticked boxes or inactivity should not therefore constitute consent."
Just displaying a link to the privacy policy is the same, in substance, as having a pre-checked checkbox.

**Comment by masteradhoc** [comment]
@DavidAnderson684 thanks for the comment, appreciate it.

**Law**
Carike is right and pointed out, that a simple text is not enough. Her statement is from the official recital which can be found here: https://gdpr.eu/Recital-32-Conditions-for-consent/

**Checkout**
If the Terms and Conditions Page is set at WooCommerce -> Settings -> Advanced right now on the checkout a NOT prefilled checkbox appears that needs to be manually checked - which is correct.

=> the same should apply also on the my account page when creating an account.

**Comment by DavidAnderson684** [comment]
You're missing my point - someone who fills in a form with a clearly specified purpose accompanied by an explanation of what the form is for *has already taken explicit action*. There is no "consent by omission" in that situation.

So:
https://www.linkedin.com/pulse/why-gdpr-doesnt-require-checkboxes-peter-austin
https://dma.org.uk/article/gdpr-in-practice-tick-box-consent-forms
https://www.mailerlite.com/blog/how-to-create-opt-in-forms-that-still-work-under-gdpr#when-use-checkboxes

**Comment by carike-codes** [comment]
The English translation of the text accompanying the privacy link in the screenshot seems to be the following:
"Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy."
That does not make it clear that the creation of an account is **conditional** upon the acceptance of a contractual term (acceptance of the privacy policy).
Other fields are marked as required fields and registration cannot proceed without them. Yet, you can proceed without reading a sentence that is phrased like it is providing additional information.
Think of it as this - if you are signing a contract, you are often required to initial the most important terms (non-standard, alterable from either law or industry standards to indicate that you have been made aware of them). Here, you are requiring people to "initial" other fields, but not acceptance of the privacy policy.
If you wanted to change the text of the button, it would be a different matter.
"Register" !== "I agree"

Furthermore, there are considerations like the font size / visibility.

Additionally, that LinkedIn article is an opinion piece from December 2017.
The DMA article is from 2016.
Both of those are from before the the CJEU built on the body of precedent that is now available.

The Mailerlite article is from 2020. I have not evaluated the author's history, nor have they stated authority for their recommendations (I mean that they have not referred to specific subsections or judgments), but I'll take it as a given that what they are saying is correct.
Unless you can guarantee that the installation does not use someone's data for anything other than functional purposes, you should not provide a registration mechanism as part of your code without the ability to opt out of other categories (broadly: preferences, anonymous statistics, statistics and marketing), or at least pointing to a place where this may be done.
The fact that you cannot opt-out / must opt in to these additional categories in order to register an account is what makes the consent implied, rather than explicit.

**Comment by peterfabian** [comment]
Thanks for starting the discussion. Being in the clear from GDPR and CCPA point of view is very important.
We're consulting this with our legal department and will let you know the outcome soon.

**Comment by peterfabian** [comment]
We got an answer back from our legal team:

> For the types of data collected by woocommerce store owners about their customers when those customers create an account you don’t need to get consent because there is a contractual necessity to this data collection. I.e. the store owners are collecting data they have to get in order to fulfill their customer’s request. The customer is asking the store owner to create them an account; the store owner cannot fulfill this request without collecting an email address and a password.

Additionally, the link above also mentions:

>  Consent should be given by a clear affirmative act establishing an indication of the subject’s agreement to the processing of personal data This could include ... conduct which clearly indicates in this context the data subject’s acceptance of the proposed processing of his or her personal data.

Not being a lawyer myself, but if I'm reading this right, a person who is creating an account on an eshop clearly indicates to shop owner that they can use their data for their records, sending them the goods, etc.

In light of this, I'm inclined to not change this unless many folks would strongly feel about adding it.

Please express your opinion if you feel like this is necessary in the comments below.

**Comment by DavidAnderson684** [comment]
This analysis agrees with my understanding of it and I think it should be left as it is.

**Comment by carike-codes** [comment]
That assumes that every store owner **only** plans to use the e-mail address for fulfilling the order. That is simply not true.

**Comment by masteradhoc** [comment]
@peterfabian quick question here: why do we ask for explicit consent then when you take an order? There is the same data behind.

**Comment by carike-codes** [comment]
Thought I'd give a little more comprehensive explanation, if someone who is interested in the topic stumbles on this thread :-)

In my view, this shows inadequate attention to architecture, as well as a lack of understanding regarding the value proposition of an e-commerce solution and expectation management.

In brick-and-mortar terms, if you're building near a flood-line, you're going to have to (whether or not this is required by authorities, although it usually is) take certain precautions. What the implementation of those precautions look like, are often flexible. It may involve strengthening a bank of sorts. It may involve stronger foundations. It may involve elevating the structure in some way. It may involve a combination of these things.

While WooCommerce is an e-commerce solution in general, this specific (sub-)component that we are talking about now, is a **registration / login** functionality.
That is to say, here WooCommerce isn't just designing for itself, it's designing for whichever use the website owner / admin puts their site to.
The prudent assumption (and sane default) is to assume that there is a high likelihood that the store is using data for purposes other than strictly fulfilling the order (whether that is tracking usage habits for re-targeting, or even selling the info).

**Comment by michi-dev** [comment]
I really agree with @masteradhoc. Thank you @masteradhoc for writing about this. I also had the same thoughts...

**Comment by barryhughes** [comment]
We seem to be at a bit of an impasse, here. Some thoughts after reading back:

- It doesn't seem like the proposed change is required, or even desired by all.
- It would be possible to implement on a site-by-site basis, without a template override, by taking advantage of hooks such as `woocommerce_register_form`.
- A good point was made about sites having purposes beyond ecommerce ("we're not just designing for ourselves"), however I think we can say that this is generally true of many WordPress sites, not just sites that happen to have WooCommerce installed.

With those things in mind, I'm closing this issue: when this functionality is needed, it can be handled as a customization.
