### ISSUE TITLE
REST API endpoint for Cart management

### ISSUE THREAD

**Issue by Ndroid042** [woocommerce/woocommerce#27724]
We need a rest api for management of cart; for guest sessions and user account.

**Comment by seb86** [comment]
Use [CoCart](https://cocart.xyz/) @Ndroid042

**Comment by claudiosanches** [comment]
Hello @Ndroid042, thanks for opening this report.
Currently there's an cart endpoint getting created for WooCommerce Product Blocks, and also it's possible for your manage cart sessions on your app and then just create regular orders on WooCommerce using the REST API, it should be faster than relying on servers response for all cart interactions.

I'm closing this issue for now, since it's something that is under development and there's also alternatives like @seb86 mentioned.
Thanks!
