### ISSUE TITLE
'No downloads available yet.' notice looks broken in mobile some locales

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce#27745]
## To Reproduce
1. Change your site language to Spanish, for example.
2. Go to `my-account` and log in.
3. Go to _Descargas_ (_Downloads_) and make your viewport narrow simulating a mobile phone.
4. If you don't have any download, see the notice. 

## Screenshots
English:
![imatge](https://user-images.githubusercontent.com/3616980/80075558-27809100-854b-11ea-82c9-2600e5c3526b.png)

Spanish:
![imatge](https://user-images.githubusercontent.com/3616980/80075600-3e26e800-854b-11ea-99f1-3233c6ccb805.png)

## Expected behavior
I think the button (_Browse Products_) should always be rendered below the text on mobile.

**Comment by juliaamosova** [comment]
Hi @Aljullu @haszari @nielslange, thanks for raising the issue and for the testing done on it. 

I am marking this as a `low` priority as the issue seems specific to the `Downloads` section only on the mobile device. However, please feel free to argue that it should have a `high` priority to be fixed.

**Comment by nielslange** [comment]
> Sounds good, thanks @nielslange. Moving this issue to the WooCommerce Core repo.

Thanks for doing so, @juliaamosova. 🙌

> I am marking this as a `low` priority as the issue seems specific to the `Downloads` section only on the mobile device. However, please feel free to argue that it should have a `high` priority to be fixed.

I'd have to investigate a bit deeper to see if only downloads are affected or also other sections. Keeping the priority on low, sounds great for now. If it needs to be raised, I'll let you know.

**Comment by haszari** [comment]
Here's a similar example for `Add to cart` notice. I don't think this issue is specific to the downloads notice, I think could affect any notice with long text and an action button.

<img width="344" alt="Screen Shot 2020-09-22 at 4 37 20 PM" src="https://user-images.githubusercontent.com/4167300/93933120-4d69c600-fd75-11ea-8e31-462fbc8e46cc.png">

I don't think there's a major issue here, but it might be good to add some responsive styles to make notice layout more robust when the content is long and there's an action button. For example, move the action button on to a new line.

Totally agree this is a low priority though 👍

**Comment by swatipawarGS** [comment]
Hi @Aljullu @haszari @nielslange ,


Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce with the  Seedlet , Twenty Twenty and Storefront theme the issue on our end using WooCommerce 5.9.0 version . 


Please find below screenshots for reference :

Storefront theme : 

Site language to English : 

![#27745(storefront(english)) (1)](https://user-images.githubusercontent.com/94531721/145543505-1a9b024d-7fb2-4139-b832-c290d2c8eee1.jpeg)


Site language to Spanish : 


![#27745(storefront(Spanish))](https://user-images.githubusercontent.com/94531721/145543469-097cc1bd-4b7b-4ae6-952f-d8a4c8f3e024.jpeg)

Seedlet theme : 


![#27745(Seedlet)](https://user-images.githubusercontent.com/94531721/145543434-65e8f02e-7d45-423d-a2c7-a33ce90b344f.jpeg)


Twenty Twenty : 

![#27745(Twenty Twenty)](https://user-images.githubusercontent.com/94531721/145543846-c5845c63-c190-4e39-891c-0b34843cda95.jpeg)


Click on  Add to cart : 

![#27745(Cart)](https://user-images.githubusercontent.com/94531721/145543352-a9650710-2a93-4932-843c-18e9932e3001.jpeg)



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by mikejolley** [comment]
This looks to have been fixed. 
![Screenshot 2024-07-18 at 15 16 25](https://github.com/user-attachments/assets/42d9e1f3-2a1e-4155-b423-22ac176c4663)

You can see that when you use a narrow viewport the button wraps below the text now.
