### ISSUE TITLE
WC_Customer() has two identical functions

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#27743]
In https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-customer.php, the method `is_vat_exempt()` contains only the code `return $this->get_is_vat_exempt()`. Presumably one of the two ought to include a deprecation notice, guiding consumers to prefer the other.

**Comment by rrennick** [comment]
@DavidAnderson684 This is a valid point from a code optimization perspective. 

However, the `get_is_vat_exempt ` version of the function is to support the base data store functionality which uses `get_{property_name}` functions when they exist. The `is_vat_exempt` is for extensions / customization. Aliases are common in operating systems, programming languages, etc. Since there is a legitimate reason for both names we would not deprecate either of them.
