### ISSUE TITLE
Tooltips stay on screen after moving out in Safari on Mac

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#27769]
If I am in product edit page and edit product details the tooltip popup stay on screen even if I move out of tooltip window. This does effect workflow as I have to get into tooltip window again and move mouse around til it gets closed. But at moving around next tooltip window pops up.

Seems that Safari does not sent even mouseout to code?

Below screenshot were I had such a situation. Tooltip stayed on screen even after I opend media library window for selecting product image:

![Bildschirmfoto 2020-09-24 um 14 11 37](https://user-images.githubusercontent.com/3390880/94144135-0e209f80-fe71-11ea-8667-3598e8fd64c7.png)

**Comment by billrobbins** [comment]
I've also run into this issue through WooCommerce products, orders, and settings.  Tooltips won't disappear as they previously did.  Now I have to leave the tooltip with my cursor.  Then bring the cursor back over the tooltip and then finally leave in order to make it disappear.  It's a small thing, but it's annoying since these often cover up fields lower on the page.  

This happens to me on Chrome and Firefox too.

![tooltip](https://cdn-std.droplr.net/files/acc_705319/368JZY)
(Link to screenshot:  https://d.pr/i/368JZY)

**Comment by juliaamosova** [comment]
Hi @ajgw,

Apologies for the delayed response here. 

Thank you for reporting the issue. We have a fix for it in place via https://github.com/woocommerce/woocommerce/pull/28010 - it is included in WooCommerce 4.7 (currently can be tested using WC 4.7 beta). 

We assigned the fix to close https://github.com/woocommerce/woocommerce/issues/28007 (the same issue reported). Because of this, I am going to go ahead and close this thread. However, please let us know in case 4.7 won't fix the issue for you. Thanks!

**Comment by bardiotmarin** [comment]
Hy i have same trouble now
