### ISSUE TITLE
Write new e2e test: Merchant / Orders flow (customer payment page)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27878]
Write a new e2e test that covers Merchant / Orders flow. 

The new test should cover the following functionality:
- customer payment page

**Comment by zhongruige** [comment]
After digging into this a little bit (and thanks to @tammullen for providing guidance!) we have three flows to access this customer payment page:

**Create a Manual Order**

When creating a manual order, there's a link to the Customer payment page in the order details:

<img width="394" alt="Screen Shot 2021-02-05 at 2 30 18 PM" src="https://user-images.githubusercontent.com/71906536/107091351-dfbbb500-67be-11eb-948c-5201b0125f29.png">

If clicking the link while still logged in to WordPress/WooCommerce, and there is not a customer account associated with this order, it will have a "You are paying for a guest order. " notice in red across the top on the payment page:

<img width="836" alt="Screen Shot 2021-02-05 at 2 31 31 PM" src="https://user-images.githubusercontent.com/71906536/107091391-f3671b80-67be-11eb-87a5-6c677fc93ab5.png">

**Create a Customer Account and View a "Pending Payment" Order**

If you have an account as a customer, then you can go to `My account > Orders` and click the Pay button in the order Actions section:

<img width="840" alt="Screen Shot 2021-02-05 at 2 32 55 PM" src="https://user-images.githubusercontent.com/71906536/107091565-3cb76b00-67bf-11eb-9acc-674125438eb2.png">

**Clicking "Email invoice / order details to customer" - the Email Contains a Link to the Page**

In this flow, the email sent out will contain a link to pay for the invoice:

<img width="561" alt="Screen Shot 2021-02-05 at 2 15 39 PM" src="https://user-images.githubusercontent.com/71906536/107089961-ba2dac00-67bc-11eb-9574-405c4c0b7d31.png">

**Overall**

In all cases, the link will lead the user can then click the link (which is the same in all cases) and will be brought to a payment page:

`https://storeurl.com/checkout/order-pay/{order_id}/?pay_for_order=true&key=wc_order_{random_id}`

<img width="813" alt="Screen Shot 2021-02-05 at 2 17 11 PM" src="https://user-images.githubusercontent.com/71906536/107090100-ee08d180-67bc-11eb-838a-704821c1e5fb.png">

Given that, we have these three flows we can consider automating. I am thinking for this test, we can have the following steps in the test:

* Login as a merchant
* Create a new manual order
* Verify the "Customer payment page →" link is displayed
* Click the link
* Verify the warning text is shown (since this is a merchant flow, we should make sure they see the warning)
* Verify product / quantity / price all match
* Be able to pay for the order and land on the "Order received" page

**Comment by juliaamosova** [comment]
@zhongruige thanks for doing research on this issue! Your proposed plan below sounds good to me:

>Given that, we have these three flows we can consider automating. I am thinking for this test, we can have the following steps in the test:

>Login as a merchant
Create a new manual order
Verify the "Customer payment page →" link is displayed
Click the link
Verify the warning text is shown (since this is a merchant flow, we should make sure they see the warning)
Verify product / quantity / price all match
Be able to pay for the order and land on the "Order received" page

**Comment by zhongruige** [comment]
Thanks so much for the feedback @juliaamosova! I'll get started on adding in those tests 🎉

**Comment by tammullen** [comment]
> Create a Customer Account and View a "Pending Payment" Order

> If you have an account as a customer, then you can go to My account > Orders and click the Pay button in the order Actions section:

I realised we already have a separate flow for this 
https://github.com/woocommerce/woocommerce/issues/27884

**Comment by zhongruige** [comment]
> > Create a Customer Account and View a "Pending Payment" Order
> 
> > If you have an account as a customer, then you can go to My account > Orders and click the Pay button in the order Actions section:
> 
> I realised we already have a separate flow for this
> #27884

Thanks for sharing that!
