### ISSUE TITLE
The option "switch on to calculate  tax  automatic" don't show up to me:

### ISSUE THREAD

**Issue by mariofrancoz** [woocommerce/woocommerce#27931]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**  

the option: switch on to calculate tax automatic in the tab "impost" is not there. 

![imagem](https://user-images.githubusercontent.com/52144083/95772655-048e9880-0cb5-11eb-81d2-a7a548594a25.png)

So after I configured to show up the price with the impost don't works, after I check it I realised that this option is not there, how Can I fix it?

**Comment by rodrigoprimo** [comment]
Hi @mariofrancoz,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
