### ISSUE TITLE
Database tables wiki outdated

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#27946]
None of the WooCommerce Admin database tables are included in the current doc. The WooCommerce Admin related database tables should be included since this was merged into the 4.0 release. It is also missing the custom database tables that the Action Scheduler also uses which was updated in version 4.0 as well.

```
actionscheduler_actions
actionscheduler_claims
actionscheduler_groups
actionscheduler_logs
wc_admin_notes 
wc_admin_note_actions
wc_category_lookup
wc_customer_lookup
wc_order_coupon_lookup
wc_order_product_lookup
wc_order_stats
wc_order_tax_lookup
```

https://github.com/woocommerce/woocommerce/wiki/Database-Description

**Comment by rodrigoprimo** [comment]
Thanks for raising this, @lukecav.

We currently don't have a way to automatically update this page and I must say that we have been doing a poor job at keeping it up to date. I just added the Action Scheduler tables.

Before I proceed and add the WooCommerce Admin tables, I'm curious to hear from you what is the value that you get from this page and how do you use it? If, instead of having the list of tables in the wiki page, we just kept links to the parts of the code where those tables are created (for example, for WooCommerce core, it would be: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L799), would this work for your use case?

**Comment by lukecav** [comment]
@rodrigoprimo 

The wiki page is very useful for reference and it should be kept updated rather than having to look in the correct PHP file to find the database table reference each time.

**Comment by rodrigoprimo** [comment]
Thanks, @lukecav. If you could provide more details as to how you use it that would be great. I'm closing this issue as I found an older one that reports the same problem (#26953).
