### ISSUE TITLE
Add information to Tracks event

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27990]
As requested by @oneillo, the following properties should be added as global ones:
- Age of store in days
- Total # of completed orders
- Total # of products by Product Type (Simple Product, Grouped Product, Affiliate Product, Simple subscription, virtual, etc.)

**Comment by roykho** [comment]
So I am just looking into this one and had some questions before I start.

> Age of store in days

How do we determine this?

> Total # of completed orders

Does this mean orders with the status of "completed" ?

Since these information are not specific to an event, how often do we want to log this?

**Comment by oneillo** [comment]
> Age of store in days
In case this helps, I've seen an approach that relies on the [woocommerce_admin_install_timestamp option](https://github.com/woocommerce/woocommerce-admin/blob/38dfbff6d1d5943cfe196e1b5a6dcd6bb737b500/src/Notes/NoteTraits.php#L22) 

> Does this mean orders with the status of "completed" ?
Yes.

> Since these information are not specific to an event, how often do we want to log this?
FYI, I originally requested this, and I don't know the tradeoffs in terms of performance, storage cost, or other costs for including this in every event, but the intention was to retain a better snapshot of the state of the store when it is completing key actions like installing new plugins. Otherwise we have to join less-frequent WCTracker snapshots about the store config onto the Tracks data. We don't have anything blocked by this right now, but it would eventually be helpful for predictive analyses/actions.

**Comment by roykho** [comment]
Ok so having spoke with Woo Data team, thanks (@deltaWhiskey) and @oneillo , we've decided this information is best added to WC Tracker instead of Tracks. The reason being we only really need this information in an aggregated snapshot fashion and not necessarily in every event that happens in WC.

So all the information needed in the request is actually already passed to WC Tracker. Will be closing this now as it doesn't require any work from our side. Woo Marketing will take this over.
