### ISSUE TITLE
REST API: Variant attribute inconsistency

### ISSUE THREAD

**Issue by weaselmetal** [woocommerce/woocommerce#28040]
Global and custom product attributes result in different data on the REST API.
On the `line_items.meta data` of an order, returned from the API:

For a global attribute, `meta_data.key` is the lowercased attribute name prefixed with "pa_".
The `meta_data.value` of the chosen variant will be the slug of the attribute, which can differ from the original name.

For a custom attribute, the `meta_data.key` is the lowercased attribute name.
The `meta_data.value` of the chosen variant will match the `product.attributes.option` value exactly.

Yet, on the product itself, the attribute names and values are returned unchanged, for both custom and global attributes.
We wrote an integration against the WooCommerce REST API, and it's difficult to match up the variation information from orders with the attribute information of products, as they differ in multiple aspects.

I think it would be an improvement if attribute names and values were equal in all cases. Always having and using a slug would also help. Maybe the data returned on orders and products could be unified, for global and custom attributes.
If a distinction between them is desired, a property `scope=GLOBAL|CUSTOM` or `isGlobal=true|false` could still be added.

**Comment by rrennick** [comment]
@weaselmetal Thanks for the feedback. Since this is a published API we are limited to

- Adding new data
- Fixing errors
- Correcting issues where the response does not match the published specification for the API

Changing this version of the api to return different data in the response breaks the contract with existing API consumers. Here is some of the reasoning behind the current response

> The meta_data.value of the chosen variant will be the slug of the attribute, which can differ from the original name.

The reason the slug is used is that the name field is equivalent to a title field on a post. WordPress requires slugs to be unique but not the name
<img width="1162" alt="Screen Shot 2020-10-22 at 11 45 52 AM" src="https://user-images.githubusercontent.com/343847/96888576-2aa5fc80-145c-11eb-9dc6-772fea6de48e.png">

Create variations from all attributes:

<img width="862" alt="Screen Shot 2020-10-22 at 11 46 54 AM" src="https://user-images.githubusercontent.com/343847/96888731-4f9a6f80-145c-11eb-9d7e-b01fdd68a377.png">

In the response from the API you can see which it is
```
      "meta_data": [
        {
          "id": 20,
          "key": "pa_size",
          "value": "large"
        },
        {
          "id": 21,
          "key": "shape",
          "value": "Square"
        }
      ],
```

> For a global attribute, meta_data.key is the lowercased attribute name prefixed with "pa_".

In v3 of the API the `pa_` is what you use to distinguish between global and local attributes.

> We wrote an integration against the WooCommerce REST API, and it's difficult to match up the variation information from orders with the attribute information of products, as they differ in multiple aspects.

The product variation is included in the order response
```
      "id": 2,
      "name": "Test Variable - Small, Square",
      "product_id": 19,
      "variation_id": 20,
```
If you do have confusing attribute names you could use `https://example.com/wp-json/wc/v3/products/19/variations/20` to retrieve the information specific to that variation.

We will keep this in consideration during development of `v4` of the API but is not something we would implement in `v3`.
