### ISSUE TITLE
Image Post Thumbnail  issues in version 4.70 replacing from product gallery image when no thumbnail has been set

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#28053]
In version 4.70 b1 the single product post image when not set is replaced with the first image from  the product gallery image and thus not showing the default thumbnail  poster image.

I have two problems with this

1)  If a user does not set a post thumbnail but only gallery images the thumbnail is replaced by the first image in the gallery. A nice feature but now that same feature does not apply to the shop listing images. I suggest to use the same way when shop images are presented.

related https://github.com/woocommerce/woocommerce/pull/27289

> Why did this feature even got into the build? Simply having users set the thumbnail image for the post would have been the better way to go and stay. This is how we have been doing it for ages now. Why suddenly this change? It does not add anything. If one can set gallery images one can also set a thumbnail. I am realy missing the point for this code change.

The problem i have with this change is as follow: if you do this for the single image it should also work on the shop, related, upsell or any other product listings showing the product image.

Now we get the default image to show when no thumbnail has been set in the shop page, upsel, related. So this is only half of the solution. I know how to fix this myselves by overriding the woocommerce_template_loop_product_thumbnail action but i believe this change should also gotten into the default core code.

Thank you and please change that aswell.

2) The second issue i have with this change is the way the $post_thumbnail_id and  $attachment_ids are parsed to the files product-image.php and template and product-thumbnails.php. 

As i want to override the product-image.php and template and product-thumbnails.php as i am doing so now for years i now suddenly have a problem. I dont know when a user updates Woocommerce. But i do know they update my theme.

Now I still need to add a check for the product image having a value like this

`

		if (!isset($post_thumbnail_id)) {
		$post_thumbnail_id = $product->get_image_id();
		$gallery_image_ids = '';

		if ( ! $post_thumbnail_id ) {
			$gallery_image_ids = $product->get_gallery_image_ids();
			if ( ! empty( $gallery_image_ids ) ) {
				$post_thumbnail_id = array_shift( $gallery_image_ids );
			}
		}
		}
		
		`

If i dont do so  i am at risk to get a warning mesage saying 

> Notice: Undefined variable: post_thumbnail_id in the  product-image.php

Simply because the user did not update woocommerce yet for which he might have a good reason !

BUT i can NOT do this same trick as the variable $attachment_ids parsed to the template product-thumbnails.php is a array. There is no isset($attachment_ids) or is_array($attachment_ids) check working on this when you are on a older version of woocommerce.

In order to remain compatible with older wp versions i still need to add code into product-thumbnails.php like this before the thumbnails are presented.

`

		$attachment_ids = '';

		if ( $attachment_ids && ! $product->get_image_id() ) {
			array_shift( $attachment_ids );
		}

`

So now i am facing a problem that in order to remain comptible with older woo versions i have to add back in code that has been there before and was stripped in version 4.7.0

I would rather see that the  product-image.php and template and product-thumbnails.php call a function where they grab that correct product image and correct thumbnail array, with the new ability that if the post image not has been set that the first image of the product gallery image is used and the product gallery thumbnails are shifted one to the left so we do not get a duplicate thumbnail image.

This makes more sense then the way it is done now by parsing the variables to the template by $args  and this way we can remain backwards compatible when themes update their code and the users who do not update woocommerce yet. In most cases they do not update because they either have expired paid plugins or the plugins are  not yet compatible with the lates version. But they do update the themes.

Moreover having a seperate function that returns the correct image for the product_image_id and attachements_ids when no post thumbnail has been set can be usefull for plugins that uses these to present images in a carousel and sliders etc.

Please consider changing this.

**Comment by peterfabian** [comment]
cc @claudiosanches

**Comment by claudiosanches** [comment]
Hello @BackuPs, thank you very much for submitting this report.

While I'm not sure about the time frame to also apply it in the product listing pages, for sure I'll make it backwards compatible before 4.7 gets released. I'll work on it before we release RC 1 on next Tuesday. Thanks!

**Comment by rodrigoprimo** [comment]
I checked this issue, and I will leave here my thoughts to help decide the best way to handle this for 4.7.0 and future versions of WooCommerce.

I agree with @BackuPs that the change introduced in #27289 can be a bit confusing to users as we are displaying the first image from the gallery if there is no product image on the single product page, but we don't do the same in other places like the shop, cart and checkout pages. Actually, even on the single product page, if you are using Storefront and scroll all the way to the bottom, a top bar is displayed informing the user what product they are viewing, and this bar doesn't include the image as well.

Since we are already past PR freeze for 4.7.0, I suggest we revert #27289 instead of shipping it with changes to make sure it is backwards compatible. After that, we can have a conversation to decide if this is a change that we want to introduce. If we decide to proceed with it, I believe we should be consitent across all places where we display product images and display the first image from the gallery for products that don't have a produt image defined. Probably a good idea to get a designer involved in this decision as well.

No matter what we decide, we will need to address #27247 to display the magnifying icon when viewing images for variations of a variable product that doesn't have a product image set. That being said, I don't see this as a high priority bug that needs to be included in 4.7.0. It can wait for another release.
