### ISSUE TITLE
WooCommerce 4.6.1 Bug Shop_manager  [woocommerce_rest_cannot_view error]

### ISSUE THREAD

**Issue by bambootb** [woocommerce/woocommerce#28085]
Already post this issue to Wordpress.org support:
https://wordpress.org/support/topic/woocommerce_rest_cannot_view-error-with-woocommerce-to-4-6-1/#post-13575114

Step to replicate:
1. Log into a user with role “shop manager”
2. go to order page or any WooCommerce page
for example: [yoursite]/wp-admin/edit.php?post_type=shop_order
3. open inspector tools, then there will show the errors

Please see the screenshot attached:
https://monosnap.com/file/SqYYcIK0cTMDVRldLHliv6ZmGLLf32

Best,
T

**Comment by bambootb** [comment]
Any update regarding to the issue? @mikejolley @claudiosanches

**Comment by juliaamosova** [comment]
Hi @bambootb,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![shop_manager](https://user-images.githubusercontent.com/19143190/97634511-3a00e900-1a0c-11eb-91fc-92c4d63e1446.jpg)

I think this is rather a `high` priority issue and something we should fix soonish. However, whoever is going to work on it, feel free to argue.

**Comment by bambootb** [comment]
@juliaamosova 
Is there any update regarding to the issue.

Thanks,
T

**Comment by roykho** [comment]
This is specifically related to WC Admin so I am moving it there.

**Comment by roykho** [comment]
Issue moved to [woocommerce/woocommerce-admin #5745](https://github.com/woocommerce/woocommerce-admin/issues/5745) via [**ZenHub**](https://www.zenhub.com/)

**Comment by uhlhosting** [comment]
@roykho the issue moved, yet that Repository is archived, and so thus the issue never solved, 2 years later! Someone messed up big time here!

So what is going to happen now? Who will fix the issue when the woocommerce-admin repository is archived, you people care about our customers websites? Or just to make yourselves more money and we are good like stupid as we are to keep on contributing, you will pick what you seem fit, and the rest is up to us. Or? 

it seems like you folks always forget that without us the community and adopters you wont be earning either.

Just unacceptable for a multimillion dollar company, to not make proper use of BUG tracking, and only to cause more issues to their users instead of helping/solving.
