### ISSUE TITLE
Order table does not contain all orders

### ISSUE THREAD

**Issue by jozeflambrecht** [woocommerce/woocommerce#28130]
**Prerequisites (mark completed items with an [x]):**
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.

**Describe the bug**
Pending orders are missing in table. The total (all orders) is correct. When I go to Analytics -> Orders, I can see the pending orders..

**Expected behavior**
Show all orders.

**Screenshots**
![image](https://user-images.githubusercontent.com/11506957/97480959-7fe58080-192a-11eb-955f-c77dd3017227.png)

As you can see, total orders is 6, in the table I see only 4 orders..

![image](https://user-images.githubusercontent.com/11506957/97482416-84129d80-192c-11eb-95fb-e5370a1bb206.png)

In analytics, I can see the 2 "missing" orders

WooCommerce: 4.6.1
WordPress: 5.5.1
PHP: 7.4.11
Theme: Storefront 2.7.0

**Comment by juliaamosova** [comment]
Hi @jozeflambrecht,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Comment by jozeflambrecht** [comment]
Hello,
I did some research and see that the missing orders have the `processing` status instead of `wc-processing`. (because of payment gateway) This fixes the issue.
Still wondering why the order does show up in the analytics (with correct order status)..

**Comment by ajayver** [comment]
I also have the same issue. I use $wc_order->set_status in a custom plugin and it removes "wc-" from statuses, so they end up having unexisting statuses in the database, hence not listed in the orders list: https://prnt.sc/v9ffh3

**Comment by jozeflambrecht** [comment]
@juliaamosova can ou please re-open? The issue is here why the `wc-` prefix is dropped when using `$order->update_status( 'processing', 'note' );`

**Comment by ajayver** [comment]
I was able to fix this by switching my functions to use a later hook. I switched from 'woocommerce_after_register_post_type' to 'rest_api_init' and looks like it works now. 
I guess some functions weren't loaded at the point when I was trying to update the status.

**Comment by juliaamosova** [comment]
Reopening the issue due to the feedback above.

**Comment by rrennick** [comment]
> The issue is here why the wc- prefix is dropped when using $order->update_status( 'processing', 'note' );
> Which can easily be reproduced..

@jozeflambrecht Can you provide a complete code sample that reproduces the issue? This will allow us to investigate further.
