### ISSUE TITLE
Adding a product does not sync to facebook

### ISSUE THREAD

**Issue by wahsunny** [woocommerce/woocommerce#28220]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
When I try to add a new product via WordPress, the product gets updated inside WordPress but does not sync to Facebook.

I get the following error message
```
Your message couldn't be sent because it includes content that other people on Facebook have reported as abusive.
```

This is my product link
[https://www.wahshopping.topi.fun/product/test-product-1/](https://www.wahshopping.topi.fun/product/test-product-1/)

I am not sure what is causing this, but for me this is a show-stopper and critical issue.

I used a brand new catalog, pixel profile and Facebook page to isolate the issue, but the issue is still persistent. 
# Screenshot
![Capture](https://user-images.githubusercontent.com/72580462/98595013-408a3d00-22f7-11eb-85fa-22691b8a9e65.PNG)

**Comment by juliaamosova** [comment]
Hi @wahsunny,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request for the `Facebook for WooCommerce` extension which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please contact the team that maintains the `Facebook for WooCommerce` extension by clicking on the `Get support` button on the [Facebook for WooCommerce](https://woocommerce.com/products/facebook/) product page.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
