### ISSUE TITLE
Change to a default blank on Hold Stock (minutes) time limit. Instead of default 60 minutes.

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#28236]
**Is your feature request related to a problem? Please describe.**
I noticed that a customers order suddenly got cancelled. I had to look it up online and found: https://hitusupdesigns.com/blog/woocommerce-unpaid-order-cancelled-time-limit-reached-fix/ I find it very strange that there is a time limit for handling orders. We thought it was a bug. This should start out blank and the admin can instead go in and add a time limit if need be. 

**Describe the solution you'd like**
Instead of adding a time limit of 60 minutes. Let it start out blank and if needed the admin can go in and adjust this setting.

**Describe alternatives you've considered**
Searching for the bug online. Finding a solution. Which was to blank out the Hold Stock (minutes) setting.

**Comment by peterfabian** [comment]
Hi, thanks for the suggestion. I think the time limit makes sense in case you have stock management enabled, as otherwise I see basically two options:
- either you don't hold stock for the customers who went through the checkout but haven't paid yet and can run into problems with negative stock, 
- or you hold stock for them indefinitely, which doesn't make sense either, as then you can't sell those items as they are blocked. 

Thus the time limit. Leaving this blank by default means hold stock gets disabled by default, which I don't think is what people expect when they enable stock management. 

Perhaps if this doesn't work well with some payment gateways, we could look into fixing it? Are you also experiencing problems with this related to PayPal?

**Comment by paaljoachim** [comment]
Thank you for the feedback Peter!

I told my colleague about your reply, and I will see if he has anything to add.
For now I will just close the issue, and will reopen if needed.
