### ISSUE TITLE
Bug in order tracking page

### ISSUE THREAD

**Issue by parsmutaf** [woocommerce/woocommerce#28243]
Hello,

In the order tracking page, text in Order ID and Billing e-mail address exceed the box size. I tried fixing it buy putting "resize: both" but it did not work. Thanks.

![Screen Shot 2020-11-11 at 16 49 47](https://user-images.githubusercontent.com/74306261/98819487-f95a9400-243d-11eb-89e1-af04caccdef6.png)

**Comment by juliaamosova** [comment]
Hi @parsmutaf,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin that allows order tracking. It can also be caused by the theme you are using.  

Please contact the author of the plugin directly for further help.
