### ISSUE TITLE
{"code":"woocommerce_product_invalid_image_id","message":"#12362 is an invalid image ID.","data":{"status":400}}  even with a valid ID it still throws the same error

### ISSUE THREAD

**Issue by haonetuc24** [woocommerce/woocommerce#28240]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

{"code":"woocommerce_product_invalid_image_id","message":"#12362 is an invalid image ID.","data":{"status":400}}

even with a valid ID it still throws the same error

**Comment by juliaamosova** [comment]
Hi @haonetuc24,

Thanks for raising the issue! Would you please provide the details of the request you are making to receive this error?

**Comment by haonetuc24** [comment]
hi we are trying to use the Rest API to copy the image from Shopee (
https://shopee.ph) to my woocommerce website (https://nobaco.ph) however we
are getting the following error that I provided.

Regards,

**Comment by tammullen** [comment]
Hi @haonetuc24 

Sorry for the delay in replying

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
