### ISSUE TITLE
Wrong cart subtotals due to rounding

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#28292]
I have a product, that due to the Woo Mutilingual currency conversions has total price `301.90909`. The tax rate is 23%, so the product price is `245.454545` and tax `56.454545`.

The store is set to display `0 decimals`, on the product page I see the price `302 PLN`. When I add the product to the cart, I get wrong subtotal `301 PLN`. When I go to checkout, the cart subtotal is `301 PLN`, and the total is `302 PLN`. When I submit the order, the order subtotal is `301 PLN` and the order total `302 PLN`.

I dived into the code and the issue comes from rounding too soon: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L753. 

That rounding with my prices returns 245 + 56, which is wrong. There also seems to be no filter to be able to override this.

There used to be similar rounding for cart total, but that got fixed and is returning non-rounded values, so is there any reason why the `items_subtotal` is rounded here?

**Comment by vedanshujain** [comment]
We round `items_subtotal` there because at that point its also displayed to the shopper. So if it is not rounded, then they may see a different value (since in the frontend we any way round to make it pretty) than what is being used in the calculation and see different results. Additionally, if there are more items in the card, then in the subtotal we would have to sum them and then anyway would have to round to them (so that we can display it accurately to the shopper).

In your case, you are seeing an inconsistency, because rates are entered with more precision but are displayed with less precision. This adds a problem because the tax total will also be displayed, and let's say if we don't round at the subtotal level, then the sum of tax + subtotal won't add up to the total.

For example, 

when not rounded at subtotal:
245.45 + 56.45 = 301.90, will be displayed as 245 + 56 = 302 to the customer (wherever we show the tax breakup), whereas this total is 301 which is what customers do see currently. So if we don't round, then the customer may ask why the total is off by 1. 

When displaying product prices, we don't break tax and subtotal, so the price entered is displayed as it is, which in this case happens to be 302.

Generally in these cases, when there is a mismatch in prices entered and prices displayed, the recommendation is to show prices exclusive of taxes in the shop. If this is not possible, I would recommend at least show prices exclusive of taxes in during cart and checkout. This way customers will have a more consistent experience. You can customize this setting from WooCommerce > Settings > Tax > Display prices during cart and checkout.

For repository maintenance purposes, I am going to close this issue, but will re-open if you reply back with any additional questions/suggestions or if you want to discuss more.

**Comment by vasikgreif** [comment]
@vedanshujain Thanks. Entering prices tax excluded is not an issue for the shop owner, and displaying tax excluded prices on cart is a legal issue. 

I don't think that the prices that are used for calculations should be rounded that soon - I mean, if I removed the rounding, the prices worked as expected, because what is displayed on the frontend goes through `wp_price`, which rounds the values by whatever is set in the admin.

Can you please try removing the rounding and check if it breaks anything for you?

**Comment by vedanshujain** [comment]
Closed in #29318
