### ISSUE TITLE
Write new e2e test: Merchant / Orders / Refund Order

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28356]
Write a new e2e test that covers `Merchant / Orders / Refund Order` flow.

**Comment by zhongruige** [comment]
I'll work on getting these tests added to the e2e test suite, applying a refund when viewing an order:

![Screen Shot 2020-11-23 at 9 36 23 PM](https://user-images.githubusercontent.com/71906536/100049183-f6fc2080-2dd3-11eb-800c-8b28909b6df0.png)

**Comment by zhongruige** [comment]
As I've been looking into this issue, my current thinking is I could potentially add the product as a Store Owner to an order. Granted I could "cheat" it a bit by just adding fees or shipping, but I believe this should be testing on an order with a product. Alternatively, I could use the customer flow, but I feel this is a bit too cumbersome of the needs of this test. So, I'm curious on what people think about adding a fee or shipping to an order to test the refund with or if a product would be more desirable in this flow.

**Comment by rrennick** [comment]
> I believe this should be testing on an order with a product.

The `e2e-utils` package has a `createSimpleProduct()` function for creating a product needed in an E2E test.

**Comment by tammullen** [comment]
Great question, I initially thought a using a fee could potentially make the test slightly faster and with less of a data dependency than using a product.
However, as @rrennick points out, because we already have a function for creating a product via the API it would be fast to do so and using a product will be a more realistic scenario as it is likely the majority of refunds are done on products. So I think we should try using Product.

**Comment by zhongruige** [comment]
Sounds good! Thanks for the feedback @rrennick and @tammullen -- I'll go that direction with these tests.
