### ISSUE TITLE
WooCommerce suddenly made ZIP and City / Town fields optional

### ISSUE THREAD

**Issue by mladja12** [woocommerce/woocommerce#28366]
Hello everybody,

I have a problem with WooCommerce at this website: https://santi.rs/ 

It may be a little hard to see what is going on actually, because the website is just in Serbian language...

However, the problem is with the checkout page. Somehow Town, ZIP code and County/State fields became optional instead of being required. Without those, it is impossible to complete an order, it just can not be shipped if a customer misses to add that information.

I have the same setup (theme and plugins) here: https://etilab24.de/ and everything is working just fine. This website is not launched yet, but the Serbian one is.

I tried to disable all the plugins I am using and to enable just the WooCommerce and the issue still was present. I've cleaned the cache, I've performed a hard reload, even tried to access the website from browsers I have never used before, but without any success.

I also tried to add this plugin https://wordpress.org/plugins/flexible-checkout-fields/ but when I tried to change things, I got a message that fields I am trying to change are controlled by WooCommerce and because of that it is not possible to change them.

Does anybody know what is going on? I have never seen any options anywhere to set that data optional or required (except in the mentioned plugin). I can change that just  for the phone number and company name under the theme settings, but that is all.

Am I missing something? Is all this because I made a stupid mistake somewhere in the sett up process?

Thanks in advance.

Mladan

**Comment by masteradhoc** [comment]
@mladja12 see the PR here https://github.com/woocommerce/woocommerce/pull/27779 made by @zzap

**Comment by mladja12** [comment]
Thanks.

**Comment by zzap** [comment]
Hi @mladja12 , you can use `woocommerce_get_country_locale_default` filter to modify default values.

**Comment by mladja12** [comment]
Well, that was urgent so, I found a plugin to override that. Btw., why WooCommerce would make those fields optional for few countries? That is super weird.

**Comment by rrennick** [comment]
Hi @mladja12 ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mladja12** [comment]
Hi,

Well, since I fixed the issue with a plugin, I can not provide all that data for you, because I do not want to mess with a live website, but I can explain what was (and probably still is) wrong. Plus, I think this is just administrational problem and it could be fixed by WooCommerce easily, without any coding.

It looks like WooCommerce disabled few fields at the checkout page from being mandatory for filling, so a customer could live them blank. It also looks like they did that just for specific countries.

In case of Serbia, ZIP code and City/Town fields are optional. Those fields are an important part of any address, so, if a customer misses to fill them out, his order can not be shipped. Of course, you, as a shop manager, have his phone number, so you can make a call and ask for missing data, but that is so unprofessional.

**How I figured this out?**

Well, I found similar complains on line, so I decided to run a test. I added a fresh WordPress installation on a subdomain and I installed there just WooCommerce. After setting it up, I tried to place an order which should be shipped to Serbia and - voila. 

I was watching how mentioned fields became optional right away after I added Serbia as destination country for that order. Then I set Germany and they became required again.

This is the case in both: billing and shipping addresses.

I hope this helps.

P. S. This just crossed my mind now. You can still see what I am talking about here: https://etilab24.de/ Just try to place an order and select Serbia as country at the checkout for billing and take a closer look at the mentioned fields.

If you do not speak German, this is the translation for points of interest:

Ort / Stadt - **this is Town / City**
Postleitzahl - **this is ZIP number**

BR,
M.

**Comment by zzap** [comment]
@mladja12 I made PR for making city and postcode mandatory again.

https://github.com/woocommerce/woocommerce/pull/28415
