### ISSUE TITLE
Question/request - Ability to record Tracks events in REST endpoint 

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#28404]
Currently the Tracks PHP library is only loaded in `is_admin()` context. Since admin functionality can be handled via REST endpoints I think we should make Tracks events available for use here.

In AutomateWoo, we have an endpoint to create a workflow via a specified preset and would like to record a tracks event when every workflow is created including this endpoint. 

https://github.com/woocommerce/woocommerce/blob/4b3b40d42e35852b7ac465b331f8204feb1ecdcd/includes/admin/class-wc-admin.php#L65-L69

**Comment by rrennick** [comment]
@danielbitzer I've labeled this request for discussion.

**Comment by jconroy** [comment]
Hey @rrennick 👋 what's the process for progressing the discussion here?

**Comment by garymurray** [comment]
@timmyc @peterfabian who should we be pinging to follow-up on this issue? Currently it's not enabling us to track usage of new workflows created in AW accurately and means we cannot assess the overall impact of the preset workflows.

**Comment by peterfabian** [comment]
I think it makes sense and could be useful for us as well to track usage of REST API endpoints. I'll enqueue it for prioritization and estimation for sprint 2021.3.

**Comment by mikkamp** [comment]
This issue is no longer valid since PR #37796

In that PR the loading of the tracks classes was moved to `class-woocommerce.php` so tracks can be recorded during REST API requests. While testing this for AutomateWoo I was able to confirm tracks being sent during a REST API request.

As such we are no longer waiting on this issue for AutomateWoo so I'll go ahead and close it.
