### ISSUE TITLE
Partial Refund with Coupon: redistribute discount over remaining items?

### ISSUE THREAD

**Issue by jozeflambrecht** [woocommerce/woocommerce#28436]
When a customer applies a coupon, to make sure taxes are calculated correctly due to rounding the discount is split across all items.
However, when we do a partial refund, should the coupon value not be redistributed over all remaining items?

**Comment by juliaamosova** [comment]
Hi @jozeflambrecht,

Thank you for raising the question here. 

My personal opinion here would be that when the partial refund is issued, the coupon's distribution should stay the same - meaning it should not get redistributed among remaining items on the order. I see the use of coupons similar to items on sale which are usually final and therefore non-refundable. If the customer had to request a refund on the order that had a coupon applied, then it is on them and they sort of missed the chance. But that doesn't mean that the coupon amount has to get redistributed among the remaining items. 

I am curious, however, what others think and also how other e-commerce platforms handle it. I added a label `status: needs discussion` so that we could decide at some point if there is any action for us to take as far as changing existing behavior.

**Comment by jozeflambrecht** [comment]
Thanks @juliaamosova 
If you and the community decide to take action, happy to contribute!
