### ISSUE TITLE
Cant sync with facebook

### ISSUE THREAD

**Issue by gesponda** [woocommerce/woocommerce#28475]
I have tried change status for the total of articules we have from no sync to sync and show on facebook but was impossible since the only possibility was to change from no sync to sync and hide.

**Comment by juliaamosova** [comment]
Hi @gesponda,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the `Facebook for WooCommerce` plugin which is one of the products on our marketplace. To get further technical support for it, please open [Facebook for the WooCommerce](https://woocommerce.com/products/facebook/) page and click on the `Get Support` button on the sidebar. 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
