### ISSUE TITLE
country-select.js

### ISSUE THREAD

**Issue by robotikz** [woocommerce/woocommerce#28511]
If Select-Field for countries is empty-empty, then the error comes.
Bug in UI-JS-File
/wp-content/plugins/woocommerce/assets/js/frontend/country-select.js
see at the screenshot and add the marked checking, thanks
![woo_bug](https://user-images.githubusercontent.com/10348033/101336465-cd82d080-387a-11eb-806a-e5caa4ab4229.png)

**Comment by juliaamosova** [comment]
Hi @robotikz,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Comment by robotikz** [comment]
what kind of details do you need?

**Comment by juliaamosova** [comment]
Hi @robotikz,

We need all the details that we request in our bug report template which you seemed to ignore. 

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by robotikz** [comment]
if you show my description and screenshot to your frontend developers they understand it.
My aim was to help you, I have no time to describe it all, may by someone in the future make it better as I ;-) 
You can ignore it or close it, 
thanks

**Comment by juliaamosova** [comment]
@robotikz if you want to help us, it is best if you provide the details that we ask for to avoid unnecessary back and force replies - this doesn't help anyone. I will mark this for the core team to take a look further but it will be great if you'd follow the bug report template next time.

**Comment by rrennick** [comment]
The code being referenced in the screenshot is https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/assets/js/frontend/country-select.js#L174.

From the [jQuery documentation](https://api.jquery.com/val/):

> The .val() method is primarily used to get the values of form elements such as input, select and textarea. When called on an empty collection, it returns undefined.

The first condition in the if statement verifies that `$country_input` is not an empty collection so it's not clear how the issue described above could occur. 

@robotikz I'm marking this as `needs feedback` as we steps to reproduce the issue to test that a change addresses the issue.
