### ISSUE TITLE
Sale price and date range is not in REST API

### ISSUE THREAD

**Issue by Bjolja** [woocommerce/woocommerce#28526]
When accessing REST API for getting products, every single product has an attribute for sale_price, regular_price, date_on_sale_to and date_on_sale_to. This is not the case for variations. It seems as the price is calculated on the fly and takes the lowest price, so if it is on sale one the time of the request, the sale price is returned, otherwise, regular price is shown.

This should be changed to comply with the product itself.

**Comment by negapo** [comment]
Hi @Bjolja 
According to the docs https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variation-properties the variation also has those fields. These are the fields relating to sales info:

"price": "9.00",
"regular_price": "9.00",
"sale_price": "",
"date_on_sale_from": null,
"date_on_sale_from_gmt": null,
"date_on_sale_to": null,
"date_on_sale_to_gmt": null,
"on_sale": false,

Does your parser have this fields set up?

**Comment by juliaamosova** [comment]
Hi @Bjolja,

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

Please see the variaions fields in question in my request for variable products:

![var](https://user-images.githubusercontent.com/19143190/101993485-2098c100-3c89-11eb-8de5-2e5921ab703f.jpg)

I can recommend testing your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Bjolja** [comment]
Thank you for quick feedback. I read the documentation and it clearly states you should be correct so I disabled my theme, and voila, correct output from my REST api. Was not aware themes could interfere with the output from the API

**Comment by juliaamosova** [comment]
Thanks for your follow-up @Bjolja! Glad to hear that you found the culrupt.
