### ISSUE TITLE
Tracks: wcadmin_settings_change not working on the Payments tab

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#28603]
@pmcpinto commented on [Mon Dec 14 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875)

**Describe the bug**
The `wcadmin_settings_change` is not being triggered when you make an update on the Payments tab (Settings)

**To Reproduce**

1. Go to Settings > Payments (make sure that you have event tracking enabled)
2. Toggle one or more payments options
3. Save changes
4. See that `wcadmin_settings_change` wasn't triggered in the network tab. 

**Expected behavior**
Trigger `wcadmin_settings_change` when the user saves any change in the Payments tab. The `tab` prop should have the `checkout` value

---

@pmcpinto commented on [Mon Dec 14 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875#issuecomment-744630693)

@timmyc I suppose that this needs to be implemented in WC Core, so I'm wondering if we still have time to include a fix for 4.9. Assuming that the fix is straightforward. If not let's target 5.0

---

@timmyc commented on [Tue Dec 15 2020](https://github.com/woocommerce/woocommerce-admin/issues/5875#issuecomment-745629908)

Confirmed this is not working on a ecom plan site. I tried toggling COD payment type, and also adjusting values of the COD payment type description and did not see the tracks event record at all. Worth mentioning this is a server side track, so nothing will be shown in the network tab. Rather I was using the tracks viewer for my wpcom user account to test.

Associated logic for this particular track [lives here](https://github.com/woocommerce/woocommerce/blob/085b4b53fae187b0669714bc9da4e3084ba318d8/includes/tracks/events/class-wc-settings-tracking.php#L102) so we should probably move the issue to the woo core repo.

**Comment by pmcpinto** [comment]
@timmyc just a heads up that I already moved the issue to the Core repo

**Comment by rrennick** [comment]
@pmcpinto Is this still an issue?

**Comment by pmcpinto** [comment]
Hey @rrennick yes, I'm still seeing this issue in the tracking

**Comment by pmcpinto** [comment]
@peterfabian do you have an estimate on when this will be fixed? I can also check if someone from Isotope can help with this

**Comment by peterfabian** [comment]
Hey @pmcpinto If Isotope has some spare cycles on this, it would be great to have a helping hand. If not, please let me know and we can prioritize it higher in Proton. Thanks!

**Comment by pmcpinto** [comment]
@becdetat can you check if it's possible to include this in the scope of cycle 21? Thanks

**Comment by becdetat** [comment]
@pmcpinto For cycle 21 I definitely think it can be included

**Comment by joshuatf** [comment]
Just noting that [this branch of the test helper plugin](https://github.com/woocommerce/woocommerce-admin-test-helper/pull/25) may be useful for debugging this event since it's a backend event.

**Comment by octaedro** [comment]
Hi @pmcpinto, I have a question related to this issue. I assumed we needed to track all gateway settings and the toggling but after chatting with @joshuatf, he pointed out that it wasn't so clear that we should also track every gateway settings. Since it's possible to enable/disable a payment gateway from the specific payment settings page (e.g. bacs) I thought that we would want to also track those events.
Is it ok if we just track the Payments toggle or should we also track every change to the gateway settings?

**Comment by pmcpinto** [comment]
@octaedro it would be better to track every change to the gateways settings. Let me know if this has a significant impact in the effort

**Comment by octaedro** [comment]
Thank you @pmcpinto, I'm going to add that change in a follow-up PR. I have a couple of commits ready for that.

**Comment by octaedro** [comment]
Hey @pmcpinto ,

I wanted to confirm with you what and how we will track the gateways settings changes.
Right now I can see two different options to track the gateway settings:

**Option 1**
Record the gateway name (e.g. `woocommerce_bacs_settings`), tab name, with the addition of the section name. If we add the section name that means that there is a change inside of a specific payment setting, otherwise (without a section) it's just the toggle.
The `Advanced` tab works like that so we should just follow the pattern we're using.
The effort to do this is minimal.

**Option 2**
There isn't an out-of-the-box way to track the changed items under the Payments tab. We can save another param to record the modified element name (like: title, description, enabled).
This would take more time and we should test this very well, to be sure that it's not breaking anything else.

Initially, I would go for the first option, since it follows the way we're currently recording that kind of event, but I wanted to confirm with you first just in case.

**Comment by pmcpinto** [comment]
@octaedro  Option 1 seems to be the best approach. It's in line with what we already do in other settings sections, where we record the tab and the setting.
