### ISSUE TITLE
 [GlobalStep - WooCommerce 4.8 + WPB 3.9] Non-ASCII character's product names fails to retain in Search text field on frontend

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28614]
## Bug Description:
Non-ASCII character's product names fails to retain in Search text field on frontend

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version  87.0.4280.88 (64-bit))
                 Firefox(Version 83.0)(64-bit)
                 Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Go to Products->"Add New" Product
1. Add the Product Name as جميلة and price and save it. 
1. Go to Pages-> Add New.
1. Add a "All Product" block.
1. Go to frontend by tapping on Preview->open in new tab option 
1.  On Search text field, enter the product name جميلة and tap on search icon.
1. Note that product is displayed.
1. Observe that product name fails to retain in Search text field.

## Actual Result:
Non-ASCII character's product names fails to retain in Search text field on frontend

## Expected Result:
For all products, its product name should retain in Search text field on frontend irrespective of the characters used 

## Artifacts:
[#28614.zip](https://github.com/woocommerce/woocommerce/files/5710376/28614.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for reporting the issue. However, it looks like everything is working as expected. The reason why in your case the name of the product doesn't stay in the search bar is because you only have 1 of those products so WooCommerce navigates directly to the product page in that case and there is no need to have product name in the search bar. 

I tested with 2 products and it seems to work as expected - please see gif below:

![](http://g.recordit.co/xkbgbOJuKA.gif)

I am closing this as a non-bug, however, please feel free to comment back in case I missed something and we'd take another look.
