### ISSUE TITLE
 WooCommerce Memberships is wrongly modifying a WP's query WHERE clause by adding "comments_clauses" filter

### ISSUE THREAD

**Issue by geeksalah7** [woocommerce/woocommerce#28638]
**Describe the bug**
WooCommerce Memberships is wrongly modifying a WP's query WHERE clause by adding "comments_clauses" filter.
When we use LEFT JOIN in MySQL, the purpose is that we need all rows from the first table, if we include a column from the second table, in the WHERE clause we need to add `OR column IS NULL` as well otherwise the LEFT JOIN will act as a simple JOIN. 

**Expected behavior**
I wanted to get all comments, having post_id = 0 through the `new WP_Comment_Query($args)->get_comments()`, which should actually work fine and list those comments having comment_post_ID = 0.

**Actual behavior**
Comment having comment_post_ID  = 0 are not listed through `new WP_Comment_Query($args)->get_comments()`.

**Steps to fix the bug**

1. Go to woocommerce-memberships\includes\class-wc-memberships-user-memberships.php file
2. Go to `public function exclude_membership_notes_from_queries( $clauses ) {`
3. Change this line `$clauses['where'] .= " $wpdb->posts.post_type <> 'wc_user_membership'";` to the following
4. `$clauses['where'] .= " ($wpdb->posts.post_type <> 'wc_user_membership' OR $wpdb->posts.post_type IS NULL)";`

**Comment by juliaamosova** [comment]
Hi @geeksalah7,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Memberships plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
