### ISSUE TITLE
Kaspersky Internet Security reports the `tests\e2e\env\external.md` file as a detected object.

### ISSUE THREAD

**Issue by bobbingwide** [woocommerce/woocommerce#28666]
**Prerequisites (mark completed items with an [x]):**
Not applicable.
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Kaspersky Internet Security reports the `tests\e2e\env\external.md` file as a detected object.
It's not possible to view the file.

**Expected behavior**
The file shouldn't be considered a **detected** object.

**Actual behavior**

Here's the report from Kaspersky Internet Security
```
File: C:\github\woocommerce\woocommerce\tests\e2e\env\external.md	
Object name: not-a-virus:HEUR:RiskTool.Script.BitMiner.gen	
Object type: Legitimate software that can be used by criminals to damage your computer or personal data	
```

**Workaround:** Add the file to exclusions.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Clone https://github.com/woocommerce/woocommerce.git to a Windows machine with Kaspersky Internet Security
2. Attempt to view the file `tests\e2e\env\external.md`
3. See the report in Kaspersky

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**

Not applicable 

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
Not applicable.
```
</details>

**Comment by rrennick** [comment]
@bobbingwide Thanks for submitting the issue. 

`external.md` is a text file containing [markdown](https://guides.github.com/features/mastering-markdown/). Since it's just a text file it's not clear why a malware scanner would flag it. 

The `/tests/` folder is not included in the distributed WooCommerce plugin. If you are setting up a development environment on your local computer then you may need to address this type of flagging (by adding exceptions to your scanner) as you add development files.

Closing this issue.
