### ISSUE TITLE
WC 3.8: stock is decreased in Admin "Order / Add order" when adding a product even for a Quote status.

### ISSUE THREAD

**Issue by flyingeyefr** [woocommerce/woocommerce#28674]
Context
Admin / Add order is used to create quotes for new customers. Therefore we use WooCommerce Order Status Manager plugin and have created a custom status "Quote". A quote should not affect the stock because it is not yet a validated order.

Describe the bug
When a quote is created or updated, the stock is modified for each item inside the quote.

Expected behavior
No further stock adjustment should happen.

Actual behavior
The stock is increased or decreased when creating/modifying a quote.

Steps to reproduce the bug: 
Install WooCommerce Order Status Manager plugin and create a "Quote" custom status. 
Create a new order, add items, Save it: stock is modified. 

Please advise.

![2020-12-26_172132](https://user-images.githubusercontent.com/50369066/103155640-edceec80-47a1-11eb-8237-83cf516f9a6f.jpg)

**Comment by juliaamosova** [comment]
Hi @flyingeyefr,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Order Status Manager plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
