### ISSUE TITLE
Store Notice appears truncated 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28701]
## Bug Description:
For "Store Front", "Twenty-Twenty" and "Twenty Twenty-One" themes, Store Notice appears truncated and Dismiss button visibility is low when viewed on frontend

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard 
1. Click on "Personalize my store" under "Finish Setup" checklist on WooCommerce->Home
1. Complete till step 3 and add Store Notice as a long text 
1. Go to front end and Note the "Dismiss" option and text  on Store Notice
1. Observe that Store Notice appears truncated and Dismiss button visibility is low when viewed on frontend

**Note**:
Observed for "Store Front", "Twenty-Twenty" and "Twenty Twenty-One" themes

## Actual Result:
Store Notice appears truncated and Dismiss button visibility is low when viewed on frontend

## Expected Result:
Store Notice should not appear truncated and Dismiss button visibility should be high when viewed on frontend

## Artifacts:
[#28701.zip](https://github.com/woocommerce/woocommerce/files/5757271/28701.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Sharing screenshot provided by @gglobalstep in the `Artifacts` section for quicker overview:

![#28701](https://user-images.githubusercontent.com/19143190/103705241-af42ea00-4f78-11eb-9025-d57f0a5b4a84.png)

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @gglobalstep!

I tested this further on my end. What I am seeing is that the issue of the notice being truncated only happens if the notice is one very long word which is unlikely to happen:

![Screen Shot 2021-01-05 at 5 12 56 PM](https://user-images.githubusercontent.com/19143190/103705694-80794380-4f79-11eb-9339-6ece91553916.png)

If the notice is a combination of several words, it is being properly wrapped. 

**2021:**

![Screen Shot 2021-01-05 at 5 11 32 PM](https://user-images.githubusercontent.com/19143190/103705780-aacb0100-4f79-11eb-9dc9-5ee3fa4e6d2e.png)

**2020:**

![Screen Shot 2021-01-05 at 5 11 17 PM](https://user-images.githubusercontent.com/19143190/103705794-b1f20f00-4f79-11eb-9dc1-4496933839c5.png)

**Storefront:**

![Screen Shot 2021-01-05 at 5 10 42 PM](https://user-images.githubusercontent.com/19143190/103705813-b8808680-4f79-11eb-98e1-8900de6c9da3.png)

This issue with the notice being not wrapped correctly if a very long word is being used seems to be an edge case which is why I am giving it a low priority. 

Regarding the issue with the `Dismiss` button being of low contrast in 2020 and 2021 themes - I will go ahead and create a separate issue for this so we could address it separately. I am updating the title of this issue to reflect only the store notice being truncated issue.

**Comment by rrennick** [comment]
I believe this has been addressed.
