### ISSUE TITLE
Programmatically updating an existing product download URL/name does not work

### ISSUE THREAD

**Issue by psaikali** [woocommerce/woocommerce#28705]
Hi,

I need to programmatically update an existing product download URL and name, so that past orders can still download the new file.

Here is my code:
```php
class Update_Product {
	public function get_new_downloads() {
		$downloads = $this->get_product()->get_downloads( 'edit' );
		$updated   = false;

		foreach ( $downloads as $download ) {
			// Only update first download.
			if ( $updated ) {
				continue;
			}

			$download->set_name( basename( $this->get_csv_url() ) );
			$download->set_file( $this->get_csv_url() );
			$updated = true;
		}

		return $downloads;
	}

	public function update() {
		$some_product = wc_get_product( 123 );
		$some_product->set_downloads( $this->get_new_downloads() );
		$some_product->save();
	}
}
```

The above code does not work: the download name/URL stays unchanged.

I notice that the `_downloadable_files` metadata only gets updated if the downloads array actually change. Updating an existing download item (without modifying its UID) does not trigger the `_downloadable_files` metadata update.

---

To trick WooCommerce, I'm currently doing the following:
- add a fake download item to the array, 
- save the product, removing the last download item,
- remove the last download item from the array,
- save the product again.

It looks like that:
```php
class Update_Product {
	public function get_new_downloads( $with_fake = false ) {
		$downloads = $this->get_product()->get_downloads( 'edit' );
		$updated   = false;

		foreach ( $downloads as $download ) {
			// Only update first download.
			if ( $updated ) {
				continue;
			}

			$download->set_name( basename( $this->get_csv_url() ) );
			$download->set_file( $this->get_csv_url() );
			$updated = true;
		}

		if ( $with_fake ) {
			$test_download = new \WC_Product_Download();
			$test_download->set_id( wp_generate_uuid4() );
			$test_download->set_name( 'Temporary new download' );
			$test_download->set_file( $this->get_csv_url() . '?' . time() );

			$downloads[] = $test_download;
		} else {
			$test_download = array_pop( $downloads );
		}

		return $downloads;
	}

	public function update() {
		$some_product = wc_get_product( 123 );
		
		$some_product->set_downloads( $this->get_new_downloads( true ) );
		$some_product->save();
		
		$some_product->set_downloads( $this->get_new_downloads( false ) );
		$some_product->save();
	}
}
```

This seems to work fine, but it's obviously not optimal.

I've tried to reverse engineer this and find the reason why this is happening, but with no success so far.

Thank you!

**Comment by psaikali** [comment]
```php
$some_product->set_downloads( $this->get_new_downloads( true ) );
$some_product->set_downloads( $this->get_new_downloads( false ) );
$some_product->save();
```

Not saving between the hacky-update and the normal-update works too.
Still not ideal, but maybe this could help :)

**Comment by kevinruscoe** [comment]
Does your code work?

`$some_product = wc_get_product( 123 );` gets product 123 and assigns it to $some_product.

`$this->get_new_downloads()` this calls `$this->get_product()`, but ->get_product() doesn't exist.

Should `$some_product = wc_get_product( 123 );` be `$this->product = wc_get_product( 123 );`? and `$this->get_product()` be `$this->product`?

**Comment by kevinruscoe** [comment]
```php
class Update_Product {
    private $product;

	public function get_new_downloads() {
		$downloads = $this->product->get_downloads( 'edit' );

        $download[0]->set_name( basename( $this->get_csv_url() ) );
        $download[0]->set_file( $this->get_csv_url() );

		return $downloads;
	}

	public function update() {
		$this->product = wc_get_product( 123 );
		$this->product->set_downloads( $this->get_new_downloads() );
		$this->product->save();
	}

    public function get_csv_url() {
        // TODO
    }
}
```

Does this make more sense? Unless you've heavily edited your sample.

**Comment by psaikali** [comment]
Yes, sorry, I edited my code to make it more understandable here.
(original = https://media.mosaika.fr/rRu0mjgg)

**Comment by kevinruscoe** [comment]
Having a dig into this, you're right. If you don't update the id (with $download->set_id()) it doesn't get updated. A simple work around is to clear the downloads just before writing to it, so when you write to it, it has nothing to compare it to.

```php
$this->product->set_downloads([]);
$this->product->set_downloads( $this->get_new_downloads() );
```

**Comment by psaikali** [comment]
Thanks @kevinruscoe!
But I need to update the (existing) first product URL, so by setting an empty array, I will NOT be able to target it here:
![Capture 2021-01-01 à 17 24 26](https://user-images.githubusercontent.com/1606655/103442413-3846e200-4c56-11eb-81a5-734c5f61c4ac.jpg)

Right?

**Comment by psaikali** [comment]
The `->get_downloads()` would return an empty array I guess?

**Comment by kevinruscoe** [comment]
Set it to empty just before you call ->set_downloads(), so in your first example, it's the update function. So, something like

```php
public function update() {
	$some_product = wc_get_product( 123 );
	$new_downloads = $this->get_new_downloads();
	$some_product->set_downloads( array() );
	$some_product->set_downloads( $new_downloads );
	$some_product->save();
}
```

**Comment by kevinruscoe** [comment]
The problem lies at https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1210 if checks to see if what you're updating is already a download, if it is, skip editing it.

Another weird fix is 

```php
$buffer = [];
array_unshift($downloads, $buffer);
$product->set_downloads( $downloads );
```

Or, take a look at https://github.com/woocommerce/woocommerce/blob/master/includes/rest-api/Controllers/Version1/class-wc-rest-products-v1-controller.php#L951 which is they do it internally.

**Comment by psaikali** [comment]
Thanks @kevinruscoe.
Not really sure if this is expected behavior or a bug... should I close this?
I guess that the `set_downloads()` method should work in any case IMO.

**Comment by kevinruscoe** [comment]
Leave it open, I've managed to track what's going on. I'm hoping someone else will be able to help, or clear stuff up.

Basically, when you're using `$product->get_downloads()` and loop through them and change any of the values, you're effectively writing to 'downloads' prop on the product (not entirely sure why, it almost seems like it's a reference to the products downloads prop). So, when you call `set_downloads()`, internally it compares what's there to what you're setting it to. But, because you're writing directly to it, when the comparison is made, it sees no changes (they're already the same). So the data stores' `->changes[]` array doesn't contain the new data, so it doesn't write it to the database.

This is why changing the downloads array slightly works (either setting it to a blank array, then using `->set_dowloads()`, or appended to the array).

To successfully rewrite a new set of amended downloads, you need to create a new array, copying over the previous ones, like:

```php
$product = wc_get_product( 19 );
$downloads = $product->get_downloads();

$new_downloads = [];

foreach ($downloads as $download) {
	$new_download = new WC_Product_Download;
	$new_download->set_id( $download->get_id() );
	$new_download->set_file( $download->get_file() );
	$new_download->set_name( "test 1" );

	$new_downloads[] = $new_download;
}

$product->set_downloads($new_downloads);

$product->save();
```

When the `set_prop()` is then ran, and the comparison is made, it notices the difference and marks it as dirty.

There's 4 solutions really. 

1. Ensure when writing to `set_downloads()` you're using a new array.
2. Somehow ensure when `get_prop()` returns an array, clone it, don't reference it. 
3. During the comparision, if the thing you're comparing is an array, mark it as dirty regardless of it has changes and add it to changes[] array.
4. When `$this->set_prop( 'downloads', $downloads );` is ran, run `$this->set_prop( 'downloads', array() )`; beforehand to ensure it marked as dirty.

**Comment by psaikali** [comment]
Thanks for your help Kevin. Hopefully, this will gets fixed in WC core!

**Comment by kevinruscoe** [comment]
Further findings after a good nights sleep, the referece does make sense. When you use `get_downloads()` you get an array of Objects (`WC_Product_Download`) which are referencing them. So editing the underlining Object is updating the value with array. This is proved with a simple test.

```
<?php

class _Parent {
	public $children = [];

	public function addChild(_Child $child)
	{
		$this->children[] = $child;
	}

	public function getChildren()
	{
		return $this->children;
	}
}

class _Child {
	public $name;

	public function setName($name)
	{
		$this->name = $name;
	}
}

$kevsDad = new _Parent;

$kev = new _Child;
$kev->setName('Kev');

$kevsDad->addChild($kev);

var_dump($kevsDad->getChildren());

$kev->setName('Kevin');

var_dump($kevsDad->getChildren());
```

The first dump returns 

```
array(1) {
  [0]=>
  object(_Child)#2 (1) {
    ["name"]=>
    string(5) "Kev"
  }
}
```

and the second dump returns

```
array(1) {
  [0]=>
  object(_Child)#2 (1) {
    ["name"]=>
    string(5) "Kevin"
  }
}
```.

I think the fix is to check if the new prop is an array, and if it is, force it to be updated in the set_props method.

I'll whip up a PR.

**Comment by rrennick** [comment]
@psaikali Have you tried the [update download links](https://wordpress.org/plugins/ach-update-woo-download-links/) extension? This functionality was intentionally removed from WooCommerce 3.0.
