### ISSUE TITLE
Fatal Error from pre orders when viewing subscription events by date report

### ISSUE THREAD

**Issue by benbodhi** [woocommerce/woocommerce#28744]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When trying to view the subscription sales by date tab under WooCommerce > Reports with WooCommerce Pre-Orders active, there is a fatal error:
Fatal error: Uncaught Error: [] operator not supported for strings in wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-order.php on line 104

**Expected behavior**
I would expect there to be no fatal error and be able to view the report.

**Actual behavior**
When trying to view this report page, I get a fatal error.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Can reproduce with WooCommerce, WooCommerce Subscriptions and WooCommerce Pre-Orders active only.
2. Go to 'WooCommerce > Reports > Subscription sales by date'
3. Fatal error

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @benbodhi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Pre-Orders plugin (according to the Fatal Error you shared) which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.

**Comment by benbodhi** [comment]
Ok, no worries. I just saw pre orders bug reports on here before.
I'll go through the website.
