### ISSUE TITLE
Billing County is copied into Shipping Address

### ISSUE THREAD

**Issue by michja** [woocommerce/woocommerce#28759]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If your billing address has a county but shipping address doesn't then that field gets copied over and merged into the shipping address.

I have tested this on two live sites with very different setups running the latest woo (4.8.0).
Also tested on 4.0.1 which does not have this behaviour.
And tested on a totally fresh demo site (4.8.0) at http://woocommerce.oxwebdev.com/ - feel free to test here

**Expected behavior**
Billing fields should never be merged into a shipping address.

**Actual behavior**
A single field (County) is merged from billing to shipping, creating an invalid shipping address

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. Create a new account
2. Add a billing address including a county
3. Add a shipping address without a county
4. Attempt to buy an item
5. Merge is visible on the cart screen and also in the inputs that are revealed when toggling "Ship to a different address"

**Screenshots**

![screen-2021-01-08_12-40-04](https://user-images.githubusercontent.com/30815899/104017167-87899700-51af-11eb-93d4-d02ca88425be.png)

![screen-2021-01-08_12-40-24](https://user-images.githubusercontent.com/30815899/104017179-8c4e4b00-51af-11eb-9574-5e8a615df1c7.png)

![screen-2021-01-08_12-40-46](https://user-images.githubusercontent.com/30815899/104017183-8f493b80-51af-11eb-80ac-084a84f5d152.png)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://woocommerce.oxwebdev.com/wp
Site address (URL): http://woocommerce.oxwebdev.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ❌ To allow logging
make /var/www/woocommerce.oxwebdev.com/woocommerce/web/app/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.24-0ubuntu0.18.04.6
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.18.04.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 4.68MB
Database Data Size: 2.88MB
Database Index Size: 1.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

customize_changeset: 1
page: 10
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.8.0
Wordfence Security: by Wordfence – 7.4.14

### Must Use Plugins (3) ###

Bedrock Autoloader: by Roots – 1.0.3
Disallow Indexing: by Roots – 1.0.0
Register Theme Directory: by Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #10 - /index.php/shop/
Cart: #11 - /index.php/cart/
Checkout: #12 - /index.php/checkout/
My account: #13 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 5
Oldest: 2021-01-07 14:48:37 +0000
Newest: 2021-01-08 12:40:35 +0000

`
</details>

**Comment by juliaamosova** [comment]
Hi @michja,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. The County field value entered in the Shipping Address doesn't get copied to the Billing Address on my end. 

I have tried with Billing Address to be in the US and in the UK as well. Please see details below:

**US Billing Address + UK Shipping Address:**

![us - no county - 1](https://user-images.githubusercontent.com/19143190/104137274-a6338d80-5369-11eb-92fb-5939ab06aa05.jpg)

![uk-county - 2](https://user-images.githubusercontent.com/19143190/104137279-a9c71480-5369-11eb-905b-976c68f70ce7.jpg)

![us-uk-good](https://user-images.githubusercontent.com/19143190/104137290-ae8bc880-5369-11eb-99b0-17e207f939af.jpg)

**UK Billing Address + UK Shipping Address:**

![uk-county - 3](https://user-images.githubusercontent.com/19143190/104137306-b51a4000-5369-11eb-8ccd-0842cf96f380.jpg)

![uk-county - 4](https://user-images.githubusercontent.com/19143190/104137311-b8adc700-5369-11eb-8dea-93523430279f.jpg)

![uk-uk-good](https://user-images.githubusercontent.com/19143190/104137315-bf3c3e80-5369-11eb-8485-3e6dfc401479.jpg)

I understand that you already performed themes and plugins conflict. Can you think of anything in your setup that I can try in order to replicate the issue? I am using WooCommerce 4.8, WP 5.6, and the 2021 theme.

**Comment by michja** [comment]
Hi Julia,

Thanks for looking into this. 
Try the other way around. 
It's the billing county which gets copied into shipping.

Michael

**Comment by michja** [comment]
Please can someone remove the "can't reproduce" tag on this issue.
That was added in error and I'm worried its stopping the issue being looked at

**Comment by barryhughes** [comment]
Circling back to this, there seem to be two separate issues described above (though, it so happens they both impact the shipping address).

**Billing County is copied into Shipping Address** → This is the original issued described by the reporter: the problem here is that if the shipping address has 'gaps' then we try to fill them using the corresponding data from the billing address. This applies to both the [state/county field](https://github.com/woocommerce/woocommerce/blob/5.1.0/includes/data-stores/class-wc-customer-data-store-session.php#L134-L136) _and,_ at least theoretically, the [country field](https://github.com/woocommerce/woocommerce/blob/5.1.0/includes/data-stores/class-wc-customer-data-store-session.php#L142-L144) (though in most cases it will only be seen in relation to the state/county field, in those contexts where that field is optional). I have a fix drafted for this problem and propose we keep this issue focused on that specifically.

**Billing Address used for Shipping Address for Virtual Products** → So @zhongruige I think this further issue _('Perhaps more problematically, I clicked "Ship to different address" and noticed that the entire billing information was carried over')_ is a separate thing that only happens when **Settings ‣ Shipping Options ‣ Shipping Destination** is set to **Default to customer billing address** ... can you confirm? If so, I recommend we split it out into its own ticket.

:memo: _Note that if you test that second issue you'll want to make sure you completely clear the user session each time you modify the shipping destination setting._

**Comment by zhongruige** [comment]
Hi @barryhughes,

Thanks for following up!

> is a separate thing that only happens when Settings ‣ Shipping Options ‣ Shipping Destination is set to Default to customer billing address

Good call out--I verified that is the case only when doing that flow. Perhaps it is less of a bug more of a slight confusion on how that works from the customer's perspective if they aren't expecting it.

**Comment by barryhughes** [comment]
Yep could be. 

It does seem a little confusing to allow a customer to specify a shipping address, then default to the billing address (there's probably some historic context I'm missing there, but it makes me wonder if a setting like _Default to Billing Address if Shipping Address not set_ might make sense as an alternative or additional option).

Beyond that, there does seem to be some squirrelliness happening with `Default to Customer Billing Address`, at least based on some quick testing I did earlier on. For instance:

- Add a shippable item to the cart.
- Cart page shows the _shipping_ address (unexpected, I'd think).
- Proceed to checkout but change nothing.
- Back to the cart page: the _billing_ address now displays (makes sense, but why didn't it happen first time round?).

**Comment by shameemreza** [comment]
Another report: 8602432-zen
Thread: https://wordpress.org/support/topic/saved-shipping-address-gets-overwriten-by-billing-address/

**Comment by barryhughes** [comment]
Hi @shameemreza! This bug was closed following the merge of https://github.com/woocommerce/woocommerce/pull/29605, around 3 years ago. If people are reporting this is still an issue, can you create a fresh bug report with updated steps to replicate, confirmation it can be observed when no other plugins are present, etc?

**Comment by shameemreza** [comment]
Hi @barryhughes 

Yes, I will do it. We've just received one report so far, and I haven't been able to replicate the issue yet. I'll keep a close eye on it. If we receive more reports and I can reproduce the issue, I'll definitely create a new report.
