### ISSUE TITLE
Pay for $0 order in my account (order-pay page) is not possible anymore

### ISSUE THREAD

**Issue by sgoifo** [woocommerce/woocommerce#28761]
Hello to everyone!

Before the last update, it was possible to pay for orders that are $0. I know this maybe makes no sense for you but there are a few applications to this feature.

I found the problem in the file wp-content\plugins\woocommerce\includes\class-wc-form-handler.php

![image](https://user-images.githubusercontent.com/45824980/104042539-675ed580-51b9-11eb-89ad-13a40b28a959.png)

As you can see in the screenshot the first highlighted IF make it not possible to send an order with $0 amount, thanks to the $order->needs_payment()

But this doesn't make sense since there a second IF inside that also checks if the order needs payment or not. I cannot use the second IF anymore since you added $order->needs_payment() in the first IF.

Of course, I only want to use the ELSE part of the second IF:

![image](https://user-images.githubusercontent.com/45824980/104042903-d0dee400-51b9-11eb-8cd9-b9403250fd34.png)

What can I do to avoid this behavior?

Thank you very much!

**Comment by kevinruscoe** [comment]
`$order->needs_payment()` is defined at https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1497

It returns the filtered value of `woocommerce_order_needs_payment` which should be a bool. So, you could use this filter to return true instead of false for $0 orders.

**Comment by sgoifo** [comment]
Hey @kevinruscoe , but I won't be able to use the second IF statement if $order->needs_payment() returns true. Right?
Thank you very much!

**Comment by kevinruscoe** [comment]
Ohhh, I see your problem now, and you're right it doesn't make sense. It looks like it became broke at https://github.com/woocommerce/woocommerce/commit/164b39ea428b1d72f1db81aa3e3720d736304f90?branch=164b39ea428b1d72f1db81aa3e3720d736304f90&diff=split

That first call to needs_payment() needs to be reverted because the function does too much. It

1. First checks to see if it has a certain status
2. Also checks if the order value is > 0

Where as the original code just checked for the statuses, then checked the order value within the loop.

I'll whip up a PR to revert it. In the interim, here's a hacky solution that may work.

1. Make sure needs_payment() returns true using a filter. 
2. When the 'woocommerce_before_pay_action' action is called, call your own function that mimic the code that's running at https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L453 and https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L401 (if you need to save the customer).

As long as you exit, it shouldn't run the second IF ELSE.

**Comment by roykho** [comment]
Hmm I am not sure if that is issue because OP said this started happening after the latest update but the commit https://github.com/woocommerce/woocommerce/commit/164b39ea428b1d72f1db81aa3e3720d736304f90?branch=164b39ea428b1d72f1db81aa3e3720d736304f90&diff=split happened a long while ago?

**Comment by sgoifo** [comment]
@kevinruscoe thank you for taking the time to look at this, I'll follow your recommendation to try to solve this issue!
@roykho actually I'm not sure if this started after the last update, I actually updated the plugin after several months, and the customization I installed on a customer website stopped working due to this. (I need to make the website's users pay for $0 orders in some cases).

Thank you very much guys!

**Comment by peterfabian** [comment]
Hi @sgoifo !

Can I close the issue or do you want us to treat it as an enhancement request?

**Comment by barryhughes** [comment]
We'll go ahead and close, but let us know if you disagree.

As a possible alternative, note that it may be possible to hook into the `wp` action (which is how the `WC_Form_Handler::pay_action()` itself is invoked), detect that a zero-dollar order is being processed, and then run code equivalent to that which lives within the inner `else {}` clause you were trying to target.
