### ISSUE TITLE
[GlobalStep - WooCommerce 4.9 RC 2][IE 11] For Twenty Twenty One theme, radio buttons are not visible on Checkout page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28783]
## Bug Description:
For Twenty Twenty One theme, radio buttons are not visible on Checkout page.

## Environment:
Windows 10
Browser: IE11(Version:11.1139.18362.0)
                
 ## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard.
1. Select Twenty Twenty One theme.
1. Add Some products.
1. Go to frontend.
1. Add any products to the Cart.
1. Go to Checkout page.
1. Observe that radio buttons are not visible on Checkout page.

## Actual Result:
For Twenty Twenty One theme, radio buttons are not visible on Checkout page.
 
## Expected Result:
Radio buttons should be visible on Checkout page.

## Screenshots:

![#28783](https://user-images.githubusercontent.com/41110392/104200274-7611ea80-544e-11eb-9129-e213b3ee66e7.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Tested using Browserstack with Windows 10 and IE 11:

![checkout](https://user-images.githubusercontent.com/19143190/104219966-ce27fd00-540c-11eb-8275-610461a18005.jpg)

Note that it is still possible to place an order. The user will need to click on the name of the payment method, however. 

We chatted about this with @vedanshujain and @peterfabian and decided to include it in WC 5.0. 

The issue seems to be related to this change in WP Core: https://core.trac.wordpress.org/ticket/52040.

**Comment by Camilo517** [comment]
Why do you spend time making internet explorer compatible? Who uses that browser in 2021?

**Comment by juliaamosova** [comment]
>Why do you spend time making internet explorer compatible? Who uses that browser in 2021?

@Camilo517 while the usage of IE is low among our customers, we are still a part of the WordPress ecosystem. [WordPress currently provides support for `Internet Explorer >= 11`](https://make.wordpress.org/core/handbook/best-practices/browser-support/) which is why we are also making WooCommerce IE compatible.

**Comment by peterfabian** [comment]
IE 11 is no longer supported in WP: https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/
