### ISSUE TITLE
js change event not triggered on ".woocommerce-variation-price"

### ISSUE THREAD

**Issue by arenonana** [woocommerce/woocommerce#28793]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I used this code but it's not working :

```
jQuery(document).ready(function ($) {
    $('.woocommerce-variation-price').on('change', function () {
        alert('IT S CHANGED');
    });
});
```

**Comment by tammullen** [comment]
Hi @arenonana 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 
​
The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
​
If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
