### ISSUE TITLE
Unable to run stock report in Woocommerce Reports

### ISSUE THREAD

**Issue by mrnmnew** [woocommerce/woocommerce#28863]
Can anyone help?
When I try to run the stock level report it fails with a critical error and the log gives :

2021-01-20T14:56:16+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on string in /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php:81
Stack trace:
#0 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1439): WC_Report_Stock->column_default(Object(stdClass), 'product')
#1 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1379): WP_List_Table->single_row_columns(Object(stdClass))
#2 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1366): WP_List_Table->single_row(Object(stdClass))
#3 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1351): WP_List_Table->display_rows()
#4 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1278): WP_List_Table->display_rows_or_placeholder()
#5 /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php(68): WP_List_Table->display()
#6 /home/orkneyar/public_html/shop/ in /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php on line 81

**Comment by lsinger** [comment]
Hi @mrnmnew,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by lsinger** [comment]
@mrnmnew thanks for those details. I tried reproducing this issue with an empty site -- latest WordPress, WooCommerce 4.9.1 (just as yours) and no products. I then added a few products and added different levels of stock to them. 

However, this all worked fine on my end. Do you have a few more details about the products and stock levels in your store that could help us get to the bottom of this? 

Alternatively you might want to try reproducing the issue on a fresh testing site. That way you'd be able to share with us the exact steps to reproduce the issue.

**Comment by mrnmnew** [comment]
It works fine on my other sites.
Does this error message help?

An error of type E_ERROR was caused in line 81 of the file /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php. Error message: Uncaught Error: Call to a member function get_id() on string in /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php:81
Stack trace:
#0 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1439): WC_Report_Stock->column_default(Object(stdClass), 'product')
#1 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1379): WP_List_Table->single_row_columns(Object(stdClass))
#2 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1366): WP_List_Table->single_row(Object(stdClass))
#3 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1351): WP_List_Table->display_rows()
#4 /home/orkneyar/public_html/shop/wp-admin/includes/class-wp-list-table.php(1278): WP_List_Table->display_rows_or_placeholder()
#5 /home/orkneyar/public_html/shop/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php(68): WP_List_Table->display()
#6 /home/orkneyar/public_html/shop/

**Comment by mrnmnew** [comment]
on another site I look after when I select 'most stocked' report I get a simular error

**Comment by juliaamosova** [comment]
Hi @mrnmnew,

Thank you for your follow-up and for providing additional details. I am sorry for the delayed response here. 

I tested this further as well using WooCommerce 5.3 beta and did not experience the issue. 

>It works fine on my other sites.

You noted that the issue is present for you only on some of the sites but not the others. It could be that one of the plugins you are using on the sites where the issue is present is causing the issue. 

You shared your System Status Report above where I see that you have several plugins installed. Please test your site for plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce. Then test again.

If the issue is resolved with the default theme (which is Storefront and I see you are using it) and all plugins deactivated, it means that one of your plugins. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Please let us know how it goes.
