### ISSUE TITLE
Activating a plugin loads forever if wc_remote_inbox_notifications_specs option is not set.

### ISSUE THREAD

**Issue by admsa** [woocommerce/woocommerce#28915]
Hi, 

Activating any plugin while woocommerce is enabled causes the plugins.php page to load forever. After my investigation I found out that `update_option( RemoteInboxNotificationsEngine::SPECS_OPTION_NAME, $specs );` isn't working. I'm assuming that it's because of the unicode characters from `https://woocommerce.com/wp-json/wccom/inbox-notifications/1.0/notifications.json` file.

**Comment by hedqvist** [comment]
After implementing the workaround suggested here:
https://github.com/woocommerce/woocommerce-admin/issues/6168

I got this working. Seems like an issue coming from last update.

**Comment by DesignInvento** [comment]
Hi,
A simple fix would can be implement by adding option to wp_options table
if (!get_option('wc_remote_inbox_notifications_specs')){
    add_option('wc_remote_inbox_notifications_specs', '');
}

proposed fix for next update:
A conditions should be added to check if wc_remote_inbox_notifications_specs exists in run method

**Comment by tammullen** [comment]
Hi All,
Thanks for raising this issue, we are looking into it, stay tuned for updates.

This issue is primarily being discussed in the WooCommerce Admin repository as early signs are pointing towards usage of the Remote Inbox System which is developed there.
woocommerce/woocommerce-admin#6168

It had also been reported previously here https://github.com/woocommerce/woocommerce/issues/28911 . We are closing this issue in favor of the previously submitted. 

Please continue sharing your feedback there if needed.
