### ISSUE TITLE
After editing and saving product, get asked if I would leave page in Safari on Mac

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#28963]
I have this issue I think since WC 4.6 or 4.7 (I don't remember exactly). If I edit a product and save it, I get a notice on top of title that product is saved. If I leave product window for going to dashboard or viewing product in frontend, a popup window opens and asks me if I am sure leaving that page.

That should only happen if I had edited product but did not save.

I checked this behavior about on different sites of mine and clients too with really different configurations and plugins. This message asking me about shows only after editing products, not pages or posts. And it comes up random but most often.

![Bildschirmfoto 2021-01-27 um 19 25 00](https://user-images.githubusercontent.com/3390880/106036289-6b558780-60d5-11eb-80e4-897050d50bd5.png)

I use Safari on Mac version 14.x

**Comment by tammullen** [comment]
Hi @ajgw 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/28557. We are closing your issue in favor of the previously submitted. 
Note this is a WordPress core issue. The fix is planned to be released in WordPress 5.6.1.
