### ISSUE TITLE
Chyba po aktualizaci

### ISSUE THREAD

**Issue by arnost649** [woocommerce/woocommerce#29055]
Po aktualizaci na verzi 1.2.14 ze dnešního dne se nezobrazí žádné volby, kromě seznamu funkcí ve vertikálním menu, viz print screen
https://ibb.co/723fgWT

**Comment by tammullen** [comment]
Hi @arnost649 

Please note that we reply to bug reports in English language only. I used Google Translate to translate your message. You can use the same to translate my reply back.

Translation of the title:

> Error after update

Translation of the issue description:

> After updating to version 1.2.14 from today, no options will be displayed, except for the list of functions in the vertical menu, see print screen

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party plugin WPify Woo Czech (I'm making the assumption that it is this plugin from your screenshot and your reference to a version number 1.2.14 which matches a version number of that plugin from earlier today). 
​
Please contact the author of the plugin directly for further help.
