### ISSUE TITLE
Composer installation results in an empty /packages directory

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#29078]
Hello!

I cannot release WC stubs v4.9.2 and v5.0.0 as after `composer update` [the /packages directory](https://github.com/woocommerce/woocommerce/tree/master/packages) remains empty.
https://github.com/php-stubs/woocommerce-stubs/releases

```json
{
    "require": {
        "php": "~7.1",
        "ext-gettext": "*",
        "ext-hash": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "woocommerce/woocommerce": "4.9.2"
    },
    "minimum-stability": "stable",
    "extra": {
        "installer-paths": {
            "{$name}/": [
                "type:wordpress-plugin"
            ]
        }
    }
}
```

Please help me.

**Comment by szepeviktor** [comment]
I know many work-arounds but interested in a sustainable solution.

**Comment by szepeviktor** [comment]
@claudiosanches Please help me. I cannot release stubs.

**Comment by szepeviktor** [comment]
Thank you @tammullen! I'm thinking about closing my project as the WC release process seems unpredictable to me.

**Comment by ObliviousHarmony** [comment]
Howdy @szepeviktor,

This set of `installer-paths` will fix your problem:

```json
{
    "extra": {
        "installer-paths": {
            "woocommerce/": [
                "woocommerce/woocommerce"
            ],
            "woocommerce/packages/{$name}": [
                "woocommerce/action-scheduler",
                "woocommerce/woocommerce-blocks",
                "woocommerce/woocommerce-admin"
            ]
        }
    }
}
```

As far as an explanation goes this is a consequence of two factors:

1. The contents of the `packages` directory have an installer type of `wordpress-plugin`. Your previous `installer-paths` setting indicates that they should be moved to the top-level, which they are. Since only the consumer's `composer-installer` settings matter we can't actually install those packages into the sub-directory. You can place them manually though as demonstrated above.
2. We changed to a new release script that does not tag a package with all of the `composer` dependencies installed. You'll note that with 4.8.0 for instance that the `woocommerce/vendor` folder contains all of the dependencies even though `composer install` will have duplicated them in the top-level `vendor` folder.

While it's true that we need to address this more extensively in our build process I don't believe you'll experience any more problems with the above config.

**Comment by szepeviktor** [comment]
Thank you. I do as you say.

**Comment by szepeviktor** [comment]
@ObliviousHarmony Lastly installed WC seems to overwrite those 3 packages ending up with an empty `/packages` directory.

`composer-v1 update -v`

```
 Extracting archive  - Installing composer/installers (v1.10.0): Loading from cache
 Extracting archive  - Installing woocommerce/woocommerce-blocks (v4.0.0): Loading from cache
 Extracting archive  - Installing woocommerce/woocommerce-admin (1.8.3): Loading from cache
 Extracting archive  - Installing woocommerce/action-scheduler (3.1.6): Loading from cache
 Extracting archive  - Installing psr/container (1.0.0): Loading from cache
 Extracting archive  - Installing symfony/css-selector (v5.2.3): Loading from cache
 Extracting archive  - Installing pelago/emogrifier (v3.1.0): Loading from cache
 Extracting archive  - Installing maxmind-db/reader (v1.6.0): Loading from cache
 Extracting archive  - Installing automattic/jetpack-constants (v1.5.1): Loading from cache
 Extracting archive  - Installing woocommerce/woocommerce (4.9.2): Loading from cache
```

A second run puts those 3 packages into `/packages`.
I am very sad. Please help me.

**Comment by szepeviktor** [comment]
`composer2 update -v`

```
  - Installing composer/installers (v1.10.0): Extracting archive
  - Installing automattic/jetpack-autoloader (v2.7.1): Extracting archive
  - Installing symfony/css-selector (v5.2.3): Extracting archive
  - Installing woocommerce/woocommerce-blocks (v4.0.0): Extracting archive
  - Installing woocommerce/woocommerce-admin (1.8.3): Extracting archive
  - Installing woocommerce/action-scheduler (3.1.6): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing pelago/emogrifier (v3.1.0): Extracting archive
  - Installing maxmind-db/reader (v1.6.0): Extracting archive
  - Installing automattic/jetpack-constants (v1.5.1): Extracting archive
  - Installing woocommerce/woocommerce (4.9.2): Extracting archive
```

```
drwxr-xr-x 5 viktor viktor 4096 May 12  2020 action-scheduler
drwxr-xr-x 2 viktor viktor 4096 Jan 25 14:41 packages
drwxr-xr-x 9 viktor viktor 4096 Jan  6 00:00 woocommerce-admin
drwxr-xr-x 7 viktor viktor 4096 Dec  8 13:17 woocommerce-blocks
```

Composer v2 - which I'm not daring enough to use yes - created these, `packages/packages/` is empty.

**Comment by ObliviousHarmony** [comment]
@szepeviktor Sorry, I'm using `v2` and can't speak to a `v1` solution. It isn't ideal but perhaps if you added those dependencies to your `require` key (ordered after `woocommerce/woocommerce` with the same versions as the corresponding release) it wouldn't squash the packages? As for the extra directory this shouldn't be a concern as its empty.

**Comment by szepeviktor** [comment]
Thank you for your answers.

**Comment by imonteiro** [comment]
Hi,

Since 4.9.2 I'm having the same issue. After reading this issue, there is my steps:

Add extra `installer-paths`:
```
"extra": {
    "installer-paths": {
      "web/app/plugins/woocommerce/": [
        "woocommerce/woocommerce"
      ],
      "web/app/plugins/woocommerce/packages/{$name}": [
          "woocommerce/action-scheduler",
          "woocommerce/woocommerce-blocks",
          "woocommerce/woocommerce-admin"
      ]
}
```

Set all packages at composer:
```
    "woocommerce/woocommerce": "5.2.2",
    "woocommerce/woocommerce-blocks": "4.7.2",
    "woocommerce/woocommerce-admin": "2.1.5",
    "woocommerce/action-scheduler": "3.1.6",
```

A second run puts those 3 packages into `/packages`. However, Woocomerce class is not found as referred at #29011 :

```
Fatal error: Uncaught Error: Class 'WooCommerce' not found in C:\...\app\site\web\app\plugins\woocommerce\woocommerce.php on line 47
```

It's there some solution? (I'm using composer 2.0.12)

Thanks in advance.
