### ISSUE TITLE
woocommerce update error

### ISSUE THREAD

**Issue by haroonstar77** [woocommerce/woocommerce#29084]
juts upgraded my woocommerce plugin, my site becomes inaccessible, neither wp admin nor website. error message a critical error.
tried renameing plugin folder with ftp, site and wp admin comes back, but as soon as i try to install the woocommerce, it's not successful. tried downgrading woocommerce and uploading it through ftp. same error. 

please help me to recover from this situation.

**Comment by tammullen** [comment]
Hi @haroonstar77 

Do you have any other details in the error message you can paste here? Can you check if you have any emails from your site that contain Error Details?

This kind of problem is usually caused by a conflict with your theme or with another plugin.
 
The best way to determine this is to:

Temporarily switch your theme to [Storefront](https://www.woocommerce.com/storefront/)
Disable all plugins except for WooCommerce
Repeat the action that is causing the problem
If you’re not seeing the same problem after completing the conflict test, then you know the problem was with the plugins and/or theme you deactivated. To figure out which plugin is causing the problem, reactivate your other plugins one by one, testing after each, until you find the one causing conflict. [You can find a more detailed explanation on how to do a conflict test here.](https://docs.woocommerce.com/document/how-to-test-for-conflicts/)

**Comment by haroonstar77** [comment]
the error message is * your site has encountered a critical error please check your email for debugging options*, and  I don't receive any email. I renamed the plugin folder through ftp to *plugin-old* and created a new folder name *plugin*. At this point everything works fine, I am able to login and and access my site. as soon as I install the woocommerce, the error comes back and won't let me access wp-admin. There is no other plugin installed. I will try the option you proposed (swithing theme) to switch the theme with storefront and will come back to you with updates. Thanks for your reply

**Comment by claudiosanches** [comment]
Hello @haroonstar77,

Could you please enable WP debugging mode, so we could have some idea of what is causing it?
You can find instructions here: https://docs.woocommerce.com/document/woocommerce-product-search/api/debugging/

After enabling WP debugging mode you should try to navigate in `wp-admin` again with WooCommerce activated, it will fill the `wp-content/debug.log` file with information about the error that prevent you to load `wp-admin`.

Please let me know if you can do it and what shows up in the `debug.log` file.

**Comment by haroonstar77** [comment]
I followed the procedure you mentioned above. but wp is not creating any debug file. I stilll have same problem after trying all methods. 

![image](https://user-images.githubusercontent.com/67603220/107615292-2b051600-6c4c-11eb-9058-c749b6475986.png)

**Comment by claudiosanches** [comment]
@haroonstar77 if you enable correctly the WP debugging mode it should start filling the `wp-content/debug.log` file. Because onlyu with your screenshot isn't possible to determine what is wrong on your installation.

**Comment by haroonstar77** [comment]
@claudiosanches Finally i have found the problem, my SQL database was overloaded because it has reached the maximum limit. i cleaned up my database and everything comes back to normal. little strange but that's what it was.

**Comment by claudiosanches** [comment]
@haroonstar77 thanks for posting back. I'm glad that it helped you.
