### ISSUE TITLE
Cannot import multiple rows of attribute fields

### ISSUE THREAD

**Issue by a19901201** [woocommerce/woocommerce#29161]
When importing a CSV file with multiple lines in the attribute, line breaks cannot be displayed normally, and all lines will be treated as the same line.

**Comment by zhongruige** [comment]
Hi @a19901201,

Thank you for taking the time to report this. For us to investigate a little bit further, can you provide an example of how the new lines are being added in the CSV file?

Thank you!

**Comment by a19901201** [comment]
For example, this is the data before I export:
![image](https://user-images.githubusercontent.com/62532231/108628074-ab6d1780-7493-11eb-9c25-092566d04db5.png)

`資料儲存應用,"4 x SATA2.0 (3GB/s) 接口",1,0,內部I/O接口,"2 x USB 2.0擴充座，支援擴充2個USB 2.0接口
1 x USB 3.0擴充座，支援擴充2個USB 3.0接口
1 x CPU風扇接口（1 x 4針）
1 x 機殼風扇接口（1 x 4針）
1 x 24針EATX電源接口
1 x 8針ATX 12V電源接口
1 x 前面板音訊接頭（AAFP）",1,0,後I/O接口,"1 x PS/2鍵盤與滑鼠接口
1 x RJ-45埠 6 x USB 2.0接口
2 x USB 3.0接口
3 x 音源接口",1,0,`


But when I import it will become like this:
![image](https://user-images.githubusercontent.com/62532231/108628328-46b2bc80-7495-11eb-8227-57f89381ca01.png)

![image](https://user-images.githubusercontent.com/62532231/108628421-c80a4f00-7495-11eb-82f3-b94d4d3db11e.png)

**Comment by tammullen** [comment]
Hi @a19901201 ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further including a sample CSV file if possible.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
