### ISSUE TITLE
Can't Change Status of Facebook Sync

### ISSUE THREAD

**Issue by gqjesus** [woocommerce/woocommerce#29160]
In Woo -

The status of maybe 4 items (variants) is set to do not sync with Facebook, when I view each product they are set to sync.  When I try to bulk sync to Facebook, the status doesn't change.

**Comment by zhongruige** [comment]
Hi @gqjesus ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [Facebook for WooCommerce plugin](https://woocommerce.com/products/facebook/). To get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.

**Comment by gqjesus** [comment]
To me this sounds like a bug as the when you go to change a setting and nothing happens… seems buggy to me.
