### ISSUE TITLE
"Changes you made may not be saved." message when leaving ANY PAGE, even if no changes have been made #28557

### ISSUE THREAD

**Issue by nostradamuszen** [woocommerce/woocommerce#29185]
*Any action at all* (for example, Customise Site) produces the alert: "Leave site? Changes you made may not have been saved."

This was widely supposed to be a bug in WordPress 5.6.1 - however, I have upgraded to the Bleeding Edge beta of 5.7, and the infuriating problem persists, slashing our productivity in half.

However .... the problem PERSISTS with ALL plugins disabled - so this seems to rule out any problem with WooCommerce ... 

Any guidance would be much appreciated, as I am now having to consider nuking the entire site for morbid, and starting again from ground zero. 

With all plugins disabled, I can only surmise that possibly the theme I am using (Divi) has in some way corrupted the database files.

Many apologies if I am posting this with the wrong tags - but I am a desperate man facing broken_deadline_meltdown !!

![Screen Shot 2021-02-22 at 06 59 54](https://user-images.githubusercontent.com/653325/108676716-8fdc2e00-74e0-11eb-8f7e-7e728352eb49.png)
![Screen Shot 2021-02-22 at 07 22 58](https://user-images.githubusercontent.com/653325/108676719-9074c480-74e0-11eb-9b39-881b5a98e885.png)
![Screen Shot 2021-02-22 at 07 23 51](https://user-images.githubusercontent.com/653325/108676722-91a5f180-74e0-11eb-9b05-fc95b8dc01f3.png)

**Comment by juliaamosova** [comment]
Hi @nostradamuszen,

Thanks for bringing up this issue. It is indeed a WordPress issue though (not WooCommerce related). It is being worked on in the WP track ticket here: https://core.trac.wordpress.org/ticket/52440

It looks like the fix is scheduled to be released in WordPress 5.6.2. 

I am sorry to hear about all the troubles you've been having with it!

Since this is not a WooCommerce bug, I am going to close this thread.
