### ISSUE TITLE
do_shortcode('[woocommerce_checkout]') doesn't load all scripts

### ISSUE THREAD

**Issue by oliveiracom** [woocommerce/woocommerce#29226]
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
*all with the same issua was closed and people stop interaction

http://oliveiracomunicacao.com.br/clientes/new-fust/english/cushion-covers/

i've looked for this problem but none with a solution...

i'm trying to add the chegkou form inside an page, it does load all html for the form, but some hooks seem to be missing -- specially those that makes load/update in price, payments area

my code inside the page (and inside page loop structor from wordpress)
` <div class="row">
`            <div class="col-md-12">
`                <? the_content();
`
`global $woocommerce;
`
`$woocommerce->cart->empty_cart();
`$woocommerce->cart->add_to_cart(10);
`
`do_action('woocommerce_checkout_order_review');
`
`define( 'WOOCOMMERCE_CHECKOUT', true );
`define( 'WOOCOMMERCE_CART', true );
`echo do_shortcode('[woocommerce_checkout]');

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
- on wordpress - with woocommerce instaled and at least one product
- install any plugin wich has credit card options (i'm using wtripe by woocommerce)
- create a minimal theme with index, functions, header, footer, page
- create a custom page (with specific loop created like page-my-custom-page.php)
- via main shop page add a product to cart
- on the loop of page - via php - add the snnipet like:
```
`global $woocommerce;
`define( 'WOOCOMMERCE_CHECKOUT', true );
`echo do_shortcode('[woocommerce_checkout]');
```

**Expected behavior**
exact same behavior of the main checkout page
http://oliveiracomunicacao.com.br/clientes/new-fust/checkout

**Actual behavior**
Loads all httml from hooks but didn't attach the scripts needed for ajax

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. (it can't be reproduce without woocommerce)
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). (tested with twenty-nineteen/twenty)
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
attached file with status report
[status-report.txt](https://github.com/woocommerce/woocommerce/files/6045717/status-report.txt)

as referenced on 
https://stackoverflow.com/questions/34285467/woocommerce-woocommerce-checkout-shortcode-displays-checkout-form-but-not-pa

![Captura de tela 2021-02-25 174334](https://user-images.githubusercontent.com/55635874/109216073-cfca3c00-7792-11eb-8bfd-703951285bd6.png)
![Captura de tela 2021-02-25 174355](https://user-images.githubusercontent.com/55635874/109216077-d062d280-7792-11eb-9a19-ef6221b4dcce.png)

**Comment by barryhughes** [comment]
Hi @oliveiracom—great question!

As I think you've noticed, assets such as `frontend/checkout.js` are probably not being added to the page, which is why it is not working as expected.

The challenge here is that—to avoid adding scripts to pages where they are not needed—WooCommerce makes a decision about which assets are required during the `wp_enqueue_scripts` action. At that point it checks to see if the currently requested page is the main checkout page (as listed in the _WooCommerce → Status → WooCommerce Pages_ area) **or** if the requested post contains the `[woocommerce_checkout]` shortcode.

In your case, since you are calling the shortcode programmatically (and so the shortcode isn't actually stored in the `post_content` field, within the database) it is going to look as if the request is for a plain old regular page, and assets like `frontend/checkout.js` will not be added.

To that end, if you really need to add the shortcode in this fashion, you will need to find another way to signal to WooCommerce that the page should be treated as a checkout page. Here's some rough and untested code to give you an idea of what I mean:

```php
add_action( 'wp', function() {
	global $wp;

	if ( $wp->request === 'custom-page-slug' ) {
		add_filter( 'woocommerce_is_checkout', '__return_true' );
	}
} );
```

In the above example I am taking advantage of the `woocommerce_is_checkout` filter hook (which is what I'd recommend), but you could alternatively define a constant named `WOOCOMMERCE_CHECKOUT` and set it to true (the downside of course is that a constant can only be set once).

I hope that helps :-)
