### ISSUE TITLE
[GlobalStep] [IE 11] For "Twenty Twenty One" theme, Product images appears overlapped if products per rows is set to 4 and above.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29221]
## Bug Description:
For "Twenty Twenty One" theme, Product images appears overlapped if products per rows is set to 4 and above.

## Environment:
Windows 10
Browser:IE11(version:11.00.18362.1)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Choose Twenty Twenty One theme.
1. Go to Appearance->Customize.
1. Select WooCommerce->Product Catalog option.
1. Set the Products per rows to 4 or above.
1. Go to frontend->shop page.
1. Observe that Product images appears overlapped.

## Actual Result:
For "Twenty Twenty One" theme, Product images appears overlapped if products per rows is set to 4 and above.

## Expected Result:
For "Twenty Twenty One" theme, Product images should be properly display even if products per rows is set to 4 and abov

## Screenshot:

![#29221](https://user-images.githubusercontent.com/41110392/109175832-360f8880-77ac-11eb-93f0-e333100d8d05.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I tested with WooCommerce 5.0 and 5.1 - the issue is present in 5.0 so it is not specific to 5.1.

![browsers](https://user-images.githubusercontent.com/19143190/109364326-89d9aa80-785c-11eb-9947-fda1e9cf0f18.png)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment]
WordPress dropped support of [IE 11 in 2021](https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/).
