### ISSUE TITLE
[GlobalStep] [IE 11] For "Twenty Twenty One" theme, Footer section appears misaligned

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29223]
## Bug Description:
For "Twenty Twenty One" theme, Footer section appears misaligned.

## Environment:
Windows 10
Browser:IE11(version:11.00.18362.1)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Choose Twenty Twenty One theme.
1. Go to Frontend.
1. Observe that footer section appears misaligned.

## Actual Result:
For "Twenty Twenty One" theme, Footer section appears misaligned.

## Expected Result:
For "Twenty Twenty One" theme, Footer section should be properly aligned.

## Screenshot:

![#29223_1](https://user-images.githubusercontent.com/41110392/109176415-cd74db80-77ac-11eb-883d-0f517dc07924.png)

![#29223_2](https://user-images.githubusercontent.com/41110392/109176444-d796da00-77ac-11eb-81f9-0c9a33e70c5d.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I tested with WooCommerce 5.0 and 5.1 - the issue is present in 5.0 so it is not specific to 5.1. 

![footer](https://user-images.githubusercontent.com/19143190/109363947-be993200-785b-11eb-928b-4e038700d446.png)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment]
WordPress dropped support of [IE 11 in 2021](https://wordpress.org/news/2021/05/dropping-support-for-internet-explorer-11/).
