### ISSUE TITLE
Product management tooltips are misaligned on mobile

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce#29268]
**Describe the bug**
The product management guide tooltips are causing poor accessibility on mobile. Considering that they aren't optimized for mobile it might be best to turn them off completely on mobile.

**Expected behavior**
I'd either expect the tooltips to align with the content they're referring to, or not see them at all.

**Actual behavior**
On mobile devices the product management tooltips are misaligned and blocking areas of the navigation.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
One way:
- Go to 'WooCommerce > Products > All Products'
- Press Create Product
- Open the sidebar.
- See error

Another way:
- Go to Woocommerce home page task card
- Add products -> Add manually
- See error

**Screenshots**
https://share.getcloudapp.com/wbu9JY2G

This was tested on multiple devices in [this issue in WooCommerce Admin](https://github.com/woocommerce/woocommerce-admin/issues/6250).

**Comment by tammullen** [comment]
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2021-03-08 at 12 11 19](https://user-images.githubusercontent.com/24649833/110319924-74f0da00-8007-11eb-906d-1767c6e4b973.png)
![Screenshot 2021-03-08 at 12 11 30](https://user-images.githubusercontent.com/24649833/110319932-77533400-8007-11eb-85b7-9faf31387578.png)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

I'm also adding the `needs developer feedback` to check with the team if the related code is in WooCommerce Core

**Comment by psealock** [comment]
Since switching to the new component, I believe this has been resolved 

<img width="398" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/8f050400-9e53-45a3-9186-bdcb09dfe5e6">

I will close out this issue
