### ISSUE TITLE
Exposing customer billing data to WP Rest API

### ISSUE THREAD

**Issue by megphillips91** [woocommerce/woocommerce#29299]
I stumbled onto something which I figure is a privacy vulnerability related to  Woocommerce Customer billing details in the REST API. 

WooCommerce registers the personal data of the "billing contact" into user meta under the meta_keys "billing_email" "billing_phone", etc.

Since these fields are not registered as "_billing_email" instead of "billing_email" then it is very easy to accidentally expose those to the $_GET of the REST API.

I see that as pretty insecure because just by adding a new register_meta statement I can pull all that private data onto a completely insecure endpoint. Which is a really bad idea I think for the privacy of our WooCommerce customer data.

### If I do this: 
` register_meta( 'user', 'billing_phone', array(
        'show_in_rest' => true,
        'single' => true,
        'type' => 'string',
  ) );`

### Then the Customer's private billing data is open to the public $_GET endpoint of all users.

My suggestion is to maybe register the customer meta keys themselves and set the context to edit so 3rd party devs working on extensions like myself don’t accidentally expose data they didn’t intend to. A good "you're doing it wrong" error would also be cool. Either way, it seems pretty risky that these meta fields are so easily accidentally made public. 

Thank you,
:) Meg

**Comment by vedanshujain** [comment]
Hi, thanks for raising this enhancement. Your suggestion is helpful but does not look it we will be able to support it:

1. changing from `billing_phone` to `_billing_phone` could break extensions and other plugins, because they would be expecting the field `_` in there.
2. adding `doing_it_wrong` is incorrect because someone might be exposing these fields intentionally behind some authentication or a gateway. their logs will be unnecessarily filled in this case although they are doing it correctly.

thanks for raising the issue. I am closing the issue for repo maintenance, but feel free to reply back if you have additional questions.
