### ISSUE TITLE
API endpoint "products/batch" to support updating variation(s)

### ISSUE THREAD

**Issue by Bossman1337** [woocommerce/woocommerce#29341]
For this post, as an example, lets say i have a CSV file with id's and stock counts. Typical what you would get from suppliers and manufacturers. These id's could be simple products or a variation of a product. We don't know just by looking at it. Anyways...

Currently the endpoint **products/batch -> update** only supports simple products. For example If you need to update a variation stock count within a batch, then it wont work and this is stopping it:

https://github.com/woocommerce/woocommerce/blob/b446417be69602ffce3d9023bd2b3eef39318451/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L316-L326

Commenting out the code obviously stops the error but, the **products/batch -> update** works as expected and updates the variation stock. Now i understand there must be a reason as the proceeding code might not have methods for the variation class type.

I don't want to use the endpoint **products/<product_id>/variations/batch** this only batch updates the variations of a **single** product. If my CSV list had 10,000 items and each of those items were a separate variation of a product, then it would mean 10k calls. If i could batch them with **products/batch** then i could do it in 100 calls (10,000/100 - batches of 100 supported)

Hope this makes sense.

I have looked over this section of code but without spending tonnes of time working out how it's designed, is there anyone who worked on this part of the API and knows what checks need to be implemented so this can be done?

**Comment by vedanshujain** [comment]
You are right that we don't support updating variations across multiple variable products yet. I don't think we would be able to get to this enhancement request anytime soon, because we are more interested in implementing https://github.com/woocommerce/woocommerce/issues/28453 which will take care of this request as well across all the endpoints and resources and not just variations.

Note that the workaround of commenting out the check is not recommended because associated hooks and triggers that are added proper variations endpoint and code may not fire. If possible please use multiple API requests using variations/batch endpoint for now.

I am going to close this issue in favor of #28453.  Feel free to comment back if you have more questions.
