### ISSUE TITLE
Replace refund price using .html vs .text

### ISSUE THREAD

**Issue by ouija** [woocommerce/woocommerce#29377]
**Is your feature request related to a problem? Please describe.**
When using the "refund" option in the WooCommerce Order edit page, there is HTML that is **not** being rendered as HTML due to WooCommerce updating the refund price in the button using the jQuery .text() vs .html() query, so when selecting a item to refund, it is displaying the price in the refund button as so:

<img src="https://i.imgur.com/oUM4nyo.png">

This additional html is being added by the Wordpress Theme I am using, and I'm not sure how to remove it and have been living with this issue, but it's been somewhat annoying.

**Describe the solution you'd like**
If the method used to update the price in this "refund button" was using the jQuery .html() method to update the text that is within the **.woocommerce-Price-amount** <span> element, this would result in the HTML being rendered and would have the button render with the update value:

<img src="https://i.imgur.com/Z3mCpfs.png">

**Describe alternatives you've considered**
I've managed to resolve this issue by modifying the code my theme had in place that wrapping this span element around the currency format _(it is using a 'woocommerce_price_format' filter)_ but figured I'd mention this if anyone else has similar issues with this.

**Comment by vedanshujain** [comment]
@ouija we looked into the code but since the filter is added externally we cannot do anything in the code to fix it because:

1. it uses `text` instead of `html` for security reasons so changing this is not advisable.
2. `woocommerce_price_format` actually expects a string instead of an HTML. this is how it's being used across the code base, so changing it to account for HTML isn't without sideeffects either. 

I would recommend you to reach out to the theme developers to see if the HTML response is really needed? and if it is, then perhaps they can disable it just for admin screens. I am closing this issue because there is nothing for us (WC team) to do but feel free to reply back with any additional questions/comments and we will re-open and discuss.
