### ISSUE TITLE
Replace services lookup ip for http

### ISSUE THREAD

**Issue by Rahe** [woocommerce/woocommerce#29405]
Hello,

All the lookup ip services are available in https, but the values are still in http://  in the code https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-geolocation.php#L47
I think we can update them for the https version since they are all available.

Generating in some cases : 
> WP HTTP API Error: cURL error 60: SSL certificate problem: unable to get local issuer certificate - Response code: .

Nicolas,

**Comment by masteradhoc** [comment]
@Rahe / @juliaamosova  added a PR for this. Please also test the changes on your installation to see if it fixes your http api error.

**Comment by ObliviousHarmony** [comment]
Hello @Rahe,

Based on the error you've shared, I suspect changing the protocol to `HTTPS` would make your experience worse. This error is caused by `cURL` making `HTTPS` requests without having any local certificates installed. Your environment likely has no CA bundle installed and is unable to verify these requests, hence the error. This is likely a consequence of the `http://ipecho.net/plain` API redirecting to `https://ipecho.net/plain`.

After discussing it with the team, these kinds of situations highlight why we should leave these links as they are. We can't rely on the user's environment being configured in a way that those requests would work. If anything, we should remove the `ipecho.net` API, now that it performs this redirect.

There is also a `woocommerce_geolocation_ip_lookup_apis` filter to modify the contents of this list, if you want something specific for just your use-case.
