### ISSUE TITLE
[GlobalStep] "Select Options" button for variable product appears misaligned when added it in a grouped product on frontend 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29409]
## Bug Description:
"Select Options" button for variable product appears misaligned when added in a grouped product on frontend  for "Twenty Twenty-One" and "Twenty Nineteen" theme

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)
WooCommerce Admin version: v2.0.2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Select any one of the theme among these two: "Twenty Twenty-One" and "Twenty Nineteen" 
1. Go to Products->Add New and create a simple product and a variable product
1. Go to Products->Add New and create a grouped product
1. Link the simple and variable product to the grouped product
1. Click on "Publish" button and "Preview" button
1. Observe that "Select Options" button for variable product appears misaligned when added in a grouped product on frontend  for Twenty Twenty-One and Twenty Nineteen

**Note:**
Didn't observe this issue on "StoreFront" and "Twenty-Twenty" theme

## Actual Result:
"Select Options" button for variable product appears misaligned when added in a grouped product on frontend  for Twenty Twenty-One and Twenty Nineteen

## Expected Result:
"Select Options" button for variable product should appear properly aligned when added in a grouped product on frontend for Twenty Twenty-One and Twenty Nineteen

## ScreenShot:
![ #29409_2](https://user-images.githubusercontent.com/41110392/111488314-22c65c00-875f-11eb-8c8d-8a0dc6fe12a7.png)
![#29409_1](https://user-images.githubusercontent.com/41110392/111488341-278b1000-875f-11eb-8aa9-7f43ffab6229.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

**Twenty Twenty One theme - in general looks good but as the size of the screen gets reduced, the text on the button `Select Options` doesn't get scaled properly:**

![](http://g.recordit.co/d7rE53qHn3.gif)

**Twenty Twenty - looks good:**

![](http://g.recordit.co/bs788X8lT3.gif)

**Twenty Nineteen - doesn't look good from the beginning:**

![](http://g.recordit.co/hfBamndRmT.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment]
In WC 7.9-dev the select options button isn't shown in a grouped product.
