### ISSUE TITLE
Better hook to clear cart instead of 'get_header'

### ISSUE THREAD

**Issue by amritansh24** [woocommerce/woocommerce#29445]
**Is your feature request related to a problem? Please describe.**
When an order with no payment needed got placed (or in some cases of payments as well when gateway doesn't clear cart), the method to empty the cart hooked on 'get_header' handle. This handle in WordPress only works when the template loaded called 'get_header()'. Which is not the requirement of course. For the template having no headers, the cart is not getting cleaned up on order received pages. 

**Describe the solution you'd like**
This should be hooked on 'wp_head' (or a better hook) to overcome this limitation.

**Comment by roykho** [comment]
Hi @amritansh24 - thanks for reporting this. I can see how using `get_header` may not be the best way to do this. Maybe we should use `template_redirect` instead.

I will mark this as an enhancement however since this is not a high priority we may not be able to get this in a release anytime soon.

**Comment by iamdharmesh** [comment]
Hi @roykho @juliaamosova, 

Block-based themes(Twenty Twenty-Two - The default bundled theme with WordPress 5.9)  don't trigger the `get_header` action. So, if the payment gateway doesn't clear the cart it will not get cleared. I think this need to be fixed with high priority as a part of compatibility with block-based themes. 

Thanks.
