### ISSUE TITLE
WooCommerce "enable auto updates" option not available on some sites

### ISSUE THREAD

**Issue by Siemwagemans** [woocommerce/woocommerce#29460]
I'm posting this bug report at the request of the WooCommerce plugin support after opening a ticket at wordpress.org
https://wordpress.org/support/topic/cant-enable-woocommerce-auto-updates/#post-14217729 

For some websites, the WooCommerce auto updates option isn't available.
This issue only occurs in existing sites, not in new WordPress + WooCommerce installations. 
Normally there should be an option called "Enable auto-updates", but instead it only says "Auto-updates disabled".
I have included a screenshot of this below:

![Auto updates disabled](https://user-images.githubusercontent.com/81180959/112031913-24679980-8b3c-11eb-986c-cd43274e021c.png)

I don't have any experience fixing bugs, but if I can be of any assistance please let me know. 

Kind regards,
Siem Wagemans

**Comment by tammullen** [comment]
Hi @Siemwagemans 

Thank you for raising this issue.

This is happening because WooCommerce disables auto-updating if any WooCommerce extensions exist on your website that are untested (ie haven't declared support for the new version of WooCommerce).

I'm adding the needs `developer feedback label` to get input from the core team if this is a bug and if the `wc_prevent_dangerous_auto_updates` https://github.com/woocommerce/woocommerce/blob/f89b21488e49ce56f5c8beeef9ef2a89750319f1/includes/wc-core-functions.php#L2259 fucntion should have also been updated when the untested notices were disabled in https://github.com/woocommerce/woocommerce/pull/28840

**Comment by tammullen** [comment]
Will be fixed in https://github.com/woocommerce/woocommerce/pull/29200

**Comment by vedanshujain** [comment]
Closing since PR is merged. This will be available with WC 5.2.
