### ISSUE TITLE
Conditional Checkout Fields Not Retaining the Required Option

### ISSUE THREAD

**Issue by hjbrimner** [woocommerce/woocommerce#29524]
The WooCommerce Conditional Checkout Fields Settings plugin is not keeping boxes checked. We have it set up for all boxes to be required for certain products but they do not stay saved permanently. We have saved the changes and while immediately after we select the required box, it will switch back to being unchecked (I would say within a hour or so).

We are currently running WordPress 5.7.
We have version 1.0.6 of Conditional Checkout Fields for WooCommerce.

**Comment by juliaamosova** [comment]
Hi @hjbrimner,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [Conditional Checkout Fields for WooCommerce](https://woocommerce.com/products/conditional-checkout-fields-for-woocommerce/) plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
