### ISSUE TITLE
Add a filter for json_search_products_and_variations to exclude variation

### ISSUE THREAD

**Issue by hamza-wpbrigade** [woocommerce/woocommerce#29550]
I wanted to remove variations from the AJAX autocomplete for upsell products.
This is the method that is calling the method that is returning the JSON.

```
public static function json_search_products_and_variations() {
	self::json_search_products( '', true );
}
```

The option is already there. The 'true' need to be set to 'false'. Please add a filter to override this.

**Comment by ObliviousHarmony** [comment]
Hello @hamza-wpbrigade,

As this is a generic JSON endpoint for searching for products _and_ variations, it doesn't feel like a filter here would be fitting to address upsells. Since you're only attempting to affect that single select, I'd suggest looking at using the `exclude_type` data attribute on it. There are also some other places in the call stack will acceptable filters to address this, so I'd take a look there.
