### ISSUE TITLE
Not allowed when used per_page and search together

### ISSUE THREAD

**Issue by RASTecnoTI** [woocommerce/woocommerce#29555]
Hi
I am running the API command using curl with search an per_page parameters and I everytime receive the message "no permission to list resources", erros 401.
When I run only with 1 parameter, it work fine, but informing 2 parameters always is returned error.

**Comment by claudiosanches** [comment]
Hello @RASTecnoTI.

The only way to get the error you are talking about is if you are using  OAuth 1.0a and not sorting your parameters properly, what will cause an authentication error.
Note that OAuth 1.0a that everything gets ordered, for PHP you can use `uksort( $params, 'strcmp' )`.

You can see all details of how to use OAuth 1.0a in https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

I'm closing since this isn't an issue with WooCommerce.
