### ISSUE TITLE
WC_Order_Data_Store_CPT->get_order_count() causes slow queries on every page

### ISSUE THREAD

**Issue by starflower** [woocommerce/woocommerce#29563]
Hi, 

```
WC_Order_Data_Store_CPT->get_order_count()
```
is called on every page and in a database with a lot of orders this can cause slow queries.

```
SELECT COUNT( * ) FROM wp_posts WHERE post_type = 'shop_order' AND post_status = 'wc-completed'
```

Is called ob every page, even on the login page. This seems completely unnecessary to get the completely order history on every page load.

![image](https://user-images.githubusercontent.com/499926/113242351-12f75d80-92b1-11eb-961b-4de1a0f99853.png)

Why is that and how to prevent it?

Thanks!

**Comment by vedanshujain** [comment]
@starflower looks like this is coming from the WC Google Integration Analytics plugin. Thanks for the report, I am going to pass this feedback to the team managing the plugin, meanwhile, you can run `update_option( 'woocommerce_google_analytics_pro_notice_shown', false );` once on your site to get around the issue while we work on a fix.
I am closing the issue in this repo since it needs to be fixed in the extension. 
All this said this query is supposed to be fast since it uses DB indexes, may I know how many total orders you have on this site?

**Comment by starflower** [comment]
@vedanshujain There are ~90k orders, ~153k coupons and ~44k user memberships, which are all stored in posts and I think that's why it is slow. Thanks for your help!

**Comment by starflower** [comment]
@vedanshujain I tried to run `update_option( 'woocommerce_google_analytics_pro_notice_shown', false );`, but this didn't have any effect :/

**Comment by thomas-zg** [comment]
Looking to the code of the plugin, the option set to false should solve the problem:
[https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/b8b2e67ae7c2716b851ba278a1877e8f74857f1d/woocommerce-google-analytics-integration.php#L130]

**Comment by roykho** [comment]
Hi @starflower - can you try `update_option( 'woocommerce_google_analytics_pro_notice_shown', true );` instead?

**Comment by starflower** [comment]
@roykho We set it manually to the database and now it works with value `false`. Thank you!

**Comment by roykho** [comment]
@starflower - Thanks for confirming. Will be closing this issue now.
