### ISSUE TITLE
Typo in Payment Methods

### ISSUE THREAD

**Issue by dfeuster** [woocommerce/woocommerce#29579]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

Typo in Settings > Payments > Payment Methods > Direct bank transfer. The description for this method doesn't have a period.
<img width="903" alt="wordpress-poynt-settings-01-04022021" src="https://user-images.githubusercontent.com/11587025/113455994-e468a800-93c0-11eb-98e7-998a77def673.png">

**Comment by juliaamosova** [comment]
Hi @dfeuster,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

If you are interested to submit a PR to fix it, it will be welcomed.

**Comment by masteradhoc** [comment]
@juliaamosova / @dfeuster added a PR for this, thx.
