### ISSUE TITLE
Allows to filter the condition "is using shop base" in the breadcrumbs

### ISSUE THREAD

**Issue by strategio** [woocommerce/woocommerce#29618]
**Is your feature request related to a problem? Please describe.**
In `\WC_Breadcrumb::prepend_shop_page`, there's a condition to add the "Shop" breadcrumb which partly depends on the permalinks product base.

On a multilingual site like with WPML, the shop page ID is filtered inside `wc_get_page_id( 'shop' )` to return the translated shop page and the subsequent condition is not passing because the translated shop page slug does not (necessarily) match original shop page slug.

**Describe the solution you'd like**
We would like a filter hook to allow overriding this condition.

**Describe alternatives you've considered**
We 2 inefficient alternatives by filtering the breadcrumbs items with the filter hook `woocommerce_get_breadcrumb`:
1. We try to detect when the Shop breadcrumb is missing and then insert it.
2. We reuse the 2nd argument `$this` and regenerate the breadcrumb with the `\WC_Breadcrumb` object.

Both alternatives are very hacky and with bad performance.

**Additional context**

I will open a PR and show a proof of concept.

**Comment by claudiosanches** [comment]
Hello @strategio,

Thank you for taking the time to share this idea, we really appreciate your help.

> Both alternatives are very hacky and with bad performance.

Sorry but I don't agree, we introduced `woocommerce_get_breadcrumb` so anyone can customize WooCommerce's breadcrumbs, I see no reason for not using this filter now, also note that everything will be on object cache, transients and so on by `get_option` and other WP functions, so I can't see any performance impact as you are claiming, also in the solution you are proposing there's no performance improvement if this is something of your concern, everything will still be loaded as before.

Also it's a little confusing this new filter and method, since WooCommerce already have options to use or not the shop as a base for the permalink and then for breadcrumbs and everything else.

If performance is a big concern to you it's also possible to extend `WC_Breadcrumb` and create your own class, and get it applied by overriding `woocommerce_breadcrumb()` function, so you have full control of all elements in the breadcrumb.

Anyway, while we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue. Thanks.

**Comment by strategio** [comment]
@claudiosanches, I can understand this is not in your priorities to include this filter, OK that's fine...

Maybe I was not clear about our needs. We don't want to "customize" the breadcrumb, we just want the breadcrumb to display the same way for different languages. We would need this for our official WPML glue plugin (https://wordpress.org/plugins/woocommerce-multilingual/).

Example:
- EN (default) => "Home / Shop / Uncategorized / T-Shirt"
- BR (secondary lang) => "Accueil / Boutique / Non classifié(e) / T-Shirt"

The condition with the "product base" permalink is the only thing we need to filter. Otherwise we have 2 alternatives that I can list to be complete (via `woocommerce_get_breadcrumb` hook):
1. We can try to include an extra "hand-made" crumb => This is not super safe because in some way, we are re-writing the conditions and the code to build the crumbs. Our codes might diverge in the future.
2. Regenerate the breadcrumb with the `\WC_Breadcrumb` instance passed to the filter, while we are temporarily filtering the woocommerce permalinks => This is not very satisfying because we are doing the job twice.

Overriding `woocommerce_breadcrumb()` function is also not appropriate in our case, it's a bit overkill to steal this function for our small adjustment.

BTW, I checked the UI option "Settings > Permalinks > Shop base" and it's not really an option in the DB. It's just a UI option that pre-fills the "Custom base" input. Ideally, it would be way easier to check that option in the breadcrumb code rather than the actual permalink base... we could easily filter this.

Since you don't want to introduce this filter now, we'll also put this issue on hold on our side. Thanks anyway!
