### ISSUE TITLE
/wp-content/themes/woodmart/js/scripts/portfolio/portfolioEffect.js?ver=6.0.2	 (canceled) 

### ISSUE THREAD

**Issue by fradaspa** [woocommerce/woocommerce#29649]
Hello guys, 
i can see this file js from the home page that goes in 404. Somebody know what to do?

**Comment by wayheming** [comment]
@fradaspa hello you better contact support for your theme (Woodmart)

**Comment by fradaspa** [comment]
Hi
There is nothing to do except the author oh the theme?

**Comment by wayheming** [comment]
@fradaspa looking at the error there is a problem with the theme file

**Comment by tammullen** [comment]
Hi @fradaspa 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party theme Woodmart.
​
Please contact the author of the theme directly for further help.
