### ISSUE TITLE
Variable (parent) product stays out of stock, while the variation (child 

### ISSUE THREAD

**Issue by sebaskalk** [woocommerce/woocommerce#29658]
Hello,

Wordpress 5.7

WooCommerce version: |   | 5.1.0
-- | -- | --
WooCommerce REST API package: |   | 5.1.0 
WooCommerce Blocks package: |   | 4.4.3 
Action Scheduler package: |   | 3.1.6 
WooCommerce Admin package: |   | Inactive 2.0.2 

I've seen multiple threads and none that helped me.

Ive attached a diagram of the issue, but the title actually explains the core problem. Variable products shows as out of stock, while they should be IN STOCK.
[Parent stockstatus problem EN.pdf](https://github.com/woocommerce/woocommerce/files/6304352/Parent.stockstatus.problem.EN.pdf)

If you need any further information I'm happy to share :)

**Comment by roulag** [comment]
It's possible I am having the same issue. I updated to the latest version today.

The variable products do show as IN STOCK in the Dashboard Products section but OUT OF STOCK on the front end with a message: This product is currently out of stock and unavailable.
Any fixes?

**Comment by tammullen** [comment]
Hi @sebaskalk 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
