### ISSUE TITLE
[GlobalStep] Font is too large for "Email Address" and "Phone Number" displayed under "Billing Address" on "My Account->Addresses/Subscriptions" page for "Twenty Twenty One theme".

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29673]
## Bug Description:
Font is too large for "Email Address" and "Phone Number" displayed under "Billing Address" on "My Account->Addresses/Subscriptions" page for "Twenty Twenty One theme"

## Environment:
Woocommerce Version: WooCommerce 5.2 and 5.1
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site.
1. Install and activate all the required plugins 
1. Complete OBW setup
1. Go to Products->Add New 
1. Add payment method say "Cash on Delivery" from WooCommerce->Payments
1. Go to front-end, add a product to cart by clicking on "Add to Cart" button
1. Click on "View Cart" button
1. Click on "Proceed to Checkout" button
1. Click on "Place Order" button
1. Go to "My Account-> Orders" 
1. Click on "View" button
1. Observe that font is too large for "Email Address" and "Phone Number" displayed under "Billing Address" on "My Account->Addresses/Subscriptions" page for "Twenty Twenty One theme"

## Actual Result:
Font is too large for "Email Address" and "Phone Number" displayed under "Billing Address" on "My Account->Addresses/Subscriptions" page for "Twenty Twenty One theme"

## Expected Result:
Font should be same as the other details under "Billing Address" for "Email Address" and "Phone Number" field on "My Account->Addresses/Subscriptions" page for "Twenty Twenty One theme"

## ScreenShot:
![#29673](https://user-images.githubusercontent.com/41110392/114731918-bd668a80-9d5f-11eb-91a8-2ec65da9c814.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![Screenshot_2021-04-18_at_11_18_59](https://user-images.githubusercontent.com/24649833/115142199-5d5e3580-a038-11eb-9ca4-16e23df4f26b.png)
Twenty Twenty One
![Screenshot_2021-04-18_at_11_19_18](https://user-images.githubusercontent.com/24649833/115142201-5fc08f80-a038-11eb-859b-03c26ba2fd0c.png)
Storefront for comparison

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rrennick** [comment]
I'm not able to reproduce this in the latest WooCommerce.
