### ISSUE TITLE
It would be totally awesome to see the orderID which is displayed in UI not internal one

### ISSUE THREAD

**Issue by dangoriaynov** [woocommerce/woocommerce#29671]
I have installed the "WooCommerce Sequential Order Numbers" extension (https://docs.woocommerce.com/document/sequential-order-numbers/)
It allows having sequential order numbers instead of ones provided by Wordpress.
This helps and UI everything works fine. However when I receive the notification in Slack - I still see some unrelated numbers.

AFAIK you should take the order number using following logic for it to be shown correctly in notifications:
$order_id = wc_seq_order_number_pro()->find_order_by_order_number( $order_number );

instead of standard way of taking the order numbers. See:
https://docs.woocommerce.com/document/sequential-order-numbers/#section-9

This improvement will add-up to the overall user experience with the slack plugin itself.
Thanks!

**Comment by kkmuffme** [comment]
This is not a bug with woocommerce, but with the sequential order numbers plugin. Please contact support at woocommerce.com

**Comment by tammullen** [comment]
Hi @dangoriaynov 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party plugin WooCommerce Sequential Order Numbers. 
​
Please contact the author of the plugin directly for further help.
