### ISSUE TITLE
[GlobalStep] For "Twenty Twenty One" theme, Content appears misaligned on Cart page for Multiple variable products.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29697]
## Bug Description:
For "Twenty Twenty One" theme, Content appears misaligned on Cart page for Multiple variable products.

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.1
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete OBW setup.
1. Select Twenty Twenty One theme.
1. Add Some Variable products.
1. Go to frontend and add multiple variable products to the cart with different variations.
1. Go to Cart page.
1. Observe that content appears misaligned on Cart page for Multiple variable products.

## Actual Result:
For "Twenty Twenty One" theme, Content appears misaligned on Cart page for Multiple variable products.

## Expected Result:
All content should be properly aligned.

## ScreenShot:
![#29697](https://user-images.githubusercontent.com/41110392/114890996-21a15100-9e29-11eb-80b7-7278ef390b9b.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for taking the time to report this bug, we really appreciate your help. I can partially reproduce it on my end. 

The column titles in Twenty Twenty One aren't aligned the same way as they are in Storefront and Twenty Twenty

![Screenshot 2021-04-18 at 10 32 37](https://user-images.githubusercontent.com/24649833/115141074-64824500-a032-11eb-8c8d-5460bc90594d.png)
Storefront

![Screenshot 2021-04-18 at 10 38 44](https://user-images.githubusercontent.com/24649833/115141077-65b37200-a032-11eb-96ae-85cc92904dcc.png)
Twenty Twenty

![Screenshot_2021-04-18_at_10_34_58](https://user-images.githubusercontent.com/24649833/115141082-68ae6280-a032-11eb-9f26-b6a4d9e5e241.png)
Twenty Twenty One

I wasn't however able to reproduce the issue with the Quantity text boxes being different sizes.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

Can you give more details on the setup of the products used that might allow us to reproduce the quantity boxes sizing issue.

**Comment by gglobalstep** [comment]
> Hi @gglobalstep
> 
> Thank you for taking the time to report this bug, we really appreciate your help. I can partially reproduce it on my end.
> 
> The column titles in Twenty Twenty One aren't aligned the same way as they are in Storefront and Twenty Twenty
> 
> ![Screenshot 2021-04-18 at 10 32 37](https://user-images.githubusercontent.com/24649833/115141074-64824500-a032-11eb-8c8d-5460bc90594d.png)
> Storefront
> 
> ![Screenshot 2021-04-18 at 10 38 44](https://user-images.githubusercontent.com/24649833/115141077-65b37200-a032-11eb-96ae-85cc92904dcc.png)
> Twenty Twenty
> 
> ![Screenshot_2021-04-18_at_10_34_58](https://user-images.githubusercontent.com/24649833/115141082-68ae6280-a032-11eb-9f26-b6a4d9e5e241.png)
> Twenty Twenty One
> 
> I wasn't however able to reproduce the issue with the Quantity text boxes being different sizes.
> 
> We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
> 
> Can you give more details on the setup of the products used that might allow us to reproduce the quantity boxes sizing issue?

We added Multiple variable products with different variations to the cart and observed the quantity boxes sizing issue.

**Comment by rodelgc** [comment]
The varying lengths for the product quantity input fields seems specific to Chrome. I can reproduce the issue there, but not on Firefox. Firefox shows the the input boxes to be the same length. Here's the screenshot from my Chrome. Notice that the input box for "Heavy Duty Bronze Shirt" is shorter than the rest:
<img width="1266" alt="Screen Shot 2021-11-18 at 12 07 48 AM" src="https://user-images.githubusercontent.com/4509348/142237617-e7d0439b-73fb-42fb-819e-cd6b62ac440f.png">

I viewed the exact same cart on Firefox, and notice that "Heavy Duty Bronze Shirt" now has consistent input box length as the others
<img width="1274" alt="Screen Shot 2021-11-18 at 12 10 10 AM" src="https://user-images.githubusercontent.com/4509348/142237749-9163a429-981a-45bf-a1a7-a2730614ba77.png">

Note that this product is just a simple product, not variable.

**Comment by rodelgc** [comment]
It seems that the `Enable stock management at product level` setting affects the length of the input box for some reason. When it's checked, the input box appears short. When it's unchecked, the input box lengthens, and will already be the same length as the other input boxes. Screen recording can be found here - p1637166551131600/1637163091.125200-slack-C011ENB20Q1

**Comment by rrennick** [comment]
This looks like it has been addressed.
