### ISSUE TITLE
[GlobalStep] "Fatal error: Uncaught WC_Data_Exception:" is displayed when user tries to allow backorders with edit bulk action on products including with "Affiliated/External Product" on "All Products" Page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29696]
## Bug Description:
"Fatal error: Uncaught WC_Data_Exception:" is displayed when user tries to allow backorders with edit bulk action on products including with "Affliated/External Product" on "All Products" Page

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.1
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete OBW setup
1. Go to Products->Import and import "sample_products.csv"
1. Go to All Products, once all the products are imported
1. Click on "Bulk Actions" dropdown and Select "Edit" , select all products by ticking on check box below it 
1. Click on "Apply" button
1.  Click on "Backorders?" dropdown and Select any one of the Allow options
1. Click on "Update" button
1. Observe that "Fatal error: Uncaught WC_Data_Exception:" is displayed when user tries to allow backorders with edit bulk action on products including with "Affliated/External Product" on "All Products" Page

## Actual Result:
"Fatal error: Uncaught WC_Data_Exception:" is displayed when user tries to allow backorders with edit bulk action on products including with "Affliated/External Product" on "All Products" Page

## Expected Result:
Proper validation should be displayed when user tries to allow backorders with edit bulk action on products including with "Affliated/External Product" on "All Products" Page or it should exclude "Affliated/External Product when bulk product edit action is applied 

## Video:

https://user-images.githubusercontent.com/41110392/114890465-a8a1f980-9e28-11eb-818b-531deabc37ba.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I selected a variety of product types including external products and selected to allow backorders
![Screenshot 2021-04-15 at 21 19 15](https://user-images.githubusercontent.com/24649833/114936806-d3924a80-9e34-11eb-9a8a-06fed91240cd.png)

Pressed update and got error `Fatal error: Uncaught Exception: External products cannot be backordered.`
![Screenshot 2021-04-15 at 21 19 44](https://user-images.githubusercontent.com/24649833/114936975-12c09b80-9e35-11eb-9ca5-dde21977d475.png)

I tested this in 5.1.0 and 5.2.2

A couple of things to note
- We note in documentation bulk editing works best with Simple Products https://docs.woocommerce.com/document/bulk-editing-products/#section-2
- The filter by product type can be used to avoid including external products in a bulk edit
- The external product doesn't actually get updated, which is what we would expect
- Although a fatal error is displayed you can navigate back to the previous screen with the browser back button

I'm setting this to `high` priority for now because of the Fatal Error however due to the reasons above we may later decide to change this to `low`.

Stay tuned for updates.
