### ISSUE TITLE
Unavailable screen options on the product area in Woocommerce

### ISSUE THREAD

**Issue by ManuryR** [woocommerce/woocommerce#29715]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Unavailable screen options on the product area in Woocommerce :

The accumulation of plugins gives an anarchic display due to lack of space in the admin area -> WooCommerce -> Products

"Screen option" to check or uncheck what you want to be displayed is "blocked" and so I can't display only what is necessary on the screen to solve this display bug. 

Could you please help me? Thanks 
![Capture 1](https://user-images.githubusercontent.com/82819579/115241659-5eb75d00-a121-11eb-8065-040f3ac91d2a.png)
![Capture 2](https://user-images.githubusercontent.com/82819579/115241667-60812080-a121-11eb-883c-182e55f0e18c.png)

**Comment by juliaamosova** [comment]
Hi @ManuryR,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
