### ISSUE TITLE
Geolocate transients are not being deleted and then bloat out the options database table

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#29738]
If a customer is using the geolocate feature using MaxMind to get the customer's default address then it is common to have higher transients levels where those transients use the following option names.

```
_transient_external_ip_address_%
_transient_timeout_external_ip_address_%
```
Those IP address-related transients need to be purged at least daily on-site. I know there is already a cron event that runs daily to delete expired transients but those transients do not always show as being expired.

**Comment by laszlof** [comment]
Can confirm this is an issue. I recent was troubleshooting a site that was seeing massive page load times, it turns out there was around 40K transients in the DB with the above name. Removing them and disabling geolocate dropped page load times by a factor of 10.

**Comment by juliaamosova** [comment]
Hi @lukecav,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Thanks for the report, looks like [these transients are set with the expiry of a week](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-geolocation.php#L124). We should at least reduce this to a day if not a few hours, and optionally add a cleanup routine.

**Comment by claudiosanches** [comment]
Hello @lukecav @laszlof,

Thanks for reporting this issue, but please note that `_transient_external_ip_address_*` is used only as a fallback for those hosting and accessing a WooCommerce store in localhost, where there's no way to get a server variable like `HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR` or `REMOTE_ADDR`, so if you are experiencing it in a production site, please check for those `$_SERVER` variables, because maybe there's a bigger problem in your environment.

This is how works when `wc_get_customer_default_location()` is called and geolocation is enabled:

1. First it's called `WC_Geolocation::geolocate_ip( '', true, false )`.
2. Since there's no `IP address` as the first parameter of `WC_Geolocation::geolocate_ip()` it will try to use `WC_Geolocation::get_ip_address()` to get users IP address (here is when we try to fetch `HTTP_X_REAL_IP` and other variables as I said above).
3. After Woo tries to find the geolocation with `WC_Geolocation::get_country_code_from_headers()` looking into `MM_COUNTRY_CODE`, `GEOIP_COUNTRY_CODE`, `HTTP_CF_IPCOUNTRY` and `HTTP_X_COUNTRY_CODE` server variables.
4. If no country code is found Woo will use the GeoLite API, but it requires a valid IP address, so if `WC_Geolocation::get_ip_address()` returns empty Woo will use an external API to find the IP address running `WC_Geolocation::get_external_ip_address()`, and will also run `WC_Geolocation::geolocate_ip( $external_ip_address, false, $api_fallback )` to try fetch geolocation from GeoLite database but now with the external IP address, this will also get saved by a transient, to avoid accessing a external API to fetch this IP address.

I agree that we need to improve this transient time, but having a large database with those transients indicates another issue in your environment.

**Comment by claudiosanches** [comment]
I just submitted a PR to change those transients to expire in one day, but this doesn't solve any issue if your server doesn't return `HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR` or `REMOTE_ADDR`.
