### ISSUE TITLE
Price report on WooCommerce. Please check

### ISSUE THREAD

**Issue by 79ho3ein** [woocommerce/woocommerce#29755]
Hello. In the Persian language site, the price unit has gone to the right of the price.  While before the update, the new version was on the left side of the price. Of course, this problem only exists in the Android Chrome browser.

Has a similar case been reported?
Thanks

**Comment by zhongruige** [comment]
Hi @79ho3ein,

So far I haven't seen any other issues reported. We can further triage if you can fill out this bug template and we're happy to take a look if this is a bug.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
