### ISSUE TITLE
wc_get_products needs to be able to search by product name

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29777]
When reading this official docs for 'wc_get_products' here:
https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query

There is no way to search product by name. Its the very basic human way to differentiate each product.

Current solution mentioned in #21450 cant be use to return unique product with the exact name. It will return product even if the "search_string" found in the product description.

Yes I can use like this but I dont know the realibility of this method. Because Its not mentioned in the official docs, so it will likely break due to database changes in future WooCommerce versions.

    $args = array(
        'limit' => 1,
        'title' => 'Philips Avent Bottle Natural 260ml/9oz',       //search by product name
        //'name' => 'philips-avent-bottle-natural-260ml-9oz',    //search by product slug
        //'return' => 'ids',
    );
    $products = wc_get_products( $args );

Please add this basic functionality.

**Comment by zhongruige** [comment]
Hi @erikdemarco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @erikdemarco,

Thanks for the question. I see that you've discovered that `title` can be used. Thanks for pointing out the lack of documentation there. I'm going to use this issue to track that we need to expand our documentation to indicate that `title` can be used to get products by _exact_ title.

We have no plans to remove that functionality, and in any changes we make, we'll maintain backwards-compatibility.

**Comment by erikdemarco** [comment]
@jonathansadowski is there anyway to search title but not in 'exact match'? in mysql it will be 'LIKE'

**Comment by barryhughes** [comment]
The [wiki page](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query) has been updated to cover the `name` field (which should be preferred, rather than `title`).

> Is there anyway to search title but not in 'exact match'?

This is not supported, but we'd be receptive to a feature request and/or PR (and, we should probably also add `s` to the set of officially supported query params).
