### ISSUE TITLE
Rest API cyrillic slugs 

### ISSUE THREAD

**Issue by kbehov** [woocommerce/woocommerce#29784]
Hello, i'm trying to make a frontend app for Woocommerce store with nextJS, so i'm buiding single product page wich have a cyrillic symbols in the url. I'm making the product request based on the query for example example.com/produkt/кроп-топ-atlanta-1991-grey. I'm getting the slug from the frontend app  and pass it as param for the query to woocommerce API, but always returns 404. I also try my funcion with latin characters and their is no problem with the request it's return 200 and the data.i also try in JS with  encodeURIComponent() and decodeURIComponent() but i'm still getting 404. I will paste parts of my code here and i will be very thankful if someone give me suggestion how to fix this.
```
`import { withRouter } from "next/router";
import axios from "axios";

const product = ({ slug }) => {
  const [product, setProduct] = useState(undefined);
  const [error, setError] = useState(false);
  const productUrl = `/wp-json/wc/v3/products&slug=${slug}`;
  useEffect(async () => {

    await axios
      .get(baseUrl + productUrl + AUTH_PARAMS)
      .then((res) => console.log("res", res))
      .catch((err) => console.log("err", err));
  }, [product, error]);

product.getInitialProps = async ({ query }) => {
  const { slug } = query;
  return { slug };
};
```

export default withRouter(product);`
I also try with the search param to search for product with cyrillic characters but also get 404 for the sarch. I'm not sure how to properly pass the cyrillic characters to the API.
Thank you in advance!
P.s:  I'm not sure this is bug or my mistake

**Comment by zhongruige** [comment]
Hi @kbehov,

Thank you for submitting this question!

Looking at the `productUrl` being set, it appears the parameter is being added on incorrectly. Instead of an `&` it should be a `?`. For example:

`/wp-json/wc/v3/products?slug=кроп-топ-atlanta-1991-grey`

I verified this works with Cyrillic slugs as well:

<img width="1357" alt="Screen Shot 2021-04-30 at 2 51 15 PM" src="https://user-images.githubusercontent.com/71906536/116753584-87164580-a9c4-11eb-8ed0-96cacf40f5d4.png">

<img width="902" alt="Screen Shot 2021-04-30 at 2 58 40 PM" src="https://user-images.githubusercontent.com/71906536/116753606-91384400-a9c4-11eb-9d08-4e78f67fe28b.png">

Let me know if this works for you and we can close out this issue. Thanks!

**Comment by kbehov** [comment]
Yes, i see it later. Thank you for the fast support. Now i checked and it's works fine with PostMan, but now i have some problem with cors fetching data from React App. Thank you again! :)

**Comment by zhongruige** [comment]
You're quite welcome! Happy I could help :) I'll go ahead and close this issue for now then. Good luck with the CORS issue!
