### ISSUE TITLE
ups prices doubling woocommerce.

### ISSUE THREAD

**Issue by tdesan** [woocommerce/woocommerce#29786]
Our prices are doubling for shipping on small items. usually the shipping would be about $10.49 according to the UPS estimated shipping cost. But instead for 1 item that is 1.5 lbs and 11X4X3 dimensions is coming out to 21.56 for ground shipping local. Larger items seem to be calculating right. Any ideas how to fix this on WooCommerce?

Our shipping plugins are:
Multiple Packages for WooCommerce
Packages Configuration for WooCommerce
WooCommerce Shipping & Tax
WooCommerce Shipping Tracking
WooCommerce Table Rate Shipping
WooCommerce UPS Shipping

Any ideas?

**Comment by zhongruige** [comment]
Hi @tdesan,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only.

As the issue you are having seems to be caused by one of the above plugins, to get further technical support for it, please contact WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin. Thank you!
