### ISSUE TITLE
Please fix the woocommerce issues which arise when using some minification plugins

### ISSUE THREAD

**Issue by dangoriaynov** [woocommerce/woocommerce#29794]
Hello!

I am using Woocommerce 5.2.2 and Swift Performance Pro 2.3.3
When using the script minification feature in the Swift Performance plug-in I see the following issue in the developer console in the browser:

Uncaught TypeError: (intermediate value)(...) is not a function

Which is effectively caused by the following code:

/**
 * NO JS handling.
 *
 * @since 3.4.0
 */
function wc_no_js() {
        ?>
        <script type="text/javascript">
                (function () {
                        var c = document.body.className;
                        c = c.replace(/woocommerce-no-js/, 'woocommerce-js');
                        document.body.className = c;
                })();
        </script>
        <?php
}

It's perfectly fine till this block leaves in the separate <script type="text/javascript"> code block
But when it gets merged with rest of javascript code in the file - compiler starts reading it wrongly.
Compiler assumes that this is not anonym function but rather way to call the previous code block (some function is usually concatenated before this one).
This results to whole Woocommerce not working properly and cart couldn't be open for example.

I understand that this issue might be treated as a Swift Performance one. But since it is not clear how such ambiguous cases should be treated by Swift Performance and other optimisation plugins - please either provide a clear way to report an issue to them or fix this code block.

**Comment by zhongruige** [comment]
Hi @dangoriaynov,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@dangoriaynov we discussed this internally, and actually the JavaScript here is valid as you yourself note in your comment that this is an anonymous function and should not have been optimized away. We generally don't want to name these functions to not pollute the global namespace, so perhaps WooCommerce is not the correct place to fix it. Also seems like Swift Performance is a paid plugin so we cannot test this anyway.

Can you please reach out to the authors of the plugin and ask them to see if this code can be excluded from optimization? I am closing the issue for now marking it as won't fix, but that said if you do get a reply from Swift plugin author about what can we do here to fix (or perhaps a PR even), if the fix is complicated from their end, then we will definitely consider it.
