### ISSUE TITLE
Update order status filter e2e tests to use orders API

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#29797]
Once work is completed on https://github.com/woocommerce/woocommerce/issues/27873 we want to update the order status filters test to use the API to create the orders instead. For more context, see the discussion here: https://github.com/woocommerce/woocommerce/pull/29683#discussion_r622501876

**Comment by rodelgc** [comment]
Hi @zhongruige,

Where should I put the new function to batch create the orders? Currently I see two places where I could put it:
1. As a new factory JS file in the directory `tests/e2e/utils/src/factories`, or...
2. As a new function named something like `batchCreateOrders()` inside `tests/e2e/utils/src/components.js` file

Which of these two places should we put the new function in? Thanks!

**Comment by zhongruige** [comment]
Hi @rodelgc,

Good question!

I think adding it into `components.js` would make the most sense. I am curious, for the `batchCreateOrders()`, are you envisioning that we would we pass in an array of order statuses that we loop through to create orders with different statuses, or something else?

**Comment by rodelgc** [comment]
Thank you for clarifying @zhongruige. OK, I'll put the function inside `components.js`. 

> we would pass in an array of order statuses...

Yes, that is how I imagine `batchCreateOrders()` would be.

> ...that we loop through to create orders with different statuses

I'm thinking I would use a loop only to create the request payload for the [Batch Create endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-orders) (`POST /wp-json/wc/v3/orders/batch`) to save more time rather than using the loop to repeatedly call the [Create an Order](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order) endpoint.

In code, this is how I roughly imagine it would be:
```
const batchCreateOrders = async (statusesArray)=>{
	
	// Array of orders that will be used on the request payload later on
	const ordersArray = [];
	
	// Use the loop only to construct the array of order objects,
	// not to repeatedly call the "Create an Order" endpoint
	for( const status of statusesArray){
		// create an order object that has this status,
		// then add this order object to `ordersArray[]`
	}

	// Do some formatting on the `ordersArray[]` to match the request payload
	// for the "Batch Create Order" endpoint according to our API docs
	const requestPayload = {};

	// Finally, call the "Batch Create Order" endpoint with this request payload.
	await callTheBatchCreateOrderEndpoint();

	// Not sure if this function would need to return anything.
	// We'll see...
	return something;
}
```

Please let me know what you think of this approach. Thanks!
