### ISSUE TITLE
Rest API returns JSON ERROR: Syntax Error

### ISSUE THREAD

**Issue by Grin0011** [woocommerce/woocommerce#29801]
**Prerequisites (mark completed items with an [x]):**
- [ X ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ X ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
We have an connection with an external POS and a WooCommerce shop. We will load the products from the POS into the webshop using the REST API v3. Everything worked fine, but since this week we received an error and I can't find where it goes wrong.

Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /.../.../public_html/wp-content/plugins/insert-products-api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /.../.../public_html/wp-content/plugins/insert-products-api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /.../.../public_html/wp-content/plugins/insert-products-api/vendor/automattic/woocommerce/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('products/221754...', 'PUT', Array)
#2 /.../.../public_html/wp-content/plugins/insert-products-api/store-products.php(304): Automattic\WooCommerce\Client->put('products/221754...', Array)
#3 /.../.../public_html/wp-content/plugins/insert-products-api/store-products.php(248): LoadInventory->updateVariation(Object(stdClass), 221757, 221754)
#4 /.../.../public_htm in /home/vander1q/public_html/wp-content/plugins/insert-products-api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

Can you help me to resolve this?

**Comment by zhongruige** [comment]
Hi @Grin0011,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
