### ISSUE TITLE
Change Add to Cart Button to when Product or Variation is Backorder

### ISSUE THREAD

**Issue by svenms** [woocommerce/woocommerce#29866]
Dears,

Currently there is a way to change Add to Cart button for single products with Backoders.

```
add_filter( 'woocommerce_product_single_add_to_cart_text', 'change_add_to_cart_single_prod', 10, 2 );
function change_add_to_cart_single_prod( $text, $product ){
    if ( $product->is_on_backorder( 1 ) ) {
        return __( 'Reservar', 'woocommerce' );
    }
    return __( 'Comprar', 'woocommerce' );
}
```

But it does not work with variations unless the every variation is in backorders or out of stock.
I believe backorders variations should also have the possibility to change their Add to Cart button.

**Comment by juliaamosova** [comment]
Hi @svenms,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @svenms thanks for the enhancement request.

Unfortunately, what you are asking will actually need javascript customization, in that you would need to add a script that can listen to when customers change the variation and then modify the cart text.

Perhaps you can also use `woocommerce_get_availability_text` to indicate to customers that adding to cart, when product is in backorder will only reserve the product, and won't buy it outright.

For what it's worth, your filter is actually working, the only problem is it's getting applied to the parent product and not the variation. I am closing the issue for now, since this needs JS customization, and there is also a workaround (although not pretty) in using `woocommerce_get_availability_text` instead of changing the button text which will be updated per variation. 

Let us know if we have missed something.
