### ISSUE TITLE
Adding new parent category to existing categories - existing products not making new parent appear

### ISSUE THREAD

**Issue by DavidBorrink** [woocommerce/woocommerce#29872]
I created a new parent category (let’s call it “clip art”) and moved existing categories (“apple clip art”, “Canada clip art”, and more ) under it, and those existing categories already had products under them. One would assume that existing products would allow “Clip art” to show up on the main shop page, because the subcategories did have products in them. But it did not.

Using a tip from another forum situation, I tried this:  I added another new parent “A Test Category”, and created a new subcategory “A Test Subcategory”, then took one of the existing clip art products of the existing “apple clip art” category and added it to the “A Test Subcategory” subcategory. The new "A Test Category" showed up in the shop page, but then suddenly the new “Clip Art” parent category for the existing categories worked and showed up on the home shop page. There was something about attaching it to the “A Test Subcategory” that somehow fixed it’s ability to exist under “Clip Art”. That’s what was solved, and it’s not obvious that one would need to do that to fix the situation.

This was done on one site of mine back in March. On another site this month, it happened again. I was able to fix it again using the same method. The March situation was working with GeneratePress theme framework. The May situation was on Genesis/Mai framework.

I posted this situation on the WordPress forums at https://wordpress.org/support/topic/woocommerce-bug-involving-adding-subcategories/. Maykayo requested that I post this issue here, as she was able to re-create the issue.

**Comment by zhongruige** [comment]
Hi @DavidBorrink,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested on:

* WordPress 5.7.1
* WooCommerce 5.3.0
* Storefront theme

### Replication Steps

* With a fresh install of WooCommerce, I imported the sample products which also brought in some sample categories with it
* Verified the current category list showed correctly in the store:

<img width="1142" alt="Screen Shot 2021-05-21 at 2 19 47 PM" src="https://user-images.githubusercontent.com/71906536/119194365-2cf72600-ba40-11eb-8af2-ae5aba3824ad.png">

* I then created a new category, `New Category`:

<img width="995" alt="Screen Shot 2021-05-21 at 2 18 42 PM" src="https://user-images.githubusercontent.com/71906536/119194263-10f38480-ba40-11eb-8333-db8bb64d55d0.png">

* I proceeded to move two child categories from `Clothes` under the new `New Category`:

<img width="819" alt="Screen Shot 2021-05-21 at 2 20 00 PM" src="https://user-images.githubusercontent.com/71906536/119194386-341e3400-ba40-11eb-8339-a9774be0d888.png">

<img width="809" alt="Screen Shot 2021-05-21 at 2 19 37 PM" src="https://user-images.githubusercontent.com/71906536/119194400-3aacab80-ba40-11eb-967b-57366d6a9e03.png">

* Verified this showed as expected in the Categories list, too:

<img width="994" alt="Screen Shot 2021-05-21 at 2 20 13 PM" src="https://user-images.githubusercontent.com/71906536/119194439-4a2bf480-ba40-11eb-97f9-f87ab0d8f930.png">

* Back on the storefront, I verified the new category was added both in the category list and in the side widget:

<img width="1150" alt="Screen Shot 2021-05-21 at 2 20 23 PM" src="https://user-images.githubusercontent.com/71906536/119194509-6a5bb380-ba40-11eb-8e14-d8b200467485.png">

<img width="270" alt="Screen Shot 2021-05-21 at 2 21 47 PM" src="https://user-images.githubusercontent.com/71906536/119194517-6d56a400-ba40-11eb-90af-cf626296548b.png">

* Here's the widget setup on the WP Admin side:

<img width="459" alt="Screen Shot 2021-05-21 at 2 21 51 PM" src="https://user-images.githubusercontent.com/71906536/119194550-79426600-ba40-11eb-938c-6fd9f7335a52.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

My first guess is it could be related to the third party themes, GeneratePress or Genesis/Mai. If possible, can you test this on one of the default themes such as [Storefront](https://woocommerce.com/storefront/) or [Twenty Twenty-one](https://wordpress.org/themes/twentytwentyone/)?

Also please let me know if I missed any steps above. Providing the information below will also help us further investigate. Thank you in advance!

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by DavidBorrink** [comment]
Hi Greg,

Well, that's good to know that it doesn't happen with your situation. My situations involved 1) a migration from one shopping cart system imported into WooCommerce (on GeneratePress), and 2) a seven-year old WooCommerce setup on an existing site (on Genesis). So while your situation worked while creating a new setup, my situations involved existing setups in two forms. That's the difference, and could be a key to why this happened.

Your attempt to replicate is by setting up a new system, not working within an old system. Perhaps there's a reason that existing systems might cause the problem? Since both my situations were in different themes, it seemed to me that it was a Woo issue, not a theme issue.

**Comment by tammullen** [comment]
Hi @DavidBorrink 

Can you provide the details requested? Without this information we cannot evaluate this issue further.

**Comment by DavidBorrink** [comment]
I really don't have any details other than the examples and descriptions given above. I believe I was very thorough with them.

**Comment by tammullen** [comment]
Hi @DavidBorrink 

We requested that you provide all the information we ask for in our bug reporting template. Without this information we cannot evaluate this issue further.

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Also it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.
