### ISSUE TITLE
Невозможно разместить текст в категориях

### ISSUE THREAD

**Issue by VIKTIRI** [woocommerce/woocommerce#29874]
Невозможно разместить текст в категориях (рубриках).
При вводе текста в строку "Description" - текст не добавляется, а тот что был ранее добавленный - не редактируется.

Как решить эту проблему?

**Comment by juliaamosova** [comment]
Hi @VIKTIRI,

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

Title Translation:
> Unable to place text in categories

Body of the report translation:
> Unable to place text in categories (headings).
When you enter text in the "Description" line, the text is not added, and the one that was previously added is not edited.
>How to solve this problem?
---

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
