### ISSUE TITLE
5.3.0 crashed both my sites

### ISSUE THREAD

**Issue by Celaro** [woocommerce/woocommerce#29883]
To let you know that updating to v 5.3.0 launched 15 hours ago disabled both my sites with "there has been a critical error with this website"
My hosting support fixed it by deleting the offending plugin, which restored my sites.

I then reinstalled it OK, but as soon as I tried to activate it I got this:
![image](https://user-images.githubusercontent.com/52117437/117932699-cb0a3280-b354-11eb-84c0-dd55ef73f469.png)

Tomorrow I will try to download 5.2.2 again

**Comment by Celaro** [comment]
5.2.2 installed & activated OK with no problems, looking forward to a fixed 5.3.x

**Comment by tammullen** [comment]
Hi @Celaro 

it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by DavidAnderson684** [comment]
The error message indicates that you have two WooCommerce plugins both installed and active at the same time, stored in distinct directories.

**Comment by claudiosanches** [comment]
Hello @Celaro 

Thanks for starting this issue.

By reading this error message it's possible to determinate that you have two installations of WooCommerce, one located in `.../wp-content/plugins/woocommerce/woocommerce.php` installed by the update, and another in `.../wp-content/plugins/woocommerce.bk/woocommerce.php`.
This last one is incorrect and you should remove it by FTP or by your hosting file manager tool.
Enabling both will cause issues like that for sure, and you shouldn't rename plugins directory like that, because the WP update may cause issues like you are seeing.

I am closing this issue for now since doesn't sounds like an issue on WooCommerce. If I missed something, please leave a comment and we will take a second look.
