### ISSUE TITLE
Exclude products whose catalog_visibility is hidden in WooCommerce API

### ISSUE THREAD

**Issue by jackeychina** [woocommerce/woocommerce#29895]
I am using API - 

`https://example.com/wp-json/wc/v3/products?status=publish&per_page=100&page=1&skip_cache=1&category=250&consumer_key=<value>&consumer_secret=<value>`

Now I want to exclude all the products whose catalog_visibility is hidden. 

I have checked API doc but there is no way to filter based on this. 

Is there any way to do this ?

**Comment by juliaamosova** [comment]
Hi @jackeychina,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi there @jackeychina - while there is no documented way to do this, you can parse the list after and filter on `catalog_visibility`. I hope that helps.
