### ISSUE TITLE
Woocommerce review showing all types of comments...

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29919]
When you add custom comment_type for product for example when you install a plugin that adds product 'discussion/question' in product page. And after you uninstall that plugin, allthat question which use custom comment type will be shown in product review. 

And woocommerce show different for "review count" and review list. The review_count is already correct for only showing 'review' comment type. But the review list also show other type of comments. Making the count and list not sync.

Woocommerce should add a hook to only show their own custom 'comment_type'. In this case its 'review'.

Something like this:

```
//hook via 'woocommerce_product_review_list_args' or 'comments_template_query_args'
add_filter( 'woocommerce_product_review_list_args', function($comment_args){

    $comment_args['type'] = 'review';   //only show 'review' comment , so review list is same with review count returned by get_review_counts_for_product_ids()

    return $comment_args;
}, 10, 1 );
```

And because wp_list_comments used by 'woocommerce_product_review_list_args' cant accept array for 'type' argument. We also need to modify the code in get_review_counts_for_product_ids()

```
From:
comment_type in ( 'review', '', 'comment' )
To:
comment_type in ( 'review')
```

**Comment by juliaamosova** [comment]
Hi @erikdemarco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks, @erikdemarco! However, we will not change this due to backwards compatibility concerns: comment types are a _relatively_ new feature of WordPress and did not always exist, so we have to cater to the possibility that historic reviews exist with _no_ comment type, etc ... hence the `comment_type in ( 'review', '', 'comment' )` logic you referenced.
