### ISSUE TITLE
PHP 8.0 compatibility issue in class-wc-query.php file [fatal error]

### ISSUE THREAD

**Issue by acrolink** [woocommerce/woocommerce#29917]
I have just upgraded `PHP` from `7.x` to `8.0.5` and got the the following fatal error:

`Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /srv/wp/my-store/wp-content/plugins/woocommerce/includes/class-wc-query.php:708`

The solution is to change this line:

`return array_filter( apply_filters( 'woocommerce_product_query_meta_query', $meta_query, $this ) );`

To:

`return array_filter( [ apply_filters( 'woocommerce_product_query_meta_query', $meta_query, $this ) ] );`

i.e. wrap the `array_filter` argument with `[ ]`

Kindly review this and commit it in near future.

**Comment by juliaamosova** [comment]
Hi @acrolink,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
We discussed this one, and seems like return value of `meta_query` as null is coming from a external code when it is not supposed to be. Can you please check if there is a custom integration or a plugin that might be causing this?
