### ISSUE TITLE
Please add "Comment Type" filter for Comments

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29920]
In the new comment list page, We can now filter comment based on its type.

Please add a way to filter only woocommerce review.
Here's the sample code:

```
add_filter('admin_comment_types_dropdown', 'add_comment_type' );
function add_comment_type($args) {
        $args['review'] = __('Woocomerce Review', 'woocommerce');
        return $args;
}
```

**Comment by juliaamosova** [comment]
Hi @erikdemarco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks, @erikdemarco. We'll flag this as a future enhancement (and if you wish to, feel free to submit a PR). Minor note: we might prefer the text to read as _'Product Reviews'_ rather than _'WooCommerce Review'._

**Comment by peterfabian** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Proton-Sprints-601bf65b30b069000e1c7782/issues/woocommerce/woocommerce/29920?planning-poker) with ZenHub @vedanshujain @Konamiman @barryhughes @claudiosanches @jeffstieler
