### ISSUE TITLE
Api Product attribute terms

### ISSUE THREAD

**Issue by moonzlo** [woocommerce/woocommerce#29921]
Greetings dear developers, perhaps this repository is not suitable for describing problems with the API, but I did not find a suitable one.

I am trying to create an attribute with an image, however, the documentation does not describe the entity of the data source, whereas the product has one. The functionality itself exists by default, so why can't I attach an image using api methods?

**Comment by juliaamosova** [comment]
Hi @moonzlo,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @moonzlo—I'm not sure I understand the problem, as attributes don't support images (at least, not by default). Perhaps you are using a third party solution or custom code which has added this? 

I'll go ahead and close the issue since it doesn't look like something we can help with...if you disagree, just let me know :-)
