### ISSUE TITLE
Need help to understand the checkout field management

### ISSUE THREAD

**Issue by dennisheiden** [woocommerce/woocommerce#29947]
Related to this issue:

https://github.com/woocommerce/woocommerce/issues/23865

The required / optional status of some billing fields change depending on which country is selected.
I need really help to understand why this is a good behaviour?
If you have a shop, you mostly have some accounting or payment gateways attached which often require fields like CITY.

I mean, what do I do, when I have an international shop and people from Singapore leave the city field unfilled because it isn't required but my account software needs this field?

The second thing I don't understand why the form-billing.php template is ignored on checkout updates and fields get reshuffled via js?

I'm really confused by this and I want to understand what is going on or if I can do something better to customize the checkout form / template in a more persistent way.

I'm appreciating every thought about this.

**Comment by zhongruige** [comment]
Hi @dennisheiden,

Regarding the first question:

> I mean, what do I do, when I have an international shop and people from Singapore leave the city field unfilled because it isn't required but my account software needs this field?

In this case, this would require a custom code solution depending on which counties you want to require that field for. A code solution (along with an explanation of why this is needed) was suggested by the core team in [this comment](https://github.com/woocommerce/woocommerce/issues/29455#issuecomment-831293441) (copied below for convenience), to be added in your theme's `functions.php` file. For example, in the case of Singapore:

```php
function mark_city_required_for_singapore( $country_locales ) {
	if ( isset( $country_locales['SG'] ) && isset( $country_locales['SG']['city'] ) ) {
		$country_locales['SG']['city']['required'] = true;
	}
	return $country_locales;
}

add_filter( 'woocommerce_get_country_locale', 'mark_city_required_for_singapore' );
```

 > The second thing I don't understand why the form-billing.php template is ignored on checkout updates and fields get reshuffled via js?

This could be being caused by the theme being used. Which theme do you have currently in place? Are you seeing this with the default themes, such as Storefront or Twenty Twenty-one as well? It would be great, too, if you could provide some screenshots or steps that we could further investigate the fields being reshuffled and how the `form-billing.php` template is being ignored. Thank you!

**Comment by dennisheiden** [comment]
Need some time to test your propositions, I think we can close this for now.

Your required-function makes sense to me and might be the way.
The shuffle issue needs some digging and preparation on my side to ensure it isn't a theme related problem.

Thanks.
