### ISSUE TITLE
Missing hook for minimum quantity in admin order edit

### ISSUE THREAD

**Issue by dzunghv** [woocommerce/woocommerce#29963]
In this file /woocommerce/includes/admin/meta-boxes/views/html-order-item.php, haven't hook for the minimum quantity https://www.screencast.com/t/lPimHPRjaXc. So, it causes the issue with some plugins that can help modify the minimum/step/maximum quantity. E.g WPC Product Quantity.

With this plugin, you can set the minimum 1 and step is 2.5, so the buyer can buy the amount of 3.5. But in the admin order edit, the step is a fixed value (zero). Now the minimum is 0 and the step is 2.5. So the 3.5 is incorrect and I can't update the order status https://www.screencast.com/t/GRdgiUtG0

Hope it will be changed from:
`min="0"`
to:
`min="<?php echo esc_attr( apply_filters( 'woocommerce_quantity_input_min', '0', $product ) ); ?>"`

**Comment by rodelgc** [comment]
Hi @dzunghv ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @dzunghv, thanks for the report. I've confirmed that the combination of the default minimum of "0", in combination with the step value from the filter can result in buggy validation for refunds. Thanks for your suggestion to make minimum filterable, but that may lead to issues with partial refunds, and backwards-compatibility, since that filter key is used elsewhere throughout WooCommerce. We'll discuss this further, for now I'm confirming this as a bug, and giving it high priority, thanks for the report.

**Comment by jonathansadowski** [comment]
Further discussion on p1625775163272400-slack-C0E1AV8T0

**Comment by vedanshujain** [comment]
We discussed it, and we would be adding two filters for step and min just for admin view to prevent any backward compat issues. We would still keep the existing step filter as well.
