### ISSUE TITLE
Product Image Meta data export/import

### ISSUE THREAD

**Issue by imacg123** [woocommerce/woocommerce#29973]
I'm exporting products by Category to various niche sites from a main site, using the built-in Export/Import process in Woocommerce, and I noticed that product images get copied over but without Alternative Text and Description information.

I had spent the time inputting this data on the main site for SEO purposes and now need to re-do this for product images on my niche sites.

If I do a Media Library export I can get the images over with the data intact but when I do the product csv import it overwrites the images and removes the meta data. The only other solution I have currently is to do the product  import first, delete the images and then import the media library xml again and thus I have the data I require for each image, but then have to go and re-assign images to each product.

So either the meta data has to be re-done image by image, or the products need to be re-mapped to their images one by one, which seems the lesser of the two, work wise.

It would therefore be great if the product import/export process was able to grab and copy over the image meta data if it exists.

**Comment by rodelgc** [comment]
Hi @imacg123,

Instead of doing a product CSV import first, I would suggest importing the images first (together with their metadata like alt-text, description, etc.) into the Media Library of the niche site. And then on your product CSV file, use the filename of these images instead of their URL. And then go import the products CSV. This way, your products will automatically be mapped to the correct images in the Media Library. This information can be found in this [documentation](https://docs.woocommerce.com/document/product-csv-importer-exporter/#section-3) (the third bullet point).

> when I do the product csv import it overwrites the images and removes the meta data

This shouldn't happen if you import the Media Library first before importing the products CSV as I mentioned above. I double-checked this behavior on my end, and nothing got overwritten in my Media Library. Here are the steps I took:

1. Currently, my Media Library and Products list are empty.
1. I uploaded a single product using the Product CSV Importer. Here's the CSV file that I used. Notice that I've set the product image to be an external URL:
    [sample_products_main.csv](https://github.com/woocommerce/woocommerce/files/6559799/sample_products_main.csv)
1. Then I went to the Media Library and added these metadata:
    <img width="660" alt="Screen Shot 2021-05-28 at 5 22 09 PM" src="https://user-images.githubusercontent.com/4509348/119962131-516f7700-bfd9-11eb-8fd1-a8985bc06a8f.png">

1. I went back to `Products > All Products` page and removed the product that I imported earlier. At this point, I'm simulating being in the niche site, where the Media Library had already been populated, but the Products list is still empty.
1. I imported this product CSV file. Notice that instead of the external URL, I specified the filename of the image in the Media Library:
    [sample_products_niche.csv](https://github.com/woocommerce/woocommerce/files/6559852/sample_products_niche.csv)

1. After the product import, I went back to the Media Library and verified that the metadata of the image are still present.
1. I viewed the product from the customer site, and verified that all metadata were preserved:
    <img width="1223" alt="Screen Shot 2021-05-28 at 5 25 43 PM" src="https://user-images.githubusercontent.com/4509348/119963061-40733580-bfda-11eb-8992-1d5ee0c408bc.png">

> It would therefore be great if the product import/export process was able to grab and copy over the image meta data if it exists.

There had been an [earlier discussion](https://github.com/woocommerce/woocommerce/issues/16669#issuecomment-326541776) on whether to include image metadata when importing products. But as mentioned in the thread, we won't be supporting it for the meantime.

Let me know if the workaround I mentioned above works for you. I'll keep this issue open for further feedback.

**Comment by imacg123** [comment]
Hi  rodelgc,

this looks just the job, I will give it a go and get back to you...!

thanks,

imacg123


Iain MacGillivray

mobile: 0776 8818 773

**Comment by simplysaru** [comment]
Hi @rodelgc 

Did the suggestions work for you?

Look forward to your feedback. Thanks.
