### ISSUE TITLE
Server error when attempting to make virtual downloadable products thumbnails visible in the media library

### ISSUE THREAD

**Issue by battouly** [woocommerce/woocommerce#29988]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Virtual downloadable products do not show thumbnails in the media library (including for admins). Technically, that's on purpose, I guess for security purposes. However, that comes across as an overkill, the site admin at least should be able to see all the images in the media library.

The concern was raised in this forums topic: 

- https://wordpress.org/support/topic/thumbnails-of-downloadable-product/#post-14424954
I shared the snippet below to display all thumbnails but then the `403` server error happened.

`add_filter( 'wp_prepare_attachment_for_js', function($response) {
	if ( isset( $response['url'] ) && isset( $response['full'] ) ) {
		$response['full']['url'] = $response['url'];
		if ( isset( $response['sizes'] ) ) {
			foreach ( $response['sizes'] as $size => $value ) {
				$response['sizes'][ $size ]['url'] = $response['url'];
			}
		}
	}
	return $response;
} ,999, 1);`

**Expected behavior**
The snippet is a workaround to make all images visible in the media library to everyone.

**Actual behavior**

A server error is displayed in the browser console and blank thumbnails appear in the media library.

Error: `Failed to load resource: the server responded with a status of 403 ()`

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to WordPress admin dashboard 
2. Add the snippet above via a plugin such as this one: https://wordpress.org/plugins/code-snippets/
3. Add a new downloadable image via a virtual downloadable product (upload a fresh image)
4. Visit the media library and inspect the page to check the browser console.
4. See error from console and the blank thumbnail.

**Screenshots**

<img width="624" alt="Screenshot on 2021-05-21 at 13-06-59" src="https://user-images.githubusercontent.com/13640239/119661223-994a9e80-be1f-11eb-8574-54bfcc68f346.png">

![Annotation on 2021-05-26 at 12-42-59](https://user-images.githubusercontent.com/13640239/119661579-f47c9100-be1f-11eb-892c-9449f6ce5854.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
### WordPress Environment ###

WordPress address (URL): https://myfacebookwootest.mystagingwebsite.com
Site address (URL): https://myfacebookwootest.mystagingwebsite.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔
```
</details>

**Comment by tammullen** [comment]
Hi @battouly ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Thanks for the report @battouly!

It looks like there are two underlying issues here:

1) Adding a new image when creating a virtual downloadable product results in the image not being viewable to admins within the gallery.

Steps to reproduce:
* Create a new virtual, downloadable product.
* When creating the product, "Add File", and then upload a **new** image when selecting "Choose File"...
![image](https://user-images.githubusercontent.com/363749/123305057-4aa72780-d4e5-11eb-8172-1e5bb6700e37.png)
* After creating the product, return to the gallery, and note that the image you uploaded isn't visible, and instead you see the default thumbnail:
![image](https://user-images.githubusercontent.com/363749/123305292-8fcb5980-d4e5-11eb-92aa-272a4d53500f.png)


2) The issue you with the forbidden message appearing in the console when applying the work-around appears to be related to some configuration of the server, in `htaccess` or otherwise. When I applied the work-around you provided, I actually didn't see any error in the console, and the image appeared in the gallery as expected. I don't think there's anything we can do to address this problem in the context of this issue.

I'm going to leave this issue open so that we can properly address the former issue, and because of the inability of admins to see images they added within the gallery, I'm going to bump it to high priority. Thanks for the detailed report!

**Comment by singhpaul** [comment]
This issue persists for us and does not appear resolved. 

The problem is that downloadable files are saved in the `/wp-content/uploads/woocommerce_uploads/` directory which contains an `.htaccess` file placed by WooCommerce with a directive to `deny from all`. 

This is so that users who haven't purchased a product can't just access the file directly by typing in its URL. 

The problem is that the WP media library does not do any fancy magic when displaying thumbnails and they're just displayed as simple html `<img>` entities. But the user's browser is denied access to the file because of the `.htaccess` directive. 

This results in several issues:

1. Even administrators can't see thumbnails for downloadable files in the Media Library
2. If using Apache, each file generates its own `client denied by server configuration` error in the web server log
3. If the user is using `fail2ban` with `apache-auth` jail to ban bad actors and there are many downloadable files on a Media Library page the user can inadvertently ban themselves from their own website. This has happened to multiple clients recently. 

While there might not be an easy/obvious solution, it doesn't seem accurate to say that this isn't a bug and there's nothing to be done. 

One solution, though seemingly not ideal, might be to use the same PHP file handler used with the Force Downloads option to serve downloadable files in the Media Library. I imagine this could have some performance issues and would require some sort of hook to check each media library file to see if it's in the `woocommerce_uploads` directory and serve it via the PHP handler.

**Comment by joekhartley** [comment]
I just want to echo the comments of @singhpaul on all three of his points, each of which I'm struggling with.

Download item thumbnails not appearing in the Media Browser is confusing from a usability perspective and feels broken to the user because it deviates from the expected upload experience without any indication of why they don't appear. This is where I'd hope it falls into 'Bug fix' territory for WC. 

The Fail2Ban IP issue is a big concern though, which for me resulted in Fail2Ban locking me out of our VPS for a while when I was figuring out why images weren't loading.

I know F2B is a third party app and is not something WC will directly be concerned about, but it highlights a flaw that could cause concern for many who choose WC _(given Plesk's market share)_. My WC clients will all be managing their sites from dynamic IP addresses I can only assume this will be an ongoing issue if they view the media library containing numerous downloadable product files.

**Comment by petertwise** [comment]
@Konamiman @roykho - What's the policy if we are still experiencing this issue? Should we open a new issue since this one is old and was marked closed, or is it possible to have an admin open this issue again?

We are also still experiencing the image issues and Fail2ban lockouts described by @joekhartley  and @singhpaul. We have a temporary fix with filters (thank you @basscl ) to show a fallback instead, but it would be good to have a long term solution implemented in WC core that addresses this.

**Comment by basscl** [comment]
fyi we're currently fixing by removing those changed filters and re-adding them in the previous version:
```
/**
* REVERT BREAKING WOOCOMMERCE FILTERS  in woocommerce/includes/wp-product-functions.php
* added in https://github.com/woocommerce/woocommerce/pull/30385
*/

/**
 * Prepare attachment for JavaScript.
 *
 * @param array $response JS version of a attachment post object.
 * @return array
 */
function fix_wc_prepare_attachment_for_js( $response ) {
	/*
	 * If the user can manage woocommerce, allow them to
	 * see the image content.
	 */
	if ( current_user_can( 'manage_woocommerce' ) ) {
		//return $response;
	}

	/*
	 * If the user does not have the right capabilities,
	 * filter out the image source and replace with placeholder
	 * image.
	 */
	if ( isset( $response['url'] ) && strstr( $response['url'], 'woocommerce_uploads/' ) ) {
		$response['full']['url'] = wc_placeholder_img_src();
		if ( isset( $response['sizes'] ) ) {
			foreach ( $response['sizes'] as $size => $value ) {
				$response['sizes'][ $size ]['url'] = wc_placeholder_img_src();
			}
		}
	}

	return $response;
}
remove_filter( 'wp_prepare_attachment_for_js', 'wc_prepare_attachment_for_js' );
add_filter( 'wp_prepare_attachment_for_js', 'fix_wc_prepare_attachment_for_js' );

/**
 * Get attachment image attributes.
 *
 * @param array $attr Image attributes.
 * @return array
 */
function fix_wc_get_attachment_image_attributes( $attr ) {
	/*
	 * If the user can manage woocommerce, allow them to
	 * see the image content.
	 */
	if ( current_user_can( 'manage_woocommerce' ) ) {
		//return $attr;
	}

	/*
	 * If the user does not have the right capabilities,
	 * filter out the image source and replace with placeholder
	 * image.
	 */
	if ( isset( $attr['src'] ) && strstr( $attr['src'], 'woocommerce_uploads/' ) ) {
		$attr['src'] = wc_placeholder_img_src();

		if ( isset( $attr['srcset'] ) ) {
			$attr['srcset'] = '';
		}
	}
	return $attr;
}
remove_filter( 'wp_get_attachment_image_attributes', 'wc_get_attachment_image_attributes' );
add_filter( 'wp_get_attachment_image_attributes', 'fix_wc_get_attachment_image_attributes' );
```

**Comment by roykho** [comment]
@petertwise - I would suggest you open a new issue and give as much detail as possible.

**Comment by basscl** [comment]
new issue opened here: https://github.com/woocommerce/woocommerce/issues/35166
