### ISSUE TITLE
I cannot change the variable product price.

### ISSUE THREAD

**Issue by kogawillian** [woocommerce/woocommerce#29998]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
It is not possible to change the price of variable products, the general tab in product data does not appear. 

**Expected behavior**
make the change in a simple way as in products without variations.

**Actual behavior**
The general tab is not displayed in the product data table, when the product is variable, only when the product is simple. Thus, it is impossible to change the value and other product data contained in this tab. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Products'
2. Click on 'Edit'
3. Scroll down to 'Product data'
4. do 'change product type from simple to variable'
4. See error ' the general tab (where you can edit the price) disappears. '

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @kogawillian 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

It will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by CarlotaCunha** [comment]
Hi, 

Did anybody managed to solve this issue? i am having the same problem, also tried to deactivate all the plugins and change theme, and nothing.

Thanks
