### ISSUE TITLE
[5.4 beta]: Fatal error: Uncaught TypeError: Unsupported operand types: string + string

### ISSUE THREAD

**Issue by reyrahn** [woocommerce/woocommerce#29994]
Uncaught TypeError: Unsupported operand types: string + string in /wp-content/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php:942

**Comment by tammullen** [comment]
Hi @reyrah

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

A clear and concise description of what actually happens and steps to reproduce this error. Please be as descriptive as possible; 

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.
