### ISSUE TITLE
woocommerce automatically log people out when entering the main page 

### ISSUE THREAD

**Issue by nimx202** [woocommerce/woocommerce#30007]
woocommerce is automatically logging me out when entering the main page 

https://user-images.githubusercontent.com/65628318/120118097-17e16c00-c191-11eb-8174-26da88d308ee.mp4

**Comment by tammullen** [comment]
Hi @nimx202 

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.
