### ISSUE TITLE
Out of Stock Threshold changes don't affect existing variable products

### ISSUE THREAD

**Issue by somethumb** [woocommerce/woocommerce#30002]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

We had set the Out Of Stock Threshold at 1, and then we confirmed that one of the variations of our variable products had shown Out Of Stock. However, we decided to change the threshold to 0. Then we checked the variation on the front end and it still showed Out Of Stock. We confirmed the variation is set to In Stock and there's 1 available. I saved the product again and it still showed Out Of Stock on the front end.

So I edited the variation by changing the stock amount to 7, saved it. And it showed In Stock in the front. Then I changed the variation to 2, and it showed Only 2 Left on the front end (we have the low stock set at 4). Then I changed it back to 1, and it showed IN STOCK on the front end. 

Perhaps when changing the Out Of Stock threshold, it doesn't affect products and/or variations that have already met that threshold.

**Comment by tammullen** [comment]
Hi @somethumb ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
