### ISSUE TITLE
Product Schema

### ISSUE THREAD

**Issue by ProArtur** [woocommerce/woocommerce#30018]
Hello Artur,

Thanks for writing back

I am Avinash from the Astra team and would like to help you with your queries.

I tested your site URL on the Structured Data Testing Tool site, and I can see warnings on the page.

Please refer to the screenshot - https://share.bsf.io/04u214Ak.

Further, I can confirm the Schema is not added from the Astra theme.

Here is an article with the list of Schema added from the Astra theme. Please have a look.
- https://wpastra.com/docs/disable-schema-markup/.

Furthermore, the Product Schema data is in a JSON -LD format and the WooCommrece plugin adds the Product SChema on JSON -LD format. 

Now to resolve the warnings, I would suggest you contact once with the WooCommrece plugin author.

I hope you understand. If you need anything else we can help you with, write to us.

Products - problems found on the website https://sklep-prodetektyw.pl/
To the owner of the website https://sklep-prodetektyw.pl/:
Search Console found issues with your site (Number: 4, Type: Products):
The most important warnings
Warnings suggest improvements. Some help to improve the visibility of pages in the search engine, while others may become errors in the future. Warnings found on your site:
Missing field "aggregateRating"
A global identifier (such as GTIN, MPN, or ISBN) was not specified
Missing "review" field
Missing "brand" field
We recommend that you fix these issues as soon as possible. This will make your site comfortable to use and ○ well visible in ○ Google Search.

**Comment by tammullen** [comment]
Hi @ProArtur 

Hi {username},

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ProArtur** [comment]
The report, scan and files from GSC are attached. Shows that there is 3 items error all the time, cart, order and login. It is the fault of Astra's theme where they referred me to you.

**Comment by tammullen** [comment]
Hi @ProArtur 

Can you provide the details requested? Without this information we cannot evaluate this issue further.
