### ISSUE TITLE
Reported issue

### ISSUE THREAD

**Issue by saschaludwig** [woocommerce/woocommerce#30048]
📝 Content removed, see discussion below.

**Comment by zhongruige** [comment]
Hi @saschaludwig,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for the report! This needs to be addressed and is actually on our radar already (team members, please see internal link above).

**Comment by barryhughes** [comment]
@saschaludwig—thanks again for reporting this. I've edited the title and description as this is a security related issue. Please note (in case you notice any similar problems in the future) that we prefer this sort of report to be made via [HackerOne](https://www.hackerone.com/). Thank you!

**Comment by saschaludwig** [comment]
So is this issue actually solved and if, in which release?

**Comment by barryhughes** [comment]
It's not solved, we just preferred to remove the details from the report.

**Comment by saschaludwig** [comment]
Okay, will it be fixed? And why did you decided to close the issue if it is still present? How do I know when the issue is resolved?

**Comment by saschaludwig** [comment]
So, do you say I should re-open the issue on HackerOne?

**Comment by barryhughes** [comment]
Sorry for any confusion. Let me clarify:

* Yes, this is part of an issue we already know about and intend to resolve. 
* It was already reported one HackerOne, by another user, so you don't need to report it there a second time—but of course you can if you wish to (and perhaps the HackerOne triage team can link your report with the existing one).
* In this specific case, you should see updates in the changelog once the fix is released. 
* For ref, please also see [this doc](https://github.com/woocommerce/woocommerce/blob/5.4.1/SECURITY.md).
