### ISSUE TITLE
Sale price not show if sale date was planned

### ISSUE THREAD

**Issue by grom193** [woocommerce/woocommerce#30051]
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php
method get_price_html not work properly if i created a planned sale.

For example, today i was created sale for some product that  sale should star tomorrow. For next day i checked sale price for my product and i saw 
https://tinyurl.com/y6nsdkcm

https://tinyurl.com/y5acbg33

**Comment by zhongruige** [comment]
Hi @grom193,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I performed my testing on the following:

* WordPress 5.7.2
* WooCommerce 5.3
* Storefront theme

**Replication steps**

* I created a basic simple product with a regular price of $10.99
* On 2021-06-08, I added a sale price of $5.99, scheduled to start the following day

<img width="1108" alt="Screen Shot 2021-06-09 at 11 03 16 AM" src="https://user-images.githubusercontent.com/71906536/121398172-4f2ee600-c912-11eb-894a-dabffd48064f.png">

* On the following day, 2021-06-09, I came back to view the product and verified the sale price was displayed as expected on the storefront:

<img width="1661" alt="Screen Shot 2021-06-09 at 10 36 55 AM" src="https://user-images.githubusercontent.com/71906536/121398239-6077f280-c912-11eb-8119-5871d937e48f.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

For example, this could be due to caching in the browser when viewing the page. Please try one of the following and let us know if you are still seeing the issue:

* Loading the product page in a private browsing window
* Loading the product page in a different browser
* Performing a hard refresh on page if it's in the same browser window

Additionally, this could be an issue with the theme. If you switch to Storefront or the Twenty Twenty-one theme, does the issue still persist?

Also for bug reports we do require more details as part of the report, as without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

Thank you!
