### ISSUE TITLE
process_order_without_payment function call wc_empty_cart so session not cleared  

### ISSUE THREAD

**Issue by comddol** [woocommerce/woocommerce#30053]
woocommerce version: 5.3.0
file: class-wc-checkout.php

from
	protected function process_order_without_payment( $order_id ) {
		$order = wc_get_order( $order_id );
		$order->payment_complete();
		wc_empty_cart();
                        :

to
	protected function process_order_without_payment( $order_id ) {
		$order = wc_get_order( $order_id );
		$order->payment_complete();
		WC()->cart->empty_cart(true);
                        :

wc_empty_cart() call WC()->cart->empty_cart(false) not empty_cart(true),
so session remain, customer can see the remained cart order.

**Comment by zhongruige** [comment]
Hi @comddol,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi @comddol - from looking at the logic, it all seems correctly implemented. It is clearing the session from the items added but not necessarily removing them from the database unless `true` is explicitly passed in. In many cases, that is the expected behavior.

Perhaps you can give us a full detail as to what you're trying to do in what context and order which can help us better understand what is it that you need?

**Comment by aheckler** [comment]
User in 4288348-zen brought up a scenario that may cause this. I've asked them to have the devs from XLPlugins leave a comment here with more technical detail on the problem.
