### ISSUE TITLE
[wc 5.4 rc] new product attributes lookup table gets created but isn't filled (should we enable this new feature in live sites?)

### ISSUE THREAD

**Issue by Danielspain22** [woocommerce/woocommerce#30058]
**Prerequisites (mark completed items with an [x]):**
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
New product attributes lookup table gets created but isn't filled with my products
I've tried to follow #29190, but i don't understand why it doesn't gets filled or if is it meant for live sites or not.

**Expected behavior**
I've tried to test how the new lookup table wp_wc_product_attributes_lookup is constructed and populated, but it doesn't gets filled

**Actual behavior**
wp_wc_product_attributes_lookup gets created in database, the message "The table Product attributes lookup table is being filled" appears in tools after enabling the feature, it completes after increases from 0 to hundreds of my products, action scheduler finishes the queue with all the  tasks "woocommerce_run_product_attribute_lookup_update_callback" with no error, _but the table is empty after all this_. (no errors or warnings in php logs, woocommerce logs, database, etc.)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I've followed https://github.com/woocommerce/woocommerce/pull/29778
but i don't understand this:

"Entries should have been created for all the existing products..."
But later, it mentions the proof of concept where the products are imported from a csv...
**Is this feature ready to fill the table with the current products of a site?? Should I modify my woocommerce.php to enable it in production sites or not at this stage?** 
Sorry if i misunderstood this(i'm confused with a feature that is in testing but also shipped in upcoming final release...)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.7.2
PHP 7.3
Database verified ok with wc tools 
Twenty Twenty-One Theme
No other plugins active

**Comment by zhongruige** [comment]
Hi @Danielspain22,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
Hi @Danielspain22, thanks for your input.

The product filtering by attributes using a lookup table is a complex feature and so we are implementing it incrementally. https://github.com/woocommerce/woocommerce/pull/29778 is just the first of these increments and it's not really useful by itself, so no, it's NOT supposed to be enabled in live sites (that's why it needs running the `show_feature` method and then triggering the table creation via tools page). And even when it's enabled, with that pull request alone the lookup table is not used for anything anyway.

My recommendation is to wait until the feature is completed and then test it in full; even after it's completed we're going to still have it as an "opt-in" feature initially (so it still will have to be explicitly enabled) so that we are sure that it's working properly before we roll out it to everyone.

That said, maybe you seeing the table empty due to how the tools page work. When you click the "regenerate table" action and then reload the page, the URL in your browser will still have the `action=regenerate_product_attributes_lookup_table` part, and thus if the process had finished then it will start again.

**Comment by Danielspain22** [comment]
Thank you very much for clarifying the issue. The woo team always responds quickly and clearly, it is very important to us.

**Comment by Konamiman** [comment]
Great. I'm going to close the issue for now then.
