### ISSUE TITLE
When 'Free Shipping' is enabled as a shipping option conditional to $70+ order, Flat Rate is selected by default instead.

### ISSUE THREAD

**Issue by pranavmtn** [woocommerce/woocommerce#30055]
Hi,

Free shipping is not enabling for the site,even it is available.Instead Flat rate is choosing.

I could see similar topics on https://github.com/woocommerce/woocommerce/issues/25471,but there is no any proper solution.

And it is happening for random orders.

Screen shot:https://prnt.sc/14i107h

Any idea,what might caused this?

Thanks

**Comment by zhongruige** [comment]
Hi @pranavmtn,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further. So far, it is working as expected on my end. I followed the steps below:

* On a new install of WooCommerce 5.3 with the Storefront theme I set up the following shipping options:

<img width="1424" alt="Screen Shot 2021-06-08 at 3 02 58 PM" src="https://user-images.githubusercontent.com/71906536/121261307-cd867c00-c86f-11eb-97ec-5b2d3c17351c.png">

<img width="1410" alt="Screen Shot 2021-06-08 at 3 43 45 PM" src="https://user-images.githubusercontent.com/71906536/121261740-556c8600-c870-11eb-83d7-9c320f0bfae0.png">

* I went and placed an order and saw the Free Shipping option selected and the default on an order over $70:
 
<img width="843" alt="Screen Shot 2021-06-08 at 3 02 38 PM" src="https://user-images.githubusercontent.com/71906536/121261295-c95a5e80-c86f-11eb-9b48-a6027cc2d63d.png">

It will help to know, for example if there's any plugins that are being used and if the bug still persists once those plugins have been disabled. Additionally, it will be helpful if you can provide information on the following shipping settings:

* Under `WooCommerce > Settings > General`:

<img width="691" alt="Screen Shot 2021-06-08 at 3 40 32 PM" src="https://user-images.githubusercontent.com/71906536/121261530-176f6200-c870-11eb-8909-786b33055470.png">

* Under `WooCommerce > Settings > Shipping > Shipping options`:

<img width="919" alt="Screen Shot 2021-06-08 at 3 40 46 PM" src="https://user-images.githubusercontent.com/71906536/121261554-1cccac80-c870-11eb-886d-3cf3e5fcce97.png">

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
