### ISSUE TITLE
Duplicate H1 tags across multiple Commerce Category pages

### ISSUE THREAD

**Issue by simona6** [woocommerce/woocommerce#30065]
We have noticed, via an SEO report, that all categories across what appears to be nearly all themes we have tested this on, have duplicate H1 tags.

If you have a Category for Men's T-Shirts, with 30 pages.  Each page has the same H1 tag... Men's T-Shirts.  29 duplicate H1 tags.  Surely Page 2 onwards should show: "Men's T-Shirts - Page 2"?

Even with canonicalisation, this is incorrect, when you have page numbering.

How can this be resolved?  Seems strange that a major SEO flaw like this... is standard.

**Comment by juliaamosova** [comment]
Hi @simona6,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by simona6** [comment]
Hello there.

The bug is such a simple one to spot on any Woocommerce website.

Here is an example:
https://www.marinefishshop.co.uk/maintenance/

Go to the bottom of the page and click on page 2, then page 3…
Or try most other WC  powered websites.  The issue is, the main title – the H1 of the page.  No two pages should have the same H1 tag.  And yet, every single Page of any category is the same.

If you have 20 pages of ‘Maintenance’ on this website, you have 20 pages that all have the same H1 “maintenance” keyword.

Surely it should be Maintenance – pg 2. ??

Regards

Simon

**Comment by simplysaru** [comment]
@simona6 

Thanks for the example. marinefishshop.co.uk/maintenance

I don't this is a WooCommerce behaviour, but a WordPress one. WooCommerce borrows the category functionality from WordPress. You can notice the same H1 tag behaviour for blog posts as well. 

example here. 
https://www.marinefishshop.co.uk/blog/category/shop-news/

If this is a concern, please report this issue in the WordPress core repository.

Note: 

I updated your response to clean up for meta content from your email response. This content was removed. https://d.pr/i/d99ad1
Feel free to just send in a reply without the email meta next time. Thanks.
