### ISSUE TITLE
Value limit 200 characters for woocommerce attribute value

### ISSUE THREAD

**Issue by manjeet8562** [woocommerce/woocommerce#30063]
Someone can help here how can we support more than 200 characters in the attribute value.

I am creating a website and i am storing all the custom data as attribute and some of the attributes expect large amount of data like a paragraph so is there any way to support it without editing the plugin files.

Thanks in advance :)

**Comment by juliaamosova** [comment]
Hi @manjeet8562,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @manjeet8562 
Can you confirm what attributes are you talking about? For example, product attributes are stored in WordPress's core tables which are not recommended at all to be modified.

Taking a step back though:
> storing all the custom data as attribute

this doesn't sound right. if they would be paragraphs, maybe they should be stored in a different or in a meta table instead?

Note that we use Github for bug tracking purposes, so generally won't be able to provide custom development support on this forum.
