### ISSUE TITLE
Core Bug: Woocommerce Admin User Country influence orders

### ISSUE THREAD

**Issue by FITZKRAWALLDO** [woocommerce/woocommerce#30088]
Dear Team!

We found a bug in your core plugin. If we logged in backend and when we create a new order. The tax on this specific order we created manually is set to the country of our admin user country.

So if we create a new order with country "Germany" and our admin user profile is set to "Austria" the tax on all orders we create manually per backend are like Austria and NOT like the order country.

Tested on: Woocommerce 5.4.1 + Clean Wordpress 5.4.x

**Comment by lkraav** [comment]
If you can also swing a short screencast proof, it often helps expedite getting attention :+1:

**Comment by FITZKRAWALLDO** [comment]
Hey Ikraav,

your are right!

Simple example:

**`add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' );`**
= Set all prices to e.g. 20 including tax. Totally doesn't matter which country we sell to. No matter what taxes are set. The prices are always the same. Germany with 19% = 10€. Austria with 20% = 10€ gross price.

But, and this is the bug:

If we add a order by backend the base prices of the product will be calculated of the country of the admin user (not the order countrys and so on).

We need to remove the whole filter, so that the base prices of the prodcuts will be generated by the order shipping/billing country again.

**Comment by juliaamosova** [comment]
Hi @FITZKRAWALLDO,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by FITZKRAWALLDO** [comment]
#reopen
