### ISSUE TITLE
Error importing csv product import, image error

### ISSUE THREAD

**Issue by Serafim1994** [woocommerce/woocommerce#30090]
![Opera Snapshot_2021-06-11_190646_unchiugadget ro](https://user-images.githubusercontent.com/85785065/121771054-b26c8280-cb75-11eb-8db6-290e6606b847.png)
Whenever I try to upload an image I get this error, before I got the error "Sorry, this file type is not allowed for security reasons", but now it has been resolved, now I get the text with "I can't attach"

**Comment by Serafim1994** [comment]
Whenever I try to upload an image I get this error, before I got the error "Sorry, this file type is not allowed for security reasons", but now it has been resolved, now I get the text with "I can't attach"

**Comment by Serafim1994** [comment]
I did what he says here
https://woocommerce-manager.com/useful-articles/how-tos/fix-woocommerce-import-error-sorry-this-file-type-is-not-permitted-for-security-reasons/

**Comment by Serafim1994** [comment]
But nothing was resolved

**Comment by juliaamosova** [comment]
Hi @Serafim1994,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
