### ISSUE TITLE
Hangs up at 91% on Square

### ISSUE THREAD

**Issue by Obijaun** [woocommerce/woocommerce#30106]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
X  I have have carried out troubleshooting steps and I believe I have found a bug.
X  I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I click sync for the Square plugin. It hangs up at 91% every time. 

**Expected behavior**
I want it to sync without getting hung up. 

**Actual behavior**
The manual sync will hang up and stop working at 91%.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Settings in Woocommerce
2. Click on Square tab
3. Click on Update
4. Click on Sync Now
4. See error when at 91% synced

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @Obijaun,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [Square for WooCommerce](https://woocommerce.com/products/square/) plugin which is one of the products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
