### ISSUE TITLE
Product price rounding bug

### ISSUE THREAD

**Issue by jkonet** [woocommerce/woocommerce#30159]
If tax-option "No, I will enter prices exclusive of tax" is selected, "Round tax at subtotal level, instead of rounding per line" is not selected and product price is 44,355e (excl. tax), Woocommerce product-page show price 55,01e despite that 44,355*1,24 is 55,0002. Tax percent is 24%.

If option "Round tax at subtotal level, instead of rounding per line" is not selected, then Woocommerce show 55,00e price.

Is this bug or is there some reason why Woocommerce rounding price up in this case?

**Comment by rodelgc** [comment]
Hi @jkonet,

Thank you for submitting this issue. However, some of the steps you gave are quite confusing:

> "Round tax at subtotal level, instead of rounding per line" is not selected and product price is 44,355e (excl. tax), Woocommerce product-page show price 55,01e

On the first line, you mentioned that when the checkbox is **not selected**, you see the total to be 55,01 €.

> If option "Round tax at subtotal level, instead of rounding per line" is not selected, then Woocommerce show 55,00e price.

Then on the second line, you mentioned that when the checkbox is **not selected** (just like in the first line), then you see the total 55,00 €.
So I would like to clarify which setting do you see those 2 prices?

Take note by the way that the "Round tax at subtotal level, instead of rounding per line" option will really sometimes produce different totals depending on whether you selected it or not.

For example, these are the product price and tax rate you gave:
Product price (excl. tax): 44,355 €
Tax rate: 24%
Quantity: Let's say the customer would like to order just 1 unit of this product.

If "Round tax at subtotal level, instead of rounding per line" is unchecked, we round off each "line" first (the product line item and the tax component) before adding them all together. So the computation will be:
```
Line item total = 44,355€ * 1 unit = 44,355
Line item after rounding off = 44,36 €
Tax component before rounding off = 44,36 * 24%  = 10,6464 €
Tax component after rounding off = 10,65 €
TOTAL = sum of each rounded off line item = 44,36 + 10,65 = 55,01 € 
```
We arrive at a total of 55,01€ which is the correct total shown on the cart page when I tested it:
<img width="892" alt="Screen Shot 2021-06-25 at 6 11 52 PM" src="https://user-images.githubusercontent.com/4509348/123410181-99d28280-d5e1-11eb-99a0-c4725e7f2633.png">
<img width="1351" alt="Screen Shot 2021-06-25 at 6 12 27 PM" src="https://user-images.githubusercontent.com/4509348/123410220-a48d1780-d5e1-11eb-9af8-3965f06babc4.png">

But when you check the "Round tax at subtotal level, instead of rounding per line" option, we add the line items together (retaining their decimal digits) before we round off their sum. Therefore, the computation would be:
```
Line item total = 44,355€ * 1 unit = 44,355
Tax component = 44,355 * 24% = 10,6452
Total = sum of each line item retaining all decimal digits = 44,355€ + 10,6452€ = 55,0002€ rounded off to 55,00€
```
In this case, we arrive at a total of 55,00€ which is the correct value I saw in my test:
<img width="702" alt="Screen Shot 2021-06-25 at 6 30 27 PM" src="https://user-images.githubusercontent.com/4509348/123411999-ac4dbb80-d5e3-11eb-8bdd-fca74511aedd.png">
<img width="1276" alt="Screen Shot 2021-06-25 at 6 31 00 PM" src="https://user-images.githubusercontent.com/4509348/123412019-b1126f80-d5e3-11eb-9f48-7736412788ab.png">

I hope this sheds some light on how the `Round tax at subtotal level, instead of rounding per line` works.

For now, I will leave this issue open with a `needs feedback` label so that you could give clarification to the question I posted at the beginning of this comment. Thanks!

**Comment by jkonet** [comment]
Hi, sorry there is typo in part "If option "Round tax at subtotal level, instead of rounding per line" is not selected, then Woocommerce show 55,00e price." I mean "selected", not "not selected"

Thanks for answer. Price is 55,01e because Woocommerce make rounding for both tax and excl. tax separately.

Find out also strange behavior in shopping cart subtotal-price when "If option "Round tax at subtotal level, instead of rounding per line" is not selected and "No, I will enter prices exclusive of tax" is selected.

If there is one product in shopping cart, product price and subtotal is same 55,01e

Two products: price 55,01e, subtotal 110,00e instead of 110,02e
Three products: price 55,01e, subtotal 165,01e instead of 165,03e
Four products: price 55,01e, subtotal 220,00e instead of 220,04e
Five products: price 55,01e, subtotal 275,00e instead of 275,05e

**Comment by barryhughes** [comment]
So noting first of all that those findings match the logic @rodelgc already described a little earlier.

> Find out also strange behavior in shopping cart subtotal-price
> ...
> Three products: price 55,01e, subtotal 165,01e instead of 165,03e

Understood, but it is not clear to me if you are suggesting `165.03` is actually preferred/correct or if the concern is more one of potential customer confusion?
