### ISSUE TITLE
We don´t receive notications whern someone start a warranty process or send a warranty message.

### ISSUE THREAD

**Issue by ilmoti** [woocommerce/woocommerce#30152]
We don´t receive notications whern someone start a warranty process or send a warranty message.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
We can´t use the pluggins like this because many times clients start a proces of refound and we didn´t find out unless the client contact us-

**Expected behavior**
We should receive message notification by email when someone start a warranty process or send a new message.

**Actual behavior**
nothing happend.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment]
Hi @ilmoti,

Thank you for submitting this issue. However, you didn't fill out the **Steps to reproduce** and the **System Status report** that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
﻿
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
﻿
**Screenshots**
If applicable, add screenshots to help explain your problem.
﻿
**Expected behavior**
A clear and concise description of what you expected to happen.
﻿
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
