### ISSUE TITLE
There is an error message which is not translated.

### ISSUE THREAD

**Issue by japanayu** [woocommerce/woocommerce#30173]
My site language is set to 'Japanese' and the following error message which is displayed when the users enter the wrong ID/password on the checkout and my account login page is not translated into Japanese and shown in English.

'ERROR: The username or password you entered is incorrect. Lost your password?'

I could not find these strings in the woocommerce-ja.po file either.

**Comment by claudiosanches** [comment]
Hello @japanayu,

Thanks for reporting this issue, but there's no string like that in WooCommerce, seems like is coming from other plugin, maybe Wordfence? https://wordpress.org/support/topic/cant-translate-error-the-username-or-password-you-entered-is-incorrect/page/2/

I'm closing for now since this isn't an issue on WooCommerce.

**Comment by japanayu** [comment]
Hi, @claudiosanches
I've just found that it came from WordFence and was going to delete the issue.
So sorry about this and thank you for your support.
