### ISSUE TITLE
inconsistent price and total value in order vs API

### ISSUE THREAD

**Issue by Morph21** [woocommerce/woocommerce#30197]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Prices of one row and total are not displayed properly.

Here is an example of one order with product which on the admin page is displayed as 14,63zł with quantity of 2 and total 29,27zł
On the other hand when im using API to get this product i get rounded total and exact price.
Anyway 14.63 times 2 is not equal to 29.27.

![image](https://user-images.githubusercontent.com/38075691/124117635-a9821900-da70-11eb-8933-7456b18cc07c.png)
![image](https://user-images.githubusercontent.com/38075691/124117892-f36aff00-da70-11eb-9da4-bf8aded28405.png)

**Expected behavior**
I'm expecting that prices should be consistent between API and Website.
If we have price 14.634 it should be rounded first to 14.63 and then multiply by quantity should occur so the total should be 29.26. My statement is based on that if we would buy only one product then price would be 14.63 

**Actual behavior**
Inconsistent values, not proper rounding

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add product with value 14.634
2. Create new order
3. Add created product with quantity of 2

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Wordpress version: 5.7.2
Woocommerce version: 5.4.1

**Comment by tammullen** [comment]
Hi @Morph21 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team to confirm if this is the expected behavior. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 
​
Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
Hi @Morph21. What API endpoint are you using exactly? We need to know in order to troubleshoot the issue.

**Comment by Morph21** [comment]
Hi @Konamiman I'm using /wp-json/wc/v3/orders

**Comment by roykho** [comment]
Hi @Morph21 - so we have discussed this within the team and concluded that it is actually a feature to show the raw value that was entered and have that as a response from the REST API endpoint.

What we suggest you can do is to round it up after you get the response so that it would match what you see in the admin screen.

Thank you for reporting we really appreciated. We will close this for now however if you have other insights please feel free to comment back this issue and we can reassess.
