### ISSUE TITLE
Checkout columns misaligned when adding a coupon code in checkout

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#30209]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The  columns of the checkout layout are condensed and display on half the page after you reveal the coupon form

**Expected behavior**
the layout should not be impacted and the billing details and your order overview should be full-width

**Actual behavior**
The width of the billing details and order overview are reduced

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a product to the cart
2. Go to checkout
3. click "click here to enter your coupon"

**Screenshots**
![Screen Recording 2021-07-03 at 08 52 33 27 AM](https://user-images.githubusercontent.com/507025/124358183-60e76e80-dbdc-11eb-9e26-2efd0001213b.gif)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @helgatheviking,

Thank you for taking the time to report this bug, we really appreciate your help. I am seeing a slightly different behavior when trying to apply the coupon using the Twenty Twenty theme but it looks like it may be related to what you are seeing. 

Tested using:
- WooCommerce 5.5 RC2
- Twenty Twenty 1.7

**Twenty Twenty v 1.7 - screencast of me trying to apply the coupon at checkout:**

https://user-images.githubusercontent.com/19143190/125122380-55f07a80-e0c3-11eb-842d-080d9e418735.mov

**Twenty Twenty One v 1.3 - everything is working as expected:**

https://user-images.githubusercontent.com/19143190/125122506-8506ec00-e0c3-11eb-95fc-96dd5b89e67c.mov

The issue seems to be specific to the Twenty Twenty theme here. 

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.
