### ISSUE TITLE
Hide product tag cloud widget title

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#30207]
Hello,

Why it is not possible to leave products tag cloud widget title just empty ?
When I leave empty input for other widget for ex. product categories then title of this widget just not showing.

http://prntscr.com/189dcuq frontend
http://prntscr.com/189dihx backend
1,3 - with titles
2,4 - without titles

Storefront theme tested !
You may simply check on your localhost and see the same result !

The same issue was reprodused by your team member from wordpress support -> https://wordpress.org/support/topic/hide-product-tags-title/#post-14626056

Regards, Stas

**Comment by juliaamosova** [comment]
Hi @Stas0238,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 5.5 RC2. 

![widgets](https://user-images.githubusercontent.com/19143190/125130640-555de100-e0cf-11eb-99d5-7b7e6917da1f.png)

![widgets2](https://user-images.githubusercontent.com/19143190/125130653-58f16800-e0cf-11eb-83e2-147de86f1c0a.png)

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by vedanshujain** [comment]
Looks like this is because [we set a default title](https://github.com/woocommerce/woocommerce/blob/trunk/includes/widgets/class-wc-widget-product-tag-cloud.php#L48) for this widget. While the suggestion makes sense, unfortunately, we won't be able to implement it because it may cause backward compatibility issues for many shops (like suddenly title going away which was there earlier). 

If you want an empty title, use this string `&nbsp;` which is code for non-breaking space characters and can be a substitute for empty title.

**Comment by Stas0238** [comment]
@vedanshujain Thanks for your answer but it is not perfect as you can find on next screenshots :
http://prntscr.com/1d4ohzo - empty title but border exists (it is only if storefront theme but I worked for others teams and know that there could be even switcher for open/close widget icon )
http://prntscr.com/1d4owwa - extra empty space not best here 

One of ideas is to check this `&nbsp;` inside [title conditions you set](https://github.com/woocommerce/woocommerce/blob/trunk/includes/widgets/class-wc-widget-product-tag-cloud.php#L48) so that your solution will work ok and no title will be shown there as it should if not set.

Regards, @Stas0238

**Comment by vedanshujain** [comment]
I agree with your suggestion, but as I said above we won't be able to implement it because it will cause backward compatible issues for many sites.
Looking in more detail, seems like the filter `widget_title` [defined in base class](https://github.com/woocommerce/woocommerce/blob/58e6d8c1837782b3708ea191eb194f9d1ba1dde9/includes/abstracts/abstract-wc-widget.php#L165) could work for your use case. Can you give it a shot?

**Comment by Stas0238** [comment]
@vedanshujain 
Maybe It was a good shot but it's still a bug in my opinion, because why it should be modified by child-theme or even parent theme if it could be simply fixed from your side.
Anyway you can close this task.
Regards, @Stas0238
