### ISSUE TITLE
WooCommerce Pre-Order 1..5.30 Fatal Error after changeing order status from preorder to cancel in WP admin

### ISSUE THREAD

**Issue by sreeram62** [woocommerce/woocommerce#30219]
I am facing an issue when changing order status from Pre Order to cancelled.

It throws an fatal error "plugins/woocommerce-pre-orders/includes/admin/class-wc-pre-orders-admin.php. Error message: Cannot declare class WC_Pre_Orders_Admin, because the name is already in use"

**Steps to reproduce:**
1.  Initally place a pre order.
2. Login to WP admin
3. Try changing the order from "Pre Order" to "Cancelled"
4. We get a fatal error.

**Comment by juliaamosova** [comment]
Hi @sreeram62,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the WooCommerce Pre-Order plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce support team by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/). 

One of the support agents will be able to confirm the issue with you and file a bug with the developers of the plugin.
