### ISSUE TITLE
Duplicate orders created

### ISSUE THREAD

**Issue by opeyemi-jonah** [woocommerce/woocommerce#30224]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60982863/124607490-232c5500-de2b-11eb-8811-5d8a97ed2613.png)

I use the WooCommerce Subscription importer to import users from a different system and when it was time for renewal which defaulted to manual renewal, multiple orders with 0 items were charged to each subscriber.

**Comment by juliaamosova** [comment]
Hi @opeyemi-jonah,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
