### ISSUE TITLE
Session data stored for wrong user

### ISSUE THREAD

**Issue by WebMedic-X** [woocommerce/woocommerce#30237]
Hi,

We are using WooCommerce session set (woocommerce->session->set()) to store a unique ID.

It happens that even though 2 users start with 2 unique IDs, at one point the session stores one of their IDs in both sessions.

The 2 users are completely different website visitors.

The rest of their session data is still good, meaning their cart details / other data in the session is still their own unique version. 

But for some reason the data we added got mixed up and now its in both the users session as the same ID instead of each having their own unique ID.

This doesn't happen to all users, only a few.

Any idea what could be causing this?

Thank you

**Comment by juliaamosova** [comment]
Hi @WebMedic-X,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by WebMedic-X** [comment]
Found out the issue was due to cache.

Cached pages containing the unique ID is served to visitors where the same ID then attaches to them.

Fix was to only add the unique ID on the pages we know are not cached, like shop, product pages, checkout etc.
