### ISSUE TITLE
Product Archive Not break down in row

### ISSUE THREAD

**Issue by 3dxchatstore** [woocommerce/woocommerce#30245]
Recently i have find out the Product Archive bug, which whenever you put a shortcode [products] in elementor, it show all products in 1 row only. No matter how we tried to Woocommerce shortcode by putting the column 4, it still show in 1 row. 

We also go into Customize > Woocommerce > Archieve to change the Shop Column and Product per page it also turn out to be this problem. 

Here is the screenshot : https://prnt.sc/19pdh3u

My Website now is looking normal, but if i now edit my website any page, the product archive will exist again. So i am not changing anything now and wait the product archive bug is solved. 

If you needed my login credential to see the problem, please do let me know

Thank you!

**Comment by juliaamosova** [comment]
Hi @3dxchatstore,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
