### ISSUE TITLE
Variations stuck on loading none stop

### ISSUE THREAD

**Issue by joyeenteng** [woocommerce/woocommerce#30257]
![image](https://user-images.githubusercontent.com/46899046/125228777-fdf68580-e307-11eb-99d2-d705865249f6.png)

I got this error in my log.

2021-07-12T00:50:48+00:00 CRITICAL Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/app/current/wp-content/themes/woodmart/inc/integrations/woocommerce/modules/variation-gallery-new.php:83
Stack trace:
#0 /var/app/current/wp-content/themes/woodmart/inc/integrations/woocommerce/modules/variation-gallery-new.php(83): implode(',', '')
#1 /var/app/current/wp-includes/class-wp-hook.php(292): woodmart_avi_admin_html(0, Array, Object(WP_Post))
#2 /var/app/current/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#3 /var/app/current/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /var/app/current/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php(108): do_action('woocommerce_var...', 0, Array, Object(WP_Post))
#5 /var/app/current/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(721): include('/var/app/curren...')
#6 /var/app/current/wp-includes/class-wp-hook.php(292): WC_AJAX::add_variation('')
#7 /var/app/current/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#8 /var/app/current/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#9 /var/app/current/wp-admin/admin-ajax.php(187): do_action('wp_ajax_woocomm...')
#10 {main}
  thrown in /var/app/current/wp-content/themes/woodmart/inc/integrations/woocommerce/modules/variation-gallery-new.php on line 83

**Comment by rodelgc** [comment]
Hi @joyeenteng,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. 

I can confirm from our end that the Variations section is loading fine as you can see below:
<img width="624" alt="Screen Shot 2021-07-14 at 3 41 01 PM" src="https://user-images.githubusercontent.com/4509348/125583081-156afd88-b0b4-4ad4-9e11-46996fb68b86.png">

Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
