### ISSUE TITLE
Products descriptions Problem

### ISSUE THREAD

**Issue by Mohamedelsehemy** [woocommerce/woocommerce#30262]
I am using woocomerce plugin and urna theme

Recently I cleared a problem with the description of the products
All products with more than one description line now contain the letter " n "

please check the website

Site URL : https://maarkety.com/

**Comment by rodelgc** [comment]
Hi @Mohamedelsehemy,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

I can see the "n" in one of the product descriptions in your site:
<img width="824" alt="Screen Shot 2021-07-14 at 3 50 00 PM" src="https://user-images.githubusercontent.com/4509348/125586421-e7188601-4253-4a88-bd89-a2edc0107405.png">

However, this issue is not happening in one of our pre-included themes, for example the Twenty Twenty-One theme shown below:
<img width="886" alt="Screen Shot 2021-07-14 at 3 51 43 PM" src="https://user-images.githubusercontent.com/4509348/125586525-c4bc14f3-cf08-4030-b836-ca6baf161347.png">


Therefore, the issue you are having seems to be caused by the 3rd party theme "Urna". 

Please contact the author of the plugin directly for further help.
