### ISSUE TITLE
Unable to register namespaced Payment Gateways

### ISSUE THREAD

**Issue by zakalwe2016** [woocommerce/woocommerce#30276]
**Describe the solution you'd like**
When registering a payment gateway using `woocommerce_payment_gateways`, the returned array is checked to see if the class implements `WC_Payment_Gateway` 

https://github.com/woocommerce/woocommerce/blob/9398c894c943524928d5b181eaeba9b44eb7a8ad/includes/class-wc-payment-gateways.php#L98

This returns false given:

```
namespace Vendor\Package\PaymentGateways;

class My_Payment_Gateway extends \WC_Payment_Gateway
{....

```
I use composer to organise plugin code and in this case, I have to take the gateway out of my namespaced code in order for WooCommerce to register it.

**Describe alternatives you've considered**

Simple solution *possibly* is to prefix the check with `\` to indicate that the check is referring to `WC_Payment_Gateway` in the global scope.

`if ( ! is_a( $gateway, '\WC_Payment_Gateway' ) ) {`

On a more general note - is there a reason why WooCommerce classes are not namespaced?

**Comment by rodelgc** [comment]
Hi @zakalwe2016,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @zakalwe2016,

We'd like to understand this better but can't quite see the problem. For instance, given a custom payment gateway defined as follows (obviously, this is very minimal and just for the sake of poking at this issue):

```php
namespace Cash {
	class Money extends \WC_Payment_Gateway {}
}
```

And given the following code to register it:

```php
add_filter( 'woocommerce_payment_gateways', function ( $gateways ) {
	$gateways[] = Cash\Money::class;
	return $gateways;
} );
```

There is no problem—the [condition you referred to](https://github.com/woocommerce/woocommerce/blob/9398c894c943524928d5b181eaeba9b44eb7a8ad/includes/class-wc-payment-gateways.php#L98) is not met (because the instance of our gateway is recognized as being of type `WC_Payment_Gateway`) and so registration is successful.

Are you able to distill the problem down to a minimal snippet that will let us see the same problem you have described?
