### ISSUE TITLE
Automatic update to non-existant version

### ISSUE THREAD

**Issue by Mulugruntz** [woocommerce/woocommerce#30283]
Hi,

We had an automatic update of WooCommerce from 5.4.1 to 5.4.2 at 06:02 UTC+0 today.

2 weird things:

- Our auto-updates are disabled, but it still forced the update.
- Version 5.4.2 does not exist.

Is there a security breach on WooCommerce side?

We noticed it because 5.4.1 has a bug there:
https://github.com/woocommerce/woocommerce/blob/5.4.1/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php#L643

And I manually modified the file to fix it a month ago. And today, it got reinitialised with 5.4.2 version (whatever it is), which contains the bug from 5.4.1.

So, this raises the question... was this update initialised by the official WooCommerce team? Or was it maliciously done by another party?

![image](https://user-images.githubusercontent.com/13810199/125782440-88421dc2-f806-4885-9415-25dffd164a13.png)

**Comment by tammullen** [comment]
Hi @Mulugruntz,

Thanks for question, this update happened due to this https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/.

We provided the patch to WordPress.org and automatic software updates are rolling out now to all stores running impacted versions of each plugin.

5.4.2 is the patched version.

If you experience any issues with this, feel free to contact one of our Happiness Engineers here: https://woocommerce.com/my-account/create-a-ticket/

**Comment by Mulugruntz** [comment]
Thank you @tammullen for your quick response.

Will the 5.4.2 (and other related versions) tag and commits be available on GitHub once all the dust settles?

Regards.

**Comment by tammullen** [comment]
Thanks @Mulugruntz, yes we will also be uploading all the patches on GitHub soon, we don't have an exact ETA for that just yet.
