### ISSUE TITLE
Redirect to page using Downloadable Products is broken since 5.5.1/5.5.0 (download_file_redirect/download_file_force)

### ISSUE THREAD

**Issue by kgosciniak-insys** [woocommerce/woocommerce#30288]
Hello,

I couldn't find anywhere if this change is intended or not (WooCommerce 5.5.1 changelog is not published). There is nothing on 5.5.0 changelog https://github.com/woocommerce/woocommerce/blob/release/5.5/changelog.txt#L3-L185
Before 5.5.1 you could use "Force download" for products and it will fallback to download_file_redirect if file was remote or not found on server.

Commit that changed this behavior:
https://github.com/woocommerce/woocommerce/commit/f88586eb1f040b81a73a62f183aa7084dccfdbc5

This is breaking change, because if you run store with "mixed" files from cloud and local and some redirects to pages, now your redirects to pages are downloading htmls, instead of redirecting.

Maybe there should be another download option "Mixed" or something that will allow to have both benefits of forced download and redirect. Or maybe you should be able to specify it on each downloadable product

**Comment by zhongruige** [comment]
Hi @kgosciniak-insys,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by AllenFreeman** [comment]
I posted this same issue to woocommerce support yesterday:
https://wordpress.org/support/topic/file-not-found-error-for-downloadable-product-orders/

To me, changing/adding new Force Download options is secondary to fixing the more urgent issue of the broken X-Accel-Redirect/X-Sendfile option. It's a business killer...

**Comment by barryhughes** [comment]
@AllenFreeman—I added a note [in the thread you linked to](https://wordpress.org/support/topic/file-not-found-error-for-downloadable-product-orders/page/2/#post-14665422). In your case, if you had been using X-Accel as your preferred method but actually your web server was never configured to support that (I think you noted that the _functionality worked perfectly for years without the suggested apache module installed on our server)_ then it has actually been using the Redirect Method for all that time (up until this most recent release)...it perhaps just was not obvious. 

That to say, as far as we know, the Accel-Redirect/X-Sendfile option is not 'broken'. Your webserver (ie, Apache) does need to be configured appropriately for it to work, though, and that isn't something that WooCommerce can realistically do on your behalf.

**Comment by barryhughes** [comment]
@kgosciniak-insys—thanks for creating this. That particular scenario where you effectively require the previous chain of fallbacks is an interesting one (and now you raise it, I can see it being particularly valid in some scenarios such as a multi-vendor marketplace). 

> Maybe there should be another download option "Mixed" or something

That could be an attractive option. We're just talking this through, bear with us :+1:

**Comment by AllenFreeman** [comment]
Thanks for the reply Barry. My host is reviewing your post on the WP support page and the linked woo page for the xsendfile download setup now, to make sure it is configured correctly. I should know what's what in a few minutes.

But a question: if the Redirect Method was being used "downstream" by default, why didn't the links created to download a product show the end URL? (Or is that where the problem now lies, that the link is a key instead of a URL so none of the options work?)

**Comment by barryhughes** [comment]
> But a question: if the Redirect Method was being used "downstream" by default, why didn't the links created to download a product show the end URL?

If I'm misunderstanding your question let me know, but if you specifically mean the links you see on the **My Account ▸ Downloads** page then it's worth noting that, even if Redirect Only is selected, these follow the same standard form. 

It's only when a customer actually follows one of those links that a redirect will take place (when appropriate/if allowed) and, if that happens, that is when the 'source URL' of the digital asset is exposed.

> Also, our .zip file downloads are hosted in a subdomain (software.) with only the URL of the file entered into File URL field in each woo Simple Product (no other encoding on the link). Is that okay?

Yes, that's fine and is supported. However, it can be tricky to support this with the X-Accel/Sendfile method. 

Similarly, it is entirely possible to use this with the Force Download method but your server's PHP configuration needs to allow for this, more details over here (including some notable exceptions):

[docs.woocommerce.com/document/digital-downloadable-product-handling](https://docs.woocommerce.com/document/digital-downloadable-product-handling/)

**Comment by AllenFreeman** [comment]
So by installing the apache xsendfile mod to the server and putting the download files directly into the woo media folders instead of serving them from a subdomain, X-Accel/Sendfile method is now working. Thanks Barry.

**Comment by barryhughes** [comment]
Excellent, I'm happy to hear that (though, of course, sorry for the disruption that took place).

**Comment by kgosciniak-insys** [comment]
> > Maybe there should be another download option "Mixed" or something
> 
> That could be an attractive option. We're just talking this through, bear with us

Thanks for looking into this topic. Maybe adding a checkbox to optionally allow fallback will be good idea?

**Comment by mzpack** [comment]
WooCommerce 5.5.1
It downloads nothing if a link is set to a site page. I can see File not found Go to shop

**Comment by barryhughes** [comment]
> It downloads nothing if a link is set to a site page.

@mzpack can you clarify what you mean—are you literally using something like `https://example.com/sample-page` (where that is a regular page on your site) as a download URL?

**Comment by mzpack** [comment]
> @mzpack can you clarify what you mean—are you literally using something like `https://example.com/sample-page` (where that is a regular page on your site) as a download URL?

Yes, I use something like that. It works previously with WooComm 4.x.x

**Comment by barryhughes** [comment]
OK. "Redirect Only" should support that workflow (at least as a possible temporary workaround) and we're looking into a better long-term solution.

**Comment by mzpack** [comment]
> OK. "Redirect Only" should support that workflow (at least as a possible temporary workaround) and we're looking into a better long-term solution.

@barryhughes
That works. Thank you.

**Comment by philbearman** [comment]
Just to add a detail in case it helps locate the problem:

I'm experiencing exactly the same thing since upgrading to 5.5.1 yesterday.  But my files are served via Amazon S3 using the Woocommerce Amazon S3 plugin.

**Comment by KateMP** [comment]
@philbearman I am also using Amazon storage and was using the force download setting. Similarly, neither force download or x-accel settings work anymore.

**Comment by apmwebdev** [comment]
Seeing some more reports of this issue, e.g. 4153391-zen and 25934250-hc. Created a snippet for it, described here: p6YafG-JU-p2

**Comment by stephhjacq** [comment]
Another report in 4160426-zen affecting Amazon S3

**Comment by barryhughes** [comment]
Regarding S3, afaik the problem is *essentially* the same and in most cases switching to *Redirect Only* will be a suitable workaround until we release a fix. There is actually less risk when selecting *Redirect Only,* in the case of S3, because the source URL is valid for one minute (one minute is the default, but this is configurable) and then expires.

**Comment by streamworksaudio** [comment]
> Regarding S3, afaik the problem is _essentially_ the same and in most cases switching to _Redirect Only_ will be a suitable workaround until we release a fix. There is actually less risk when selecting _Redirect Only,_ in the case of S3, because the source URL is valid for one minute (one minute is the default, but this is configurable) and then expires.

We too use URLs as the download link to a custom post type that run security checks then redirects to a signed temp URL on Cloudfront.  I did change it to Redirect Only and that is now working.  As this method is depreciated (and we get the warning) is this a temp. workaround?

**Comment by barryhughes** [comment]
> As this method is depreciated (and we get the warning) is this a temp. workaround?

Correct!

Our current plan is to introduce a new setting (a checkbox, in the Product Downloads settings) that can be enabled to *optionally* restore the pre-5.5.0 behavior. We did it this way because:

* We don't want redirects to happen 'silently' (without the merchant's knowledge), as this can expose digital assets in an undesirable way. In other words: serving files via redirects should be a deliberate decision.
* Additionally, it's apparent there are cases where having Force Download (for example) as first choice with redirects as a fallback is genuinely useful and is exactly what some merchants need (such as if they serve assets from a range of platforms/locations, where some are amenable to force download and others not).

**Comment by KateMP** [comment]
Any updates on when woocommerce might have a fix or update?

**Comment by barryhughes** [comment]
Yes—our 5.5.2 release contained an update directed toward this problem and we've also updated the plugin docs:

🗞️ [Developer Advisory](https://developer.woocommerce.com/2021/07/28/developer-advisory-new-download-handling-may-cause-errors/) 

📖 [Docs for Digital/Downloadable Product Handling](https://docs.woocommerce.com/document/digital-downloadable-product-handling/)

In essence, you can now select _X-Accel-Redirect_ or _Force Downloads_ and get back the same behavior as existed before 5.5.0 by enabling the new _Allow using redirect mode (insecure) as a last resort_ setting. Additionally, each time a fallback is used (for instance if you have selected Force Downloads but a file needs to be served using a redirect), a warning will be logged to help merchants identify potentially problematic downloadables.

**Comment by KateMP** [comment]
This hasn't worked for me. It's still using redirect mode regardless. I am servicing from Amazon storage. Is this part of the issue?

**Comment by barryhughes** [comment]
Hi @KateMP,

If before 5.5.0 you had selected either the Force Download or X-Accel-Redirect method, and with our current release (5.5.2) you use either of those **with** the new _"allow using redirect mode (insecure) as a last resort"_ setting enabled, then the behavior should be exactly the same as it used to be.

Those things being true, some possibilities to explain what you are experiencing:

- Perhaps it always behaved this way with S3 downloads and you simply didn't notice (prior to the issues introduced by 5.5.0 prompting you to look at this)?
- Perhaps something changed on the server where you host WordPress and WooCommerce (for instance, perhaps the `allow_url_fopen` setting changed)?
- You note using Amazon storage, perhaps something changed their in terms of permissions or the access policy for individual files or buckets was modified?

For those last two points, you may not have explicitly changed anything yourself: the service provider may have introduced changes.

Since this issue is closed, though, I'd recommend the following:

- If you are using the [Amazon S3 Storage](https://docs.woocommerce.com/document/amazon-s3-storage/) extension, start with a new support ticket. Right now I don't think this is a problem with WooCommerce core, but the team can help you troubleshoot further. If necessary, we can always create a **new** issue here on GitHub.
    - Also note that, in general, redirects with this solution (S3) should be far more secure than redirects generally are: see docs at the above link regarding _"URL Valid Period"_ to learn more about this.
- Perform a test by creating a new downloadable product that is uploaded directly to your WordPress site: is the behavior with this (non-S3 served) asset what you would expect?
    - You can also get a picture of what is happening if you look at the logs made available via the **WooCommerce ▸ Status ▸ Logs** screen. Look for entries such as _"WARNING some.url/asset.pdf could not be served using the Force Download method. A redirect will be used instead."_

**Comment by KateMP** [comment]
@barryhughes  thank you for the reply.
The downloads are defaulting to redirect and the URL of the source is showing. This is what concerns me. Previously, the files would just download, rather than opening in a browser window as they do now.  I'm not much of a techie, I've sought advice on the matter and have been told that I just need to wait for woocommerce to fix the issue, but it doesn't sound like that's the case here...

**Comment by KateMP** [comment]
Oh also, I was previously using 'force downloads' method.

**Comment by barryhughes** [comment]
> The downloads are defaulting to redirect and the URL of the source is showing. This is what concerns me.

Understood! Again, though, this is typically less of a problem with S3—because the period in which URLs are valid is, by default, on the low side. [See docs here.](https://docs.woocommerce.com/document/amazon-s3-storage/)

> I just need to wait for woocommerce to fix the issue, but it doesn't sound like that's the case here...

Right now—as of the 5.5.2 release—there doesn't appear to be a problem in core (or, there isn't enough information for me to think that's the case). It sounds like your concerns are specific to the [Amazon S3 Storage](https://woocommerce.com/products/amazon-s3-storage/) extension and so I'd recommend contacting the support team for specific guidance about that product, as this issue tracker is only concerned with WooCommerce core. 

If you are already actively talking to them, please feel free to reference this and my last reply to make sure they have context.
