### ISSUE TITLE
Divi Theme Builder Search template

### ISSUE THREAD

**Issue by diviengine** [woocommerce/woocommerce#30298]
On the latest update, the theme builder template from Divi is not working well with the search results.

For example: domain.com/?s=shirt&post_type=product - does not work

if you search: domain.com/?s=shirt - works
domain.com/?s=shirt&post_type=post - works

BUT not product

I tested a old version of WooCommerce and it works

Was there something changed in the code and the way the search results template is processed?

**Comment by myhope8729** [comment]
Hello WooCommerce team.

I found the reason of this issue.

Issue is on includes/class-wc-query.php.

**Comment by wayheming** [comment]
Same issue with another theme.

**Comment by wayheming** [comment]
@Konamiman Hello, could you please check as the code from your commit?

**Comment by squibsy** [comment]
I can confirm that the code from @myhope8729 works for Divi at least as a temporary solution until the patch is released.

**Comment by diviengine** [comment]
Yes we have written about this here in case anyone wants to download the file: https://diviengine.com/woocommerce-5-5-1-issue-with-divi-search/

**Comment by rodelgc** [comment]
Hi @diviengine ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by Konamiman** [comment]
I see. I extended the previous handling of  the `posts_clauses` hook to do more stuff besides just calling `price_filter_post_clauses`, but forgot to notice that that handling should happen only on the main query. Yes, the solution suggested by @myhope8729 seems good.

**Comment by wayheming** [comment]
@Konamiman solution from @myhope8729 not working for Woodmart theme only removing this lines resolve problem
```php
$search = $this->get_main_search_query_sql();
if ( $search ) {
	$args['where'] .= ' AND ' . $search;
}
```

**Comment by lgladdy** [comment]
This is also affecting Advanced Custom Fields plugin users who output fields on a search results page.

**Comment by Konamiman** [comment]
Hi @diviengine and @wayheming. We are going to release WooCommerce 5.5.2 soon, it will include https://github.com/woocommerce/woocommerce/pull/30335 which removes that extra `where` statement (which, indeed, is not needed). We conducted internal testing but not with the theme builders you mention, could you please confirm if the fix is good?

**Comment by Konamiman** [comment]
Pinging @lgladdy for https://github.com/woocommerce/woocommerce/issues/30298#issuecomment-884783849 as well.

**Comment by wayheming** [comment]
@Konamiman Hello. Thank you very much for your promptness. Yes, removing the code will fix the problem.
