### ISSUE TITLE
Update JS script file versions

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#30290]
Props to @jkirrane for mentioning this.

We've recently updated many of our JS script files based on the jQuery migration efforts. However many of them have hardcoded versions as seen here https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-frontend-scripts.php#L174-L227

This means sites could still be using the cached versions of the script and would not have the fixes in place. We need to bust these cache anytime we update these JS script files.

We have two possible approaches here.

1. Bump the hardcoded versions by their patch version so for example `3.0.0` becomes `3.0.1`. Doing this means we have to remember to update this anytime we touch these JS files. Upside is the cache would last longer as clients won't need to refresh these scripts on each WC release if we were to use WC version.
2. Use the WC version. Using this method we don't need to think about it anymore and can rely on it to bust the cache on every WC release.

cc @jonathansadowski

**Comment by jkirrane** [comment]
For what it's worth, the default behavior of `wp_enqueue_script` if `$ver` is not included is to apply the current WordPress version number. WordPress core does not individually manage script versions in `wp-includes`, they all use the current WordPress version. My recommendation is to follow that approach but with the WooCommerce version number.

WordPress has new releases (and thus new script version numbers) about once a month. WooCommerce has a relatively similar release schedule. If it's good enough for WordPress then I think it's probably good enough for WooCommerce, too.

With all that said, I think the safest approach is to use the WooCommerce version. This will mitigate specifically against what happened to some of my sites related to the fix for [30069](https://github.com/woocommerce/woocommerce/issues/30069), where payment gateways completely failed even after the patched version of WooCommerce was deployed. I think the cost savings of maintaining version numbers for a longer period of time is outweighed by the benefit of not having to worry about this possibility.

**Comment by jkirrane** [comment]
I should add, if you look at https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-frontend-scripts.php#L229-L297 you'll see that plenty of scripts are _already_ using the current WooCommerce version for the script's version.
