### ISSUE TITLE
No way to redirect after registration without autologin

### ISSUE THREAD

**Issue by alexincore** [woocommerce/woocommerce#30315]
Prior to [this commit](https://github.com/woocommerce/woocommerce/commit/53b9e219e7bd4a9c8223701ed670fc8e6ee6c0af#diff-f5dd40c237b9af145a434c0adddac32e151339562a757b30445aaea41e6726ddR1091-R1104) there was a possibility to provide a redirect after successful registration IF the auto login was disabled. Now there's absolutely no way to do that as it never reaches the piece of code inside `if ( apply_filters( 'woocommerce_registration_auth_new_customer', true, $new_customer ) ) {`.

**Describe the solution you'd like**
A way to redirect the user to a _thank you_ page after registration, without enabling automatic login.

**Describe alternatives you've considered**
I have enabled automatic login, and am logging out the user during the registration. It's ugly, slow, and conflicts with other during the logout

**Comment by tammullen** [comment]
Hi @alexincore ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @alexincore , thanks for reporting this issue. Just to confirm, by auto-login you mean automatically login as soon as the customer is registered correct?

If so, we have the following options:
1. Hook into the `woocommerce_registration_auth_new_customer` and use this as an action to do the redirection yourself. I won't recommend this method because it means duplicating core functionality and keeping it up to date. But if I am reading this right, it can be used as a workaround.
2. Add a proper action after we are able to register the customer. Refactor the redirect logic to a different method, which can be called in the action if needed.

We cannot revert to 3.6 behavior now, as that would break the flow of several plugins that may be redirecting users to my-account page. I am marking this issue as an enhancement request for now.

**Comment by peterfabian** [comment]
Let's put this up for voting and if it gets enough traction, we can implement this. If anyone lands here and supports this idea, please give the initial post a thumbs up. Thanks!
