### ISSUE TITLE
Coupon Code text box Theme/font Conflict 

### ISSUE THREAD

**Issue by akissz** [woocommerce/woocommerce#30345]
There seems to be a conflict on the coupon code text box. Maybe the width could be widened to 120px instead of 80px, or you can write the code differently somehow so the text box looks better with more standard font types. See screen shot here to view problem. As you see the second word "code" from "Coupon code" is completely cut off in the text box...
![image](https://user-images.githubusercontent.com/23090286/126855552-78a92e4d-a124-4e7f-b928-8f332a694d8d.png)
FIX to 120px:
![image](https://user-images.githubusercontent.com/23090286/126855598-1f97daa3-9739-4f41-ac06-791ff195ec7a.png)

**Comment by calvinmorett** [comment]
Can you additional context please.

**Since this is a bug report please review and use the template, so others can reproduce the bug, and then work on a fix**: [Bug Report Issue Template](https://github.com/woocommerce/woocommerce/blob/58e6d8c1837782b3708ea191eb194f9d1ba1dde9/.github/ISSUE_TEMPLATE/4-Bug-report.md)

**Comment by akissz** [comment]
I thought the original post was self explanatory. All that is needed to reproduce the bug is use any theme besides the WP 2021 default theme!!! I just tried with 3 random themes prior to replying here and all 3 themes have the same bug!!!

**Comment by calvinmorett** [comment]
_I would love to help you, but it's not self explanatory._ 

This is why there is a Bug Report Issue Template. It's much easier to help someone when the issue is formatted in a way where anyone can first confirm that it's a bug that either everyone has, can be replicated, or if it's somehow only effecting you.

I know you need help and you might feel frustrated, but we need to start on understanding the problem, then we can work together on finding a solution.

**Comment by rodelgc** [comment]
Hi @akissz,

Thank you for submitting the issue. However, as @calvinmorett mentioned, you didn’t fill out the details of the bug report template that we ask for. What may be self-explanatory to you might not be self-explanatory to others. 

For example, I tried with the Storefront theme (as it's the theme closest to the one you used in your screenshot) but as you can see from the image below, the input box for the Coupon Code looks fine.
<img width="448" alt="Screen Shot 2021-07-28 at 4 05 49 PM" src="https://user-images.githubusercontent.com/4509348/127287366-507543f9-9247-41ae-bf6d-c23bb178c0f1.png">

Now that we cannot recreate the issue, there's this back-and-forth in our communication and a delay in resolving the issue, which could have been avoided in the first place if the details in the template were provided early on. Without these details, we can’t fully evaluate this issue. 

Again, please provide us with the information requested so we could take a look further. Here is the copy of the template:

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
