### ISSUE TITLE
Missing hook to change shipping method for "pay for order" endpoint link

### ISSUE THREAD

**Issue by harrypotter30022003** [woocommerce/woocommerce#30363]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Cant seem to call the shipping method for "pay later" order, when user click pay for order in their email, is there an option to call the shipping method hook?

Thanks

**Comment by rodelgc** [comment]
Hi @harrypotter30022003,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @harrypotter30022003,

Thanks for the report...however we're just a little unsure as to what you are describing. Our default bug report template contains the following sections:

* **Describe the bug** → A clear and concise description of what the bug is.
* **Expected behavior** → A clear and concise description of what you expected to happen.
* **Actual behavior** → A clear and concise description of what actually happens. Please be as descriptive as possible;
* **Steps to reproduce the bug** → We need to be able to reproduce the bug in order to fix it.

These sections seem to have been omitted from your report, but could be useful. Your initial report reads as if this relates to some custom code...is that the case and, inline with the last bullet (steps to reproduce) could you perhaps distill things down to some minimal snippets that will help us see the problem?

Thanks!
