### ISSUE TITLE
 [GlobalStep] On Product types screen during OBW, the Info pop up content fails to translate in the respective language.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30368]
## Bug Description:
On Product types screen during OBW, the Info pop up content fails to translate in the respective language.

## Environment:
Woocommerce Version : WooCommerce 5.6.0 Beta 1
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 89.0.2)
Safari: v14.0

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Go to General->Settings and change the site language to non-English (Eg. Espanol, Deutsche).
1. Go to Dashboard->Updates and Update the translation.
1. Go to OBW set up.
1. Go to Product types step.
1. Click on "i" button.
1. Observe that Info pop up content fails to translate.

## Actual Result:
On Product types screen during OBW, the Info pop up content fails to translate in the respective language.

## Expected Result:
The Info pop up content should get translate in the respective language.

## Screenshot:

![#30368](https://user-images.githubusercontent.com/41110392/127349667-c512ca4f-a128-4dcc-9239-0057012bd119.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @gglobalstep,

Thank you for reporting the issue. I can reproduce it on  my end:
<img width="526" alt="Screen Shot 2021-07-29 at 1 22 26 AM" src="https://user-images.githubusercontent.com/4509348/127368958-66283564-4a04-4189-a37b-3adb3388086c.png">

This is possibly related to https://github.com/woocommerce/woocommerce-admin/issues/7323.

Translations are being developed in a different repository: [woocommerce/woocommerce-admin](https://github.com/woocommerce/woocommerce-admin)

I am going to move your bug report there so that the right team could take a look further.

**Comment by rodelgc** [comment]
Issue moved to [woocommerce/woocommerce-admin #7434](https://github.com/woocommerce/woocommerce-admin/issues/7434) via [**ZenHub**](https://www.zenhub.com/)
