### ISSUE TITLE
Change coupon amount filter

### ISSUE THREAD

**Issue by AmeenJalali** [woocommerce/woocommerce#30436]
**Is your feature request related to a problem? Please describe.**
I wanted to modify the coupon amount based on cart subtotal but there is no filter to achieve that. For instance, I'd like to have 15% off for cart subtotal > $50, and 30% for subtotal > %200. 
I found `woocommerce_coupon_get_discount_amount` filter but it's for each item in the cart, not the subtotal, so it's not accurate. 

**Describe the solution you'd like**
A filter like `woocommerce_coupon_set_discount_amount` which we can easily change the coupon amount.

**Comment by juliaamosova** [comment]
Hi @AmeenJalali,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @AmeenJalali,

What inaccuracies are you seeing when calculating the subtotal within the existing filter? You should be able to sum the subtotals for each item and dynamically update the coupon amount based on that, you may just have to account for whether or not prices are inclusive of tax, and use `get_subtotal()` or `get_subtotal_tax()` as appropriate.

**Comment by jonathansadowski** [comment]
Internal discussion: p1630013301017200-slack-C0E1AV8T0
