### ISSUE TITLE
Wrong data type returned by WC()->cart->get_total() 

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [woocommerce/woocommerce#30431]
According to PHPDoc of `WC()->cart->get_total()` method:
https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-cart.php#L282-L292

It should return float, But `wc_price()` return string:
https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/wc-formatting-functions.php#L538-L575

So, `WC()->cart->get_total()` should return the float value of cart total.
It should not wrap by `wc_price()` because serve the harmony of other methods in this class like `get_subtotal()` and others.

~~I will fix this issue by pull request.~~

**Comment by AmirHosseinKarimi** [comment]
Looks like I missed up `context` parameter of `get_total()`. So it works good for backward compatibility. Awesome.
But it's not better to check the version of WooCommerce for backward compatibility instead of set view context by default?

**Comment by juliaamosova** [comment]
Hi @AmirHosseinKarimi,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @AmirHosseinKarimi,

Thanks for pointing out the confusion caused by the documentation. We'll update the PHPDoc to indicate that the return type can be either a string or a float.

One of the reasons that we're not able to do a version check in this case for compatibility is that extensions that support older versions of WooCommerce still need to know what type to expect for the response to the function. We chose to maintain backward compatibility in this case by conditioning the response on `$context`, but created some confusion in the process with the PHPDoc. Thanks for bringing that to our attention, we'll be sure to fix that soon. Stay tuned.
