### ISSUE TITLE
Add zero value for 29 Feb in non-leap years in Analytics charts

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce#32259]
**Describe the bug**
If you run an analytics report on a date range that includes February in a leap year, the chart misses the 29th of February.

This means reports such as quarterly reports, half-yearly reports, and annual reports can be affected if February 29 is present in the current year **OR** the comparison year, e.g. reports in 2024 and 2025 are affected.

Raised here - woocommerce/woocommerce-admin#6584 - discussion here - p90Yrv-2f6-p2

**To Reproduce**

1. Go to Analytics -> Revenue
2. Select "Year to date" and compare to "Previous year"
3. Update
4. The chart will include 28 Feb for both years but not 29 Feb for 2020

**Expected behavior**
A zero value should be created for 29 Feb 2021 so that the value for 29 Feb 2020 can be displayed in the chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/224531/115186594-5b25d500-a125-11eb-94fb-5e650e6a2756.png)

**Comment by chihsuan** [comment]
This has been here for a while. However, I think it would be great if we can fix this along with https://github.com/woocommerce/woocommerce-admin/issues/6822.

I believe it should be "Feb" so I changed all "April" to "Feb"  in the issue title and descriptions.

**Comment by ilyasfoo** [comment]
Reviving this issue since we're observing the bug in 29th Feb 2024 with WooCommerce 8.7-beta.1

There are two more instances where we can observe the leap year bug:

### Entire previous period data bumped down 1 day after 29th Feb

1. Download and install [wc-smooth-generator](https://github.com/woocommerce/wc-smooth-generator/releases/tag/1.1.0) plugin
2. Run the following code: <p>
```
wp wc generate orders 1 --date-start=2020-02-29 --date-end=2020-02-29 --status=completed &&
wp wc generate orders 1 --date-start=2019-02-28 --date-end=2019-02-28 --status=completed &&
wp wc generate orders 1 --date-start=2019-03-01 --date-end=2019-03-01 --status=completed
```

3. Go to `Analytics > Settings` and set `Date type` to `Date created` and save
4. Go to `Analytics > Orders` and set `Date range` to custom tab, `02/01/2020` to `03/31/2020` and update
5. Observe despite having an order dated 1st March 2019, it displays `0` in chart.

<img width="828" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3747241/04020566-a4a7-42a2-8697-76bf3ec054d1">




### ~~Previous period date range overflows~~

1. Set your system date to `2024-02-29` (example [tutorial](https://www.lifewire.com/manually-change-the-date-and-time-on-mac-2378143))
6. Go to Analytics > Orders
7. Select the `Date range` to be `Month to date` under `Preset` tab, and ensure `Compare to` is set to `Previous year`
8. Observe the previous year date range ends with `Mar 1, 2023` instead of `Feb 29, 2023`

<img width="473" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3747241/fe335d7e-1996-4b8c-9546-a31f54ddc9d3">

Edit: After some thought, I think this is actually desirable behaviour. Previous related work on this: https://github.com/woocommerce/woocommerce-admin/pull/6584

**Comment by ilyasfoo** [comment]
Closing this issue in favour of https://github.com/woocommerce/woocommerce/issues/47503
