### ISSUE TITLE
Revise menu_order system

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#5468]
When using the Default sorting (custom + name) for shop display, you can drag and drop to change menu order for products rather than using the alphabetical display. However, once this is used, there's no easy way to change the menu_order values for products. Maybe creating a tool under System Status to reset product menu_order would be appropriate for users that want to revert to alphabetical displays would be helpful.

**Comment by mikejolley** [comment]
Sorting is clunky. Let's look at ways to revise how this works, or replace it with something more automatic (a better default) and move this out of core. Sorting thousands of products via drag and drop is silly.

**Comment by mikejolley** [comment]
Closed in favour of #13072

**Comment by kaldari** [comment]
> Closed in favour of #13072

@mikejolley - Since #13072 has been closed as well, can we reopen this bug? It would be really, really handy if there were a way to reset all the product menu order values to 0. Currently the only way to do this is in the MySQL itself (https://geofffranklin.com/reset-menu_order-woocommerce-products-phpmyadmin), which is inaccessible to most admins (and rather dangerous). This should be a very simple feature to add (until the full UI redesign happens).
