### ISSUE TITLE
Select2 - update to version 4

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#7900]
Version 4.0 of Select2 is imminent for release (has reached rc2), and has some breaking changes - https://select2.github.io/announcements-4.0.html.

**Comment by shivapoudel** [comment]
@DavidAnderson684 Select2 v4.0 is not officially released. It will be updated when v4.0 is officially released xD

**Comment by claudiosmweb** [comment]
We will include only when it get a stable release.

**Comment by franticpsyx** [comment]
@claudiosmweb We might have some difficulty with ajax-powered fields, since v4 apparently dropped the hidden `input` approach. Extensions that already maintain backwards compatibility with `chosen` will have a hard time to support WC 2.3 versions with select2 v4 **alongside** WC 2.3 versions with select2 v3.5.

I'd suggest waiting until WC 2.4 before updating select2 to v4.

**Comment by claudiosmweb** [comment]
@franticpsyx Select2 v4 is for WC 2.4 ;)

**Comment by franticpsyx** [comment]
Awesome!

**Comment by helgatheviking** [comment]
Select2 v4.0 is now officially out. Looks like it's on [4.0.3](https://github.com/select2/select2/tags).

**Comment by brandomeniconi** [comment]
[Shortcode-UI](https://github.com/wp-shortcake/shortcake/) causes JS errors because ships with select2 v4 and WC can't find it's v3 methods. Please update soon :)

**Comment by mikejolley** [comment]
This is in 2.7 :) Didn't realise there was an issue.
